import type { AuthoredQuiz } from '../../advanced/shared/authoredQuiz';

// Fifteen authored questions per lesson (key = lesson number in LessonN.tsx).
export const upperInterVocabularyQuizBank: Record<number, AuthoredQuiz[]> = {
  // Lesson 1: Academic Research
  1: [
    ["The study tested the ___ that exercise improves cognitive function.", "hypothesis", ["methodology", "citation", "paradigm"], "Hypothesis adalah dugaan sementara yang diuji dalam penelitian, sehingga cocok dengan kata kerja 'tested'."],
    ["What does 'inference' mean in a research report?", "A logical conclusion drawn from evidence", ["A short summary placed before a paper", "A factor that can change during an experiment", "A reference to the source of an idea"], "Inference berarti kesimpulan logis yang ditarik dari bukti yang tersedia."],
    ["Which word names the short summary at the start of a research paper?", "Abstract", ["Citation", "Paradigm", "Variable"], "Abstract adalah ringkasan singkat di awal karya ilmiah yang dibaca untuk menilai relevansinya."],
    ["The journal only accepts articles that have passed ___ by specialists in the field.", "peer review", ["methodology", "correlation", "inference"], "Peer review adalah evaluasi karya ilmiah oleh peneliti lain sebelum diterbitkan."],
    ["The results seem to ___ the earlier study, which found the opposite effect.", "contradict", ["substantiate", "validate", "synthesise"], "Contradict berarti bertentangan, cocok karena studi sebelumnya menemukan efek yang berlawanan."],
    ["Choose the correct form: 'Her ___ of the interview data was challenged by other researchers.'", "interpretation", ["interpret", "interpretive", "interpreted"], "Setelah 'Her' dan sebelum 'of' dibutuhkan kata benda, yaitu interpretation."],
    ["Which phrasal verb is closest in meaning to 'substantiate' a claim?", "back up", ["play down", "cast doubt on", "put forward"], "Substantiate berarti mendukung klaim dengan bukti, sama dengan 'back up'."],
    ["A writer wants to admit a study's weaknesses but still praise it: '___, the study offers valuable insights.' Which opening fits?", "Despite the limitations", ["In contrast to", "Further research is needed", "This raises the question of"], "'Despite the limitations' mengakui kekurangan sekaligus menyatakan nilai positif penelitian."],
    ["Which phrase signals that a study's conclusions are not final and more work should follow?", "Further research is needed", ["Broadly speaking", "Based on evidence", "According to the findings"], "'Further research is needed' menyatakan bahwa penelitian lanjutan masih diperlukan."],
    ["Apa arti 'paradigm shift' dalam kalimat 'The discovery triggered a paradigm shift in modern biology'?", "Perubahan mendasar dalam kerangka berpikir dominan", ["Pergeseran kecil dalam jadwal penelitian", "Kesalahan dalam metode pengambilan data", "Perbedaan pendapat antara dua peneliti"], "Paradigm adalah kerangka berpikir dominan, sehingga paradigm shift berarti perubahan mendasar pada kerangka itu."],
    ["There is a strong ___ between sleep deprivation and academic performance.", "correlation", ["variable", "inference", "hypothesis"], "Correlation adalah hubungan statistik antara dua hal, dan lazim dipakai dengan 'between'."],
    ["Before writing her conclusion, she had to ___ findings from twenty studies into one coherent argument.", "synthesise", ["deduce", "contradict", "cite"], "Synthesise berarti menggabungkan informasi dari banyak sumber menjadi satu kesatuan."],
    ["Which word describes a long piece of academic writing submitted for a doctoral degree?", "Dissertation", ["Methodology", "Bibliography", "Correlation"], "Dissertation adalah karya tulis ilmiah panjang untuk meraih gelar doktor."],
    ["In 'The researchers controlled all variables', what does 'variables' refer to?", "Factors that can change and affect the result", ["Sources quoted in the reference list", "Experts who check the paper before it is published", "Questions asked in the final interview"], "Variables adalah faktor yang dapat berubah dan memengaruhi hasil percobaan."],
    ["Choose the phrase that introduces what the numbers show: '___ older participants slept less than younger ones.'", "The data suggests that", ["In contrast to", "Despite the limitations", "To a significant extent"], "'The data suggests that' diikuti klausa lengkap dan memperkenalkan temuan dari data."],
  ],

  // Lesson 2: Business & Finance
  2: [
    ["The company had to ___ its assets after declaring bankruptcy.", "liquidate", ["diversify", "allocate", "acquire"], "Liquidate berarti menjual aset untuk membayar utang, yang terjadi setelah bangkrut."],
    ["Which term refers to a share of a company's profit paid to its shareholders?", "Dividend", ["Portfolio", "Leverage", "Recession"], "Dividend adalah bagian keuntungan yang dibagikan kepada pemegang saham."],
    ["When interest rates rise, many firms delay hiring because they fear the economy is heading into a ___.", "recession", ["dividend", "portfolio", "acquisition"], "Recession adalah penurunan aktivitas ekonomi, yang membuat perusahaan menunda perekrutan."],
    ["What does 'venture capital' refer to?", "Money invested in new, high-risk companies", ["Money a government raises through taxes", "Profit shared among the company's owners", "Cash kept aside to pay for the firm's daily expenses"], "Venture capital adalah modal berisiko tinggi yang diinvestasikan di perusahaan rintisan."],
    ["To reduce the risk of losing everything, the investor decided to ___ into property, bonds and gold.", "diversify", ["streamline", "liquidate", "outsource"], "Diversify berarti menyebar investasi ke berbagai bidang untuk mengurangi risiko."],
    ["Which verb means to make a process simpler and more efficient by removing unnecessary steps?", "streamline", ["restructure", "negotiate", "forecast"], "Streamline berarti mengefisienkan proses dengan menghilangkan langkah yang tidak perlu."],
    ["After two difficult years, the café finally managed to ___ and stop losing money.", "break even", ["break down", "break out", "break up"], "Break even berarti mencapai titik impas, yaitu tidak lagi merugi."],
    ["Before buying the company, the investors spent months on ___, checking its accounts and legal risks.", "due diligence", ["market share", "cash flow", "fiscal year"], "Due diligence adalah riset menyeluruh sebelum sebuah transaksi dilakukan."],
    ["A 'blue-chip company' is best described as ...", "a large, well-established and reliable firm", ["a small start-up growing very fast", "a company that is very close to going bankrupt", "a firm owned entirely by the state"], "Blue-chip company adalah perusahaan besar yang mapan dan terpercaya."],
    ["Choose the correct form: 'The ___ of the rival firm took almost a year to complete.'", "acquisition", ["acquire", "acquiring", "acquired"], "Setelah 'The' dan sebelum 'of' dibutuhkan kata benda, yaitu acquisition."],
    ["Which word is closest in meaning to 'mitigate' in 'measures to mitigate the risk'?", "reduce", ["increase", "ignore", "measure"], "Mitigate berarti mengurangi dampak atau risiko, sama dengan 'reduce'."],
    ["The central bank lowered interest rates as part of its expansionary ___ policy.", "monetary", ["fiscal", "dividend", "portfolio"], "Kebijakan suku bunga bank sentral disebut monetary policy, bukan fiscal policy."],
    ["The government raised taxes and cut public spending. Which term describes this area of policy?", "fiscal policy", ["monetary policy", "supply chain", "market share"], "Fiscal policy adalah penggunaan pajak dan belanja pemerintah untuk mengatur ekonomi."],
    ["Who counts as a 'stakeholder' in a business?", "Anyone affected by or interested in the company", ["Only the person who owns the most shares", "An employee who manages the accounts", "A bank that lends money to the company for expansion"], "Stakeholder mencakup semua pihak yang berkepentingan atau terdampak oleh perusahaan."],
    ["Delays at the port disrupted the entire ___, leaving shops without stock.", "supply chain", ["cash flow", "bottom line", "fiscal year"], "Supply chain adalah alur dari produksi hingga konsumen, sehingga keterlambatan di pelabuhan mengganggunya."],
  ],

  // Lesson 3: Environment & Sustainability
  3: [
    ["Tropical rainforests are critical for maintaining global ___.", "biodiversity", ["emissions", "deforestation", "greenwashing"], "Biodiversity adalah keanekaragaman hayati yang dijaga oleh hutan hujan tropis."],
    ["The country pledged to reduce carbon ___ by 45% before 2030.", "emissions", ["ecosystems", "renewables", "biodiversity"], "Carbon emissions adalah pelepasan gas karbon yang ingin dikurangi."],
    ["A company advertises its plastic bottles as 'eco-friendly' while doing nothing to cut waste. This practice is called ___.", "greenwashing", ["net zero", "climate justice", "carbon neutral"], "Greenwashing adalah klaim ramah lingkungan yang menyesatkan."],
    ["Which word means 'caused by human activity'?", "Anthropogenic", ["Environmental", "Ecological", "Renewable"], "Anthropogenic berarti disebabkan oleh aktivitas manusia."],
    ["Overfishing has ___ fish stocks in the North Sea to dangerously low levels.", "depleted", ["restored", "harnessed", "recycled"], "Deplete berarti menguras sumber daya secara besar-besaran hingga hampir habis."],
    ["Engineers are building turbines to ___ the strong winds along the coast.", "harness", ["deplete", "emit", "contaminate"], "Harness berarti memanfaatkan energi alam seperti angin atau matahari."],
    ["Which phrase describes the point after which a change in the climate system can no longer be reversed?", "tipping point", ["net zero", "carbon footprint", "climate justice"], "Tipping point adalah ambang batas yang setelahnya perubahan tidak dapat dipulihkan."],
    ["Choose the correct form: 'Factories that ___ large amounts of smoke must pay a higher tax.'", "emit", ["emission", "emitting", "emissions"], "Setelah 'that' sebagai subjek klausa dibutuhkan kata kerja bentuk sekarang, yaitu emit."],
    ["Which verb is closest in meaning to 'contaminate' in 'Chemicals contaminated the river'?", "polluted", ["purified", "restored", "conserved"], "Contaminate berarti mencemari, sama dengan 'pollute'."],
    ["What is a 'circular economy'?", "A system where materials are reused and waste is avoided", ["An economy that depends mainly on oil and gas", "A system in which prices rise and fall in regular yearly cycles", "A trade network between neighbouring countries"], "Circular economy adalah sistem ekonomi tanpa limbah di mana bahan terus digunakan kembali."],
    ["A firm that removes as much carbon as it emits can describe itself as ___.", "carbon neutral", ["ecological", "renewable", "anthropogenic"], "Carbon neutral berarti tidak menambah emisi karbon bersih ke atmosfer."],
    ["Rampant ___ in the Amazon threatens global climate stability.", "deforestation", ["sustainability", "biodiversity", "conservation"], "Deforestation adalah penebangan hutan besar-besaran yang mengancam stabilitas iklim."],
    ["Which verb is the opposite of 'degrade' when talking about a damaged habitat?", "restore", ["pollute", "deplete", "emit"], "Restore berarti memulihkan, kebalikan dari degrade yang berarti menurunkan kualitas."],
    ["The oil spill caused long-lasting ___ damage to the coastal region.", "ecological", ["renewable", "sustainable", "circular"], "Ecological berkaitan dengan hubungan makhluk hidup dan lingkungannya, cocok untuk kerusakan akibat tumpahan minyak."],
    ["Which term refers to the fair sharing of the burdens of climate change between rich and poor countries?", "climate justice", ["climate change", "net zero", "ecological footprint"], "Climate justice berarti pembagian beban perubahan iklim secara adil."],
  ],

  // Lesson 4: Technology & Innovation
  4: [
    ["Social media platforms use complex ___ to curate personalised content.", "algorithms", ["encryption", "cybersecurity", "automation"], "Algorithms adalah serangkaian instruksi yang dipakai platform untuk memilih konten."],
    ["End-to-end ___ ensures that only the sender and recipient can read messages.", "encryption", ["integration", "automation", "innovation"], "Encryption adalah pengodean data sehingga hanya pihak tertentu yang dapat membacanya."],
    ["Which word describes a set of step-by-step instructions a computer follows to solve a problem?", "algorithm", ["platform", "encryption", "integration"], "Algorithm adalah serangkaian instruksi sistematis untuk menyelesaikan masalah."],
    ["'Streaming services have been disruptive to traditional broadcasting.' What does 'disruptive' mean here?", "changing an industry in a fundamental way", ["making a product slightly cheaper", "protecting data from hackers", "copying a rival's most successful product exactly"], "Disruptive berarti mengubah atau merevolusi sebuah industri secara mendasar."],
    ["Which word means the protection of computer systems and networks from digital attacks?", "Cybersecurity", ["Integration", "Automation", "Innovation"], "Cybersecurity adalah perlindungan sistem digital dari serangan."],
    ["Choose the correct form: 'The company's ability to ___ quickly has kept it ahead of its rivals.'", "innovate", ["innovation", "innovative", "innovatively"], "Setelah 'to' dibutuhkan kata kerja dasar, yaitu innovate."],
    ["The bank replaced most of its cashiers with machines; this ___ cut costs but led to job losses.", "automation", ["encryption", "integration", "scalability"], "Automation adalah penggantian kerja manusia dengan mesin."],
    ["Which noun follows 'digital' to describe a service, such as an online marketplace, that connects users?", "platform", ["encryption", "automation", "innovation"], "Digital platform adalah infrastruktur digital yang menghubungkan para penggunanya."],
    ["The new app allows smooth ___ with the hospital's existing booking system.", "integration", ["innovation", "encryption", "automation"], "Integration berarti penggabungan sistem secara mulus dengan sistem yang sudah ada."],
    ["A hospital chatbot that diagnoses skin conditions from photos is an example of ___ in healthcare.", "artificial intelligence", ["cybersecurity", "encryption", "integration"], "Artificial intelligence adalah mesin yang meniru kecerdasan manusia, misalnya untuk mendiagnosis."],
    ["Which word is closest in meaning to 'disruptive' in 'a disruptive innovation'?", "groundbreaking", ["conventional", "gradual", "predictable"], "Disruptive innovation mengubah industri secara mendasar, sehingga paling dekat dengan 'groundbreaking'."],
    ["Continuous ___ is essential to remain competitive in the tech sector.", "innovation", ["encryption", "platform", "cybersecurity"], "Innovation adalah pengenalan ide atau produk baru yang diperlukan agar tetap kompetitif."],
    ["Which is the adjective from 'scale' that means 'able to be expanded easily'?", "scalable", ["scaling", "scaled", "scaly"], "Scalable berarti mampu diperbesar tanpa kehilangan efisiensi."],
    ["In 'the integration of AI into existing workflows', 'integration' means ...", "combining it smoothly with what is already there", ["removing it from the old system", "testing it in a separate laboratory before launch", "selling it to another company"], "Integration berarti menggabungkan sesuatu secara mulus ke dalam sistem yang sudah ada."],
    ["The startup built a ___ solution that could serve ten users or ten million without slowing down.", "scalable", ["disruptive", "encrypted", "automated"], "Scalable menggambarkan solusi yang tetap efisien meski jumlah pengguna bertambah besar."],
  ],

  // Lesson 5: Health & Medicine
  5: [
    ["Early ___ is critical for improving outcomes in cancer treatment.", "diagnosis", ["epidemic", "pathogen", "heredity"], "Diagnosis adalah identifikasi penyakit, dan diagnosis dini meningkatkan hasil pengobatan."],
    ["Which word means a doctor's prediction of how a disease is likely to develop?", "prognosis", ["diagnosis", "intervention", "therapy"], "Prognosis adalah prediksi perjalanan suatu penyakit."],
    ["A doctor first identifies the illness and then says how it will probably progress. These two steps are ___.", "diagnosis, then prognosis", ["prognosis, then diagnosis", "intervention, then diagnosis", "prognosis, then intervention"], "Diagnosis mengidentifikasi penyakit, lalu prognosis memprediksi perkembangannya."],
    ["Which adjective describes a condition that lasts for a long time or keeps coming back?", "chronic", ["acute", "hereditary", "therapeutic"], "Chronic berarti berlangsung lama dan terus-menerus, berlawanan dengan acute."],
    ["Choose the correct form: 'All children in the village were ___ against measles last year.'", "immunised", ["immunity", "immune", "immunising"], "Setelah 'were' dibutuhkan bentuk pasif, yaitu immunised."],
    ["Palliative care focuses on ...", "relieving symptoms rather than curing the disease", ["finding the exact cause of a disease", "preventing infections with vaccines", "curing patients completely through major surgery"], "Palliative care bertujuan meringankan gejala dan meningkatkan kualitas hidup, bukan menyembuhkan."],
    ["The ___ responsible for the outbreak was identified within 48 hours.", "pathogen", ["prognosis", "intervention", "diagnosis"], "Pathogen adalah mikroorganisme penyebab penyakit, sehingga dapat bertanggung jawab atas wabah."],
    ["Which word describes a disease passed down from parents to children through genes?", "hereditary", ["chronic", "contagious", "therapeutic"], "Hereditary berarti diwariskan melalui gen, sedangkan contagious berarti menular antarorang."],
    ["When the virus spread rapidly to twelve cities, officials announced that the country was facing a serious ___.", "epidemic", ["immunity", "remedy", "therapy"], "Epidemic adalah wabah penyakit yang menyebar luas di suatu komunitas."],
    ["Swimming has a ___ effect on people recovering from back injuries, helping them heal.", "therapeutic", ["hereditary", "chronic", "pathogenic"], "Therapeutic berarti bersifat menyembuhkan atau mengobati."],
    ["Early ___ programmes significantly reduce the impact of developmental disorders.", "intervention", ["prognosis", "epidemic", "pathogen"], "Intervention adalah tindakan untuk mengubah kondisi kesehatan sejak dini."],
    ["Apa arti 'chronic stress' dalam 'Chronic stress has been linked to heart disease'?", "Stres yang berlangsung lama dan terus-menerus", ["Stres ringan yang cepat hilang", "Stres yang dialami saat ujian saja", "Stres karena penyakit yang menular"], "Chronic berarti berlangsung lama dan terus-menerus."],
    ["Choose the correct form: 'Doctors could not ___ the illness until the test results arrived.'", "diagnose", ["diagnosis", "diagnostic", "diagnosed"], "Setelah 'could not' dibutuhkan kata kerja dasar, yaitu diagnose."],
    ["Which adjective goes with 'care' to mean treatment that makes terminally ill patients more comfortable?", "palliative", ["pathogenic", "hereditary", "epidemic"], "Palliative care adalah perawatan yang meringankan penderitaan pasien yang sakit parah."],
    ["Which word is closest in meaning to 'pathogen'?", "germ", ["vaccine", "symptom", "antibody"], "Pathogen adalah mikroorganisme penyebab penyakit, sama dengan 'germ'."],
  ],

  // Lesson 6: Politics & Society
  6: [
    ["A ___ government was formed after no party achieved a majority.", "coalition", ["populist", "referendum", "censorship"], "Coalition adalah aliansi partai yang membentuk pemerintahan ketika tidak ada partai yang menang mayoritas."],
    ["Which word means a direct vote in which all citizens decide on a single question?", "referendum", ["election", "coalition", "legislature"], "Referendum adalah pemungutan suara langsung oleh rakyat tentang satu isu."],
    ["The treaty was seen as a threat to national ___.", "sovereignty", ["bureaucracy", "polarisation", "censorship"], "Sovereignty adalah kekuasaan tertinggi suatu negara atas dirinya sendiri."],
    ["Starting a business there means months of forms, stamps and waiting in government offices. This is a complaint about ___.", "bureaucracy", ["censorship", "populism", "sovereignty"], "Bureaucracy adalah sistem administrasi pemerintahan yang rumit dan lambat."],
    ["Choose the correct form: 'Social media has helped to ___ public opinion, pushing people towards opposite extremes.'", "polarise", ["polarisation", "polar", "polarised"], "Setelah 'helped to' dibutuhkan kata kerja dasar, yaitu polarise."],
    ["What is 'censorship'?", "Official control over what can be published or said", ["The counting of votes after an election", "A formal agreement between two countries", "The process of debating and passing new laws in parliament"], "Censorship adalah pembatasan informasi atau ekspresi oleh pihak berwenang."],
    ["The ___ passed the new immigration bill by a narrow margin.", "legislature", ["sovereignty", "referendum", "polarisation"], "Legislature adalah lembaga pembuat undang-undang yang mengesahkan rancangan undang-undang."],
    ["Which adjective describes how geography influences international politics and power?", "geopolitical", ["electoral", "municipal", "bureaucratic"], "Geopolitical berkaitan dengan pengaruh geografi terhadap politik antarnegara."],
    ["___ reform was a central demand of the opposition parties, who wanted a fairer voting system.", "Electoral", ["Geopolitical", "Sovereign", "Bureaucratic"], "Electoral berkaitan dengan pemilihan umum, sesuai dengan sistem pemungutan suara."],
    ["A politician who claims to speak for 'ordinary people' against a corrupt elite is often associated with ___.", "populism", ["censorship", "bureaucracy", "sovereignty"], "Populism adalah ideologi yang mengklaim mewakili rakyat melawan elit."],
    ["Which word is the opposite of 'polarisation' in a society?", "consensus", ["division", "conflict", "extremism"], "Polarisation berarti perpecahan tajam, sedangkan consensus berarti kesepakatan bersama."],
    ["Which verb collocates naturally with 'a referendum'?", "hold", ["make", "do", "take"], "Kolokasi yang benar adalah 'hold a referendum', artinya mengadakan referendum."],
    ["Critics accused the government of imposing ___ on independent media.", "censorship", ["sovereignty", "populism", "legislature"], "Censorship adalah pembatasan yang dapat dikenakan pada media independen."],
    ["Choose the correct form: 'The country declared itself a ___ state after centuries of foreign rule.'", "sovereign", ["sovereignty", "sovereignly", "sovereigns"], "Sebelum kata benda 'state' dibutuhkan kata sifat, yaitu sovereign."],
    ["Kata 'legislature' paling tepat diterjemahkan sebagai ...", "badan pembuat undang-undang", ["pengadilan tertinggi negara", "kantor perdana menteri", "komisi pemilihan umum"], "Legislature adalah badan legislatif yang membuat undang-undang."],
  ],

  // Lesson 7: Arts & Culture
  7: [
    ["The ___ designed the exhibition to challenge conventional interpretations.", "curator", ["patron", "genre", "motif"], "Curator adalah pengelola koleksi yang merancang pameran di museum atau galeri."],
    ["Which word refers to financial support given to artists or arts institutions?", "patronage", ["heritage", "narrative", "aesthetic"], "Patronage adalah dukungan finansial kepada seniman atau lembaga seni."],
    ["Her ___ compositions shocked traditionalists but inspired a new generation.", "avant-garde", ["conventional", "classical", "traditional"], "Avant-garde berarti eksperimental dan inovatif, sehingga mengejutkan kaum tradisionalis."],
    ["What does 'motif' mean in literature or art?", "An element that recurs and carries meaning", ["The main character in a story", "The price paid for a painting", "The final scene of a play or other performance"], "Motif adalah elemen berulang dalam karya seni yang membawa makna."],
    ["Which word means the study of signs and symbols and how they create meaning?", "semiotics", ["aesthetics", "linguistics", "narratives"], "Semiotics adalah studi tentang tanda dan simbol."],
    ["She works across multiple ___, blending fiction with documentary elements.", "genres", ["motifs", "curators", "patrons"], "Genre adalah kategori karya seni, dan menggabungkan fiksi dengan dokumenter berarti melintasi genre."],
    ["The film challenges the dominant ___ around colonialism and identity.", "narrative", ["curator", "patronage", "motif"], "Narrative di sini berarti cara pandang atau cerita dominan tentang suatu topik."],
    ["Choose the correct form: 'The director chose to ___ the events of the war through the eyes of a child.'", "narrate", ["narrative", "narrator", "narration"], "Setelah 'chose to' dibutuhkan kata kerja dasar, yaitu narrate."],
    ["Which word is closest in meaning to 'subversive' in 'his subversive art'?", "rebellious", ["decorative", "traditional", "obedient"], "Subversive berarti menentang tatanan yang ada, mirip dengan 'rebellious'."],
    ["Which adjective relates to beauty and the appreciation of art?", "aesthetic", ["subversive", "narrative", "cultural"], "Aesthetic berkaitan dengan keindahan dan apresiasi seni."],
    ["Batik, traditional dances and ancient temples are all part of Indonesia's ___.", "cultural heritage", ["patronage", "genre", "avant-garde"], "Cultural heritage adalah tradisi dan artefak warisan generasi sebelumnya."],
    ["The ___ of water appears again and again in the novel, always linked to memory.", "motif", ["genre", "curator", "aesthetic"], "Motif adalah elemen yang muncul berulang kali dalam karya dan membawa makna."],
    ["Choose the correct form: 'The design is ___ pleasing, but it is not very practical.'", "aesthetically", ["aesthetic", "aesthetics", "aestheticism"], "Untuk menerangkan kata sifat 'pleasing' dibutuhkan kata keterangan, yaitu aesthetically."],
    ["Which word is the opposite of 'avant-garde'?", "conventional", ["experimental", "innovative", "radical"], "Avant-garde berarti eksperimental, sedangkan conventional berarti mengikuti kebiasaan lama."],
    ["Without royal ___, many Renaissance artists would not have flourished.", "patronage", ["heritage", "aesthetic", "genre"], "Patronage dari kerajaan memberi dukungan dana yang membuat seniman Renaisans berkembang."],
  ],

  // Lesson 8: Philosophy & Ethics
  8: [
    ["Which branch of philosophy asks 'What can we know, and how do we know it?'", "epistemology", ["ontology", "aesthetics", "metaphysics"], "Epistemology adalah cabang filsafat yang mempelajari hakikat pengetahuan."],
    ["___ judges actions by their consequences for overall well-being.", "Utilitarianism", ["Determinism", "Nihilism", "Deontology"], "Utilitarianism menilai tindakan dari akibatnya terhadap kebahagiaan bersama."],
    ["Kant believed lying is always wrong, whatever the result. This is a ___ view of ethics.", "deontological", ["utilitarian", "pragmatic", "nihilistic"], "Deontological ethics menilai tindakan berdasarkan kewajiban, bukan hasilnya."],
    ["The view that every event, including human choices, is caused by earlier events is called ___.", "determinism", ["autonomy", "pragmatism", "nihilism"], "Determinism berpandangan bahwa semua peristiwa ditentukan oleh sebab sebelumnya."],
    ["Respecting patient ___ is a cornerstone of modern medical ethics.", "autonomy", ["cognition", "determinism", "ontology"], "Autonomy adalah hak pasien untuk mengambil keputusan sendiri."],
    ["What is 'nihilism'?", "The belief that life has no built-in meaning", ["The belief that knowledge comes from experience", "The view that actions should maximise happiness", "The idea that people must follow strict duties"], "Nihilism adalah keyakinan bahwa hidup tidak memiliki makna intrinsik."],
    ["Choose the correct form: 'She took a ___ approach, choosing whatever solution worked best in practice.'", "pragmatic", ["pragmatism", "pragmatist", "pragmatically"], "Sebelum kata benda 'approach' dibutuhkan kata sifat, yaitu pragmatic."],
    ["Questions about the mind-body problem fall within the domain of ___.", "metaphysics", ["pragmatism", "utilitarianism", "nihilism"], "Metaphysics mempelajari hakikat realitas, termasuk hubungan pikiran dan tubuh."],
    ["Which word refers to the mental processes of thinking, knowing and remembering?", "cognition", ["autonomy", "ontology", "emotion"], "Cognition adalah proses mental untuk memperoleh pengetahuan."],
    ["Choose the correct form: 'Philosophers have long debated the ___ status of numbers: do they really exist?'", "ontological", ["ontology", "ontologist", "ontologically"], "Sebelum kata benda 'status' dibutuhkan kata sifat, yaitu ontological."],
    ["Which belief is most directly challenged by 'determinism'?", "free will", ["cause and effect", "natural law", "predictability"], "Determinism menyatakan semua sudah ditentukan, sehingga menantang keyakinan akan free will."],
    ["Which word is closest in meaning to 'autonomy'?", "independence", ["dependence", "obedience", "uncertainty"], "Autonomy berarti kemampuan bertindak atas pilihan sendiri, sama dengan independence."],
    ["Kata 'pragmatism' paling tepat dijelaskan sebagai ...", "pendekatan yang menilai sesuatu dari kegunaan praktisnya", ["keyakinan bahwa hidup tidak memiliki makna", "pandangan bahwa semua peristiwa sudah ditentukan oleh sebab sebelumnya", "studi tentang hakikat keberadaan sesuatu"], "Pragmatism menilai ide atau tindakan berdasarkan konsekuensi praktisnya."],
    ["A doctor sacrifices one patient to save five, arguing that this produces the greatest good. Which theory supports this?", "utilitarianism", ["nihilism", "determinism", "epistemology"], "Utilitarianism membenarkan tindakan yang menghasilkan kebaikan terbesar bagi jumlah terbanyak."],
    ["Choose the correct form: 'The novel's hero is a ___ who believes nothing truly matters.'", "nihilist", ["nihilism", "nihilistic", "nihilistically"], "Setelah 'a' dibutuhkan kata benda untuk orang, yaitu nihilist."],
  ],

  // Lesson 9: Science & Discovery
  9: [
    ["The claim was supported by robust ___ evidence from multiple independent studies.", "empirical", ["theoretical", "hypothetical", "anecdotal"], "Empirical evidence adalah bukti dari observasi dan eksperimen, sesuai dengan 'independent studies'."],
    ["Which word means the repeating of an experiment to check whether the results are the same?", "replication", ["observation", "calculation", "publication"], "Replication adalah pengulangan percobaan untuk memverifikasi hasilnya."],
    ["Mapping the human ___ has opened entirely new frontiers in personalised medicine.", "genome", ["quantum", "catalyst", "species"], "Genome adalah keseluruhan informasi genetik organisme yang dapat dipetakan."],
    ["Which type of study observes the same participants repeatedly over many years?", "a longitudinal study", ["a cross-sectional study", "a pilot study", "a replication study"], "Longitudinal study berlangsung jangka panjang untuk mengamati perubahan pada peserta yang sama."],
    ["Which word describes the brain's ability to change and form new connections throughout life?", "neuroplasticity", ["intelligence", "memory", "replication"], "Neuroplasticity adalah kemampuan otak untuk berubah dan beradaptasi."],
    ["In 'The discovery acted as a catalyst for a new wave of research', 'catalyst' means ...", "something that starts or speeds up a process", ["something that slows a process down", "the final result of a long and complicated experiment", "a mistake that ruins an experiment"], "Catalyst adalah sesuatu yang mempercepat atau memicu sebuah proses."],
    ["Choose the correct form: 'The results could not be ___ by other laboratories, so the paper was withdrawn.'", "replicated", ["replication", "replicate", "replicable"], "Setelah 'could not be' dibutuhkan bentuk pasif, yaitu replicated."],
    ["Which packaging would be described as 'biodegradable'?", "A bag that breaks down naturally in soil", ["A bottle that can be refilled many times", "A box that is made from recycled metal", "A wrapper that is very easy to open"], "Biodegradable berarti dapat terurai secara alami di lingkungan."],
    ["Choose the correct form: 'The theory was tested ___ through a series of field experiments.'", "empirically", ["empirical", "empiricism", "empiricist"], "Untuk menerangkan kata kerja 'tested' dibutuhkan kata keterangan, yaitu empirically."],
    ["___ computing promises to solve problems beyond the reach of classical computers.", "Quantum", ["Genome", "Empirical", "Catalyst"], "Quantum computing adalah komputasi berbasis fisika kuantum yang melampaui komputer klasik."],
    ["Which word is the opposite of 'empirical'?", "theoretical", ["experimental", "observational", "practical"], "Empirical berdasarkan observasi, sedangkan theoretical berdasarkan teori semata."],
    ["New evidence has ___ that challenges the original theory.", "emerged", ["emitted", "submerged", "immersed"], "Emerge berarti muncul atau menjadi diketahui, cocok untuk bukti baru."],
    ["Choose the correct form: 'The ___ of new technologies has transformed laboratory research.'", "emergence", ["emergency", "emerging", "emerge"], "Emergence adalah kata benda dari emerge yang berarti kemunculan, bukan emergency (keadaan darurat)."],
    ["Which verb completes the phrase: 'The protests ___ as a catalyst for reform'?", "acted", ["did", "made", "played"], "Kolokasi yang benar adalah 'act as a catalyst', artinya berperan sebagai pemicu."],
    ["Apa arti 'genome'?", "Keseluruhan informasi genetik suatu organisme", ["Satu sel dalam tubuh manusia", "Penyakit yang diturunkan dari orang tua", "Zat yang mempercepat reaksi kimia"], "Genome adalah seluruh informasi genetik yang dimiliki suatu organisme."],
  ],

  // Lesson 10: Media & Communication
  10: [
    ["State-sponsored ___ campaigns have undermined trust in democratic institutions.", "disinformation", ["investigative", "plurality", "gatekeeping"], "Disinformation adalah informasi salah yang disebarkan dengan sengaja untuk merusak kepercayaan."],
    ["What makes 'disinformation' different from simple misinformation?", "It is spread deliberately to deceive", ["It is always about national politics", "It only appears in printed newspapers", "It is usually harmless and amusing"], "Disinformation disebarkan dengan sengaja untuk menipu, sedangkan misinformation bisa tidak disengaja."],
    ["A headline like 'You won't BELIEVE what happened next!' is a typical example of ___.", "clickbait", ["propaganda", "soundbite", "gatekeeping"], "Clickbait adalah konten yang dirancang untuk menarik klik tanpa substansi."],
    ["Which word describes a short, memorable quote from a speech, designed to be broadcast on the news?", "soundbite", ["headline", "clickbait", "propaganda"], "Soundbite adalah kutipan singkat yang dirancang untuk disiarkan."],
    ["Which adjective describes journalism that involves deep, systematic research to uncover hidden wrongdoing?", "investigative", ["sensational", "paywalled", "opinionated"], "Investigative journalism melibatkan penelitian mendalam untuk mengungkap pelanggaran."],
    ["If you only follow people who share your views online, you may end up in an ___.", "echo chamber", ["ivory tower", "open debate", "editorial board"], "Echo chamber adalah lingkungan di mana seseorang hanya mendengar pandangan yang sama dengan miliknya."],
    ["Media ___ is essential for a functioning democracy and an informed citizenry.", "plurality", ["propaganda", "gatekeeping", "clickbait"], "Plurality adalah keberagaman suara dalam media yang penting bagi demokrasi."],
    ["In journalism, 'gatekeeping' refers to ...", "deciding which information reaches the public", ["charging readers to access online articles", "protecting reporters from legal action", "checking the spelling and grammar of published articles"], "Gatekeeping adalah kontrol atas informasi apa yang disebarluaskan kepada publik."],
    ["Quality journalism is increasingly ___ as advertising revenues decline.", "paywalled", ["sponsored", "biased", "censored"], "Paywalled berarti hanya dapat diakses dengan membayar, yang terjadi karena pendapatan iklan turun."],
    ["Apa arti 'propaganda'?", "Informasi bias yang disebarkan untuk memengaruhi opini publik", ["Laporan berita yang netral, seimbang dan berdasarkan fakta lengkap", "Iklan produk di media sosial", "Kutipan singkat dari pidato politik"], "Propaganda adalah informasi yang disebarkan untuk memengaruhi opini publik."],
    ["Choose the correct form: 'The minister's ___ remarks sparked protests across the country.'", "controversial", ["controversy", "controversially", "controversies"], "Sebelum kata benda 'remarks' dibutuhkan kata sifat, yaitu controversial."],
    ["The decision to publish the leaked photos caused a great deal of ___.", "controversy", ["plurality", "gatekeeping", "clickbait"], "Controversy adalah perdebatan publik yang serius, yang dapat muncul akibat sebuah keputusan."],
    ["Which verb collocates with 'disinformation' when people share it widely?", "spread", ["make", "tell", "say"], "Kolokasi yang benar adalah 'spread disinformation', artinya menyebarkan disinformasi."],
    ["Modern political communication is dominated by ___ rather than substantive debate.", "soundbites", ["paywalls", "gatekeepers", "plurality"], "Soundbites adalah kutipan singkat yang menggantikan perdebatan yang mendalam."],
    ["Which phrase is the opposite of 'media plurality'?", "media concentration", ["media diversity", "media freedom", "media literacy"], "Media plurality berarti keberagaman, sedangkan media concentration berarti media dikuasai segelintir pihak."],
  ],

  // Lesson 11: Law & Justice
  11: [
    ["The case fell outside the court's ___ and was referred to an international tribunal.", "jurisdiction", ["precedent", "litigation", "statute"], "Jurisdiction adalah kewenangan hukum suatu pengadilan atas perkara tertentu."],
    ["The ruling set an important ___ for future environmental liability cases.", "precedent", ["statute", "acquittal", "verdict"], "Precedent adalah keputusan hukum yang menjadi acuan untuk kasus berikutnya."],
    ["Which word means a 'not guilty' decision at the end of a trial?", "acquittal", ["conviction", "extradition", "arbitration"], "Acquittal adalah putusan tidak bersalah, kebalikan dari conviction."],
    ["Instead of going to court, two companies asked an independent expert to settle their dispute. This is called ___.", "arbitration", ["litigation", "extradition", "jurisdiction"], "Arbitration adalah penyelesaian sengketa di luar pengadilan oleh pihak ketiga."],
    ["The company faced years of expensive ___ after customers sued it over a faulty product.", "litigation", ["arbitration", "acquittal", "extradition"], "Litigation adalah proses penyelesaian sengketa melalui pengadilan, sesuai dengan kata 'sued'."],
    ["Before joining the project, all staff signed a ___ agreement promising not to share confidential details.", "non-disclosure", ["non-binding", "non-profit", "non-compete"], "Non-disclosure agreement melarang pihak yang menandatangani mengungkapkan informasi rahasia."],
    ["'Extradition' means ...", "sending a suspect to another country to face trial", ["releasing a prisoner before the end of the full sentence", "banning a foreigner from entering a country", "moving a trial to a different city"], "Extradition adalah penyerahan tersangka kepada negara lain untuk diadili."],
    ["Choose the correct form: 'The jury voted to ___ the defendant of all charges.'", "acquit", ["acquittal", "acquitted", "acquitting"], "Setelah 'voted to' dibutuhkan kata kerja dasar, yaitu acquit."],
    ["Choose the correct form: 'The report found the directors ___ for the collapse of the bank.'", "culpable", ["culpability", "culprit", "culpably"], "Pola 'find someone + adjective' membutuhkan kata sifat, yaitu culpable."],
    ["What does 'due process' guarantee?", "fair treatment under established legal procedures", ["a quick trial without any delay, whatever the charges are", "the right to avoid paying legal fees", "automatic release for first-time offenders"], "Due process menjamin perlakuan adil sesuai prosedur hukum yang berlaku."],
    ["Which word refers to a written law formally passed by a parliament?", "statute", ["precedent", "verdict", "treaty"], "Statute adalah undang-undang tertulis yang disahkan secara formal."],
    ["Which word is closest in meaning to 'culpability'?", "blame", ["innocence", "authority", "evidence"], "Culpability berarti tingkat kesalahan atau tanggung jawab, mirip dengan 'blame'."],
    ["Choose the correct form: 'Unhappy customers threatened to ___ unless the company paid compensation.'", "litigate", ["litigation", "litigious", "litigant"], "Setelah 'threatened to' dibutuhkan kata kerja dasar, yaitu litigate."],
    ["Which verb completes the sentence: 'The two countries ___ an extradition treaty last year.'", "signed", ["made", "did", "took"], "Kolokasi yang benar adalah 'sign a treaty', artinya menandatangani perjanjian."],
    ["Kata 'precedent' dalam hukum paling tepat dijelaskan sebagai ...", "keputusan pengadilan sebelumnya yang menjadi acuan", ["undang-undang baru yang disahkan parlemen", "hukuman yang dijatuhkan kepada terdakwa", "bukti yang diajukan oleh pengacara"], "Precedent adalah putusan terdahulu yang dijadikan acuan dalam perkara serupa."],
  ],

  // Lesson 12: Psychology & Behaviour
  12: [
    ["___ arises when smokers know the health risks but continue smoking.", "Cognitive dissonance", ["Cognitive bias", "Self-efficacy", "Conformity"], "Cognitive dissonance adalah ketidaknyamanan mental ketika keyakinan dan tindakan bertentangan."],
    ["A student who studies because she genuinely enjoys learning, not for grades, shows ___.", "intrinsic motivation", ["extrinsic motivation", "cognitive dissonance", "conformity"], "Intrinsic motivation adalah dorongan dari dalam diri, bukan karena hadiah eksternal."],
    ["Which term describes thinking about your own thinking, for example checking whether you really understand a text?", "metacognition", ["self-efficacy", "conformity", "resilience"], "Metacognition adalah kemampuan berpikir tentang proses berpikir sendiri."],
    ["A person's belief in their own ability to succeed at a particular task is called ___.", "self-efficacy", ["self-esteem", "self-awareness", "self-discipline"], "Self-efficacy adalah keyakinan seseorang terhadap kemampuannya menyelesaikan tugas tertentu."],
    ["Milgram's classic studies revealed the disturbing power of ___ and authority.", "conformity", ["resilience", "metacognition", "self-efficacy"], "Conformity adalah kecenderungan menyesuaikan perilaku dengan kelompok atau otoritas."],
    ["Choose the correct form: 'Teenagers often ___ to the fashion choices of their friends.'", "conform", ["conformity", "conformist", "conforming"], "Setelah subjek 'Teenagers often' dibutuhkan kata kerja, yaitu conform."],
    ["Which theory explains how early bonds with caregivers shape a person's adult relationships?", "attachment theory", ["game theory", "learning theory", "conflict theory"], "Attachment theory menjelaskan pengaruh hubungan awal dengan pengasuh terhadap ikatan emosional dewasa."],
    ["What is 'resilience' in psychology?", "The ability to recover from difficulties", ["The tendency to follow group norms", "A strong fear of failing in front of other people", "The habit of avoiding all stress"], "Resilience adalah kemampuan untuk pulih dari kesulitan."],
    ["Choose the correct form: 'Children who grow up with support tend to be more ___ when facing problems later.'", "resilient", ["resilience", "resiliently", "resiliency"], "Setelah 'be more' dibutuhkan kata sifat, yaitu resilient."],
    ["Confirmation bias, the habit of noticing only evidence that supports what we already believe, is a well-known ___.", "cognitive bias", ["attachment style", "neurological disorder", "intrinsic motivation"], "Confirmation bias adalah salah satu jenis cognitive bias, yaitu penyimpangan dari pemikiran rasional."],
    ["___ research has revealed the biological basis of anxiety disorders.", "Neurological", ["Intrinsic", "Attachment", "Behavioural"], "Neurological berkaitan dengan sistem saraf, sesuai dengan 'biological basis'."],
    ["Identifying negative ___ is the first step in effective therapy.", "behavioural patterns", ["intrinsic motivations", "attachment theories", "neurological effects"], "Behavioural patterns adalah pola perilaku yang perlu dikenali dalam terapi."],
    ["Which phrase is the opposite of 'intrinsic motivation'?", "extrinsic motivation", ["inner motivation", "personal motivation", "self-motivation"], "Intrinsic berarti dari dalam diri, sedangkan extrinsic berarti dari luar seperti hadiah atau nilai."],
    ["Psychological resilience can be ___ through mindfulness and social support.", "cultivated", ["inherited", "diagnosed", "imitated"], "Cultivate berarti mengembangkan secara bertahap, cocok dengan latihan mindfulness dan dukungan sosial."],
    ["Apa arti 'cognitive bias'?", "Kecenderungan berpikir yang menyimpang dari rasionalitas", ["Kemampuan memahami perasaan orang lain", "Kerusakan pada sistem saraf di otak", "Keyakinan pada kemampuan diri sendiri"], "Cognitive bias adalah kecenderungan pikiran yang menyimpang dari pertimbangan rasional."],
  ],

  // Lesson 13: Travel & Globalisation
  13: [
    ["The Indian ___ plays a significant cultural and economic role in over 100 countries.", "diaspora", ["assimilation", "xenophobia", "homogenisation"], "Diaspora adalah komunitas yang tersebar di luar tanah air aslinya."],
    ["Which word means fear or hatred of people from other countries?", "xenophobia", ["nationalism", "diaspora", "migration"], "Xenophobia adalah ketakutan atau kebencian terhadap orang asing."],
    ["An agreement signed by thirty countries to cut tariffs is a ___ agreement.", "multilateral", ["bilateral", "unilateral", "transnational"], "Multilateral berarti melibatkan banyak negara, sedangkan bilateral hanya dua negara."],
    ["London's ___ population makes it one of the world's most culturally diverse cities.", "cosmopolitan", ["homogeneous", "provincial", "xenophobic"], "Cosmopolitan berarti berasal dari banyak budaya dan terbuka pada dunia."],
    ["'Cultural homogenisation' describes ...", "local cultures becoming more and more alike", ["people moving to another country to find better-paid work", "the protection of traditional customs", "tourism that respects the environment"], "Homogenisation adalah proses menjadi seragam sehingga keragaman budaya hilang."],
    ["Visitors stay in a village, pay local guides and help protect a rainforest. This is an example of ___.", "ecotourism", ["mass tourism", "migration", "diaspora"], "Ecotourism adalah pariwisata yang bertanggung jawab terhadap lingkungan dan masyarakat lokal."],
    ["Choose the correct form: 'Thousands of workers ___ to the city every year in search of better wages.'", "migrate", ["migration", "migrant", "migratory"], "Setelah subjek dibutuhkan kata kerja, yaitu migrate."],
    ["Which word describes companies or organisations that operate across national borders?", "transnational", ["multilateral", "cosmopolitan", "domestic"], "Transnational berarti melampaui batas-batas negara."],
    ["Newcomers often need help to ___ the complicated visa system.", "navigate", ["assimilate", "migrate", "emigrate"], "Navigate berarti menemukan jalan melalui situasi atau sistem yang rumit."],
    ["What is 'cultural assimilation'?", "Adopting the customs of a new society", ["Keeping one's culture fully separate", "Travelling abroad for a short holiday", "Teaching one's language to tourists"], "Cultural assimilation adalah proses mengadopsi norma budaya masyarakat baru."],
    ["Choose the correct form: 'Many immigrants ___ quickly, adopting the language and habits of their new country.'", "assimilate", ["assimilation", "assimilating", "assimilative"], "Setelah subjek 'Many immigrants' dibutuhkan kata kerja, yaitu assimilate."],
    ["Which word is the opposite of 'cosmopolitan'?", "provincial", ["international", "multicultural", "urban"], "Cosmopolitan berarti terbuka pada dunia, sedangkan provincial berarti berpandangan sempit dan lokal."],
    ["Which adjective goes with 'migration' to describe people moving for jobs and income?", "economic", ["financial", "commercial", "monetary"], "Kolokasi yang lazim adalah 'economic migration', yaitu migrasi karena alasan pekerjaan."],
    ["Choose the correct form: 'Online maps have made ___ in unfamiliar cities much easier.'", "navigation", ["navigate", "navigator", "navigable"], "Setelah 'made' dibutuhkan kata benda yang menyatakan kegiatan, yaitu navigation."],
    ["Kata 'diaspora' paling tepat dijelaskan sebagai ...", "komunitas yang tersebar di luar tanah air aslinya", ["kelompok wisatawan dari luar negeri", "penduduk asli suatu wilayah", "pekerja musiman di perkebunan"], "Diaspora adalah kelompok masyarakat yang hidup tersebar di luar negeri asalnya."],
  ],

  // Lesson 14: Urban Life & Infrastructure
  14: [
    ["___ in the historic district has priced out long-term residents.", "Gentrification", ["Urban sprawl", "Congestion", "Zoning"], "Gentrification menaikkan harga properti sehingga penduduk lama tergeser."],
    ["Which term describes a city spreading in an uncontrolled way into the surrounding countryside?", "urban sprawl", ["gentrification", "zoning", "congestion"], "Urban sprawl adalah perluasan kota yang tidak terkendali ke daerah pinggiran."],
    ["Ageing ___ such as bridges, water pipes and power lines poses serious risks to public safety.", "infrastructure", ["architecture", "zoning", "congestion"], "Infrastructure adalah sistem fisik dasar seperti jembatan, pipa air dan jaringan listrik."],
    ["Rules that say which areas of a city can be used for housing, shops or factories are called ___ laws.", "zoning", ["traffic", "property", "building"], "Zoning adalah pembagian wilayah kota berdasarkan fungsi penggunaan lahan."],
    ["Traffic ___ costs the city an estimated $1.5 billion in lost productivity each year.", "congestion", ["gentrification", "zoning", "infrastructure"], "Traffic congestion adalah kemacetan lalu lintas yang menghambat produktivitas."],
    ["'Sustainable development' means ...", "growth that meets today's needs without harming the future", ["building as fast as possible to attract foreign investors and tourists", "moving factories out of the city centre", "replacing old houses with luxury apartments"], "Sustainable development adalah pembangunan yang memenuhi kebutuhan kini tanpa merugikan generasi mendatang."],
    ["___ development reduces car use by building homes and offices around train and bus stations.", "Transit-oriented", ["Car-centred", "Low-density", "Suburban"], "Transit-oriented development berpusat di sekitar transportasi umum sehingga mengurangi penggunaan mobil."],
    ["Choose the correct form: 'The new metro line has made the city centre far less ___.'", "congested", ["congestion", "congest", "congesting"], "Setelah 'made ... less' dibutuhkan kata sifat, yaitu congested."],
    ["Which phrase is the opposite of 'high-density housing'?", "low-density housing", ["affordable housing", "social housing", "temporary housing"], "High-density berarti padat, sedangkan low-density berarti jarang bangunan atau penduduk."],
    ["The ___ council voted to build three new public libraries in the town.", "municipal", ["national", "federal", "international"], "Municipal berkaitan dengan pemerintahan kota setempat, sesuai dengan 'in the town'."],
    ["A 'resilient city' is one that ...", "can withstand and recover from crises", ["has the largest population in its region", "has banned cars from its centre", "attracts the most foreign tourists"], "Resilient city adalah kota yang mampu bertahan dan pulih dari krisis."],
    ["The council plans to ___ a new parking policy from January.", "implement", ["implicate", "imply", "implore"], "Implement berarti menerapkan sebuah rencana atau kebijakan."],
    ["Choose the correct form: 'The ___ of the congestion charge reduced traffic by 20%.'", "implementation", ["implement", "implemented", "implementer"], "Setelah 'The' dan sebelum 'of' dibutuhkan kata benda yang berarti penerapan, yaitu implementation."],
    ["Choose the correct form: 'The old docks have been ___, and cafés have replaced warehouses.'", "gentrified", ["gentrification", "gentrify", "gentry"], "Setelah 'have been' dibutuhkan bentuk pasif, yaitu gentrified."],
    ["Which adjective most naturally describes infrastructure that is old and in poor condition?", "ageing", ["elderly", "senior", "antique"], "Kolokasi yang lazim adalah 'ageing infrastructure', sedangkan elderly dan senior dipakai untuk orang."],
  ],

  // Lesson 15: Education Systems
  15: [
    ["The national ___ was revised to include digital literacy as a core subject.", "curriculum", ["attainment", "assessment", "timetable"], "Curriculum adalah rencana materi pelajaran yang dapat direvisi untuk menambah mata pelajaran."],
    ["Which word refers to the methods and theory of teaching?", "pedagogy", ["curriculum", "literacy", "attainment"], "Pedagogy adalah seni dan ilmu mengajar, sedangkan curriculum adalah isi yang diajarkan."],
    ["A teacher gives short quizzes during a unit to check progress and adjust her lessons. This is ___.", "formative assessment", ["summative assessment", "standardised testing", "academic attainment"], "Formative assessment adalah evaluasi berkelanjutan selama proses belajar."],
    ["Socioeconomic background remains the strongest predictor of ___.", "academic attainment", ["lifelong learning", "inclusive education", "critical thinking"], "Academic attainment adalah tingkat pencapaian akademik siswa yang dipengaruhi latar belakang sosial ekonomi."],
    ["'Inclusive education' means ...", "students of all abilities learning together", ["schools that only accept top students", "education paid for by private companies", "learning done entirely online at home without teachers"], "Inclusive education mengakomodasi semua kebutuhan belajar dalam satu kelas."],
    ["Which term describes the natural variety in how people's brains work, including conditions such as dyslexia and ADHD?", "neurodiversity", ["disability", "pedagogy", "literacy"], "Neurodiversity adalah keragaman alami dalam cara otak berfungsi."],
    ["Choose the correct form: 'Adult ___ rates have risen sharply since the new reading programme began.'", "literacy", ["literate", "literal", "literature"], "Literacy adalah kemampuan membaca dan menulis, dan 'literacy rates' adalah kolokasi yang benar."],
    ["Which phrase best describes 'critical thinking'?", "analysing and evaluating information carefully", ["memorising facts for an important exam", "criticising other people's ideas", "thinking quickly under pressure"], "Critical thinking adalah kemampuan menganalisis dan mengevaluasi informasi secara sistematis."],
    ["Critics argue that ___ narrows the curriculum, because teachers focus only on what will be in the exam.", "standardised testing", ["formative assessment", "lifelong learning", "inclusive education"], "Standardised testing adalah ujian seragam yang membuat guru hanya mengajarkan materi ujian."],
    ["Which phrase describes continuing to learn new skills throughout your whole life?", "lifelong learning", ["distance learning", "rote learning", "early learning"], "Lifelong learning adalah komitmen untuk terus belajar sepanjang hayat."],
    ["Choose the correct form: 'The training course focuses on the ___ skills that new teachers need.'", "pedagogical", ["pedagogy", "pedagogue", "pedagogically"], "Sebelum kata benda 'skills' dibutuhkan kata sifat, yaitu pedagogical."],
    ["In 'Digital literacy is now as essential as reading and writing', 'digital literacy' means ...", "the ability to use digital technology effectively", ["the ability to read books on a screen", "a list of approved educational websites", "the habit of spending a lot of time online every day"], "Digital literacy adalah kemampuan menggunakan teknologi digital secara efektif."],
    ["Choose the correct form: 'Few students managed to ___ the highest grade in the final exam.'", "attain", ["attainment", "attainable", "attained"], "Setelah 'managed to' dibutuhkan kata kerja dasar, yaitu attain."],
    ["Choose the correct form: 'The school aims to ___ students with disabilities in every activity.'", "include", ["inclusive", "inclusion", "inclusively"], "Setelah 'aims to' dibutuhkan kata kerja dasar, yaitu include."],
    ["Apa arti 'formative assessment'?", "Penilaian berkelanjutan selama proses belajar", ["Ujian akhir di penghujung semester", "Tes masuk untuk sekolah unggulan", "Nilai rata-rata dari semua mata pelajaran"], "Formative assessment adalah penilaian yang dilakukan terus-menerus selama pembelajaran."],
  ],

  // Lesson 16: Food Industry & Nutrition
  16: [
    ["The ___ value of ultra-processed food is typically far lower than that of whole food alternatives.", "nutritional", ["caloric", "fortified", "plant-based"], "Nutritional value adalah kandungan gizi, yang pada makanan ultra-olahan biasanya rendah."],
    ["Research on the gut ___ suggests links between diet and mental health.", "microbiome", ["obesity", "nutrition", "fortification"], "Microbiome adalah komunitas mikroorganisme di dalam usus."],
    ["Which term describes a situation where people lack reliable access to enough affordable, nutritious food?", "food insecurity", ["food waste", "obesity", "food safety"], "Food insecurity adalah kondisi kekurangan akses terhadap pangan yang cukup."],
    ["Flour that has extra iron and vitamins added to it is described as ___.", "fortified", ["processed", "organic", "refined"], "Fortified berarti diperkaya dengan tambahan nutrisi."],
    ["'Caloric restriction' means ...", "eating fewer calories than usual", ["removing all fat from your diet", "eating only plant-based food", "taking vitamin supplements daily"], "Caloric berkaitan dengan kandungan energi, sehingga caloric restriction berarti mengurangi asupan kalori."],
    ["Farming methods that protect soil health and reduce pesticide use are part of ___.", "sustainable agriculture", ["intensive agriculture", "industrial farming", "food insecurity"], "Sustainable agriculture adalah praktik bertani yang menjaga keseimbangan ekosistem."],
    ["Choose the correct form: 'Childhood ___ rates have tripled in many high-income countries.'", "obesity", ["obese", "obesities", "fattening"], "Sebelum 'rates' dibutuhkan kata benda tunggal, yaitu obesity."],
    ["Which adjective describes a diet built mainly on vegetables, grains, beans and nuts rather than meat?", "plant-based", ["high-protein", "low-carb", "fortified"], "Plant-based berarti berbasis bahan nabati."],
    ["Many doctors ___ a reduction in sugar intake for children.", "advocate", ["advertise", "adapt", "adopt"], "Advocate berarti mendukung atau menganjurkan sesuatu secara aktif."],
    ["Choose the correct form: 'She is a passionate ___ of local, seasonal food.'", "advocate", ["advocacy", "advocating", "advocated"], "Setelah 'a passionate' dibutuhkan kata benda untuk orang, yaitu advocate."],
    ["Transforming the ___ is essential for addressing climate change and food insecurity.", "agri-food system", ["microbiome", "caloric intake", "plant-based diet"], "Agri-food system adalah jaringan produksi, distribusi dan konsumsi pangan yang perlu diubah."],
    ["Which phrase is the opposite of 'food insecurity'?", "food security", ["food safety", "food poverty", "food shortage"], "Food security berarti akses pangan yang cukup, kebalikan dari food insecurity."],
    ["Apa arti 'microbiome'?", "Komunitas mikroorganisme di dalam tubuh", ["Jenis vitamin yang larut dalam air", "Proses pencernaan makanan di lambung", "Bakteri yang hanya menyebabkan penyakit"], "Microbiome adalah kumpulan mikroorganisme yang hidup di dalam tubuh."],
    ["Choose the correct form: 'A balanced diet provides all the ___ the body needs.'", "nutrients", ["nutritional", "nutritious", "nutritionist"], "Setelah 'all the' dibutuhkan kata benda jamak, yaitu nutrients."],
    ["Choose the correct form: 'The government decided to ___ table salt with iodine.'", "fortify", ["fortified", "fortification", "fortifying"], "Setelah 'decided to' dibutuhkan kata kerja dasar, yaitu fortify."],
  ],

  // Lesson 17: Sports & Performance
  17: [
    ["___ research has revolutionised training methods in competitive swimming.", "Biomechanics", ["Doping", "Sportsmanship", "Endurance"], "Biomechanics adalah ilmu tentang gerakan tubuh yang dapat memperbaiki teknik latihan."],
    ["The use of banned substances to improve performance is known as ___.", "doping", ["tapering", "periodisation", "conditioning"], "Doping adalah penggunaan zat terlarang untuk meningkatkan performa."],
    ["A tennis player helps her injured opponent up and congratulates her after the match. This shows ___.", "sportsmanship", ["endurance", "tactics", "doping"], "Sportsmanship adalah perilaku jujur dan sportif dalam olahraga."],
    ["Developing ___ requires consistent aerobic training over several months.", "endurance", ["sportsmanship", "tactics", "biomechanics"], "Endurance adalah ketahanan fisik yang dibangun melalui latihan aerobik."],
    ["'Periodisation' in sports training means ...", "planning training in structured cycles", ["training at the same intensity every single day of the season", "studying the history of a sport", "resting completely between seasons"], "Periodisation adalah perencanaan latihan dalam siklus yang terstruktur."],
    ["Regular exercise provides ___ benefits that reduce the risk of heart disease.", "cardiovascular", ["tactical", "biomechanical", "sportsmanlike"], "Cardiovascular berkaitan dengan jantung dan pembuluh darah."],
    ["The coach changed the formation at half-time to exploit the opponent's weak defence. This was a ___ decision.", "tactical", ["physiological", "biomechanical", "cardiovascular"], "Tactical berkaitan dengan strategi dalam pertandingan."],
    ["Which field helps athletes with visualisation, focus and managing nerves before competitions?", "sports psychology", ["biomechanics", "physiology", "periodisation"], "Sports psychology mempelajari aspek mental performa atletik."],
    ["Choose the correct form: 'Increased red blood cell production is a ___ adaptation to high-altitude training.'", "physiological", ["physiology", "physiologically", "physiologist"], "Sebelum kata benda 'adaptation' dibutuhkan kata sifat, yaitu physiological."],
    ["The new programme led to a ___ improvement, cutting her race time by almost a minute.", "substantial", ["subsequent", "substitute", "subtle"], "Substantial berarti besar atau signifikan, sesuai dengan peningkatan hampir satu menit."],
    ["Which word is closest in meaning to 'substantial'?", "considerable", ["minor", "temporary", "sudden"], "Substantial berarti besar atau penting, sama dengan 'considerable'."],
    ["Choose the correct form: 'Marathon runners must ___ hours of pain and fatigue.'", "endure", ["endurance", "enduring", "endured"], "Setelah 'must' dibutuhkan kata kerja dasar, yaitu endure."],
    ["'Athletic performance' refers to ...", "an athlete's physical and technical ability in competition", ["the number of fans who watch a match", "the money an athlete earns from sponsors and advertising deals", "the official rules that govern a sport"], "Athletic performance adalah kemampuan fisik dan teknis seorang atlet."],
    ["Apa arti 'biomechanics'?", "Ilmu yang mempelajari gerakan tubuh manusia", ["Ilmu tentang kebutuhan gizi atlet", "Teknik mengatur strategi pertandingan", "Studi tentang mesin olahraga modern"], "Biomechanics adalah ilmu yang mempelajari gerakan tubuh manusia."],
    ["Which verb completes 'to ___ a doping test' when an athlete is found to have used banned drugs?", "fail", ["lose", "miss", "drop"], "Kolokasi 'fail a doping test' berarti hasil tes menunjukkan penggunaan zat terlarang."],
  ],

  // Lesson 18: Relationships & Society
  18: [
    ["Economic inequality continues to erode ___ in many urban communities.", "social cohesion", ["marginalisation", "stigma", "intergenerational"], "Social cohesion adalah rasa persatuan yang dapat terkikis oleh ketimpangan ekonomi."],
    ["Which term describes the ability to move from one social or economic class to another?", "social mobility", ["social cohesion", "social capital", "civic engagement"], "Social mobility adalah kemampuan berpindah antar strata sosial."],
    ["Volunteering, voting in local elections and attending community meetings are all forms of ___.", "civic engagement", ["social mobility", "welfare state", "interpersonal skills"], "Civic engagement adalah partisipasi aktif dalam kehidupan masyarakat."],
    ["Reducing the ___ surrounding mental health is crucial for improving access to treatment.", "stigma", ["empathy", "cohesion", "capital"], "Stigma adalah label negatif yang membuat orang enggan mencari pengobatan."],
    ["'Empathy' means ...", "understanding and sharing another person's feelings", ["feeling sorry for someone from a distance", "agreeing with everyone in order to avoid any kind of conflict", "trusting people you have only just met"], "Empathy adalah kemampuan memahami dan merasakan perasaan orang lain."],
    ["Choose the correct form: 'Good nurses ___ with patients who are frightened.'", "empathise", ["empathy", "empathetic", "empathetically"], "Setelah subjek 'Good nurses' dibutuhkan kata kerja, yaitu empathise."],
    ["Strong ___ skills are essential in any collaborative work environment.", "interpersonal", ["intergenerational", "welfare", "stigma"], "Interpersonal berkaitan dengan hubungan antarindividu, penting dalam kerja sama."],
    ["A project in which teenagers and pensioners teach each other new skills is an ___ project.", "intergenerational", ["international", "interdisciplinary", "intermediate"], "Intergenerational berarti melibatkan beberapa generasi."],
    ["Choose the correct form: 'Disabled people are often ___ in the job market.'", "marginalised", ["marginalisation", "marginalise", "margins"], "Setelah 'are often' dibutuhkan bentuk pasif, yaitu marginalised."],
    ["Which term describes a system in which the government guarantees citizens healthcare, pensions and unemployment benefits?", "welfare state", ["free market", "police state", "nation state"], "Welfare state adalah negara yang menjamin kebutuhan dasar warganya."],
    ["'Social capital' refers to ...", "the value of networks of relationships and trust", ["the money a community has saved in local banks over many years", "the main city of a country", "the taxes paid by local businesses"], "Social capital adalah nilai jaringan hubungan dan kepercayaan antarindividu."],
    ["The minister ___ that the policy had failed to help poorer families.", "acknowledged", ["acquired", "accused", "achieved"], "Acknowledge berarti mengakui suatu kenyataan, cocok dengan pengakuan kegagalan kebijakan."],
    ["Choose the correct form: 'The report gives ___ to the volunteers who made the project possible.'", "acknowledgement", ["acknowledge", "acknowledged", "acknowledging"], "Setelah 'gives' dibutuhkan kata benda, yaitu acknowledgement."],
    ["Which phrase is the opposite of 'social cohesion'?", "social fragmentation", ["social harmony", "social unity", "social solidarity"], "Social cohesion berarti persatuan, sedangkan social fragmentation berarti perpecahan."],
    ["Apa arti 'stigma'?", "Label negatif pada kelompok atau kondisi tertentu", ["Dukungan dari keluarga dan teman dekat", "Bantuan keuangan dari pemerintah", "Hubungan baik antara para tetangga"], "Stigma adalah label negatif yang dilekatkan pada kelompok atau kondisi tertentu."],
  ],

  // Lesson 19: Literature & Language
  19: [
    ["Orwell's Animal Farm is a powerful political ___ that critiques totalitarian regimes.", "allegory", ["biography", "monologue", "foreshadowing"], "Allegory adalah narasi dengan makna tersembunyi, seperti kritik politik dalam Animal Farm."],
    ["Which technique presents a character's thoughts as a continuous, unedited flow, as in Virginia Woolf's novels?", "stream of consciousness", ["foreshadowing", "discourse analysis", "unreliable narrator"], "Stream of consciousness merekam pikiran tokoh secara spontan dan mengalir."],
    ["A storyteller whose account the reader gradually realises cannot be trusted is an ___.", "unreliable narrator", ["omniscient narrator", "anonymous author", "objective observer"], "Unreliable narrator adalah pencerita yang persepsinya tidak dapat dipercaya."],
    ["Which word describes a writer giving hints early in a story about what will happen later?", "foreshadowing", ["flashback", "satire", "symbolism"], "Foreshadowing adalah petunjuk awal tentang peristiwa yang akan datang."],
    ["Swift's A Modest Proposal is one of the most famous examples of political ___ in English literature.", "satire", ["tragedy", "romance", "biography"], "Satire adalah humor yang mengkritik kelemahan sosial, seperti dalam A Modest Proposal."],
    ["'Intertextuality' refers to ...", "the relationships and references between texts", ["the translation of a text into other languages", "the layout of text on a printed page", "the total number of words in a novel"], "Intertextuality adalah hubungan dan rujukan antara satu teks dengan teks lain."],
    ["___ theory examines how colonial legacies continue to shape literature and identity.", "Postcolonial", ["Postmodernist", "Structural", "Modernist"], "Postcolonial theory mengkaji warisan kolonialisme dalam sastra dan identitas."],
    ["In The Great Gatsby, the green light stands for the American Dream. This is an example of ___.", "symbolism", ["satire", "foreshadowing", "intertextuality"], "Symbolism adalah penggunaan elemen untuk mewakili konsep abstrak."],
    ["Which field studies how language is used in real social contexts, for example in political speeches?", "discourse analysis", ["spelling reform", "creative writing", "textual editing"], "Discourse analysis mengkaji penggunaan bahasa dalam konteks sosial."],
    ["The story is told from the ___ of a ten-year-old girl.", "perspective", ["prospect", "perception", "aspect"], "Perspective adalah sudut pandang penceritaan, dan 'from the perspective of' adalah kolokasi yang benar."],
    ["Choose the correct form: 'The comedian ___ politicians who break their own rules.'", "satirises", ["satire", "satirical", "satirist"], "Setelah subjek tunggal 'The comedian' dibutuhkan kata kerja, yaitu satirises."],
    ["Choose the correct form: 'In the poem, the broken clock ___ the passing of time.'", "symbolises", ["symbolism", "symbolic", "symbolically"], "Setelah subjek tunggal dibutuhkan kata kerja, yaitu symbolises."],
    ["Choose the correct form: 'The dark clouds in the first chapter ___ the tragedy to come.'", "foreshadow", ["foreshadowing", "foreshadows", "shadowy"], "Subjek jamak 'The dark clouds' membutuhkan kata kerja tanpa -s, yaitu foreshadow."],
    ["Choose the correct form: 'The novel can be read on an ___ level as a criticism of the government.'", "allegorical", ["allegory", "allegorically", "allegorise"], "Sebelum kata benda 'level' dibutuhkan kata sifat, yaitu allegorical."],
    ["Which word is closest in meaning to 'perspective' in 'from a feminist perspective'?", "viewpoint", ["background", "summary", "conclusion"], "Perspective berarti sudut pandang, sama dengan 'viewpoint'."],
  ],

  // Lesson 20: Future & AI Technology
  20: [
    ["___ remains a theoretical goal, though progress is accelerating rapidly.", "Artificial general intelligence", ["Automation anxiety", "The digital divide", "The neural network"], "Artificial general intelligence adalah AI setara manusia di segala bidang yang belum terwujud."],
    ["Which term describes the gap between people who have access to modern technology and the internet and those who do not?", "digital divide", ["digital literacy", "data gap", "tech boom"], "Digital divide adalah kesenjangan akses teknologi antara kelompok masyarakat."],
    ["A factory worker who worries that robots will soon take his job is experiencing ___.", "automation anxiety", ["existential risk", "the digital divide", "the singularity"], "Automation anxiety adalah ketakutan kehilangan pekerjaan akibat otomatisasi."],
    ["Which word names the hypothetical point at which AI overtakes human intelligence?", "singularity", ["breakthrough", "milestone", "revolution"], "Singularity adalah titik hipotetis ketika AI melampaui kecerdasan manusia."],
    ["'Surveillance capitalism' is a business model that ...", "profits from collecting and selling data on users' behaviour", ["uses security cameras to protect shops and offices from theft", "lets governments control private banks", "pays users to watch online advertisements"], "Surveillance capitalism adalah model bisnis yang mengambil keuntungan dari data perilaku pengguna."],
    ["Deep ___ have achieved remarkable accuracy in image recognition.", "neural networks", ["digital divides", "existential risks", "social networks"], "Neural networks adalah sistem komputasi tiruan otak yang unggul dalam pengenalan gambar."],
    ["Leading AI researchers increasingly consider ___, meaning threats that could end human civilisation.", "existential risk", ["automation anxiety", "the digital divide", "a neural network"], "Existential risk adalah ancaman terhadap keberadaan peradaban manusia."],
    ["Self-driving cars and delivery drones that operate without human control are examples of ___.", "autonomous systems", ["manual systems", "digital divides", "remote-controlled systems"], "Autonomous systems adalah teknologi yang beroperasi tanpa campur tangan manusia."],
    ["Choose the correct form: 'The robot can operate ___, without any instructions from a human.'", "autonomously", ["autonomous", "autonomy", "automated"], "Untuk menerangkan kata kerja 'operate' dibutuhkan kata keterangan, yaitu autonomously."],
    ["The study's findings have serious ___ for how schools use AI.", "implications", ["implementations", "impressions", "imitations"], "Implications adalah konsekuensi tidak langsung, dan 'implications for' adalah kolokasi yang benar."],
    ["Choose the correct form: 'The report ___ that the company had ignored the risks, without saying so directly.'", "implied", ["implicated", "implication", "implying"], "Imply berarti menyiratkan sesuatu tanpa mengatakannya secara langsung, dan bentuk lampaunya implied."],
    ["Which verb collocates with 'the digital divide' when governments try to close it?", "bridge", ["build", "cross", "open"], "Kolokasi yang lazim adalah 'bridge the digital divide', artinya menjembatani kesenjangan digital."],
    ["In 'artificial general intelligence', what does 'general' contrast with?", "AI designed for one narrow task", ["AI owned and used by the military", "AI that runs without electricity", "AI that is built only for robots"], "General berarti mampu di segala bidang, berbeda dengan AI yang hanya untuk satu tugas sempit."],
    ["Apa arti 'neural network'?", "Sistem komputasi yang meniru cara kerja otak manusia", ["Jaringan internet berkecepatan tinggi", "Kelompok ilmuwan yang meneliti otak", "Media sosial khusus untuk para peneliti"], "Neural network adalah sistem komputasi yang meniru jaringan saraf otak manusia."],
    ["The ___ hypothesis remains controversial, with experts deeply divided on its likelihood.", "singularity", ["neural network", "digital divide", "automation"], "Singularity hypothesis adalah dugaan bahwa AI suatu saat akan melampaui kecerdasan manusia."],
  ],
};
