// CEFR word lists (from cefrLevelVocabulary) with Indonesian meanings and an
// example sentence that contains the word, for review and cloze questions.
type Entry = [word: string, meaning: string, example: string];

export const englishCefrLexicon: Record<string, Entry[]> = {
  a1: [
    ['name', 'nama', 'My name is Rina.'],
    ['friend', 'teman', 'She is my best friend.'],
    ['home', 'rumah', 'I go home at five.'],
    ['food', 'makanan', 'The food here is delicious.'],
    ['water', 'air', 'Please drink some water.'],
    ['school', 'sekolah', 'My school is near the park.'],
    ['book', 'buku', 'I read a book every night.'],
    ['happy', 'senang', 'I am happy today.'],
    ['go', 'pergi', 'We go to the market on Sunday.'],
    ['learn', 'belajar', 'I learn English every day.'],
    ['day', 'hari', 'Have a nice day!'],
    ['night', 'malam', 'The city is quiet at night.'],
    ['morning', 'pagi', 'I drink tea in the morning.'],
    ['house', 'rumah (bangunan)', 'Their house has a big garden.'],
    ['room', 'kamar / ruangan', 'My room is small but clean.'],
    ['family', 'keluarga', 'My family lives in Bandung.'],
    ['teacher', 'guru', 'Our teacher is very kind.'],
    ['student', 'pelajar / siswa', 'He is a new student.'],
    ['city', 'kota', 'Jakarta is a busy city.'],
    ['shop', 'toko', 'The shop opens at nine.'],
    ['bag', 'tas', 'My bag is on the chair.'],
    ['phone', 'telepon / ponsel', 'Can I use your phone?'],
    ['table', 'meja', 'The keys are on the table.'],
    ['chair', 'kursi', 'Please sit on this chair.'],
    ['big', 'besar', 'That is a big dog.'],
    ['small', 'kecil', 'I live in a small town.'],
    ['new', 'baru', 'I have a new bike.'],
    ['old', 'tua / lama', 'This is an old photo.'],
    ['like', 'suka', 'I like fried rice.'],
    ['want', 'ingin', 'I want a cup of coffee.'],
  ],
  a2: [
    ['usually', 'biasanya', 'I usually wake up at six.'],
    ['prepare', 'menyiapkan', 'I prepare breakfast for my family.'],
    ['invite', 'mengundang', 'I want to invite you to my party.'],
    ['borrow', 'meminjam', 'Can I borrow your pen?'],
    ['choose', 'memilih', 'You can choose any color.'],
    ['simple', 'sederhana', 'The recipe is simple.'],
    ['travel', 'bepergian', 'We travel to Bali every year.'],
    ['practice', 'berlatih', 'I practice speaking with my friend.'],
    ['favorite', 'favorit', 'Blue is my favorite color.'],
    ['message', 'pesan', 'I sent you a message this morning.'],
    ['plan', 'rencana', 'What is your plan for the weekend?'],
    ['visit', 'mengunjungi', 'We visit our grandparents on Sunday.'],
    ['arrive', 'tiba', 'The train will arrive at noon.'],
    ['leave', 'pergi / berangkat', 'The bus will leave in ten minutes.'],
    ['order', 'memesan', 'I want to order a pizza.'],
    ['pay', 'membayar', 'Can I pay by card?'],
    ['helpful', 'membantu / berguna', 'The staff were very helpful.'],
    ['busy', 'sibuk', 'I am busy this afternoon.'],
    ['early', 'awal / pagi-pagi', 'Please come early tomorrow.'],
    ['late', 'terlambat', 'Sorry, I am late.'],
    ['nearby', 'di dekat sini', 'Is there a bank nearby?'],
    ['during', 'selama', 'Please be quiet during the test.'],
    ['because', 'karena', 'I stayed home because it was raining.'],
    ['before', 'sebelum', 'Wash your hands before dinner.'],
    ['after', 'setelah', 'We watched a movie after dinner.'],
    ['bring', 'membawa (ke sini)', 'Please bring your notebook.'],
    ['carry', 'membawa / mengangkut', 'Can you carry this box for me?'],
    ['check', 'memeriksa', 'Please check your answers.'],
    ['change', 'mengubah / mengganti', 'I need to change my password.'],
    ['enough', 'cukup', 'We have enough time.'],
  ],
  b1: [
    ['improve', 'meningkatkan', 'I want to improve my speaking skills.'],
    ['explain', 'menjelaskan', 'Can you explain the rule again?'],
    ['request', 'permintaan', 'We received your request yesterday.'],
    ['compare', 'membandingkan', 'Let us compare the two prices.'],
    ['support', 'mendukung', 'My parents always support my decisions.'],
    ['confident', 'percaya diri', 'She feels confident before the interview.'],
    ['decision', 'keputusan', 'It was a difficult decision.'],
    ['experience', 'pengalaman', 'Working abroad was a great experience.'],
    ['opportunity', 'kesempatan', 'This job is a good opportunity for me.'],
    ['solution', 'solusi', 'We need a quick solution.'],
    ['suggest', 'menyarankan', 'I suggest we leave early.'],
    ['avoid', 'menghindari', 'Try to avoid sugary drinks.'],
    ['manage', 'mengelola', 'She can manage a big team.'],
    ['describe', 'mendeskripsikan', 'Can you describe the man you saw?'],
    ['recommend', 'merekomendasikan', 'I recommend this restaurant.'],
    ['organize', 'mengatur / menyelenggarakan', 'We organize a charity event every year.'],
    ['advantage', 'keuntungan / kelebihan', 'Living near the office is a big advantage.'],
    ['disadvantage', 'kerugian / kekurangan', 'One disadvantage is the high price.'],
    ['comfortable', 'nyaman', 'This sofa is very comfortable.'],
    ['necessary', 'perlu', 'Is it necessary to book in advance?'],
    ['available', 'tersedia', 'The manager is not available right now.'],
    ['probably', 'mungkin sekali', 'It will probably rain tonight.'],
    ['especially', 'terutama', 'I love fruit, especially mangoes.'],
    ['instead', 'sebagai gantinya', 'Let us walk instead.'],
    ['although', 'meskipun', 'Although it was late, we kept working.'],
    ['however', 'namun', 'The plan is good. However, it is expensive.'],
    ['require', 'membutuhkan / mensyaratkan', 'The job may require some travel.'],
    ['include', 'mencakup / termasuk', 'The price does not include breakfast.'],
    ['depend', 'bergantung', 'It will depend on the weather.'],
    ['consider', 'mempertimbangkan', 'Please consider my offer.'],
  ],
  b2: [
    ['approach', 'pendekatan', 'We need a different approach to this problem.'],
    ['highlight', 'menyoroti', 'The report will highlight the main risks.'],
    ['maintain', 'mempertahankan / merawat', 'It is hard to maintain a healthy routine.'],
    ['reliable', 'dapat diandalkan', 'We need a reliable supplier.'],
    ['challenge', 'tantangan', 'Learning Arabic is a real challenge.'],
    ['priority', 'prioritas', 'Safety is our top priority.'],
    ['effective', 'efektif', 'This is an effective way to learn words.'],
    ['adapt', 'beradaptasi', 'It took me months to adapt to the new job.'],
    ['outcome', 'hasil akhir', 'Nobody could predict the outcome of the match.'],
    ['perspective', 'sudut pandang', 'Try to see it from her perspective.'],
    ['assess', 'menilai', 'Teachers assess students every term.'],
    ['clarify', 'memperjelas', 'Could you clarify your last point?'],
    ['contribute', 'berkontribusi', 'Everyone should contribute to the discussion.'],
    ['negotiate', 'bernegosiasi', 'We had to negotiate a better price.'],
    ['resolve', 'menyelesaikan (masalah)', 'The team worked hard to resolve the issue.'],
    ['strategy', 'strategi', 'Our marketing strategy is working.'],
    ['efficient', 'efisien', 'The new system is more efficient.'],
    ['significant', 'signifikan / berarti', 'There was a significant increase in sales.'],
    ['flexible', 'fleksibel', 'My working hours are flexible.'],
    ['consistent', 'konsisten', 'Be consistent with your study schedule.'],
    ['context', 'konteks', 'The meaning depends on the context.'],
    ['impact', 'dampak', 'Social media has a huge impact on young people.'],
    ['benefit', 'manfaat', 'Regular exercise has many benefits.'],
    ['drawback', 'kelemahan', 'The main drawback is the cost.'],
    ['alternative', 'alternatif', 'Is there an alternative route?'],
    ['regarding', 'mengenai', 'I am writing regarding your application.'],
    ['whereas', 'sedangkan', 'He likes tea, whereas his wife prefers coffee.'],
    ['therefore', 'oleh karena itu', 'The road was closed; therefore, we took the train.'],
    ['overall', 'secara keseluruhan', 'Overall, the trip was a success.'],
    ['specifically', 'secara khusus', 'The course is designed specifically for beginners.'],
  ],
  c1: [
    ['subtle', 'halus / tidak kentara', 'There is a subtle difference between the two words.'],
    ['substantial', 'cukup besar / substansial', 'The company made a substantial profit.'],
    ['evaluate', 'mengevaluasi', 'We need to evaluate the results carefully.'],
    ['implication', 'implikasi', 'Consider the implication of this decision.'],
    ['constraint', 'kendala / batasan', 'Time is our biggest constraint.'],
    ['coherent', 'koheren / runtut', 'Her argument was clear and coherent.'],
    ['distinction', 'perbedaan / pembedaan', 'Make a clear distinction between facts and opinions.'],
    ['assumption', 'asumsi', 'That assumption turned out to be wrong.'],
    ['justify', 'membenarkan / memberi alasan', 'Can you justify the extra cost?'],
    ['precise', 'tepat / presisi', 'Please give a precise answer.'],
    ['facilitate', 'memfasilitasi', 'Technology can facilitate learning.'],
    ['anticipate', 'mengantisipasi', 'We did not anticipate such a large crowd.'],
    ['emphasize', 'menekankan', 'I want to emphasize the importance of practice.'],
    ['undermine', 'melemahkan', 'Constant criticism can undermine confidence.'],
    ['enhance', 'meningkatkan (kualitas)', 'Good lighting can enhance a photo.'],
    ['comprehensive', 'menyeluruh', 'The book gives a comprehensive overview.'],
    ['ambitious', 'ambisius', 'It is an ambitious plan.'],
    ['credible', 'kredibel / dapat dipercaya', 'We need a credible source.'],
    ['inherent', 'melekat / inheren', 'There are risks inherent in any investment.'],
    ['inevitable', 'tak terhindarkan', 'Some mistakes are inevitable.'],
    ['framework', 'kerangka kerja', 'The study uses a clear theoretical framework.'],
    ['insight', 'wawasan', 'The interview gave us useful insight.'],
    ['criterion', 'kriteria', 'Price is not the only criterion.'],
    ['tendency', 'kecenderungan', 'He has a tendency to speak too fast.'],
    ['controversy', 'kontroversi', 'The new law caused a lot of controversy.'],
    ['nevertheless', 'namun demikian', 'It was raining; nevertheless, the match continued.'],
    ['consequently', 'akibatnya', 'He missed the bus and consequently arrived late.'],
    ['arguably', 'bisa dibilang', 'She is arguably the best player in the team.'],
    ['notably', 'terutama / khususnya', 'Several countries, notably Japan, supported the plan.'],
    ['primarily', 'terutama / pada dasarnya', 'The course is primarily for adults.'],
  ],
  c2: [
    ['nuanced', 'bernuansa', 'She gave a nuanced answer to a complex question.'],
    ['meticulous', 'sangat teliti', 'He is meticulous about every detail.'],
    ['convey', 'menyampaikan', 'It is hard to convey emotion in a text message.'],
    ['scrutinize', 'meneliti dengan cermat', 'Auditors scrutinize every transaction.'],
    ['detrimental', 'merugikan', 'Lack of sleep is detrimental to your health.'],
    ['arbitrary', 'sewenang-wenang / acak', 'The rules seemed completely arbitrary.'],
    ['sophisticated', 'canggih / rumit', 'The software uses a sophisticated algorithm.'],
    ['ambiguous', 'ambigu', 'The instructions were ambiguous.'],
    ['compelling', 'meyakinkan / memikat', 'She made a compelling case for change.'],
    ['resilient', 'tangguh', 'Children are often more resilient than we think.'],
    ['articulate', 'fasih mengungkapkan', 'He is an articulate speaker.'],
    ['substantiate', 'membuktikan / memperkuat', 'Can you substantiate that claim with data?'],
    ['reconcile', 'mendamaikan / menyelaraskan', 'It is hard to reconcile these two views.'],
    ['exacerbate', 'memperparah', 'The heat will exacerbate the drought.'],
    ['dispel', 'menghilangkan (keraguan)', 'The report helped dispel the rumours.'],
    ['profound', 'mendalam', 'The book had a profound effect on me.'],
    ['impeccable', 'sempurna / tanpa cela', 'Her manners are impeccable.'],
    ['elusive', 'sulit dicapai / sulit dipahami', 'Success remained elusive for years.'],
    ['plausible', 'masuk akal', 'That is a plausible explanation.'],
    ['redundant', 'berlebihan / tidak diperlukan', 'Remove the redundant words from the sentence.'],
    ['paradigm', 'paradigma', 'The discovery led to a new paradigm in physics.'],
    ['rationale', 'dasar pemikiran', 'Explain the rationale behind your decision.'],
    ['discrepancy', 'ketidaksesuaian', 'There is a discrepancy between the two reports.'],
    ['interpretation', 'interpretasi', 'The poem is open to interpretation.'],
    ['phenomenon', 'fenomena', 'Global warming is a worldwide phenomenon.'],
    ['notwithstanding', 'meskipun / terlepas dari', 'Notwithstanding the delays, the project was a success.'],
    ['ostensibly', 'tampaknya / seolah-olah', 'He was ostensibly on holiday, but he worked every day.'],
    ['invariably', 'selalu / tanpa kecuali', 'The meetings invariably start late.'],
    ['intrinsically', 'secara intrinsik', 'Learning is intrinsically rewarding.'],
    ['conversely', 'sebaliknya', 'Some prefer mornings; conversely, others work best at night.'],
  ],
};
