// Japanese Clause Connect: reason, contrast, sequence and linking expressions, 30 per level.
// Conditionals (と/ば/たら/なら) live in Conditional Run; this bank covers the other connectors.
import type { ChoiceTuple } from '../mandarin/questions';

export const easyClauses: ChoiceTuple[] = [
  ['雨が 降っている____、出かけません。', 'Karena hujan, saya tidak keluar.', 'から', ['けど', 'のに', 'ながら'], 'Sebab', 'から = karena.'],
  ['この 店は 安い____、おいしくない。', 'Toko ini murah, tapi tidak enak.', 'けど', ['から', 'ので', 'し'], 'Kontras', 'けど = tetapi (lisan).'],
  ['朝ご飯を 食べ____、学校へ 行きます。', 'Saya sarapan, lalu pergi ke sekolah.', 'て', ['から', 'けど', 'し'], 'Urutan', 'Bentuk て = lalu.'],
  ['音楽を 聞き____、勉強します。', 'Saya belajar sambil mendengarkan musik.', 'ながら', ['から', 'て', 'けど'], 'Bersamaan', 'ながら = sambil.'],
  ['寝る ____、歯を 磨きます。', 'Sebelum tidur, saya menyikat gigi.', '前に', ['後で', 'から', 'ながら'], 'Waktu', 'Bentuk kamus + 前に = sebelum.'],
  ['ご飯を 食べた ____、散歩します。', 'Setelah makan, saya jalan-jalan.', '後で', ['前に', 'から', 'ながら'], 'Waktu', 'Bentuk た + 後で = setelah.'],
  ['子どもの ____、よく 海へ 行きました。', 'Waktu kecil, saya sering ke laut.', 'とき', ['前に', '後で', 'から'], 'Waktu', 'の + とき = ketika.'],
  ['頭が 痛い____、薬を 飲みました。', 'Karena sakit kepala, saya minum obat.', 'ので', ['けど', 'のに', 'し'], 'Sebab', 'ので = karena (lebih halus).'],
  ['この 部屋は 広い____、明るいです。', 'Kamar ini luas dan terang.', 'し', ['けど', 'のに', 'ながら'], 'Daftar alasan', 'し = lagi pula/dan.'],
  ['これは 私が 作った ____ です。', 'Ini kue yang saya buat.', 'ケーキ', ['から', 'けど', 'ので'], 'Klausa penjelas', 'Klausa bentuk biasa + kata benda.'],
  ['日本語は 難しい____、おもしろいです。', 'Bahasa Jepang sulit, tetapi menarik.', 'けど', ['から', 'ので', 'て'], 'Kontras', 'けど = tetapi.'],
  ['疲れた____、少し 休みましょう。', 'Karena lelah, ayo istirahat sebentar.', 'から', ['けど', 'のに', 'ながら'], 'Sebab', 'から + ajakan/perintah.'],
  ['シャワーを 浴び____、寝ました。', 'Saya mandi, lalu tidur.', 'て', ['から', 'けど', 'し'], 'Urutan', 'Bentuk て = lalu.'],
  ['テレビを 見____、ご飯を 食べます。', 'Saya makan sambil menonton TV.', 'ながら', ['て', 'から', 'けど'], 'Bersamaan', 'ながら = sambil.'],
  ['日本へ 来る ____、日本語を 勉強しました。', 'Sebelum datang ke Jepang, saya belajar bahasa Jepang.', '前に', ['後で', 'から', 'ながら'], 'Waktu', 'Bentuk kamus + 前に.'],
  ['授業が 終わった ____、図書館へ 行きます。', 'Setelah kelas selesai, saya ke perpustakaan.', '後で', ['前に', 'ながら', 'けど'], 'Waktu', 'Bentuk た + 後で.'],
  ['暇な ____、本を 読みます。', 'Ketika senggang, saya membaca buku.', 'とき', ['前に', '後で', 'から'], 'Waktu', 'Adjektiva な + とき.'],
  ['この 料理は おいしい____、安いです。', 'Masakan ini enak, lagi pula murah.', 'し', ['けど', 'のに', 'ので'], 'Daftar alasan', 'し = lagi pula.'],
  ['宿題が ある____、遊べません。', 'Karena ada PR, saya tidak bisa main.', 'から', ['けど', 'のに', 'ながら'], 'Sebab', 'から = karena.'],
  ['お金が ない____、旅行に 行きたい。', 'Tidak punya uang, tapi ingin jalan-jalan.', 'けど', ['から', 'ので', 'し'], 'Kontras', 'けど = tetapi.'],
  ['あそこに いる ____ は 私の 兄です。', 'Orang yang ada di sana adalah kakak saya.', '人', ['から', 'けど', 'ので'], 'Klausa penjelas', 'Klausa bentuk biasa + kata benda.'],
  ['手を 洗っ____ から、食べましょう。', 'Cuci tangan dulu, baru makan.', 'て', ['た', 'ない', 'る'], 'Urutan', 'Bentuk て + から = setelah.'],
  ['駅に 着いた ____、電話して ください。', 'Ketika sudah sampai stasiun, tolong telepon.', 'とき', ['前に', 'ながら', 'けど'], 'Waktu', 'Bentuk た + とき = ketika sudah.'],
  ['眠かった____、早く 寝ました。', 'Karena mengantuk, saya tidur lebih awal.', 'ので', ['けど', 'のに', 'し'], 'Sebab', 'ので = karena.'],
  ['歩き____ 電話するのは 危ないです。', 'Menelepon sambil berjalan itu berbahaya.', 'ながら', ['て', 'から', 'けど'], 'Bersamaan', 'ながら = sambil.'],
  ['母が 作った ____ は おいしいです。', 'Masakan yang dibuat ibu enak.', '料理', ['から', 'けど', 'し'], 'Klausa penjelas', 'Klausa bentuk biasa + kata benda.'],
  ['寒い____、窓を 閉めました。', 'Karena dingin, saya menutup jendela.', 'から', ['けど', 'のに', 'ながら'], 'Sebab', 'から = karena.'],
  ['電車に 乗っ____、会社へ 行きます。', 'Saya naik kereta, lalu ke kantor.', 'て', ['から', 'けど', 'し'], 'Urutan', 'Bentuk て = lalu.'],
  ['風邪を ひいた ____、学校を 休みました。', 'Karena masuk angin, saya tidak masuk sekolah.', 'ので', ['けど', 'のに', 'ながら'], 'Sebab', 'ので = karena.'],
  ['彼は 背が 高い____、足も 速いです。', 'Dia tinggi, kakinya juga cepat.', 'し', ['けど', 'のに', 'ので'], 'Daftar alasan', 'し … も = lagi pula.'],
];

export const mediumClauses: ChoiceTuple[] = [
  ['一生懸命 勉強した____、試験に 落ちた。', 'Padahal sudah belajar keras, saya gagal ujian.', 'のに', ['ので', 'から', 'し'], 'Kecewa', 'のに = padahal.'],
  ['雨が 降った。____、試合は 中止に なった。', 'Hujan turun. Karena itu, pertandingan dibatalkan.', 'それで', ['しかし', 'それに', 'でも'], 'Akibat', 'それで = karena itu.'],
  ['この 店は 安い。____、店員も 親切だ。', 'Toko ini murah. Selain itu, pelayannya ramah.', 'それに', ['しかし', 'それで', 'だから'], 'Tambahan', 'それに = selain itu.'],
  ['彼は 頭が いい。____、努力しない。', 'Dia pintar. Tetapi, dia tidak berusaha.', 'しかし', ['それに', 'それで', 'だから'], 'Kontras', 'しかし = tetapi (formal).'],
  ['明日は テストだ。____、今日は 早く 寝よう。', 'Besok ujian. Jadi, hari ini tidur lebih awal.', 'だから', ['でも', 'それに', 'ところが'], 'Akibat', 'だから = jadi.'],
  ['晴れると 思った。____、雨が 降ってきた。', 'Saya kira akan cerah. Ternyata, hujan turun.', 'ところが', ['だから', 'それに', 'それで'], 'Di luar dugaan', 'ところが = ternyata (di luar dugaan).'],
  ['日本語が 話せる ____ に なりたいです。', 'Saya ingin menjadi bisa berbicara bahasa Jepang.', 'よう', ['ため', 'こと', 'の'], 'Perubahan', 'ように なる = menjadi (bisa).'],
  ['留学する ____ に、お金を 貯めています。', 'Saya menabung untuk kuliah di luar negeri.', 'ため', ['よう', 'こと', 'の'], 'Tujuan', 'ために = untuk.'],
  ['日本語を 話す ____ は 楽しいです。', 'Berbicara bahasa Jepang itu menyenangkan.', 'の', ['ため', 'よう', 'し'], 'Nominalisasi', 'V + の = hal (melakukan) ….'],
  ['私の 趣味は 写真を 撮る ____ です。', 'Hobi saya adalah memotret.', 'こと', ['ため', 'よう', 'し'], 'Nominalisasi', 'V + こと = hal (melakukan) ….'],
  ['彼は 何も 言わ____ 帰った。', 'Dia pulang tanpa berkata apa-apa.', 'ないで', ['なくて', 'ないと', 'なければ'], 'Tanpa', 'Bentuk ない + で = tanpa.'],
  ['宿題が 多く____、大変です。', 'PR-nya banyak, jadi berat.', 'て', ['ても', 'たら', 'ながら'], 'Sebab ringan', 'Bentuk て (adj) = karena.'],
  ['電車が 来る ____ 、本を 読んで いました。', 'Selama menunggu kereta datang, saya membaca buku.', 'まで', ['までに', 'から', 'ので'], 'Durasi', 'まで = sampai/selama.'],
  ['先生が 来る ____、教室を 掃除しましょう。', 'Sebelum guru datang, ayo bersihkan kelas.', 'までに', ['まで', 'ながら', 'のに'], 'Tenggat', 'までに = sebelum (tenggat).'],
  ['子どもが 寝ている ____ に、洗濯を しました。', 'Selama anak tidur, saya mencuci baju.', '間', ['前', '後', 'まで'], 'Selama', '間に = selagi (dalam rentang).'],
  ['ドアを 開けた ____、猫が 入ってきた。', 'Begitu saya membuka pintu, kucing masuk.', 'ら', ['り', 'て', 'し'], 'Penemuan', 'Bentuk た + ら (lampau) = ketika …, ternyata.'],
  ['映画を 見____、泣いて しまった。', 'Saya menonton film, dan akhirnya menangis.', 'て', ['ても', 'たら', 'ながら'], 'Sebab-akibat', 'Bentuk て = lalu/sehingga.'],
  ['安い ____ 品質が いい。', 'Walaupun murah, kualitasnya bagus.', 'わりに', ['ために', 'ように', 'ことに'], 'Tidak sebanding', 'わりに = walaupun (tidak sebanding).'],
  ['日本に 行った ____ が あります。', 'Saya pernah ke Jepang.', 'こと', ['の', 'ため', 'よう'], 'Pengalaman', 'Bentuk た + ことがある.'],
  ['彼が 来ない ____ を 知っていましたか。', 'Apakah kamu tahu bahwa dia tidak datang?', 'の', ['ため', 'よう', 'し'], 'Klausa nomina', 'Klausa + の + を 知る.'],
  ['疲れていた____、仕事を 続けた。', 'Meskipun lelah, saya terus bekerja.', 'けれども', ['ので', 'から', 'し'], 'Kontras', 'けれども = meskipun/tetapi (formal).'],
  ['駅に 着いた。____、友達に 電話した。', 'Saya sampai di stasiun. Kemudian, menelepon teman.', 'それから', ['しかし', 'ところが', 'それに'], 'Urutan', 'それから = kemudian.'],
  ['この 本は おもしろい。____、少し 高い。', 'Buku ini menarik. Tapi, agak mahal.', 'でも', ['だから', 'それで', 'それに'], 'Kontras lisan', 'でも = tapi (awal kalimat).'],
  ['大雪が 降った。____、電車が 止まった。', 'Salju lebat turun. Akibatnya, kereta berhenti.', 'そのため', ['しかし', 'それに', 'でも'], 'Akibat formal', 'そのため = oleh karena itu.'],
  ['父は 医者です。____、母は 先生です。', 'Ayah dokter. Sementara itu, ibu guru.', '一方', ['だから', 'それで', 'ところが'], 'Perbandingan', '一方 = sementara itu.'],
  ['この 道は 狭い____ 暗いので、夜は 危ない。', 'Jalan ini sempit, lagi pula gelap, jadi berbahaya di malam hari.', 'し', ['けど', 'のに', 'ながら'], 'Daftar alasan', 'し = lagi pula.'],
  ['家に 帰って ____、宿題を します。', 'Setelah pulang ke rumah, saya mengerjakan PR.', 'から', ['ので', 'けど', 'のに'], 'Urutan', 'Bentuk て + から = setelah.'],
  ['兄は 勉強している ____、弟は 遊んでいる。', 'Kakak sedang belajar, sedangkan adik bermain.', 'のに', ['ので', 'から', 'し'], 'Kontras', 'のに = padahal/sedangkan (bernada tidak puas).'],
  ['電気を つけた ____ 寝て しまった。', 'Saya tertidur dengan lampu masih menyala.', 'まま', ['ため', 'よう', 'こと'], 'Keadaan tetap', 'Bentuk た + まま = dalam keadaan ….'],
  ['日本の 生活に 慣れる ____ 、時間が かかった。', 'Butuh waktu untuk terbiasa dengan kehidupan di Jepang.', 'のに', ['ので', 'から', 'し'], 'Keperluan', 'V + のに + 時間がかかる = untuk ….'],
];

export const hardClauses: ChoiceTuple[] = [
  ['彼は 先生である ____、作家でも ある。', 'Dia seorang guru sekaligus penulis.', 'と同時に', ['にもかかわらず', 'からには', 'ものの'], 'Sekaligus', 'と同時に = sekaligus.'],
  ['努力した ____、成功できた。', 'Justru karena berusaha, bisa berhasil.', 'からこそ', ['ものの', 'くせに', 'わりに'], 'Penegasan sebab', 'からこそ = justru karena.'],
  ['約束した ____、守らなければ ならない。', 'Karena sudah berjanji, harus ditepati.', '以上', ['ものの', 'くせに', 'わりに'], 'Konsekuensi', '以上 = karena sudah ….'],
  ['頑張った ____、結果は 出なかった。', 'Meskipun sudah berusaha, hasilnya tidak muncul.', 'ものの', ['からこそ', '以上', 'ばかりに'], 'Konsesi formal', 'ものの = meskipun (formal).'],
  ['知っている ____ 教えて くれない。', 'Padahal tahu, dia tidak mau memberi tahu.', 'くせに', ['からこそ', '以上', 'ために'], 'Kritik', 'くせに = padahal (mencela).'],
  ['雨 ____ 、試合は 行われた。', 'Meskipun hujan, pertandingan tetap dilaksanakan.', 'にもかかわらず', ['からこそ', '以上', 'ばかりに'], 'Konsesi formal', 'にもかかわらず = meskipun.'],
  ['油断した ____ 、試合に 負けた。', 'Gara-gara lengah, kalah dalam pertandingan.', 'ばかりに', ['からこそ', 'ものの', 'わりに'], 'Penyesalan', 'ばかりに = gara-gara (hal itu saja).'],
  ['彼は 笑い ____ 話を 聞いていた。', 'Dia mendengarkan cerita sambil tertawa.', 'つつ', ['ものの', 'くせに', 'ばかりに'], 'Bersamaan formal', 'つつ = sambil (formal).'],
  ['悪いと 知り ____ 、やめられない。', 'Meskipun tahu itu buruk, tidak bisa berhenti.', 'つつも', ['からこそ', '以上', 'ばかりに'], 'Konsesi', 'つつも = meskipun (formal).'],
  ['駅に 着く ____ 、雨が 降りだした。', 'Begitu sampai di stasiun, hujan mulai turun.', 'やいなや', ['ものの', '以上', 'くせに'], 'Seketika', 'やいなや = begitu … langsung.'],
  ['家に 着いた ____ 、電話が 鳴った。', 'Begitu sampai di rumah, telepon berbunyi.', 'とたん', ['ものの', '以上', 'わりに'], 'Seketika', 'た + とたん = tepat saat itu.'],
  ['日本に 来て ____ 、ずっと 東京に 住んでいる。', 'Sejak datang ke Jepang, saya terus tinggal di Tokyo.', '以来', ['以上', 'ものの', 'わりに'], 'Sejak', 'て + 以来 = sejak.'],
  ['経済が 発展する ____ 、環境問題が 深刻に なった。', 'Seiring berkembangnya ekonomi, masalah lingkungan menjadi serius.', 'につれて', ['について', 'にとって', 'に対して'], 'Seiring', 'につれて = seiring.'],
  ['年を とる ____ 、体力が 落ちる。', 'Seiring bertambahnya usia, stamina menurun.', 'とともに', ['ものの', '以上', 'くせに'], 'Seiring', 'とともに = seiring/bersamaan.'],
  ['彼は 何も 知らない ____ 、平気な 顔を している。', 'Dia bersikap tenang seolah-olah tidak tahu apa-apa.', 'かのように', ['からこそ', 'ものの', '以上'], 'Seolah-olah', 'かのように = seolah-olah.'],
  ['勉強 ____ 、遊んで ばかり いる。', 'Bukannya belajar, malah main terus.', 'どころか', ['ものの', '以上', 'からこそ'], 'Kebalikan', 'どころか = bukannya …, malah ….'],
  ['この 料理は 見た目 ____ 、味も いい。', 'Masakan ini tidak hanya tampilannya, rasanya juga enak.', 'だけでなく', ['どころか', 'ものの', 'くせに'], 'Tambahan', 'だけでなく … も = tidak hanya … juga.'],
  ['子ども ____ 、大人も 楽しめる 映画だ。', 'Film yang tidak hanya untuk anak-anak, orang dewasa pun bisa menikmatinya.', 'はもちろん', ['どころか', 'くせに', 'ものの'], 'Apalagi', 'はもちろん = tentu saja … (dan juga).'],
  ['あれだけ 練習した ____ 、優勝できなかった。', 'Sudah berlatih sebanyak itu, tetap tidak juara.', 'のに', ['ので', 'から', 'し'], 'Kecewa', 'のに = padahal.'],
  ['計画を 立てて ____ 、実行しない。', 'Membuat rencana, tapi tidak pernah dijalankan.', 'も', ['は', 'が', 'を'], 'Konsesi', 'て + も = meskipun ….'],
  ['社長は 忙しい ____ 、毎日 社員と 話す。', 'Walaupun sibuk, direktur berbicara dengan karyawan setiap hari.', 'ながらも', ['ばかりに', 'からこそ', '以上'], 'Konsesi', 'ながらも = walaupun.'],
  ['この 問題は 複雑な ____ 、解決に 時間が かかる。', 'Karena masalah ini rumit, penyelesaiannya butuh waktu.', 'ため', ['くせに', 'ものの', 'わりに'], 'Sebab formal', 'ため = karena (formal).'],
  ['彼は 疲れて いる ____ 、休もうと しない。', 'Padahal dia lelah, dia tidak mau beristirahat.', 'のに', ['ので', 'から', 'し'], 'Kecewa', 'のに = padahal.'],
  ['説明書を 読む ____ 、すぐ 使い始めた。', 'Tanpa membaca petunjuk, dia langsung mulai memakai.', 'ことなく', ['ものの', 'くせに', 'ばかりに'], 'Tanpa', 'ことなく = tanpa (formal).'],
  ['彼女は 歌手 ____ 、女優としても 有名だ。', 'Dia terkenal tidak hanya sebagai penyanyi, juga sebagai aktris.', 'としてだけでなく', ['どころか', 'くせに', 'ものの'], 'Peran ganda', 'としてだけでなく … も.'],
  ['この 町は 便利な ____ 、家賃が 高い。', 'Kota ini praktis, sebaliknya sewa rumahnya mahal.', '反面', ['ため', 'ばかりに', '以上'], 'Sisi sebaliknya', '反面 = di sisi lain.'],
  ['天気が いい ____ 、山に 登ろう。', 'Selagi cuaca bagus, ayo mendaki gunung.', 'うちに', ['ものの', 'くせに', 'ばかりに'], 'Selagi', 'うちに = selagi.'],
  ['彼の 話を 聞く ____ 、涙が 出てきた。', 'Selama mendengarkan ceritanya, air mata keluar.', 'うちに', ['ものの', 'くせに', '以上'], 'Tanpa sadar', 'うちに = dalam proses …, (tanpa sadar).'],
  ['先生の 説明 ____ 、作業を 進めた。', 'Saya melanjutkan pekerjaan sesuai penjelasan guru.', 'どおりに', ['ものの', 'くせに', 'ばかりに'], 'Sesuai', 'どおりに = sesuai.'],
  ['食べ ____ 、太らない。', 'Meskipun makan, tidak gemuk.', 'ても', ['たら', 'れば', 'ながら'], 'Konsesi', 'て + も = meskipun.'],
];
