// Japanese Conditional Run: と, ば, たら, なら, ても and friends, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, type, rule]
// Type and rule are shown before answering, so they are written in Indonesian/romaji only.
import type { ChoiceTuple } from '../mandarin/questions';

const NATURAL = 'bentuk kamus + (syarat alami): selalu terjadi';
const TARA = 'bentuk ta + (syarat): kalau sudah / kalau';
const EBA = 'akhiran -e + (syarat): kalau';
const NARA = 'kata benda/bentuk biasa + (syarat): kalau memang';
const EVEN = 'bentuk te + (konsesi): meskipun';
const NOKO = 'padahal …';

export const easyConditionals: ChoiceTuple[] = [
  ['春に なる ____、桜が 咲きます。', 'Kalau musim semi tiba, sakura mekar.', 'と', ['のに', 'けど', 'ても'], 'Syarat alami', NATURAL],
  ['駅に 着い____、電話して ください。', 'Kalau sudah sampai stasiun, tolong telepon.', 'たら', ['ても', 'たり', 'たの'], 'Syarat selesai', TARA],
  ['この ボタンを 押す ____、ドアが 開きます。', 'Kalau tombol ini ditekan, pintu terbuka.', 'と', ['のに', 'けど', 'ても'], 'Syarat alami', NATURAL],
  ['安けれ____、買います。', 'Kalau murah, saya beli.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['雨が 降っ____、行きません。', 'Kalau hujan, saya tidak pergi.', 'たら', ['ても', 'たり', 'たの'], 'Syarat', TARA],
  ['時間が あれ____、手伝います。', 'Kalau ada waktu, saya bantu.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['右に 曲がる ____、銀行が あります。', 'Kalau belok kanan, ada bank.', 'と', ['ので', 'けど', 'のに'], 'Arah jalan', NATURAL],
  ['雨が 降っ____、試合は あります。', 'Meskipun hujan, pertandingan tetap ada.', 'ても', ['たら', 'たり', 'たの'], 'Konsesi', EVEN],
  ['高く____、買います。', 'Meskipun mahal, saya beli.', 'ても', ['ば', 'と', 'たら'], 'Konsesi', EVEN],
  ['日本へ 行く ____、京都が いいですよ。', 'Kalau (mau) ke Jepang, Kyoto bagus lho.', 'なら', ['ので', 'けど', 'のに'], 'Saran', NARA],
  ['わからなかっ____、聞いて ください。', 'Kalau tidak mengerti, silakan bertanya.', 'たら', ['ても', 'たり', 'たの'], 'Syarat', TARA],
  ['窓を 開け____、海が 見えました。', 'Ketika membuka jendela, ternyata terlihat laut.', 'たら', ['ても', 'たり', 'ないで'], 'Penemuan', 'bentuk ta + (syarat) dalam lampau: ketika …, ternyata'],
  ['ここを まっすぐ 行く ____、駅です。', 'Kalau lurus dari sini, sampai stasiun.', 'と', ['のに', 'けど', 'ので'], 'Arah jalan', NATURAL],
  ['寒けれ____、窓を 閉めて ください。', 'Kalau dingin, tolong tutup jendela.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['暇 ____、遊びに 来て ください。', 'Kalau senggang, mainlah ke sini.', 'なら', ['ので', 'のに', 'けど'], 'Syarat', NARA],
  ['この 薬を 飲め____、治りますよ。', 'Kalau minum obat ini, sembuh lho.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['いくら 呼ん____、返事が ない。', 'Berapa kali pun dipanggil, tidak ada jawaban.', 'でも', ['だら', 'だり', 'での'], 'Konsesi', EVEN],
  ['春休みに なっ____、旅行しましょう。', 'Kalau sudah libur musim semi, ayo jalan-jalan.', 'たら', ['ても', 'たり', 'たの'], 'Syarat selesai', TARA],
  ['安く____、いい ものを 買いたい。', 'Meskipun tidak murah, saya ingin membeli barang bagus.', 'なくても', ['なければ', 'なくて', 'ないと'], 'Konsesi negatif', 'bentuk nai → nakute + (konsesi)'],
  ['お金が なけれ____、何も 買えません。', 'Kalau tidak punya uang, tidak bisa beli apa-apa.', 'ば', ['と', 'て', 'た'], 'Syarat negatif', EBA],
  ['二に 三を 足す ____、五に なります。', 'Dua ditambah tiga, jadi lima.', 'と', ['のに', 'けど', 'ので'], 'Kebenaran umum', NATURAL],
  ['もし 宝くじが 当たっ____、何を しますか。', 'Kalau menang lotre, apa yang akan kamu lakukan?', 'たら', ['ても', 'たり', 'たの'], 'Andaian', TARA],
  ['天気が よけれ____、山に 登ります。', 'Kalau cuacanya bagus, saya mendaki gunung.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['疲れ____、休んで ください。', 'Kalau lelah, istirahatlah.', 'たら', ['ても', 'たり', 'ると'], 'Syarat + permintaan', TARA],
  ['毎日 練習す____、上手に なります。', 'Kalau berlatih setiap hari, akan mahir.', 'れば', ['れて', 'った', 'ろ'], 'Syarat', EBA],
  ['雨 ____、中止です。', 'Kalau hujan, dibatalkan.', 'なら', ['ので', 'けど', 'のに'], 'Syarat kata benda', NARA],
  ['頑張っ____、できなかった。', 'Padahal sudah berusaha, tetap tidak bisa.', 'たのに', ['たら', 'たり', 'ていて'], 'Kecewa', NOKO],
  ['テレビを 見____、ご飯を 食べます。', 'Saya makan sambil menonton TV.', 'ながら', ['たら', 'ても', 'れば'], 'Bersamaan', 'batang masu + (bersamaan): sambil'],
  ['もっと 勉強すれ____ よかった。', 'Seharusnya saya belajar lebih banyak.', 'ば', ['と', 'て', 'た'], 'Penyesalan', EBA + ' + yokatta'],
  ['わからない ____、いつも 先生に 聞きます。', 'Kalau tidak mengerti, saya selalu bertanya pada guru.', 'と', ['のに', 'けど', 'ても'], 'Kebiasaan', NATURAL],
];

export const mediumConditionals: ChoiceTuple[] = [
  ['練習すれば する ____ 上手に なる。', 'Makin berlatih, makin mahir.', 'ほど', ['まで', 'だけ', 'しか'], 'Semakin … semakin', 'syarat -eba + bentuk kamus + (tingkat)'],
  ['たとえ 失敗し____、諦めない。', 'Sekalipun gagal, saya tidak menyerah.', 'ても', ['たら', 'たり', 'ながら'], 'Konsesi', 'tatoe + bentuk te + (konsesi)'],
  ['時間 ____ あれば、できます。', 'Asalkan ada waktu, bisa.', 'さえ', ['しか', 'だけ', 'まで'], 'Asalkan', 'kata benda + (asalkan) + syarat -eba'],
  ['早く 行か____、間に合わない。', 'Kalau tidak cepat pergi, tidak akan keburu.', 'ないと', ['なくても', 'ないで', 'ないのに'], 'Syarat wajib', 'bentuk nai + (syarat): kalau tidak …'],
  ['勉強し____、合格できない。', 'Kalau tidak belajar, tidak bisa lulus.', 'なければ', ['なくても', 'ないで', 'ないのに'], 'Syarat negatif', 'bentuk nai → -nakereba'],
  ['雨が 降っている ____、出かけた。', 'Padahal sedang hujan, dia keluar.', 'のに', ['ので', 'なら', 'ば'], 'Kontras', NOKO],
  ['安い ____ といって、いい とは 限らない。', 'Belum tentu bagus hanya karena murah.', 'から', ['ので', 'のに', 'けど'], 'Belum tentu', 'hanya karena …, belum tentu'],
  ['もし 明日 晴れた____、ピクニックに 行こう。', 'Kalau besok cerah, ayo piknik.', 'ら', ['り', 'ので', 'のに'], 'Syarat', TARA],
  ['行く ____ 早い ほうが いい。', 'Kalau mau pergi, lebih cepat lebih baik.', 'なら', ['と', 'ので', 'のに'], 'Saran', NARA],
  ['仕事が 終わっ____、飲みに 行きませんか。', 'Kalau pekerjaan sudah selesai, mau minum?', 'たら', ['ても', 'たり', 'たのに'], 'Syarat selesai', TARA],
  ['この 薬を 飲む ____、眠く なります。', 'Kalau minum obat ini, jadi mengantuk.', 'と', ['のに', 'けど', 'ので'], 'Akibat pasti', NATURAL],
  ['説明を 聞い____、まだ わからない。', 'Meskipun sudah mendengar penjelasan, masih belum paham.', 'ても', ['たら', 'たり', 'ていて'], 'Konsesi', EVEN],
  ['疲れている ____、休んだら？', 'Kalau memang capek, istirahat saja?', 'なら', ['のに', 'けど', 'ても'], 'Saran', NARA],
  ['一生懸命 頑張れ____、きっと 成功する。', 'Kalau berusaha keras, pasti berhasil.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['お金が ある ____、旅行に 行けるのに。', 'Seandainya punya uang, bisa jalan-jalan.', 'なら', ['ので', 'けど', 'から'], 'Andaian', NARA],
  ['メールを 送っ____、返事が 来なかった。', 'Padahal sudah mengirim email, tidak ada balasan.', 'たのに', ['たり', 'ていて', 'たので'], 'Kecewa', NOKO],
  ['雨が 止ま____、出かけられない。', 'Kalau hujan tidak berhenti, tidak bisa keluar.', 'ないと', ['なくても', 'ないで', 'ないのに'], 'Syarat wajib', 'bentuk nai + (syarat): kalau tidak …'],
  ['子ども ____、そんな ことは 知っている。', 'Anak-anak pun tahu hal itu.', 'でも', ['なら', 'しか', 'だけ'], 'Bahkan', 'kata benda + (bahkan) … pun'],
  ['駅まで 歩く ____、二十分 かかります。', 'Kalau jalan kaki ke stasiun, butuh 20 menit.', 'と', ['のに', 'けど', 'ても'], 'Akibat pasti', NATURAL],
  ['ちゃんと 説明すれ____、彼も わかって くれる はずだ。', 'Kalau dijelaskan dengan baik, dia pasti mengerti.', 'ば', ['と', 'て', 'た'], 'Syarat', EBA],
  ['もう 少し 安けれ____、買ったのに。', 'Seandainya sedikit lebih murah, sudah saya beli.', 'ば', ['と', 'て', 'た'], 'Kontrafaktual', EBA],
  ['薬 ____ 飲めば、治ります。', 'Asalkan minum obat, sembuh.', 'さえ', ['しか', 'だけ', 'まで'], 'Asalkan', 'kata benda + (asalkan) + syarat -eba'],
  ['どんなに 忙しく____、朝ご飯は 食べます。', 'Sesibuk apa pun, saya tetap sarapan.', 'ても', ['たら', 'て', 'ば'], 'Konsesi', 'donna ni + bentuk te + (konsesi)'],
  ['日本語を 勉強する ____、まず ひらがなから 始めましょう。', 'Kalau mau belajar bahasa Jepang, mulailah dari hiragana.', 'なら', ['と', 'ので', 'のに'], 'Saran', NARA],
  ['知って いれ____、教えたのに。', 'Seandainya tahu, sudah saya beri tahu.', 'ば', ['と', 'て', 'た'], 'Kontrafaktual', EBA],
  ['ボタンを 押し____、何も 起きなかった。', 'Saya menekan tombolnya, tetapi tidak terjadi apa-apa.', 'たが', ['たり', 'たので', 'ていて'], 'Kontras', 'bentuk ta + (tetapi)'],
  ['雨でも 雪 ____、毎日 走ります。', 'Hujan maupun salju, saya lari setiap hari.', 'でも', ['なら', 'しか', 'ほど'], 'Apa pun', 'A demo B (…) = baik A maupun B'],
  ['お酒を 飲んだ____、運転しては いけません。', 'Kalau sudah minum alkohol, tidak boleh menyetir.', 'ら', ['り', 'ので', 'のに'], 'Syarat selesai', TARA],
  ['もし 私が 鳥 ____、空を 飛びたい。', 'Seandainya saya burung, saya ingin terbang.', 'だったら', ['でも', 'なのに', 'なので'], 'Andaian', 'kata benda + bentuk ta + (syarat)'],
  ['いくら 頼ま____、それは できません。', 'Seberapa pun diminta, itu tidak bisa.', 'れても', ['れたら', 'れば', 'れて'], 'Konsesi', 'pasif + bentuk te + (konsesi)'],
];

export const hardConditionals: ChoiceTuple[] = [
  ['本当の ことを 言お____、彼は 怒るだろう。', 'Kalau sampai berkata jujur, dia pasti marah.', 'うものなら', ['うとも', 'うのに', 'うから'], 'Kalau sampai', 'bentuk volisional + (kalau sampai, akibat buruk)'],
  ['実際に 見____、何とも 言えない。', 'Kalau belum melihat langsung, tidak bisa berkomentar.', 'ないことには', ['ないうちに', 'なくても', 'ないのに'], 'Prasyarat', 'kalau tidak … dulu, tidak bisa'],
  ['もし 百万円 ある ____、何に 使いますか。', 'Seandainya ada sejuta yen, untuk apa?', 'としたら', ['としても', 'とともに', 'とおりに'], 'Andaian', 'seandainya (asumsi)'],
  ['引き受けた ____、最後まで やります。', 'Karena sudah menyanggupi, akan saya selesaikan.', 'からには', ['からといって', 'からこそ', 'からすると'], 'Konsekuensi', 'karena sudah …, harus sampai tuntas'],
  ['雨が 降らない ____、試合は 行われます。', 'Selama tidak hujan, pertandingan diadakan.', '限り', ['うちに', 'ために', 'わりに'], 'Selama', 'selama (syarat terpenuhi)'],
  ['ドアを 開けた ____、猫が 飛び出した。', 'Begitu pintu dibuka, kucing melompat keluar.', 'とたん', ['とおり', 'ところで', 'ばかりに'], 'Seketika', 'bentuk ta + (begitu …, langsung)'],
  ['弟は 一度 寝た____、朝まで 起きない。', 'Adik saya sekali tertidur, tidak bangun sampai pagi.', 'ら最後', ['らいいのに', 'りして', 'ばかり'], 'Sekali terjadi', 'bentuk ta + (sekali …, tidak bisa kembali)'],
  ['できる ____、もう一度 学生時代に 戻りたい。', 'Kalau bisa, ingin kembali ke masa sekolah.', 'ものなら', ['ものの', 'ことに', 'わりに'], 'Andaian mustahil', 'kalau saja bisa …'],
  ['たとえ 反対され____、私は 行く。', 'Sekalipun ditentang, saya tetap pergi.', 'ようと', ['たら', 'れば', 'ので'], 'Konsesi kuat', 'tatoe + volisional + (sekalipun)'],
  ['彼が 来ても 来____、会議は 始めます。', 'Dia datang atau tidak, rapat tetap dimulai.', 'なくても', ['なければ', 'ないなら', 'ないので'], 'Apa pun', '-te mo + -nakute mo = … atau tidak, tetap'],
  ['これだけ 練習した ____、優勝したい。', 'Setelah berlatih sebanyak ini, tentu ingin juara.', '以上', ['うちに', 'わりに', 'ものの'], 'Konsekuensi', 'karena sudah …, tentu'],
  ['急いで いる ____、先に 帰って いいよ。', 'Kalau memang sedang buru-buru, pulang duluan saja.', 'のなら', ['のに', 'けれど', 'ものの'], 'Kalau memang', 'bentuk biasa + no + (syarat)'],
  ['知らなかった ____、失礼な ことを 言って しまった。', 'Gara-gara tidak tahu, saya terlanjur berkata tidak sopan.', 'ばかりに', ['からには', 'ものなら', '限り'], 'Penyesalan', 'gara-gara satu hal itu saja'],
  ['彼の 助け ____、成功しなかっただろう。', 'Tanpa bantuannya, tidak akan berhasil.', 'なしには', ['とともに', 'にしては', 'について'], 'Tanpa', 'tanpa …, tidak mungkin'],
  ['もし あの とき 彼に 会わなかった____、今の 私は いない。', 'Seandainya waktu itu tidak bertemu dia, saya yang sekarang tidak ada.', 'ら', ['り', 'ので', 'のに'], 'Kontrafaktual', TARA],
  ['この 店は 安い ____、品質が いい。', 'Toko ini murah, tapi kualitasnya bagus (di luar dugaan).', 'わりに', ['ばかりに', 'からには', '限り'], 'Di luar dugaan', 'tidak sebanding dengan …'],
  ['頑張った ____、結果は よくなかった。', 'Meskipun sudah berusaha, hasilnya tidak bagus.', 'ものの', ['ばかりに', 'からには', '限り'], 'Konsesi formal', 'meskipun (formal)'],
  ['社長の 許可が ない ____、使えません。', 'Tanpa izin direktur, tidak bisa dipakai.', '限り', ['うちに', 'わりに', 'ものの'], 'Selama tidak', 'selama tidak …'],
  ['子どもで ____、こんな 問題は 解ける。', 'Bahkan anak kecil pun bisa mengerjakan soal ini.', 'さえ', ['こそ', 'ほど', 'まで'], 'Bahkan', 'bahkan … pun'],
  ['これが 本物だ ____、値段は 百万円以上だろう。', 'Kalau ini asli, harganya pasti di atas sejuta yen.', 'とすれば', ['としても', 'とともに', 'とおりに'], 'Asumsi', 'kalau diasumsikan …'],
  ['天気が よけれ____ よかったのに。', 'Seandainya cuaca bagus, alangkah baiknya.', 'ば', ['ど', 'て', 'と'], 'Penyesalan', EBA + ' + yokatta noni'],
  ['一歩 間違え____、大事故に なる ところだった。', 'Salah sedikit saja, bisa jadi kecelakaan besar.', 'れば', ['ても', 'て', 'たり'], 'Nyaris', EBA + ' + tokoro datta'],
  ['雨が 降り そうな ____、傘を 持って いこう。', 'Karena kelihatannya akan hujan, ayo bawa payung.', 'ので', ['のに', 'けど', 'ものの'], 'Alasan', 'karena (alasan objektif)'],
  ['年を 取る ____、体力が 落ちる。', 'Seiring bertambah usia, stamina menurun.', 'につれて', ['について', 'にとって', 'に対して'], 'Seiring', 'seiring dengan …'],
  ['たとえ 冗談に ____、言って いい ことと 悪い ことが ある。', 'Sekalipun bercanda, ada hal yang boleh dan tidak boleh dikatakan.', 'しても', ['したら', 'すれば', 'しては'], 'Konsesi', 'tatoe + … + (sekalipun)'],
  ['この 機会を 逃し____、二度と チャンスは ない。', 'Kalau melewatkan kesempatan ini, tidak akan ada peluang lagi.', 'たら', ['ても', 'たり', 'つつ'], 'Syarat', TARA],
  ['ちょっと 考え____ わかる はずだ。', 'Kalau dipikir sedikit saja, pasti paham.', 'れば', ['ても', 'たり', 'つつ'], 'Syarat', EBA],
  ['体に 悪いと 知り____、たばこを やめられない。', 'Meskipun tahu buruk untuk tubuh, tidak bisa berhenti merokok.', 'ながら', ['たら', 'ても', 'ば'], 'Konsesi', 'batang masu + (meskipun)'],
  ['君が 行く ____、僕も 行く。', 'Kalau kamu pergi, aku juga pergi.', 'なら', ['のに', 'けど', 'ものの'], 'Syarat', NARA],
  ['合格 できる ____、毎晩 遅くまで 勉強した。', 'Supaya bisa lulus, saya belajar sampai larut setiap malam.', 'ように', ['ために', 'ことに', 'わりに'], 'Tujuan', 'potensial + (supaya)'],
];
