// Japanese Conjugation Master (verb-forms mode): pick the right form of a dictionary verb, 30 per level.
// [dictionary form, romaji, meaning, group, form, answer, three wrong forms]
// Wrong forms are the slips learners actually make: wrong group (帰ます), wrong te-form sound change (書きて),
// or a real neighbouring form (書かれる vs 書ける).
export type VerbGroup = 'I' | 'II' | 'III';
export type ConjugationTuple = [dictionary: string, romaji: string, meaning: string, group: VerbGroup, form: string, answer: string, wrong: [string, string, string]];

export const FORM_COPY: Record<string, { label: string; pattern: string; gloss: string }> = {
  'ます': { label: 'Bentuk ます', pattern: 'sopan, sekarang/akan', gloss: 'sopan' },
  'ません': { label: 'Bentuk ません', pattern: 'sopan, negatif', gloss: 'sopan, tidak' },
  'ました': { label: 'Bentuk ました', pattern: 'sopan, lampau', gloss: 'sopan, sudah' },
  'ませんでした': { label: 'Bentuk ませんでした', pattern: 'sopan, negatif lampau', gloss: 'sopan, tidak (lampau)' },
  'て': { label: 'Bentuk て', pattern: 'penyambung / permintaan', gloss: 'bentuk te' },
  'た': { label: 'Bentuk た', pattern: 'biasa, lampau', gloss: 'biasa, sudah' },
  'ない': { label: 'Bentuk ない', pattern: 'biasa, negatif', gloss: 'biasa, tidak' },
  'なかった': { label: 'Bentuk なかった', pattern: 'biasa, negatif lampau', gloss: 'biasa, tidak (lampau)' },
  Potensial: { label: 'Bentuk potensial', pattern: 'bisa / mampu', gloss: 'bisa' },
  Pasif: { label: 'Bentuk pasif', pattern: 'di- (dikenai tindakan)', gloss: 'di-' },
  Kausatif: { label: 'Bentuk kausatif', pattern: 'menyuruh / membiarkan', gloss: 'menyuruh' },
  'Kausatif-pasif': { label: 'Bentuk kausatif-pasif', pattern: 'disuruh (terpaksa)', gloss: 'disuruh' },
  Volisional: { label: 'Bentuk volisional', pattern: 'ayo / berniat', gloss: 'ayo' },
  'Syarat ば': { label: 'Bentuk syarat -eba', pattern: 'kalau …', gloss: 'kalau' },
  Perintah: { label: 'Bentuk perintah', pattern: 'perintah kasar', gloss: 'perintah' },
};

export const easyConjugations: ConjugationTuple[] = [
  ['食べる', 'taberu', 'makan', 'II', 'ます', '食べます', ['食べります', '食べいます', '食べるます']],
  ['飲む', 'nomu', 'minum', 'I', 'ます', '飲みます', ['飲むます', '飲います', '飲まます']],
  ['行く', 'iku', 'pergi', 'I', 'ました', '行きました', ['行くました', '行いました', '行かました']],
  ['書く', 'kaku', 'menulis', 'I', 'ません', '書きません', ['書くません', '書かません', '書いません']],
  ['見る', 'miru', 'melihat', 'II', 'ませんでした', '見ませんでした', ['見りませんでした', '見るませんでした', '見ないでした']],
  ['来る', 'kuru', 'datang', 'III', 'ます', '来ます', ['来ります', '来るます', '来います']],
  ['する', 'suru', 'melakukan', 'III', 'ました', 'しました', ['するました', 'すりました', 'さました']],
  ['帰る', 'kaeru', 'pulang', 'I', 'ます', '帰ります', ['帰ます', '帰るます', '帰います']],
  ['起きる', 'okiru', 'bangun', 'II', 'ました', '起きました', ['起きりました', '起くました', '起きるました']],
  ['話す', 'hanasu', 'berbicara', 'I', 'ません', '話しません', ['話すません', '話さません', '話ちません']],
  ['待つ', 'matsu', 'menunggu', 'I', 'ます', '待ちます', ['待つます', '待たます', '待います']],
  ['買う', 'kau', 'membeli', 'I', 'ませんでした', '買いませんでした', ['買うませんでした', '買わませんでした', '買ませんでした']],
  ['寝る', 'neru', 'tidur', 'II', 'ます', '寝ます', ['寝ります', '寝るます', '寝います']],
  ['読む', 'yomu', 'membaca', 'I', 'ました', '読みました', ['読むました', '読まました', '読いました']],
  ['聞く', 'kiku', 'mendengar', 'I', 'ます', '聞きます', ['聞くます', '聞かます', '聞います']],
  ['遊ぶ', 'asobu', 'bermain', 'I', 'ません', '遊びません', ['遊ぶません', '遊ばません', '遊いません']],
  ['入る', 'hairu', 'masuk', 'I', 'ます', '入ります', ['入ます', '入るます', '入います']],
  ['泳ぐ', 'oyogu', 'berenang', 'I', 'ました', '泳ぎました', ['泳ぐました', '泳がました', '泳いました']],
  ['洗う', 'arau', 'mencuci', 'I', 'ます', '洗います', ['洗うます', '洗わます', '洗ます']],
  ['教える', 'oshieru', 'mengajar', 'II', 'ませんでした', '教えませんでした', ['教えりませんでした', '教えるませんでした', '教ませんでした']],
  ['作る', 'tsukuru', 'membuat', 'I', 'ます', '作ります', ['作ます', '作るます', '作います']],
  ['走る', 'hashiru', 'berlari', 'I', 'ました', '走りました', ['走ました', '走るました', '走いました']],
  ['着る', 'kiru', 'memakai (baju)', 'II', 'ます', '着ます', ['着ります', '着るます', '着います']],
  ['切る', 'kiru', 'memotong', 'I', 'ます', '切ります', ['切ます', '切るます', '切います']],
  ['会う', 'au', 'bertemu', 'I', 'ました', '会いました', ['会うました', '会わました', '会ました']],
  ['立つ', 'tatsu', 'berdiri', 'I', 'ます', '立ちます', ['立つます', '立たます', '立います']],
  ['勉強する', 'benkyou suru', 'belajar', 'III', 'ません', '勉強しません', ['勉強するません', '勉強さません', '勉強すりません']],
  ['開ける', 'akeru', 'membuka', 'II', 'ました', '開けました', ['開けりました', '開けるました', '開かました']],
  ['持つ', 'motsu', 'membawa', 'I', 'ませんでした', '持ちませんでした', ['持つませんでした', '持たませんでした', '持いませんでした']],
  ['降りる', 'oriru', 'turun', 'II', 'ます', '降ります', ['降りります', '降りるます', '降りいます']],
];

export const mediumConjugations: ConjugationTuple[] = [
  ['書く', 'kaku', 'menulis', 'I', 'て', '書いて', ['書きて', '書って', '書くて']],
  ['行く', 'iku', 'pergi', 'I', 'て', '行って', ['行いて', '行きて', '行くて']],
  ['飲む', 'nomu', 'minum', 'I', 'て', '飲んで', ['飲みて', '飲って', '飲いで']],
  ['話す', 'hanasu', 'berbicara', 'I', 'て', '話して', ['話いて', '話って', '話しで']],
  ['待つ', 'matsu', 'menunggu', 'I', 'た', '待った', ['待いた', '待ちた', '待んだ']],
  ['買う', 'kau', 'membeli', 'I', 'た', '買った', ['買いた', '買んだ', '買うた']],
  ['泳ぐ', 'oyogu', 'berenang', 'I', 'て', '泳いで', ['泳いて', '泳って', '泳ぎて']],
  ['遊ぶ', 'asobu', 'bermain', 'I', 'た', '遊んだ', ['遊った', '遊びた', '遊いだ']],
  ['帰る', 'kaeru', 'pulang', 'I', 'て', '帰って', ['帰て', '帰りて', '帰んで']],
  ['食べる', 'taberu', 'makan', 'II', 'ない', '食べない', ['食べらない', '食べわない', '食べるない']],
  ['行く', 'iku', 'pergi', 'I', 'ない', '行かない', ['行きない', '行くない', '行わない']],
  ['会う', 'au', 'bertemu', 'I', 'ない', '会わない', ['会あない', '会いない', '会うない']],
  ['する', 'suru', 'melakukan', 'III', 'ない', 'しない', ['すない', 'さない', 'するない']],
  ['来る', 'kuru', 'datang', 'III', 'ない', '来ない', ['来らない', '来るない', '来りない']],
  ['見る', 'miru', 'melihat', 'II', 'なかった', '見なかった', ['見らなかった', '見るなかった', '見ないかった']],
  ['読む', 'yomu', 'membaca', 'I', 'なかった', '読まなかった', ['読みなかった', '読むなかった', '読まないかった']],
  ['ある', 'aru', 'ada (benda)', 'I', 'ない', 'ない', ['あらない', 'あない', 'ありない']],
  ['呼ぶ', 'yobu', 'memanggil', 'I', 'て', '呼んで', ['呼びて', '呼って', '呼いで']],
  ['聞く', 'kiku', 'mendengar', 'I', 'た', '聞いた', ['聞きた', '聞った', '聞くた']],
  ['立つ', 'tatsu', 'berdiri', 'I', 'て', '立って', ['立ちて', '立いて', '立んで']],
  ['起きる', 'okiru', 'bangun', 'II', 'た', '起きた', ['起きった', '起った', '起きるた']],
  ['走る', 'hashiru', 'berlari', 'I', 'ない', '走らない', ['走ない', '走りない', '走るない']],
  ['入る', 'hairu', 'masuk', 'I', 'た', '入った', ['入た', '入りた', '入んだ']],
  ['教える', 'oshieru', 'mengajar', 'II', 'て', '教えて', ['教えって', '教えりて', '教いて']],
  ['休む', 'yasumu', 'beristirahat', 'I', 'た', '休んだ', ['休みた', '休った', '休いだ']],
  ['歌う', 'utau', 'bernyanyi', 'I', 'ない', '歌わない', ['歌あない', '歌いない', '歌うない']],
  ['持つ', 'motsu', 'membawa', 'I', 'なかった', '持たなかった', ['持ちなかった', '持つなかった', '持あなかった']],
  ['出す', 'dasu', 'mengeluarkan', 'I', 'た', '出した', ['出いた', '出った', '出すた']],
  ['作る', 'tsukuru', 'membuat', 'I', 'て', '作って', ['作て', '作りて', '作んで']],
  ['急ぐ', 'isogu', 'bergegas', 'I', 'た', '急いだ', ['急いた', '急った', '急ぎた']],
];

export const hardConjugations: ConjugationTuple[] = [
  ['書く', 'kaku', 'menulis', 'I', 'Potensial', '書ける', ['書かれる', '書かせる', '書けれる']],
  ['食べる', 'taberu', 'makan', 'II', 'Potensial', '食べられる', ['食べれれる', '食べさせる', '食べらる']],
  ['来る', 'kuru', 'datang', 'III', 'Potensial', '来られる', ['来れれる', '来させる', '来せる']],
  ['する', 'suru', 'melakukan', 'III', 'Potensial', 'できる', ['される', 'させる', 'しられる']],
  ['読む', 'yomu', 'membaca', 'I', 'Pasif', '読まれる', ['読める', '読ませる', '読みられる']],
  ['見る', 'miru', 'melihat', 'II', 'Pasif', '見られる', ['見させる', '見せられる', '見りれる']],
  ['言う', 'iu', 'berkata', 'I', 'Pasif', '言われる', ['言える', '言わせる', '言いれる']],
  ['飲む', 'nomu', 'minum', 'I', 'Kausatif', '飲ませる', ['飲まれる', '飲める', '飲みさせる']],
  ['行く', 'iku', 'pergi', 'I', 'Kausatif', '行かせる', ['行かれる', '行ける', '行きさせる']],
  ['食べる', 'taberu', 'makan', 'II', 'Kausatif', '食べさせる', ['食べられる', '食べせる', '食べらせる']],
  ['する', 'suru', 'melakukan', 'III', 'Kausatif', 'させる', ['される', 'できる', 'しさせる']],
  ['来る', 'kuru', 'datang', 'III', 'Kausatif', '来させる', ['来られる', '来せる', '来かせる']],
  ['待つ', 'matsu', 'menunggu', 'I', 'Kausatif-pasif', '待たされる', ['待たせる', '待たれる', '待てる']],
  ['書く', 'kaku', 'menulis', 'I', 'Volisional', '書こう', ['書きよう', '書くよう', '書けよう']],
  ['食べる', 'taberu', 'makan', 'II', 'Volisional', '食べよう', ['食べろう', '食べこう', '食べるよう']],
  ['する', 'suru', 'melakukan', 'III', 'Volisional', 'しよう', ['すろう', 'さよう', 'するよう']],
  ['帰る', 'kaeru', 'pulang', 'I', 'Volisional', '帰ろう', ['帰よう', '帰りよう', '帰るよう']],
  ['行く', 'iku', 'pergi', 'I', 'Syarat ば', '行けば', ['行きば', '行くば', '行かば']],
  ['食べる', 'taberu', 'makan', 'II', 'Syarat ば', '食べれば', ['食べば', '食べるば', '食べらば']],
  ['する', 'suru', 'melakukan', 'III', 'Syarat ば', 'すれば', ['しば', 'するば', 'さば']],
  ['来る', 'kuru', 'datang', 'III', 'Syarat ば', '来れば', ['来ば', '来るば', '来らば']],
  ['待つ', 'matsu', 'menunggu', 'I', 'Perintah', '待て', ['待ち', '待とう', '待たれ']],
  ['見る', 'miru', 'melihat', 'II', 'Perintah', '見ろ', ['見れ', '見よう', '見る']],
  ['する', 'suru', 'melakukan', 'III', 'Perintah', 'しろ', ['すれ', 'しよう', 'さろ']],
  ['話す', 'hanasu', 'berbicara', 'I', 'Potensial', '話せる', ['話される', '話させる', '話しれる']],
  ['呼ぶ', 'yobu', 'memanggil', 'I', 'Pasif', '呼ばれる', ['呼べる', '呼ばせる', '呼びれる']],
  ['泳ぐ', 'oyogu', 'berenang', 'I', 'Potensial', '泳げる', ['泳がれる', '泳がせる', '泳ぎれる']],
  ['休む', 'yasumu', 'beristirahat', 'I', 'Kausatif', '休ませる', ['休まれる', '休みさせる', '休ませれる']],
  ['飲む', 'nomu', 'minum', 'I', 'Kausatif-pasif', '飲まされる', ['飲ませる', '飲まれる', '飲みされる']],
  ['買う', 'kau', 'membeli', 'I', 'Pasif', '買われる', ['買える', '買わせる', '買いれる']],
];
