// Japanese Error Fix: [wrong sentence, corrected sentence, translation, type, rule, two more wrong versions], 30 per level.
// Every alternative is ungrammatical, so exactly one option is correct.
import type { ErrorFixTuple } from '../mandarin/errorFix';

const OBJECT = 'Objek kata kerja transitif memakai を.';
const TE_FORM = 'Bentuk て: く→いて, ぐ→いで, う/つ/る→って, む/ぶ/ぬ→んで, す→して.';

export const easyErrors: ErrorFixTuple[] = [
  ['私は 学生だです。', '私は 学生です。', 'Saya pelajar.', 'Kopula', 'だ dan です tidak dipakai bersamaan.', ['私が 学生だです。', '私は 学生でした です。']],
  ['水が 飲みます。', '水を 飲みます。', 'Saya minum air.', 'Partikel objek', OBJECT, ['水に 飲みます。', '水へ 飲みます。']],
  ['学校で 行きます。', '学校へ 行きます。', 'Saya pergi ke sekolah.', 'Partikel arah', 'Tujuan gerak memakai へ/に, bukan で.', ['学校を 行きます。', '学校が 行きます。']],
  ['この 本は おもしろいだ です。', 'この 本は おもしろい です。', 'Buku ini menarik.', 'Adjektiva い', 'Adjektiva い langsung + です, tanpa だ.', ['この 本は おもしろな です。', 'この 本は おもしろく です。']],
  ['静かの 部屋です。', '静かな 部屋です。', 'Kamar yang tenang.', 'Adjektiva な', 'Adjektiva な + な + kata benda.', ['静か 部屋です。', '静かい 部屋です。']],
  ['昨日 映画を 見るました。', '昨日 映画を 見ました。', 'Kemarin saya menonton film.', 'Bentuk ます', 'ます melekat pada batang, bukan bentuk kamus.', ['昨日 映画を 見りました。', '昨日 映画を 見ますでした。']],
  ['机の 上に 猫が あります。', '机の 上に 猫が います。', 'Di atas meja ada kucing.', 'います / あります', 'Makhluk hidup memakai います.', ['机の 上に 猫を います。', '机の 上で 猫が あります。']],
  ['部屋に テレビが います。', '部屋に テレビが あります。', 'Di kamar ada TV.', 'います / あります', 'Benda mati memakai あります.', ['部屋で テレビが あります。', '部屋に テレビを あります。']],
  ['これは 私 本です。', 'これは 私の 本です。', 'Ini buku saya.', 'Kepemilikan', 'Pemilik + の + benda.', ['これは 私が 本です。', 'これは 本の 私です。']],
  ['高いくないです。', '高くないです。', 'Tidak mahal.', 'Negatif adjektiva い', 'い → くない.', ['高いないです。', '高くじゃないです。']],
  ['きれいくないです。', 'きれいじゃないです。', 'Tidak bersih.', 'Negatif adjektiva な', 'きれい adalah adjektiva な: じゃない.', ['きれくないです。', 'きれいないです。']],
  ['三時で 起きます。', '三時に 起きます。', 'Saya bangun jam tiga.', 'Partikel waktu', 'Jam tertentu memakai に.', ['三時を 起きます。', '三時へ 起きます。']],
  ['バスに 学校へ 行きます。', 'バスで 学校へ 行きます。', 'Saya ke sekolah naik bus.', 'Partikel alat', 'Kendaraan memakai で.', ['バスを 学校へ 行きます。', 'バスが 学校へ 行きます。']],
  ['友達を 会います。', '友達に 会います。', 'Saya bertemu teman.', '会う + に', '会う memakai に untuk orang yang ditemui.', ['友達で 会います。', '友達へ 会いました。']],
  ['日本語が 話します。', '日本語を 話します。', 'Saya berbicara bahasa Jepang.', 'Partikel objek', OBJECT, ['日本語に 話します。', '日本語へ 話します。']],
  ['猫を 好きです。', '猫が 好きです。', 'Saya suka kucing.', '好き + が', '好き memakai が.', ['猫に 好きです。', '猫で 好きです。']],
  ['昨日は 寒いでした。', '昨日は 寒かったです。', 'Kemarin dingin.', 'Lampau adjektiva い', 'い → かった + です.', ['昨日は 寒くでした。', '昨日は 寒いだった です。']],
  ['昨日は 暇かったです。', '昨日は 暇でした。', 'Kemarin saya senggang.', 'Lampau adjektiva な', 'Adjektiva な + でした.', ['昨日は 暇だでした。', '昨日は 暇くでした。']],
  ['私は 毎日 日本語に 勉強します。', '私は 毎日 日本語を 勉強します。', 'Saya belajar bahasa Jepang setiap hari.', 'Partikel objek', OBJECT, ['私は 毎日 日本語が 勉強します。', '私は 毎日 日本語へ 勉強します。']],
  ['ここに 名前を 書くて ください。', 'ここに 名前を 書いて ください。', 'Tolong tulis nama di sini.', 'Bentuk て', TE_FORM, ['ここに 名前を 書きて ください。', 'ここに 名前を 書って ください。']],
  ['ちょっと 待ちて ください。', 'ちょっと 待って ください。', 'Tolong tunggu sebentar.', 'Bentuk て', TE_FORM, ['ちょっと 待て ください。', 'ちょっと 待いて ください。']],
  ['妹が 二人 あります。', '妹が 二人 います。', 'Saya punya dua adik perempuan.', 'います / あります', 'Orang memakai います.', ['妹を 二人 います。', '妹が 二つ います。']],
  ['りんごを 三人 買いました。', 'りんごを 三つ 買いました。', 'Saya membeli tiga apel.', 'Penghitung', 'Benda umum dihitung dengan ～つ.', ['りんごを 三枚 買いました。', 'りんごを 三台 買いました。']],
  ['駅は どこに ですか。', '駅は どこ ですか。', 'Stasiun di mana?', 'Kata tanya + です', 'どこ langsung + ですか.', ['駅は どこが ですか。', '駅が どこを ですか。']],
  ['私も 学生も です。', '私も 学生です。', 'Saya juga pelajar.', 'Partikel も', 'も menggantikan は setelah subjek saja.', ['私は 学生もです。', '私も の 学生です。']],
  ['図書館に 勉強します。', '図書館で 勉強します。', 'Saya belajar di perpustakaan.', 'Tempat kegiatan', 'Tempat kegiatan memakai で.', ['図書館を 勉強します。', '図書館へ 勉強します。']],
  ['大きいな 家です。', '大きい 家です。', 'Rumah yang besar.', 'Adjektiva い + benda', 'Adjektiva い langsung diikuti kata benda.', ['大きいの 家です。', '大きく 家です。']],
  ['明日 雨が 降りましょう。', '明日 雨が 降るでしょう。', 'Besok mungkin hujan.', 'Perkiraan', 'Perkiraan memakai bentuk biasa + でしょう.', ['明日 雨が 降りでしょう。', '明日 雨が 降ったでしょう です。']],
  ['これは 誰ですか の 本。', 'これは 誰の 本ですか。', 'Ini buku siapa?', 'Urutan pertanyaan', 'Kata tanya + の + benda + ですか.', ['これは 誰が 本ですか。', 'これは 本 誰の ですか。']],
  ['私は 朝ご飯を 食べないでした。', '私は 朝ご飯を 食べませんでした。', 'Saya tidak sarapan.', 'Negatif lampau', 'ません → ませんでした.', ['私は 朝ご飯を 食べませんだった。', '私は 朝ご飯を 食べなかったでした。']],
];

export const mediumErrors: ErrorFixTuple[] = [
  ['日本へ 行って ことが あります。', '日本へ 行った ことが あります。', 'Saya pernah ke Jepang.', 'Pengalaman', 'Bentuk た + ことがある.', ['日本へ 行きた ことが あります。', '日本へ 行くた ことが あります。']],
  ['写真を 撮らなくて ください。', '写真を 撮らないで ください。', 'Tolong jangan memotret.', 'Larangan halus', 'Bentuk ない + で + ください.', ['写真を 撮りないで ください。', '写真を 撮るないで ください。']],
  ['音楽を 聞きて ながら 勉強します。', '音楽を 聞きながら 勉強します。', 'Saya belajar sambil mendengarkan musik.', 'ながら', 'Batang ます + ながら.', ['音楽を 聞くながら 勉強します。', '音楽を 聞いたながら 勉強します。']],
  ['漢字が 読むことが できます。', '漢字を 読むことが できます。', 'Saya bisa membaca kanji.', 'ことができる', 'Objek di dalam V-ること tetap memakai を.', ['漢字に 読むことが できます。', '漢字を 読むことを できます。']],
  ['この 部屋に 入っては いいです。', 'この 部屋に 入っても いいです。', 'Boleh masuk ke kamar ini.', 'Izin', 'Izin = bentuk て + も + いい.', ['この 部屋に 入るても いいです。', 'この 部屋に 入りても いいです。']],
  ['寝た 前に 歯を 磨きます。', '寝る 前に 歯を 磨きます。', 'Saya menyikat gigi sebelum tidur.', 'Sebelum', 'Bentuk kamus + 前に.', ['寝て 前に 歯を 磨きます。', '寝ます 前に 歯を 磨きます。']],
  ['ご飯を 食べる 後で 散歩します。', 'ご飯を 食べた 後で 散歩します。', 'Setelah makan, saya jalan-jalan.', 'Sesudah', 'Bentuk た + 後で.', ['ご飯を 食べて 後で 散歩します。', 'ご飯を 食べます 後で 散歩します。']],
  ['私は 日本語が 話せれます。', '私は 日本語が 話せます。', 'Saya bisa berbicara bahasa Jepang.', 'Potensial', 'Godan: う → える (話す → 話せる).', ['私は 日本語が 話されます。', '私は 日本語が 話せられます。']],
  ['昨日 買いました の 本を 読みました。', '昨日 買った 本を 読みました。', 'Saya membaca buku yang saya beli kemarin.', 'Klausa relatif', 'Klausa penjelas memakai bentuk biasa langsung + benda.', ['昨日 買ったな 本を 読みました。', '昨日 買ったの 本を 読みました。']],
  ['窓が 開けて います。', '窓が 開いて います。', 'Jendelanya terbuka.', 'Transitif / intransitif', 'Keadaan memakai kata kerja intransitif + が.', ['窓を 開いて います。', '窓が 開きて います。']],
  ['先生を 本を くれました。', '先生が 本を くれました。', 'Guru memberi saya buku.', 'くれる', 'Pemberi + が + くれる.', ['先生で 本を くれました。', '先生へ 本を くれました。']],
  ['私は 友達に プレゼントを くれました。', '私は 友達に プレゼントを あげました。', 'Saya memberi teman hadiah.', 'あげる / くれる', 'Saya memberi orang lain = あげる.', ['私は 友達を プレゼントに あげました。', '私が 友達に プレゼントを くれます。']],
  ['上手に なる ために、毎日 練習します。', '上手に なる ように、毎日 練習します。', 'Agar menjadi mahir, saya berlatih setiap hari.', 'ために / ように', 'Hasil yang tidak bisa dikendalikan langsung memakai ように.', ['上手に なる ことに、毎日 練習します。', '上手に なるの ために、毎日 練習します。']],
  ['彼は 来るだと 思います。', '彼は 来ると 思います。', 'Saya pikir dia akan datang.', 'と思う', 'Kata kerja bentuk biasa + と思う, tanpa だ.', ['彼は 来ますと 思います。', '彼は 来るの 思います。']],
  ['この ケーキは おいしそうだです。', 'この ケーキは おいしそうです。', 'Kue ini kelihatannya enak.', 'そう (penampilan)', 'Adjektiva い tanpa い + そう + です.', ['この ケーキは おいしいそうな です。', 'この ケーキは おいしくそうです。']],
  ['彼女は 日本へ 行きたいです。', '彼女は 日本へ 行きたがって います。', 'Dia (perempuan) ingin ke Jepang.', 'Keinginan orang ketiga', 'Keinginan orang lain memakai たがっている.', ['彼女は 日本へ 行きたいって います。', '彼女は 日本へ 行きたがるです。']],
  ['弟は 母に しかりました。', '弟は 母に しかられました。', 'Adik dimarahi ibu.', 'Pasif', 'Pasif = akhiran られる/れる, pelaku + に.', ['弟は 母を しかられました。', '弟は 母に しかれました。']],
  ['母は 私に 野菜を 食べられました。', '母は 私に 野菜を 食べさせました。', 'Ibu menyuruh saya makan sayur.', 'Kausatif', 'Kausatif = akhiran させる/せる.', ['母は 私を 野菜を 食べさせました。', '母は 私に 野菜を 食べせました。']],
  ['まだ 宿題を しませんでした。', 'まだ 宿題を して いません。', 'Saya belum mengerjakan PR.', 'まだ … ていない', 'Belum = まだ + bentuk て + いない.', ['まだ 宿題を しました。', 'まだ 宿題を するいません。']],
  ['週末に 映画を 見たり、本を 読みます。', '週末に 映画を 見たり、本を 読んだり します。', 'Akhir pekan saya menonton film, membaca buku, dan lain-lain.', 'たり … たりする', 'Setiap kata kerja memakai たり, ditutup する.', ['週末に 映画を 見たり、本を 読みたり します。', '週末に 映画を 見てたり、本を 読んだり します。']],
  ['駅に 着くと、電話して ください。', '駅に 着いたら、電話して ください。', 'Kalau sudah sampai stasiun, tolong telepon.', 'と / たら', 'Kalimat permintaan tidak memakai と; pakai たら.', ['駅に 着いてたら、電話して ください。', '駅に 着くたら、電話して ください。']],
  ['安いだったら、買います。', '安かったら、買います。', 'Kalau murah, saya beli.', 'たら + adjektiva い', 'い → かったら.', ['安いかったら、買います。', '安くだったら、買います。']],
  ['暇いなら、遊びに 来て ください。', '暇なら、遊びに 来て ください。', 'Kalau senggang, mainlah ke sini.', 'なら + adjektiva な', 'Adjektiva な langsung + なら.', ['暇だなら、遊びに 来て ください。', '暇くなら、遊びに 来て ください。']],
  ['食べるすぎて おなかが 痛いです。', '食べすぎて おなかが 痛いです。', 'Kebanyakan makan, perut saya sakit.', 'すぎる', 'Batang ます + すぎる.', ['食べたすぎて おなかが 痛いです。', '食べてすぎて おなかが 痛いです。']],
  ['この 字は 読むやすいです。', 'この 字は 読みやすいです。', 'Tulisan ini mudah dibaca.', 'やすい / にくい', 'Batang ます + やすい.', ['この 字は 読みやすくです。', 'この 字は 読んでやすいです。']],
  ['雨が 降るても 行きます。', '雨が 降っても 行きます。', 'Meskipun hujan, saya pergi.', 'Konsesi ても', 'Bentuk て + も.', ['雨が 降りても 行きます。', '雨が 降ったても 行きます。']],
  ['テストため 勉強しました。', 'テストの ために 勉強しました。', 'Saya belajar untuk ujian.', 'ために + benda', 'Kata benda + の + ために.', ['テストに ために 勉強しました。', 'テストが ために 勉強しました。']],
  ['日本語の 新聞が 読むように なりました。', '日本語の 新聞が 読めるように なりました。', 'Saya jadi bisa membaca koran Jepang.', 'ようになる + potensial', 'Kemampuan baru = potensial + ようになる.', ['日本語の 新聞が 読めるの ように なりました。', '日本語の 新聞が 読めるに なりました。']],
  ['先生に 聞きて みます。', '先生に 聞いて みます。', 'Saya akan coba tanya guru.', 'Bentuk て + みる', TE_FORM, ['先生に 聞くて みます。', '先生に 聞いた みます。']],
  ['もう 帰るなければ なりません。', 'もう 帰らなければ なりません。', 'Saya harus pulang sekarang.', 'Kewajiban', 'Bentuk ない → なければならない.', ['もう 帰りなければ なりません。', 'もう 帰らないければ なりません。']],
];

export const hardErrors: ErrorFixTuple[] = [
  ['部長が お帰りしました。', '部長が お帰りに なりました。', 'Manajer sudah pulang (hormat).', 'Sonkeigo / kenjougo', 'Tindakan atasan memakai お + batang + になる.', ['部長が お帰りいたしました。', '部長が 帰られに なりました。']],
  ['私が お茶を お持ちに なります。', '私が お茶を お持ちします。', 'Saya akan membawakan teh (rendah hati).', 'Kenjougo', 'Tindakan sendiri memakai お + batang + する.', ['私が お茶を 持ちられます。', '私が お茶を お持ちされます。']],
  ['先生が 申しました。', '先生が おっしゃいました。', 'Guru berkata (hormat).', 'Sonkeigo khusus', '申す adalah bentuk rendah hati; untuk guru pakai おっしゃる.', ['先生が 言いされました。', '先生が お言いました。']],
  ['私は 田中と おっしゃいます。', '私は 田中と 申します。', 'Nama saya Tanaka (rendah hati).', 'Kenjougo khusus', 'Untuk diri sendiri pakai 申す.', ['私は 田中と 言わされます。', '私は 田中と お申しします。']],
  ['雨に 降って、服が ぬれました。', '雨に 降られて、服が ぬれました。', 'Saya kehujanan, bajunya basah.', 'Pasif penderitaan', 'Kejadian yang merugikan memakai pasif (降られる).', ['雨を 降られて、服が ぬれました。', '雨に 降らせて、服が ぬれました。']],
  ['子どもの とき、母に 塾へ 行かせました。', '子どもの とき、母に 塾へ 行かされました。', 'Waktu kecil saya disuruh ibu pergi les.', 'Kausatif-pasif', 'Disuruh (terpaksa) = akhiran される/させられる.', ['子どもの とき、母を 塾へ 行かされました。', '子どもの とき、母に 塾へ 行かれさせました。']],
  ['日本に 来た 以来、ずっと 東京に 住んで います。', '日本に 来て 以来、ずっと 東京に 住んで います。', 'Sejak datang ke Jepang, saya tinggal di Tokyo.', 'て以来', 'Bentuk て + 以来.', ['日本に 来る 以来、ずっと 東京に 住んで います。', '日本に 来ての 以来、ずっと 東京に 住んで います。']],
  ['練習すれば したほど 上手に なる。', '練習すれば するほど 上手に なる。', 'Makin berlatih, makin mahir.', 'ば … ほど', 'V-ば + bentuk kamus + ほど.', ['練習したら するほど 上手に なる。', '練習すれば するまで 上手に なる。']],
  ['彼は 医者な くせに、たばこを 吸う。', '彼は 医者の くせに、たばこを 吸う。', 'Padahal dokter, dia merokok.', 'くせに + benda', 'Kata benda + の + くせに.', ['彼は 医者だ くせに、たばこを 吸う。', '彼は 医者が くせに、たばこを 吸う。']],
  ['この 料理は おいしいそうに 見える。', 'この 料理は おいしそうに 見える。', 'Masakan ini kelihatan enak.', 'そう (penampilan)', 'Adjektiva い tanpa い + そう.', ['この 料理は おいしくそうに 見える。', 'この 料理は おいしいそうな 見える。']],
  ['この 服は いさそうですね。', 'この 服は よさそうですね。', 'Baju ini kelihatannya bagus ya.', 'いい → よさそう', 'いい berubah menjadi よさそう.', ['この 服は いいさそうですね。', 'この 服は よいそうに ですね。']],
  ['勉強しなかった おかげで、試験に 落ちた。', '勉強しなかった せいで、試験に 落ちた。', 'Gara-gara tidak belajar, saya gagal ujian.', 'おかげで / せいで', 'Akibat buruk memakai せいで.', ['勉強しなかった せいに、試験に 落ちた。', '勉強しなかったの せいで、試験に 落ちた。']],
  ['先生の せいで 合格できました。', '先生の おかげで 合格できました。', 'Berkat guru, saya lulus.', 'おかげで / せいで', 'Akibat baik memakai おかげで.', ['先生に おかげで 合格できました。', '先生の おかげに 合格できました。']],
  ['日本語が 話せる ために 毎日 練習します。', '日本語が 話せる ように 毎日 練習します。', 'Agar bisa berbicara bahasa Jepang, saya berlatih setiap hari.', 'ために / ように', 'Bentuk potensial tidak dipakai dengan ために; pakai ように.', ['日本語が 話せる ことに 毎日 練習します。', '日本語が 話す ように 毎日 練習します。']],
  ['雨が 降っているのに、傘を 持って いきなさい。', '雨が 降っているから、傘を 持って いきなさい。', 'Karena hujan, bawalah payung.', 'のに + perintah', 'のに (padahal) tidak bisa diikuti perintah.', ['雨が 降っているのに、傘を 持って いくなさい。', '雨が 降っているのが、傘を 持って いきなさい。']],
  ['たとえ 雨が 降ったら、行きます。', 'たとえ 雨が 降っても、行きます。', 'Sekalipun hujan, saya pergi.', 'たとえ … ても', 'たとえ berpasangan dengan ても.', ['たとえ 雨が 降れば、行きます。', 'たとえ 雨が 降るのに、行きます。']],
  ['彼が 来るの どうか わかりません。', '彼が 来るか どうか わかりません。', 'Saya tidak tahu dia datang atau tidak.', 'かどうか', 'Pertanyaan ya/tidak tak langsung = か + どうか.', ['彼が 来るか どうして わかりません。', '彼が 来るかどうかが わかりますません。']],
  ['一度も 見た ことが あります。', '一度も 見た ことが ありません。', 'Saya belum pernah melihatnya sekali pun.', '一度も + negatif', '一度も selalu diikuti bentuk negatif.', ['一度も 見る ことが あります。', '一度も 見た ことが ありました。']],
  ['子どもが 寝た うちに 掃除した。', '子どもが 寝ている うちに 掃除した。', 'Selagi anak tidur, saya bersih-bersih.', 'うちに', 'うちに memakai keadaan yang sedang berlangsung.', ['子どもが 寝る うちに 掃除した。', '子どもが 寝ていた うちで 掃除した。']],
  ['彼は 何も 言わないずに 帰った。', '彼は 何も 言わずに 帰った。', 'Dia pulang tanpa berkata apa-apa.', 'ずに', 'Bentuk ない tanpa ない + ずに.', ['彼は 何も 言いずに 帰った。', '彼は 何も 言わずで 帰った。']],
  ['彼は 勉強しずに 試験を 受けた。', '彼は 勉強せずに 試験を 受けた。', 'Dia ikut ujian tanpa belajar.', 'ずに + する', 'する → せずに.', ['彼は 勉強さずに 試験を 受けた。', '彼は 勉強しないずに 試験を 受けた。']],
  ['本当の ことを 言わないざるを得ない。', '本当の ことを 言わざるを得ない。', 'Saya terpaksa mengatakan yang sebenarnya.', 'ざるを得ない', 'Bentuk ない tanpa ない + ざるを得ない.', ['本当の ことを 言いざるを得ない。', '本当の ことを 言わざるに得ない。']],
  ['この 問題は 簡単の わりに 間違える 人が 多い。', 'この 問題は 簡単な わりに 間違える 人が 多い。', 'Walaupun soal ini mudah, banyak yang salah.', 'わりに + adjektiva な', 'Adjektiva な + な + わりに.', ['この 問題は 簡単だ わりに 間違える 人が 多い。', 'この 問題は 簡単い わりに 間違える 人が 多い。']],
  ['約束は 守るべきだです。', '約束は 守るべきです。', 'Janji sepatutnya ditepati.', 'べき', 'べき + です, tanpa だ.', ['約束は 守りべきです。', '約束は 守ったべきです。']],
  ['日本に 来る ばかりです。', '日本に 来た ばかりです。', 'Saya baru saja datang ke Jepang.', 'たばかり', 'Baru saja = bentuk た + ばかり.', ['日本に 来て ばかりです。', '日本に 来ます ばかりです。']],
  ['先生に 静かに しろように 言われました。', '先生に 静かに する ように 言われました。', 'Saya diminta guru untuk tenang.', 'ように言う', 'Bentuk kamus + ように言われる.', ['先生を 静かに する ように 言われました。', '先生に 静かに しての ように 言われました。']],
  ['来月 大阪に 転勤する ことを なりました。', '来月 大阪に 転勤する ことに なりました。', 'Bulan depan saya dipindahtugaskan ke Osaka.', 'ことになる', 'Diputuskan = ことに + なる.', ['来月 大阪に 転勤する ことが なりました。', '来月 大阪に 転勤するの ことに なりました。']],
  ['大切な 皿を 割れて しまいました。', '大切な 皿を 割って しまいました。', 'Saya tidak sengaja memecahkan piring berharga.', 'Transitif + てしまう', 'Objek を memakai kata kerja transitif (割る).', ['大切な 皿を 割りて しまいました。', '大切な 皿が 割って しまいました。']],
  ['彼が 犯人だに 違いない。', '彼が 犯人に 違いない。', 'Dia pasti pelakunya.', 'に違いない', 'Kata benda langsung + に違いない, tanpa だ.', ['彼が 犯人の 違いない。', '彼が 犯人を 違いない。']],
  ['音楽を 聞いた ながら 運転する。', '音楽を 聞きながら 運転する。', 'Menyetir sambil mendengarkan musik.', 'ながら', 'Batang ます + ながら.', ['音楽を 聞く ながら 運転する。', '音楽を 聞いて ながら 運転する。']],
];
