// Japanese Verb Form Master (tense-master mode): conjugation in context, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule, timeline]
// Label and rule are shown before answering, so they are written in romaji/Indonesian, never as the answer.
import type { AspectTuple } from '../mandarin/aspect';

export const easyForms: AspectTuple[] = [
  ['昨日 映画を ____。', 'Kemarin saya menonton film.', '見ました', ['見ます', '見ません', '見て'], 'Lampau sopan', 'bentuk -mashita', 'Past'],
  ['毎日 日本語を ____。', 'Setiap hari saya belajar bahasa Jepang.', '勉強します', ['勉強しました', '勉強して', '勉強しない'], 'Kebiasaan', 'bentuk -masu', 'Now'],
  ['私は お酒を ____。', 'Saya tidak minum alkohol.', '飲みません', ['飲みました', '飲みます', '飲んで'], 'Negatif sopan', 'bentuk -masen', 'Now'],
  ['昨日は 学校へ ____。', 'Kemarin saya tidak pergi ke sekolah.', '行きませんでした', ['行きません', '行きました', '行って'], 'Negatif lampau', 'bentuk -masen deshita', 'Past'],
  ['ここに 名前を ____ ください。', 'Tolong tulis nama di sini.', '書いて', ['書き', '書く', '書いた'], 'Permintaan', 'bentuk te + kudasai', 'Future'],
  ['一緒に ____ か。', 'Maukah makan bersama?', '食べません', ['食べました', '食べて', '食べる'], 'Ajakan', 'bentuk -masen + ka', 'Future'],
  ['一緒に ____。', 'Ayo pergi bersama!', '行きましょう', ['行きます', '行きました', '行って'], 'Ajakan', 'bentuk -mashou', 'Future'],
  ['来年 日本へ ____。', 'Tahun depan saya ingin ke Jepang.', '行きたいです', ['行きたかったです', '行きましょう', '行って'], 'Keinginan', 'batang masu + -tai desu', 'Future'],
  ['明日 友達に ____。', 'Besok saya akan bertemu teman.', '会います', ['会いました', '会って', '会いたかった'], 'Rencana', 'bentuk -masu untuk masa depan', 'Future'],
  ['先週 京都へ ____。', 'Minggu lalu saya pergi ke Kyoto.', '行きました', ['行きます', '行きません', '行って'], 'Lampau sopan', 'bentuk -mashita', 'Past'],
  ['毎朝 コーヒーを ____。', 'Setiap pagi saya minum kopi.', '飲みます', ['飲みました', '飲んで', '飲みたかった'], 'Kebiasaan', 'bentuk -masu', 'Now'],
  ['窓を ____ ください。', 'Tolong buka jendela.', '開けて', ['開け', '開ける', '開けた'], 'Permintaan', 'bentuk te + kudasai', 'Future'],
  ['昨日の 夜 よく ____。', 'Tadi malam saya tidur nyenyak.', '寝ました', ['寝ます', '寝て', '寝ません'], 'Lampau sopan', 'bentuk -mashita', 'Past'],
  ['今日は 雨が ____。', 'Hari ini tidak hujan.', '降りません', ['降りました', '降って', '降る'], 'Negatif sopan', 'bentuk -masen', 'Now'],
  ['ちょっと ____ ください。', 'Tolong tunggu sebentar.', '待って', ['待ち', '待つ', '待った'], 'Permintaan', 'bentuk te + kudasai', 'Future'],
  ['冷たい 水が ____。', 'Saya ingin minum air dingin.', '飲みたいです', ['飲みます', '飲んで', '飲みました'], 'Keinginan', 'batang masu + -tai desu', 'Now'],
  ['昨日 何も ____。', 'Kemarin saya tidak makan apa-apa.', '食べませんでした', ['食べません', '食べました', '食べて'], 'Negatif lampau', 'bentuk -masen deshita', 'Past'],
  ['先生の 話を よく ____ ください。', 'Tolong dengarkan penjelasan guru baik-baik.', '聞いて', ['聞き', '聞く', '聞いた'], 'Permintaan', 'bentuk te + kudasai', 'Future'],
  ['毎晩 十一時に ____。', 'Setiap malam saya tidur jam sebelas.', '寝ます', ['寝ました', '寝て', '寝たかった'], 'Kebiasaan', 'bentuk -masu', 'Now'],
  ['もう 一度 ____ ください。', 'Tolong ucapkan sekali lagi.', '言って', ['言い', '言う', '言った'], 'Permintaan', 'bentuk te + kudasai', 'Future'],
  ['今朝 何時に ____ か。', 'Tadi pagi kamu bangun jam berapa?', '起きました', ['起きます', '起きて', '起きません'], 'Lampau sopan', 'bentuk -mashita + ka', 'Past'],
  ['ここで 写真を ____。', 'Ayo berfoto di sini.', '撮りましょう', ['撮ります', '撮りました', '撮って'], 'Ajakan', 'bentuk -mashou', 'Future'],
  ['週末は いつも テニスを ____。', 'Akhir pekan saya selalu bermain tenis.', 'します', ['しました', 'して', 'しよう'], 'Kebiasaan', 'bentuk -masu', 'Now'],
  ['昨日 部屋を ____。', 'Kemarin saya membersihkan kamar.', '掃除しました', ['掃除します', '掃除して', '掃除しません'], 'Lampau sopan', 'bentuk -mashita', 'Past'],
  ['日曜日は 会社へ ____。', 'Hari Minggu saya tidak ke kantor.', '行きません', ['行きました', '行って', '行きたかった'], 'Negatif sopan', 'bentuk -masen', 'Now'],
  ['駅まで ____ か。', 'Maukah berjalan sampai stasiun?', '歩きません', ['歩きました', '歩いて', '歩く'], 'Ajakan', 'bentuk -masen + ka', 'Future'],
  ['早く ____ ください。', 'Tolong cepat datang.', '来て', ['来', '来る', '来た'], 'Permintaan', 'bentuk te + kudasai', 'Future'],
  ['去年 車を ____。', 'Tahun lalu saya membeli mobil.', '買いました', ['買います', '買って', '買いません'], 'Lampau sopan', 'bentuk -mashita', 'Past'],
  ['今晩は テレビを ____。', 'Malam ini saya tidak menonton TV.', '見ません', ['見ました', '見て', '見たかった'], 'Negatif sopan', 'bentuk -masen', 'Future'],
  ['新しい 靴が ____。', 'Saya ingin sepatu baru.', 'ほしいです', ['ほしかったです', 'ほしくて', 'ほしがります'], 'Keinginan benda', 'kata sifat keinginan + desu', 'Now'],
];

export const mediumForms: AspectTuple[] = [
  ['今、雨が ____ います。', 'Sekarang sedang hujan.', '降って', ['降り', '降る', '降った'], 'Sedang berlangsung', 'bentuk te + iru', 'Now'],
  ['日本へ ____ ことが あります。', 'Saya pernah ke Jepang.', '行った', ['行く', '行って', '行き'], 'Pengalaman', 'bentuk ta + koto ga aru', 'Past'],
  ['写真を ____ ください。', 'Tolong jangan memotret.', '撮らないで', ['撮って', '撮らない', '撮った'], 'Larangan halus', 'bentuk nai + de kudasai', 'Future'],
  ['早く ____ ほうが いいです。', 'Sebaiknya tidur lebih awal.', '寝た', ['寝て', '寝ない', '寝ます'], 'Saran', 'bentuk ta + hou ga ii', 'Future'],
  ['音楽を ____ ながら 勉強します。', 'Saya belajar sambil mendengarkan musik.', '聞き', ['聞いて', '聞く', '聞いた'], 'Sambil', 'batang masu + nagara', 'Now'],
  ['漢字が 少し ____。', 'Saya bisa membaca sedikit kanji.', '読めます', ['読みます', '読んで', '読まれます'], 'Potensial', 'akhiran -u → -e + ru', 'Now'],
  ['ここで たばこを ____ も いいですか。', 'Bolehkah merokok di sini?', '吸って', ['吸い', '吸う', '吸った'], 'Izin', 'bentuk te + mo ii', 'Now'],
  ['ここで 写真を ____ は いけません。', 'Tidak boleh memotret di sini.', '撮って', ['撮り', '撮る', '撮った'], 'Larangan', 'bentuk te + wa ikenai', 'Now'],
  ['____ 前に 歯を 磨きます。', 'Saya menyikat gigi sebelum tidur.', '寝る', ['寝た', '寝て', '寝ます'], 'Sebelum', 'bentuk kamus + mae ni', 'Now'],
  ['ご飯を ____ 後で 散歩します。', 'Setelah makan, saya jalan-jalan.', '食べた', ['食べる', '食べて', '食べない'], 'Sesudah', 'bentuk ta + ato de', 'Future'],
  ['来年 日本へ ____ つもりです。', 'Tahun depan saya berniat ke Jepang.', '行く', ['行った', '行って', '行き'], 'Niat', 'bentuk kamus + tsumori', 'Future'],
  ['宿題を 全部 ____ しまいました。', 'Saya sudah menghabiskan semua PR.', 'やって', ['やり', 'やる', 'やった'], 'Tuntas', 'bentuk te + shimau', 'Past'],
  ['パーティーの 前に 飲み物を 買って ____。', 'Sebelum pesta, saya membeli minuman (sebagai persiapan).', 'おきます', ['います', 'あります', 'きます'], 'Persiapan', 'bentuk te + oku', 'Future'],
  ['この 服を ____ みても いいですか。', 'Bolehkah saya mencoba baju ini?', '着て', ['着', '着る', '着た'], 'Mencoba', 'bentuk te + miru', 'Now'],
  ['明日は 学校へ ____ も いいです。', 'Besok tidak perlu ke sekolah.', '行かなくて', ['行かないで', '行かない', '行って'], 'Tidak perlu', 'bentuk nai → nakute + mo ii', 'Future'],
  ['日本語が ____ ように なりました。', 'Saya jadi bisa berbicara bahasa Jepang.', '話せる', ['話す', '話して', '話した'], 'Perubahan kemampuan', 'potensial + you ni naru', 'Past'],
  ['毎日 ____ ように して います。', 'Saya berusaha berolahraga setiap hari.', '運動する', ['運動した', '運動して', '運動し'], 'Usaha kebiasaan', 'bentuk kamus + you ni suru', 'Now'],
  ['電気を ____ まま 寝て しまいました。', 'Saya tertidur dengan lampu menyala.', 'つけた', ['つける', 'つけて', 'つけ'], 'Keadaan dibiarkan', 'bentuk ta + mama', 'Past'],
  ['明日は 雪が ____ でしょう。', 'Besok mungkin turun salju.', '降る', ['降って', '降り', '降れ'], 'Perkiraan', 'bentuk kamus + deshou', 'Future'],
  ['窓が ____ います。', 'Jendelanya (dalam keadaan) terbuka.', '開いて', ['開き', '開く', '開いた'], 'Keadaan hasil', 'kata kerja intransitif bentuk te + iru', 'Now'],
  ['今から ご飯を ____ ところです。', 'Saya baru akan makan sekarang.', '食べる', ['食べ', '食べて', '食べます'], 'Tepat akan', 'bentuk kamus + tokoro', 'Future'],
  ['たった今 駅に ____ ところです。', 'Saya baru saja tiba di stasiun.', '着いた', ['着く', '着いて', '着き'], 'Baru saja', 'bentuk ta + tokoro', 'Past'],
  ['試験の ために 毎日 ____ います。', 'Demi ujian, saya belajar setiap hari.', '勉強して', ['勉強し', '勉強する', '勉強した'], 'Kebiasaan berlanjut', 'bentuk te + iru', 'Now'],
  ['彼は 毎朝 公園を ____ います。', 'Setiap pagi dia berlari di taman.', '走って', ['走り', '走る', '走った'], 'Kebiasaan berlanjut', 'bentuk te + iru', 'Now'],
  ['母に 手紙を ____ あげました。', 'Saya menuliskan surat untuk ibu.', '書いて', ['書き', '書く', '書いた'], 'Memberi bantuan', 'bentuk te + ageru', 'Past'],
  ['友達が 駅まで ____ くれました。', 'Teman mengantarku sampai stasiun.', '送って', ['送り', '送る', '送った'], 'Menerima bantuan', 'bentuk te + kureru', 'Past'],
  ['先生に 作文を ____ もらいました。', 'Saya minta guru memeriksa karanganku.', '直して', ['直し', '直す', '直した'], 'Minta bantuan', 'bentuk te + morau', 'Past'],
  ['この 漢字は 難しくて ____。', 'Kanji ini sulit, jadi tidak bisa dibaca.', '読めません', ['読めます', '読まれません', '読んで'], 'Potensial negatif', 'potensial + -masen', 'Now'],
  ['疲れたから、少し ____ たいです。', 'Karena lelah, saya ingin istirahat sebentar.', '休み', ['休んで', '休む', '休んだ'], 'Keinginan', 'batang masu + tai', 'Future'],
  ['その ケーキ、____ みて ください。', 'Silakan coba makan kue itu.', '食べて', ['食べ', '食べる', '食べた'], 'Mencoba', 'bentuk te + miru', 'Future'],
];

export const hardForms: AspectTuple[] = [
  ['先生に ____。', 'Saya dipuji oleh guru.', 'ほめられました', ['ほめました', 'ほめさせました', 'ほめて'], 'Pasif', 'akhiran -rareru (lampau sopan)', 'Past'],
  ['母は 弟に 野菜を ____。', 'Ibu menyuruh adik makan sayur.', '食べさせました', ['食べました', '食べられました', '食べて'], 'Kausatif', 'akhiran -saseru (lampau sopan)', 'Past'],
  ['駅に ____ら、電話して ください。', 'Kalau sudah sampai stasiun, tolong telepon.', '着いた', ['着く', '着いて', '着き'], 'Kondisional', 'bentuk ta + ra', 'Future'],
  ['雨が ____ も、試合は 行われます。', 'Meskipun hujan, pertandingan tetap diadakan.', '降って', ['降る', '降った', '降り'], 'Konsesi', 'bentuk te + mo', 'Future'],
  ['明日までに レポートを 出さ____。', 'Saya harus menyerahkan laporan paling lambat besok.', 'なければなりません', ['なくてもいいです', 'ないでください', 'ましょう'], 'Kewajiban', 'bentuk nai → -nakereba naranai', 'Future'],
  ['急げ____、間に合います。', 'Kalau bergegas, masih sempat.', 'ば', ['たら', 'と', 'なら'], 'Kondisional', 'akhiran -u → -e + partikel syarat', 'Future'],
  ['子どもの とき、毎日 母に 塾へ ____。', 'Waktu kecil saya (terpaksa) disuruh ibu ke les setiap hari.', '行かされました', ['行かせました', '行かれました', '行きました'], 'Kausatif-pasif', 'akhiran -sareru (disuruh)', 'Past'],
  ['雨に ____、服が ぬれて しまいました。', 'Saya kehujanan, bajunya basah.', '降られて', ['降って', '降らせて', '降られ'], 'Pasif penderitaan', 'pasif bentuk te', 'Past'],
  ['明日は 早く ____ と 思って います。', 'Saya berniat bangun pagi besok.', '起きよう', ['起きた', '起きて', '起きろ'], 'Niat', 'bentuk volisional + to omou', 'Future'],
  ['この 薬を ____ ば、すぐ 治りますよ。', 'Kalau minum obat ini, cepat sembuh lho.', '飲め', ['飲み', '飲む', '飲ん'], 'Kondisional', 'akhiran -u → -e + partikel syarat', 'Future'],
  ['部長は もう ____。', 'Manajer sudah pulang (hormat).', 'お帰りになりました', ['お帰りしました', '帰らせました', '帰られさせました'], 'Sonkeigo', 'o + batang masu + ni naru', 'Past'],
  ['私が 荷物を ____。', 'Saya akan membawakan barang Anda (rendah hati).', 'お持ちします', ['お持ちになります', '持たれます', '持たせます'], 'Kenjougo', 'o + batang masu + suru', 'Future'],
  ['先生は 何時に ____ か。', 'Guru akan datang jam berapa (hormat)?', 'いらっしゃいます', ['参ります', '来させます', '来られさせます'], 'Sonkeigo khusus', 'kata kerja hormat khusus untuk datang', 'Future'],
  ['空が 暗いから、雨が ____ そうです。', 'Langit gelap, kelihatannya akan hujan.', '降り', ['降って', '降れ', '降ろう'], 'Kelihatannya', 'batang masu + sou', 'Future'],
  ['天気予報に よると、明日は 雨が ____ そうです。', 'Menurut prakiraan cuaca, katanya besok hujan.', '降る', ['降り', '降って', '降れ'], 'Kabar', 'bentuk biasa + sou (katanya)', 'Future'],
  ['日本語で 自己紹介が ____。', 'Saya bisa memperkenalkan diri dalam bahasa Jepang.', 'できます', ['されます', 'させます', 'しません'], 'Potensial khusus', 'potensial dari suru', 'Now'],
  ['忘れない ように メモを ____ おきます。', 'Saya mencatat supaya tidak lupa.', '取って', ['取り', '取る', '取った'], 'Persiapan', 'bentuk te + oku', 'Future'],
  ['もっと 早く ____ よかった。', 'Seharusnya saya berangkat lebih awal.', '出れば', ['出て', '出る', '出た'], 'Penyesalan', 'syarat -eba + yokatta', 'Past'],
  ['彼は 何も ____ ずに 帰りました。', 'Dia pulang tanpa berkata apa-apa.', '言わ', ['言い', '言え', '言お'], 'Tanpa', 'bentuk nai tanpa -nai + zu ni', 'Past'],
  ['仕事が ____ 次第、連絡します。', 'Segera setelah pekerjaan selesai, saya hubungi.', '終わり', ['終わる', '終わった', '終わって'], 'Segera setelah', 'batang masu + shidai', 'Future'],
  ['日本に ____ 以来、ずっと 東京に 住んで います。', 'Sejak datang ke Jepang, saya terus tinggal di Tokyo.', '来て', ['来た', '来る', '来'], 'Sejak', 'bentuk te + irai', 'Past'],
  ['子どもに 毎日 野菜を ____ ように しています。', 'Saya membiasakan anak makan sayur setiap hari.', '食べさせる', ['食べられる', '食べた', '食べる'], 'Kausatif kebiasaan', 'kausatif + you ni suru', 'Now'],
  ['この 歌は 世界中で ____ います。', 'Lagu ini dinyanyikan di seluruh dunia.', '歌われて', ['歌って', '歌わせて', '歌えて'], 'Pasif umum', 'pasif bentuk te + iru', 'Now'],
  ['練習すれ____ するほど 上手に なります。', 'Makin berlatih, makin mahir.', 'ば', ['と', 'たら', 'なら'], 'Semakin … semakin', 'syarat -eba + bentuk kamus + hodo', 'Now'],
  ['もし 宝くじに ____ら、家を 買います。', 'Kalau menang lotre, saya beli rumah.', '当たった', ['当たる', '当たって', '当たり'], 'Andaian', 'bentuk ta + ra', 'Future'],
  ['春に ____ と、桜が 咲きます。', 'Kalau musim semi tiba, sakura mekar.', 'なる', ['なった', 'なって', 'なり'], 'Kondisional alami', 'bentuk kamus + to', 'Now'],
  ['先生の ご意見を ____ いただけませんか。', 'Bolehkah saya mendengar pendapat Bapak/Ibu guru?', '聞かせて', ['聞かれて', '聞け', '聞き'], 'Permohonan sopan', 'kausatif bentuk te + itadakemasen ka', 'Future'],
  ['宿題を ____ ないで 遊びに 行きました。', 'Dia pergi main tanpa mengerjakan PR.', 'し', ['する', 'して', 'した'], 'Tanpa', 'bentuk nai + de', 'Past'],
  ['あの 店は 安くて おいしいと ____ います。', 'Toko itu dikenal murah dan enak.', '言われて', ['言って', '言わせて', '言えて'], 'Pasif umum', 'pasif bentuk te + iru', 'Now'],
  ['大切な 書類を 犬に ____ しまいました。', 'Dokumen penting saya dirobek anjing.', '破られて', ['破って', '破らせて', '破れて'], 'Pasif penderitaan', 'pasif bentuk te + shimau', 'Past'],
];
