// Japanese Particle Dash (article-dash mode): particles and compound particles, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule]
// Wrong options leave out particles that would also be correct (へ/に for direction, は for contrast).
import type { ChoiceTuple } from '../mandarin/questions';

export const easyParticles: ChoiceTuple[] = [
  ['私____ 学生です。', 'Saya pelajar.', 'は', ['を', 'に', 'で'], 'Topik', 'は menandai topik kalimat.'],
  ['水____ 飲みます。', 'Saya minum air.', 'を', ['に', 'で', 'へ'], 'Objek', 'を menandai objek kata kerja.'],
  ['学校____ 行きます。', 'Saya pergi ke sekolah.', 'へ', ['を', 'で', 'と'], 'Arah', 'へ (atau に) menandai arah tujuan.'],
  ['図書館____ 勉強します。', 'Saya belajar di perpustakaan.', 'で', ['に', 'を', 'へ'], 'Tempat kegiatan', 'で menandai tempat kegiatan berlangsung.'],
  ['友達____ 映画を 見ます。', 'Saya menonton film bersama teman.', 'と', ['を', 'へ', 'に'], 'Bersama', 'と = bersama (seseorang).'],
  ['机の 上に 本____ あります。', 'Di atas meja ada buku.', 'が', ['を', 'で', 'へ'], 'Keberadaan', 'Benda yang ada ditandai が.'],
  ['これは 私____ 本です。', 'Ini buku saya.', 'の', ['が', 'を', 'で'], 'Kepemilikan', 'の menghubungkan pemilik dan benda.'],
  ['私____ 日本人です。', 'Saya juga orang Jepang.', 'も', ['を', 'で', 'へ'], 'Juga', 'も = juga, menggantikan は/が.'],
  ['七時____ 起きます。', 'Saya bangun jam tujuh.', 'に', ['で', 'を', 'へ'], 'Waktu', 'Jam/tanggal tertentu memakai に.'],
  ['家____ 駅まで 歩きます。', 'Saya berjalan dari rumah sampai stasiun.', 'から', ['を', 'で', 'に'], 'Titik awal', 'から = dari.'],
  ['九時から 五時____ 働きます。', 'Saya bekerja dari jam 9 sampai jam 5.', 'まで', ['から', 'を', 'で'], 'Batas akhir', 'まで = sampai.'],
  ['りんご____ みかんを 買いました。', 'Saya membeli apel, jeruk, dan lain-lain.', 'や', ['を', 'で', 'へ'], 'Daftar tak lengkap', 'や = dan (di antaranya), daftar tidak lengkap.'],
  ['ペン____ 書きます。', 'Saya menulis dengan pena.', 'で', ['を', 'に', 'へ'], 'Alat', 'で menandai alat.'],
  ['公園____ 犬が います。', 'Di taman ada anjing.', 'に', ['で', 'を', 'へ'], 'Tempat keberadaan', 'Tempat sesuatu berada memakai に.'],
  ['猫____ 好きです。', 'Saya suka kucing.', 'が', ['を', 'で', 'へ'], 'Objek perasaan', '好き/嫌い/上手 memakai が.'],
  ['バス____ 学校へ 行きます。', 'Saya ke sekolah naik bus.', 'で', ['を', 'に', 'へ'], 'Alat transportasi', 'Kendaraan memakai で.'],
  ['母____ 電話を かけます。', 'Saya menelepon ibu.', 'に', ['を', 'で', 'が'], 'Penerima', 'Orang yang dituju memakai に.'],
  ['日本語____ わかります。', 'Saya mengerti bahasa Jepang.', 'が', ['を', 'で', 'へ'], 'Objek kemampuan', 'わかる memakai が.'],
  ['先生____ 質問します。', 'Saya bertanya kepada guru.', 'に', ['を', 'で', 'へ'], 'Penerima', 'Orang yang dituju memakai に.'],
  ['電車____ 降ります。', 'Saya turun dari kereta.', 'を', ['に', 'で', 'へ'], 'Titik keluar', 'Tempat yang ditinggalkan (turun/keluar) memakai を.'],
  ['部屋____ 入ります。', 'Saya masuk ke kamar.', 'に', ['を', 'で', 'が'], 'Titik masuk', 'Tempat yang dimasuki memakai に.'],
  ['だれ____ 来ましたか。', 'Siapa yang datang?', 'が', ['は', 'を', 'で'], 'Subjek kata tanya', 'Kata tanya sebagai subjek memakai が, bukan は.'],
  ['これは 日本____ 車です。', 'Ini mobil buatan Jepang.', 'の', ['が', 'を', 'で'], 'Asal', 'の menghubungkan asal dan benda.'],
  ['毎朝 公園____ 散歩します。', 'Setiap pagi saya jalan-jalan di taman.', 'を', ['に', 'が', 'へ'], 'Jalur gerak', 'Tempat yang dilalui memakai を.'],
  ['東京____ 大阪まで 新幹線で 行きます。', 'Dari Tokyo ke Osaka saya naik shinkansen.', 'から', ['を', 'で', 'に'], 'Titik awal', 'から = dari.'],
  ['友達____ プレゼントを あげました。', 'Saya memberi teman hadiah.', 'に', ['を', 'で', 'が'], 'Penerima', 'Penerima pemberian memakai に.'],
  ['日曜日____ 何を しますか。', 'Hari Minggu kamu melakukan apa?', 'に', ['を', 'で', 'が'], 'Waktu', 'Hari tertentu memakai に.'],
  ['この 道____ まっすぐ 行って ください。', 'Tolong jalan lurus menyusuri jalan ini.', 'を', ['に', 'で', 'が'], 'Jalur gerak', 'Jalan yang dilalui memakai を.'],
  ['兄____ 背が 高いです。', 'Kakak laki-laki saya tinggi.', 'は', ['を', 'で', 'に'], 'Topik', 'Topik + (bagian) が + sifat.'],
  ['ここ____ 名前を 書いて ください。', 'Tolong tulis nama di sini.', 'に', ['を', 'が', 'へ'], 'Titik tujuan', 'Tempat tulisan diletakkan memakai に.'],
];

export const mediumParticles: ChoiceTuple[] = [
  ['今日は 昨日____ 暑いです。', 'Hari ini lebih panas daripada kemarin.', 'より', ['ほど', 'まで', 'しか'], 'Perbandingan', 'より = daripada.'],
  ['今日は 昨日____ 暑くないです。', 'Hari ini tidak sepanas kemarin.', 'ほど', ['まで', 'だけ', 'しか'], 'Perbandingan negatif', 'ほど + negatif = tidak se- …'],
  ['財布に 百円____ ありません。', 'Di dompet hanya ada 100 yen.', 'しか', ['だけ', 'まで', 'より'], 'Hanya (negatif)', 'しか selalu diikuti bentuk negatif.'],
  ['水____ 飲みました。', 'Saya hanya minum air.', 'だけ', ['しか', 'まで', 'ほど'], 'Hanya', 'だけ = hanya, dengan kalimat positif.'],
  ['一人 二つ____ 取って ください。', 'Silakan ambil masing-masing dua.', 'ずつ', ['まで', 'より', 'しか'], 'Masing-masing', 'ずつ = masing-masing / per.'],
  ['金曜日____ レポートを 出して ください。', 'Serahkan laporan paling lambat hari Jumat.', 'までに', ['まで', 'から', 'より'], 'Tenggat', 'までに = paling lambat (titik waktu).'],
  ['金曜日____ 待って ください。', 'Tolong tunggu sampai hari Jumat.', 'まで', ['までに', 'から', 'より'], 'Durasi sampai', 'まで = terus sampai.'],
  ['コーヒー____ 飲みませんか。', 'Bagaimana kalau minum kopi atau semacamnya?', 'でも', ['しか', 'ほど', 'ずつ'], 'Usul halus', 'でも = … atau semacamnya.'],
  ['弟は ゲーム____ して います。', 'Adik saya main game terus.', 'ばかり', ['しか', 'ほど', 'ずつ'], 'Terus-menerus', 'ばかり = hanya … terus.'],
  ['日本の 文化____ レポートを 書きました。', 'Saya menulis laporan tentang budaya Jepang.', 'について', ['によって', 'にとって', 'として'], 'Topik', 'について = tentang.'],
  ['私____ 家族は 一番 大切です。', 'Bagi saya, keluarga paling penting.', 'にとって', ['について', 'によって', 'として'], 'Sudut pandang', 'にとって = bagi.'],
  ['国____ 習慣が 違います。', 'Kebiasaan berbeda tergantung negara.', 'によって', ['について', 'にとって', 'として'], 'Tergantung', 'によって = tergantung pada.'],
  ['通訳____ 会議に 参加しました。', 'Saya ikut rapat sebagai penerjemah.', 'として', ['について', 'によって', 'にとって'], 'Peran', 'として = sebagai.'],
  ['雨____ 試合が 中止に なりました。', 'Karena hujan, pertandingan dibatalkan.', 'で', ['を', 'に', 'が'], 'Sebab', 'で bisa menandai sebab.'],
  ['駅の 前____ 友達を 待ちます。', 'Saya menunggu teman di depan stasiun.', 'で', ['に', 'を', 'へ'], 'Tempat kegiatan', 'で menandai tempat kegiatan.'],
  ['毎日 三時間____ 勉強します。', 'Saya belajar sekitar tiga jam setiap hari.', 'ぐらい', ['しか', 'ずつ', 'まで'], 'Perkiraan', 'ぐらい = sekitar (jumlah).'],
  ['彼は 野菜____ 食べません。', 'Dia hanya makan sayur.', 'しか', ['だけ', 'ほど', 'ずつ'], 'Hanya (negatif)', 'しか + negatif = hanya.'],
  ['この 本は 子ども____ 読めます。', 'Buku ini bahkan anak-anak pun bisa membacanya.', 'でも', ['しか', 'ずつ', 'より'], 'Bahkan', 'でも = bahkan … pun.'],
  ['東京から 大阪____ 三時間 かかります。', 'Dari Tokyo sampai Osaka butuh tiga jam.', 'まで', ['までに', 'より', 'しか'], 'Batas akhir', 'まで = sampai.'],
  ['部屋の 中は 外____ 寒いです。', 'Di dalam kamar lebih dingin daripada di luar.', 'より', ['ほど', 'まで', 'しか'], 'Perbandingan', 'より = daripada.'],
  ['この 仕事は 私____ できません。', 'Pekerjaan ini hanya bisa dilakukan oleh saya.', 'しか', ['だけ', 'ほど', 'より'], 'Hanya (negatif)', 'しか + negatif = hanya.'],
  ['漢字を 一日 十個____ 覚えます。', 'Saya menghafal sepuluh kanji per hari.', 'ずつ', ['まで', 'しか', 'より'], 'Masing-masing', 'ずつ = per / masing-masing.'],
  ['甘い もの____ 食べていると 太りますよ。', 'Kalau makan yang manis-manis terus, nanti gemuk.', 'ばかり', ['ずつ', 'ほど', 'まで'], 'Terus-menerus', 'ばかり = hanya … terus.'],
  ['テストの ____ 勉強しました。', 'Saya belajar untuk ujian.', 'ために', ['ように', 'について', 'として'], 'Tujuan', 'Kata benda + の + ために = untuk.'],
  ['この 店は 日曜日____ 開いて います。', 'Toko ini buka bahkan hari Minggu.', 'でも', ['しか', 'ずつ', 'ばかり'], 'Bahkan', 'でも = bahkan … pun.'],
  ['ドア____ 開きました。', 'Pintunya terbuka (sendiri).', 'が', ['を', 'で', 'に'], 'Subjek intransitif', 'Kata kerja intransitif memakai が.'],
  ['クラスで 田中さん____ 背が 高い 人は いません。', 'Di kelas tidak ada yang setinggi Tanaka.', 'ほど', ['まで', 'だけ', 'しか'], 'Perbandingan negatif', 'ほど + negatif = tidak ada yang se- …'],
  ['晩ご飯は 七時____ 食べます。', 'Saya makan malam sekitar jam tujuh.', 'ごろ', ['まで', 'ずつ', 'しか'], 'Perkiraan waktu', 'ごろ = sekitar (jam/waktu).'],
  ['日本語____ 中国語も 話せます。', 'Selain bahasa Jepang, dia juga bisa bahasa Mandarin.', 'だけでなく', ['しか', 'ほど', 'ずつ'], 'Tidak hanya', 'だけでなく … も = tidak hanya … tetapi juga.'],
  ['三日____ 雨が 降って います。', 'Sudah tiga hari hujan terus (banyak).', 'も', ['しか', 'ずつ', 'まで'], 'Penekanan jumlah', 'Jumlah + も = sebanyak itu.'],
];

export const hardParticles: ChoiceTuple[] = [
  ['この 問題____ 意見を 聞かせて ください。', 'Mohon pendapat Anda mengenai masalah ini.', 'に関して', ['に対して', 'にわたって', 'において'], 'Mengenai', 'に関して = mengenai (formal).'],
  ['先生____ 失礼な ことを 言っては いけない。', 'Tidak boleh berkata kasar terhadap guru.', 'に対して', ['に関して', 'に沿って', 'を通して'], 'Terhadap', 'に対して = terhadap.'],
  ['天気予報____、明日は 雪だそうだ。', 'Menurut ramalan cuaca, besok salju.', 'によると', ['に対して', 'に沿って', 'にわたって'], 'Sumber info', 'によると = menurut.'],
  ['去年____ 今年は 雨が 多い。', 'Dibandingkan tahun lalu, tahun ini banyak hujan.', 'に比べて', ['に対して', 'によると', 'にわたって'], 'Perbandingan', 'に比べて = dibandingkan.'],
  ['データ____ 判断します。', 'Kami memutuskan berdasarkan data.', 'に基づいて', ['に対して', 'にわたって', 'をめぐって'], 'Dasar', 'に基づいて = berdasarkan.'],
  ['三日間____ 会議が 行われた。', 'Rapat diadakan selama tiga hari penuh.', 'にわたって', ['に対して', 'に基づいて', 'をめぐって'], 'Rentang', 'にわたって = sepanjang/selama.'],
  ['インターネット____ 情報を 集める。', 'Mengumpulkan informasi melalui internet.', 'を通して', ['に対して', 'にわたって', 'に比べて'], 'Melalui', 'を通して = melalui.'],
  ['社長____ 部長が あいさつしました。', 'Manajer memberi sambutan menggantikan direktur.', 'に代わって', ['に対して', 'に比べて', 'によると'], 'Menggantikan', 'に代わって = menggantikan.'],
  ['九州から 東北____ 雨が 降るでしょう。', 'Hujan akan turun dari Kyushu hingga Tohoku.', 'にかけて', ['に対して', 'に基づいて', 'を通して'], 'Rentang wilayah', 'から … にかけて = dari … hingga (area/waktu).'],
  ['子ども____ 分かる 問題だ。', 'Ini soal yang bahkan anak-anak pun mengerti.', 'でさえ', ['こそ', 'など', 'なんて'], 'Bahkan', 'でさえ = bahkan.'],
  ['今年____ 合格したい。', 'Tahun inilah saya ingin lulus.', 'こそ', ['さえ', 'など', 'まで'], 'Penekanan', 'こそ = justru/-lah.'],
  ['忙しくて 水____ 飲めなかった。', 'Saking sibuknya, minum air pun tidak sempat.', 'さえ', ['こそ', 'など', 'ばかり'], 'Bahkan', 'さえ = bahkan (hal paling dasar).'],
  ['若い 人____ 人気が ある 店。', 'Toko yang populer terutama di kalangan anak muda.', 'を中心に', ['によると', 'にわたって', 'に代わって'], 'Berpusat', 'を中心に = berpusat pada / terutama.'],
  ['初めて____ 上手ですね。', 'Untuk pemula, kamu cukup mahir.', 'にしては', ['にしても', 'によると', 'に対して'], 'Di luar dugaan', 'にしては = untuk ukuran …'],
  ['冗談____、言いすぎだよ。', 'Meskipun bercanda, itu keterlaluan.', 'にしても', ['にしては', 'に対して', 'によると'], 'Meskipun', 'にしても = meskipun.'],
  ['テスト____ 簡単だよ。', 'Ujian sih gampang (meremehkan).', 'なんて', ['こそ', 'さえ', 'を通して'], 'Meremehkan', 'なんて = … sih (meremehkan).'],
  ['経済の 発展____ 環境問題も 増えた。', 'Seiring perkembangan ekonomi, masalah lingkungan juga bertambah.', 'とともに', ['に対して', 'によると', 'にしては'], 'Seiring', 'とともに = seiring / bersama.'],
  ['マニュアル____ 作業して ください。', 'Kerjakan sesuai manual.', 'に沿って', ['に対して', 'にしては', 'を通して'], 'Sesuai', 'に沿って = mengikuti / sesuai.'],
  ['会議は 東京____ 開かれます。', 'Rapat diadakan di Tokyo (formal).', 'において', ['に対して', 'に比べて', 'にしては'], 'Tempat formal', 'において = di (formal).'],
  ['この 映画は 実話____ 作られた。', 'Film ini dibuat berdasarkan kisah nyata.', 'をもとに', ['に対して', 'にしては', 'によると'], 'Bahan dasar', 'をもとに = berdasarkan (bahan).'],
  ['新しい 法律____ 議論が 続いている。', 'Perdebatan terus berlangsung seputar undang-undang baru.', 'をめぐって', ['にしては', 'に比べて', 'に代わって'], 'Seputar', 'をめぐって = seputar (perdebatan).'],
  ['健康の ____ 毎日 歩いて います。', 'Demi kesehatan, saya berjalan setiap hari.', 'ために', ['ように', 'として', 'について'], 'Tujuan', 'Kata benda + の + ために = demi.'],
  ['雨____ 試合は 続いた。', 'Meskipun hujan, pertandingan berlanjut.', 'にもかかわらず', ['にしては', 'によると', 'に代わって'], 'Meskipun', 'にもかかわらず = meskipun (formal).'],
  ['努力した____ 合格できたのだ。', 'Justru karena berusaha, saya bisa lulus.', 'からこそ', ['からには', 'にしては', 'ものの'], 'Justru karena', 'からこそ = justru karena.'],
  ['学生である____、勉強しなければ ならない。', 'Karena statusnya pelajar, harus belajar.', '以上', ['にしては', 'ものの', 'とともに'], 'Karena status', '以上 = karena (sudah) …, maka.'],
  ['この 店の ケーキは 一個 千円____ する。', 'Kue di toko ini harganya sampai seribu yen per potong.', 'も', ['しか', 'ずつ', 'さえ'], 'Penekanan jumlah', 'Jumlah + も = sebanyak itu.'],
  ['雨が 降ろう____ 降るまいが、行きます。', 'Hujan atau tidak, saya tetap pergi.', 'が', ['も', 'ば', 'に'], 'Apa pun', 'V-ou ga V-mai ga = … atau tidak, tetap.'],
  ['説明書の ____ 組み立てて ください。', 'Rakitlah sesuai buku petunjuk.', 'とおりに', ['に対して', 'にしては', 'をめぐって'], 'Sesuai', 'Kata benda + の + とおりに = persis seperti.'],
  ['この 町は 古い お寺____ 有名です。', 'Kota ini terkenal dengan kuil-kuil tuanya.', 'で', ['に', 'を', 'へ'], 'Sebab terkenal', 'で有名 = terkenal karena.'],
  ['先生の アドバイス____、論文を 書き直した。', 'Mengikuti saran guru, saya menulis ulang makalah.', 'に従って', ['に対して', 'にしては', 'をめぐって'], 'Mengikuti', 'に従って = mengikuti.'],
];
