// Japanese Position Path (preposition-path mode): location nouns, direction and relational expressions, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule]
import type { ChoiceTuple } from '../mandarin/questions';

export const easyPositions: ChoiceTuple[] = [
  ['本は 机の ____ に あります。', 'Buku ada di atas meja.', '上', ['下', '中', '前'], 'Posisi', '上 (ue) = atas.'],
  ['猫は 椅子の ____ に います。', 'Kucing ada di bawah kursi.', '下', ['上', '中', '後ろ'], 'Posisi', '下 (shita) = bawah.'],
  ['かばんの ____ に 財布が あります。', 'Di dalam tas ada dompet.', '中', ['上', '下', '横'], 'Posisi', '中 (naka) = dalam.'],
  ['駅の ____ に 銀行が あります。', 'Di depan stasiun ada bank.', '前', ['後ろ', '中', '下'], 'Posisi', '前 (mae) = depan.'],
  ['家の ____ に 庭が あります。', 'Di belakang rumah ada kebun.', '後ろ', ['前', '中', '上'], 'Posisi', '後ろ (ushiro) = belakang.'],
  ['学校の ____ に 公園が あります。', 'Di sebelah sekolah ada taman.', '隣', ['中', '上', '下'], 'Posisi', '隣 (tonari) = sebelah (sejajar).'],
  ['ペンは 本と ノートの ____ に あります。', 'Pena ada di antara buku dan buku tulis.', '間', ['中', '隣', '上'], 'Posisi', 'A と B の 間 = di antara A dan B.'],
  ['駅の ____ に コンビニが あります。', 'Di dekat stasiun ada minimarket.', '近く', ['中', '上', '下'], 'Posisi', '近く (chikaku) = dekat.'],
  ['箱の ____ は 何も ありません。', 'Di luar kotak tidak ada apa-apa.', '外', ['中', '上', '間'], 'Posisi', '外 (soto) = luar.'],
  ['テレビの ____ に 時計が あります。', 'Di samping TV ada jam.', '横', ['中', '間', '下'], 'Posisi', '横 (yoko) = samping.'],
  ['銀行は 郵便局の ____ です。', 'Bank ada di sebelah kanan kantor pos.', '右', ['上', '中', '下'], 'Arah', '右 (migi) = kanan.'],
  ['トイレは 階段の ____ です。', 'Toilet ada di sebelah kiri tangga.', '左', ['上', '中', '下'], 'Arah', '左 (hidari) = kiri.'],
  ['冷蔵庫の ____ に 牛乳が あります。', 'Di dalam kulkas ada susu.', '中', ['上', '前', '外'], 'Posisi', '中 = dalam.'],
  ['ベッドの ____ に 靴が あります。', 'Di bawah tempat tidur ada sepatu.', '下', ['上', '中', '外'], 'Posisi', '下 = bawah.'],
  ['山の ____ に 雲が あります。', 'Di atas gunung ada awan.', '上', ['下', '中', '隣'], 'Posisi', '上 = atas.'],
  ['ドアの ____ で 待って ください。', 'Tolong tunggu di depan pintu.', '前', ['中', '上', '間'], 'Posisi', '前 = depan.'],
  ['私の ____ に 田中さんが 座っています。', 'Pak Tanaka duduk di sebelah saya.', '隣', ['中', '上', '下'], 'Posisi', '隣 = sebelah.'],
  ['この 道を ____ に 行って ください。', 'Silakan jalan lurus di jalan ini.', 'まっすぐ', ['右', '左', '中'], 'Arah', 'まっすぐ = lurus.'],
  ['次の 角を ____ に 曲がって ください。', 'Belok kanan di tikungan berikutnya.', '右', ['まっすぐ', '中', '上'], 'Arah', '右に曲がる = belok kanan.'],
  ['部屋の ____ に 人が たくさん います。', 'Di dalam kamar ada banyak orang.', '中', ['上', '下', '横'], 'Posisi', '中 = dalam.'],
  ['公園の ____ に 池が あります。', 'Di tengah taman ada kolam.', '真ん中', ['上', '下', '外'], 'Posisi', '真ん中 = tepat di tengah.'],
  ['車の ____ に 自転車が あります。', 'Di belakang mobil ada sepeda.', '後ろ', ['中', '上', '間'], 'Posisi', '後ろ = belakang.'],
  ['学校は 駅の ____ に あります。', 'Sekolah ada di sebelah utara stasiun.', '北', ['上', '中', '下'], 'Arah mata angin', '北 (kita) = utara.'],
  ['海は 町の ____ に あります。', 'Laut ada di sebelah selatan kota.', '南', ['上', '中', '下'], 'Arah mata angin', '南 (minami) = selatan.'],
  ['窓の ____ に 花が あります。', 'Di dekat jendela ada bunga.', 'そば', ['中', '上', '下'], 'Posisi', 'そば = dekat/di sisi.'],
  ['家の ____ で 子どもが 遊んでいます。', 'Anak-anak bermain di luar rumah.', '外', ['中', '上', '下'], 'Posisi', '外 = luar.'],
  ['写真は 壁の ____ に あります。', 'Fotonya ada di dinding (bagian atas).', '上', ['下', '中', '間'], 'Posisi', '上 = atas.'],
  ['椅子は 机の ____ に あります。', 'Kursi ada di depan meja.', '前', ['上', '中', '外'], 'Posisi', '前 = depan.'],
  ['二つの ビルの ____ に 道が あります。', 'Di antara dua gedung ada jalan.', '間', ['中', '上', '隣'], 'Posisi', '間 = di antara.'],
  ['駅は ここから ____ です。', 'Stasiun dekat dari sini.', '近い', ['中', '上', '間'], 'Jarak', '近い = dekat.'],
];

export const mediumPositions: ChoiceTuple[] = [
  ['駅から 学校____ 歩いて 十分です。', 'Dari stasiun ke sekolah sepuluh menit jalan kaki.', 'まで', ['から', 'に', 'で'], 'Rentang', 'から … まで = dari … sampai.'],
  ['橋を ____ と、左に 公園が あります。', 'Setelah menyeberangi jembatan, ada taman di sebelah kiri.', '渡る', ['入る', '出る', '乗る'], 'Gerak', '橋を渡る = menyeberangi jembatan.'],
  ['二つ目の 信号を 右に ____ ください。', 'Belok kanan di lampu lalu lintas kedua.', '曲がって', ['渡って', '入って', '乗って'], 'Gerak', '曲がる = berbelok.'],
  ['この 道を ____ と、駅に 着きます。', 'Kalau menyusuri jalan ini, sampai di stasiun.', '進む', ['曲がる', '渡る', '入る'], 'Gerak', '進む = maju/terus berjalan.'],
  ['公園の ____ を 散歩します。', 'Saya berjalan-jalan di sekeliling taman.', 'まわり', ['中心', '真上', '奥'], 'Posisi', 'まわり = sekeliling.'],
  ['部屋の ____ に 古い 箱が あります。', 'Di bagian dalam (pojok jauh) kamar ada kotak tua.', '奥', ['表', '横', '前'], 'Posisi', '奥 (oku) = bagian dalam/paling belakang.'],
  ['ビルの ____ に 看板が あります。', 'Di bagian depan gedung ada papan nama.', '正面', ['奥', '裏', '底'], 'Posisi', '正面 = tepat di depan/fasad.'],
  ['店の ____ に 駐車場が あります。', 'Di belakang (sisi belakang) toko ada parkiran.', '裏', ['表', '正面', '上'], 'Posisi', '裏 (ura) = sisi belakang.'],
  ['コップの ____ に 砂糖が 残っています。', 'Di dasar gelas tersisa gula.', '底', ['上', '表', '横'], 'Posisi', '底 (soko) = dasar.'],
  ['駅の ____ 側に 出口が あります。', 'Pintu keluar ada di sisi seberang stasiun.', '反対', ['正面', '真上', '底'], 'Arah', '反対側 = sisi seberang.'],
  ['ホテルは 駅の ____ に あります。', 'Hotel ada di seberang stasiun.', '向かい', ['中', '底', '奥'], 'Posisi', '向かい = seberang (berhadapan).'],
  ['飛行機が 町の ____ を 飛んでいます。', 'Pesawat terbang tepat di atas kota.', '真上', ['真下', '奥', '裏'], 'Posisi', '真上 = tepat di atas.'],
  ['橋の ____ を 船が 通ります。', 'Kapal lewat tepat di bawah jembatan.', '真下', ['真上', '正面', '奥'], 'Posisi', '真下 = tepat di bawah.'],
  ['東京から 大阪____ 新幹線で 行きます。', 'Saya pergi dari Tokyo ke Osaka naik shinkansen.', 'まで', ['から', 'で', 'を'], 'Rentang', 'から … まで.'],
  ['トンネルを ____ と、海が 見えました。', 'Setelah melewati terowongan, terlihat laut.', '抜ける', ['乗る', '入れる', '降りる'], 'Gerak', '抜ける = keluar melewati.'],
  ['道の ____ を 歩いて ください。', 'Tolong berjalan di pinggir jalan.', '端', ['真ん中', '奥', '底'], 'Posisi', '端 (hashi) = pinggir/ujung.'],
  ['この 先の ____ を 左です。', 'Setelah ini, di tikungan belok kiri.', '角', ['底', '奥', '裏'], 'Posisi', '角 (kado) = tikungan/sudut jalan.'],
  ['信号の ____ で 止まって ください。', 'Tolong berhenti di depan lampu lalu lintas.', '手前', ['向こう', '奥', '底'], 'Posisi', '手前 = sebelum/di sisi dekat.'],
  ['川の ____ に 村が あります。', 'Di seberang sungai ada desa.', '向こう', ['手前', '底', '真下'], 'Posisi', '向こう = seberang (jauh).'],
  ['このまま まっすぐ 行くと、____ に 交番が あります。', 'Kalau terus lurus, di ujung jalan ada pos polisi.', '突き当たり', ['真上', '底', '裏'], 'Posisi', '突き当たり = ujung jalan buntu.'],
  ['学校の ____ に 大きな 木が あります。', 'Di dalam area sekolah ada pohon besar.', '中', ['底', '真上', '向こう'], 'Posisi', '中 = di dalam (area).'],
  ['エレベーターで 五階____ 上がります。', 'Saya naik lift sampai lantai lima.', 'まで', ['から', 'で', 'を'], 'Batas', 'まで = sampai.'],
  ['入り口は 建物の ____ に あります。', 'Pintu masuk ada di sisi timur gedung.', '東側', ['真上', '底', '奥'], 'Arah', '東側 = sisi timur.'],
  ['駅の ____ で 会いましょう。', 'Mari bertemu di pintu keluar barat stasiun.', '西口', ['東側', '底', '奥'], 'Tempat', '西口 = pintu keluar barat.'],
  ['子どもたちは 先生の ____ に 並びました。', 'Anak-anak berbaris di belakang guru.', '後ろ', ['底', '奥', '真上'], 'Posisi', '後ろ = belakang.'],
  ['ここから 駅____ どのくらい かかりますか。', 'Dari sini ke stasiun butuh berapa lama?', 'まで', ['から', 'で', 'に'], 'Rentang', 'まで = sampai.'],
  ['机と 壁の ____ に 本が 落ちました。', 'Buku jatuh ke celah antara meja dan dinding.', '間', ['底', '奥', '端'], 'Posisi', '間 = di antara.'],
  ['この ビルの ____ に レストランが あります。', 'Di lantai paling atas gedung ini ada restoran.', '最上階', ['底', '裏', '端'], 'Posisi', '最上階 = lantai teratas.'],
  ['バス停は 道の ____ 側です。', 'Halte bus ada di sisi seberang jalan.', '向こう', ['底', '奥', '真上'], 'Arah', '向こう側 = sisi seberang.'],
  ['公園の ____ から 花火が 見えます。', 'Dari tengah taman terlihat kembang api.', '真ん中', ['底', '裏', '端'], 'Posisi', '真ん中 = tepat di tengah.'],
];

export const hardPositions: ChoiceTuple[] = [
  ['会議は 本社____ 行われます。', 'Rapat diadakan di kantor pusat (formal).', 'において', ['にとって', 'に対して', 'について'], 'Tempat formal', 'において = di (formal).'],
  ['駅前____ 新しい ビルが 建ちました。', 'Di depan stasiun berdiri gedung baru.', 'に', ['で', 'を', 'へ'], 'Keberadaan', 'Tempat sesuatu berdiri/ada memakai に.'],
  ['川____ 桜並木が 続いています。', 'Deretan pohon sakura berjajar menyusuri sungai.', '沿いに', ['向けに', '越しに', '先に'], 'Menyusuri', '～沿いに = di sepanjang.'],
  ['窓____ 富士山が 見えます。', 'Gunung Fuji terlihat dari balik jendela.', '越しに', ['沿いに', '向けに', '先に'], 'Melalui', '～越しに = dari balik.'],
  ['この 先____ 工事中です。', 'Di depan sana sedang ada perbaikan jalan.', 'は', ['が', 'を', 'で'], 'Topik lokasi', 'この先は = di depan sana (topik).'],
  ['駅を ____ に、北に 商店街が あります。', 'Dengan stasiun sebagai titik pusat, di utara ada pusat belanja.', '中心', ['底', '端', '裏'], 'Titik acuan', '～を中心に = berpusat di.'],
  ['山の ____ に 小さな 村が あります。', 'Di kaki gunung ada desa kecil.', 'ふもと', ['頂上', '真上', '裏'], 'Posisi', 'ふもと = kaki gunung.'],
  ['山の ____ から 町が よく 見えます。', 'Dari puncak gunung kota terlihat jelas.', '頂上', ['ふもと', '底', '奥'], 'Posisi', '頂上 = puncak.'],
  ['海____ ホテルに 泊まりました。', 'Saya menginap di hotel yang menghadap laut.', '沿いの', ['越しの', '先の', '向けの'], 'Menyusuri', '～沿いの + kata benda.'],
  ['雨の 中、傘も ささず____ 歩いた。', 'Di tengah hujan, dia berjalan tanpa memakai payung.', 'に', ['で', 'を', 'と'], 'Tanpa', '～ずに = tanpa.'],
  ['駅から 徒歩 五分の ____ に あります。', 'Lokasinya lima menit jalan kaki dari stasiun.', '距離', ['底', '裏', '端'], 'Jarak', '～の距離 = berjarak ….'],
  ['この 道を 左へ ____ と、すぐ 右手に 見えます。', 'Kalau masuk ke kiri di jalan ini, langsung terlihat di sebelah kanan.', '入る', ['出す', '乗る', '降りる'], 'Gerak', '道を入る = masuk ke jalan.'],
  ['ここは 町で 一番 高い ____ です。', 'Ini tempat tertinggi di kota.', '地点', ['底', '裏', '端'], 'Lokasi', '地点 = titik lokasi.'],
  ['国境を ____ と、景色が 変わった。', 'Begitu melewati perbatasan, pemandangan berubah.', '越える', ['沿う', '向かう', '抜く'], 'Gerak', '越える = melintasi.'],
  ['台風は 沖縄の 南を 北へ ____ います。', 'Topan bergerak ke utara di selatan Okinawa.', '向かって', ['沿って', '越えて', '抜いて'], 'Arah', '～へ向かう = menuju.'],
  ['子ども____ 本を 選びました。', 'Saya memilih buku yang ditujukan untuk anak-anak.', '向けの', ['沿いの', '越しの', '先の'], 'Sasaran', '～向け = ditujukan untuk.'],
  ['大通りを ____ 西へ 進んで ください。', 'Silakan terus ke barat melewati jalan besar.', '越えて', ['向けて', '沿いで', '先で'], 'Gerak', '～を越えて = melewati.'],
  ['空港____ 直行バスが あります。', 'Ada bus langsung menuju bandara.', '行きの', ['沿いの', '越しの', '向けで'], 'Tujuan', '～行き = tujuan ke.'],
  ['東京駅____ 電車が 遅れています。', 'Kereta yang berangkat dari Stasiun Tokyo terlambat.', '発の', ['沿いの', '越しの', '向けの'], 'Asal', '～発 = berangkat dari.'],
  ['入り口は 建物の ____ 側に あります。', 'Pintu masuk ada di sisi gedung yang menghadap jalan.', '道路', ['頂上', 'ふもと', '底'], 'Sisi', '道路側 = sisi jalan.'],
  ['その 店は 路地の ____ に あります。', 'Toko itu ada di ujung dalam gang.', '奥', ['表', '頂上', 'ふもと'], 'Posisi', '奥 = bagian dalam.'],
  ['二人は テーブルを ____ 座った。', 'Mereka berdua duduk berhadapan di meja.', '挟んで', ['越えて', '沿って', '抜けて'], 'Posisi', '～を挟んで = mengapit/berseberangan.'],
  ['この 町は 川を ____ 東西に 分かれている。', 'Kota ini terbagi timur dan barat dengan sungai di tengahnya.', '境に', ['先に', '向けに', '沿いに'], 'Batas', '～を境に = dengan … sebagai batas.'],
  ['ここ____ 先は 立ち入り禁止です。', 'Dari sini ke depan dilarang masuk.', 'から', ['まで', 'で', 'へ'], 'Titik mulai', 'ここから先 = dari sini ke depan.'],
  ['駅の 改札を ____ すぐ 右です。', 'Begitu keluar gerbang tiket stasiun, langsung di kanan.', '出て', ['入れて', '越して', '向けて'], 'Gerak', '改札を出る = keluar gerbang tiket.'],
  ['海岸____ 道を ドライブしました。', 'Saya menyetir di jalan menyusuri pantai.', '沿いの', ['向けの', '越しの', '行きの'], 'Menyusuri', '～沿い = sepanjang.'],
  ['山____ 朝日が 昇ってきた。', 'Matahari pagi terbit dari balik gunung.', 'の向こうから', ['沿いに', '向けに', '行きの'], 'Arah', '～の向こうから = dari balik.'],
  ['県____ 大会が 開かれた。', 'Turnamen tingkat prefektur diadakan.', '全体で', ['越しに', '沿いに', '発の'], 'Cakupan', '～全体で = di seluruh ….'],
  ['この 地域は 海に ____ いる。', 'Daerah ini menghadap ke laut.', '面して', ['越えて', '抜けて', '挟んで'], 'Menghadap', '～に面する = menghadap ke.'],
  ['ビルと ビルの ____ から 月が 見えた。', 'Bulan terlihat dari celah antara gedung-gedung.', 'すき間', ['頂上', 'ふもと', '表'], 'Posisi', 'すき間 = celah.'],
];
