import type { ExtraEnglishLesson } from './types';

export const beginnerSpeakingExtra: ExtraEnglishLesson[] = [
  {
    id: 12, title: 'Memesan di Kafe', subtitle: "Can I have...? · I'd like...",
    intro: 'Latih frasa sopan untuk memesan minuman dan makanan, menanyakan harga, dan membayar.',
    points: ["Memesan: Can I have a latte, please? / I'd like a sandwich.", 'Ukuran: small, medium, large.', 'Membayar: Can I pay by card?'],
    examples: [['Can I have a small latte, please?', 'Boleh saya pesan latte kecil?'], ['For here or to go?', 'Makan di sini atau dibawa pulang?'], ['To go, please.', 'Dibawa pulang.'], ['Can I pay by card?', 'Bisa bayar pakai kartu?']],
    dialogue: [['Barista', 'Hi! What can I get you?', 'Hai! Mau pesan apa?'], ['You', 'Can I have a medium iced tea, please?', 'Boleh saya pesan es teh ukuran sedang?'], ['Barista', 'Sure. Anything else?', 'Tentu. Ada lagi?'], ['You', 'A chocolate muffin, please.', 'Satu muffin cokelat.'], ['Barista', 'For here or to go?', 'Di sini atau dibawa?'], ['You', "For here. Can I pay by card? — Of course.", 'Di sini. Bisa bayar pakai kartu? — Tentu.']],
    practice: [
      ['Kalimat sopan untuk memesan adalah...', 'Can I have a coffee, please?', ['Give coffee.', 'I want coffee now.', 'Coffee me.']],
      ['"To go" artinya...', 'dibawa pulang', ['makan di sini', 'pergi sekarang', 'antre']],
      ['Pelayan bertanya "Anything else?" artinya...', 'Ada lagi?', ['Mau bayar?', 'Sudah selesai?', 'Mau duduk di mana?']],
      ['Untuk bertanya pembayaran kartu, ucapkan...', 'Can I pay by card?', ['Can I card?', 'Do you pay me?', 'Is card here?']],
    ],
    task: 'Rekam dialog memesan di kafe (peran pelanggan) dengan 2 item dan pertanyaan pembayaran.',
  },
  {
    id: 13, title: 'Berbelanja Pakaian', subtitle: 'Ukuran, warna, mencoba',
    intro: 'Latih bertanya ukuran, warna lain, mencoba pakaian, dan menanyakan harga.',
    points: ['Do you have this in a larger size?', 'Can I try it on?', "It's too tight / too long."],
    examples: [['Do you have this in black?', 'Ada yang warna hitam?'], ['Can I try it on?', 'Boleh saya coba?'], ["It's a bit too big.", 'Agak terlalu besar.'], ["I'll take it.", 'Saya ambil yang ini.']],
    dialogue: [['You', 'Excuse me, do you have this jacket in a smaller size?', 'Permisi, jaket ini ada ukuran lebih kecil?'], ['Assistant', 'Yes, here is a small.', 'Ada, ini ukuran S.'], ['You', 'Can I try it on?', 'Boleh saya coba?'], ['Assistant', 'Sure, the fitting room is on the left.', 'Tentu, ruang ganti di kiri.'], ['You', "It fits well. How much is it?", 'Pas. Berapa harganya?'], ['Assistant', "It's thirty dollars. — Great, I'll take it.", 'Tiga puluh dolar. — Bagus, saya ambil.']],
    practice: [
      ['"Can I try it on?" dipakai untuk...', 'meminta izin mencoba pakaian', ['meminta diskon', 'menanyakan harga', 'mengembalikan barang']],
      ['"I\'ll take it." artinya...', 'Saya ambil/beli ini.', ['Saya bawa pulang dulu.', 'Saya coba nanti.', 'Saya tidak mau.']],
      ['Untuk meminta ukuran lebih besar, ucapkan...', 'Do you have a larger size?', ['Is it more big?', 'I want big more.', 'Give size big.']],
      ['"It fits well." artinya...', 'Ukurannya pas.', ['Harganya murah.', 'Warnanya bagus.', 'Terlalu ketat.']],
    ],
    task: 'Rekam dirimu meminta warna/ukuran lain dan memutuskan membeli atau tidak.',
  },
  {
    id: 14, title: 'Menelepon & Membuat Janji', subtitle: 'Can I speak to...?',
    intro: 'Latih membuka telepon, meminta berbicara dengan seseorang, meninggalkan pesan, dan membuat janji.',
    points: ["Hello, this is Rani. Can I speak to Mr. Lee?", "He's not here. Can I take a message?", "Is 3 o'clock OK for you?"],
    examples: [['Hello, this is Dimas speaking.', 'Halo, saya Dimas.'], ['Can I speak to Ms. Tan, please?', 'Bisa bicara dengan Bu Tan?'], ['Can I leave a message?', 'Bisa saya titip pesan?'], ['How about Tuesday at ten?', 'Bagaimana kalau Selasa jam sepuluh?']],
    dialogue: [['Receptionist', 'Good morning, Smile Dental Clinic.', 'Selamat pagi, Klinik Gigi Smile.'], ['You', "Hello, this is Ayu. I'd like to make an appointment.", 'Halo, saya Ayu. Saya ingin membuat janji.'], ['Receptionist', 'Sure. Is Wednesday morning OK?', 'Baik. Rabu pagi bisa?'], ['You', "Sorry, I work on Wednesday. How about Friday afternoon?", 'Maaf, saya kerja hari Rabu. Bagaimana kalau Jumat siang?'], ['Receptionist', "Friday at two o'clock is free.", 'Jumat jam dua kosong.'], ['You', 'Perfect. Thank you! — See you on Friday.', 'Sempurna. Terima kasih! — Sampai jumpa Jumat.']],
    practice: [
      ['Cara memperkenalkan diri di telepon adalah...', 'This is Ayu.', ['I am phone Ayu.', 'Here Ayu is.', 'Me is Ayu.']],
      ['"Can I take a message?" diucapkan oleh...', 'orang yang menerima telepon', ['orang yang menelepon', 'dokter', 'kurir']],
      ['Untuk mengusulkan waktu lain, ucapkan...', 'How about Friday?', ['Friday is bad.', 'Go Friday.', 'Friday you?']],
      ['"I\'d like to make an appointment." artinya...', 'Saya ingin membuat janji.', ['Saya ingin membatalkan janji.', 'Saya sudah punya janji.', 'Saya terlambat.']],
    ],
    task: 'Rekam telepon membuat janji ke salon atau dokter: sebut nama, usulkan waktu, dan konfirmasi.',
  },
  {
    id: 15, title: 'Di Apotek', subtitle: 'Menjelaskan keluhan ringan',
    intro: 'Latih menyebutkan gejala, bertanya obat, dan memahami aturan pakai.',
    points: ['I have a headache / a runny nose / a stomachache.', 'Do you have something for...?', 'How often should I take it?'],
    examples: [['I have a runny nose.', 'Saya pilek.'], ['Do you have something for a cough?', 'Ada obat untuk batuk?'], ['How often should I take it?', 'Seberapa sering saya harus minum?'], ['Twice a day after meals.', 'Dua kali sehari sesudah makan.']],
    dialogue: [['Pharmacist', 'Hello, how can I help you?', 'Halo, ada yang bisa saya bantu?'], ['You', 'I have a sore throat. Do you have something for it?', 'Tenggorokan saya sakit. Ada obatnya?'], ['Pharmacist', 'Yes, try these lozenges.', 'Ada, coba permen pelega tenggorokan ini.'], ['You', 'How often should I take them?', 'Seberapa sering saya harus memakainya?'], ['Pharmacist', 'One every four hours. No more than six a day.', 'Satu setiap empat jam. Maksimal enam sehari.'], ['You', 'Thank you. How much are they? — Five dollars.', 'Terima kasih. Berapa harganya? — Lima dolar.']],
    practice: [
      ['"I have a sore throat." artinya...', 'Tenggorokan saya sakit.', ['Saya sakit kepala.', 'Saya demam.', 'Perut saya sakit.']],
      ['Untuk menanyakan obat, ucapkan...', 'Do you have something for a cough?', ['Give me medicine now.', 'Where is doctor?', 'I am medicine.']],
      ['"Twice a day" artinya...', 'dua kali sehari', ['setiap dua hari', 'sekali sehari', 'dua jam sekali']],
      ['Pertanyaan tentang aturan pakai adalah...', 'How often should I take it?', ['How much is it?', 'Where is it?', 'Who takes it?']],
    ],
    task: 'Rekam dirimu menjelaskan 2 gejala ke apoteker dan bertanya aturan pakai obat.',
  },
  {
    id: 16, title: 'Menceritakan Kemarin', subtitle: 'What did you do yesterday?',
    intro: 'Latih menceritakan kegiatan lampau dengan urutan dan perasaan.',
    points: ['Past simple: went, ate, watched, met.', 'Urutan: first, then, after that.', 'Perasaan: It was fun / tiring / boring.'],
    examples: [['What did you do yesterday?', 'Apa yang kamu lakukan kemarin?'], ['I went to the mall with my sister.', 'Saya pergi ke mal dengan kakak.'], ['We watched a funny movie.', 'Kami menonton film lucu.'], ['It was really fun.', 'Sangat menyenangkan.']],
    dialogue: [['Friend', 'Hi! What did you do yesterday?', 'Hai! Kemarin kamu ngapain?'], ['You', 'I visited my grandparents in the village.', 'Saya mengunjungi kakek-nenek di desa.'], ['Friend', 'Nice! What did you do there?', 'Asyik! Ngapain di sana?'], ['You', 'First, we had lunch. Then we walked in the rice fields.', 'Pertama kami makan siang. Lalu kami jalan-jalan di sawah.'], ['Friend', 'Sounds relaxing.', 'Kedengarannya santai.'], ['You', 'Yes, it was. But the drive home was long and tiring.', 'Ya. Tapi perjalanan pulangnya lama dan melelahkan.']],
    practice: [
      ['Bentuk lampau "go" adalah...', 'went', ['goed', 'gone', 'going']],
      ['Pertanyaan tentang kemarin yang benar adalah...', 'What did you do yesterday?', ['What you did yesterday?', 'What do you did yesterday?', 'What did you did yesterday?']],
      ['"It was tiring." artinya...', 'Itu melelahkan.', ['Itu seru.', 'Itu membosankan.', 'Itu murah.']],
      ['Kata urutan yang muncul setelah "First" biasanya...', 'Then', ['Finally first', 'Before', 'Yesterday']],
    ],
    task: 'Rekam cerita 45 detik tentang harimu kemarin dengan 3 kata urutan dan 1 perasaan.',
  },
  {
    id: 17, title: 'Rencana Akhir Pekan', subtitle: 'Mengajak dan menanggapi ajakan',
    intro: 'Latih bertanya rencana, mengajak, menerima, dan menolak dengan sopan.',
    points: ['Are you free on Saturday?', "Do you want to...? / Let's...", "I'd love to! / Sorry, I can't. I have to..."],
    examples: [['Are you free this weekend?', 'Kamu kosong akhir pekan ini?'], ['Do you want to go swimming?', 'Mau berenang?'], ["I'd love to!", 'Mau sekali!'], ["Sorry, I can't. I have to work.", 'Maaf, tidak bisa. Saya harus kerja.']],
    dialogue: [['Friend', 'Are you free on Sunday?', 'Kamu kosong hari Minggu?'], ['You', 'Yes, why?', 'Ya, kenapa?'], ['Friend', "Let's go to the new night market!", 'Ayo ke pasar malam yang baru!'], ['You', "I'd love to! What time?", 'Mau! Jam berapa?'], ['Friend', 'Around seven. I can pick you up.', 'Sekitar jam tujuh. Aku bisa jemput.'], ['You', 'Great, thanks! See you on Sunday.', 'Oke, makasih! Sampai jumpa Minggu.']],
    practice: [
      ['Kalimat untuk menerima ajakan dengan antusias adalah...', "I'd love to!", ["I can't.", 'Maybe never.', "I don't like."]],
      ['Menolak dengan sopan yang benar adalah...', "Sorry, I can't. I have to study.", ['No. Bye.', 'I not go.', "I don't want you."]],
      ['"I can pick you up." artinya...', 'Aku bisa menjemputmu.', ['Aku bisa mengangkatmu.', 'Aku akan menunggumu.', 'Aku akan menelepon.']],
      ['"Let\'s go..." dipakai untuk...', 'mengajak', ['menolak', 'meminta maaf', 'bertanya harga']],
    ],
    task: 'Rekam dua dialog: satu menerima ajakan, satu menolak dengan alasan sopan.',
  },
  {
    id: 18, title: 'Basa-basi Cuaca', subtitle: 'Small talk sederhana',
    intro: 'Obrolan ringan tentang cuaca membantu memulai percakapan dengan orang baru.',
    points: ["Nice day, isn't it?", "It's so hot/cold today!", 'Menanggapi: Yes, it is! / I know, right?'],
    examples: [["Lovely weather today, isn't it?", 'Cuaca bagus hari ini, ya?'], ["It's so hot today!", 'Panas sekali hari ini!'], ['I think it will rain later.', 'Sepertinya nanti hujan.'], ['I love this cool breeze.', 'Saya suka angin sejuk ini.']],
    dialogue: [['Neighbor', "Morning! Hot day, isn't it?", 'Pagi! Panas ya hari ini?'], ['You', "Yes, it is! It's thirty-four degrees.", 'Iya! Suhunya tiga puluh empat derajat.'], ['Neighbor', 'I hope it rains this afternoon.', 'Semoga sore ini hujan.'], ['You', 'Me too. My plants need water.', 'Saya juga. Tanaman saya butuh air.'], ['Neighbor', 'Are you going to the market?', 'Kamu mau ke pasar?'], ['You', 'Yes. Have a nice day! — You too!', 'Ya. Semoga harimu menyenangkan! — Kamu juga!']],
    practice: [
      ['"Nice day, isn\'t it?" dipakai untuk...', 'memulai obrolan ringan', ['mengeluh ke atasan', 'memesan makanan', 'meminta arah']],
      ['Tanggapan yang cocok untuk "Hot day, isn\'t it?" adalah...', 'Yes, it is!', ['No, thank you.', 'I am fine.', 'Goodbye.']],
      ['"Me too." artinya...', 'Saya juga.', ['Saya tidak.', 'Saya dua.', 'Untuk saya.']],
      ['"Have a nice day!" dijawab dengan...', 'You too!', ['Me too!', 'Yes, I am.', 'No problem.']],
    ],
    task: 'Rekam small talk 30 detik tentang cuaca hari ini dengan tetangga imajiner.',
  },
  {
    id: 19, title: 'Meminta Bantuan & Izin', subtitle: 'Could you...? · May I...?',
    intro: 'Latih meminta tolong dan meminta izin secara sopan, serta menjawabnya.',
    points: ['Meminta tolong: Could you help me, please?', 'Meminta izin: May I open the window? / Can I sit here?', 'Menjawab: Sure! / Of course. / Sorry, ...'],
    examples: [['Could you help me with this bag?', 'Bisa bantu saya dengan tas ini?'], ['May I use your pen?', 'Boleh saya pakai pulpenmu?'], ['Can I sit here?', 'Boleh saya duduk di sini?'], ['Sure, go ahead.', 'Tentu, silakan.']],
    dialogue: [['You', 'Excuse me, could you help me? I think I\'m lost.', 'Permisi, bisa bantu saya? Sepertinya saya tersesat.'], ['Stranger', 'Of course. Where do you want to go?', 'Tentu. Mau ke mana?'], ['You', 'The post office. May I look at your map?', 'Kantor pos. Boleh saya lihat petamu?'], ['Stranger', "Sure. It's here, next to the bank.", 'Tentu. Di sini, sebelah bank.'], ['You', 'Thank you so much!', 'Terima kasih banyak!'], ['Stranger', "You're welcome. Good luck!", 'Sama-sama. Semoga lancar!']],
    practice: [
      ['Meminta tolong yang paling sopan adalah...', 'Could you help me, please?', ['Help me!', 'You help me.', 'Must help me.']],
      ['"May I...?" dipakai untuk...', 'meminta izin', ['memberi perintah', 'menolak', 'mengucapkan salam']],
      ['Jawaban positif untuk "Can I sit here?" adalah...', 'Sure, go ahead.', ['No problem, sorry.', 'I am sitting.', 'Go away.']],
      ['"You\'re welcome." artinya...', 'Sama-sama.', ['Selamat datang saja.', 'Kamu baik.', 'Terima kasih.']],
    ],
    task: 'Rekam 3 permintaan tolong dan 3 permintaan izin untuk situasi di kelas atau kantor.',
  },
  {
    id: 20, title: 'Presentasi Diri 1 Menit', subtitle: 'Penilaian akhir speaking A1',
    intro: 'Gabungkan semua keterampilan: perkenalan, keluarga, pekerjaan/sekolah, hobi, kemarin, dan rencana.',
    points: ['Struktur: salam → identitas → keluarga → kegiatan → hobi → rencana → penutup.', 'Pakai kalimat pendek dan jelas.', 'Tersenyum dan jaga kontak mata.'],
    examples: [["Hello everyone, my name is Sinta and I'm 19.", 'Halo semua, nama saya Sinta, 19 tahun.'], ['I live with my parents and my little brother.', 'Saya tinggal dengan orang tua dan adik laki-laki.'], ["I'm a student at a nursing school.", 'Saya mahasiswa sekolah keperawatan.'], ["Next year I'm going to work at a hospital.", 'Tahun depan saya akan bekerja di rumah sakit.']],
    dialogue: [['Model', "Hello everyone! My name is Fajar and I'm twenty-two.", 'Halo semua! Nama saya Fajar, 22 tahun.'], ['Model', "I'm from Palembang, but I live in Bandung now.", 'Saya dari Palembang, tapi sekarang tinggal di Bandung.'], ['Model', 'I work at a bakery. I start work at five in the morning.', 'Saya bekerja di toko roti. Saya mulai bekerja jam lima pagi.'], ['Model', 'In my free time, I play guitar and watch football.', 'Di waktu luang saya main gitar dan menonton sepak bola.'], ['Model', 'Last weekend I baked a big cake for my mother.', 'Akhir pekan lalu saya membuat kue besar untuk ibu.'], ['Model', "Next year I'm going to open my own small café. Thank you!", 'Tahun depan saya akan membuka kafe kecil sendiri. Terima kasih!']],
    practice: [
      ['Urutan presentasi diri yang baik dimulai dengan...', 'salam dan nama', ['rencana masa depan', 'hobi', 'penutup']],
      ['Kalimat untuk rencana masa depan adalah...', "I'm going to open a café.", ['I opened a café.', 'I open a café yesterday.', "I'm opening a café yesterday."]],
      ['Kalimat lampau yang benar adalah...', 'Last weekend I baked a cake.', ['Last weekend I bake a cake.', 'Last weekend I am baking a cake.', 'Last weekend I will bake a cake.']],
      ['Penutup presentasi yang sopan adalah...', 'Thank you!', ['Bye bye now!', 'Finish.', 'That is all, go.']],
    ],
    task: 'Rekam presentasi diri 1 menit mengikuti struktur model, lalu nilai dirimu dengan rubrik speaking A1.',
  },
];

export const beginnerVocabularyExtra: ExtraEnglishLesson[] = [
  {
    id: 12, title: 'Clothes', subtitle: 'Pakaian sehari-hari',
    intro: 'Kosakata pakaian dan kata kerja yang sering dipakai: wear, put on, take off.',
    points: ['Pakaian atas: shirt, T-shirt, jacket, sweater.', 'Bawah & kaki: trousers, skirt, shoes, socks.', 'wear (memakai), put on (mengenakan), take off (melepas).'],
    examples: [['shirt', 'kemeja'], ['trousers', 'celana panjang'], ['shoes', 'sepatu'], ['I wear a uniform to school.', 'Saya memakai seragam ke sekolah.'], ['Take off your shoes, please.', 'Tolong lepas sepatumu.']],
    practice: [
      ['"Socks" artinya...', 'kaus kaki', ['sepatu', 'sarung tangan', 'topi']],
      ['Kata untuk "jaket" adalah...', 'jacket', ['skirt', 'belt', 'dress']],
      ['"Take off" artinya...', 'melepas', ['memakai', 'membeli', 'mencuci']],
      ['Pakaian yang dipakai di kaki adalah...', 'shoes', ['hat', 'scarf', 'shirt']],
      ['"Skirt" artinya...', 'rok', ['kemeja', 'celana pendek', 'jas']],
    ],
    task: 'Tulis apa yang kamu pakai hari ini (5 kalimat dengan "I am wearing...").',
  },
  {
    id: 13, title: 'Weather', subtitle: 'Cuaca dan suhu',
    intro: 'Kosakata cuaca: sunny, rainy, cloudy, windy, hot, cold, dan cara bertanya cuaca.',
    points: ["What's the weather like? — It's sunny.", 'Kata benda → sifat: sun → sunny, rain → rainy, cloud → cloudy.', 'Suhu: hot, warm, cool, cold.'],
    examples: [["It's sunny today.", 'Hari ini cerah.'], ["It's raining.", 'Sedang hujan.'], ['cloudy', 'berawan'], ['windy', 'berangin'], ["What's the weather like in Bali?", 'Bagaimana cuaca di Bali?']],
    practice: [
      ['"Cloudy" artinya...', 'berawan', ['berangin', 'bersalju', 'cerah']],
      ['Kata sifat dari "wind" adalah...', 'windy', ['windly', 'winding', 'winder']],
      ['Pertanyaan tentang cuaca adalah...', "What's the weather like?", ['How is weather you?', 'Where is the weather?', 'What weather do you?']],
      ['"Cool" dalam cuaca artinya...', 'sejuk', ['panas', 'lembap', 'badai']],
      ['Kata untuk "salju" adalah...', 'snow', ['storm', 'fog', 'ice cream']],
    ],
    task: 'Tulis prakiraan cuaca 3 hari untuk kotamu dalam bahasa Inggris.',
  },
  {
    id: 14, title: 'Jobs', subtitle: 'Pekerjaan dan tempat kerja',
    intro: 'Kosakata pekerjaan umum dan tempat kerjanya, serta cara bertanya pekerjaan.',
    points: ['What do you do? — I\'m a nurse.', 'Pakai a/an: a teacher, an engineer.', 'Tempat: A doctor works in a hospital.'],
    examples: [['teacher', 'guru'], ['nurse', 'perawat'], ['farmer', 'petani'], ['engineer', 'insinyur'], ['A chef works in a restaurant.', 'Koki bekerja di restoran.']],
    practice: [
      ['"Farmer" artinya...', 'petani', ['nelayan', 'tukang kebun', 'pedagang']],
      ['Pertanyaan tentang pekerjaan adalah...', 'What do you do?', ['What are you doing now?', 'Where do you go?', 'How do you do?']],
      ['Artikel yang tepat: "She is ___ engineer."', 'an', ['a', 'the', '(tanpa artikel)']],
      ['Pilot bekerja di...', 'airplane', ['hospital', 'school', 'farm']],
      ['Kata untuk "sopir" adalah...', 'driver', ['rider', 'pilot', 'waiter']],
    ],
    task: 'Tulis pekerjaan 5 anggota keluarga atau temanmu dan tempat kerja mereka.',
  },
  {
    id: 15, title: 'Animals', subtitle: 'Hewan peliharaan dan liar',
    intro: 'Kosakata hewan dan kata sifat sederhana untuk mendeskripsikannya.',
    points: ['Peliharaan: cat, dog, rabbit, fish.', 'Hewan liar: lion, elephant, monkey, snake.', 'Deskripsi: big, small, fast, slow, dangerous.'],
    examples: [['cat', 'kucing'], ['elephant', 'gajah'], ['monkey', 'monyet'], ['Snakes can be dangerous.', 'Ular bisa berbahaya.'], ['I have a small rabbit.', 'Saya punya kelinci kecil.']],
    practice: [
      ['"Rabbit" artinya...', 'kelinci', ['tikus', 'kura-kura', 'burung']],
      ['Kata untuk "gajah" adalah...', 'elephant', ['giraffe', 'tiger', 'horse']],
      ['"Dangerous" artinya...', 'berbahaya', ['lucu', 'lambat', 'besar']],
      ['Hewan yang hidup di air adalah...', 'fish', ['cow', 'bird', 'goat']],
      ['Kata untuk "burung" adalah...', 'bird', ['bear', 'bee', 'bat']],
    ],
    task: 'Deskripsikan 3 hewan favoritmu (ukuran, warna, tempat tinggal) dalam bahasa Inggris.',
  },
  {
    id: 16, title: 'Hobbies', subtitle: 'Kegiatan waktu luang',
    intro: 'Kosakata hobi dan kata kerja yang cocok: play, go, do.',
    points: ['play + olahraga bola/alat musik: play football, play the guitar.', 'go + V-ing: go swimming, go shopping.', 'do + kegiatan: do yoga, do puzzles.'],
    examples: [['play badminton', 'main bulu tangkis'], ['go fishing', 'pergi memancing'], ['do yoga', 'melakukan yoga'], ['I like reading comics.', 'Saya suka membaca komik.'], ['She plays the piano.', 'Dia bermain piano.']],
    practice: [
      ['Kata kerja yang tepat: "___ swimming"', 'go', ['play', 'do', 'make']],
      ['Kata kerja yang tepat: "___ the guitar"', 'play', ['go', 'do', 'make']],
      ['"Go fishing" artinya...', 'pergi memancing', ['membeli ikan', 'memasak ikan', 'berenang']],
      ['Kata kerja yang tepat: "___ yoga"', 'do', ['play', 'go', 'take']],
      ['"Gardening" artinya...', 'berkebun', ['memasak', 'menjahit', 'melukis']],
    ],
    task: 'Tulis 6 hobi dengan kata kerja play/go/do yang tepat, lalu tandai yang kamu suka.',
  },
  {
    id: 17, title: 'Rooms & Furniture', subtitle: 'Ruangan dan perabot rumah',
    intro: 'Kosakata ruangan dan perabot, serta preposisi letak.',
    points: ['Ruangan: bedroom, kitchen, bathroom, living room.', 'Perabot: sofa, bed, table, shelf, fridge.', 'Letak: on, under, next to, in front of.'],
    examples: [['living room', 'ruang tamu/keluarga'], ['fridge', 'kulkas'], ['shelf', 'rak'], ['The lamp is on the table.', 'Lampu ada di atas meja.'], ['The cat is under the bed.', 'Kucing ada di bawah tempat tidur.']],
    practice: [
      ['"Fridge" ada di ruangan...', 'kitchen', ['bedroom', 'garage', 'bathroom']],
      ['"Shelf" artinya...', 'rak', ['lemari es', 'kasur', 'kursi']],
      ['"Under" artinya...', 'di bawah', ['di atas', 'di samping', 'di depan']],
      ['Tempat untuk tidur adalah...', 'bed', ['sofa', 'desk', 'sink']],
      ['"Next to the window" artinya...', 'di sebelah jendela', ['di bawah jendela', 'di luar jendela', 'di atas jendela']],
    ],
    task: 'Gambar denah kamarmu dan tulis 6 kalimat letak perabot memakai preposisi.',
  },
  {
    id: 18, title: 'School Things', subtitle: 'Perlengkapan sekolah dan kelas',
    intro: 'Kosakata benda di kelas dan tas sekolah, serta frasa kelas.',
    points: ['Benda: pencil, eraser, ruler, notebook, whiteboard.', 'Pertanyaan: Can I borrow your...?', 'This is / These are untuk tunggal / jamak.'],
    examples: [['eraser', 'penghapus'], ['ruler', 'penggaris'], ['notebook', 'buku catatan'], ['Can I borrow your pencil?', 'Boleh pinjam pensilmu?'], ['These are my markers.', 'Ini spidol-spidol saya.']],
    practice: [
      ['"Ruler" artinya...', 'penggaris', ['penghapus', 'rautan', 'gunting']],
      ['Kata untuk "penghapus" adalah...', 'eraser', ['sharpener', 'marker', 'glue']],
      ['"Can I borrow...?" artinya...', 'Boleh saya pinjam...?', ['Boleh saya beli...?', 'Boleh saya ambil...?', 'Di mana...?']],
      ['Lengkapi: "___ are my books."', 'These', ['This', 'That', 'It']],
      ['"Scissors" artinya...', 'gunting', ['lem', 'kapur', 'tas']],
    ],
    task: 'Buat daftar isi tas sekolah/kerjamu (8 benda) dengan This is / These are.',
  },
  {
    id: 19, title: 'Feelings', subtitle: 'Perasaan dan emosi',
    intro: 'Kosakata perasaan dan cara bertanya serta menjawab tentang perasaan.',
    points: ['How do you feel? / How are you feeling?', 'Perasaan: happy, sad, angry, tired, bored, excited, nervous.', 'Alasan: I feel nervous because I have an exam.'],
    examples: [['happy', 'senang'], ['tired', 'lelah'], ['nervous', 'gugup'], ['I feel bored.', 'Saya merasa bosan.'], ["I'm excited about the trip!", 'Saya bersemangat tentang perjalanan itu!']],
    practice: [
      ['"Nervous" artinya...', 'gugup', ['marah', 'bosan', 'lapar']],
      ['Kata untuk "marah" adalah...', 'angry', ['hungry', 'sorry', 'lonely']],
      ['"Excited" artinya...', 'bersemangat / antusias', ['lelah', 'takut', 'sedih']],
      ['Pertanyaan tentang perasaan adalah...', 'How do you feel?', ['What do you feel it?', 'Where do you feel?', 'Why you feel?']],
      ['"Bored" artinya...', 'bosan', ['sibuk', 'senang', 'kaget']],
    ],
    task: 'Tulis jurnal perasaan 3 hari: bagaimana perasaanmu dan mengapa (pakai because).',
  },
  {
    id: 20, title: 'Ulasan Kosakata A1', subtitle: 'Campuran semua tema',
    intro: 'Ulang kosakata A1 dari semua tema: keluarga, makanan, pakaian, cuaca, pekerjaan, hewan, rumah, dan perasaan.',
    points: ['Kelompokkan kata per tema agar mudah diingat.', 'Buat kalimat sendiri untuk setiap kata baru.', 'Ulang dengan fitur Review Harian (SRS).'],
    examples: [['My aunt is a doctor.', 'Bibi saya seorang dokter.'], ["It's cold, so I'm wearing a jacket.", 'Dingin, jadi saya memakai jaket.'], ['There is a cat under the sofa.', 'Ada kucing di bawah sofa.'], ["I'm hungry. Let's eat rice and chicken.", 'Saya lapar. Ayo makan nasi dan ayam.']],
    practice: [
      ['Kata yang BUKAN pakaian adalah...', 'kitchen', ['jacket', 'socks', 'skirt']],
      ['Kata yang termasuk cuaca adalah...', 'windy', ['nurse', 'eraser', 'monkey']],
      ['"Aunt" artinya...', 'bibi / tante', ['nenek', 'sepupu', 'kakak']],
      ['Pasangan yang benar adalah...', 'chef – restaurant', ['farmer – hospital', 'teacher – farm', 'pilot – school']],
      ['"Hungry" artinya...', 'lapar', ['marah', 'haus', 'sakit']],
    ],
    task: 'Buat peta pikiran (mind map) dengan 8 tema dan 5 kata per tema.',
  },
];

export const beginnerWritingExtra: ExtraEnglishLesson[] = [
  {
    id: 11, title: 'Menulis Kartu Ucapan', subtitle: 'Selamat & terima kasih',
    intro: 'Kartu ucapan singkat: salam pembuka, ucapan, satu kalimat personal, dan penutup.',
    points: ['Dear + nama, / Hi + nama,', 'Isi: Happy birthday! / Congratulations! / Thank you for...', 'Penutup: Love, / Best wishes, + nama.'],
    examples: [['Dear Mr. Budi,', 'Pak Budi yang terhormat,'], ['Congratulations on your new job!', 'Selamat atas pekerjaan barumu!'], ['Thank you for helping me.', 'Terima kasih sudah membantu saya.'], ['Best wishes, Laras', 'Salam hangat, Laras']],
    practice: [
      ['Pembuka kartu yang tepat adalah...', 'Dear Rina,', ['Hey you!', 'To: Rina Subject', 'Rina, listen.']],
      ['Ucapan selamat atas pekerjaan baru adalah...', 'Congratulations on your new job!', ['Happy new job birthday!', 'Sorry for your job.', 'Good job job!']],
      ['Penutup kartu yang tepat adalah...', 'Best wishes, Laras', ['Bye, Laras.', 'The end.', 'From Laras to.']],
      ['"Thank you for ___ me." (membantu)', 'helping', ['help', 'helped', 'to help']],
    ],
    task: 'Tulis 2 kartu: ucapan selamat wisuda dan ucapan terima kasih untuk guru (4 kalimat masing-masing).',
  },
  {
    id: 12, title: 'Mengisi Formulir', subtitle: 'Data pribadi dalam bahasa Inggris',
    intro: 'Formulir memakai istilah khusus: first name, surname, date of birth, nationality, signature.',
    points: ['First name = nama depan, Surname/Last name = nama belakang.', 'Date of birth (DOB) = tanggal lahir.', 'Tulis huruf kapital jika diminta: BLOCK CAPITALS.'],
    examples: [['First name: Putri', 'Nama depan: Putri'], ['Surname: Lestari', 'Nama belakang: Lestari'], ['Date of birth: 12/05/2004', 'Tanggal lahir: 12/05/2004'], ['Nationality: Indonesian', 'Kewarganegaraan: Indonesia']],
    practice: [
      ['"Surname" artinya...', 'nama belakang', ['nama depan', 'nama panggilan', 'nama ibu']],
      ['"Date of birth" artinya...', 'tanggal lahir', ['tanggal hari ini', 'tempat lahir', 'tanggal daftar']],
      ['"Nationality" untuk orang Indonesia ditulis...', 'Indonesian', ['Indonesia people', 'Indo', 'Indonesiaan']],
      ['"Signature" artinya...', 'tanda tangan', ['stempel', 'alamat', 'nomor telepon']],
    ],
    task: 'Isi formulir pendaftaran kursus dalam bahasa Inggris (nama, DOB, alamat, email, alasan ikut kursus).',
  },
  {
    id: 13, title: 'Pesan Singkat (Chat)', subtitle: 'Teks informal ke teman',
    intro: 'Pesan chat singkat dan santai, tetapi tetap jelas: tujuan, waktu, tempat.',
    points: ['Mulai langsung: Hi! Are you free tonight?', 'Singkatan umum: pls (please), thx (thanks), btw.', 'Akhiri dengan pertanyaan atau ajakan.'],
    examples: [['Hi! Running 10 mins late, sorry!', 'Hai! Telat 10 menit, maaf!'], ['Can you buy some milk pls?', 'Bisa belikan susu?'], ['Thx for today!', 'Makasih untuk hari ini!'], ['See you at 7?', 'Ketemu jam 7?']],
    practice: [
      ['"Thx" adalah singkatan dari...', 'thanks', ['this', 'think', 'text']],
      ['Pesan yang jelas untuk terlambat adalah...', "Sorry, I'm 15 minutes late!", ['Late.', 'Me time late you.', 'Sorry for yesterday.']],
      ['"pls" artinya...', 'please / tolong', ['plus', 'places', 'plans']],
      ['Pesan chat sebaiknya...', 'singkat dan jelas', ['panjang dan formal', 'tanpa informasi waktu', 'memakai bahasa resmi']],
    ],
    task: 'Tulis 4 pesan chat: mengajak, terlambat, minta tolong, dan berterima kasih.',
  },
  {
    id: 14, title: 'Mendeskripsikan Rumah', subtitle: 'There is / There are + preposisi',
    intro: 'Tulis paragraf pendek tentang rumahmu memakai there is/are dan preposisi letak.',
    points: ['Kalimat topik: I live in a small house in Bogor.', 'There are three bedrooms. There is a garden.', 'Tambahkan pendapat: My favorite room is...'],
    examples: [['I live in an apartment on the tenth floor.', 'Saya tinggal di apartemen lantai sepuluh.'], ['There are two bedrooms and one bathroom.', 'Ada dua kamar tidur dan satu kamar mandi.'], ['There is a small balcony next to the kitchen.', 'Ada balkon kecil di sebelah dapur.'], ['My favorite room is the living room.', 'Ruangan favorit saya ruang keluarga.']],
    practice: [
      ['Lengkapi: "There ___ two bedrooms."', 'are', ['is', 'am', 'be']],
      ['Lengkapi: "There ___ a garden."', 'is', ['are', 'have', 'has']],
      ['Kalimat topik yang baik adalah...', 'I live in a small house in Bogor.', ['And there is a table.', 'Next to the sofa.', 'Finally, bye.']],
      ['"My favorite room" artinya...', 'ruangan favorit saya', ['kamar saya', 'rumah favorit', 'ruang tamu saya']],
    ],
    task: 'Tulis paragraf 6–8 kalimat tentang rumahmu dengan there is/are dan 3 preposisi.',
  },
  {
    id: 15, title: 'Daftar Belanja & To-do', subtitle: 'Menulis daftar yang jelas',
    intro: 'Daftar memakai kata benda + jumlah atau kata kerja perintah untuk tugas.',
    points: ['Belanja: 2 kg rice, a bottle of oil, 6 eggs.', 'To-do: Call the bank. Pay the bill. Clean my room.', 'Satuan: a bottle of, a packet of, a kilo of.'],
    examples: [['a bottle of water', 'sebotol air'], ['a packet of noodles', 'sebungkus mi'], ['Pay the electricity bill.', 'Bayar tagihan listrik.'], ['Email my teacher.', 'Kirim email ke guru.']],
    practice: [
      ['"A packet of biscuits" artinya...', 'sebungkus biskuit', ['sebotol biskuit', 'sekilo biskuit', 'sepiring biskuit']],
      ['Satuan yang tepat: "a ___ of milk"', 'bottle', ['packet', 'piece', 'slice']],
      ['To-do list biasanya memakai...', 'kata kerja perintah', ['kalimat tanya', 'kalimat lampau', 'kata sifat']],
      ['"Pay the bill" artinya...', 'bayar tagihan', ['beli tagihan', 'cetak tagihan', 'kirim tagihan']],
    ],
    task: 'Tulis daftar belanja 8 item (dengan satuan) dan to-do list 5 tugas untuk besok.',
  },
  {
    id: 16, title: 'Email Singkat ke Teman', subtitle: 'Kabar dan pertanyaan',
    intro: 'Email informal: salam, kabar singkat, satu berita, satu pertanyaan, penutup.',
    points: ['Hi Mira, How are you?', "Berita: I'm writing to tell you... / Guess what?", 'Penutup: Write soon! / Take care, + nama.'],
    examples: [['How are you? I hope you are well.', 'Apa kabar? Semoga kamu baik.'], ['Guess what? I got a new job!', 'Tebak apa? Aku dapat pekerjaan baru!'], ['How is your new school?', 'Bagaimana sekolah barumu?'], ['Write soon!', 'Segera balas ya!']],
    practice: [
      ['Pembuka email informal yang tepat adalah...', 'Hi Mira,', ['Dear Sir/Madam,', 'To whom it may concern,', 'Attention Mira!']],
      ['"Guess what?" dipakai untuk...', 'memperkenalkan berita menarik', ['menutup email', 'meminta maaf', 'menanyakan alamat']],
      ['Penutup email informal yang tepat adalah...', 'Take care, Dewi', ['Yours faithfully, Dewi', 'Regards Sir, Dewi', 'End.']],
      ['"Write soon!" artinya...', 'Segera balas ya!', ['Tulis pelan-pelan!', 'Jangan menulis!', 'Tulis sekarang juga di sini!']],
    ],
    task: 'Tulis email 60–80 kata ke teman: kabarmu, satu berita, dan dua pertanyaan untuknya.',
  },
  {
    id: 17, title: 'Menulis tentang Hobi', subtitle: 'Paragraf dengan alasan',
    intro: 'Paragraf hobi berisi apa, kapan, dengan siapa, dan mengapa kamu menyukainya.',
    points: ['My hobby is... / I love + V-ing.', 'Kapan & dengan siapa: every weekend, with my friends.', 'Alasan: because it is relaxing / fun / healthy.'],
    examples: [['My hobby is cooking.', 'Hobi saya memasak.'], ['I usually cook on Sunday with my mom.', 'Saya biasanya memasak hari Minggu dengan ibu.'], ['I love it because it is relaxing.', 'Saya suka karena menenangkan.'], ['My favorite dish is chicken curry.', 'Masakan favorit saya kari ayam.']],
    practice: [
      ['Lengkapi: "I love ___ (membaca)."', 'reading', ['read', 'reads', 'to reading']],
      ['Kata untuk memberi alasan adalah...', 'because', ['but', 'and', 'or']],
      ['Kalimat yang benar adalah...', 'I play guitar every weekend.', ['I every weekend play guitar.', 'I play every guitar weekend.', 'Every I play weekend guitar.']],
      ['"It is relaxing." artinya...', 'Itu menenangkan.', ['Itu melelahkan.', 'Itu mahal.', 'Itu sulit.']],
    ],
    task: 'Tulis paragraf 7 kalimat tentang hobimu dengan minimal 2 alasan memakai because.',
  },
  {
    id: 18, title: 'Menulis Kejadian Kemarin', subtitle: 'Diary dengan past simple',
    intro: 'Tulis catatan harian memakai past simple dan kata urutan.',
    points: ['Mulai dengan waktu: Yesterday / Last Saturday...', 'Pakai kata kerja lampau: went, bought, saw.', 'Akhiri dengan perasaan: I felt happy.'],
    examples: [['Dear diary, yesterday was a busy day.', 'Buku harian, kemarin hari yang sibuk.'], ['In the morning I went to the bank.', 'Pagi hari saya ke bank.'], ['Then I bought a birthday gift for my sister.', 'Lalu saya membeli hadiah ulang tahun untuk adik.'], ['In the evening I felt tired but happy.', 'Malamnya saya merasa lelah tapi senang.']],
    practice: [
      ['Bentuk lampau "buy" adalah...', 'bought', ['buyed', 'brought', 'buied']],
      ['Bentuk lampau "see" adalah...', 'saw', ['seed', 'seen', 'sawed']],
      ['Kalimat yang benar adalah...', 'Yesterday I visited my friend.', ['Yesterday I visit my friend.', 'Yesterday I am visiting my friend.', 'Yesterday I will visit my friend.']],
      ['"I felt tired." artinya...', 'Saya merasa lelah.', ['Saya jatuh lelah.', 'Saya akan lelah.', 'Saya tidak lelah.']],
    ],
    task: 'Tulis diary 80 kata tentang hari kemarin dengan 5 kata kerja lampau berbeda.',
  },
  {
    id: 19, title: 'Menulis Rencana', subtitle: 'Liburan dengan going to',
    intro: 'Tulis rencana liburan memakai be going to, waktu, tempat, dan kegiatan.',
    points: ["Next month I'm going to...", 'Tambahkan detail: with, by train, for three days.', 'Perasaan: I can\'t wait!'],
    examples: [["Next holiday, I'm going to visit Lombok.", 'Liburan nanti saya akan mengunjungi Lombok.'], ["I'm going to travel by plane with my cousins.", 'Saya akan naik pesawat bersama sepupu.'], ["We're going to stay there for four days.", 'Kami akan tinggal di sana empat hari.'], ["I can't wait!", 'Saya tidak sabar!']],
    practice: [
      ['Lengkapi: "We ___ going to stay for four days."', 'are', ['is', 'am', 'will']],
      ['"By plane" artinya...', 'naik pesawat', ['di pesawat', 'membeli pesawat', 'dekat pesawat']],
      ['"I can\'t wait!" menunjukkan perasaan...', 'tidak sabar / antusias', ['bosan', 'marah', 'takut']],
      ['Kalimat rencana yang benar adalah...', "I'm going to visit my aunt.", ['I going to visit my aunt.', "I'm go to visit my aunt.", "I'm going visit my aunt."]],
    ],
    task: 'Tulis rencana liburan 80 kata dengan tempat, transportasi, teman perjalanan, dan 3 kegiatan.',
  },
  {
    id: 20, title: 'Paragraf Perkenalan Akhir', subtitle: 'Penilaian menulis A1',
    intro: 'Tulis paragraf perkenalan lengkap yang menggabungkan semua pola A1.',
    points: ['Struktur: kalimat topik → info pribadi → keluarga → kegiatan → hobi → rencana → penutup.', 'Periksa huruf kapital dan titik.', 'Periksa bentuk kata kerja (present, past, going to).'],
    examples: [["My name is Rudi and I'm twenty years old.", 'Nama saya Rudi, umur 20 tahun.'], ['I live in Semarang with my parents.', 'Saya tinggal di Semarang bersama orang tua.'], ['Last year I finished high school.', 'Tahun lalu saya lulus SMA.'], ["Next year I'm going to study IT.", 'Tahun depan saya akan kuliah IT.']],
    practice: [
      ['Kalimat dengan huruf kapital yang benar adalah...', 'I live in Jakarta.', ['i live in jakarta.', 'I live in jakarta.', 'i Live In Jakarta.']],
      ['Kalimat topik yang tepat untuk perkenalan adalah...', 'My name is Rudi and I am twenty.', ['Then I play.', 'Because it is fun.', 'Finally I sleep.']],
      ['Bentuk yang benar untuk rencana adalah...', "I'm going to study IT.", ['I studied IT next year.', 'I study IT last year.', 'I am study IT.']],
      ['Tanda baca di akhir kalimat berita adalah...', 'titik (.)', ['tanda tanya (?)', 'koma (,)', 'tanpa tanda baca']],
    ],
    task: 'Tulis paragraf perkenalan 100–120 kata lalu periksa dengan rubrik menulis A1.',
  },
];
