import type { ExtraEnglishLesson } from './types';

export const beginnerPronunciationExtra: ExtraEnglishLesson[] = [
  {
    id: 11, title: 'Short i vs Long ee', subtitle: 'ship /ɪ/ vs sheep /iː/',
    intro: 'Bunyi /ɪ/ pendek dan santai, bunyi /iː/ panjang dengan bibir tersenyum. Salah bunyi bisa mengubah arti.',
    points: ['/ɪ/: sit, ship, live, fill — pendek.', '/iː/: seat, sheep, leave, feel — panjang, tarik bibir.', 'Latih berpasangan: sit – seat, live – leave.'],
    examples: [['ship — sheep', 'kapal — domba'], ['sit — seat', 'duduk — kursi'], ['live — leave', 'tinggal — pergi'], ['fill — feel', 'mengisi — merasa'], ['I live here. / I leave now.', 'Saya tinggal di sini. / Saya pergi sekarang.']],
    practice: [
      ['Kata dengan bunyi /iː/ panjang adalah...', 'sheep', ['ship', 'sit', 'fill']],
      ['Kata dengan bunyi /ɪ/ pendek adalah...', 'live', ['leave', 'seat', 'feel']],
      ['Pasangan minimal yang benar adalah...', 'sit – seat', ['sit – sat', 'seat – sun', 'ship – shop']],
      ['"I want to leave." artinya...', 'Saya ingin pergi.', ['Saya ingin tinggal.', 'Saya ingin hidup.', 'Saya ingin duduk.']],
      ['Untuk bunyi /iː/, bibir sebaiknya...', 'ditarik seperti tersenyum', ['dibulatkan', 'ditutup rapat', 'dibuka lebar ke bawah']],
    ],
    task: 'Rekam 5 pasangan kata (ship/sheep, sit/seat, live/leave, fill/feel, hit/heat) dan dengarkan perbedaannya.',
  },
  {
    id: 12, title: 'Akhiran -s: /s/ /z/ /ɪz/', subtitle: 'books · dogs · buses',
    intro: 'Akhiran -s pada kata jamak dan kata kerja orang ketiga punya tiga bunyi tergantung bunyi terakhir kata.',
    points: ['/s/ setelah bunyi tak bersuara (p, t, k, f): books, cats, stops.', '/z/ setelah bunyi bersuara dan vokal: dogs, plays, calls.', '/ɪz/ setelah s, z, sh, ch, x: buses, watches, boxes.'],
    examples: [['books /s/', 'buku-buku'], ['dogs /z/', 'anjing-anjing'], ['buses /ɪz/', 'bus-bus'], ['She watches TV.', 'Dia menonton TV.'], ['He plays football.', 'Dia bermain sepak bola.']],
    practice: [
      ['Akhiran "watches" dibaca...', '/ɪz/', ['/s/', '/z/', 'tidak dibaca']],
      ['Akhiran "cats" dibaca...', '/s/', ['/z/', '/ɪz/', '/es/']],
      ['Akhiran "plays" dibaca...', '/z/', ['/s/', '/ɪz/', '/is/']],
      ['Kata yang berakhiran bunyi /ɪz/ adalah...', 'boxes', ['books', 'pens', 'maps']],
      ['Kata yang berakhiran bunyi /z/ adalah...', 'calls', ['stops', 'wishes', 'laughs']],
    ],
    task: 'Buat tabel 3 kolom (/s/, /z/, /ɪz/) dan isi masing-masing dengan 4 kata, lalu baca keras-keras.',
  },
  {
    id: 13, title: 'Akhiran -ed: /t/ /d/ /ɪd/', subtitle: 'walked · played · wanted',
    intro: 'Kata kerja lampau beraturan berakhiran -ed dibaca dengan tiga cara.',
    points: ['/t/ setelah bunyi tak bersuara: walked, stopped, washed.', '/d/ setelah bunyi bersuara: played, called, lived.', '/ɪd/ hanya setelah t atau d: wanted, needed.'],
    examples: [['walked /t/', 'berjalan (lampau)'], ['played /d/', 'bermain (lampau)'], ['wanted /ɪd/', 'ingin (lampau)'], ['I needed help.', 'Saya butuh bantuan.'], ['She cooked dinner.', 'Dia memasak makan malam.']],
    practice: [
      ['"needed" dibaca dengan akhiran...', '/ɪd/', ['/t/', '/d/', 'tanpa bunyi']],
      ['"cooked" dibaca dengan akhiran...', '/t/', ['/d/', '/ɪd/', '/ed/']],
      ['"called" dibaca dengan akhiran...', '/d/', ['/t/', '/ɪd/', '/ked/']],
      ['Akhiran /ɪd/ muncul setelah bunyi...', 't atau d', ['k atau p', 'vokal', 's atau sh']],
      ['Kata yang TIDAK dibaca dengan /ɪd/ adalah...', 'jumped', ['started', 'visited', 'decided']],
    ],
    task: 'Baca 10 kata kerja lampau dan kelompokkan menurut bunyi akhirannya.',
  },
  {
    id: 14, title: 'Huruf Diam (Silent Letters)', subtitle: 'know · write · hour',
    intro: 'Beberapa huruf dalam bahasa Inggris ditulis tetapi tidak diucapkan.',
    points: ['k diam sebelum n: know, knife, knee.', 'w diam sebelum r: write, wrong.', 'h diam di awal beberapa kata: hour, honest. b diam setelah m: climb, comb.'],
    examples: [['know', 'tahu'], ['write', 'menulis'], ['hour', 'jam (60 menit)'], ['climb', 'memanjat'], ['I know the right answer.', 'Saya tahu jawaban yang benar.']],
    practice: [
      ['Huruf yang tidak dibaca dalam "knife" adalah...', 'k', ['n', 'f', 'e']],
      ['Huruf yang tidak dibaca dalam "write" adalah...', 'w', ['r', 't', 'i']],
      ['"hour" dibaca mirip dengan...', 'our', ['her', 'how', 'hot']],
      ['Huruf diam dalam "comb" adalah...', 'b', ['c', 'm', 'o']],
      ['Kata yang TIDAK memiliki huruf diam adalah...', 'hotel', ['honest', 'knee', 'wrong']],
    ],
    task: 'Cari 8 kata dengan huruf diam, tulis dan coret huruf diamnya, lalu ucapkan.',
  },
  {
    id: 15, title: 'Kontraksi', subtitle: "I'm · don't · it's · can't",
    intro: 'Dalam percakapan, penutur asli menyingkat kata. Kontraksi membuat bicara lebih alami.',
    points: ["I am → I'm, you are → you're, it is → it's.", "do not → don't, does not → doesn't, cannot → can't.", "I will → I'll, we have → we've."],
    examples: [["I'm tired.", 'Saya lelah.'], ["It's cold today.", 'Hari ini dingin.'], ["I don't know.", 'Saya tidak tahu.'], ["She can't come.", 'Dia tidak bisa datang.'], ["We'll call you.", 'Kami akan meneleponmu.']],
    practice: [
      ['Kontraksi dari "do not" adalah...', "don't", ["dont'", "do'nt", "doesn't"]],
      ['Kontraksi dari "cannot" adalah...', "can't", ["cann't", "ca'nt", "cant'"]],
      ['"It\'s" adalah singkatan dari...', 'it is', ['its', 'it was', 'it does']],
      ['Kontraksi dari "I will" adalah...', "I'll", ["I'l", "Il'l", "I'will"]],
      ['Kalimat dengan kontraksi yang benar adalah...', "They're my friends.", ["Their'e my friends.", "They'r my friends.", "Theyre' my friends."]],
    ],
    task: 'Ubah 8 kalimat penuh menjadi bentuk kontraksi lalu ucapkan dengan cepat dan alami.',
  },
  {
    id: 16, title: 'Angka -teen vs -ty', subtitle: 'thirteen vs thirty',
    intro: 'Angka 13–19 dan 30–90 mudah tertukar. Bedanya ada pada tekanan dan bunyi akhir.',
    points: ['-teen: tekanan di akhir → thir-TEEN, fif-TEEN.', '-ty: tekanan di awal → THIR-ty, FIF-ty.', 'Bunyi -teen panjang /tiːn/, -ty pendek /ti/.'],
    examples: [['thirteen — thirty', '13 — 30'], ['fourteen — forty', '14 — 40'], ['fifteen — fifty', '15 — 50'], ['The bus leaves at four-fifteen.', 'Bus berangkat pukul 4.15.'], ["It's forty dollars.", 'Harganya 40 dolar.']],
    practice: [
      ['Angka dengan tekanan di akhir adalah...', 'sixteen', ['sixty', 'seventy', 'twenty']],
      ['"Fifty" adalah angka...', '50', ['15', '5', '500']],
      ['Tekanan pada "eighty" ada di suku kata...', 'pertama', ['kedua', 'ketiga', 'tidak ada']],
      ['"Nineteen" adalah angka...', '19', ['90', '9', '99']],
      ['Bunyi akhir -teen adalah...', 'panjang /tiːn/', ['pendek /ti/', 'diam', '/tɪd/']],
    ],
    task: 'Minta teman membacakan 10 angka acak (13–19 dan 30–90) lalu tulis angkanya.',
  },
  {
    id: 17, title: 'Intonasi Pertanyaan', subtitle: 'Yes/No naik · Wh- turun',
    intro: 'Pertanyaan yes/no biasanya naik di akhir, sedangkan pertanyaan Wh- biasanya turun.',
    points: ['Yes/No ↗: Are you ready? Do you like tea?', 'Wh- ↘: Where do you live? What is your name?', 'Kalimat berita ↘: I live in Bandung.'],
    examples: [['Are you hungry? ↗', 'Kamu lapar?'], ['Do you speak English? ↗', 'Kamu bisa bahasa Inggris?'], ['Where are you from? ↘', 'Kamu dari mana?'], ['What time is it? ↘', 'Jam berapa?'], ["I'm from Surabaya. ↘", 'Saya dari Surabaya.']],
    practice: [
      ['Intonasi "Are you ready?" di akhir biasanya...', 'naik', ['turun', 'datar', 'naik lalu turun dua kali']],
      ['Intonasi "Where do you work?" di akhir biasanya...', 'turun', ['naik', 'datar', 'naik tajam']],
      ['Pertanyaan yang biasanya berintonasi naik adalah...', 'Can you swim?', ['What is this?', 'Who is she?', 'How old are you?']],
      ['Kalimat berita "I like coffee." berakhir dengan intonasi...', 'turun', ['naik', 'naik tajam', 'tidak berubah']],
      ['Pertanyaan yang biasanya berintonasi turun adalah...', 'Why are you late?', ['Is it cold?', 'Are you OK?', 'Do you have a pen?']],
    ],
    task: 'Rekam 5 pertanyaan yes/no dan 5 pertanyaan Wh-, tandai panah ↗ atau ↘ untuk tiap kalimat.',
  },
  {
    id: 18, title: 'Menyambung Kata (Linking)', subtitle: 'an apple · pick it up',
    intro: 'Penutur asli menyambung konsonan akhir dengan vokal awal kata berikutnya sehingga terdengar seperti satu kata.',
    points: ['Konsonan + vokal: an_apple → "a-napple".', 'pick_it_up → "pi-ki-tup".', 'Latih pelan dulu, lalu percepat.'],
    examples: [['an apple', 'sebuah apel'], ['pick it up', 'ambil itu'], ['turn it off', 'matikan itu'], ['Is it open?', 'Apakah itu buka?'], ['Come in!', 'Masuk!']],
    practice: [
      ['"an apple" terdengar seperti...', 'a-napple', ['an-ap-ple terpisah', 'a-pple', 'an-nap-pel-le']],
      ['Linking terjadi saat konsonan akhir bertemu...', 'vokal awal kata berikutnya', ['konsonan awal', 'tanda titik', 'angka']],
      ['"turn it off" dibaca alami seperti...', 'tur-ni-toff', ['turn / it / off terputus', 'tur-toff', 'turnit-of-fe']],
      ['Frasa yang cocok untuk linking adalah...', 'look at', ['big dog', 'red car', 'hot tea']],
      ['Tujuan linking adalah...', 'bicara lebih lancar dan alami', ['mengeja lebih jelas', 'memperlambat bicara', 'menghilangkan vokal']],
    ],
    task: 'Latih 8 frasa linking (get up, look at it, a lot of, come on in...) dengan kecepatan pelan lalu normal.',
  },
  {
    id: 19, title: 'V vs F · B vs P', subtitle: 'very · fine · bag · pack',
    intro: 'Penutur Indonesia sering menukar v/f dan b/p. Bedanya ada pada getaran pita suara.',
    points: ['/v/ bergetar, /f/ tidak: van – fan.', '/b/ bergetar, /p/ tidak (dengan hembusan): bag – pack.', 'Sentuh leher: terasa getaran untuk /v/ dan /b/.'],
    examples: [['van — fan', 'mobil van — kipas'], ['very — ferry', 'sangat — kapal feri'], ['bag — pack', 'tas — mengemas'], ['I have a very big bag.', 'Saya punya tas yang sangat besar.'], ['Five fine violins.', 'Lima biola bagus.']],
    practice: [
      ['Bunyi yang membuat pita suara bergetar adalah...', '/v/', ['/f/', '/p/', '/s/']],
      ['Pasangan minimal v–f yang benar adalah...', 'van – fan', ['van – ban', 'fan – pan', 'vet – bet']],
      ['/p/ diucapkan dengan...', 'hembusan udara tanpa getaran', ['getaran kuat', 'bibir bawah menyentuh gigi atas', 'lidah di antara gigi']],
      ['Untuk /v/, bibir bawah menyentuh...', 'gigi atas', ['bibir atas', 'langit-langit', 'gigi bawah']],
      ['"Very" dimulai dengan bunyi...', '/v/', ['/f/', '/b/', '/w/']],
    ],
    task: 'Rekam kalimat "Vivian found five very big bags" 3 kali, lalu periksa v/f dan b/p-nya.',
  },
  {
    id: 20, title: 'Membaca Nyaring A1', subtitle: 'Gabungan bunyi, tekanan, dan intonasi',
    intro: 'Latihan akhir: baca paragraf pendek dengan bunyi vokal yang tepat, akhiran -s/-ed, dan intonasi yang benar.',
    points: ['Baca pelan, beri jeda di koma dan titik.', 'Perhatikan akhiran -s dan -ed.', 'Turunkan intonasi di akhir kalimat berita.'],
    examples: [["Hi! I'm Lina and I live in a small city.", 'Hai! Saya Lina dan saya tinggal di kota kecil.'], ['Every morning I walk to work.', 'Setiap pagi saya berjalan kaki ke kantor.'], ['Yesterday I visited my friend and we cooked dinner.', 'Kemarin saya mengunjungi teman dan kami memasak makan malam.'], ['Do you want to join us next week?', 'Kamu mau ikut minggu depan?']],
    practice: [
      ['Dalam "walked", akhiran -ed dibaca...', '/t/', ['/d/', '/ɪd/', 'tidak dibaca']],
      ['Dalam "visited", akhiran -ed dibaca...', '/ɪd/', ['/t/', '/d/', '/ed/ panjang']],
      ['Intonasi "Do you want to join us?" di akhir...', 'naik', ['turun', 'datar', 'naik lalu turun']],
      ['Di mana sebaiknya memberi jeda saat membaca?', 'Di koma dan titik', ['Setelah setiap kata', 'Tidak perlu jeda', 'Hanya di akhir paragraf']],
      ['"I\'m" adalah bentuk singkat dari...', 'I am', ['I have', 'I was', 'I will']],
    ],
    task: 'Rekam dirimu membaca contoh paragraf di atas, lalu bandingkan dengan audio model.',
  },
];

export const beginnerReadingExtra: ExtraEnglishLesson[] = [
  {
    id: 11, title: 'Kartu Ucapan', subtitle: 'Birthday card & thank-you card',
    intro: 'Kartu ucapan berisi salam, pesan singkat, dan nama pengirim. Cari siapa penerima, acara, dan harapannya.',
    points: ['Pembuka: Dear..., Hi...', 'Isi: Happy birthday! Thank you for...', 'Penutup: Love, Best wishes, From...'],
    examples: [['Happy birthday!', 'Selamat ulang tahun!'], ['Thank you for the lovely gift.', 'Terima kasih atas hadiahnya yang indah.'], ['Best wishes,', 'Salam hangat,'], ['I hope you have a great day.', 'Semoga harimu menyenangkan.']],
    dialogue: [['Card', 'Dear Grandma,', 'Nenek tersayang,'], ['Card', 'Happy 70th birthday!', 'Selamat ulang tahun ke-70!'], ['Card', 'Thank you for the delicious cakes every Sunday.', 'Terima kasih atas kue lezat setiap hari Minggu.'], ['Card', "I'm sorry I can't come to your party. I have an exam.", 'Maaf saya tidak bisa datang ke pestamu. Saya ada ujian.'], ['Card', 'I will visit you next weekend with Mom.', 'Saya akan mengunjungimu akhir pekan depan bersama Ibu.'], ['Card', 'Love, Nadia', 'Sayang, Nadia']],
    practice: [
      ['Kartu ini untuk siapa?', 'Nenek', ['Ibu', 'Guru', 'Teman']],
      ['Nenek berulang tahun ke berapa?', '70', ['17', '60', '75']],
      ['Mengapa Nadia tidak bisa datang?', 'Ada ujian', ['Sakit', 'Bekerja', 'Sedang di luar negeri']],
      ['Kapan Nadia akan berkunjung?', 'Akhir pekan depan', ['Besok', 'Bulan depan', 'Hari ini']],
      ['Apa yang Nenek buat setiap Minggu?', 'Kue', ['Teh', 'Kartu', 'Sup']],
    ],
    task: 'Tulis kartu ucapan ulang tahun (4–5 kalimat) untuk teman atau anggota keluarga.',
  },
  {
    id: 12, title: 'Profil Media Sosial', subtitle: 'Bio singkat dan info pribadi',
    intro: 'Profil media sosial berisi nama, asal, pekerjaan, hobi, dan kalimat pendek. Latih scanning informasi cepat.',
    points: ['Scanning: cari informasi tertentu tanpa membaca semua kata.', 'Kata kunci: from, lives in, works as, loves.', 'Emoji dan simbol sering menggantikan kata.'],
    examples: [["I'm from Medan.", 'Saya dari Medan.'], ['I work as a nurse.', 'Saya bekerja sebagai perawat.'], ['I love hiking and coffee.', 'Saya suka mendaki dan kopi.'], ['Follow me for travel photos!', 'Ikuti saya untuk foto perjalanan!']],
    dialogue: [['Profile', 'Name: Rizky Hakim', 'Nama: Rizky Hakim'], ['Profile', "I'm 24 and I'm from Makassar, but I live in Jakarta now.", 'Saya 24 tahun, dari Makassar, tapi sekarang tinggal di Jakarta.'], ['Profile', 'I work as a graphic designer at a small company.', 'Saya bekerja sebagai desainer grafis di perusahaan kecil.'], ['Profile', 'I love cats, street food, and old movies.', 'Saya suka kucing, jajanan kaki lima, dan film lama.'], ['Profile', 'I post new drawings every Friday.', 'Saya mengunggah gambar baru setiap Jumat.'], ['Profile', 'Languages: Indonesian, English, a little Japanese.', 'Bahasa: Indonesia, Inggris, sedikit Jepang.']],
    practice: [
      ['Berapa usia Rizky?', '24', ['42', '20', '34']],
      ['Di mana Rizky tinggal sekarang?', 'Jakarta', ['Makassar', 'Bandung', 'Bali']],
      ['Apa pekerjaan Rizky?', 'Desainer grafis', ['Guru', 'Fotografer', 'Koki']],
      ['Kapan Rizky mengunggah gambar baru?', 'Setiap Jumat', ['Setiap hari', 'Setiap Senin', 'Sebulan sekali']],
      ['Bahasa apa yang hanya sedikit ia kuasai?', 'Jepang', ['Inggris', 'Indonesia', 'Korea']],
    ],
    task: 'Tulis bio profil media sosialmu dalam bahasa Inggris (5–6 baris).',
  },
  {
    id: 13, title: 'Email Sederhana', subtitle: 'Undangan dari teman',
    intro: 'Email informal punya subjek, salam, isi, dan penutup. Temukan tujuan email dan detail penting.',
    points: ['Subject: menunjukkan topik.', 'Isi: apa, kapan, di mana.', 'Penutup: See you, Cheers, Take care.'],
    examples: [['Subject: Picnic on Saturday', 'Subjek: Piknik hari Sabtu'], ['Would you like to come?', 'Apakah kamu mau datang?'], ["Let me know by Thursday.", 'Kabari saya paling lambat Kamis.'], ['Take care,', 'Jaga diri,']],
    dialogue: [['Email', 'Subject: Picnic on Saturday', 'Subjek: Piknik hari Sabtu'], ['Email', 'Hi Tari,', 'Hai Tari,'], ['Email', "We're having a picnic at Green Park this Saturday at ten.", 'Kami mengadakan piknik di Green Park Sabtu ini jam sepuluh.'], ['Email', 'Please bring some fruit. I will bring sandwiches and drinks.', 'Tolong bawa buah. Saya akan bawa roti lapis dan minuman.'], ['Email', "If it rains, we'll meet at my house instead.", 'Kalau hujan, kita bertemu di rumah saya saja.'], ['Email', 'Let me know by Thursday. Cheers, Bella', 'Kabari saya paling lambat Kamis. Salam, Bella']],
    practice: [
      ['Apa tujuan email ini?', 'Mengundang piknik', ['Meminta maaf', 'Menjual buah', 'Mengumumkan ujian']],
      ['Di mana pikniknya?', 'Green Park', ['Rumah Tari', 'Pantai', 'Sekolah']],
      ['Apa yang harus dibawa Tari?', 'Buah', ['Roti lapis', 'Minuman', 'Tikar']],
      ['Apa rencana jika hujan?', 'Bertemu di rumah Bella', ['Piknik dibatalkan', 'Pindah ke mal', 'Diundur ke Minggu']],
      ['Tari harus membalas paling lambat...', 'Kamis', ['Jumat', 'Sabtu', 'Senin']],
    ],
    task: 'Balas email Bella (4–5 kalimat): terima undangan dan sebutkan buah yang akan kamu bawa.',
  },
  {
    id: 14, title: 'Rambu & Tanda', subtitle: 'No parking · Exit · Wet floor',
    intro: 'Rambu memakai kata sangat singkat. Pahami perintah, larangan, dan peringatan.',
    points: ['Larangan: No smoking, Do not enter.', 'Peringatan: Caution, Wet floor, Danger.', 'Petunjuk: Exit, Push/Pull, Open 24 hours.'],
    examples: [['No parking', 'Dilarang parkir'], ['Caution: wet floor', 'Hati-hati: lantai basah'], ['Push', 'Dorong'], ['Staff only', 'Khusus staf'], ['Keep off the grass', 'Jangan menginjak rumput']],
    dialogue: [['Sign 1', 'EMERGENCY EXIT — Keep clear', 'PINTU DARURAT — Jangan dihalangi'], ['Sign 2', 'Please queue here', 'Silakan antre di sini'], ['Sign 3', 'No food or drinks in the library', 'Dilarang membawa makanan dan minuman di perpustakaan'], ['Sign 4', 'Out of order', 'Rusak / tidak berfungsi'], ['Sign 5', 'Open Monday to Friday, 8 a.m. – 5 p.m.', 'Buka Senin–Jumat, 08.00–17.00'], ['Sign 6', 'Mind the gap', 'Perhatikan celah (antara kereta dan peron)']],
    practice: [
      ['"Out of order" pada lift artinya...', 'Lift rusak', ['Lift penuh', 'Lift khusus staf', 'Lift darurat']],
      ['Tanda "Please queue here" meminta kamu...', 'antre di sini', ['duduk di sini', 'membayar di sini', 'menunggu di luar']],
      ['Kapan tempat ini tutup menurut Sign 5?', 'Sabtu dan Minggu', ['Senin', 'Jumat sore', 'Setiap malam jam 8']],
      ['"Staff only" artinya...', 'Khusus staf', ['Staf sedang istirahat', 'Cari staf', 'Staf di luar']],
      ['Di mana kamu biasanya melihat "Mind the gap"?', 'Stasiun kereta', ['Perpustakaan', 'Restoran', 'Rumah sakit']],
    ],
    task: 'Foto atau gambar 5 tanda berbahasa Inggris di sekitarmu dan tulis artinya.',
  },
  {
    id: 15, title: 'Resep Singkat', subtitle: 'Bahan dan langkah',
    intro: 'Resep punya daftar bahan (ingredients) dan langkah (steps) dengan kata kerja perintah.',
    points: ['Ingredients: 2 eggs, 1 cup of milk.', 'Langkah memakai imperatif: Mix, Cut, Boil, Add.', 'Urutan: first, then, finally.'],
    examples: [['2 eggs', '2 butir telur'], ['a pinch of salt', 'sejumput garam'], ['Mix the eggs and milk.', 'Campur telur dan susu.'], ['Cook for three minutes.', 'Masak selama tiga menit.']],
    dialogue: [['Recipe', 'Banana Pancakes (for 2 people)', 'Panekuk Pisang (untuk 2 orang)'], ['Recipe', 'Ingredients: 1 banana, 2 eggs, 4 spoons of flour, a little oil.', 'Bahan: 1 pisang, 2 telur, 4 sendok tepung, sedikit minyak.'], ['Recipe', 'First, mash the banana in a bowl.', 'Pertama, haluskan pisang dalam mangkuk.'], ['Recipe', 'Then add the eggs and flour and mix well.', 'Lalu tambahkan telur dan tepung dan aduk rata.'], ['Recipe', 'Heat the oil in a pan and cook small pancakes for two minutes on each side.', 'Panaskan minyak di wajan dan masak panekuk kecil dua menit tiap sisi.'], ['Recipe', 'Finally, serve with honey.', 'Terakhir, sajikan dengan madu.']],
    practice: [
      ['Resep ini untuk berapa orang?', '2', ['1', '4', '6']],
      ['Berapa telur yang dibutuhkan?', '2', ['1', '4', '3']],
      ['Apa langkah pertama?', 'Menghaluskan pisang', ['Memanaskan minyak', 'Menambahkan tepung', 'Menyajikan dengan madu']],
      ['Berapa lama setiap sisi dimasak?', '2 menit', ['1 menit', '4 menit', '10 menit']],
      ['Panekuk disajikan dengan...', 'madu', ['gula', 'cokelat', 'selai']],
    ],
    task: 'Tulis resep makanan favoritmu (bahan + 4 langkah) dalam bahasa Inggris.',
  },
  {
    id: 16, title: 'Cerita Pendek: Hari Hujan', subtitle: 'Membaca narasi sederhana',
    intro: 'Baca cerita pendek dan pahami tokoh, masalah, dan akhir cerita.',
    points: ['Siapa tokohnya? Apa masalahnya? Bagaimana akhirnya?', 'Kata kerja lampau menceritakan kejadian.', 'Tebak arti kata dari konteks.'],
    examples: [['It was raining heavily.', 'Hujan turun deras.'], ['He forgot his umbrella.', 'Dia lupa payungnya.'], ['A kind woman helped him.', 'Seorang wanita baik menolongnya.'], ['He was very happy.', 'Dia sangat senang.']],
    dialogue: [['Story', 'On Monday morning, Budi left home late.', 'Senin pagi, Budi berangkat terlambat.'], ['Story', 'It was raining heavily, and he forgot his umbrella.', 'Hujan deras dan dia lupa membawa payung.'], ['Story', 'He waited at the bus stop, cold and wet.', 'Dia menunggu di halte bus, kedinginan dan basah.'], ['Story', 'An old woman shared her big umbrella with him.', 'Seorang nenek berbagi payung besarnya dengannya.'], ['Story', 'They talked and laughed until the bus came.', 'Mereka mengobrol dan tertawa sampai bus datang.'], ['Story', 'The next day, Budi brought her a cup of hot tea to say thank you.', 'Keesokan harinya, Budi membawakan teh hangat sebagai ucapan terima kasih.']],
    practice: [
      ['Apa masalah Budi?', 'Lupa membawa payung saat hujan', ['Kehilangan tas', 'Bus mogok', 'Salah naik bus']],
      ['Di mana Budi menunggu?', 'Halte bus', ['Stasiun', 'Sekolah', 'Toko']],
      ['Siapa yang menolong Budi?', 'Seorang nenek', ['Teman sekolah', 'Sopir bus', 'Ibunya']],
      ['Apa yang Budi bawa keesokan harinya?', 'Teh hangat', ['Payung baru', 'Bunga', 'Kue']],
      ['"Heavily" dalam "raining heavily" artinya...', 'deras', ['sedikit', 'pelan', 'kemarin']],
    ],
    task: 'Tulis akhir cerita yang berbeda (3–4 kalimat) untuk kisah Budi.',
  },
  {
    id: 17, title: 'Brosur Kebun Binatang', subtitle: 'Harga tiket & jadwal',
    intro: 'Brosur berisi informasi harga, jam buka, dan kegiatan. Latih scanning angka dan waktu.',
    points: ['Tiket: adult (dewasa), child (anak), under 3 free.', 'Jadwal kegiatan: feeding time, show.', 'Info tambahan: parking, café, gift shop.'],
    examples: [['Adults: $10', 'Dewasa: 10 dolar'], ['Children under 3: free', 'Anak di bawah 3 tahun: gratis'], ['Feeding time: 2 p.m.', 'Waktu memberi makan: 14.00'], ['Closed on Mondays', 'Tutup setiap Senin']],
    dialogue: [['Brochure', 'City Zoo — Open Tuesday to Sunday, 9 a.m. to 5 p.m.', 'Kebun Binatang Kota — Buka Selasa–Minggu, 09.00–17.00'], ['Brochure', 'Tickets: Adults $12, Children (3–12) $6, Under 3 free.', 'Tiket: Dewasa $12, Anak (3–12) $6, di bawah 3 gratis.'], ['Brochure', 'Elephant show: 11 a.m. and 3 p.m.', 'Pertunjukan gajah: 11.00 dan 15.00'], ['Brochure', 'Penguin feeding time: 1:30 p.m.', 'Waktu memberi makan penguin: 13.30'], ['Brochure', 'Free parking. Café and gift shop near the main gate.', 'Parkir gratis. Kafe dan toko suvenir dekat gerbang utama.'], ['Brochure', 'Please do not feed the animals.', 'Harap jangan memberi makan hewan.']],
    practice: [
      ['Hari apa kebun binatang tutup?', 'Senin', ['Minggu', 'Selasa', 'Sabtu']],
      ['Berapa harga tiket anak usia 8 tahun?', '$6', ['$12', 'Gratis', '$3']],
      ['Jam berapa pertunjukan gajah sore?', '15.00', ['13.30', '11.00', '17.00']],
      ['Di mana kafe berada?', 'Dekat gerbang utama', ['Dekat kandang penguin', 'Di tempat parkir', 'Di pintu belakang']],
      ['Apa yang dilarang?', 'Memberi makan hewan', ['Parkir', 'Mengambil foto', 'Membawa anak kecil']],
    ],
    task: 'Hitung biaya tiket untuk keluargamu dan tulis rencana kunjungan (jam dan pertunjukan).',
  },
  {
    id: 18, title: 'Tiket Bus & Kereta', subtitle: 'Membaca informasi perjalanan',
    intro: 'Tiket berisi asal, tujuan, tanggal, waktu, kursi, dan kelas. Temukan info penting dengan cepat.',
    points: ['From / To = dari / ke.', 'Departure / Arrival = berangkat / tiba.', 'Seat, Coach, Class = kursi, gerbong, kelas.'],
    examples: [['From: Jakarta  To: Yogyakarta', 'Dari: Jakarta Ke: Yogyakarta'], ['Departure: 07:45', 'Berangkat: 07.45'], ['Coach 3, Seat 12A', 'Gerbong 3, Kursi 12A'], ['Economy class', 'Kelas ekonomi']],
    dialogue: [['Ticket', 'TRAIN TICKET — Passenger: Mr. Andi Wijaya', 'TIKET KERETA — Penumpang: Tn. Andi Wijaya'], ['Ticket', 'From: Surabaya  To: Malang', 'Dari: Surabaya Ke: Malang'], ['Ticket', 'Date: 14 August  Departure: 08:20  Arrival: 10:05', 'Tanggal: 14 Agustus Berangkat: 08.20 Tiba: 10.05'], ['Ticket', 'Coach 5, Seat 7C, Executive class', 'Gerbong 5, Kursi 7C, Kelas eksekutif'], ['Ticket', 'Please arrive 30 minutes before departure.', 'Harap tiba 30 menit sebelum berangkat.'], ['Ticket', 'This ticket is not refundable.', 'Tiket ini tidak dapat dikembalikan uangnya.']],
    practice: [
      ['Ke mana tujuan Andi?', 'Malang', ['Surabaya', 'Jakarta', 'Bandung']],
      ['Jam berapa kereta tiba?', '10.05', ['08.20', '10.50', '09.05']],
      ['Di gerbong berapa Andi duduk?', '5', ['7', '3', '14']],
      ['Andi harus datang paling lambat jam...', '07.50', ['08.20', '07.20', '08.00']],
      ['"Not refundable" artinya...', 'uang tidak bisa dikembalikan', ['tiket bisa ditukar', 'tiket gratis', 'tiket hilang']],
    ],
    task: 'Buat tiket perjalanan impianmu dalam bahasa Inggris dengan semua informasi di atas.',
  },
  {
    id: 19, title: 'Artikel Anak: Panda', subtitle: 'Teks informasi sederhana',
    intro: 'Teks informasi menjelaskan fakta. Temukan ide utama dan detail pendukung.',
    points: ['Ide utama biasanya di kalimat pertama.', 'Detail: angka, tempat, makanan, kebiasaan.', 'Kata "because" menjelaskan alasan.'],
    examples: [['Pandas live in China.', 'Panda hidup di Tiongkok.'], ['They eat bamboo.', 'Mereka makan bambu.'], ['They sleep a lot.', 'Mereka banyak tidur.'], ['Pandas are in danger because their forests are small.', 'Panda terancam karena hutannya kecil.']],
    dialogue: [['Article', 'Giant pandas are black and white bears from the mountains of China.', 'Panda raksasa adalah beruang hitam-putih dari pegunungan Tiongkok.'], ['Article', 'They eat bamboo for about twelve hours every day.', 'Mereka makan bambu sekitar dua belas jam setiap hari.'], ['Article', 'An adult panda can weigh more than 100 kilograms.', 'Panda dewasa bisa berbobot lebih dari 100 kilogram.'], ['Article', 'Baby pandas are very small, about the size of a stick of butter.', 'Bayi panda sangat kecil, kira-kira sebesar sebatang mentega.'], ['Article', 'Pandas are in danger because people cut down their forests.', 'Panda terancam karena manusia menebang hutan mereka.'], ['Article', 'Today, many parks protect pandas and their homes.', 'Kini banyak taman melindungi panda dan habitatnya.']],
    practice: [
      ['Dari mana panda raksasa berasal?', 'Tiongkok', ['Jepang', 'Afrika', 'Australia']],
      ['Berapa lama panda makan setiap hari?', 'Sekitar 12 jam', ['2 jam', '24 jam', '6 jam']],
      ['Berapa berat panda dewasa?', 'Lebih dari 100 kg', ['Sekitar 10 kg', 'Kurang dari 50 kg', 'Tepat 1 ton']],
      ['Mengapa panda terancam?', 'Hutannya ditebang', ['Tidak ada bambu di dunia', 'Terlalu banyak tidur', 'Diburu harimau']],
      ['Apa ide utama teks?', 'Fakta tentang panda raksasa', ['Cara memasak bambu', 'Kebun binatang di Jepang', 'Perjalanan ke Tiongkok']],
    ],
    task: 'Tulis 5 fakta tentang hewan favoritmu dalam bahasa Inggris.',
  },
  {
    id: 20, title: 'Latihan Akhir Membaca A1', subtitle: 'Pengumuman komunitas',
    intro: 'Tes akhir: baca pengumuman dan jawab pertanyaan detail. Gunakan skimming lalu scanning.',
    points: ['Skimming: baca cepat untuk ide umum.', 'Scanning: cari angka, tanggal, tempat.', 'Periksa kembali jawaban dengan teks.'],
    examples: [['Everyone is welcome!', 'Semua orang dipersilakan!'], ['Entry is free.', 'Masuk gratis.'], ['Please register online.', 'Silakan daftar daring.'], ['For more information, call...', 'Untuk informasi lebih lanjut, hubungi...']],
    dialogue: [['Notice', 'GREEN STREET CLEAN-UP DAY', 'HARI BERSIH-BERSIH JALAN GREEN'], ['Notice', 'Saturday, 5 October, from 7 a.m. to 10 a.m.', 'Sabtu, 5 Oktober, pukul 07.00–10.00'], ['Notice', 'Meet at the community hall next to the mosque.', 'Berkumpul di balai warga di sebelah masjid.'], ['Notice', 'Bring gloves and a bottle of water. Bags are provided.', 'Bawa sarung tangan dan sebotol air. Kantong disediakan.'], ['Notice', 'Free breakfast for all volunteers at 10 a.m.!', 'Sarapan gratis untuk semua relawan pukul 10.00!'], ['Notice', 'Register by Thursday: text Mr. Joko at 0813 222 404.', 'Daftar paling lambat Kamis: SMS Pak Joko di 0813 222 404.']],
    practice: [
      ['Apa acara ini?', 'Bersih-bersih jalan', ['Lomba lari', 'Pasar murah', 'Pesta ulang tahun']],
      ['Di mana peserta berkumpul?', 'Balai warga sebelah masjid', ['Di taman', 'Di sekolah', 'Di rumah Pak Joko']],
      ['Apa yang harus dibawa peserta?', 'Sarung tangan dan air', ['Kantong sampah', 'Sapu', 'Makanan']],
      ['Apa yang didapat relawan jam 10?', 'Sarapan gratis', ['Uang', 'Kaos', 'Sertifikat']],
      ['Bagaimana cara mendaftar?', 'Mengirim SMS ke Pak Joko', ['Datang langsung hari Sabtu', 'Mengisi formulir di masjid', 'Email ke sekolah']],
    ],
    task: 'Tulis pengumuman acara komunitasmu sendiri (5–6 baris) dengan waktu, tempat, dan cara daftar.',
  },
];
