import type { ExtraEnglishLesson } from './types';

export const beginnerGrammarExtra: ExtraEnglishLesson[] = [
  {
    id: 15, title: "Possessive 's & Whose", subtitle: "Tom's bag · Whose book is this?",
    intro: "Untuk menyatakan kepemilikan orang, tambahkan 's setelah nama/kata benda. Untuk bertanya milik siapa, pakai Whose.",
    points: ["Nama + 's: Anna's phone, my brother's car.", "Kata benda jamak berakhiran -s cukup tambah apostrof: my parents' house.", "Whose + benda + is this/are these? → Whose bag is this?"],
    examples: [["This is Anna's phone.", 'Ini ponsel Anna.'], ["My brother's car is red.", 'Mobil kakak/adik laki-laki saya merah.'], ["Whose book is this? — It's Tom's.", 'Buku siapa ini? — Punya Tom.'], ["The teachers' room is upstairs.", 'Ruang guru ada di lantai atas.'], ["Whose shoes are these?", 'Sepatu siapa ini?']],
    practice: [
      ['"Buku milik Sara" dalam bahasa Inggris adalah...', "Sara's book", ['Sara book', "book's Sara", 'Saras book']],
      ['Kata tanya untuk "milik siapa" adalah...', 'Whose', ['Who', 'Where', 'Which']],
      ['"Rumah orang tua saya" yang benar adalah...', "my parents' house", ["my parent's houses", 'my parents house', "my parentses' house"]],
      ['Lengkapi: "___ bag is this? — It is Mia\'s."', 'Whose', ['Who', 'What', 'Who\'s']],
      ['"It\'s Tom\'s." artinya...', 'Itu milik Tom.', ['Itu Tom.', 'Tom ada di sana.', 'Tom sedang pergi.']],
    ],
    task: "Tulis 5 kalimat tentang barang milik anggota keluargamu memakai 's, lalu buat 2 pertanyaan dengan Whose.",
  },
  {
    id: 16, title: 'Present Continuous (Sekarang)', subtitle: 'I am eating · She is working',
    intro: 'Present continuous dipakai untuk kegiatan yang sedang terjadi sekarang. Rumusnya: am/is/are + kata kerja-ing.',
    points: ['I am + V-ing, he/she/it is + V-ing, you/we/they are + V-ing.', 'Negatif: I am not eating. Pertanyaan: Are you eating?', 'Kata petunjuk: now, right now, at the moment, look!'],
    examples: [['I am reading a book now.', 'Saya sedang membaca buku sekarang.'], ['She is cooking dinner.', 'Dia sedang memasak makan malam.'], ['They are playing football.', 'Mereka sedang bermain sepak bola.'], ['Are you watching TV?', 'Apakah kamu sedang menonton TV?'], ['He is not sleeping.', 'Dia tidak sedang tidur.']],
    practice: [
      ['Lengkapi: "She ___ cooking now."', 'is', ['are', 'am', 'be']],
      ['Bentuk -ing dari "run" adalah...', 'running', ['runing', 'runnning', 'runs']],
      ['Kalimat yang benar adalah...', 'They are playing now.', ['They playing now.', 'They is playing now.', 'They are play now.']],
      ['"Are you watching TV?" artinya...', 'Apakah kamu sedang menonton TV?', ['Apakah kamu suka TV?', 'Apakah kamu punya TV?', 'Kamu menonton TV kemarin?']],
      ['Kata yang menandai present continuous adalah...', 'right now', ['yesterday', 'every day', 'last week']],
    ],
    task: 'Lihat sekelilingmu dan tulis 6 kalimat tentang apa yang sedang dilakukan orang-orang sekarang.',
  },
  {
    id: 17, title: 'Object Pronouns', subtitle: 'me · you · him · her · us · them',
    intro: 'Object pronoun menggantikan kata benda yang menjadi objek (setelah kata kerja atau preposisi).',
    points: ['I → me, you → you, he → him, she → her, it → it, we → us, they → them.', 'Letaknya setelah kata kerja: I like her.', 'Atau setelah preposisi: Come with me.'],
    examples: [['Please call me tomorrow.', 'Tolong telepon saya besok.'], ['I know him.', 'Saya kenal dia (laki-laki).'], ['Can you help us?', 'Bisakah kamu membantu kami?'], ['I love them.', 'Saya menyayangi mereka.'], ['This gift is for her.', 'Hadiah ini untuk dia (perempuan).']],
    practice: [
      ['Object pronoun untuk "she" adalah...', 'her', ['she', 'hers', 'him']],
      ['Lengkapi: "Can you help ___? (kami)"', 'us', ['we', 'our', 'ours']],
      ['Kalimat yang benar adalah...', 'I like them.', ['I like they.', 'I like their.', 'Me like them.']],
      ['"Come with me." artinya...', 'Ikutlah dengan saya.', ['Saya datang.', 'Datanglah sendiri.', 'Saya ikut kamu.']],
      ['Lengkapi: "I know ___. He is my teacher."', 'him', ['he', 'his', 'her']],
    ],
    task: 'Tulis 5 kalimat tentang orang yang kamu kenal memakai object pronoun (him, her, them, us, me).',
  },
  {
    id: 18, title: 'Some / Any · How much / How many', subtitle: 'Countable & uncountable dasar',
    intro: 'Some dipakai di kalimat positif, any di kalimat negatif dan pertanyaan. How many untuk benda yang bisa dihitung, how much untuk yang tidak bisa dihitung.',
    points: ['There are some apples. / There aren\'t any apples. / Are there any apples?', 'How many + benda jamak: How many eggs?', 'How much + benda tak terhitung: How much water? How much is it? (harga)'],
    examples: [['I have some water.', 'Saya punya sedikit air.'], ["We don't have any milk.", 'Kami tidak punya susu sama sekali.'], ['Are there any chairs?', 'Apakah ada kursi?'], ['How many brothers do you have?', 'Berapa saudara laki-laki yang kamu punya?'], ['How much sugar do you want?', 'Berapa banyak gula yang kamu mau?']],
    practice: [
      ['Lengkapi: "I don\'t have ___ money."', 'any', ['some', 'many', 'a']],
      ['Lengkapi: "How ___ apples do you need?"', 'many', ['much', 'any', 'some']],
      ['Lengkapi: "How ___ rice do we have?"', 'much', ['many', 'any', 'more']],
      ['Kalimat yang benar adalah...', 'There are some books on the table.', ['There are any books on the table.', 'There is some books on the table.', 'There are much books on the table.']],
      ['"How much is it?" biasanya menanyakan...', 'harga', ['jumlah orang', 'waktu', 'jarak']],
    ],
    task: 'Tulis daftar isi kulkasmu: 3 kalimat dengan some, 3 dengan any, dan 2 pertanyaan dengan how many/how much.',
  },
  {
    id: 19, title: 'Going to (Rencana)', subtitle: "I'm going to visit my grandma",
    intro: 'Be going to + kata kerja dasar dipakai untuk rencana yang sudah diputuskan.',
    points: ["I'm going to + V1: I'm going to study tonight.", "Negatif: She isn't going to come.", 'Pertanyaan: Are you going to travel next week?'],
    examples: [["I'm going to visit my grandma on Sunday.", 'Saya akan mengunjungi nenek hari Minggu.'], ["We're going to watch a movie tonight.", 'Kami akan menonton film malam ini.'], ["He isn't going to work tomorrow.", 'Dia tidak akan bekerja besok.'], ['Are you going to buy a new phone?', 'Apakah kamu akan membeli ponsel baru?'], ["It's going to rain.", 'Akan turun hujan.']],
    practice: [
      ['Lengkapi: "I ___ going to study tonight."', 'am', ['is', 'are', 'be']],
      ['Kalimat yang benar adalah...', 'She is going to call you.', ['She going to call you.', 'She is going call you.', 'She is go to call you.']],
      ['"Be going to" dipakai untuk...', 'rencana yang sudah diputuskan', ['kebiasaan harian', 'kejadian kemarin', 'kemampuan']],
      ['"We\'re going to watch a movie." artinya...', 'Kami akan menonton film.', ['Kami sedang menonton film.', 'Kami sudah menonton film.', 'Kami suka menonton film.']],
      ['Bentuk negatif: "He ___ going to come."', "isn't", ["doesn't", "don't", "aren't"]],
    ],
    task: 'Tulis 6 rencanamu untuk akhir pekan depan memakai be going to.',
  },
  {
    id: 20, title: 'Ulasan Akhir Grammar A1', subtitle: 'Campuran semua pola A1',
    intro: 'Pelajaran ini mengulang to be, present simple, present continuous, past simple, can, dan going to dalam konteks sehari-hari.',
    points: ['Kebiasaan: present simple (I work every day).', 'Sekarang: present continuous (I am working now).', 'Kemarin: past simple (I worked yesterday). Rencana: going to (I am going to work tomorrow).'],
    examples: [['I get up at six every day.', 'Saya bangun jam enam setiap hari.'], ["I'm having breakfast now.", 'Saya sedang sarapan sekarang.'], ['I went to the market yesterday.', 'Saya pergi ke pasar kemarin.'], ['I can swim, but I can\'t dive.', 'Saya bisa berenang, tapi tidak bisa menyelam.'], ["I'm going to visit Bali next month.", 'Saya akan mengunjungi Bali bulan depan.']],
    practice: [
      ['Lengkapi: "She ___ to school every day."', 'goes', ['go', 'going', 'went']],
      ['Lengkapi: "Look! The baby ___."', 'is sleeping', ['sleeps', 'slept', 'sleep']],
      ['Lengkapi: "I ___ a movie last night."', 'watched', ['watch', 'am watching', 'watches']],
      ['Lengkapi: "We ___ going to travel next week."', 'are', ['is', 'am', 'do']],
      ['Kalimat yang benar adalah...', 'He can speak English.', ['He can speaks English.', 'He cans speak English.', 'He can to speak English.']],
    ],
    task: 'Tulis paragraf 8 kalimat tentang dirimu: kebiasaan, yang sedang kamu lakukan, kemarin, kemampuan, dan rencana.',
  },
];

export const beginnerListeningExtra: ExtraEnglishLesson[] = [
  {
    id: 11, title: 'Di Kelas', subtitle: 'Instruksi guru & percakapan kelas',
    intro: 'Dengarkan percakapan di kelas. Fokus pada instruksi guru seperti open, close, repeat, dan page.',
    points: ['Instruksi memakai kata kerja dasar: Open your books.', '"Page twenty" = halaman 20.', '"Can you repeat that, please?" untuk minta diulang.'],
    examples: [['Open your books to page twenty.', 'Buka bukumu halaman 20.'], ['Can you repeat that, please?', 'Bisakah diulang?'], ['Work in pairs.', 'Bekerja berpasangan.'], ['What does this word mean?', 'Apa arti kata ini?']],
    dialogue: [['Teacher', 'Good morning, class. Please open your books to page twenty.', 'Selamat pagi, anak-anak. Buka buku kalian halaman 20.'], ['Student', 'Sorry, which page?', 'Maaf, halaman berapa?'], ['Teacher', 'Page twenty. Now read the first text with your partner.', 'Halaman 20. Sekarang baca teks pertama dengan pasanganmu.'], ['Student', 'What does "library" mean?', 'Apa arti "library"?'], ['Teacher', 'It means a place with many books.', 'Artinya tempat dengan banyak buku.'], ['Teacher', "Great. Tomorrow we're going to have a short test.", 'Bagus. Besok kita akan ada tes singkat.']],
    practice: [
      ['Halaman berapa yang disebut guru?', '20', ['12', '22', '30']],
      ['Dengan siapa siswa membaca teks?', 'Pasangannya', ['Guru', 'Sendiri', 'Seluruh kelas']],
      ['Apa arti "library" menurut guru?', 'Tempat dengan banyak buku', ['Ruang kelas', 'Kantin', 'Taman sekolah']],
      ['Apa yang akan terjadi besok?', 'Tes singkat', ['Libur', 'Karyawisata', 'Upacara']],
      ['"Can you repeat that, please?" dipakai untuk...', 'meminta diulang', ['meminta izin keluar', 'meminta buku', 'menjawab pertanyaan']],
    ],
    task: 'Dengarkan skrip 2 kali tanpa teks, lalu tulis 3 instruksi guru yang kamu dengar.',
  },
  {
    id: 12, title: 'Di Restoran', subtitle: 'Memesan dan membayar',
    intro: 'Dengarkan pelayan dan pelanggan. Tangkap pesanan, minuman, dan total harga.',
    points: ['"Are you ready to order?" = sudah siap memesan?', '"I\'d like..." = saya mau...', '"Can I have the bill, please?" = minta tagihan.'],
    examples: [["I'd like the chicken soup, please.", 'Saya mau sup ayam.'], ['Anything to drink?', 'Mau minum apa?'], ['Can I have the bill, please?', 'Minta tagihannya.'], ["That's twelve dollars.", 'Totalnya dua belas dolar.']],
    dialogue: [['Waiter', 'Good evening. Are you ready to order?', 'Selamat malam. Sudah siap memesan?'], ['Customer', "Yes. I'd like the fried rice, please.", 'Ya. Saya mau nasi goreng.'], ['Waiter', 'Anything to drink?', 'Mau minum apa?'], ['Customer', 'An orange juice, please. No ice.', 'Jus jeruk, tanpa es.'], ['Customer', 'Can I have the bill, please?', 'Minta tagihannya.'], ['Waiter', "Sure. That's twelve dollars.", 'Tentu. Totalnya dua belas dolar.']],
    practice: [
      ['Apa makanan yang dipesan?', 'Nasi goreng', ['Sup ayam', 'Mi goreng', 'Pizza']],
      ['Minuman apa yang dipesan?', 'Jus jeruk tanpa es', ['Teh manis', 'Kopi hitam', 'Air putih dengan es']],
      ['Berapa totalnya?', '12 dolar', ['20 dolar', '2 dolar', '15 dolar']],
      ['"Are you ready to order?" diucapkan oleh...', 'pelayan', ['pelanggan', 'koki', 'kasir bank']],
      ['Kalimat untuk meminta tagihan adalah...', 'Can I have the bill, please?', ['Can I have the menu?', 'Is it spicy?', 'Where is the toilet?']],
    ],
    task: 'Dengarkan lalu peragakan dialog ini dengan menukar makanan dan minuman sesuai seleramu.',
  },
  {
    id: 13, title: 'Di Toko Baju', subtitle: 'Ukuran, warna, dan mencoba',
    intro: 'Dengarkan percakapan di toko pakaian. Fokus pada ukuran (size), warna, dan harga.',
    points: ['"What size are you?" = ukuranmu berapa?', '"Can I try it on?" = boleh saya coba?', '"It\'s too small/big." = terlalu kecil/besar.'],
    examples: [['Can I try this on?', 'Boleh saya coba ini?'], ['What size are you? — Medium.', 'Ukuranmu berapa? — Medium.'], ["It's too small.", 'Terlalu kecil.'], ['Do you have it in blue?', 'Ada yang warna biru?']],
    dialogue: [['Assistant', 'Hello. Can I help you?', 'Halo. Bisa saya bantu?'], ['Customer', "Yes, I'm looking for a T-shirt.", 'Ya, saya mencari kaos.'], ['Assistant', 'What size are you?', 'Ukuranmu berapa?'], ['Customer', 'Medium. Do you have this one in blue?', 'Medium. Yang ini ada warna biru?'], ['Assistant', 'Yes, here you are. The fitting room is over there.', 'Ada, ini dia. Ruang ganti di sebelah sana.'], ['Customer', "It's perfect. How much is it? — It's fifteen dollars.", 'Pas sekali. Berapa harganya? — Lima belas dolar.']],
    practice: [
      ['Apa yang dicari pelanggan?', 'Kaos', ['Celana', 'Sepatu', 'Jaket']],
      ['Ukuran pelanggan adalah...', 'Medium', ['Small', 'Large', 'Extra large']],
      ['Warna apa yang diminta?', 'Biru', ['Merah', 'Hitam', 'Putih']],
      ['Berapa harganya?', '15 dolar', ['50 dolar', '5 dolar', '13 dolar']],
      ['"Fitting room" artinya...', 'ruang ganti', ['kasir', 'gudang', 'pintu keluar']],
    ],
    task: 'Buat dialog baru di toko sepatu dengan ukuran dan warna berbeda, lalu baca keras-keras.',
  },
  {
    id: 14, title: 'Di Dokter', subtitle: 'Keluhan sederhana',
    intro: 'Dengarkan pasien menjelaskan keluhan. Tangkap gejala, sudah berapa lama, dan saran dokter.',
    points: ['"What\'s the matter?" = ada keluhan apa?', '"I have a headache / a fever / a cough."', '"Since yesterday" = sejak kemarin.'],
    examples: [["What's the matter?", 'Ada keluhan apa?'], ['I have a headache and a fever.', 'Saya sakit kepala dan demam.'], ['Since Monday.', 'Sejak hari Senin.'], ['Drink a lot of water and rest.', 'Minum banyak air dan istirahat.']],
    dialogue: [['Doctor', "Hello, what's the matter?", 'Halo, ada keluhan apa?'], ['Patient', 'I have a sore throat and a cough.', 'Tenggorokan saya sakit dan saya batuk.'], ['Doctor', 'How long have you had it?', 'Sudah berapa lama?'], ['Patient', 'Since Saturday.', 'Sejak hari Sabtu.'], ['Doctor', 'Take this medicine three times a day, after meals.', 'Minum obat ini tiga kali sehari, sesudah makan.'], ['Doctor', "Drink warm water and don't go to work for two days.", 'Minum air hangat dan jangan bekerja selama dua hari.']],
    practice: [
      ['Apa keluhan pasien?', 'Sakit tenggorokan dan batuk', ['Sakit perut', 'Sakit gigi', 'Patah kaki']],
      ['Sejak kapan pasien sakit?', 'Sabtu', ['Senin', 'Kemarin', 'Seminggu lalu']],
      ['Berapa kali obat diminum?', 'Tiga kali sehari', ['Sekali sehari', 'Dua kali sehari', 'Setiap jam']],
      ['Berapa hari pasien tidak boleh bekerja?', 'Dua hari', ['Satu hari', 'Tiga hari', 'Seminggu']],
      ['"What\'s the matter?" artinya...', 'Ada keluhan apa?', ['Jam berapa?', 'Siapa namamu?', 'Berapa harganya?']],
    ],
    task: 'Dengarkan lalu tulis ulang saran dokter dalam 3 kalimat bahasa Inggris.',
  },
  {
    id: 15, title: 'Hobi & Akhir Pekan', subtitle: 'What do you do on weekends?',
    intro: 'Dengarkan dua teman membicarakan hobi. Tangkap kegiatan, frekuensi, dan tempat.',
    points: ['"What do you do on weekends?"', 'Frekuensi: always, usually, sometimes, never.', '"I love / I enjoy + V-ing": I enjoy cycling.'],
    examples: [['What do you do on weekends?', 'Apa yang kamu lakukan di akhir pekan?'], ['I usually go cycling.', 'Saya biasanya bersepeda.'], ['I enjoy cooking.', 'Saya senang memasak.'], ['I never watch horror movies.', 'Saya tidak pernah menonton film horor.']],
    dialogue: [['Rina', 'What do you usually do on weekends, Dan?', 'Apa yang biasanya kamu lakukan di akhir pekan, Dan?'], ['Dan', 'I usually play badminton on Saturday morning.', 'Biasanya saya main bulu tangkis Sabtu pagi.'], ['Rina', 'Where do you play?', 'Main di mana?'], ['Dan', 'At the sports center near my house. What about you?', 'Di pusat olahraga dekat rumah. Kamu?'], ['Rina', 'I love painting. I sometimes sell my pictures online.', 'Saya suka melukis. Kadang saya jual lukisan saya secara daring.'], ['Dan', "Wow! Can you show me? — Sure, I'll send you some photos.", 'Wah! Boleh lihat? — Tentu, nanti saya kirim fotonya.']],
    practice: [
      ['Apa hobi Dan?', 'Bulu tangkis', ['Melukis', 'Berenang', 'Memasak']],
      ['Kapan Dan bermain?', 'Sabtu pagi', ['Minggu sore', 'Setiap malam', 'Jumat siang']],
      ['Di mana Dan bermain?', 'Pusat olahraga dekat rumah', ['Sekolah', 'Taman kota', 'Kantor']],
      ['Apa hobi Rina?', 'Melukis', ['Menari', 'Membaca', 'Bersepeda']],
      ['Apa yang akan Rina kirim?', 'Foto lukisan', ['Uang', 'Buku', 'Tiket']],
    ],
    task: 'Rekam dirimu menjawab: "What do you do on weekends?" dengan 4 kalimat.',
  },
  {
    id: 16, title: 'Membuat Janji', subtitle: 'Hari, jam, dan tempat bertemu',
    intro: 'Dengarkan telepon untuk membuat janji. Catat hari, jam, dan tempat.',
    points: ['"Are you free on Friday?" = kamu kosong hari Jumat?', '"Let\'s meet at..." = ayo bertemu di/jam...', '"See you then!" = sampai jumpa nanti.'],
    examples: [['Are you free on Friday?', 'Kamu kosong hari Jumat?'], ["Let's meet at the café.", 'Ayo bertemu di kafe.'], ['What time? — At half past four.', 'Jam berapa? — Jam setengah lima.'], ['See you then!', 'Sampai jumpa nanti!']],
    dialogue: [['Maya', 'Hi Leo! Are you free on Thursday?', 'Hai Leo! Kamu kosong hari Kamis?'], ['Leo', "Sorry, I have a class on Thursday. What about Friday?", 'Maaf, Kamis saya ada kelas. Bagaimana kalau Jumat?'], ['Maya', "Friday is good. Let's meet at the bookshop.", 'Jumat bisa. Ayo bertemu di toko buku.'], ['Leo', 'What time?', 'Jam berapa?'], ['Maya', 'At half past four.', 'Jam setengah lima.'], ['Leo', 'Great. See you then!', 'Oke. Sampai jumpa!']],
    practice: [
      ['Mengapa Leo tidak bisa hari Kamis?', 'Ada kelas', ['Sakit', 'Bekerja', 'Pergi ke luar kota']],
      ['Hari apa mereka bertemu?', 'Jumat', ['Kamis', 'Sabtu', 'Senin']],
      ['Di mana mereka bertemu?', 'Toko buku', ['Kafe', 'Stasiun', 'Perpustakaan']],
      ['Jam berapa mereka bertemu?', '16.30', ['14.30', '16.00', '17.30']],
      ['"Half past four" artinya...', 'setengah lima (16.30)', ['empat lewat seperempat', 'jam empat tepat', 'setengah empat']],
    ],
    task: 'Buat janji dengan temanmu lewat pesan suara (30 detik) yang menyebut hari, jam, dan tempat.',
  },
  {
    id: 17, title: 'Pengumuman di Stasiun', subtitle: 'Platform, tujuan, dan keterlambatan',
    intro: 'Pengumuman stasiun cepat dan formal. Fokus pada angka platform, tujuan, dan waktu.',
    points: ['"Platform three" = peron 3.', '"The train to..." = kereta tujuan...', '"is delayed by ten minutes" = terlambat 10 menit.'],
    examples: [['The train to London leaves from platform three.', 'Kereta tujuan London berangkat dari peron 3.'], ['The 9:15 train is delayed.', 'Kereta 09.15 terlambat.'], ['Please stand behind the yellow line.', 'Harap berdiri di belakang garis kuning.'], ['This train is cancelled.', 'Kereta ini dibatalkan.']],
    dialogue: [['Announcer', 'Attention, please.', 'Mohon perhatian.'], ['Announcer', 'The ten fifteen train to Bandung will leave from platform four.', 'Kereta pukul 10.15 tujuan Bandung akan berangkat dari peron 4.'], ['Announcer', 'This train is delayed by twenty minutes.', 'Kereta ini terlambat 20 menit.'], ['Announcer', 'The new departure time is ten thirty-five.', 'Waktu keberangkatan baru pukul 10.35.'], ['Announcer', 'Please stand behind the yellow line.', 'Harap berdiri di belakang garis kuning.'], ['Announcer', 'We are sorry for the delay.', 'Kami mohon maaf atas keterlambatan.']],
    practice: [
      ['Kereta menuju ke mana?', 'Bandung', ['Jakarta', 'Surabaya', 'Bogor']],
      ['Dari peron berapa kereta berangkat?', '4', ['2', '3', '10']],
      ['Berapa lama keterlambatannya?', '20 menit', ['10 menit', '15 menit', '35 menit']],
      ['Jam berapa keberangkatan baru?', '10.35', ['10.15', '10.20', '11.35']],
      ['Penumpang diminta berdiri di belakang...', 'garis kuning', ['pintu', 'kursi', 'papan jadwal']],
    ],
    task: 'Tulis pengumuman stasiunmu sendiri (4 kalimat) dengan tujuan, peron, dan waktu.',
  },
  {
    id: 18, title: 'Check-in Hotel', subtitle: 'Reservasi, kamar, dan sarapan',
    intro: 'Dengarkan tamu melakukan check-in. Tangkap nama, jumlah malam, nomor kamar, dan jam sarapan.',
    points: ['"I have a reservation" = saya sudah reservasi.', '"for three nights" = untuk tiga malam.', '"Breakfast is from seven to ten." = sarapan jam 7 sampai 10.'],
    examples: [['I have a reservation under the name Putri.', 'Saya ada reservasi atas nama Putri.'], ['For two nights.', 'Untuk dua malam.'], ['Your room is on the fifth floor.', 'Kamarmu di lantai lima.'], ['Is breakfast included?', 'Apakah termasuk sarapan?']],
    dialogue: [['Receptionist', 'Good afternoon. Welcome to Sunrise Hotel.', 'Selamat siang. Selamat datang di Hotel Sunrise.'], ['Guest', 'Hi, I have a reservation under the name Adi Pratama.', 'Hai, saya ada reservasi atas nama Adi Pratama.'], ['Receptionist', 'Yes, a single room for three nights. Can I see your passport?', 'Ya, kamar single untuk tiga malam. Boleh lihat paspor Anda?'], ['Guest', 'Here you are. Is breakfast included?', 'Ini. Apakah termasuk sarapan?'], ['Receptionist', 'Yes, breakfast is from seven to ten in the restaurant.', 'Ya, sarapan dari jam tujuh sampai sepuluh di restoran.'], ['Receptionist', 'Your room is 512, on the fifth floor. Enjoy your stay!', 'Kamar Anda 512 di lantai lima. Selamat menginap!']],
    practice: [
      ['Berapa malam tamu menginap?', 'Tiga malam', ['Dua malam', 'Satu malam', 'Lima malam']],
      ['Dokumen apa yang diminta?', 'Paspor', ['KTP', 'Tiket pesawat', 'Kartu kredit']],
      ['Sarapan sampai jam berapa?', '10', ['9', '11', '7']],
      ['Nomor kamar tamu adalah...', '512', ['215', '502', '520']],
      ['Kamar ada di lantai...', 'lima', ['dua', 'satu', 'dua belas']],
    ],
    task: 'Peragakan check-in dengan namamu sendiri, jumlah malam, dan pertanyaan tentang Wi-Fi.',
  },
  {
    id: 19, title: 'Cerita Kemarin', subtitle: 'Menangkap urutan kejadian (past)',
    intro: 'Dengarkan cerita pendek tentang hari kemarin. Perhatikan kata urutan: first, then, after that, finally.',
    points: ['Kata kerja lampau: went, had, saw, bought.', 'Urutan: first → then → after that → finally.', 'Waktu: in the morning, at noon, in the evening.'],
    examples: [['First, I had breakfast.', 'Pertama, saya sarapan.'], ['Then I went to the park.', 'Lalu saya pergi ke taman.'], ['After that, I met my friend.', 'Setelah itu, saya bertemu teman.'], ['Finally, I went home.', 'Akhirnya, saya pulang.']],
    dialogue: [['Narrator', 'Yesterday was Sunday, so I got up late.', 'Kemarin hari Minggu, jadi saya bangun siang.'], ['Narrator', 'First, I had pancakes for breakfast.', 'Pertama, saya sarapan panekuk.'], ['Narrator', 'Then I went to the beach with my cousin.', 'Lalu saya pergi ke pantai bersama sepupu.'], ['Narrator', 'We swam and took a lot of photos.', 'Kami berenang dan mengambil banyak foto.'], ['Narrator', 'After that, we ate grilled fish at a small restaurant.', 'Setelah itu, kami makan ikan bakar di restoran kecil.'], ['Narrator', 'Finally, I went home and slept early.', 'Akhirnya saya pulang dan tidur cepat.']],
    practice: [
      ['Mengapa penulis bangun siang?', 'Karena hari Minggu', ['Karena sakit', 'Karena lelah bekerja', 'Karena hujan']],
      ['Apa sarapannya?', 'Panekuk', ['Nasi goreng', 'Roti bakar', 'Bubur']],
      ['Ke mana dia pergi bersama sepupu?', 'Pantai', ['Gunung', 'Mal', 'Museum']],
      ['Apa yang mereka makan?', 'Ikan bakar', ['Pizza', 'Sate', 'Mi ayam']],
      ['Apa yang terakhir dia lakukan?', 'Pulang dan tidur cepat', ['Menonton film', 'Berenang lagi', 'Belajar']],
    ],
    task: 'Ceritakan harimu kemarin dalam 6 kalimat memakai first, then, after that, finally.',
  },
  {
    id: 20, title: 'Ujian Menyimak A1', subtitle: 'Gabungan semua situasi',
    intro: 'Tes akhir menyimak A1: pesan suara berisi informasi campuran (waktu, tempat, angka, dan permintaan).',
    points: ['Dengarkan sekali untuk ide umum.', 'Dengarkan lagi untuk angka dan nama.', 'Jawab, lalu cek dengan teks.'],
    examples: [['Please call me back.', 'Tolong telepon saya balik.'], ['My number is 0812 345 678.', 'Nomor saya 0812 345 678.'], ["Don't forget to bring your ID.", 'Jangan lupa bawa kartu identitas.'], ['The meeting is at the library.', 'Pertemuannya di perpustakaan.']],
    dialogue: [['Voicemail', 'Hi Sam, this is Nina from the English club.', 'Hai Sam, ini Nina dari klub bahasa Inggris.'], ['Voicemail', "Our next meeting is on Wednesday at seven p.m.", 'Pertemuan berikutnya hari Rabu jam 7 malam.'], ['Voicemail', "It's not at the café this time. It's at the city library, room B.", 'Kali ini bukan di kafe, tapi di perpustakaan kota, ruang B.'], ['Voicemail', 'Please bring your notebook and two new words to share.', 'Tolong bawa buku catatan dan dua kata baru untuk dibagikan.'], ['Voicemail', 'If you have questions, call me at 0812 777 305.', 'Kalau ada pertanyaan, telepon saya di 0812 777 305.'], ['Voicemail', 'See you on Wednesday. Bye!', 'Sampai jumpa hari Rabu!']],
    practice: [
      ['Siapa yang meninggalkan pesan?', 'Nina', ['Sam', 'Guru', 'Petugas perpustakaan']],
      ['Kapan pertemuan berikutnya?', 'Rabu jam 7 malam', ['Rabu jam 7 pagi', 'Kamis jam 7 malam', 'Senin jam 5 sore']],
      ['Di mana pertemuannya?', 'Perpustakaan kota, ruang B', ['Kafe', 'Sekolah', 'Rumah Nina']],
      ['Apa yang harus dibawa?', 'Buku catatan dan dua kata baru', ['Makanan ringan', 'Kamus tebal', 'Uang iuran']],
      ['Nomor telepon Nina berakhir dengan...', '305', ['777', '350', '812']],
    ],
    task: 'Tinggalkan pesan suara 30–40 detik untuk teman berisi hari, jam, tempat, dan barang yang harus dibawa.',
  },
];
