import type { ExtraEnglishLesson } from './types';

export const elementaryListeningExtra: ExtraEnglishLesson[] = [
  {
    id: 11, title: 'Wawancara Kerja Sederhana', subtitle: 'Pengalaman dan ketersediaan',
    intro: 'Dengarkan wawancara kerja paruh waktu. Tangkap pengalaman, keterampilan, dan jadwal kerja.',
    points: ['"Have you ever worked...?" menanyakan pengalaman.', '"When can you start?" = kapan bisa mulai?', 'Tangkap angka: jam kerja dan gaji.'],
    examples: [['Have you ever worked in a shop?', 'Pernahkah kamu bekerja di toko?'], ['I worked at a café for six months.', 'Saya bekerja di kafe selama enam bulan.'], ['When can you start?', 'Kapan bisa mulai?'], ['The pay is ten dollars an hour.', 'Gajinya sepuluh dolar per jam.']],
    dialogue: [['Manager', 'Thanks for coming. Have you ever worked in a bookshop?', 'Terima kasih sudah datang. Pernah bekerja di toko buku?'], ['Applicant', 'No, but I worked at a supermarket for a year.', 'Belum, tapi saya bekerja di supermarket selama setahun.'], ['Manager', 'Good. We need someone on weekends, from nine to three.', 'Bagus. Kami butuh orang untuk akhir pekan, jam sembilan sampai tiga.'], ['Applicant', "That's fine. I have classes on weekdays.", 'Tidak masalah. Saya kuliah di hari kerja.'], ['Manager', 'The pay is eleven dollars an hour. When can you start?', 'Gajinya sebelas dolar per jam. Kapan bisa mulai?'], ['Applicant', 'Next Saturday, if that is OK.', 'Sabtu depan, kalau boleh.']],
    practice: [
      ['Di mana pelamar pernah bekerja?', 'Supermarket', ['Toko buku', 'Kafe', 'Bank']],
      ['Berapa lama pengalamannya?', 'Satu tahun', ['Enam bulan', 'Dua tahun', 'Tiga bulan']],
      ['Jam kerja yang ditawarkan adalah...', '09.00–15.00 akhir pekan', ['09.00–15.00 hari kerja', '15.00–21.00 setiap hari', 'Hanya Minggu pagi']],
      ['Berapa gajinya per jam?', '11 dolar', ['10 dolar', '7 dolar', '15 dolar']],
      ['Kapan pelamar bisa mulai?', 'Sabtu depan', ['Besok', 'Bulan depan', 'Senin depan']],
    ],
    task: 'Dengarkan lalu tulis ringkasan 4 kalimat tentang pekerjaan yang ditawarkan.',
  },
  {
    id: 12, title: 'Laporan Cuaca', subtitle: 'Prakiraan per wilayah',
    intro: 'Dengarkan prakiraan cuaca radio. Tangkap wilayah, kondisi, suhu, dan saran.',
    points: ['"In the north / south" menunjukkan wilayah.', '"Highs of 30 degrees" = suhu tertinggi 30°.', '"Showers" = hujan ringan singkat.'],
    examples: [['There will be showers in the afternoon.', 'Akan ada hujan ringan di sore hari.'], ['Temperatures will reach 32 degrees.', 'Suhu akan mencapai 32 derajat.'], ['Strong winds are expected in the south.', 'Angin kencang diperkirakan di selatan.'], ["Don't forget your umbrella.", 'Jangan lupa payungmu.']],
    dialogue: [['Presenter', "Good morning, here's the weather for Friday.", 'Selamat pagi, ini cuaca untuk hari Jumat.'], ['Presenter', "In the north, it'll be sunny and hot, with highs of thirty-four degrees.", 'Di utara cerah dan panas, suhu tertinggi 34 derajat.'], ['Presenter', 'In the central areas, expect clouds in the morning and showers after lunch.', 'Di wilayah tengah, berawan pagi hari dan hujan ringan setelah makan siang.'], ['Presenter', 'The south will be windy, so be careful at the beach.', 'Selatan berangin, jadi hati-hati di pantai.'], ['Presenter', 'On Saturday, rain will spread across the whole country.', 'Hari Sabtu, hujan akan meluas ke seluruh negeri.'], ['Presenter', "So if you're going out, take an umbrella!", 'Jadi kalau keluar, bawa payung!']],
    practice: [
      ['Bagaimana cuaca di utara?', 'Cerah dan panas', ['Hujan', 'Berangin', 'Berawan sepanjang hari']],
      ['Suhu tertinggi di utara adalah...', '34°', ['30°', '24°', '43°']],
      ['Kapan hujan ringan di wilayah tengah?', 'Setelah makan siang', ['Pagi hari', 'Malam hari', 'Tidak ada hujan']],
      ['Mengapa orang harus hati-hati di pantai selatan?', 'Berangin', ['Terlalu panas', 'Ada badai petir', 'Air laut tinggi']],
      ['Bagaimana cuaca hari Sabtu?', 'Hujan di seluruh negeri', ['Cerah di mana-mana', 'Bersalju', 'Hanya berangin']],
    ],
    task: 'Rekam prakiraan cuaca 30 detik untuk tiga kota di Indonesia.',
  },
  {
    id: 13, title: 'Pesan Suara', subtitle: 'Voicemail dari kantor',
    intro: 'Pesan suara sering cepat. Catat siapa penelepon, alasan, dan tindakan yang diminta.',
    points: ['"I\'m calling about..." = saya menelepon soal...', '"Could you call me back?" = tolong telepon balik.', 'Catat nomor dan batas waktu.'],
    examples: [["I'm calling about your order.", 'Saya menelepon soal pesananmu.'], ['Could you call me back before five?', 'Bisa telepon balik sebelum jam lima?'], ['My extension is 204.', 'Nomor ekstensi saya 204.'], ['Sorry for the inconvenience.', 'Mohon maaf atas ketidaknyamanannya.']],
    dialogue: [['Voicemail', 'Hello, this is Karen from City Electronics.', 'Halo, ini Karen dari City Electronics.'], ['Voicemail', "I'm calling about the laptop you ordered last week.", 'Saya menelepon soal laptop yang Anda pesan minggu lalu.'], ['Voicemail', "Unfortunately, the silver model isn't available until next month.", 'Sayangnya, model perak baru tersedia bulan depan.'], ['Voicemail', 'We have the black model now, at the same price.', 'Kami punya model hitam sekarang, dengan harga yang sama.'], ['Voicemail', 'Could you call me back before Thursday? My number is 555 0192.', 'Bisa telepon balik sebelum Kamis? Nomor saya 555 0192.'], ['Voicemail', 'Sorry for the inconvenience. Goodbye.', 'Mohon maaf atas ketidaknyamanannya. Sampai jumpa.']],
    practice: [
      ['Dari mana Karen menelepon?', 'Toko elektronik', ['Bank', 'Rumah sakit', 'Kantor pos']],
      ['Apa masalahnya?', 'Laptop warna perak belum tersedia', ['Laptop rusak', 'Pembayaran gagal', 'Alamat salah']],
      ['Apa alternatif yang ditawarkan?', 'Model hitam dengan harga sama', ['Diskon 50%', 'Laptop bekas', 'Uang kembali']],
      ['Kapan harus menelepon balik?', 'Sebelum Kamis', ['Sebelum Senin', 'Hari ini', 'Bulan depan']],
      ['Nomor Karen berakhir dengan...', '0192', ['0912', '555', '2019']],
    ],
    task: 'Tulis balasan pesan (atau rekam) untuk Karen: pilih model hitam atau menunggu.',
  },
  {
    id: 14, title: 'Di Bandara', subtitle: 'Pengumuman dan check-in',
    intro: 'Dengarkan percakapan check-in dan pengumuman gerbang. Tangkap gate, waktu boarding, dan bagasi.',
    points: ['"Window or aisle seat?" = kursi jendela atau lorong?', '"Boarding starts at..." = boarding mulai jam...', '"Gate 12" = gerbang 12.'],
    examples: [['Can I see your passport, please?', 'Boleh lihat paspornya?'], ['Window or aisle seat?', 'Kursi jendela atau lorong?'], ['Your bag is two kilos overweight.', 'Tasmu kelebihan dua kilo.'], ['Boarding starts at 9:40 at gate 12.', 'Boarding mulai 09.40 di gerbang 12.']],
    dialogue: [['Agent', 'Good morning. Where are you flying to today?', 'Selamat pagi. Terbang ke mana hari ini?'], ['Passenger', 'To Singapore.', 'Ke Singapura.'], ['Agent', 'Window or aisle seat?', 'Kursi jendela atau lorong?'], ['Passenger', 'Aisle, please. And I have one suitcase.', 'Lorong. Dan saya punya satu koper.'], ['Agent', "It's twenty-three kilos. That's fine. Boarding starts at ten fifteen at gate eight.", 'Beratnya 23 kilo. Tidak masalah. Boarding mulai 10.15 di gerbang 8.'], ['Announcement', 'Flight SQ 961 to Singapore is now boarding at gate eight.', 'Penerbangan SQ 961 ke Singapura sekarang boarding di gerbang 8.']],
    practice: [
      ['Ke mana penumpang terbang?', 'Singapura', ['Bangkok', 'Tokyo', 'Kuala Lumpur']],
      ['Kursi apa yang dipilih?', 'Lorong', ['Jendela', 'Tengah', 'Darurat']],
      ['Berapa berat koper?', '23 kg', ['32 kg', '20 kg', '25 kg']],
      ['Boarding di gerbang berapa?', '8', ['18', '10', '6']],
      ['Nomor penerbangannya adalah...', 'SQ 961', ['SQ 196', 'SQ 916', 'SA 961']],
    ],
    task: 'Peragakan check-in dengan tujuan, pilihan kursi, dan pertanyaan tentang bagasi kabin.',
  },
  {
    id: 15, title: 'Tur Kota', subtitle: 'Pemandu wisata menjelaskan tempat',
    intro: 'Dengarkan pemandu wisata. Tangkap nama tempat, fakta sejarah, dan waktu kumpul.',
    points: ['"On your left/right" = di kiri/kanan Anda.', '"It was built in..." = dibangun pada tahun...', '"Meet back here at..." = kembali berkumpul jam...'],
    examples: [['On your left is the old post office.', 'Di kiri Anda adalah kantor pos lama.'], ['It was built in 1920.', 'Dibangun tahun 1920.'], ['You have forty-five minutes of free time.', 'Anda punya waktu bebas 45 menit.'], ['Please meet back here at noon.', 'Silakan berkumpul lagi di sini jam 12.']],
    dialogue: [['Guide', 'Welcome to the old town tour!', 'Selamat datang di tur kota tua!'], ['Guide', 'On your right is the city museum. It was built in eighteen ninety.', 'Di kanan Anda museum kota, dibangun tahun 1890.'], ['Guide', 'It used to be the town hall.', 'Dulu gedung ini balai kota.'], ['Guide', 'Now we are walking to the flower market. It opens at six every morning.', 'Sekarang kita berjalan ke pasar bunga. Pasar ini buka jam enam setiap pagi.'], ['Guide', 'You have forty minutes of free time to shop.', 'Anda punya waktu bebas 40 menit untuk berbelanja.'], ['Guide', 'Please meet back at the fountain at eleven thirty.', 'Silakan kumpul lagi di air mancur jam 11.30.']],
    practice: [
      ['Kapan museum kota dibangun?', '1890', ['1980', '1819', '1920']],
      ['Dulu museum itu adalah...', 'Balai kota', ['Sekolah', 'Stasiun', 'Rumah sakit']],
      ['Jam berapa pasar bunga buka?', '06.00', ['07.00', '09.00', '05.00']],
      ['Berapa lama waktu bebas?', '40 menit', ['14 menit', '30 menit', '1 jam']],
      ['Di mana peserta berkumpul lagi?', 'Air mancur', ['Museum', 'Pintu masuk pasar', 'Bus tur']],
    ],
    task: 'Buat naskah tur 1 menit tentang tempat bersejarah di kotamu dan rekam.',
  },
  {
    id: 16, title: 'Video Memasak', subtitle: 'Instruksi berurutan',
    intro: 'Dengarkan instruksi memasak. Tangkap bahan, jumlah, urutan, dan waktu.',
    points: ['Kata urutan: first, next, after that, finally.', 'Kata kerja dapur: chop, stir, fry, boil.', 'Waktu: for five minutes, until golden.'],
    examples: [['First, chop the onions.', 'Pertama, cincang bawang.'], ['Stir for two minutes.', 'Aduk selama dua menit.'], ['Fry until golden.', 'Goreng sampai keemasan.'], ['Add a pinch of salt.', 'Tambahkan sejumput garam.']],
    dialogue: [['Chef', "Today we're making simple fried noodles.", 'Hari ini kita membuat mi goreng sederhana.'], ['Chef', 'First, boil the noodles for three minutes and drain them.', 'Pertama, rebus mi tiga menit lalu tiriskan.'], ['Chef', 'Next, fry two cloves of garlic in a little oil.', 'Selanjutnya, tumis dua siung bawang putih dengan sedikit minyak.'], ['Chef', 'Add the vegetables and one egg. Stir quickly.', 'Masukkan sayuran dan satu telur. Aduk cepat.'], ['Chef', 'After that, add the noodles and two spoons of soy sauce.', 'Setelah itu masukkan mi dan dua sendok kecap.'], ['Chef', 'Finally, cook for one more minute and serve hot.', 'Terakhir, masak satu menit lagi dan sajikan panas.']],
    practice: [
      ['Berapa lama mi direbus?', '3 menit', ['1 menit', '5 menit', '10 menit']],
      ['Berapa siung bawang putih?', '2', ['1', '3', '4']],
      ['Berapa telur yang dipakai?', '1', ['2', '3', 'Tidak ada']],
      ['Berapa sendok kecap?', '2', ['1', '3', '4']],
      ['Apa langkah terakhir?', 'Masak satu menit lagi lalu sajikan', ['Merebus mi', 'Menumis bawang', 'Menambahkan telur']],
    ],
    task: 'Rekam instruksi memasak menu favoritmu (5 langkah) memakai kata urutan.',
  },
  {
    id: 17, title: 'Pengumuman Sekolah', subtitle: 'Informasi acara dan perubahan jadwal',
    intro: 'Dengarkan pengumuman kepala sekolah. Tangkap acara, tanggal, perubahan, dan hal yang harus dibawa.',
    points: ['"has been moved to" = dipindah ke.', '"is cancelled" = dibatalkan.', '"Students must bring..." = siswa wajib membawa...'],
    examples: [['The science fair has been moved to Friday.', 'Pameran sains dipindah ke Jumat.'], ["Tomorrow's football match is cancelled.", 'Pertandingan sepak bola besok dibatalkan.'], ['Students must bring their ID cards.', 'Siswa wajib membawa kartu pelajar.'], ['The library will close early.', 'Perpustakaan akan tutup lebih awal.']],
    dialogue: [['Principal', 'Good morning, students. I have three announcements.', 'Selamat pagi, anak-anak. Ada tiga pengumuman.'], ['Principal', "First, the school trip to the science museum has been moved to next Wednesday.", 'Pertama, karyawisata ke museum sains dipindah ke Rabu depan.'], ['Principal', 'Please bring a packed lunch and fifteen thousand rupiah for the ticket.', 'Bawa bekal makan siang dan lima belas ribu rupiah untuk tiket.'], ['Principal', "Second, this afternoon's basketball practice is cancelled because of the rain.", 'Kedua, latihan basket sore ini dibatalkan karena hujan.'], ['Principal', 'Finally, the library will close at two p.m. on Friday.', 'Terakhir, perpustakaan tutup jam 14.00 hari Jumat.'], ['Principal', 'Have a great day!', 'Semoga hari kalian menyenangkan!']],
    practice: [
      ['Ke mana karyawisata?', 'Museum sains', ['Kebun binatang', 'Pantai', 'Pabrik']],
      ['Kapan karyawisata sekarang?', 'Rabu depan', ['Jumat ini', 'Senin depan', 'Besok']],
      ['Berapa uang tiket yang dibawa?', 'Rp15.000', ['Rp50.000', 'Rp5.000', 'Rp25.000']],
      ['Mengapa latihan basket dibatalkan?', 'Karena hujan', ['Pelatih sakit', 'Lapangan diperbaiki', 'Ada ujian']],
      ['Perpustakaan tutup jam berapa hari Jumat?', '14.00', ['12.00', '16.00', '15.00']],
    ],
    task: 'Tulis dan rekam pengumuman sekolah/kantor dengan satu perubahan jadwal dan satu pembatalan.',
  },
  {
    id: 18, title: 'Rencana Bersama Teman', subtitle: 'Menyepakati pilihan',
    intro: 'Dengarkan dua teman merencanakan akhir pekan. Tangkap pilihan, alasan menolak, dan keputusan akhir.',
    points: ['Usul: How about...? / Why don\'t we...?', 'Menolak: I\'d rather not, because...', 'Kesepakatan: OK, let\'s do that.'],
    examples: [['How about going to the cinema?', 'Bagaimana kalau ke bioskop?'], ["I'd rather not. It's too expensive.", 'Lebih baik jangan. Terlalu mahal.'], ["Why don't we have a picnic?", 'Kenapa kita tidak piknik saja?'], ["OK, let's do that.", 'Oke, ayo lakukan itu.']],
    dialogue: [['Ana', 'What shall we do on Saturday?', 'Kita ngapain hari Sabtu?'], ['Ben', 'How about going to the water park?', 'Bagaimana kalau ke taman air?'], ['Ana', "I'd rather not. It's always crowded on weekends.", 'Mending jangan. Selalu ramai di akhir pekan.'], ['Ben', "Why don't we go cycling around the lake, then?", 'Kalau begitu kenapa tidak bersepeda keliling danau?'], ['Ana', "Good idea! We can rent bikes there. It's cheap.", 'Ide bagus! Kita bisa sewa sepeda di sana. Murah.'], ['Ben', "Great. Let's meet at eight, before it gets hot.", 'Oke. Ketemu jam delapan, sebelum panas.']],
    practice: [
      ['Apa usul pertama Ben?', 'Taman air', ['Bersepeda', 'Bioskop', 'Pasar malam']],
      ['Mengapa Ana menolak usul pertama?', 'Selalu ramai di akhir pekan', ['Terlalu mahal', 'Jauh', 'Ana tidak bisa berenang']],
      ['Apa keputusan akhir mereka?', 'Bersepeda keliling danau', ['Piknik di taman', 'Menonton film', 'Tinggal di rumah']],
      ['Mengapa mereka bertemu jam delapan?', 'Sebelum panas', ['Sebelum hujan', 'Karena sepeda buka jam 8', 'Karena Ben kerja siang']],
      ['"I\'d rather not" artinya...', 'Lebih baik jangan', ['Saya setuju sekali', 'Saya belum tahu', 'Saya sudah pernah']],
    ],
    task: 'Rekam percakapan merencanakan kegiatan dengan 2 usul, 1 penolakan beralasan, dan 1 keputusan.',
  },
  {
    id: 19, title: 'Berita Lokal Singkat', subtitle: 'Menangkap 5W+1H',
    intro: 'Dengarkan berita singkat. Tangkap what, who, where, when, why, dan how.',
    points: ['Berita dimulai dengan inti (what happened).', 'Detail angka dan waktu sering muncul.', 'Kata pasif sering dipakai: was opened, were rescued.'],
    examples: [['A new library was opened yesterday.', 'Perpustakaan baru diresmikan kemarin.'], ['More than 200 people attended.', 'Lebih dari 200 orang hadir.'], ['The mayor said...', 'Wali kota mengatakan...'], ['It will be open every day except Monday.', 'Buka setiap hari kecuali Senin.']],
    dialogue: [['Reporter', 'Good evening. A new public park opened in Riverside yesterday.', 'Selamat malam. Taman umum baru dibuka di Riverside kemarin.'], ['Reporter', 'The park has a playground, a running track, and a small lake.', 'Taman ini punya taman bermain, lintasan lari, dan danau kecil.'], ['Reporter', 'More than five hundred families visited on the first day.', 'Lebih dari lima ratus keluarga berkunjung di hari pertama.'], ['Reporter', 'The mayor said the park will help people exercise and relax.', 'Wali kota mengatakan taman ini akan membantu warga berolahraga dan bersantai.'], ['Reporter', 'It is open from six a.m. to nine p.m. and entry is free.', 'Buka dari jam enam pagi sampai jam sembilan malam, masuk gratis.'], ['Reporter', 'Bicycles are not allowed on the running track.', 'Sepeda tidak diizinkan di lintasan lari.']],
    practice: [
      ['Apa beritanya?', 'Taman umum baru dibuka', ['Sekolah baru dibangun', 'Danau meluap', 'Pasar ditutup']],
      ['Berapa keluarga berkunjung di hari pertama?', 'Lebih dari 500', ['Sekitar 50', 'Tepat 150', 'Lebih dari 5.000']],
      ['Menurut wali kota, taman membantu warga...', 'berolahraga dan bersantai', ['berdagang', 'bertani', 'belajar bahasa']],
      ['Jam berapa taman tutup?', '21.00', ['18.00', '22.00', '20.00']],
      ['Apa yang dilarang di lintasan lari?', 'Sepeda', ['Anjing', 'Makanan', 'Anak-anak']],
    ],
    task: 'Tulis berita 5 kalimat tentang kejadian di lingkunganmu dengan menjawab 5W+1H.',
  },
  {
    id: 20, title: 'Ujian Menyimak A2', subtitle: 'Percakapan dan monolog campuran',
    intro: 'Tes akhir: dengarkan percakapan pemesanan tur. Jawab pertanyaan detail dan inferensi.',
    points: ['Dengarkan sekali untuk konteks.', 'Kedua kali: catat angka, tanggal, harga.', 'Inferensi: apa yang TIDAK disebut secara langsung.'],
    examples: [["I'd like to book a tour for two people.", 'Saya ingin memesan tur untuk dua orang.'], ["It's fully booked on Sunday.", 'Hari Minggu sudah penuh.'], ['The price includes lunch.', 'Harganya termasuk makan siang.'], ["We'll pick you up from your hotel.", 'Kami akan menjemput di hotelmu.']],
    dialogue: [['Customer', "Hi, I'd like to book the island tour for two people on Sunday.", 'Hai, saya ingin memesan tur pulau untuk dua orang hari Minggu.'], ['Agent', "I'm sorry, Sunday is fully booked. We have places on Saturday or Monday.", 'Maaf, Minggu penuh. Ada tempat hari Sabtu atau Senin.'], ['Customer', 'Monday is fine. How much is it?', 'Senin boleh. Berapa harganya?'], ['Agent', "It's forty-five dollars per person, including lunch and snorkeling equipment.", 'Empat puluh lima dolar per orang, termasuk makan siang dan alat snorkeling.'], ['Agent', "We'll pick you up from your hotel at seven thirty.", 'Kami akan menjemput di hotel jam 07.30.'], ['Customer', 'Perfect. Should we bring anything? — Just sunscreen and a towel.', 'Sempurna. Perlu bawa sesuatu? — Cukup tabir surya dan handuk.']],
    practice: [
      ['Mengapa pelanggan tidak bisa ikut hari Minggu?', 'Sudah penuh', ['Hujan', 'Tur dibatalkan', 'Pelanggan sibuk']],
      ['Hari apa tur akhirnya dipesan?', 'Senin', ['Sabtu', 'Minggu', 'Selasa']],
      ['Berapa total biaya untuk dua orang?', '90 dolar', ['45 dolar', '80 dolar', '100 dolar']],
      ['Apa yang termasuk dalam harga?', 'Makan siang dan alat snorkeling', ['Tabir surya dan handuk', 'Hotel', 'Tiket pesawat']],
      ['Apa yang perlu dibawa pelanggan?', 'Tabir surya dan handuk', ['Makan siang', 'Alat snorkeling', 'Paspor']],
    ],
    task: 'Rekam dialog memesan tur/tiket dengan satu kendala tanggal dan pertanyaan tentang harga.',
  },
];

export const elementaryPronunciationExtra: ExtraEnglishLesson[] = [
  {
    id: 16, title: 'Bentuk Lemah (Weak Forms)', subtitle: 'can · to · and · of',
    intro: 'Kata fungsi seperti can, to, and, of biasanya diucapkan lemah (dengan schwa /ə/) dalam kalimat.',
    points: ['can → /kən/: I can swim.', "can't tetap kuat /kɑːnt/ atau /kænt/.", 'to → /tə/, and → /ən/, of → /əv/.'],
    examples: [['I can /kən/ swim.', 'Saya bisa berenang.'], ["I can't /kɑːnt/ swim.", 'Saya tidak bisa berenang.'], ['fish and /ən/ chips', 'ikan dan kentang goreng'], ['a cup of /əv/ tea', 'secangkir teh'], ['I want to /tə/ go.', 'Saya ingin pergi.']],
    practice: [
      ['Dalam "I can swim", "can" biasanya diucapkan...', 'lemah /kən/', ['kuat /kæn/', 'tidak diucapkan', '/kɑːnt/']],
      ['Cara membedakan can dan can\'t dalam ucapan adalah...', "can't diucapkan kuat dan panjang", ['can selalu lebih keras', 'keduanya sama', 'can diucapkan dengan /t/']],
      ['"and" dalam "bread and butter" dibaca...', '/ən/', ['/ænd/ keras', '/end/', 'tidak dibaca sama sekali']],
      ['Vokal lemah yang paling umum adalah...', 'schwa /ə/', ['/iː/', '/ɔː/', '/aɪ/']],
    ],
    task: 'Rekam 6 kalimat dengan can/can\'t dan minta teman menebak mana yang positif/negatif.',
  },
  {
    id: 17, title: 'Tekanan Kata Majemuk', subtitle: 'BLACKboard vs black BOARD',
    intro: 'Kata benda majemuk biasanya ditekan pada kata pertama. Tekanan bisa membedakan arti.',
    points: ['Kata majemuk: BUS stop, TOOTHbrush, POST office.', 'Kata sifat + kata benda: a black BOARD (papan hitam biasa).', 'BLACKboard = papan tulis.'],
    examples: [['BUS stop', 'halte bus'], ['TOOTHbrush', 'sikat gigi'], ['POST office', 'kantor pos'], ['GREENhouse vs green HOUSE', 'rumah kaca vs rumah berwarna hijau'], ['I bought a new TOOTHbrush.', 'Saya membeli sikat gigi baru.']],
    practice: [
      ['Tekanan pada "bus stop" ada di...', 'bus', ['stop', 'keduanya sama', 'tidak ada']],
      ['"GREENhouse" artinya...', 'rumah kaca', ['rumah hijau', 'taman hijau', 'rumput']],
      ['Kata majemuk biasanya ditekan pada...', 'kata pertama', ['kata terakhir', 'kata tengah', 'akhiran']],
      ['Pengucapan yang benar untuk "sikat gigi" adalah...', 'TOOTHbrush', ['toothBRUSH', 'tooth-BRUSH-es', 'toOTHbrush']],
    ],
    task: 'Temukan 10 kata majemuk di rumahmu, tandai tekanannya, dan ucapkan.',
  },
  {
    id: 18, title: '/ʃ/ vs /tʃ/', subtitle: 'ship vs chip · wash vs watch',
    intro: '/ʃ/ adalah bunyi desis panjang (sh), /tʃ/ dimulai dengan hentakan lidah (ch).',
    points: ['/ʃ/: she, shop, wash — aliran udara terus.', '/tʃ/: cheap, chair, watch — t + sh.', 'Latih pasangan: share – chair, wash – watch.'],
    examples: [['ship — chip', 'kapal — keripik'], ['share — chair', 'berbagi — kursi'], ['wash — watch', 'mencuci — menonton/jam'], ['She chose a cheap shirt.', 'Dia memilih kemeja murah.']],
    practice: [
      ['Kata yang dimulai dengan /tʃ/ adalah...', 'cheese', ['sheep', 'shoe', 'sure']],
      ['Kata yang berakhir dengan /ʃ/ adalah...', 'wash', ['watch', 'match', 'rich']],
      ['/tʃ/ terdiri dari...', 't + sh', ['s + h', 'k + h', 'd + z']],
      ['Pasangan minimal yang benar adalah...', 'shop – chop', ['shop – stop', 'chop – chip', 'shoe – show']],
    ],
    task: 'Rekam "She sells cheap cherries at the shop" 3 kali dengan tempo naik.',
  },
  {
    id: 19, title: 'Angka, Harga & Tanggal', subtitle: 'Mengucapkan informasi angka',
    intro: 'Latih cara mengucapkan harga, tahun, tanggal, dan nomor telepon secara alami.',
    points: ['$4.50 → four fifty / four dollars fifty.', 'Tahun 2024 → twenty twenty-four; 1998 → nineteen ninety-eight.', 'Tanggal: the fifth of May / May fifth. Telepon: angka per digit, 0 = "oh".'],
    examples: [['$12.99 — twelve ninety-nine', '12,99 dolar'], ['1985 — nineteen eighty-five', 'tahun 1985'], ['3rd June — the third of June', '3 Juni'], ['0812 — oh eight one two', 'nomor 0812'], ['It costs three fifty.', 'Harganya 3,50.']],
    practice: [
      ['"Nineteen ninety" adalah tahun...', '1990', ['1919', '1909', '2090']],
      ['Cara umum mengucapkan $7.25 adalah...', 'seven twenty-five', ['seven point two five dollars', 'seventy-two five', 'seven two five']],
      ['Angka 0 dalam nomor telepon sering diucapkan...', 'oh', ['zero-zero', 'nothing', 'nil']],
      ['"The twenty-first of March" adalah...', '21 Maret', ['20 Maret', '1 Maret', '12 Maret']],
    ],
    task: 'Rekam dirimu membaca 5 harga, 3 tahun, 3 tanggal, dan nomor teleponmu.',
  },
  {
    id: 20, title: 'Membaca Nyaring A2', subtitle: 'Penilaian akhir pelafalan',
    intro: 'Latihan akhir: baca paragraf dengan tekanan kalimat, bentuk lemah, linking, dan intonasi.',
    points: ['Tekan kata isi (content words), lemahkan kata fungsi.', 'Sambung konsonan-vokal (linking).', 'Jeda di batas ide (chunking).'],
    examples: [['Last summer | I went to Lombok | with my best friend.', 'Musim panas lalu saya ke Lombok bersama sahabat.'], ['We stayed in a small hotel | near the beach.', 'Kami menginap di hotel kecil dekat pantai.'], ['Every morning | we had coffee | and watched the sunrise.', 'Setiap pagi kami minum kopi dan menonton matahari terbit.'], ['Would you like to go there | next year?', 'Apakah kamu mau ke sana tahun depan?']],
    practice: [
      ['Kata yang biasanya ditekan dalam kalimat adalah...', 'kata isi (kata benda, kata kerja, kata sifat)', ['artikel', 'preposisi', 'kata ganti']],
      ['Tanda | dalam contoh menunjukkan...', 'jeda antar-kelompok kata', ['titik', 'tekanan kata', 'intonasi naik']],
      ['"Would you like to go there?" berakhir dengan intonasi...', 'naik', ['turun', 'datar', 'naik lalu turun']],
      ['"had coffee and watched" — "and" dibaca...', 'lemah /ən/', ['keras /ænd/', 'tidak dibaca', '/end/']],
    ],
    task: 'Rekam paragraf contoh, lalu bandingkan tekanan dan jeda dengan audio model.',
  },
];

export const elementaryReadingExtra: ExtraEnglishLesson[] = [
  {
    id: 16, title: 'Blog Perjalanan', subtitle: 'Pengalaman dan opini penulis',
    intro: 'Blog menggabungkan fakta perjalanan dan opini pribadi. Bedakan keduanya.',
    points: ['Fakta: tempat, harga, waktu.', 'Opini: amazing, disappointing, I think...', 'Rekomendasi: You should... / Don\'t miss...'],
    examples: [['The ferry took two hours.', 'Kapal feri memakan waktu dua jam.'], ['The view was absolutely amazing.', 'Pemandangannya luar biasa.'], ['I think the hotel was a bit overpriced.', 'Menurut saya hotelnya agak kemahalan.'], ["Don't miss the night market!", 'Jangan lewatkan pasar malamnya!']],
    dialogue: [['Blog', 'Three Days in Yogyakarta', 'Tiga Hari di Yogyakarta'], ['Blog', 'I arrived by train on Friday morning. The trip from Jakarta took about eight hours.', 'Saya tiba naik kereta Jumat pagi. Perjalanan dari Jakarta sekitar delapan jam.'], ['Blog', 'On the first day, I visited Borobudur at sunrise. It was crowded, but the view was unforgettable.', 'Hari pertama saya mengunjungi Borobudur saat matahari terbit. Ramai, tapi pemandangannya tak terlupakan.'], ['Blog', 'The next day I took a batik class. I think it was the best part of my trip.', 'Hari berikutnya saya ikut kelas batik. Menurut saya itu bagian terbaik perjalanan.'], ['Blog', 'My guesthouse was cheap and clean, but the Wi-Fi was very slow.', 'Penginapan saya murah dan bersih, tapi Wi-Fi-nya sangat lambat.'], ['Blog', "If you go, don't miss the street food on Malioboro Street!", 'Kalau ke sana, jangan lewatkan jajanan di Jalan Malioboro!']],
    practice: [
      ['Berapa lama perjalanan kereta dari Jakarta?', 'Sekitar delapan jam', ['Dua jam', 'Satu hari penuh', 'Empat jam']],
      ['Menurut penulis, apa bagian terbaik perjalanan?', 'Kelas batik', ['Borobudur', 'Penginapan', 'Kereta']],
      ['Apa kekurangan penginapannya?', 'Wi-Fi sangat lambat', ['Mahal', 'Kotor', 'Jauh dari kota']],
      ['Kalimat mana yang merupakan OPINI?', 'I think it was the best part of my trip.', ['I arrived by train on Friday morning.', 'The trip took about eight hours.', 'I visited Borobudur at sunrise.']],
      ['Apa rekomendasi penulis?', 'Mencoba jajanan di Malioboro', ['Naik pesawat', 'Menghindari Borobudur', 'Menginap di hotel mahal']],
    ],
    task: 'Tulis entri blog 100 kata tentang perjalananmu dengan 3 fakta, 2 opini, dan 1 rekomendasi.',
  },
  {
    id: 17, title: 'Artikel Kesehatan', subtitle: 'Tips tidur yang baik',
    intro: 'Artikel tips punya judul, pengantar, dan beberapa saran bernomor. Temukan ide utama tiap tips.',
    points: ['Judul dan subjudul membantu memprediksi isi.', 'Saran memakai imperatif atau should.', 'Cari alasan setiap saran (because, so that).'],
    examples: [['Try to go to bed at the same time every night.', 'Usahakan tidur di jam yang sama setiap malam.'], ['Avoid coffee after 4 p.m.', 'Hindari kopi setelah jam 4 sore.'], ['Screens keep your brain awake.', 'Layar membuat otakmu tetap terjaga.'], ['Adults need seven to nine hours of sleep.', 'Orang dewasa butuh tidur tujuh sampai sembilan jam.']],
    dialogue: [['Article', 'Five Tips for Better Sleep', 'Lima Tips Tidur Lebih Baik'], ['Article', '1. Keep a regular routine: go to bed and wake up at the same time, even on weekends.', '1. Jaga rutinitas: tidur dan bangun di jam yang sama, bahkan di akhir pekan.'], ['Article', '2. Turn off your phone one hour before bed, because the light keeps your brain awake.', '2. Matikan ponsel satu jam sebelum tidur, karena cahayanya membuat otak terjaga.'], ['Article', '3. Avoid coffee and tea in the late afternoon.', '3. Hindari kopi dan teh di sore hari.'], ['Article', '4. Keep your bedroom dark, quiet, and a little cool.', '4. Jaga kamar tetap gelap, tenang, dan agak sejuk.'], ['Article', '5. If you cannot sleep after twenty minutes, get up and read a book until you feel sleepy.', '5. Jika tidak bisa tidur setelah dua puluh menit, bangun dan baca buku sampai mengantuk.']],
    practice: [
      ['Menurut tips 1, kapan rutinitas tidur tetap dijaga?', 'Juga di akhir pekan', ['Hanya hari kerja', 'Hanya saat sakit', 'Saat libur saja']],
      ['Mengapa ponsel harus dimatikan?', 'Cahayanya membuat otak terjaga', ['Menghemat baterai', 'Suaranya keras', 'Mahal']],
      ['Kamar tidur sebaiknya...', 'gelap, tenang, dan agak sejuk', ['terang dan hangat', 'ramai dan sejuk', 'terang dan tenang']],
      ['Apa yang dilakukan jika tidak bisa tidur setelah 20 menit?', 'Bangun dan membaca buku', ['Minum kopi', 'Bermain ponsel', 'Tetap berbaring']],
      ['Apa ide utama artikel?', 'Cara tidur lebih baik', ['Bahaya kopi', 'Cara membaca cepat', 'Olahraga malam']],
    ],
    task: 'Tulis artikel tips 5 poin tentang topik kesehatan pilihanmu dengan alasan tiap poin.',
  },
  {
    id: 18, title: 'Iklan Lowongan Kerja', subtitle: 'Syarat dan cara melamar',
    intro: 'Iklan lowongan berisi posisi, tanggung jawab, syarat, gaji, dan cara melamar.',
    points: ['Requirements = syarat. Responsibilities = tanggung jawab.', 'Full-time / part-time.', 'How to apply: send your CV to...'],
    examples: [['Part-time sales assistant wanted', 'Dicari asisten penjualan paruh waktu'], ['Experience is not necessary.', 'Pengalaman tidak wajib.'], ['Good English is an advantage.', 'Bahasa Inggris yang baik menjadi nilai tambah.'], ['Send your CV by 30 June.', 'Kirim CV paling lambat 30 Juni.']],
    dialogue: [['Ad', 'WE ARE HIRING: Café Assistant (part-time)', 'KAMI MEMBUKA LOWONGAN: Asisten Kafe (paruh waktu)'], ['Ad', 'Hours: 20 hours per week, including weekends.', 'Jam kerja: 20 jam per minggu, termasuk akhir pekan.'], ['Ad', 'Responsibilities: serving customers, making drinks, and cleaning tables.', 'Tanggung jawab: melayani pelanggan, membuat minuman, dan membersihkan meja.'], ['Ad', 'Requirements: friendly, 18 or older. Experience is not necessary — we will train you.', 'Syarat: ramah, minimal 18 tahun. Pengalaman tidak wajib — kami akan melatih.'], ['Ad', 'Basic English is an advantage because we have many tourists.', 'Bahasa Inggris dasar menjadi nilai tambah karena banyak turis.'], ['Ad', 'To apply, email your CV to jobs@beanhouse.id before 15 July.', 'Untuk melamar, kirim CV ke jobs@beanhouse.id sebelum 15 Juli.']],
    practice: [
      ['Berapa jam kerja per minggu?', '20 jam', ['40 jam', '12 jam', '8 jam']],
      ['Manakah yang BUKAN tanggung jawab pekerjaan ini?', 'Memasak makanan berat', ['Melayani pelanggan', 'Membuat minuman', 'Membersihkan meja']],
      ['Berapa usia minimal pelamar?', '18 tahun', ['17 tahun', '21 tahun', '25 tahun']],
      ['Mengapa bahasa Inggris menjadi nilai tambah?', 'Banyak turis', ['Pemiliknya orang asing', 'Menu dalam bahasa Inggris', 'Wajib ujian']],
      ['Bagaimana cara melamar?', 'Kirim CV lewat email', ['Datang langsung', 'Menelepon kafe', 'Mengisi formulir di kafe']],
    ],
    task: 'Tulis email lamaran singkat (60–80 kata) untuk lowongan ini.',
  },
  {
    id: 19, title: 'Cerita Pendek: Dompet', subtitle: 'Alur, tokoh, dan pesan',
    intro: 'Baca cerita pendek dan identifikasi tokoh, masalah, penyelesaian, dan pesan moral.',
    points: ['Alur: awal → masalah → penyelesaian.', 'Kata penghubung waktu: when, while, suddenly.', 'Pesan moral: pelajaran dari cerita.'],
    examples: [['While she was waiting for the bus, she saw a wallet.', 'Saat menunggu bus, dia melihat sebuah dompet.'], ['Suddenly, a man ran towards her.', 'Tiba-tiba seorang pria berlari ke arahnya.'], ['He thanked her many times.', 'Dia berterima kasih berkali-kali.'], ['Honesty is always the best choice.', 'Kejujuran selalu pilihan terbaik.']],
    dialogue: [['Story', 'Lina was a university student with very little money.', 'Lina adalah mahasiswi dengan uang yang sangat sedikit.'], ['Story', 'One afternoon, while she was waiting for the bus, she found a brown wallet under the bench.', 'Suatu sore, saat menunggu bus, dia menemukan dompet cokelat di bawah bangku.'], ['Story', 'Inside there was a lot of money and an ID card with an address.', 'Di dalamnya ada banyak uang dan kartu identitas dengan alamat.'], ['Story', 'Lina missed her bus and walked to the address instead.', 'Lina ketinggalan bus dan malah berjalan ke alamat itu.'], ['Story', 'An old man opened the door. He cried because the money was for his granddaughter\'s operation.', 'Seorang kakek membuka pintu. Dia menangis karena uang itu untuk operasi cucunya.'], ['Story', 'A week later, he visited Lina\'s university with a small gift and a thank-you letter.', 'Seminggu kemudian dia datang ke kampus Lina dengan hadiah kecil dan surat terima kasih.']],
    practice: [
      ['Di mana Lina menemukan dompet?', 'Di bawah bangku halte', ['Di dalam bus', 'Di kelas', 'Di jalan dekat rumah']],
      ['Bagaimana Lina tahu pemilik dompet?', 'Dari alamat di kartu identitas', ['Pemiliknya menelepon', 'Polisi memberi tahu', 'Ada nama di dompet saja']],
      ['Apa yang Lina korbankan?', 'Ketinggalan bus', ['Uang kuliahnya', 'Kelasnya', 'Pekerjaannya']],
      ['Untuk apa uang itu?', 'Operasi cucu sang kakek', ['Membeli rumah', 'Liburan', 'Biaya sekolah Lina']],
      ['Apa pesan moral cerita?', 'Kejujuran adalah pilihan terbaik', ['Uang adalah segalanya', 'Jangan naik bus', 'Selalu simpan dompet di saku']],
    ],
    task: 'Tulis ringkasan cerita dalam 5 kalimat dan satu kalimat pesan moral.',
  },
  {
    id: 20, title: 'Ujian Membaca A2', subtitle: 'Teks campuran: email + pengumuman',
    intro: 'Tes akhir membaca: dua teks pendek yang saling terkait. Bandingkan informasi di keduanya.',
    points: ['Baca pertanyaan dulu, lalu cari jawabannya.', 'Beberapa jawaban butuh informasi dari dua teks.', 'Waspadai pilihan yang hampir benar.'],
    examples: [['The meeting has been moved.', 'Pertemuan telah dipindah.'], ['Please note the new time.', 'Harap perhatikan waktu baru.'], ['Parking is limited.', 'Parkir terbatas.'], ['Reply to confirm.', 'Balas untuk konfirmasi.']],
    dialogue: [['Notice', 'Sunrise Apartments — Residents\' Meeting', 'Apartemen Sunrise — Rapat Penghuni'], ['Notice', 'Date: Tuesday 12 March, 7:30 p.m., in the lobby. Topic: new parking rules.', 'Tanggal: Selasa 12 Maret, 19.30, di lobi. Topik: aturan parkir baru.'], ['Email', 'Hi Sam, did you see the notice about the residents\' meeting?', 'Hai Sam, sudah lihat pengumuman rapat penghuni?'], ['Email', "The manager just told me it's moved to Wednesday, same time, because the lobby is being painted.", 'Manajer baru bilang rapat dipindah ke Rabu, jam sama, karena lobi sedang dicat.'], ['Email', "It will be in the rooftop garden instead. I can't go because I work late on Wednesdays.", 'Tempatnya di taman atap. Saya tidak bisa datang karena Rabu saya kerja sampai malam.'], ['Email', 'Could you take notes for me? Thanks! — Rosa (flat 5B)', 'Bisa catatkan untuk saya? Terima kasih! — Rosa (unit 5B)']],
    practice: [
      ['Apa topik rapat?', 'Aturan parkir baru', ['Pengecatan lobi', 'Kenaikan sewa', 'Keamanan gedung']],
      ['Kapan rapat diadakan sekarang?', 'Rabu 19.30', ['Selasa 19.30', 'Rabu 17.30', 'Kamis 19.30']],
      ['Mengapa rapat dipindah?', 'Lobi sedang dicat', ['Manajer sakit', 'Hujan', 'Tidak ada tempat parkir']],
      ['Di mana rapat diadakan sekarang?', 'Taman atap', ['Lobi', 'Unit 5B', 'Tempat parkir']],
      ['Apa yang Rosa minta dari Sam?', 'Mencatat isi rapat', ['Menggantikan kerjanya', 'Mengecat lobi', 'Memindahkan mobilnya']],
    ],
    task: 'Tulis balasan Sam untuk Rosa (40–60 kata) dan ringkasan 3 poin rapat imajiner.',
  },
];

export const elementarySpeakingExtra: ExtraEnglishLesson[] = [
  {
    id: 16, title: 'Mengeluh dengan Sopan', subtitle: "I'm afraid there's a problem with...",
    intro: 'Latih menyampaikan keluhan secara sopan, menjelaskan masalah, dan meminta solusi.',
    points: ["Membuka: Excuse me, I'm afraid there's a problem with...", 'Menjelaskan: It doesn\'t work / It\'s broken / It\'s the wrong size.', 'Meminta solusi: Could I get a refund / a replacement?'],
    examples: [["Excuse me, I'm afraid there's a problem with my room.", 'Permisi, sepertinya ada masalah dengan kamar saya.'], ["The air conditioner doesn't work.", 'AC-nya tidak berfungsi.'], ['Could you send someone to fix it?', 'Bisa kirim orang untuk memperbaikinya?'], ['Could I change it for another one?', 'Bisa saya tukar dengan yang lain?']],
    dialogue: [['Guest', "Excuse me, I'm afraid there's a problem with my room.", 'Permisi, sepertinya ada masalah dengan kamar saya.'], ['Receptionist', "I'm sorry to hear that. What's wrong?", 'Maaf mendengarnya. Ada apa?'], ['Guest', "The shower has no hot water, and it's quite noisy next to the lift.", 'Pancurannya tidak ada air panas, dan agak bising di sebelah lift.'], ['Receptionist', 'I apologize. We can move you to a quieter room on the eighth floor.', 'Mohon maaf. Kami bisa pindahkan Anda ke kamar lebih tenang di lantai delapan.'], ['Guest', "That would be great. Thank you for your help.", 'Itu bagus sekali. Terima kasih atas bantuannya.'], ['Receptionist', "You're welcome. Here's your new key.", 'Sama-sama. Ini kunci barunya.']],
    practice: [
      ['Pembuka keluhan yang sopan adalah...', "Excuse me, I'm afraid there's a problem.", ['Hey! This is bad!', 'You made a mistake!', 'Fix it now!']],
      ['"It doesn\'t work." artinya...', 'Tidak berfungsi.', ['Tidak bekerja di kantor.', 'Tidak ada.', 'Terlalu mahal.']],
      ['Meminta barang pengganti diucapkan...', 'Could I get a replacement?', ['Give me new one.', 'I want money now.', 'Replace!']],
      ['"I apologize." artinya...', 'Saya mohon maaf.', ['Saya setuju.', 'Saya menolak.', 'Saya mengerti.']],
    ],
    task: 'Rekam keluhan sopan di restoran (pesanan salah) dengan penjelasan dan permintaan solusi.',
  },
  {
    id: 17, title: 'Memberi Saran', subtitle: 'You should... · Why don\'t you...?',
    intro: 'Latih memberi dan menanggapi saran untuk masalah sehari-hari.',
    points: ['You should / shouldn\'t + V1.', "Why don't you...? / If I were you, I'd...", 'Menanggapi: That\'s a good idea. / I\'ve tried that, but...'],
    examples: [['You should get more sleep.', 'Kamu sebaiknya tidur lebih banyak.'], ["Why don't you join a club?", 'Kenapa kamu tidak ikut klub?'], ["If I were you, I'd talk to your teacher.", 'Kalau aku jadi kamu, aku akan bicara dengan gurumu.'], ["That's a good idea. Thanks!", 'Ide bagus. Terima kasih!']],
    dialogue: [['Friend', "I'm always tired these days, and I can't concentrate in class.", 'Belakangan aku selalu lelah dan tidak bisa konsentrasi di kelas.'], ['You', 'What time do you go to bed?', 'Kamu tidur jam berapa?'], ['Friend', 'Usually after midnight. I watch videos on my phone.', 'Biasanya lewat tengah malam. Aku menonton video di ponsel.'], ['You', 'You should put your phone away at ten.', 'Sebaiknya kamu simpan ponselmu jam sepuluh.'], ['You', "And why don't you go for a walk in the morning?", 'Dan kenapa tidak jalan pagi?'], ['Friend', "That's a good idea. I'll try it this week.", 'Ide bagus. Aku coba minggu ini.']],
    practice: [
      ['Kalimat saran yang benar adalah...', 'You should drink more water.', ['You should to drink more water.', 'You should drinking more water.', 'You shoulds drink more water.']],
      ['"If I were you, I\'d..." dipakai untuk...', 'memberi saran', ['meminta maaf', 'menolak ajakan', 'bercerita masa lalu']],
      ['Tanggapan positif untuk saran adalah...', "That's a good idea.", ['That is wrong.', 'No way.', 'I don\'t care.']],
      ['"Why don\'t you join a club?" artinya...', 'Kenapa kamu tidak ikut klub?', ['Kenapa kamu ikut klub?', 'Kamu tidak boleh ikut klub.', 'Klub itu tutup.']],
    ],
    task: 'Rekam 3 saran untuk teman yang ingin belajar bahasa Inggris lebih cepat.',
  },
  {
    id: 18, title: 'Membandingkan Pilihan', subtitle: 'Comparatives dalam percakapan',
    intro: 'Latih membandingkan dua pilihan (hotel, ponsel, transportasi) dan memutuskan.',
    points: ['cheaper, more comfortable, better, worse.', 'not as ... as: The bus is not as fast as the train.', "Keputusan: I'd prefer... because..."],
    examples: [['The train is faster than the bus.', 'Kereta lebih cepat dari bus.'], ['The bus is not as comfortable as the train.', 'Bus tidak senyaman kereta.'], ['This phone has a better camera.', 'Ponsel ini kameranya lebih bagus.'], ["I'd prefer the train because it's more reliable.", 'Saya lebih pilih kereta karena lebih bisa diandalkan.']],
    dialogue: [['Friend', 'Should we take the bus or the train to Bandung?', 'Kita naik bus atau kereta ke Bandung?'], ['You', "The bus is cheaper, but it's slower because of traffic.", 'Bus lebih murah, tapi lebih lambat karena macet.'], ['Friend', "The train is more expensive, isn't it?", 'Kereta lebih mahal, kan?'], ['You', "A little, but it's much more comfortable and there's no traffic.", 'Sedikit, tapi jauh lebih nyaman dan tidak ada macet.'], ['Friend', 'OK, I\'d prefer the train then.', 'Oke, aku lebih pilih kereta kalau begitu.'], ['You', "Me too. Let's book tickets tonight.", 'Aku juga. Ayo pesan tiket malam ini.']],
    practice: [
      ['Bentuk komparatif "good" adalah...', 'better', ['gooder', 'more good', 'best']],
      ['Lengkapi: "The bus is not as fast ___ the train."', 'as', ['than', 'like', 'so']],
      ['Bentuk komparatif "comfortable" adalah...', 'more comfortable', ['comfortabler', 'most comfortable', 'comfortablier']],
      ['"I\'d prefer..." artinya...', 'Saya lebih memilih...', ['Saya sudah membeli...', 'Saya tidak suka...', 'Saya harus...']],
    ],
    task: 'Rekam perbandingan dua ponsel/laptop (harga, kamera, baterai) dan keputusanmu.',
  },
  {
    id: 19, title: 'Cerita Liburan', subtitle: 'Past simple + past continuous',
    intro: 'Latih menceritakan pengalaman liburan dengan latar (past continuous) dan kejadian (past simple).',
    points: ['Latar: It was raining when we arrived.', 'Kejadian: We saw dolphins.', 'Perasaan & penilaian: It was the best trip ever.'],
    examples: [['We were walking on the beach when it started to rain.', 'Kami sedang berjalan di pantai ketika hujan mulai turun.'], ['We saw a group of dolphins.', 'Kami melihat sekelompok lumba-lumba.'], ['The food was delicious but expensive.', 'Makanannya enak tapi mahal.'], ['It was the best trip ever!', 'Itu perjalanan terbaik!']],
    dialogue: [['Friend', 'How was your holiday in Labuan Bajo?', 'Bagaimana liburanmu di Labuan Bajo?'], ['You', 'Amazing! On the second day we went on a boat trip.', 'Luar biasa! Hari kedua kami ikut tur perahu.'], ['You', 'While we were sailing, we saw a huge manta ray.', 'Saat kami berlayar, kami melihat pari manta raksasa.'], ['Friend', 'Wow! Did you see the Komodo dragons?', 'Wah! Lihat komodo?'], ['You', 'Yes, but I was a bit scared. They were bigger than I expected.', 'Ya, tapi aku agak takut. Mereka lebih besar dari perkiraanku.'], ['You', "It was the best trip ever. I'd love to go back.", 'Itu perjalanan terbaik. Aku ingin kembali.']],
    practice: [
      ['Past continuous untuk latar adalah...', 'We were sailing', ['We sailed yesterday', 'We sail', 'We will sail']],
      ['Lengkapi: "I ___ walking when I saw him."', 'was', ['were', 'am', 'did']],
      ['"They were bigger than I expected." artinya...', 'Mereka lebih besar dari perkiraanku.', ['Mereka sebesar yang kuduga.', 'Mereka lebih kecil.', 'Aku tidak melihat mereka.']],
      ['Bentuk lampau "see" adalah...', 'saw', ['seen', 'seed', 'sawed']],
    ],
    task: 'Rekam cerita liburan 1 menit dengan 2 kalimat past continuous dan 4 past simple.',
  },
  {
    id: 20, title: 'Simulasi Wawancara A2', subtitle: 'Penilaian akhir speaking A2',
    intro: 'Simulasi ujian lisan A2: pertanyaan pribadi, deskripsi, pengalaman, rencana, dan opini singkat.',
    points: ['Jawab lengkap: jawaban + alasan + contoh.', 'Pakai variasi tense: present, past, future.', 'Jika tidak paham: Could you repeat the question, please?'],
    examples: [['Could you repeat the question, please?', 'Bisa ulangi pertanyaannya?'], ['I usually... because...', 'Saya biasanya... karena...'], ['Last year I...', 'Tahun lalu saya...'], ["In the future, I'm planning to...", 'Di masa depan, saya berencana...']],
    dialogue: [['Examiner', 'Can you tell me about your hometown?', 'Ceritakan tentang kota asalmu.'], ['Candidate', "I'm from Malang. It's a cool city in the mountains, so the weather is nice.", 'Saya dari Malang. Kota sejuk di pegunungan, jadi cuacanya enak.'], ['Examiner', 'What did you do last weekend?', 'Apa yang kamu lakukan akhir pekan lalu?'], ['Candidate', 'I went to a coffee farm with my cousins and we learned how coffee is made.', 'Saya ke kebun kopi dengan sepupu dan kami belajar cara kopi dibuat.'], ['Examiner', 'What are your plans for next year?', 'Apa rencanamu tahun depan?'], ['Candidate', "I'm planning to take an English course because I want to work in tourism.", 'Saya berencana ikut kursus bahasa Inggris karena ingin bekerja di pariwisata.']],
    practice: [
      ['Jawaban wawancara yang baik berisi...', 'jawaban, alasan, dan contoh', ['satu kata saja', 'pertanyaan balik', 'diam']],
      ['Jika tidak paham pertanyaan, ucapkan...', 'Could you repeat the question, please?', ['What?', 'I don\'t know anything.', 'Next question.']],
      ['"I\'m planning to..." dipakai untuk...', 'rencana', ['masa lalu', 'kebiasaan', 'kemampuan']],
      ['Kalimat past simple yang benar adalah...', 'I went to a coffee farm.', ['I go to a coffee farm last week.', 'I going to a coffee farm.', 'I have go to a coffee farm.']],
    ],
    task: 'Rekam jawabanmu untuk tiga pertanyaan penguji di atas (masing-masing 30–40 detik) dan nilai dengan rubrik A2.',
  },
];

export const elementaryVocabularyExtra: ExtraEnglishLesson[] = [
  {
    id: 16, title: 'Environment & Recycling', subtitle: 'Lingkungan dan daur ulang',
    intro: 'Kosakata lingkungan: pollution, recycle, reuse, waste, dan kolokasinya.',
    points: ['reduce – reuse – recycle.', 'Kolokasi: save energy, waste water, protect nature.', 'Kata benda: pollution, rubbish/trash, plastic bag.'],
    examples: [['We should recycle plastic bottles.', 'Kita harus mendaur ulang botol plastik.'], ['Air pollution is a big problem in cities.', 'Polusi udara masalah besar di kota.'], ['Turn off the lights to save energy.', 'Matikan lampu untuk menghemat energi.'], ["Don't waste water.", 'Jangan membuang-buang air.']],
    practice: [
      ['"Reuse" artinya...', 'menggunakan kembali', ['mendaur ulang', 'mengurangi', 'membuang']],
      ['Kolokasi yang benar adalah...', 'save energy', ['make energy save', 'do energy', 'keep save energy']],
      ['"Pollution" artinya...', 'polusi', ['populasi', 'politik', 'solusi']],
      ['"Rubbish" artinya...', 'sampah', ['kain', 'karet', 'daur ulang']],
      ['Lengkapi: "Don\'t ___ water."', 'waste', ['save', 'recycle', 'protect']],
    ],
    task: 'Tulis 6 kebiasaan ramah lingkungan di rumahmu memakai kosakata pelajaran ini.',
  },
  {
    id: 17, title: 'Entertainment & Media', subtitle: 'Film, musik, dan internet',
    intro: 'Kosakata hiburan: genre film, jenis program, dan kata kerja media.',
    points: ['Genre: comedy, horror, action, documentary, cartoon.', 'Media: channel, episode, series, podcast, streaming.', 'Kata kerja: download, subscribe, post, share.'],
    examples: [['I love watching documentaries about nature.', 'Saya suka menonton dokumenter tentang alam.'], ['The new series has ten episodes.', 'Serial baru itu punya sepuluh episode.'], ['Subscribe to my channel!', 'Berlangganan kanal saya!'], ['She shared the video with her friends.', 'Dia membagikan video itu ke teman-temannya.']],
    practice: [
      ['Film tentang fakta nyata disebut...', 'documentary', ['comedy', 'cartoon', 'horror']],
      ['"Episode" artinya...', 'bagian dari serial', ['saluran TV', 'penyanyi', 'iklan']],
      ['"Subscribe" artinya...', 'berlangganan', ['mengunduh', 'menghapus', 'menyukai']],
      ['Film yang lucu disebut...', 'comedy', ['thriller', 'drama', 'news']],
      ['Lengkapi: "Can you ___ the photo with me?" (membagikan)', 'share', ['post office', 'channel', 'watch']],
    ],
    task: 'Rekomendasikan 3 film/serial/podcast favoritmu dengan genre dan alasannya (6 kalimat).',
  },
  {
    id: 18, title: 'School & Education', subtitle: 'Kehidupan sekolah dan kampus',
    intro: 'Kosakata pendidikan: subject, exam, homework, graduate, dan kolokasinya.',
    points: ['Kolokasi: take/pass/fail an exam, do homework, make progress.', 'Mata pelajaran: maths, history, biology, art.', 'graduate from + sekolah/kampus.'],
    examples: [['I passed my maths exam!', 'Saya lulus ujian matematika!'], ['Did you do your homework?', 'Sudah mengerjakan PR?'], ['She graduated from university last year.', 'Dia lulus kuliah tahun lalu.'], ["I'm making good progress in English.", 'Saya membuat kemajuan bagus dalam bahasa Inggris.']],
    practice: [
      ['Kolokasi yang benar adalah...', 'do homework', ['make homework', 'take homework', 'play homework']],
      ['"Fail an exam" artinya...', 'tidak lulus ujian', ['lulus ujian', 'mengikuti ujian', 'membatalkan ujian']],
      ['"Graduate from" artinya...', 'lulus dari', ['mendaftar ke', 'pindah dari', 'mengajar di']],
      ['Mata pelajaran tentang masa lalu adalah...', 'history', ['biology', 'geography', 'chemistry']],
      ['Lengkapi: "I\'m ___ good progress."', 'making', ['doing', 'taking', 'having']],
    ],
    task: 'Tulis paragraf 80 kata tentang pengalaman sekolah/kuliahmu dengan 5 kolokasi pelajaran ini.',
  },
  {
    id: 19, title: 'Phrasal Verbs Sehari-hari', subtitle: 'get up · look for · turn on',
    intro: 'Phrasal verb = kata kerja + partikel dengan arti baru. Sangat umum dalam percakapan.',
    points: ['get up (bangun), wake up (terjaga), look for (mencari).', 'turn on/off (menyalakan/mematikan), put on/take off (memakai/melepas).', 'give up (menyerah), find out (mengetahui).'],
    examples: [["I'm looking for my keys.", 'Saya sedang mencari kunci.'], ['Turn off the TV, please.', 'Tolong matikan TV.'], ["Don't give up!", 'Jangan menyerah!'], ['I found out the truth.', 'Saya mengetahui kebenarannya.']],
    practice: [
      ['"Look for" artinya...', 'mencari', ['melihat ke', 'menjaga', 'menunggu']],
      ['"Give up" artinya...', 'menyerah', ['memberi', 'bangun', 'naik']],
      ['Lengkapi: "Please ___ the lights. It\'s dark." ', 'turn on', ['turn off', 'give up', 'look for']],
      ['"Find out" artinya...', 'mengetahui / mencari tahu', ['menemukan barang di luar', 'keluar', 'kehilangan']],
      ['"Put on your jacket." artinya...', 'Pakai jaketmu.', ['Lepas jaketmu.', 'Letakkan jaketmu.', 'Cari jaketmu.']],
    ],
    task: 'Ceritakan rutinitas pagimu dalam 6 kalimat dengan minimal 5 phrasal verb.',
  },
  {
    id: 20, title: 'Kolokasi make/do/have/take', subtitle: 'Ulasan akhir kosakata A2',
    intro: 'Kolokasi adalah pasangan kata yang lazim. Banyak kesalahan terjadi pada make/do/have/take.',
    points: ['make: a mistake, a decision, a phone call, friends.', 'do: homework, the dishes, exercise, your best.', 'have: breakfast, a shower, fun. take: a photo, a bus, a break.'],
    examples: [['I made a mistake.', 'Saya membuat kesalahan.'], ['Can you do the dishes?', 'Bisa cuci piring?'], ["Let's have lunch.", 'Ayo makan siang.'], ['We took a lot of photos.', 'Kami mengambil banyak foto.']],
    practice: [
      ['Lengkapi: "___ a decision"', 'make', ['do', 'have', 'take']],
      ['Lengkapi: "___ exercise"', 'do', ['make', 'take', 'have']],
      ['Lengkapi: "___ a break"', 'take', ['make', 'do', 'have']],
      ['Lengkapi: "___ breakfast"', 'have', ['do', 'take', 'make']],
      ['Kalimat yang benar adalah...', 'I made a phone call.', ['I did a phone call.', 'I took a phone call make.', 'I had do a phone call.']],
    ],
    task: 'Buat tabel make/do/have/take dengan 5 kolokasi masing-masing, lalu tulis 8 kalimat.',
  },
];

export const elementaryWritingExtra: ExtraEnglishLesson[] = [
  {
    id: 16, title: 'Menulis Ulasan', subtitle: 'Restoran atau film',
    intro: 'Ulasan berisi informasi dasar, hal positif, hal negatif, dan rekomendasi dengan rating.',
    points: ['Pembuka: nama tempat/film, kapan, dengan siapa.', 'Positif & negatif: The best thing was... / However,...', 'Rekomendasi: I would recommend it to... ★★★★☆'],
    examples: [['Last Saturday I went to Rumah Sambal with my family.', 'Sabtu lalu saya ke Rumah Sambal bersama keluarga.'], ['The best thing was the grilled fish.', 'Hal terbaik adalah ikan bakarnya.'], ['However, the service was quite slow.', 'Namun pelayanannya cukup lambat.'], ['I would recommend it to spicy food lovers.', 'Saya merekomendasikannya untuk pecinta makanan pedas.']],
    practice: [
      ['Kata untuk memperkenalkan hal negatif adalah...', 'However,', ['Also,', 'Because,', 'First,']],
      ['"I would recommend it" artinya...', 'Saya akan merekomendasikannya', ['Saya tidak menyukainya', 'Saya ingin kembali besok', 'Saya bekerja di sana']],
      ['Bagian ulasan yang memberi penilaian akhir adalah...', 'rekomendasi dan rating', ['judul', 'tanggal', 'nama penulis']],
      ['Kalimat ulasan yang seimbang adalah...', 'The food was great, but it was expensive.', ['Everything was bad.', 'I went there.', 'The restaurant exists.']],
    ],
    task: 'Tulis ulasan 100 kata tentang restoran atau film terakhir yang kamu datangi/tonton.',
  },
  {
    id: 17, title: 'Menulis Cerita Pendek', subtitle: 'Awal, masalah, akhir',
    intro: 'Cerita pendek A2 memakai past simple, past continuous, dan kata penghubung waktu.',
    points: ['Awal: One day / Last summer...', 'Masalah: Suddenly... / While I was..., ...', 'Akhir: In the end / Finally...'],
    examples: [['Last summer, I was camping with my friends.', 'Musim panas lalu, saya berkemah dengan teman-teman.'], ['Suddenly, we heard a strange noise.', 'Tiba-tiba kami mendengar suara aneh.'], ['It was only a small monkey looking for food.', 'Ternyata hanya monyet kecil yang mencari makanan.'], ['In the end, we all laughed.', 'Akhirnya kami semua tertawa.']],
    practice: [
      ['Kata yang menandai kejadian mendadak adalah...', 'Suddenly', ['Usually', 'Tomorrow', 'Always']],
      ['Lengkapi: "While we ___ dinner, the lights went out."', 'were having', ['had', 'are having', 'have']],
      ['Kata penutup cerita adalah...', 'In the end', ['One day', 'While', 'Suddenly']],
      ['Struktur cerita yang benar adalah...', 'awal → masalah → akhir', ['akhir → awal → masalah', 'masalah → akhir → awal', 'hanya masalah']],
    ],
    task: 'Tulis cerita 120 kata berjudul "An Unexpected Day" dengan Suddenly dan In the end.',
  },
  {
    id: 18, title: 'Email Keluhan Sopan', subtitle: 'Formal sederhana',
    intro: 'Email keluhan formal: subjek jelas, masalah, detail, permintaan, dan penutup sopan.',
    points: ['Dear Sir or Madam, / Dear Customer Service,', 'I am writing to complain about... / Unfortunately,...', 'I would like a refund/replacement. Yours faithfully / Kind regards,'],
    examples: [['Subject: Damaged order #4521', 'Subjek: Pesanan rusak #4521'], ['I am writing to complain about my recent order.', 'Saya menulis untuk mengeluhkan pesanan saya baru-baru ini.'], ['Unfortunately, the screen was broken.', 'Sayangnya, layarnya rusak.'], ['I would be grateful if you could send a replacement.', 'Saya akan berterima kasih jika Anda bisa mengirim pengganti.']],
    practice: [
      ['Pembuka email keluhan formal adalah...', 'Dear Customer Service,', ['Hi guys!', 'Hey you,', 'Yo!']],
      ['"I am writing to complain about..." menunjukkan...', 'tujuan email', ['penutup email', 'salam', 'tanda tangan']],
      ['Permintaan yang sopan adalah...', 'I would be grateful if you could...', ['You must...', 'Do it now.', 'I want it today!']],
      ['Penutup email formal yang tepat adalah...', 'Kind regards,', ['Love,', 'See ya!', 'XOXO']],
    ],
    task: 'Tulis email keluhan 100 kata tentang paket yang terlambat dan rusak.',
  },
  {
    id: 19, title: 'Biografi Singkat', subtitle: 'Menulis tentang tokoh',
    intro: 'Biografi menceritakan hidup seseorang secara kronologis: lahir, pendidikan, karya, prestasi.',
    points: ['was born in + tahun/tempat.', 'Kronologi: In 1990..., After that..., Later...', 'Prestasi: is famous for / won an award for.'],
    examples: [['B.J. Habibie was born in Parepare in 1936.', 'B.J. Habibie lahir di Parepare tahun 1936.'], ['He studied engineering in Germany.', 'Dia belajar teknik di Jerman.'], ['He is famous for his work on aircraft.', 'Dia terkenal karena karyanya di bidang pesawat.'], ['Later, he became the President of Indonesia.', 'Kemudian dia menjadi Presiden Indonesia.']],
    practice: [
      ['Lengkapi: "She ___ born in 1995."', 'was', ['is', 'were', 'has']],
      ['"Is famous for" artinya...', 'terkenal karena', ['menyukai', 'bekerja untuk', 'lahir di']],
      ['Biografi biasanya ditulis dengan urutan...', 'kronologis', ['acak', 'dari akhir ke awal', 'berdasarkan abjad']],
      ['Kata penghubung waktu yang cocok adalah...', 'Later,', ['However,', 'Because,', 'For example,']],
    ],
    task: 'Tulis biografi 100–120 kata tentang tokoh yang kamu kagumi.',
  },
  {
    id: 20, title: 'Portofolio Menulis A2', subtitle: 'Penilaian akhir',
    intro: 'Kumpulkan tiga tulisan terbaikmu (email, cerita, ulasan) dan revisi memakai rubrik A2.',
    points: ['Periksa isi: apakah tujuan tulisan tercapai?', 'Periksa bahasa: tense, artikel, kolokasi.', 'Periksa format: salam, paragraf, penutup.'],
    examples: [['First draft → feedback → final draft', 'Draf pertama → umpan balik → draf akhir'], ['Check your verb tenses.', 'Periksa bentuk kata kerja.'], ['Use linking words: and, but, because, so.', 'Pakai kata penghubung: and, but, because, so.'], ['Read your text aloud before you submit it.', 'Baca tulisanmu keras-keras sebelum dikumpulkan.']],
    practice: [
      ['Langkah setelah draf pertama adalah...', 'meminta/meninjau umpan balik', ['langsung mengumpulkan', 'menghapus semua', 'menulis ulang tanpa membaca']],
      ['Kata penghubung sebab adalah...', 'because', ['but', 'and', 'or']],
      ['Kata penghubung akibat adalah...', 'so', ['because', 'although', 'if']],
      ['Tujuan membaca tulisan keras-keras adalah...', 'menemukan kalimat yang janggal', ['menghafal tulisan', 'mempercepat menulis', 'menambah kata']],
    ],
    task: 'Revisi tiga tulisan terbaikmu dan unggah ke catatan (Notes) sebagai portofolio A2.',
  },
];
