// Concept → emoji lexicon used to illustrate vocabulary cards. Keywords are
// matched as whole words against Indonesian meanings and English terms, so
// they must be lowercase. More specific concepts come first.
export const emojiLexicon: Array<[emoji: string, keywords: string[]]> = [
  // people & family
  ['👨‍👩‍👧', ['keluarga', 'family', 'keluarga inti', 'rumah tangga']],
  ['👶', ['bayi', 'baby', 'anak kecil']],
  ['🧒', ['anak', 'child', 'children', 'kids', 'cucu']],
  ['👵', ['nenek', 'grandmother', 'grandma', 'lansia', 'lanjut usia', 'orang tua lanjut']],
  ['👴', ['kakek', 'grandfather', 'grandpa']],
  ['👩', ['ibu', 'mother', 'mom', 'bibi', 'tante', 'aunt', 'wanita', 'perempuan', 'woman']],
  ['👨', ['ayah', 'bapak', 'father', 'dad', 'paman', 'uncle', 'pria', 'laki-laki', 'man']],
  ['🧑‍🤝‍🧑', ['teman', 'sahabat', 'friend', 'kawan', 'rekan', 'tetangga', 'neighbor', 'saudara', 'sibling', 'kakak', 'adik', 'sepupu', 'cousin']],
  ['💑', ['pasangan', 'suami', 'istri', 'husband', 'wife', 'pacar', 'menikah', 'pernikahan', 'wedding', 'marry']],
  ['👥', ['kepadatan penduduk', 'orang', 'people', 'masyarakat', 'penduduk', 'warga', 'komunitas', 'community', 'sosial', 'publik', 'generasi']],
  // jobs & roles
  ['👩‍🏫', ['guru', 'teacher', 'dosen', 'pengajar', 'mengajar', 'pendidik']],
  ['🧑‍🎓', ['siswa', 'murid', 'pelajar', 'mahasiswa', 'student', 'wisuda', 'lulus', 'graduate']],
  ['🧑‍⚕️', ['dokter', 'doctor', 'perawat', 'nurse', 'apoteker', 'pharmacist']],
  ['🧑‍🍳', ['koki', 'chef', 'memasak', 'cook', 'cooking', 'masak']],
  ['🧑‍🌾', ['petani', 'farmer', 'pertanian', 'agriculture', 'bertani', 'sawah']],
  ['🧑‍💼', ['pegawai', 'karyawan', 'employee', 'manajer', 'manager', 'bos', 'atasan', 'kantor', 'office', 'pekerja kantoran']],
  ['👮', ['polisi', 'police']],
  ['🧑‍✈️', ['pilot']],
  ['🧑‍🔬', ['ilmuwan', 'peneliti', 'scientist', 'researcher']],
  ['🧑‍⚖️', ['hakim', 'judge', 'pengacara', 'lawyer']],
  ['🧑‍🔧', ['insinyur', 'engineer', 'teknisi', 'mekanik', 'tukang']],
  ['🙋', ['relawan', 'volunteer', 'kerelawanan', 'sukarela']],
  // food & drink
  ['🍚', ['nasi', 'rice', 'beras']],
  ['🍜', ['mi', 'mie', 'noodles', 'noodle', 'ramen', 'sup', 'soup']],
  ['🍞', ['roti', 'bread', 'toast', 'sandwich', 'roti lapis']],
  ['🥚', ['telur', 'egg', 'eggs']],
  ['🍎', ['apel', 'apple', 'buah', 'fruit']],
  ['🍌', ['pisang', 'banana']],
  ['🍊', ['jeruk', 'orange']],
  ['🥦', ['sayur', 'sayuran', 'vegetable', 'vegetables']],
  ['🍗', ['ayam', 'chicken']],
  ['🐟', ['ikan', 'fish']],
  ['🥩', ['daging', 'meat', 'beef']],
  ['🍰', ['kue', 'cake', 'dessert', 'manis']],
  ['☕', ['kopi', 'coffee', 'kafe', 'cafe', 'café']],
  ['🍵', ['teh', 'tea']],
  ['🥛', ['susu', 'milk']],
  ['💧', ['air', 'water', 'air putih', 'minum', 'drink', 'haus', 'thirsty']],
  ['🍽️', ['makan', 'makanan', 'food', 'eat', 'restoran', 'restaurant', 'menu', 'hidangan', 'sarapan', 'breakfast', 'makan siang', 'lunch', 'makan malam', 'dinner', 'lapar', 'hungry']],
  // animals & nature
  ['🐱', ['kucing', 'cat']],
  ['🐶', ['anjing', 'dog']],
  ['🐦', ['burung', 'bird']],
  ['🐘', ['gajah', 'elephant']],
  ['🐒', ['monyet', 'monkey']],
  ['🐍', ['ular', 'snake']],
  ['🐇', ['kelinci', 'rabbit']],
  ['🦁', ['singa', 'lion', 'harimau', 'tiger']],
  ['🐄', ['sapi', 'cow']],
  ['🐾', ['hewan', 'binatang', 'animal', 'animals', 'peliharaan', 'pet']],
  ['🌳', ['pohon', 'tree', 'hutan', 'forest', 'taman', 'park', 'garden', 'kebun']],
  ['🌸', ['bunga', 'flower']],
  ['⛰️', ['gunung', 'mountain', 'bukit', 'hill', 'mendaki']],
  ['🏖️', ['pantai', 'beach', 'laut', 'sea', 'ocean', 'pulau', 'island']],
  ['🏞️', ['sungai', 'river', 'danau', 'lake', 'alam', 'nature', 'pemandangan']],
  ['🌍', ['dunia', 'world', 'global', 'globalisasi', 'bumi', 'earth', 'internasional', 'international', 'negara', 'country', 'bangsa']],
  ['🌱', ['lingkungan', 'environment', 'ekologi', 'ekologis', 'hijau', 'berkelanjutan', 'keberlanjutan', 'sustainable', 'sustainability', 'daur ulang', 'recycle']],
  // weather & time
  ['☀️', ['matahari', 'sun', 'sunny', 'cerah', 'panas', 'hot', 'musim panas', 'summer']],
  ['🌧️', ['hujan', 'rain', 'rainy']],
  ['☁️', ['awan', 'cloud', 'cloudy', 'berawan']],
  ['❄️', ['salju', 'snow', 'dingin', 'cold', 'musim dingin', 'winter', 'es']],
  ['🌬️', ['angin', 'wind', 'windy', 'berangin']],
  ['🌡️', ['cuaca', 'weather', 'suhu', 'temperature', 'iklim', 'climate', 'pemanasan']],
  ['⏰', ['jam', 'waktu', 'time', 'clock', 'pukul', 'menit', 'minute', 'detik', 'hour']],
  ['📅', ['hari', 'day', 'tanggal', 'date', 'minggu', 'week', 'bulan', 'month', 'tahun', 'year', 'jadwal', 'schedule', 'kalender', 'calendar', 'akhir pekan', 'weekend']],
  ['🌅', ['pagi', 'morning', 'subuh']],
  ['🌙', ['malam', 'night', 'bulan purnama', 'tidur', 'sleep']],
  // places & transport
  ['🏠', ['rumah', 'house', 'home', 'apartemen', 'apartment', 'perumahan', 'tempat tinggal', 'kamar', 'room', 'bedroom']],
  ['🏫', ['sekolah', 'school', 'kelas', 'class', 'classroom']],
  ['🏛️', ['universitas', 'university', 'kampus', 'campus', 'museum', 'lembaga', 'institusi', 'institution', 'pemerintah', 'government']],
  ['🏥', ['rumah sakit', 'hospital', 'klinik', 'clinic', 'apotek', 'pharmacy']],
  ['🏪', ['toko', 'shop', 'store', 'pasar', 'market', 'supermarket', 'mal', 'mall']],
  ['🏦', ['bank', 'perbankan']],
  ['📚', ['perpustakaan', 'library', 'buku', 'book', 'books', 'novel', 'membaca', 'read', 'reading', 'bacaan', 'literatur']],
  ['🕌', ['masjid', 'mosque', 'shalat', 'salat', 'ibadah', 'doa']],
  ['🏙️', ['kota', 'city', 'urban', 'urbanisasi', 'perkotaan', 'town']],
  ['🏡', ['desa', 'village', 'kampung', 'pedesaan', 'rural']],
  ['🚆', ['kereta', 'train', 'stasiun', 'station', 'rel', 'kereta bawah tanah', 'subway', 'metro']],
  ['🚌', ['bus', 'halte', 'transportasi umum', 'public transport', 'angkutan']],
  ['🚗', ['mobil', 'car', 'mengemudi', 'drive', 'driver', 'sopir', 'lalu lintas', 'traffic', 'macet', 'kemacetan', 'kepadatan']],
  ['🚲', ['sepeda', 'bicycle', 'bike', 'bersepeda', 'cycling']],
  ['✈️', ['pesawat', 'airplane', 'plane', 'bandara', 'airport', 'penerbangan', 'flight', 'terbang']],
  ['🧳', ['perjalanan', 'travel', 'trip', 'wisata', 'wisatawan', 'turis', 'tourist', 'liburan', 'holiday', 'vacation', 'koper', 'hotel']],
  ['🧭', ['alamat tujuan', 'alamat', 'address', 'arah', 'direction', 'directions', 'peta', 'map', 'lokasi', 'location', 'tempat', 'place']],
  // body & health
  ['🧠', ['otak', 'brain', 'pikiran', 'mind', 'berpikir', 'think', 'mental', 'psikologis', 'kognitif', 'ingatan', 'memori', 'memory']],
  ['❤️', ['jantung', 'heart', 'hati', 'cinta', 'love', 'sayang', 'kasih']],
  ['👁️', ['mata', 'eye', 'eyes', 'melihat', 'see', 'look', 'penglihatan']],
  ['👂', ['telinga', 'ear', 'mendengar', 'hear', 'listen', 'menyimak', 'listening', 'dengar']],
  ['👄', ['mulut', 'mouth', 'bibir', 'berbicara', 'speak', 'speaking', 'bicara', 'ucapan', 'pelafalan', 'pronunciation', 'lafal']],
  ['✋', ['tangan', 'hand', 'jari', 'finger']],
  ['🦶', ['kaki', 'foot', 'feet', 'leg']],
  ['🤒', ['sakit', 'sick', 'ill', 'demam', 'fever', 'batuk', 'cough', 'penyakit', 'disease', 'gejala', 'symptom', 'flu']],
  ['💊', ['obat', 'medicine', 'pil', 'pengobatan', 'terapi', 'treatment']],
  ['💉', ['vaksin', 'vaccine', 'vaksinasi', 'imunisasi', 'suntik']],
  ['🩺', ['sistem kesehatan', 'kesehatan', 'health', 'healthy', 'sehat', 'medis', 'medical', 'pemeriksaan']],
  ['🏃', ['olahraga', 'sport', 'sports', 'exercise', 'berlari', 'lari', 'run', 'running', 'fitness']],
  ['⚽', ['sepak bola', 'football', 'soccer', 'bola']],
  ['🏸', ['bulu tangkis', 'badminton']],
  ['🏊', ['berenang', 'swim', 'swimming', 'renang']],
  // feelings
  ['😊', ['senang', 'bahagia', 'happy', 'gembira', 'suka', 'like', 'kebahagiaan']],
  ['😢', ['sedih', 'sad', 'menangis', 'cry', 'kesedihan']],
  ['😠', ['marah', 'angry', 'kesal']],
  ['😴', ['lelah', 'capek', 'tired', 'mengantuk', 'sleepy']],
  ['😰', ['cemas', 'kecemasan', 'anxiety', 'gugup', 'nervous', 'takut', 'afraid', 'khawatir', 'stres', 'stress', 'tekanan']],
  ['🤩', ['bersemangat', 'antusias', 'excited', 'semangat']],
  ['😐', ['bosan', 'bored', 'boring', 'membosankan']],
  ['🧘', ['tenang', 'ketenangan', 'calm', 'relaks', 'santai', 'relax', 'keseimbangan', 'balance', 'damai', 'peace']],
  // objects
  ['📱', ['ponsel', 'handphone', 'phone', 'telepon', 'smartphone', 'hp', 'menelepon', 'call']],
  ['💻', ['komputer', 'computer', 'laptop', 'teknologi', 'technology', 'digital', 'internet', 'online', 'daring', 'aplikasi', 'app', 'perangkat lunak', 'software']],
  ['🤖', ['kecerdasan buatan', 'artificial intelligence', 'ai', 'robot', 'otomatisasi', 'automation', 'algoritma', 'algorithm', 'mesin']],
  ['📊', ['data', 'statistik', 'statistics', 'grafik', 'chart', 'analisis', 'analysis', 'survei', 'survey', 'angka']],
  ['✉️', ['surat', 'letter', 'email', 'pesan', 'message', 'kartu', 'card', 'pos', 'mail']],
  ['✏️', ['pensil', 'pencil', 'pulpen', 'pen', 'menulis', 'write', 'writing', 'tulisan', 'karangan', 'esai', 'essay', 'catatan', 'note']],
  ['📝', ['ujian', 'exam', 'test', 'tes', 'kuis', 'quiz', 'tugas', 'homework', 'pr', 'formulir', 'form', 'laporan', 'report']],
  ['🎒', ['tas', 'bag', 'ransel']],
  ['👕', ['baju', 'kaos', 'kemeja', 'shirt', 't-shirt', 'pakaian', 'clothes', 'clothing', 'jaket', 'jacket']],
  ['👖', ['celana', 'trousers', 'pants', 'jeans', 'rok', 'skirt']],
  ['👟', ['sepatu', 'shoes', 'shoe', 'sandal', 'kaus kaki', 'socks']],
  ['🔑', ['kunci', 'key', 'keys']],
  ['🛏️', ['kasur', 'tempat tidur', 'bed']],
  ['🪑', ['kursi', 'chair', 'meja', 'table', 'desk', 'sofa', 'perabot', 'furniture']],
  ['🧊', ['kulkas', 'fridge', 'refrigerator']],
  ['🎁', ['hadiah', 'gift', 'present', 'kado']],
  ['🎂', ['ulang tahun', 'birthday']],
  ['🎉', ['pesta', 'party', 'perayaan', 'festival', 'celebration', 'hari raya']],
  ['🎵', ['musik', 'music', 'lagu', 'song', 'menyanyi', 'sing', 'gitar', 'guitar', 'piano']],
  ['🎬', ['film', 'movie', 'bioskop', 'cinema', 'drama', 'serial', 'series', 'menonton']],
  ['📷', ['foto', 'photo', 'kamera', 'camera', 'memotret']],
  ['🎨', ['seni', 'art', 'melukis', 'painting', 'lukisan', 'gambar', 'drawing', 'estetika', 'kreativitas', 'creativity', 'kreatif']],
  ['🎮', ['game', 'gim', 'permainan', 'bermain', 'play']],
  ['📺', ['televisi', 'tv', 'media', 'berita', 'news', 'jurnalistik', 'wartawan', 'journalist']],
  ['📣', ['pengumuman', 'announcement', 'iklan', 'advertisement', 'promosi', 'kampanye', 'campaign']],
  ['🗣️', ['percakapan', 'conversation', 'dialog', 'dialogue', 'diskusi', 'discussion', 'debat', 'debate', 'wawancara', 'interview', 'komunikasi', 'communication', 'presentasi', 'pidato', 'speech']],
  ['🔤', ['huruf', 'letter', 'alfabet', 'alphabet', 'kata', 'word', 'kosakata', 'vocabulary', 'bahasa', 'language', 'kalimat', 'sentence', 'tata bahasa', 'grammar']],
  ['🌐', ['terjemahan', 'translation', 'menerjemahkan', 'translate', 'lintas budaya', 'budaya', 'culture', 'tradisi', 'tradition', 'identitas', 'identity']],
  // money & work
  ['💰', ['uang', 'money', 'gaji', 'salary', 'harga', 'price', 'biaya', 'cost', 'mahal', 'expensive', 'murah', 'cheap', 'bayar', 'pay', 'tabungan', 'modal', 'capital', 'dana', 'fund']],
  ['🛒', ['belanja', 'berbelanja', 'shopping', 'membeli', 'buy', 'konsumen', 'consumer', 'konsumsi', 'consumption']],
  ['📈', ['ekonomi', 'economy', 'economic', 'pertumbuhan', 'growth', 'investasi', 'investment', 'inflasi', 'inflation', 'pasar', 'bisnis', 'business', 'perdagangan', 'trade', 'industri', 'industry']],
  ['💼', ['pekerjaan', 'kerja', 'work', 'job', 'karier', 'career', 'profesi', 'profession', 'lowongan', 'bekerja', 'lapangan kerja', 'employment', 'wirausaha', 'kewirausahaan']],
  ['🤝', ['kerja sama', 'cooperation', 'kolaborasi', 'collaboration', 'kemitraan', 'partnership', 'perjanjian', 'agreement', 'negosiasi', 'negotiation', 'perundingan', 'diplomasi', 'diplomacy', 'solidaritas', 'toleransi', 'tolerance']],
  // society, law, science (abstract)
  ['⚖️', ['hukum', 'law', 'keadilan', 'justice', 'adil', 'fair', 'pengadilan', 'court', 'peradilan', 'undang-undang', 'konstitusi', 'constitution', 'hak', 'right', 'rights', 'kewajiban', 'etika', 'ethics', 'moral']],
  ['🏛', ['politik', 'politics', 'kebijakan', 'policy', 'tata kelola', 'governance', 'demokrasi', 'democracy', 'parlemen', 'legislasi', 'kekuasaan', 'power', 'otoritas', 'kedaulatan', 'sovereignty']],
  ['🎓', ['pendidikan', 'education', 'akademik', 'academic', 'kurikulum', 'curriculum', 'beasiswa', 'scholarship', 'belajar', 'study', 'learn', 'learning', 'kuliah', 'jurusan', 'gelar', 'degree', 'tesis', 'thesis', 'skripsi', 'disertasi']],
  ['🔬', ['penelitian', 'riset', 'research', 'sains', 'science', 'ilmiah', 'scientific', 'eksperimen', 'experiment', 'laboratorium', 'laboratory', 'hipotesis', 'hypothesis', 'metodologi', 'methodology', 'teori', 'theory', 'penemuan', 'discovery']],
  ['📖', ['teks', 'text', 'naskah', 'manuskrip', 'manuscript', 'kitab', 'sastra', 'literature', 'puisi', 'poem', 'poetry', 'cerita', 'story', 'narasi', 'narrative', 'sejarah', 'history', 'turats', 'syarah', 'tafsir']],
  ['💡', ['ide', 'idea', 'gagasan', 'inovasi', 'innovation', 'konsep', 'concept', 'solusi', 'solution', 'saran', 'suggestion', 'rekomendasi', 'recommendation']],
  ['🧩', ['argumen', 'argument', 'logika', 'logic', 'alasan', 'reason', 'bukti', 'evidence', 'kesimpulan', 'conclusion', 'premis', 'analisis wacana', 'struktur', 'structure', 'sistem', 'system', 'kompleks']],
  ['🔒', ['privasi', 'privacy', 'keamanan', 'security', 'aman', 'safe', 'safety', 'keselamatan', 'perlindungan', 'protection', 'rahasia', 'secret', 'kerahasiaan']],
  ['⚠️', ['risiko', 'risk', 'bahaya', 'danger', 'dangerous', 'berbahaya', 'krisis', 'crisis', 'ancaman', 'threat', 'peringatan', 'warning', 'darurat', 'emergency']],
  ['⚡', ['konsumsi energi', 'energi', 'energy', 'listrik', 'electricity', 'tenaga surya', 'solar', 'minyak bumi', 'oil', 'bahan bakar', 'fuel']],
  ['🏭', ['pabrik', 'factory', 'polusi', 'pollution', 'emisi', 'emission', 'karbon', 'carbon', 'limbah', 'waste', 'sampah', 'rubbish', 'trash']],
  ['🗳️', ['pemilu', 'election', 'vote', 'voting', 'suara rakyat']],
  ['🕊️', ['perdamaian', 'peace', 'damai', 'dialog antaragama', 'koeksistensi', 'coexistence', 'pengungsi', 'refugee', 'migran', 'migrant', 'migrasi', 'migration']],
  ['⭐', ['kualitas', 'quality', 'prestasi', 'achievement', 'kemajuan', 'progress', 'target', 'tujuan', 'goal', 'sukses', 'success', 'penguasaan', 'mastery', 'orisinalitas', 'kontribusi']],
  ['❓', ['pertanyaan', 'question', 'tanya', 'ask', 'masalah', 'problem', 'problematika', 'isu', 'issue']],
  ['🔢', ['nomor', 'number', 'numbers', 'angka', 'menghitung', 'count', 'counting', 'satu', 'dua', 'tiga']],
  ['🎨', ['warna', 'color', 'colors', 'merah', 'red', 'biru', 'blue', 'kuning', 'yellow', 'hijau', 'green', 'bentuk', 'shape', 'shapes']],
  ['👋', ['halo', 'hello', 'hai', 'hi', 'salam', 'greeting', 'greetings', 'sampai jumpa', 'goodbye', 'bye', 'selamat pagi', 'perkenalan', 'introduction', 'kenalan']],
  ['🙏', ['berterima kasih', 'tidak perlu berterima kasih', 'terima kasih', 'thank you', 'thanks', 'maaf', 'sorry', 'tolong', 'please', 'mohon', 'sopan', 'polite']],
  // abstract actions & concepts
  ['⬆️', ['meningkatkan', 'menaikkan', 'naik', 'increase', 'improve', 'peningkatan', 'kenaikan', 'memperbaiki', 'mengembangkan']],
  ['⬇️', ['mengurangi', 'menurunkan', 'turun', 'reduce', 'decrease', 'penurunan', 'penipisan', 'melemahkan', 'undermine', 'resesi', 'recession']],
  ['✅', ['keputusan', 'decision', 'memutuskan', 'decide', 'pilihan', 'choice', 'memilih', 'choose', 'setuju', 'agree', 'akuntabilitas', 'accountability', 'kepatuhan', 'compliance', 'bertanggung jawab', 'tanggung jawab', 'responsibility']],
  ['🔄', ['mengubah', 'perubahan', 'change', 'berubah', 'transformasi', 'transformation', 'sirkulasi', 'daur', 'beradaptasi', 'adaptasi', 'adapt', 'berkembang', 'reformasi', 'reform', 'memulihkan', 'restore']],
  ['🔍', ['membandingkan', 'compare', 'mengevaluasi', 'evaluate', 'evaluasi', 'meneliti', 'menganalisis', 'analyze', 'memeriksa', 'check', 'transparansi', 'transparency', 'meninjau', 'review', 'mempertimbangkan', 'consider', 'kritik', 'criticism', 'kritis', 'critical']],
  ['🗂️', ['mengatur', 'organize', 'menyelenggarakan', 'mengelola', 'manage', 'manajemen', 'management', 'dokumen', 'document', 'file', 'kerangka', 'framework', 'kategori', 'category', 'kriteria', 'criterion', 'menyimpan', 'save']],
  ['🗑️', ['menghapus', 'delete', 'membuang', 'membuang-buang', 'waste']],
  ['🚫', ['menghindari', 'avoid', 'larangan', 'dilarang', 'melarang', 'forbid', 'sensor', 'censorship', 'kendala', 'constraint', 'batasan', 'limit']],
  ['🚪', ['kesempatan', 'opportunity', 'peluang', 'akses', 'access', 'tersedia', 'available']],
  ['➕', ['keuntungan', 'advantage', 'kelebihan', 'manfaat', 'benefit', 'mencakup', 'include', 'menambah', 'add']],
  ['➖', ['kerugian', 'disadvantage', 'kekurangan', 'shortage', 'kelemahan', 'weakness', 'defisit', 'deficit']],
  ['💪', ['percaya diri', 'confident', 'confidence', 'kemampuan', 'ability', 'kekuatan', 'strength', 'kuat', 'strong', 'ambisius', 'ambitious', 'berani', 'brave']],
  ['🫶', ['mendukung', 'support', 'dukungan', 'membantu', 'help', 'bantuan', 'peduli', 'care', 'kepedulian', 'menghormati', 'respect', 'martabat', 'dignity', 'empati', 'empathy']],
  ['💬', ['menjelaskan', 'explain', 'penjelasan', 'explanation', 'mendeskripsikan', 'describe', 'wacana', 'discourse', 'menyarankan', 'suggest', 'merekomendasikan', 'recommend', 'permintaan', 'request', 'menekankan', 'emphasize', 'mengutip', 'quote', 'kutipan']],
  ['🔁', ['kebiasaan', 'habit', 'rutinitas', 'routine', 'teratur', 'regular', 'konsisten', 'consistent', 'berulang', 'kecenderungan', 'tendency']],
  ['⚔️', ['konflik', 'conflict', 'kontroversi', 'controversy', 'perang', 'war', 'bertentangan', 'kontradiksi', 'contradiction', 'paradoks', 'paradox', 'polarisasi']],
  ['🎯', ['hasil', 'result', 'akibat', 'consequence', 'dampak', 'impact', 'pengaruh', 'influence', 'efek', 'effect', 'tepat', 'precise', 'akurat', 'accurate']],
  ['⚙️', ['efisiensi', 'efficiency', 'efisien', 'efektif', 'effective', 'praktis', 'practical', 'berguna', 'useful', 'mekanisme', 'mechanism', 'proses', 'process', 'implementasi', 'implementation', 'memfasilitasi', 'facilitate']],
  ['💭', ['asumsi', 'assumption', 'wawasan', 'insight', 'pendapat', 'opinion', 'sudut pandang', 'perspektif', 'perspective', 'pandangan', 'paradigma', 'paradigm', 'metafora', 'metaphor', 'eksistensi', 'existence', 'kognisi', 'subjektivitas', 'objektivitas', 'universal', 'filsafat', 'philosophy', 'implikasi', 'implication', 'memahami', 'understand', 'pemahaman', 'ingat', 'remember', 'lupa', 'forget']],
  ['🧾', ['anggaran', 'budget', 'kurs', 'exchange rate', 'permintaan dan penawaran', 'pajak', 'tax', 'utang', 'debt', 'fiskal', 'fiscal', 'keuangan', 'finance', 'financial']],
  ['🧑‍⚖️', ['penggugat', 'plaintiff', 'tergugat', 'terdakwa', 'defendant', 'yurisdiksi', 'jurisdiction', 'norma', 'norm', 'aturan', 'rule', 'rules', 'regulasi', 'regulation', 'deregulasi']],
  ['🛡️', ['konservasi', 'conservation', 'melindungi', 'protect', 'menjaga', 'mempertahankan', 'pertahanan', 'kerentanan', 'vulnerability', 'ketahanan', 'resilience']],
  ['🌿', ['ekosistem', 'ecosystem', 'keanekaragaman', 'biodiversity', 'habitat']],
  ['🎭', ['satir', 'satire', 'sensasional', 'sensational', 'manipulasi', 'manipulation', 'gaya', 'style', 'nuansa', 'nuance', 'kesan', 'impression', 'citra', 'image']],
  ['🧮', ['komputasi', 'computation', 'menghitung', 'calculate', 'korelasi', 'correlation', 'rata-rata', 'average', 'persentase', 'percentage']],
  ['🔗', ['tetapi', 'namun', 'jika', 'meskipun', 'walaupun', 'oleh karena itu', 'akibatnya', 'daripada', 'terutama', 'sebaliknya', 'justru', 'bahkan', 'sebagai gantinya', 'lebih baik', 'kata penghubung', 'konjungsi', 'however', 'although', 'therefore', 'instead', 'nevertheless', 'consequently']],
  ['📏', ['ukuran', 'size', 'cukup besar', 'sangat besar', 'besar', 'big', 'kecil', 'small', 'panjang', 'long', 'pendek', 'short', 'cakupan', 'scope', 'jangkauan', 'menyeluruh', 'comprehensive', 'substansial', 'substantial']],
  // ---- extended concepts (added after the core list, so earlier entries win)
  // phrases whose single words would point the wrong way (longest phrase wins)
  ['🎯', ['tanpa ragu', 'tegas']],
  ['🌊', ['mudah bergejolak']],
  ['🚫', ['tak relevan', 'tidak relevan']],
  // time, plans & routine
  ['⏰', ['terlambat', 'keterlambatan', 'late', 'delay', 'tepat waktu', 'jadwal', 'schedule', 'tenggat', 'deadline']],
  ['⏳', ['menunggu', 'wait', 'sementara', 'temporary', 'sesaat', 'fana', 'ephemeral', 'memudar', 'fade']],
  ['📅', ['janji temu', 'appointment', 'reservasi', 'reservation', 'rencana', 'plan', 'agenda', 'kalender']],
  ['🔁', ['sering', 'often', 'selalu', 'always', 'biasanya', 'usually', 'kadang-kadang', 'sometimes', 'rutin', 'routine', 'kebiasaan', 'habit', 'tiada henti', 'relentless', 'berulang']],
  ['🏃', ['sibuk', 'busy', 'segera', 'soon', 'cepat', 'quick']],
  ['🏁', ['pada akhirnya', 'ultimately', 'akhirnya', 'finally', 'mengakhiri', 'terminate', 'menyelesaikan', 'resolve', 'melaksanakan', 'implement', 'melakukan', 'conduct', 'selesai']],
  ['🌸', ['musim semi', 'spring']],
  ['☀️', ['musim panas', 'musim kemarau', 'summer']],
  ['❄️', ['musim dingin', 'winter']],
  ['🌧️', ['musim hujan', 'rainy season']],
  ['🍂', ['musim', 'season', 'musim gugur', 'autumn']],
  ['☂️', ['payung', 'umbrella']],
  // travel & directions
  ['🎫', ['tiket', 'ticket']],
  ['🛂', ['paspor', 'passport', 'visa']],
  ['🧳', ['bagasi', 'luggage', 'baggage', 'koper']],
  ['🛬', ['tiba', 'arrive', 'kedatangan', 'arrival']],
  ['🛫', ['berangkat', 'depart', 'keberangkatan', 'departure']],
  ['🏨', ['akomodasi', 'accommodation', 'menginap', 'penginapan']],
  ['✈️', ['luar negeri', 'abroad', 'overseas']],
  ['🌍', ['asing', 'foreign', 'global', 'internasional']],
  ['⬆️', ['lurus', 'straight']],
  ['↪️', ['belok', 'turn', 'tikungan', 'corner']],
  ['🚸', ['menyeberang', 'cross']],
  ['➡️', ['menuju', 'toward', 'towards', 'arah', 'direction']],
  ['📍', ['di dekat sini', 'nearby', 'lokasi', 'location']],
  ['🔙', ['kembali', 'return', 'pulih', 'recover']],
  ['🧭', ['pengalaman', 'experience', 'menemui', 'encounter', 'petualangan']],
  // shopping, services & food
  ['🏷️', ['diskon', 'discount', 'potongan harga', 'harga', 'price']],
  ['🧾', ['struk', 'kuitansi', 'receipt', 'tagihan', 'bill', 'faktur']],
  ['🔑', ['sewa', 'menyewa', 'rent']],
  ['🛍️', ['pelanggan', 'customer', 'konsumen', 'consumer']],
  ['🛎️', ['layanan', 'service', 'pelayanan']],
  ['🌶️', ['pedas', 'spicy']],
  ['😋', ['lezat', 'delicious', 'enak']],
  ['📜', ['resep', 'recipe']],
  ['🧂', ['bahan', 'ingredient', 'bumbu']],
  ['🔄', ['meminjam', 'borrow', 'pergeseran', 'shift', 'perubahan', 'berubah', 'change', 'menyesuaikan diri', 'adapt', 'alternatif', 'alternative', 'fleksibel', 'flexible', 'plin-plan']],
  // events & teamwork
  ['🎉', ['merayakan', 'celebrate', 'perayaan', 'celebration', 'pesta']],
  ['💌', ['mengundang', 'invite', 'undangan', 'invitation']],
  ['🎨', ['hobi', 'hobby', 'kreativitas', 'creativity', 'menciptakan', 'create']],
  ['🎤', ['konser', 'concert', 'pidato', 'speech']],
  ['🏆', ['pertandingan', 'match', 'kompetisi', 'competition', 'juara', 'mencapai', 'achieve', 'prestasi', 'pencapaian']],
  ['🤝', ['tim', 'team', 'kerja sama', 'bekerja sama', 'berkolaborasi', 'collaborate', 'kolaborasi', 'bersama', 'together', 'kompromi', 'compromise', 'bernegosiasi', 'negotiate', 'kesepakatan', 'konsensus', 'consensus', 'timbal balik', 'mutual', 'mendamaikan']],
  ['🙋', ['kandidat', 'candidate', 'berpartisipasi', 'participate', 'partisipasi']],
  ['🧍', ['sendirian', 'alone']],
  ['👥', ['ramai', 'padat', 'crowded']],
  // communication
  ['🗣️', ['rapat', 'meeting', 'membujuk', 'persuade', 'menyampaikan', 'convey', 'mengungkapkan', 'express', 'retorika', 'rhetoric', 'meyakinkan']],
  ['💬', ['membahas', 'discuss', 'diskusi', 'percakapan', 'komunikasi', 'berbagi', 'share']],
  ['🗯️', ['berargumen', 'bertengkar', 'argue', 'mengkritik', 'criticize', 'kritik', 'menegur', 'bantahan']],
  ['📤', ['mengirim', 'send', 'kirim', 'menyebarluaskan', 'disseminate']],
  ['📥', ['mengunduh', 'download']],
  ['🌐', ['situs web', 'website', 'internet', 'online', 'daring']],
  ['ℹ️', ['informasi', 'information']],
  ['📰', ['artikel', 'article', 'berita', 'news', 'tajuk rencana', 'tajuk', 'editorial']],
  ['📖', ['kamus', 'dictionary', 'petunjuk', 'instructions', 'panduan', 'guide']],
  ['📝', ['memesan', 'order', 'melamar', 'apply', 'ringkas', 'concise', 'menyimpulkan', 'conclude', 'kesimpulan', 'singkat dan jelas', 'succinct']],
  ['📋', ['menyiapkan', 'prepare', 'persiapan', 'prasyarat', 'prerequisite', 'ketentuan', 'memenuhi syarat', 'syarat', 'requirement', 'mensyaratkan', 'require']],
  ['🔒', ['pribadi', 'private', 'privasi', 'privacy', 'rahasia', 'secret', 'diam-diam']],
  // feelings & character
  ['😤', ['keluhan', 'mengeluh', 'complaint', 'complain']],
  ['😟', ['kekhawatiran', 'concern', 'khawatir', 'worry', 'cemas', 'kecemasan', 'skeptis', 'skeptical', 'sceptical', 'enggan', 'reluctant', 'ragu', 'hesitant']],
  ['😲', ['terkejut', 'surprised', 'kaget', 'mencolok', 'belum pernah terjadi', 'unprecedented']],
  ['😞', ['kecewa', 'disappointed']],
  ['😳', ['malu', 'shy', 'embarrassed']],
  ['😊', ['ramah', 'friendly', 'empatik', 'empathetic', 'sopan', 'polite']],
  ['😌', ['bangga', 'proud', 'berpuas diri', 'complacent']],
  ['😇', ['jujur', 'honest', 'integritas', 'integrity', 'terus terang', 'candid']],
  ['🧘', ['sabar', 'patient', 'tenang', 'calm']],
  ['💪', ['usaha', 'effort', 'tekun', 'diligent', 'motivasi', 'motivation', 'komitmen', 'commitment', 'bersikeras', 'insist', 'memperkuat', 'strengthen', 'menguatkan', 'corroborate', 'tangguh', 'resilient']],
  ['💭', ['merasa', 'feel', 'perasaan', 'sikap', 'attitude', 'dugaan', 'conjecture', 'tampaknya', 'apparently', 'memandang', 'perceive', 'anggapan']],
  ['🤞', ['mengharapkan', 'expect', 'berharap', 'hope', 'harapan']],
  ['🎭', ['licik', 'insidious', 'palsu', 'spurious', 'mengakali', 'circumvent', 'seolah-olah']],
  // judgement & reasoning
  ['❗', ['penting', 'important', 'sangat penting', 'crucial', 'terpenting', 'paramount', 'mendasar', 'fundamental', 'prioritas', 'priority', 'sangat diperlukan', 'indispensable']],
  ['👌', ['mudah', 'easy', 'sederhana', 'simple', 'cukup', 'enough', 'memadai', 'adequate', 'layak', 'feasible']],
  ['🧗', ['sulit', 'difficult', 'tantangan', 'challenge', 'sulit diatasi', 'insurmountable']],
  ['🚫', ['membatalkan', 'cancel', 'mustahil', 'impossible', 'melarang', 'ban', 'hambatan', 'obstacle', 'barrier']],
  ['❌', ['kesalahan', 'mistake', 'error', 'keliru', 'erroneous', 'menolak', 'refuse', 'reject']],
  ['✅', ['mengonfirmasi', 'confirm', 'menerima', 'accept', 'memvalidasi', 'validate', 'membuktikan', 'prove', 'menyetujui', 'approve', 'mematuhi', 'comply']],
  ['👍', ['mengizinkan', 'allow', 'permit', 'insentif', 'incentive', 'dorongan', 'mendukung', 'support', 'menganjurkan', 'advocate']],
  ['🛡️', ['mencegah', 'prevent', 'melindungi', 'protect', 'menjamin', 'jaminan', 'guarantee', 'memastikan', 'ensure', 'rentan', 'vulnerable', 'mitigasi', 'mitigate']],
  ['⚠️', ['risiko', 'risk', 'bahaya', 'genting', 'precarious', 'merugikan', 'detrimental', 'merusak', 'undermine', 'memperparah', 'exacerbate', 'menimbulkan', 'insiden', 'incident', 'memburuk', 'deteriorate', 'perburukan']],
  ['💡', ['menyadari', 'realize', 'ide', 'idea', 'gagasan', 'inisiatif', 'initiative', 'terobosan', 'breakthrough', 'inovasi', 'menggagas', 'mencetuskan', 'contoh', 'example', 'mengilustrasikan', 'illustrate', 'solusi']],
  ['🧠', ['pengetahuan', 'knowledge', 'keahlian', 'expertise', 'cerdik', 'shrewd', 'kecerdasan', 'menafsirkan', 'interpret', 'interpretasi', 'interpretation', 'merenungkan', 'reflect', 'kesadaran', 'awareness']],
  ['🔍', ['menemukan', 'find', 'discover', 'mencari', 'search', 'seek', 'mengidentifikasi', 'identify', 'menyelidiki', 'investigate', 'teliti', 'sangat teliti', 'meticulous', 'ketat', 'rigorous']],
  ['🛠️', ['keterampilan', 'skill', 'peralatan', 'equipment', 'alat', 'tool', 'memodifikasi', 'modify', 'menyesuaikan', 'adjust', 'menyempurnakan', 'refine', 'memperbaiki']],
  ['📱', ['perangkat', 'device', 'aplikasi', 'app']],
  ['🔗', ['penyebab', 'menyebabkan', 'cause', 'menghubungkan', 'connect', 'bergantung', 'depend', 'mengandalkan', 'rely', 'konteks', 'context', 'relevan', 'relevant', 'terkait', 'berkaitan']],
  ['🎯', ['fokus', 'focus', 'tujuan', 'goal', 'target', 'sasaran', 'strategi', 'strategy', 'mengejar', 'pursue', 'pendekatan', 'approach', 'metode', 'method', 'prosedur', 'procedure', 'prinsip', 'principle']],
  ['⚖️', ['menilai', 'assess', 'penilaian', 'assessment', 'evaluasi', 'mempertimbangkan', 'memperhitungkan', 'membenarkan', 'justify', 'sah', 'legitimate', 'bias', 'diskriminasi', 'discrimination', 'sewenang-wenang', 'arbitrary', 'mengimbangi', 'offset']],
  ['🧩', ['kompleks', 'rumit', 'canggih', 'sophisticated', 'menguraikan', 'elaborate', 'melengkapi', 'complement', 'kompatibel', 'compatible', 'koheren', 'coherent', 'heterogen', 'heterogeneous', 'beragam', 'diverse', 'eklektik', 'eclectic']],
  ['🌫️', ['samar', 'vague', 'kabur', 'ambigu', 'ambiguous', 'ambiguitas', 'ambiguity', 'mengaburkan', 'obscure', 'tidak kentara', 'subtle', 'tidak jelas', 'tersirat', 'implicit', 'mendua']],
  ['⭐', ['favorit', 'favorite', 'favourite', 'berharga', 'valuable', 'teladan', 'exemplary', 'sempurna', 'flawless', 'menonjol', 'prominent', 'khas', 'distinctive', 'unik', 'unique']],
  ['🔥', ['populer', 'popular', 'berapi-api', 'vehement', 'memicu', 'trigger', 'merangsang', 'stimulate', 'membangkitkan', 'evoke']],
  ['📊', ['proyek', 'project', 'data', 'statistik', 'proporsi', 'proportion', 'tren', 'trend', 'faktor', 'factor', 'variasi', 'variation', 'rentang', 'range', 'memperkirakan', 'estimate', 'berfluktuasi', 'fluctuate', 'skenario', 'scenario']],
  ['📈', ['meningkat', 'increase', 'memperluas', 'expand', 'meluas', 'widespread', 'pesat', 'rapid', 'mempercepat', 'accelerate', 'potensi', 'potential', 'prospek', 'prospect']],
  ['📉', ['berkurang', 'decrease', 'diminish', 'merosot', 'meminimalkan', 'minimize', 'mengurangi', 'reduce']],
  ['🌊', ['penyebaran pesat', 'proliferation', 'merasuk', 'pervasive', 'ada di mana-mana', 'ubiquitous', 'lazim', 'prevalent', 'bergejolak', 'volatile']],
  ['🏛️', ['sektor', 'sector', 'infrastruktur', 'infrastructure', 'subsidi', 'subsidy', 'memberlakukan', 'enact', 'pemangku kepentingan', 'stakeholder', 'hegemoni', 'hegemony', 'konvensional', 'conventional']],
  ['🧪', ['empiris', 'empirical', 'menyimulasikan', 'simulate', 'fenomena', 'phenomenon', 'anomali', 'anomaly', 'eksperimen', 'experiment']],
  ['💰', ['mengalokasikan', 'allocate', 'sumber daya', 'resources', 'memperoleh', 'acquire']],
  ['📚', ['sumber', 'source', 'referensi', 'reference']],
  ['🛋️', ['nyaman', 'comfortable', 'kondusif', 'conducive']],
  ['🔊', ['bising', 'noisy', 'loud']],
];
