// Arabic Clause Connect: huruf 'athf, adawat rabth, ism maushul and time connectors, 30 per level.
// Conditionals (إذا/لو/إن) live in Idza Run; this bank covers the other connectors.
import type { ChoiceTuple } from './particles';

export const easyClauses: ChoiceTuple[] = [
  ['أكلت الخبز ____ شربت الحليب.', 'Saya makan roti dan minum susu.', 'و', ['أو', 'لكن', 'بل'], 'Tambahan', 'و = dan.'],
  ['هل تشرب الشاي ____ القهوة؟', 'Kamu minum teh atau kopi?', 'أم', ['و', 'لكن', 'ثم'], 'Pilihan (tanya)', 'أم = atau (setelah هل/أ).'],
  ['خذ قلما ____ كتابا.', 'Ambil pulpen atau buku.', 'أو', ['أم', 'لكن', 'ثم'], 'Pilihan', 'أو = atau (pernyataan).'],
  ['أحب القراءة ____ لا أحب الكتابة.', 'Saya suka membaca, tapi tidak suka menulis.', 'لكن', ['و', 'أو', 'ثم'], 'Kontras', 'لكن = tetapi.'],
  ['دخل المعلم ____ جلس.', 'Guru masuk lalu (segera) duduk.', 'فـ', ['أم', 'لكن', 'أو'], 'Urutan langsung', 'فـ = lalu (segera).'],
  ['درست ____ نمت.', 'Saya belajar, kemudian (setelah jeda) tidur.', 'ثم', ['أم', 'لكن', 'أو'], 'Urutan berjeda', 'ثم = kemudian.'],
  ['غبت ____ كنت مريضا.', 'Saya tidak masuk karena sakit.', 'لأني', ['لكني', 'ثم', 'أو'], 'Sebab', 'لأن = karena.'],
  ['هذا الطالب ____ نجح.', 'Ini siswa yang lulus.', 'الذي', ['التي', 'الذين', 'اللاتي'], 'Ism maushul', 'الذي untuk mudzakkar tunggal.'],
  ['هذه الطالبة ____ نجحت.', 'Ini siswi yang lulus.', 'التي', ['الذي', 'الذين', 'اللذان'], 'Ism maushul', 'التي untuk muannats tunggal.'],
  ['هؤلاء الطلاب ____ نجحوا.', 'Mereka para siswa yang lulus.', 'الذين', ['الذي', 'التي', 'اللذان'], 'Ism maushul', 'الذين untuk jamak mudzakkar.'],
  ['أكلت ____ شبعت.', 'Saya makan sampai kenyang.', 'حتى', ['لكن', 'أم', 'أو'], 'Sampai', 'حتى = sampai.'],
  ['ذهبت إلى السوق ____ اشتريت خضارا.', 'Saya pergi ke pasar lalu membeli sayur.', 'و', ['أم', 'لكن', 'أو'], 'Tambahan', 'و = dan.'],
  ['الجو بارد ____ لم ألبس المعطف.', 'Cuaca dingin, tetapi saya tidak memakai mantel.', 'لكن', ['و', 'أو', 'ثم'], 'Kontras', 'لكن = tetapi.'],
  ['هل أنت طالب ____ معلم؟', 'Apakah kamu siswa atau guru?', 'أم', ['أو', 'و', 'لكن'], 'Pilihan (tanya)', 'أم setelah هل.'],
  ['____ وصلت إلى البيت، نمت.', 'Ketika sampai di rumah, saya tidur.', 'عندما', ['لكن', 'أو', 'أم'], 'Waktu', 'عندما = ketika.'],
  ['أحب أبي ____ أمي.', 'Saya mencintai ayah dan ibu.', 'و', ['أم', 'لكن', 'بل'], 'Tambahan', 'و = dan.'],
  ['جاء أحمد ____ علي.', 'Ahmad datang, lalu Ali (setelah jeda).', 'ثم', ['أم', 'لكن', 'بل'], 'Urutan berjeda', 'ثم = kemudian.'],
  ['ما جاء زيد ____ عمرو.', 'Bukan Zaid yang datang, melainkan Amr.', 'بل', ['أم', 'ثم', 'و'], 'Koreksi', 'بل = melainkan.'],
  ['هذا هو البيت ____ أسكن فيه.', 'Inilah rumah yang saya tinggali.', 'الذي', ['التي', 'الذين', 'اللاتي'], 'Ism maushul', 'الذي untuk mudzakkar (بيت).'],
  ['هذه هي السيارة ____ اشتريتها.', 'Inilah mobil yang saya beli.', 'التي', ['الذي', 'الذين', 'اللذان'], 'Ism maushul', 'التي untuk muannats (سيارة).'],
  ['تعلمت العربية ____ أفهم القرآن.', 'Saya belajar bahasa Arab agar memahami Al-Qur’an.', 'لكي', ['لكن', 'ثم', 'أم'], 'Tujuan', 'لكي = agar.'],
  ['استيقظت مبكرا ____ أصلي الفجر.', 'Saya bangun pagi untuk salat Subuh.', 'لـ', ['لكن', 'أم', 'أو'], 'Tujuan', 'لـ + mudhari = untuk.'],
  ['أنا جائع ____ لم آكل.', 'Saya lapar karena belum makan.', 'لأني', ['لكني', 'ثم', 'أم'], 'Sebab', 'لأن = karena.'],
  ['اكتب ____ اقرأ.', 'Tulislah atau bacalah.', 'أو', ['أم', 'لكن', 'بل'], 'Pilihan', 'أو = atau.'],
  ['هو فقير ____ هو سعيد.', 'Dia miskin, tetapi dia bahagia.', 'لكن', ['أو', 'أم', 'ثم'], 'Kontras', 'لكن = tetapi.'],
  ['____ جاء المعلم، وقف الطلاب.', 'Ketika guru datang, para siswa berdiri.', 'لما', ['لكن', 'أم', 'أو'], 'Waktu lampau', 'لما + madhi = ketika.'],
  ['انتظرت ____ جاء صديقي.', 'Saya menunggu sampai temanku datang.', 'حتى', ['لكن', 'أم', 'أو'], 'Sampai', 'حتى = sampai.'],
  ['أعرف الرجل ____ يعمل هنا.', 'Saya kenal laki-laki yang bekerja di sini.', 'الذي', ['التي', 'الذين', 'اللاتي'], 'Ism maushul', 'الذي untuk mudzakkar tunggal.'],
  ['أكلت التفاحة ____ الموز.', 'Saya makan apel dan pisang.', 'و', ['أم', 'لكن', 'بل'], 'Tambahan', 'و = dan.'],
  ['قرأت الكتاب ____ فهمته.', 'Saya membaca buku itu lalu (langsung) memahaminya.', 'فـ', ['أم', 'لكن', 'أو'], 'Urutan langsung', 'فـ = lalu.'],
];

export const mediumClauses: ChoiceTuple[] = [
  ['ذهبت إلى المكتبة ____ أقرأ.', 'Saya pergi ke perpustakaan agar bisa membaca.', 'كي', ['لكن', 'أم', 'بل'], 'Tujuan', 'كي + mudhari manshub = agar.'],
  ['____ كنت أدرس، اتصل صديقي.', 'Ketika saya sedang belajar, temanku menelepon.', 'بينما', ['لكن', 'أم', 'بل'], 'Bersamaan', 'بينما = ketika/sementara.'],
  ['____ أن انتهيت من الأكل، غسلت يدي.', 'Setelah selesai makan, saya mencuci tangan.', 'بعد', ['قبل', 'منذ', 'لكن'], 'Waktu', 'بعد أن + fi’il = setelah.'],
  ['____ أن تنام، اغسل أسنانك.', 'Sebelum tidur, sikatlah gigimu.', 'قبل', ['بعد', 'منذ', 'لكن'], 'Waktu', 'قبل أن + mudhari = sebelum.'],
  ['____ أن كان صغيرا وهو يحب الرسم.', 'Sejak kecil dia suka menggambar.', 'منذ', ['قبل', 'بعد', 'حتى'], 'Waktu', 'منذ أن = sejak.'],
  ['لم أحضر الدرس ____ المطر.', 'Saya tidak hadir karena hujan.', 'بسبب', ['رغم', 'لكن', 'بل'], 'Sebab + kata benda', 'بسبب + ism = karena.'],
  ['خرجت ____ المطر.', 'Saya keluar meskipun hujan.', 'رغم', ['بسبب', 'لأن', 'لكي'], 'Konsesi + kata benda', 'رغم + ism = meskipun.'],
  ['____ أنه متعب، فقد واصل العمل.', 'Meskipun lelah, dia tetap melanjutkan pekerjaan.', 'مع', ['بسبب', 'لأن', 'لكي'], 'Konsesi', 'مع أنّ = meskipun.'],
  ['اجتهد ____ تنجح.', 'Bersungguh-sungguhlah agar kamu berhasil.', 'لكي', ['لأن', 'بسبب', 'رغم'], 'Tujuan', 'لكي = agar.'],
  ['أحب الرياضة، ____ كرة القدم.', 'Saya suka olahraga, terutama sepak bola.', 'خاصة', ['لكن', 'أم', 'بل'], 'Pengkhususan', 'خاصة = terutama.'],
  ['هؤلاء الطالبات ____ فزن بالجائزة.', 'Mereka para siswi yang memenangkan hadiah.', 'اللاتي', ['الذين', 'الذي', 'التي'], 'Ism maushul', 'اللاتي untuk jamak muannats.'],
  ['الطالبان ____ نجحا في الامتحان مجتهدان.', 'Dua siswa yang lulus ujian itu rajin.', 'اللذان', ['الذين', 'الذي', 'اللتان'], 'Ism maushul', 'اللذان untuk mutsanna mudzakkar (rafa’).'],
  ['الطالبتان ____ نجحتا مجتهدتان.', 'Dua siswi yang lulus itu rajin.', 'اللتان', ['اللذان', 'التي', 'الذين'], 'Ism maushul', 'اللتان untuk mutsanna muannats.'],
  ['____ تزرع تحصد.', 'Apa yang kamu tanam, itulah yang kamu tuai.', 'ما', ['من', 'الذي', 'لكن'], 'Ism maushul umum', 'ما = apa yang (benda).'],
  ['____ جد وجد.', 'Barang siapa bersungguh-sungguh, dia akan berhasil.', 'من', ['ما', 'الذي', 'لكن'], 'Ism maushul umum', 'من = siapa yang.'],
  ['ما زلت أنتظر ____ الآن.', 'Saya masih menunggu sampai sekarang.', 'حتى', ['منذ', 'قبل', 'بعد'], 'Sampai', 'حتى = sampai.'],
  ['ذاكرت دروسي، ____ نجحت.', 'Saya mengulang pelajaran, karena itu saya lulus.', 'لذلك', ['لكن', 'بل', 'رغم'], 'Akibat', 'لذلك = karena itu.'],
  ['كان المطر شديدا، ____ لم نخرج.', 'Hujan sangat deras, maka kami tidak keluar.', 'فـ', ['لكن', 'رغم', 'بل'], 'Akibat', 'فـ = maka.'],
  ['لا أشرب القهوة ____ الشاي.', 'Saya tidak minum kopi, juga tidak teh.', 'ولا', ['بل', 'أم', 'لكن'], 'Negatif ganda', 'لا … ولا = tidak … dan tidak.'],
  ['____ الطالب يجتهد، نجح.', 'Karena siswa itu rajin, dia lulus.', 'لأن', ['لكن', 'رغم', 'بل'], 'Sebab', 'لأنّ + ism manshub = karena.'],
  ['قرأت الكتاب ____ صفحته الأخيرة.', 'Saya membaca buku itu hingga halaman terakhir.', 'حتى', ['منذ', 'قبل', 'رغم'], 'Sampai', 'حتى + ism majrur = hingga.'],
  ['أنا أحب العربية، ____ أخي يحب الإنجليزية.', 'Saya suka bahasa Arab, sedangkan saudaraku suka bahasa Inggris.', 'بينما', ['لأن', 'لكي', 'حتى'], 'Perbandingan', 'بينما = sedangkan.'],
  ['____ دخلت الفصل، بدأ الدرس.', 'Begitu saya masuk kelas, pelajaran dimulai.', 'ما إن', ['لكن', 'بل', 'رغم'], 'Seketika', 'ما إن … حتى = begitu … langsung.'],
  ['هو لا يدرس فقط، ____ يعمل أيضا.', 'Dia tidak hanya belajar, tetapi juga bekerja.', 'بل', ['أم', 'ثم', 'أو'], 'Tambahan', 'لا … فقط، بل … أيضا.'],
  ['____ أكملت الواجب، ذهبت للعب.', 'Setelah menyelesaikan PR, saya pergi bermain.', 'بعدما', ['قبلما', 'لكن', 'رغم'], 'Waktu', 'بعدما = setelah.'],
  ['سأنتظرك ____ تعود.', 'Saya akan menunggumu sampai kamu kembali.', 'حتى', ['منذ', 'لكن', 'بل'], 'Sampai', 'حتى + mudhari manshub.'],
  ['المدينة ____ زرتها جميلة.', 'Kota yang saya kunjungi indah.', 'التي', ['الذي', 'الذين', 'اللذان'], 'Ism maushul', 'التي untuk muannats.'],
  ['____ أنك تحب القراءة، فخذ هذا الكتاب.', 'Karena kamu suka membaca, ambillah buku ini.', 'بما', ['رغم', 'لكن', 'بل'], 'Sebab', 'بما أنّ = karena (sudah diketahui).'],
  ['صليت ____ نمت.', 'Saya salat, kemudian tidur.', 'ثم', ['أم', 'بل', 'لكن'], 'Urutan berjeda', 'ثم = kemudian.'],
  ['رأيت رجلا ____ يركض.', 'Saya melihat seorang laki-laki sedang berlari.', 'وهو', ['لكن', 'أم', 'بل'], 'Hal', 'وهو + kalimat = sambil/dalam keadaan.'],
];

export const hardClauses: ChoiceTuple[] = [
  ['____ أنه كان مريضا، فقد حضر الاجتماع.', 'Meskipun sakit, dia menghadiri rapat.', 'رغم', ['بما', 'لذلك', 'كي'], 'Konsesi', 'رغم أنّ = meskipun.'],
  ['ادرس جيدا ____ ترسب في الامتحان.', 'Belajarlah dengan baik agar tidak gagal ujian.', 'لئلا', ['لكي', 'حتى', 'لأن'], 'Mencegah', 'لئلا = agar tidak.'],
  ['____ الطلاب، فقد نجحوا جميعا.', 'Adapun para siswa, mereka semua lulus.', 'أما', ['إما', 'لكن', 'بل'], 'Penegasan topik', 'أما … فـ = adapun … maka.'],
  ['____ أن تذاكر وإما أن ترسب.', 'Kamu belajar atau kamu gagal.', 'إما', ['أما', 'لكن', 'بل'], 'Pilihan tegas', 'إما … وإما = entah … atau.'],
  ['ما ____ الطالب يجتهد حتى نجح.', 'Siswa itu terus bersungguh-sungguh hingga lulus.', 'زال', ['كان', 'صار', 'ليس'], 'Terus-menerus', 'ما زال = masih/terus.'],
  ['____ قرأت ازددت علما.', 'Setiap kali membaca, ilmuku bertambah.', 'كلما', ['لكن', 'بل', 'أم'], 'Pengulangan', 'كلما … (fi’il) = setiap kali.'],
  ['لم يكد يصل ____ بدأ المطر.', 'Baru saja dia tiba, hujan mulai turun.', 'حتى', ['لكن', 'بل', 'أم'], 'Seketika', 'لم يكد … حتى = baru saja … langsung.'],
  ['لا يسافر ____ ومعه جواز سفره.', 'Dia tidak bepergian kecuali membawa paspornya.', 'إلا', ['لكن', 'بل', 'أم'], 'Pengecualian', 'لا … إلا = tidak … kecuali.'],
  ['جاء الطلاب ____ أحمد.', 'Para siswa datang, kecuali Ahmad.', 'إلا', ['لكن', 'بل', 'أو'], 'Istitsna', 'إلا = kecuali.'],
  ['حضر الجميع ____ المدير.', 'Semua hadir, termasuk direktur.', 'بما فيهم', ['إلا', 'لكن', 'بل'], 'Termasuk', 'بما فيهم = termasuk mereka.'],
  ['____ أنني أحترم رأيك، فإنني لا أوافق.', 'Walaupun saya menghormati pendapatmu, saya tidak setuju.', 'مع', ['بما', 'لذا', 'كي'], 'Konsesi', 'مع أنّ = walaupun.'],
  ['كان متعبا، ____ أكمل عمله.', 'Dia lelah, namun tetap menyelesaikan pekerjaannya.', 'ومع ذلك', ['لذلك', 'لأن', 'كي'], 'Kontras', 'ومع ذلك = namun demikian.'],
  ['ارتفعت الأسعار، ____ قل الشراء.', 'Harga naik, sehingga pembelian berkurang.', 'لذلك', ['رغم أن', 'لكي', 'بينما'], 'Akibat', 'لذلك = karena itu.'],
  ['الكتاب ____ قرأته مفيد.', 'Buku yang saya baca bermanfaat.', 'الذي', ['التي', 'ما', 'من'], 'Ism maushul', 'الذي untuk mudzakkar.'],
  ['أعجبني ____ قلته.', 'Saya suka apa yang kamu katakan.', 'ما', ['من', 'الذي', 'التي'], 'Ism maushul umum', 'ما = apa yang.'],
  ['أكرم ____ يحترمك.', 'Muliakanlah orang yang menghormatimu.', 'من', ['ما', 'التي', 'اللاتي'], 'Ism maushul umum', 'من = orang yang.'],
  ['____ يجتهد الطالب ينجح.', 'Ketika siswa bersungguh-sungguh, dia berhasil.', 'حينما', ['بل', 'أم', 'لكن'], 'Waktu', 'حينما = ketika.'],
  ['____ العلم نافع، فاطلبه.', 'Karena ilmu itu bermanfaat, carilah.', 'بما أن', ['رغم أن', 'لئلا', 'إما'], 'Sebab', 'بما أنّ = karena (sudah diketahui).'],
  ['لا تأكل ____ تشبع.', 'Jangan makan sampai kekenyangan.', 'حتى', ['لكن', 'بل', 'أم'], 'Batas', 'حتى = sampai.'],
  ['____ غربت الشمس حتى أفطرنا.', 'Begitu matahari terbenam, kami langsung berbuka.', 'ما إن', ['لكن', 'رغم', 'لئلا'], 'Seketika', 'ما إن … حتى.'],
  ['ليس الغنى بكثرة المال، ____ الغنى غنى النفس.', 'Kaya bukan karena banyak harta, melainkan kaya jiwa.', 'وإنما', ['لذلك', 'رغم', 'كي'], 'Koreksi', 'ليس … وإنما = bukan … melainkan.'],
  ['سافر ____ يبحث عن العمل.', 'Dia bepergian untuk mencari pekerjaan.', 'لكي', ['لئلا', 'رغم', 'بينما'], 'Tujuan', 'لكي = agar/untuk.'],
  ['ذهب إلى الطبيب ____ شعر بالألم.', 'Dia pergi ke dokter begitu merasa sakit.', 'حالما', ['رغم', 'لئلا', 'بل'], 'Seketika', 'حالما = begitu.'],
  ['____ المعلمون فقد حضروا مبكرين.', 'Adapun para guru, mereka hadir lebih awal.', 'أما', ['إما', 'بل', 'لكن'], 'Penegasan topik', 'أما … فـ.'],
  ['يدرس ____ يعمل في الوقت نفسه.', 'Dia belajar sekaligus bekerja di waktu yang sama.', 'و', ['أم', 'بل', 'لكن'], 'Bersamaan', 'و = dan (bersamaan).'],
  ['لم ينجح ____ لم يجتهد.', 'Dia tidak lulus karena tidak bersungguh-sungguh.', 'لأنه', ['لكنه', 'رغم أنه', 'كي'], 'Sebab', 'لأنّه = karena dia.'],
  ['قرأت الرسالة ____ عرفت الحقيقة.', 'Saya membaca surat itu, maka saya tahu kebenarannya.', 'فـ', ['أم', 'رغم', 'لئلا'], 'Akibat langsung', 'فـ = maka.'],
  ['هذا هو الرجل ____ ساعدني.', 'Inilah laki-laki yang membantuku.', 'الذي', ['التي', 'ما', 'اللاتي'], 'Ism maushul', 'الذي untuk mudzakkar.'],
  ['____ تأخر القطار، وصلنا في الموعد.', 'Meskipun kereta terlambat, kami sampai tepat waktu.', 'رغم', ['بسبب', 'بما', 'لكي'], 'Konsesi + kata benda', 'رغم + ism = meskipun.'],
  ['العلم في الصغر ____ النقش على الحجر.', 'Ilmu di waktu kecil seperti ukiran di atas batu.', 'كـ', ['بـ', 'لـ', 'فـ'], 'Perumpamaan', 'كـ = seperti.'],
];
