// Arabic Error Fix: [wrong sentence, corrected sentence, translation, type, rule, other wrong versions], 30 per level.
export type ErrorFixTuple = [wrong: string, correct: string, translation: string, type: string, rule: string, alternatives: [string, string]];

const SIFAT = 'Sifat/khabar mengikuti mubtada dalam mudzakkar-muannats.';
const ISYARAH = 'هذا untuk mudzakkar, هذه untuk muannats.';
const FIIL_GENDER = "Fi'il mengikuti fa'il: mudzakkar يـ/ـَ, muannats تـ/ـتْ.";
const DHAMIR = "Prefiks mudhari mengikuti dhamir: أنا أـ, نحن نـ, أنتَ تـ, هو يـ.";

export const easyErrors: ErrorFixTuple[] = [
  ['أنا طالبة جيد.', 'أنا طالبة جيدة.', 'Saya siswi yang baik.', 'Kesesuaian jenis', SIFAT, ['أنا طالب جيدة.', 'أنا طالبة جيدون.']],
  ['البيت قريبة من المدرسة.', 'البيت قريب من المدرسة.', 'Rumah itu dekat dari sekolah.', 'Kesesuaian jenis', SIFAT, ['البيت قريبون من المدرسة.', 'بيت قريبة من المدرسة.']],
  ['ذهبت الطالب إلى الفصل.', 'ذهب الطالب إلى الفصل.', 'Siswa itu pergi ke kelas.', "Fi'il-fa'il", FIIL_GENDER, ['ذهبوا الطالب إلى الفصل.', 'ذهبتا الطالب إلى الفصل.']],
  ['هذا سيارة جديدة.', 'هذه سيارة جديدة.', 'Ini mobil baru.', 'Isim isyarah', ISYARAH, ['هذه سيارة جديد.', 'هذا سيارة جديد.']],
  ['هذه كتاب مفيد.', 'هذا كتاب مفيد.', 'Ini buku yang bermanfaat.', 'Isim isyarah', ISYARAH, ['هذا كتاب مفيدة.', 'هذه كتاب مفيدة.']],
  ['الشمس مشرق.', 'الشمس مشرقة.', 'Matahari bersinar.', 'Kesesuaian jenis', 'الشمس termasuk muannats.', ['الشمس مشرقون.', 'شمس مشرق.']],
  ['فاطمة يكتب الدرس.', 'فاطمة تكتب الدرس.', 'Fatimah menulis pelajaran.', "Fi'il-fa'il", FIIL_GENDER, ['فاطمة يكتبن الدرس.', 'فاطمة نكتب الدرس.']],
  ['أحمد تقرأ الكتاب.', 'أحمد يقرأ الكتاب.', 'Ahmad membaca buku.', "Fi'il-fa'il", FIIL_GENDER, ['أحمد تقرئين الكتاب.', 'أحمد يقرؤون الكتاب.']],
  ['المدرسة كبير.', 'المدرسة كبيرة.', 'Sekolah itu besar.', 'Kesesuaian jenis', SIFAT, ['المدرسة كبار.', 'مدرسة كبير.']],
  ['أنا يذهب إلى السوق.', 'أنا أذهب إلى السوق.', 'Saya pergi ke pasar.', 'Dhamir', DHAMIR, ['أنا تذهب إلى السوق.', 'أنا نذهب إلى السوق.']],
  ['نحن أدرس في الجامعة.', 'نحن ندرس في الجامعة.', 'Kami belajar di universitas.', 'Dhamir', DHAMIR, ['نحن يدرس في الجامعة.', 'نحن تدرسين في الجامعة.']],
  ['هو طويلة.', 'هو طويل.', 'Dia (lk) tinggi.', 'Kesesuaian jenis', SIFAT, ['هي طويل.', 'هو طوال.']],
  ['هي معلم في المدرسة.', 'هي معلمة في المدرسة.', 'Dia (pr) seorang guru di sekolah.', 'Kesesuaian jenis', SIFAT, ['هو معلمة في المدرسة.', 'هي معلمون في المدرسة.']],
  ['الولد صغيرة.', 'الولد صغير.', 'Anak laki-laki itu kecil.', 'Kesesuaian jenis', SIFAT, ['الولد صغار.', 'ولد صغيرة.']],
  ['الغرفة نظيف.', 'الغرفة نظيفة.', 'Kamar itu bersih.', 'Kesesuaian jenis', SIFAT, ['الغرفة نظاف.', 'غرفة نظيف.']],
  ['أنتَ تكتبين رسالة.', 'أنتَ تكتب رسالة.', 'Kamu (lk) menulis surat.', 'Dhamir', DHAMIR, ['أنتَ يكتب رسالة.', 'أنتَ أكتب رسالة.']],
  ['البنت جميل.', 'البنت جميلة.', 'Anak perempuan itu cantik.', 'Kesesuaian jenis', SIFAT, ['البنت جميلون.', 'بنت جميل.']],
  ['هذا مدرسة.', 'هذه مدرسة.', 'Ini sekolah.', 'Isim isyarah', ISYARAH, ['هذه مدرس.', 'هؤلاء مدرسة.']],
  ['القلم على الطاولة الطويل.', 'القلم على الطاولة الطويلة.', 'Pulpen ada di atas meja yang panjang.', "Na'at", "Na'at mengikuti man'ut dalam jenis.", ['القلم على طاولة الطويلة.', 'القلم على الطاولة الطوال.']],
  ['الكلب كبيرة.', 'الكلب كبير.', 'Anjing itu besar.', 'Kesesuaian jenis', SIFAT, ['الكلب كبار.', 'كلب كبيرة.']],
  ['هم يلعب في الحديقة.', 'هم يلعبون في الحديقة.', 'Mereka bermain di taman.', 'Dhamir', 'هم memakai يـ + ـون.', ['هم يلعبان في الحديقة.', 'هم تلعب في الحديقة.']],
  ['أمي يطبخ في المطبخ.', 'أمي تطبخ في المطبخ.', 'Ibuku memasak di dapur.', "Fi'il-fa'il", FIIL_GENDER, ['أمي طبخوا في المطبخ.', 'أمي يطبخون في المطبخ.']],
  ['هذه بيتي.', 'هذا بيتي.', 'Ini rumahku.', 'Isim isyarah', ISYARAH, ['هؤلاء بيتي.', 'هذان بيتي.']],
  ['أنا من إندونيسية.', 'أنا من إندونيسيا.', 'Saya dari Indonesia.', 'Nama negara', 'Setelah من gunakan nama negara, bukan nisbah.', ['أنا إندونيسيا.', 'أنا من الإندونيسي.']],
  ['المعلمة جاء أمس.', 'المعلمة جاءت أمس.', 'Guru (pr) itu datang kemarin.', "Fi'il-fa'il", FIIL_GENDER, ['المعلمة جاؤوا أمس.', 'المعلمة جئتُ أمس.']],
  ['السيارة سريع.', 'السيارة سريعة.', 'Mobil itu cepat.', 'Kesesuaian jenis', SIFAT, ['السيارة سراع.', 'سيارة سريع.']],
  ['أنتِ تذهب إلى الجامعة.', 'أنتِ تذهبين إلى الجامعة.', 'Kamu (pr) pergi ke kampus.', 'Dhamir', 'أنتِ memakai تـ + ـين.', ['أنتِ يذهب إلى الجامعة.', 'أنتِ تذهبون إلى الجامعة.']],
  ['الطالبات مجتهد.', 'الطالبات مجتهدات.', 'Para siswi itu rajin.', 'Kesesuaian jumlah', 'Khabar mengikuti mubtada jamak muannats.', ['الطالبات مجتهدون.', 'الطالبات مجتهدان.']],
  ['عندي قلمان أحمر.', 'عندي قلمان أحمران.', 'Saya punya dua pulpen merah.', 'Mutsanna', "Na'at untuk mutsanna juga mutsanna.", ['عندي قلمين أحمرين.', 'عندي قلمان حمراء.']],
  ['هذا التفاحة حلوة.', 'هذه التفاحة حلوة.', 'Apel ini manis.', 'Isim isyarah', ISYARAH, ['هذه التفاحة حلو.', 'هذا التفاحة حلو.']],
];

export const mediumErrors: ErrorFixTuple[] = [
  ['ذهبوا الطلاب إلى المدرسة.', 'ذهب الطلاب إلى المدرسة.', 'Para siswa pergi ke sekolah.', "Fi'il di depan", "Fi'il di depan fa'il jamak tetap mufrad.", ['ذهبا الطلاب إلى المدرسة.', 'ذهبن الطلاب إلى المدرسة.']],
  ['الكتاب الطالب على المكتب.', 'كتاب الطالب على المكتب.', 'Buku siswa itu ada di atas meja.', 'Idhafah', 'Mudhaf tidak memakai ال.', ['الكتب الطالب على المكتب.', 'الكتاب طالب على المكتب.']],
  ['رأيت ثلاثة طالبات.', 'رأيت ثلاث طالبات.', 'Saya melihat tiga siswi.', "'Adad", 'Bilangan 3–10 berlawanan jenis dengan ma’dud.', ['رأيت ثلاث طالبة.', 'رأيت ثلاثة طالبة.']],
  ['عندي خمس كتب.', 'عندي خمسة كتب.', 'Saya punya lima buku.', "'Adad", 'Bilangan 3–10 berlawanan jenis dengan ma’dud.', ['عندي خمسة كتاب.', 'عندي خمس كتاب.']],
  ['الطالبان مجتهدون.', 'الطالبان مجتهدان.', 'Kedua siswa itu rajin.', 'Mutsanna', 'Khabar untuk mutsanna juga mutsanna.', ['الطالبان مجتهد.', 'الطالبين مجتهدان.']],
  ['كان الجو جميل.', 'كان الجو جميلا.', 'Cuacanya indah.', 'Kana', 'Khabar كان manshub.', ['كانت الجو جميلا.', 'كان الجو جميلة.']],
  ['إنّ الطالبُ مجتهدٌ.', 'إنّ الطالبَ مجتهدٌ.', 'Sesungguhnya siswa itu rajin.', 'Inna', 'Isim إنّ manshub, khabarnya marfu’.', ['إنّ الطالبَ مجتهدًا.', 'إنّ الطالبِ مجتهدٌ.']],
  ['المعلمون يشرح الدرس.', 'المعلمون يشرحون الدرس.', 'Para guru menjelaskan pelajaran.', 'Kesesuaian jumlah', "Fi'il setelah fa'il jamak ikut jamak.", ['المعلمون يشرحان الدرس.', 'المعلمون تشرح الدرس.']],
  ['هؤلاء طالب مجتهد.', 'هؤلاء طلاب مجتهدون.', 'Mereka ini siswa-siswa yang rajin.', 'Isim isyarah', 'هؤلاء untuk jamak berakal.', ['هذا طلاب مجتهدون.', 'هؤلاء طلاب مجتهد.']],
  ['لا تذهبون إلى السوق.', 'لا تذهبوا إلى السوق.', 'Jangan pergi ke pasar (kalian).', 'Nahi', 'لا nahiyah menjazmkan: nun af’al khamsah dibuang.', ['لا اذهبوا إلى السوق.', 'لا تذهبين إلى السوق.']],
  ['لم يذهبون إلى العمل.', 'لم يذهبوا إلى العمل.', 'Mereka tidak pergi bekerja.', 'Jazm', 'لم menjazmkan: nun af’al khamsah dibuang.', ['لم ذهبوا إلى العمل.', 'لن يذهبون إلى العمل.']],
  ['الكتب الجديد في المكتبة.', 'الكتب الجديدة في المكتبة.', 'Buku-buku baru ada di perpustakaan.', "Na'at", 'Jamak tak berakal disifati mufrad muannats.', ['الكتب الجدد في المكتبة.', 'الكتب جديد في المكتبة.']],
  ['ذهبت إلى المدرسة مع أصدقائي الأمس.', 'ذهبت إلى المدرسة مع أصدقائي أمس.', 'Saya pergi ke sekolah bersama teman-temanku kemarin.', 'Zharf', 'أمس sebagai keterangan waktu tidak memakai ال.', ['ذهبت إلى مدرسة مع الأصدقائي أمس.', 'ذهبت في المدرسة مع أصدقائي أمس.']],
  ['هذه المهندسون ماهرون.', 'هؤلاء المهندسون ماهرون.', 'Para insinyur ini terampil.', 'Isim isyarah', 'هؤلاء untuk jamak berakal.', ['هذان المهندسون ماهرون.', 'هؤلاء المهندسون ماهر.']],
  ['البنات يلعبون في الحديقة.', 'البنات يلعبن في الحديقة.', 'Anak-anak perempuan bermain di taman.', 'Kesesuaian jumlah', 'Jamak muannats memakai يـ + ـنَ.', ['البنات يلعب في الحديقة.', 'البنات يلعبان في الحديقة.']],
  ['أريد أن أذهبُ إلى البيت.', 'أريد أن أذهبَ إلى البيت.', 'Saya ingin pergi ke rumah.', 'Nashb', 'أن menashabkan fi’il mudhari.', ['أريد أن ذهبتُ إلى البيت.', 'أريد أن اذهبْ إلى البيت.']],
  ['السيارات سريعون.', 'السيارات سريعة.', 'Mobil-mobil itu cepat.', 'Jamak tak berakal', 'Jamak tak berakal diberi khabar mufrad muannats.', ['السيارات سريع.', 'السيارات سريعتان.']],
  ['أنتم تدرسين كثيرا.', 'أنتم تدرسون كثيرا.', 'Kalian banyak belajar.', 'Dhamir', 'أنتم memakai تـ + ـون.', ['أنتم يدرسون كثيرا.', 'أنتم ندرس كثيرا.']],
  ['ذهبت إلى المكتبة لأقرأ كتاب.', 'ذهبت إلى المكتبة لأقرأ كتابا.', 'Saya pergi ke perpustakaan untuk membaca sebuah buku.', "Maf'ul bih", "Maf'ul bih nakirah manshub: كتابًا.", ['ذهبت إلى المكتبة لأقرأ الكتابا.', 'ذهبت إلى المكتبة لقرأت كتابا.']],
  ['قرأت عشرة كتابا.', 'قرأت عشرة كتب.', 'Saya membaca sepuluh buku.', "'Adad", 'Bilangan 3–10 + jamak majrur.', ['قرأت عشر كتب.', 'قرأت عشرة كتاب.']],
  ['الطالبتان ذهبوا إلى المكتبة.', 'الطالبتان ذهبتا إلى المكتبة.', 'Kedua siswi itu pergi ke perpustakaan.', 'Mutsanna', 'Madhi untuk mutsanna muannats: ذهبتا.', ['الطالبتان ذهبا إلى المكتبة.', 'الطالبتان ذهبن إلى المكتبة.']],
  ['جاء المعلمة إلى الفصل.', 'جاءت المعلمة إلى الفصل.', 'Guru (pr) itu datang ke kelas.', "Fi'il-fa'il", FIIL_GENDER, ['جاءوا المعلمة إلى الفصل.', 'جئتُ المعلمة إلى الفصل.']],
  ['هذا الطالب الذين نجح.', 'هذا الطالب الذي نجح.', 'Inilah siswa yang lulus itu.', 'Ism maushul', 'الذي untuk mufrad mudzakkar.', ['هذا الطالب التي نجح.', 'هذا الطالب اللذان نجح.']],
  ['هذه البنت الذي تدرس معي.', 'هذه البنت التي تدرس معي.', 'Inilah anak perempuan yang belajar bersamaku.', 'Ism maushul', 'التي untuk mufrad muannats.', ['هذه البنت الذين تدرس معي.', 'هذا البنت التي تدرس معي.']],
  ['كانوا الطلاب في الفصل.', 'كان الطلاب في الفصل.', 'Para siswa ada di kelas.', 'Kana', "كان di depan isim jamak tetap mufrad.", ['كانا الطلاب في الفصل.', 'كنّ الطلاب في الفصل.']],
  ['ليس الجو بارد.', 'ليس الجو باردا.', 'Cuacanya tidak dingin.', 'Laysa', 'Khabar ليس manshub.', ['ليست الجو باردا.', 'ليس الجو باردة.']],
  ['أصبح الطالب نشيط.', 'أصبح الطالب نشيطا.', 'Siswa itu menjadi bersemangat.', 'Ashbaha', 'Khabar أصبح manshub.', ['أصبحت الطالب نشيطا.', 'أصبح الطالب نشيطة.']],
  ['رأيت المعلمون في المسجد.', 'رأيت المعلمين في المسجد.', 'Saya melihat para guru di masjid.', "Maf'ul bih", 'Jamak mudzakkar salim manshub memakai ـين.', ['رأيت المعلمان في المسجد.', 'رأيت معلمون في المسجد.']],
  ['سلمت على المهندسون.', 'سلمت على المهندسين.', 'Saya menyalami para insinyur.', 'Majrur', 'Setelah huruf jar, jamak mudzakkar salim memakai ـين.', ['سلمت على مهندسون.', 'سلمت إلى المهندسون.']],
  ['هذان طالبتان مجتهدتان.', 'هاتان طالبتان مجتهدتان.', 'Ini dua siswi yang rajin.', 'Isim isyarah', 'هاتان untuk mutsanna muannats.', ['هاتان طالبان مجتهدتان.', 'هذان طالبتان مجتهدان.']],
];

export const hardErrors: ErrorFixTuple[] = [
  ['إنّ المسلمون إخوةٌ.', 'إنّ المسلمين إخوةٌ.', 'Sesungguhnya kaum muslimin bersaudara.', 'Inna', 'Isim إنّ manshub: jamak mudzakkar memakai ـين.', ['إنّ المسلمان إخوةٌ.', 'إنّ المسلمون إخوةً.']],
  ['كان المهندسان ماهران.', 'كان المهندسان ماهرين.', 'Kedua insinyur itu terampil.', 'Kana', 'Khabar كان manshub: mutsanna memakai ـين.', ['كان المهندسين ماهرين.', 'كانا المهندسان ماهرين.']],
  ['لن تنجحون إلا بالعمل.', 'لن تنجحوا إلا بالعمل.', 'Kalian tidak akan berhasil kecuali dengan kerja.', 'Nashb', 'لن menashabkan: nun af’al khamsah dibuang.', ['لن نجحتم إلا بالعمل.', 'لم تنجحون إلا بالعمل.']],
  ['في الفصل خمسة عشر طالب.', 'في الفصل خمسة عشر طالبا.', 'Di kelas ada lima belas siswa.', 'Tamyiz', 'Tamyiz bilangan 11–99 mufrad manshub.', ['في الفصل خمس عشرة طالبا.', 'في الفصل خمسة عشر طلاب.']],
  ['مررت بفاطمةٍ.', 'مررت بفاطمةَ.', 'Saya melewati Fatimah.', "Mamnu' minash-sharf", 'Nama muannats tidak bertanwin; majrurnya dengan fathah.', ['مررت بفاطمةً.', 'مررت لفاطمةَ.']],
  ['صلّيت في مساجدٍ كثيرةٍ.', 'صلّيت في مساجدَ كثيرةٍ.', 'Saya shalat di banyak masjid.', "Mamnu' minash-sharf", 'Wazan مَفَاعِل tidak bertanwin; majrurnya dengan fathah.', ['صلّيت في مساجدٌ كثيرةٍ.', 'صلّيت في مسجدُ كثيرةٍ.']],
  ['حضروا الطالبات المؤتمر.', 'حضرت الطالبات المؤتمر.', 'Para siswi menghadiri konferensi.', "Fi'il di depan", "Fi'il di depan fa'il muannats: mufrad muannats.", ['حضرن الطالبات المؤتمر.', 'حضرتا الطالبات المؤتمر.']],
  ['رجع المسافر فرحٌ.', 'رجع المسافر فرحًا.', 'Musafir itu pulang dengan gembira.', 'Hal', 'Hal manshub.', ['رجع المسافر فرحٍ.', 'رجع المسافرَ فرحًا.']],
  ['أبوك رجلٌ كريمٌ وأنا أحترم أبوك.', 'أبوك رجلٌ كريمٌ وأنا أحترم أباك.', 'Ayahmu orang mulia dan aku menghormati ayahmu.', "Asma' khamsah", "Asma' khamsah manshub dengan alif: أباك.", ['أبوك رجلٌ كريمٌ وأنا أحترم أبيك.', 'أبوك رجلٌ كريمٌ وأنا أحترم أبٌ.']],
  ['سلّمت على أخوك.', 'سلّمت على أخيك.', 'Saya menyalami saudaramu.', "Asma' khamsah", "Asma' khamsah majrur dengan ya: أخيك.", ['سلّمت على أخاك.', 'سلّمت على أخٌ.']],
  ['كُتِبَ الطالبُ الدرسَ.', 'كَتَبَ الطالبُ الدرسَ.', 'Siswa itu menulis pelajaran.', "Ma'lum-majhul", "Ada fa'il dan maf'ul: gunakan fi'il ma'lum.", ['كَتَبَ الطالبَ الدرسُ.', 'يُكتَبُ الطالبُ الدرسَ.']],
  ['فُتِحَ البابَ.', 'فُتِحَ البابُ.', 'Pintu itu dibuka.', "Naib fa'il", "Naib fa'il marfu'.", ['فُتِحَ البابِ.', 'فُتِحَتِ البابُ.']],
  ['ما زال الجو باردٌ.', 'ما زال الجو باردًا.', 'Cuacanya masih dingin.', 'Ma zala', 'Khabar ما زال manshub.', ['ما زالت الجو باردًا.', 'ما زال الجوَ باردًا.']],
  ['الطالب الذي نجحوا مسرور.', 'الطالب الذي نجح مسرور.', 'Siswa yang lulus itu senang.', 'Shilah', 'Shilah mengikuti ism maushul mufrad.', ['الطالب الذين نجح مسرور.', 'الطالب التي نجحت مسرور.']],
  ['هؤلاء النساء الذين يعملن في المستشفى.', 'هؤلاء النساء اللاتي يعملن في المستشفى.', 'Mereka adalah para wanita yang bekerja di rumah sakit.', 'Ism maushul', 'اللاتي untuk jamak muannats.', ['هؤلاء النساء التي يعملن في المستشفى.', 'هؤلاء النساء اللاتي يعملون في المستشفى.']],
  ['إن تدرسْ تنجحُ.', 'إن تدرسْ تنجحْ.', 'Jika kamu belajar, kamu berhasil.', 'Jazm', 'Jawab syarat إنْ juga majzum.', ['إن تدرسُ تنجحْ.', 'إن درستَ تنجحون.']],
  ['لم يأكلْ أحمدُ شيءٌ.', 'لم يأكلْ أحمدُ شيئًا.', 'Ahmad tidak makan apa pun.', "Maf'ul bih", "Maf'ul bih manshub.", ['لم يأكلُ أحمدُ شيئًا.', 'لم يأكلْ أحمدَ شيئًا.']],
  ['رأيت عشرين رجلٌ.', 'رأيت عشرين رجلًا.', 'Saya melihat dua puluh pria.', 'Tamyiz', 'Tamyiz bilangan 11–99 mufrad manshub.', ['رأيت عشرون رجلًا.', 'رأيت عشرين رجالًا.']],
  ['كانت السماءُ صافيةٌ.', 'كانت السماءُ صافيةً.', 'Langit itu cerah.', 'Kana', 'Khabar كان manshub.', ['كان السماءُ صافيةً.', 'كانت السماءَ صافيةً.']],
  ['لعلّ الطالبُ ناجحٌ.', 'لعلّ الطالبَ ناجحٌ.', 'Semoga siswa itu lulus.', 'Inna wa akhawatuha', 'Isim لعلّ manshub, khabarnya marfu’.', ['لعلّ الطالبَ ناجحًا.', 'لعلّ الطالبِ ناجحٌ.']],
  ['الطلاب لم يحضرون الدرس.', 'الطلاب لم يحضروا الدرس.', 'Para siswa tidak menghadiri pelajaran.', 'Jazm', 'لم menjazmkan: nun af’al khamsah dibuang.', ['الطلاب لم حضروا الدرس.', 'الطلاب لن يحضرون الدرس.']],
  ['أعطيت الفقير درهمان.', 'أعطيت الفقيرَ درهمين.', 'Saya memberi orang fakir itu dua dirham.', "Maf'ul bih", "Maf'ul bih mutsanna manshub memakai ـين.", ['أعطيت الفقيرُ درهمين.', 'أعطيت الفقيرَ درهمٌ.']],
  ['الطالبات المجتهدون نجحن.', 'الطالبات المجتهدات نجحن.', 'Para siswi yang rajin itu lulus.', "Na'at", "Na'at mengikuti man'ut jamak muannats.", ['الطالبات المجتهدات نجحوا.', 'الطالبات المجتهدين نجحن.']],
  ['هذه الأقلام جديدون.', 'هذه الأقلام جديدة.', 'Pulpen-pulpen ini baru.', 'Jamak tak berakal', 'Jamak tak berakal diberi khabar mufrad muannats.', ['هؤلاء الأقلام جديدة.', 'هذه الأقلام جدد.']],
  ['جاء المسافرين متأخرين.', 'جاء المسافرون متأخرين.', 'Para musafir datang terlambat.', "Fa'il", "Fa'il jamak mudzakkar salim marfu' memakai ـون.", ['جاء المسافرون متأخرون.', 'جاؤوا المسافرون متأخرين.']],
  ['يجب أن يذهبون الآن.', 'يجب أن يذهبوا الآن.', 'Mereka harus pergi sekarang.', 'Nashb', 'أن menashabkan: nun af’al khamsah dibuang.', ['يجب أن ذهبوا الآن.', 'يجب أن تذهبون الآن.']],
  ['ليت الوقتُ طويلٌ.', 'ليت الوقتَ طويلٌ.', 'Seandainya waktunya panjang.', 'Inna wa akhawatuha', 'Isim ليت manshub, khabarnya marfu’.', ['ليت الوقتَ طويلًا.', 'ليت الوقتِ طويلٌ.']],
  ['عندي إحدى عشر قلمًا.', 'عندي أحد عشر قلمًا.', 'Saya punya sebelas pulpen.', "'Adad", '11–12 sesuai jenis ma’dud: أحد عشر untuk mudzakkar.', ['عندي أحد عشرة قلمًا.', 'عندي أحد عشر أقلامًا.']],
  ['ظنّ أحمدُ الامتحانُ سهلٌ.', 'ظنّ أحمدُ الامتحانَ سهلًا.', 'Ahmad mengira ujian itu mudah.', 'Zhanna', 'ظنّ menashabkan dua maf’ul.', ['ظنّ أحمدُ الامتحانُ سهلًا.', 'ظنّ أحمدَ الامتحانَ سهلًا.']],
  ['أصبح الطلاب المجتهدون ناجحون.', 'أصبح الطلاب المجتهدون ناجحين.', 'Para siswa yang rajin itu menjadi orang-orang yang berhasil.', 'Ashbaha', 'Khabar أصبح manshub: jamak memakai ـين.', ['أصبح الطلاب المجتهدين ناجحين.', 'أصبحوا الطلاب المجتهدون ناجحين.']],
];
