// Fi'il Master and Sharaf Forms banks, 30 unique items per level.
export type TenseTuple = [prompt: string, translation: string, answer: string, wrong: string[], tense: string, formula: string];

const MUDHARI = "fi'il mudhari untuk kegiatan sekarang/kebiasaan";
const MADHI = "fi'il madhi untuk masa lalu";
const AMR = "fi'il amr untuk perintah";

export const easyTense: TenseTuple[] = [
  ['أنا ____ العربية الآن.', 'Saya sedang belajar bahasa Arab sekarang.', 'أتعلم', ['تعلّمْ', 'يتعلمون', 'تعلمنا'], 'Mudhari', MUDHARI],
  ['هو ____ إلى المدرسة أمس.', 'Dia pergi ke sekolah kemarin.', 'ذهب', ['يذهب', 'اذهب', 'سيذهب'], 'Madhi', MADHI],
  ['____ الكتاب يا أحمد.', 'Bacalah buku itu, Ahmad.', 'اقرأ', ['قرأ', 'يقرأ', 'سيقرأ'], 'Amr', AMR],
  ['نحن ____ الأرز كل يوم.', 'Kami makan nasi setiap hari.', 'نأكل', ['أكلَ', 'كُلْ', 'يأكلون'], 'Mudhari', 'prefiks نـ untuk نحن'],
  ['هي ____ رسالة أمس.', 'Dia (pr) menulis surat kemarin.', 'كتبت', ['يكتب', 'اكتبي', 'نكتب'], 'Madhi', 'madhi muannats memakai ـتْ'],
  ['____ الباب من فضلك.', 'Tolong buka pintunya.', 'افتح', ['فتح', 'يفتح', 'فتحنا'], 'Amr', AMR],
  ['أنا ____ في الساعة السادسة كل يوم.', 'Saya bangun pukul enam setiap hari.', 'أستيقظ', ['استيقظَ', 'تستيقظون', 'استيقظنا'], 'Mudhari', 'prefiks أ untuk أنا'],
  ['هم ____ كرة القدم أمس.', 'Mereka bermain sepak bola kemarin.', 'لعبوا', ['يلعب', 'العب', 'ألعب'], 'Madhi', 'madhi jamak memakai ـوا'],
  ['أنتَ ____ القهوة الآن.', 'Kamu sedang minum kopi sekarang.', 'تشرب', ['شربتُ', 'اشربوا', 'يشربون'], 'Mudhari', 'prefiks تـ untuk أنتَ'],
  ['____ يا فاطمة.', 'Duduklah, Fatimah.', 'اجلسي', ['جلس', 'يجلس', 'اجلسوا'], 'Amr', 'amr muannats memakai ـي'],
  ['أبي ____ في المكتب كل يوم.', 'Ayahku bekerja di kantor setiap hari.', 'يعمل', ['أعمل', 'اعملْ', 'عملنا'], 'Mudhari', 'prefiks يـ untuk هو'],
  ['نحن ____ إلى مكة السنة الماضية.', 'Kami pergi ke Mekah tahun lalu.', 'سافرنا', ['نسافر', 'سافِرْ', 'يسافرون'], 'Madhi', 'madhi نحن memakai ـنا'],
  ['الطالب ____ الدرس الآن.', 'Siswa itu sedang menulis pelajaran sekarang.', 'يكتب', ['كتبنا', 'اكتبْ', 'يكتبون'], 'Mudhari', MUDHARI],
  ['____ الماء يا ولد.', 'Minumlah air, Nak.', 'اشرب', ['شرب', 'يشربون', 'شربنا'], 'Amr', AMR],
  ['أنا ____ الواجب أمس.', 'Saya menyelesaikan PR kemarin.', 'أنهيتُ', ['أُنهي', 'أنهِ', 'ينهون'], 'Madhi', 'madhi أنا memakai ـتُ'],
  ['هي ____ في المطبخ الآن.', 'Dia (pr) sedang memasak di dapur sekarang.', 'تطبخ', ['طبخَ', 'اطبخْ', 'يطبخون'], 'Mudhari', 'prefiks تـ untuk هي'],
  ['____ إلى السبورة يا علي.', 'Lihatlah papan tulis, Ali.', 'انظر', ['نظر', 'ينظر', 'نظرنا'], 'Amr', AMR],
  ['أنتم ____ القرآن كل يوم.', "Kalian membaca Al-Qur'an setiap hari.", 'تقرؤون', ['قرأتُ', 'اقرأ', 'يقرأ'], 'Mudhari', 'تـ + ـون untuk أنتم'],
  ['ذهب أحمد إلى السوق و____ خبزا.', 'Ahmad pergi ke pasar dan membeli roti.', 'اشترى', ['يشتري', 'اشترِ', 'أشتري'], 'Madhi', 'rangkaian kejadian lampau memakai madhi'],
  ['أنا ____ التلفاز الآن.', 'Saya sedang menonton TV sekarang.', 'أشاهد', ['شاهدنا', 'شاهِدْ', 'يشاهدون'], 'Mudhari', MUDHARI],
  ['أختي ____ في الجامعة.', 'Kakak perempuanku kuliah di universitas.', 'تدرس', ['يدرس', 'ادرسي', 'درسنا'], 'Mudhari', "fi'il mengikuti fa'il muannats"],
  ['الأولاد ____ في الحديقة الآن.', 'Anak-anak sedang bermain di taman sekarang.', 'يلعبون', ['لعبتُ', 'العبْ', 'ألعب'], 'Mudhari', 'يـ + ـون untuk jamak mudzakkar'],
  ['أمس ____ الطبيب المريض.', 'Kemarin dokter memeriksa pasien itu.', 'فحص', ['يفحص', 'افحص', 'فحصنا'], 'Madhi', MADHI],
  ['____ يدك قبل الأكل.', 'Cucilah tanganmu sebelum makan.', 'اغسل', ['غسل', 'يغسل', 'غسلنا'], 'Amr', AMR],
  ['هما ____ الدرس معا كل مساء.', 'Mereka berdua mengulang pelajaran bersama setiap sore.', 'يراجعان', ['راجعنا', 'راجِعْ', 'أراجع'], 'Mudhari', 'يـ + ـان untuk mutsanna'],
  ['أنتِ ____ بسرعة.', 'Kamu (pr) berjalan dengan cepat.', 'تمشين', ['مشى', 'يمشي', 'امشِ'], 'Mudhari', 'تـ + ـين untuk أنتِ'],
  ['أنا ____ صديقي في المسجد أمس.', 'Saya bertemu temanku di masjid kemarin.', 'قابلتُ', ['أقابل', 'قابِلْ', 'يقابلون'], 'Madhi', 'madhi أنا memakai ـتُ'],
  ['المحل ____ في الساعة التاسعة كل صباح.', 'Toko itu buka pukul sembilan setiap pagi.', 'يفتح', ['فتحتُ', 'افتحْ', 'فتحنا'], 'Mudhari', MUDHARI],
  ['____ الدرس جيدا يا طلاب.', 'Pahamilah pelajaran dengan baik, para siswa.', 'افهموا', ['فهموا', 'يفهم', 'فهمتُ'], 'Amr', 'amr jamak memakai ـوا'],
  ['هو ____ الآن.', 'Dia sedang tidur sekarang.', 'ينام', ['نامَ', 'نَمْ', 'ننام'], 'Mudhari', MUDHARI],
];

export const mediumTense: TenseTuple[] = [
  ['سوف ____ غدا.', 'Saya akan datang besok.', 'آتي', ['أتيتُ', 'تعالَ', 'جاء'], 'Mustaqbal', 'سوف + mudhari'],
  ['نحن ____ الدرس كل يوم.', 'Kami mempelajari pelajaran setiap hari.', 'ندرس', ['درسنا', 'ادرس', 'يدرس'], 'Mudhari', 'prefiks نـ untuk نحن'],
  ['سارة ____ الرسالة أمس.', 'Sarah menulis pesan kemarin.', 'كتبت', ['تكتب', 'اكتب', 'نكتب'], 'Madhi', 'madhi muannats memakai ـتْ'],
  ['غدا ____ إلى جاكرتا.', 'Besok kami akan pergi ke Jakarta.', 'سنسافر', ['سافرنا', 'سافِرْ', 'سيسافرون'], 'Mustaqbal', 'سـ + mudhari'],
  ['أنا ____ اللحم.', 'Saya tidak makan daging (kebiasaan).', 'لا آكل', ['لن آكل', 'ما أكلتُ', 'لا تأكل'], 'Nafi', 'nafi mudhari untuk kebiasaan'],
  ['أمس ____ إلى العمل لأني كنت مريضا.', 'Kemarin saya tidak pergi bekerja karena sakit.', 'لم أذهب', ['لا أذهب', 'لن أذهب', 'لا تذهب'], 'Nafi', 'nafi masa lalu: huruf jazm + mudhari'],
  ['____ أنسى هذا اليوم أبدا.', 'Saya tidak akan pernah melupakan hari ini.', 'لن', ['لم', 'ما', 'ليس'], 'Nafi', 'nafi masa depan + mudhari manshub'],
  ['الطالبات ____ في المكتبة الآن.', 'Para siswi sedang belajar di perpustakaan sekarang.', 'يدرسن', ['يدرسون', 'درسَ', 'ادرسن'], 'Mudhari', 'يـ + ـنَ untuk jamak muannats'],
  ['الطالبان ____ الكتاب معا.', 'Kedua siswa membaca buku bersama.', 'يقرآن', ['يقرؤون', 'تقرأ', 'قرأتُ'], 'Mudhari', 'يـ + ـان untuk mutsanna'],
  ['الأمهات ____ الطعام للأطفال أمس.', 'Para ibu memasak makanan untuk anak-anak kemarin.', 'طبخن', ['طبخوا', 'يطبخن', 'اطبخن'], 'Madhi', 'madhi jamak muannats memakai ـنَ'],
  ['هل ____ القهوة يا محمد؟', 'Apakah kamu mau minum kopi, Muhammad?', 'تشرب', ['يشربون', 'اشربْ', 'شربنا'], 'Mudhari', 'هل + mudhari untuk bertanya'],
  ['سوف ____ الطائرة بعد ساعة.', 'Pesawat akan lepas landas satu jam lagi.', 'تقلع', ['أقلعت', 'أقلعْ', 'يقلعون'], 'Mustaqbal', 'سوف + mudhari muannats'],
  ['المعلمون ____ الاجتماع غدا.', 'Para guru akan menghadiri rapat besok.', 'سيحضرون', ['حضروا', 'سيحضر', 'احضروا'], 'Mustaqbal', 'سـ + mudhari jamak'],
  ['لا ____ في الفصل يا أولاد.', 'Jangan berbicara di kelas, anak-anak.', 'تتكلموا', ['تكلموا', 'يتكلمون', 'تتكلم'], 'Nahi', 'لا nahiyah + mudhari majzum'],
  ['الأطفال ____ مبكرا الليلة الماضية.', 'Anak-anak tidur lebih awal tadi malam.', 'ناموا', ['ينامون', 'نام', 'نامتا'], 'Madhi', 'madhi jamak memakai ـوا'],
  ['____ السفر غدا.', 'Kami ingin bepergian besok.', 'نريد', ['أرادوا', 'يريد', 'أرِدْ'], 'Mudhari', 'prefiks نـ untuk نحن'],
  ['كان المطر ____ عندما خرجتُ.', 'Hujan sedang turun ketika saya keluar.', 'ينزل', ['نزلوا', 'انزل', 'ننزل'], 'Kana + Mudhari', 'كان + mudhari untuk kejadian berlangsung di masa lalu'],
  ['هي ____ اللغة اليابانية منذ سنتين.', 'Dia (pr) belajar bahasa Jepang sejak dua tahun.', 'تتعلم', ['يتعلم', 'تعلّمي', 'تعلمنا'], 'Mudhari', 'prefiks تـ untuk هي'],
  ['أنتما ____ في نفس الشركة.', 'Kalian berdua bekerja di perusahaan yang sama.', 'تعملان', ['تعملون', 'يعمل', 'اعملا'], 'Mudhari', 'تـ + ـان untuk أنتما'],
  ['ما ____ الطعام بعد.', 'Saya belum makan makanan itu.', 'أكلتُ', ['كُلْ', 'يأكلون', 'سآكل'], 'Nafi', 'ما + madhi untuk menafikan masa lalu'],
  ['هل ____ إلى الحفلة غدا؟', 'Apakah kamu akan datang ke pesta besok?', 'ستأتي', ['أتيتَ', 'تعالَ', 'أتى'], 'Mustaqbal', 'سـ + mudhari'],
  ['الشمس ____ من الشرق.', 'Matahari terbit dari timur.', 'تشرق', ['يشرق', 'أشرقتُ', 'أشرقْ'], 'Mudhari', 'الشمس muannats: تـ'],
  ['لن ____ قبل أن ننهي العمل.', 'Kami tidak akan pulang sebelum menyelesaikan pekerjaan.', 'نرجع', ['رجعنا', 'يرجعون', 'ارجع'], 'Nafi', 'لن + mudhari manshub'],
  ['المهندسات ____ المشروع الأسبوع الماضي.', 'Para insinyur perempuan menyelesaikan proyek minggu lalu.', 'أنهين', ['أنهوا', 'ينهين', 'أنهى'], 'Madhi', 'madhi jamak muannats memakai ـنَ'],
  ['لم ____ الفيلم بعد.', 'Saya belum menonton film itu.', 'أشاهد', ['شاهدتُ', 'شاهِدوا', 'سأشاهد'], 'Nafi', 'لم + mudhari majzum'],
  ['الولدان ____ في الحديقة أمس.', 'Kedua anak laki-laki itu bermain di taman kemarin.', 'لعبا', ['لعبوا', 'يلعبان', 'العبا'], 'Madhi', 'madhi mutsanna memakai ـا'],
  ['سوف ____ الطلاب نتائج الامتحان الأسبوع القادم.', 'Para siswa akan menerima hasil ujian minggu depan.', 'يستلم', ['استلم', 'استلمْ', 'نستلم'], 'Mustaqbal', "fi'il di depan fa'il jamak tetap mufrad"],
  ['كان أبي ____ الجريدة كل صباح.', 'Ayahku dulu membaca koran setiap pagi.', 'يقرأ', ['قرأتُ', 'اقرأ', 'يقرؤون'], 'Kana + Mudhari', 'كان + mudhari untuk kebiasaan masa lalu'],
  ['____ يا بني.', 'Jangan berbohong, anakku.', 'لا تكذب', ['لا يكذب', 'لن تكذب', 'لم تكذب'], 'Nahi', 'larangan: huruf nahi + mudhari majzum'],
  ['أنتنّ ____ بجد.', 'Kalian (pr) belajar dengan sungguh-sungguh.', 'تدرسن', ['تدرسون', 'يدرس', 'درسنا'], 'Mudhari', 'تـ + ـنَ untuk أنتنّ'],
];

export const hardTense: TenseTuple[] = [
  ['لو ____ الوقت لراجعت الدرس.', 'Seandainya ada waktu, saya pasti mengulang pelajaran.', 'كان', ['يكون', 'كن', 'كانت'], 'Syarat', 'لو + madhi untuk pengandaian'],
  ['لم ____ السؤال جيدا.', 'Saya belum memahami pertanyaan dengan baik.', 'أفهم', ['فهمت', 'افهم', 'يفهمون'], 'Jazm', 'لم + mudhari majzum'],
  ['كان الطالب ____ في الفصل.', 'Siswa itu sedang menulis di kelas.', 'يكتب', ['يكتبون', 'اكتب', 'مكتوب'], 'Kana + Mudhari', 'كان + mudhari untuk aktivitas berlangsung di masa lalu'],
  ['الدرس ____ على السبورة.', 'Pelajaran itu ditulis di papan tulis.', 'كُتِبَ', ['كَتَبَ', 'يَكْتُبُ', 'اُكْتُبْ'], 'Majhul', "fi'il madhi majhul: فُعِلَ"],
  ['____ الطلاب إلى الجامعة مبكرين.', 'Para siswa pergi ke kampus lebih awal.', 'ذهب', ['ذهبوا', 'ذهبا', 'اذهبوا'], "Fi'il + Fa'il", "fi'il di depan fa'il jamak tetap mufrad"],
  ['يجب أن ____ مبكرا.', 'Kamu harus bangun pagi.', 'تستيقظ', ['استيقظتَ', 'تستيقظون', 'استيقظْ'], 'Nashb', 'أن + mudhari manshub'],
  ['ما زال المطر ____.', 'Hujan masih turun.', 'ينزل', ['نزلوا', 'انزل', 'ينزلون'], 'Ma zala', 'ما زال + mudhari untuk keadaan berlanjut'],
  ['كاد القطار ____ قبل وصولنا.', 'Kereta hampir berangkat sebelum kami tiba.', 'يغادر', ['غادرَ', 'غادرْ', 'سيغادر'], 'Kada', 'كاد + mudhari'],
  ['إنّ العلم ____ الإنسان.', 'Sesungguhnya ilmu mengangkat derajat manusia.', 'يرفع', ['رفعتُ', 'ارفع', 'يرفعون'], 'Inna', 'khabar إنّ berupa jumlah fi’liyah'],
  ['بدأ الأطفال ____ بعد المدرسة.', 'Anak-anak mulai bermain setelah sekolah.', 'يلعبون', ['لعب', 'العبوا', 'يلعب'], 'Syuru', 'بدأ + mudhari mengikuti subjek'],
  ['لمّا ____ إلى البيت، وجدت الباب مفتوحا.', 'Ketika saya sampai di rumah, saya mendapati pintu terbuka.', 'وصلتُ', ['أصل', 'صِلْ', 'سأصل'], 'Lamma', 'لمّا + madhi untuk "ketika"'],
  ['ليتني ____ أكثر في شبابي.', 'Seandainya saja dulu saya belajar lebih banyak di masa muda.', 'درستُ', ['ادرس', 'سأدرس', 'يدرسون'], 'Tamanni', 'ليت + madhi untuk penyesalan masa lalu'],
  ['قد ____ المسافرون قبل قليل.', 'Para musafir baru saja tiba.', 'وصل', ['وصلوا', 'صِلوا', 'سيصلون'], 'Qad + Madhi', 'قد + madhi untuk "baru saja/sudah"'],
  ['إذا ____ الماء إلى مئة درجة غلى.', 'Jika air mencapai seratus derajat, air mendidih.', 'وصل', ['صِلْ', 'وصلتُ', 'واصلْ'], 'Syarat', 'إذا + madhi'],
  ['لن ____ النجاح دون جهد.', 'Kalian tidak akan meraih kesuksesan tanpa usaha.', 'تحققوا', ['تحققون', 'حققتم', 'حققوا'], 'Nashb', 'لن + af’al khamsah membuang nun'],
  ['لم ____ الطالبات الدرس بعد.', 'Para siswi belum memahami pelajaran.', 'تفهم', ['يفهمن', 'فهمت', 'تفهمون'], 'Jazm', "fi'il di depan fa'il muannats tetap mufrad"],
  ['ليس الطالب ____ اليوم.', 'Siswa itu tidak hadir hari ini.', 'حاضرًا', ['حاضرٌ', 'حاضرٍ', 'حضورٌ'], 'Laysa', 'khabar ليس manshub'],
  ['أصبح الجو ____.', 'Cuacanya menjadi dingin.', 'باردًا', ['باردٌ', 'باردٍ', 'بُرودٌ'], 'Ashbaha', 'khabar أصبح manshub'],
  ['كان الطقس ____ أمس.', 'Cuacanya panas kemarin.', 'حارًّا', ['حارٌّ', 'حارٍّ', 'حرارةٌ'], 'Kana', 'khabar كان manshub'],
  ['الكتاب ____ على الرف.', 'Buku itu telah diletakkan di rak.', 'وُضِعَ', ['وَضَعَ', 'يَضَعُ', 'ضَعْ'], 'Majhul', "fi'il madhi majhul: فُعِلَ"],
  ['ما ____ الطالب إلا بالجد.', 'Siswa tidak akan berhasil kecuali dengan kesungguhan.', 'ينجح', ['انجح', 'ينجحون', 'نجحنا'], 'Hashr', 'ما ... إلا untuk pembatasan'],
  ['الرسائل ____ أمس.', 'Surat-surat itu dikirim kemarin.', 'أُرْسِلَتْ', ['أَرْسَلَتْ', 'يُرْسِلُ', 'أُرْسِلُوا'], 'Majhul', 'jamak tak berakal + madhi majhul muannats'],
  ['ادرس كل يوم ____ تنجح.', 'Belajarlah setiap hari agar kamu berhasil.', 'كي', ['لم', 'ما', 'إذا'], 'Nashb', 'huruf nashb untuk tujuan + mudhari'],
  ['إن ____ تنجحْ.', 'Jika kamu belajar, kamu berhasil.', 'تدرسْ', ['تدرسون', 'ادرسْ', 'يدرسان'], 'Jazm', 'إنْ syarthiyah menjazmkan dua fi’il'],
  ['لم يكن الامتحان ____.', 'Ujiannya tidak sulit.', 'صعبًا', ['صعبٌ', 'صعوبةٌ', 'يصعب'], 'Kana', 'khabar يكن manshub'],
  ['ظلّ الحارس ____ طوال الليل.', 'Penjaga itu terus terjaga sepanjang malam.', 'مستيقظًا', ['مستيقظٌ', 'مستيقظٍ', 'يستيقظون'], 'Zhalla', 'khabar ظلّ manshub'],
  ['عسى أن ____ الأمور.', 'Semoga keadaan membaik.', 'تتحسن', ['تحسنت', 'تحسّنْ', 'يتحسنون'], "Raja'", 'عسى أن + mudhari'],
  ['سوف ____ المؤتمر في الشهر القادم.', 'Konferensi itu akan diadakan bulan depan.', 'يُعْقَدُ', ['عُقِدَ', 'يَعْقِدُونَ', 'اِعْقِدْ'], 'Majhul', "fi'il mudhari majhul: يُفْعَلُ"],
  ['ما إن ____ الجرس حتى خرج الطلاب.', 'Begitu bel berbunyi, para siswa keluar.', 'رنَّ', ['رنَّتْ', 'سيرنُّ', 'يرنُّون'], 'Ma in', 'ما إن + madhi ... حتى'],
  ['لولا مساعدتك ما ____ المشروع.', 'Kalau bukan karena bantuanmu, proyek ini tidak akan selesai.', 'انتهى', ['ينتهون', 'انتهِ', 'انتهيتُ'], 'Lawla', 'لولا ... + jawab madhi'],
];

// [root letters, meaning, madhi, mudhari, amr, masdar, wazn]
export type VerbTuple = [root: string, meaning: string, madhi: string, mudhari: string, amr: string, masdar: string, wazn: string];

export const easyVerbs: VerbTuple[] = [
  ['د-ر-س', 'belajar', 'دَرَسَ', 'يَدْرُسُ', 'اُدْرُسْ', 'دِرَاسَة', 'فَعَلَ يَفْعُلُ'],
  ['ك-ت-ب', 'menulis', 'كَتَبَ', 'يَكْتُبُ', 'اُكْتُبْ', 'كِتَابَة', 'فَعَلَ يَفْعُلُ'],
  ['ق-ر-أ', 'membaca', 'قَرَأَ', 'يَقْرَأُ', 'اِقْرَأْ', 'قِرَاءَة', 'فَعَلَ يَفْعَلُ'],
  ['ذ-ه-ب', 'pergi', 'ذَهَبَ', 'يَذْهَبُ', 'اِذْهَبْ', 'ذَهَاب', 'فَعَلَ يَفْعَلُ'],
  ['ف-ت-ح', 'membuka', 'فَتَحَ', 'يَفْتَحُ', 'اِفْتَحْ', 'فَتْح', 'فَعَلَ يَفْعَلُ'],
  ['ج-ل-س', 'duduk', 'جَلَسَ', 'يَجْلِسُ', 'اِجْلِسْ', 'جُلُوس', 'فَعَلَ يَفْعِلُ'],
  ['ش-ر-ب', 'minum', 'شَرِبَ', 'يَشْرَبُ', 'اِشْرَبْ', 'شُرْب', 'فَعِلَ يَفْعَلُ'],
  ['ل-ع-ب', 'bermain', 'لَعِبَ', 'يَلْعَبُ', 'اِلْعَبْ', 'لَعِب', 'فَعِلَ يَفْعَلُ'],
  ['س-م-ع', 'mendengar', 'سَمِعَ', 'يَسْمَعُ', 'اِسْمَعْ', 'سَمَاع', 'فَعِلَ يَفْعَلُ'],
  ['ف-ه-م', 'memahami', 'فَهِمَ', 'يَفْهَمُ', 'اِفْهَمْ', 'فَهْم', 'فَعِلَ يَفْعَلُ'],
  ['ع-م-ل', 'bekerja', 'عَمِلَ', 'يَعْمَلُ', 'اِعْمَلْ', 'عَمَل', 'فَعِلَ يَفْعَلُ'],
  ['خ-ر-ج', 'keluar', 'خَرَجَ', 'يَخْرُجُ', 'اُخْرُجْ', 'خُرُوج', 'فَعَلَ يَفْعُلُ'],
  ['د-خ-ل', 'masuk', 'دَخَلَ', 'يَدْخُلُ', 'اُدْخُلْ', 'دُخُول', 'فَعَلَ يَفْعُلُ'],
  ['ن-ص-ر', 'menolong', 'نَصَرَ', 'يَنْصُرُ', 'اُنْصُرْ', 'نَصْر', 'فَعَلَ يَفْعُلُ'],
  ['ض-ر-ب', 'memukul', 'ضَرَبَ', 'يَضْرِبُ', 'اِضْرِبْ', 'ضَرْب', 'فَعَلَ يَفْعِلُ'],
  ['غ-س-ل', 'mencuci', 'غَسَلَ', 'يَغْسِلُ', 'اِغْسِلْ', 'غَسْل', 'فَعَلَ يَفْعِلُ'],
  ['ر-ج-ع', 'kembali', 'رَجَعَ', 'يَرْجِعُ', 'اِرْجِعْ', 'رُجُوع', 'فَعَلَ يَفْعِلُ'],
  ['ح-ف-ظ', 'menghafal', 'حَفِظَ', 'يَحْفَظُ', 'اِحْفَظْ', 'حِفْظ', 'فَعِلَ يَفْعَلُ'],
  ['ص-ن-ع', 'membuat', 'صَنَعَ', 'يَصْنَعُ', 'اِصْنَعْ', 'صُنْع', 'فَعَلَ يَفْعَلُ'],
  ['ر-ك-ب', 'naik (kendaraan)', 'رَكِبَ', 'يَرْكَبُ', 'اِرْكَبْ', 'رُكُوب', 'فَعِلَ يَفْعَلُ'],
  ['ط-ب-خ', 'memasak', 'طَبَخَ', 'يَطْبُخُ', 'اُطْبُخْ', 'طَبْخ', 'فَعَلَ يَفْعُلُ'],
  ['س-ك-ن', 'tinggal', 'سَكَنَ', 'يَسْكُنُ', 'اُسْكُنْ', 'سَكَن', 'فَعَلَ يَفْعُلُ'],
  ['ن-ظ-ر', 'melihat', 'نَظَرَ', 'يَنْظُرُ', 'اُنْظُرْ', 'نَظَر', 'فَعَلَ يَفْعُلُ'],
  ['ح-م-ل', 'membawa', 'حَمَلَ', 'يَحْمِلُ', 'اِحْمِلْ', 'حَمْل', 'فَعَلَ يَفْعِلُ'],
  ['ز-ر-ع', 'menanam', 'زَرَعَ', 'يَزْرَعُ', 'اِزْرَعْ', 'زِرَاعَة', 'فَعَلَ يَفْعَلُ'],
  ['ر-س-م', 'menggambar', 'رَسَمَ', 'يَرْسُمُ', 'اُرْسُمْ', 'رَسْم', 'فَعَلَ يَفْعُلُ'],
  ['س-أ-ل', 'bertanya', 'سَأَلَ', 'يَسْأَلُ', 'اِسْأَلْ', 'سُؤَال', 'فَعَلَ يَفْعَلُ'],
  ['ش-ك-ر', 'berterima kasih', 'شَكَرَ', 'يَشْكُرُ', 'اُشْكُرْ', 'شُكْر', 'فَعَلَ يَفْعُلُ'],
  ['ع-ر-ف', 'mengetahui', 'عَرَفَ', 'يَعْرِفُ', 'اِعْرِفْ', 'مَعْرِفَة', 'فَعَلَ يَفْعِلُ'],
  ['ن-ز-ل', 'turun', 'نَزَلَ', 'يَنْزِلُ', 'اِنْزِلْ', 'نُزُول', 'فَعَلَ يَفْعِلُ'],
];

export const mediumVerbs: VerbTuple[] = [
  ['ق-و-ل', 'berkata', 'قَالَ', 'يَقُولُ', 'قُلْ', 'قَوْل', 'ajwaf wawi'],
  ['ن-و-م', 'tidur', 'نَامَ', 'يَنَامُ', 'نَمْ', 'نَوْم', 'ajwaf wawi'],
  ['ب-ي-ع', 'menjual', 'بَاعَ', 'يَبِيعُ', 'بِعْ', 'بَيْع', 'ajwaf yai'],
  ['ز-و-ر', 'mengunjungi', 'زَارَ', 'يَزُورُ', 'زُرْ', 'زِيَارَة', 'ajwaf wawi'],
  ['ص-و-م', 'berpuasa', 'صَامَ', 'يَصُومُ', 'صُمْ', 'صَوْم', 'ajwaf wawi'],
  ['ق-و-م', 'berdiri', 'قَامَ', 'يَقُومُ', 'قُمْ', 'قِيَام', 'ajwaf wawi'],
  ['س-ي-ر', 'berjalan', 'سَارَ', 'يَسِيرُ', 'سِرْ', 'سَيْر', 'ajwaf yai'],
  ['خ-و-ف', 'takut', 'خَافَ', 'يَخَافُ', 'خَفْ', 'خَوْف', 'ajwaf wawi'],
  ['و-ص-ل', 'sampai', 'وَصَلَ', 'يَصِلُ', 'صِلْ', 'وُصُول', 'mitsal'],
  ['و-ج-د', 'menemukan', 'وَجَدَ', 'يَجِدُ', 'جِدْ', 'وُجُود', 'mitsal'],
  ['و-ع-د', 'berjanji', 'وَعَدَ', 'يَعِدُ', 'عِدْ', 'وَعْد', 'mitsal'],
  ['و-ض-ع', 'meletakkan', 'وَضَعَ', 'يَضَعُ', 'ضَعْ', 'وَضْع', 'mitsal'],
  ['و-ق-ف', 'berhenti', 'وَقَفَ', 'يَقِفُ', 'قِفْ', 'وُقُوف', 'mitsal'],
  ['م-ش-ي', 'berjalan kaki', 'مَشَى', 'يَمْشِي', 'اِمْشِ', 'مَشْي', 'naqish'],
  ['ب-ك-ي', 'menangis', 'بَكَى', 'يَبْكِي', 'اِبْكِ', 'بُكَاء', 'naqish'],
  ['ر-م-ي', 'melempar', 'رَمَى', 'يَرْمِي', 'اِرْمِ', 'رَمْي', 'naqish'],
  ['ج-ر-ي', 'berlari', 'جَرَى', 'يَجْرِي', 'اِجْرِ', 'جَرْي', 'naqish'],
  ['د-ع-و', 'berdoa/mengajak', 'دَعَا', 'يَدْعُو', 'اُدْعُ', 'دُعَاء', 'naqish'],
  ['ن-س-ي', 'lupa', 'نَسِيَ', 'يَنْسَى', 'اِنْسَ', 'نِسْيَان', 'naqish'],
  ['ب-ق-ي', 'tetap tinggal', 'بَقِيَ', 'يَبْقَى', 'اِبْقَ', 'بَقَاء', 'naqish'],
  ['أ-ك-ل', 'makan', 'أَكَلَ', 'يَأْكُلُ', 'كُلْ', 'أَكْل', 'mahmuz'],
  ['أ-خ-ذ', 'mengambil', 'أَخَذَ', 'يَأْخُذُ', 'خُذْ', 'أَخْذ', 'mahmuz'],
  ['أ-م-ر', 'memerintah', 'أَمَرَ', 'يَأْمُرُ', 'مُرْ', 'أَمْر', 'mahmuz'],
  ['م-د-د', 'membentangkan', 'مَدَّ', 'يَمُدُّ', 'مُدَّ', 'مَدّ', 'mudha’af'],
  ['ر-د-د', 'menjawab/mengembalikan', 'رَدَّ', 'يَرُدُّ', 'رُدَّ', 'رَدّ', 'mudha’af'],
  ['ع-د-د', 'menghitung', 'عَدَّ', 'يَعُدُّ', 'عُدَّ', 'عَدّ', 'mudha’af'],
  ['ش-د-د', 'mengencangkan', 'شَدَّ', 'يَشُدُّ', 'شُدَّ', 'شَدّ', 'mudha’af'],
  ['س-ع-ي', 'berusaha', 'سَعَى', 'يَسْعَى', 'اِسْعَ', 'سَعْي', 'naqish'],
  ['ع-و-د', 'kembali', 'عَادَ', 'يَعُودُ', 'عُدْ', 'عَوْدَة', 'ajwaf wawi'],
  ['ج-ي-ء', 'datang', 'جَاءَ', 'يَجِيءُ', 'جِئْ', 'مَجِيء', 'ajwaf yai mahmuz'],
];

export const hardVerbs: VerbTuple[] = [
  ['ع-ل-م', 'mengajar', 'عَلَّمَ', 'يُعَلِّمُ', 'عَلِّمْ', 'تَعْلِيم', 'فَعَّلَ'],
  ['د-ر-س', 'mengajarkan pelajaran', 'دَرَّسَ', 'يُدَرِّسُ', 'دَرِّسْ', 'تَدْرِيس', 'فَعَّلَ'],
  ['ن-ظ-ف', 'membersihkan', 'نَظَّفَ', 'يُنَظِّفُ', 'نَظِّفْ', 'تَنْظِيف', 'فَعَّلَ'],
  ['ق-د-م', 'menyajikan', 'قَدَّمَ', 'يُقَدِّمُ', 'قَدِّمْ', 'تَقْدِيم', 'فَعَّلَ'],
  ['ج-ر-ب', 'mencoba', 'جَرَّبَ', 'يُجَرِّبُ', 'جَرِّبْ', 'تَجْرِبَة', 'فَعَّلَ'],
  ['ك-ر-ر', 'mengulang', 'كَرَّرَ', 'يُكَرِّرُ', 'كَرِّرْ', 'تَكْرَار', 'فَعَّلَ'],
  ['س-ف-ر', 'bepergian', 'سَافَرَ', 'يُسَافِرُ', 'سَافِرْ', 'سَفَر', 'فَاعَلَ'],
  ['ش-ه-د', 'menonton', 'شَاهَدَ', 'يُشَاهِدُ', 'شَاهِدْ', 'مُشَاهَدَة', 'فَاعَلَ'],
  ['س-ع-د', 'membantu', 'سَاعَدَ', 'يُسَاعِدُ', 'سَاعِدْ', 'مُسَاعَدَة', 'فَاعَلَ'],
  ['ح-و-ل', 'berupaya', 'حَاوَلَ', 'يُحَاوِلُ', 'حَاوِلْ', 'مُحَاوَلَة', 'فَاعَلَ'],
  ['ن-ق-ش', 'berdiskusi', 'نَاقَشَ', 'يُنَاقِشُ', 'نَاقِشْ', 'مُنَاقَشَة', 'فَاعَلَ'],
  ['ر-س-ل', 'mengirim', 'أَرْسَلَ', 'يُرْسِلُ', 'أَرْسِلْ', 'إِرْسَال', 'أَفْعَلَ'],
  ['ك-م-ل', 'menyempurnakan', 'أَكْمَلَ', 'يُكْمِلُ', 'أَكْمِلْ', 'إِكْمَال', 'أَفْعَلَ'],
  ['خ-ب-ر', 'memberi tahu', 'أَخْبَرَ', 'يُخْبِرُ', 'أَخْبِرْ', 'إِخْبَار', 'أَفْعَلَ'],
  ['ح-س-ن', 'berbuat baik', 'أَحْسَنَ', 'يُحْسِنُ', 'أَحْسِنْ', 'إِحْسَان', 'أَفْعَلَ'],
  ['غ-ل-ق', 'menutup', 'أَغْلَقَ', 'يُغْلِقُ', 'أَغْلِقْ', 'إِغْلَاق', 'أَفْعَلَ'],
  ['ع-ل-م', 'belajar', 'تَعَلَّمَ', 'يَتَعَلَّمُ', 'تَعَلَّمْ', 'تَعَلُّم', 'تَفَعَّلَ'],
  ['ك-ل-م', 'berbicara', 'تَكَلَّمَ', 'يَتَكَلَّمُ', 'تَكَلَّمْ', 'تَكَلُّم', 'تَفَعَّلَ'],
  ['ذ-ك-ر', 'mengingat', 'تَذَكَّرَ', 'يَتَذَكَّرُ', 'تَذَكَّرْ', 'تَذَكُّر', 'تَفَعَّلَ'],
  ['ع-و-ن', 'bekerja sama', 'تَعَاوَنَ', 'يَتَعَاوَنُ', 'تَعَاوَنْ', 'تَعَاوُن', 'تَفَاعَلَ'],
  ['ب-د-ل', 'saling bertukar', 'تَبَادَلَ', 'يَتَبَادَلُ', 'تَبَادَلْ', 'تَبَادُل', 'تَفَاعَلَ'],
  ['ط-ل-ق', 'berangkat', 'اِنْطَلَقَ', 'يَنْطَلِقُ', 'اِنْطَلِقْ', 'اِنْطِلَاق', 'اِنْفَعَلَ'],
  ['ك-س-ر', 'pecah', 'اِنْكَسَرَ', 'يَنْكَسِرُ', 'اِنْكَسِرْ', 'اِنْكِسَار', 'اِنْفَعَلَ'],
  ['ج-م-ع', 'berkumpul', 'اِجْتَمَعَ', 'يَجْتَمِعُ', 'اِجْتَمِعْ', 'اِجْتِمَاع', 'اِفْتَعَلَ'],
  ['ن-ظ-ر', 'menunggu', 'اِنْتَظَرَ', 'يَنْتَظِرُ', 'اِنْتَظِرْ', 'اِنْتِظَار', 'اِفْتَعَلَ'],
  ['س-م-ع', 'mendengarkan', 'اِسْتَمَعَ', 'يَسْتَمِعُ', 'اِسْتَمِعْ', 'اِسْتِمَاع', 'اِفْتَعَلَ'],
  ['ح-ر-م', 'menghormati', 'اِحْتَرَمَ', 'يَحْتَرِمُ', 'اِحْتَرِمْ', 'اِحْتِرَام', 'اِفْتَعَلَ'],
  ['خ-د-م', 'menggunakan', 'اِسْتَخْدَمَ', 'يَسْتَخْدِمُ', 'اِسْتَخْدِمْ', 'اِسْتِخْدَام', 'اِسْتَفْعَلَ'],
  ['غ-ف-ر', 'memohon ampun', 'اِسْتَغْفَرَ', 'يَسْتَغْفِرُ', 'اِسْتَغْفِرْ', 'اِسْتِغْفَار', 'اِسْتَفْعَلَ'],
  ['ق-ب-ل', 'menyambut', 'اِسْتَقْبَلَ', 'يَسْتَقْبِلُ', 'اِسْتَقْبِلْ', 'اِسْتِقْبَال', 'اِسْتَفْعَلَ'],
];

// Hand-picked wrong forms for the weak verbs: classic learner slips (kept waw, kept long vowel, wrong bab vowel).
export const mediumVerbDistractors: Record<string, { Mudhari: string[]; Amr: string[] }> = {
  'قَالَ': { Mudhari: ['يَقِيلُ', 'يَقَالُ', 'يُقَالُ'], Amr: ['قِلْ', 'قَلْ', 'قُولْ'] },
  'نَامَ': { Mudhari: ['يَنُومُ', 'يَنِيمُ', 'يُنَامُ'], Amr: ['نُمْ', 'نِمْ', 'نَامْ'] },
  'بَاعَ': { Mudhari: ['يَبُوعُ', 'يَبَاعُ', 'يُبَاعُ'], Amr: ['بُعْ', 'بَعْ', 'بِيعْ'] },
  'زَارَ': { Mudhari: ['يَزِيرُ', 'يَزَارُ', 'يُزَارُ'], Amr: ['زِرْ', 'زَرْ', 'زُورْ'] },
  'صَامَ': { Mudhari: ['يَصِيمُ', 'يَصَامُ', 'يُصَامُ'], Amr: ['صِمْ', 'صَمْ', 'صُومْ'] },
  'قَامَ': { Mudhari: ['يَقِيمُ', 'يَقَامُ', 'يُقَامُ'], Amr: ['قِمْ', 'قَمْ', 'قُومْ'] },
  'سَارَ': { Mudhari: ['يَسُورُ', 'يَسَارُ', 'يُسَارُ'], Amr: ['سُرْ', 'سَرْ', 'سِيرْ'] },
  'خَافَ': { Mudhari: ['يَخُوفُ', 'يَخِيفُ', 'يُخَافُ'], Amr: ['خُفْ', 'خِفْ', 'خَافْ'] },
  'وَصَلَ': { Mudhari: ['يَوْصِلُ', 'يَصُلُ', 'يُوصَلُ'], Amr: ['اِوْصِلْ', 'صُلْ', 'صَلْ'] },
  'وَجَدَ': { Mudhari: ['يَوْجِدُ', 'يَجُدُ', 'يُوجَدُ'], Amr: ['اِوْجِدْ', 'جُدْ', 'جَدْ'] },
  'وَعَدَ': { Mudhari: ['يَوْعِدُ', 'يَعُدُ', 'يُوعَدُ'], Amr: ['اِوْعِدْ', 'عُدْ', 'عَدْ'] },
  'وَضَعَ': { Mudhari: ['يَوْضَعُ', 'يَضِعُ', 'يُوضَعُ'], Amr: ['اِوْضَعْ', 'ضِعْ', 'ضُعْ'] },
  'وَقَفَ': { Mudhari: ['يَوْقِفُ', 'يَقُفُ', 'يُوقَفُ'], Amr: ['اِوْقِفْ', 'قُفْ', 'قَفْ'] },
  'مَشَى': { Mudhari: ['يَمْشُو', 'يَمْشَى', 'يَمْشِيُ'], Amr: ['اِمْشِي', 'اِمْشُ', 'اُمْشُ'] },
  'بَكَى': { Mudhari: ['يَبْكُو', 'يَبْكَى', 'يَبْكِيُ'], Amr: ['اِبْكِي', 'اِبْكُ', 'اُبْكُ'] },
  'رَمَى': { Mudhari: ['يَرْمُو', 'يَرْمَى', 'يَرْمِيُ'], Amr: ['اِرْمِي', 'اِرْمُ', 'اُرْمُ'] },
  'جَرَى': { Mudhari: ['يَجْرُو', 'يَجْرَى', 'يَجْرِيُ'], Amr: ['اِجْرِي', 'اِجْرُ', 'اُجْرُ'] },
  'دَعَا': { Mudhari: ['يَدْعِي', 'يَدْعَى', 'يَدْعُوُ'], Amr: ['اُدْعُو', 'اِدْعِ', 'اُدْعَ'] },
  'نَسِيَ': { Mudhari: ['يَنْسِي', 'يَنْسُو', 'يُنْسِي'], Amr: ['اِنْسَى', 'اِنْسِ', 'اُنْسُ'] },
  'بَقِيَ': { Mudhari: ['يَبْقِي', 'يَبْقُو', 'يُبْقِي'], Amr: ['اِبْقَى', 'اِبْقِ', 'اُبْقُ'] },
  'سَعَى': { Mudhari: ['يَسْعِي', 'يَسْعُو', 'يُسْعِي'], Amr: ['اِسْعَى', 'اِسْعِ', 'اُسْعُ'] },
  'أَكَلَ': { Mudhari: ['يَأْكِلُ', 'يَأْكَلُ', 'يَكُلُ'], Amr: ['كِلْ', 'اُؤْكُلْ', 'أَكَلْ'] },
  'أَخَذَ': { Mudhari: ['يَأْخِذُ', 'يَأْخَذُ', 'يَخُذُ'], Amr: ['خِذْ', 'اُؤْخُذْ', 'أَخَذْ'] },
  'أَمَرَ': { Mudhari: ['يَأْمِرُ', 'يَأْمَرُ', 'يَمُرُ'], Amr: ['مِرْ', 'اُؤْمُرْ', 'أَمَرْ'] },
  'مَدَّ': { Mudhari: ['يَمِدُّ', 'يَمَدُّ', 'يَمْدُدُ'], Amr: ['مِدَّ', 'مُدْ', 'مَدِّ'] },
  'رَدَّ': { Mudhari: ['يَرِدُّ', 'يَرَدُّ', 'يَرْدُدُ'], Amr: ['رِدَّ', 'رُدْ', 'رَدِّ'] },
  'عَدَّ': { Mudhari: ['يَعِدُّ', 'يَعَدُّ', 'يَعْدُدُ'], Amr: ['عِدَّ', 'عُدْ', 'عَدِّ'] },
  'شَدَّ': { Mudhari: ['يُشَدُّ', 'يَشَدُّ', 'يَشْدُدُ'], Amr: ['شِدَّ', 'شُدْ', 'شَدِّ'] },
  'عَادَ': { Mudhari: ['يَعِيدُ', 'يَعَادُ', 'يُعَادُ'], Amr: ['عِدْ', 'عَدْ', 'عُودْ'] },
  'جَاءَ': { Mudhari: ['يَجُوءُ', 'يَجَاءُ', 'يُجَاءُ'], Amr: ['جُئْ', 'جَئْ', 'جِيئْ'] },
};
