// Alif Lam Dash, Expression Quest, Idza Run and Question Builder banks, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule]
export type ChoiceTuple = [prompt: string, translation: string, answer: string, wrong: string[], label: string, rule: string];

const NAKIRAH = 'Nakirah: benda umum/baru disebut tanpa ال.';
const MARIFAH = "Ma'rifah: benda tertentu memakai ال.";
const MUBTADA = "Mubtada' harus ma'rifah, maka memakai ال.";
const NAAT = "Na'at (sifat) mengikuti man'ut dalam ال, jenis, jumlah, dan i'rab.";
const IDHAFAH = "Mudhaf tidak memakai ال; mudhaf ilaih yang menentukan ma'rifah.";

export const easyArticles: ChoiceTuple[] = [
  ['هذا ____ جديد.', 'Ini sebuah buku baru.', 'كتاب', ['الكتاب', 'كتب', 'كتابة'], 'Nakirah', NAKIRAH],
  ['____ على الطاولة.', 'Buku itu ada di atas meja.', 'الكتاب', ['كتاب', 'كتابان', 'كتبي'], "Ma'rifah", MUBTADA],
  ['أنا في ____ الآن.', 'Saya di sekolah itu sekarang.', 'المدرسة', ['مدرسة', 'مدارس', 'مدرسي'], "Ma'rifah", MARIFAH],
  ['عندي ____.', 'Saya punya seekor kucing.', 'قطة', ['القطة', 'قطط', 'القطط'], 'Nakirah', NAKIRAH],
  ['____ نظيف.', 'Rumah itu bersih.', 'البيت', ['بيت', 'بيوت', 'بيتا'], "Ma'rifah", MUBTADA],
  ['اشتريت ____ أمس.', 'Saya membeli sebuah tas kemarin.', 'حقيبة', ['الحقيبة', 'حقائب', 'حقيبتان'], 'Nakirah', NAKIRAH],
  ['____ حار اليوم.', 'Cuacanya panas hari ini.', 'الجو', ['جو', 'جوا', 'أجواء'], "Ma'rifah", MUBTADA],
  ['هذه ____.', 'Ini sebuah apel.', 'تفاحة', ['التفاحة', 'تفاح', 'تفاحات'], 'Nakirah', 'Khabar setelah هذه berupa nakirah.'],
  ['____ في السماء.', 'Matahari ada di langit.', 'الشمس', ['شمس', 'شموس', 'شمسا'], "Ma'rifah", 'Benda yang hanya satu (matahari) memakai ال.'],
  ['رأيت ____ في الشارع.', 'Saya melihat seekor anjing di jalan.', 'كلبا', ['الكلب', 'كلب', 'كلاب'], 'Nakirah', "Maf'ul bih nakirah ditulis dengan tanwin fathah: كلبًا."],
  ['____ صديقي.', 'Ahmad adalah temanku.', 'أحمد', ['الأحمد', 'أحمدا', 'أحمدان'], "'Alam", 'Nama orang sudah ma’rifah, tidak memakai ال.'],
  ['____ عاصمة إندونيسيا.', 'Jakarta adalah ibu kota Indonesia.', 'جاكرتا', ['الجاكرتا', 'عاصمة', 'العاصمة'], "'Alam", 'Nama kota sudah ma’rifah tanpa ال.'],
  ['____ نهر طويل.', 'Sungai Nil adalah sungai yang panjang.', 'النيل', ['نيل', 'نيلا', 'الأنهار'], "'Alam", 'Beberapa nama tempat selalu memakai ال: النيل.'],
  ['في الفصل ____.', 'Di kelas ada seorang guru.', 'معلم', ['المعلم', 'معلمون', 'معلما'], 'Nakirah', "Khabar muqaddam + mubtada' nakirah: في الفصل معلمٌ."],
  ['____ مفتوحة.', 'Jendela itu terbuka.', 'النافذة', ['نافذة', 'نوافذ', 'نافذتان'], "Ma'rifah", MUBTADA],
  ['هذا ____.', 'Ini seorang guru laki-laki.', 'مدرس', ['المدرس', 'مدرسة', 'مدرسون'], 'Nakirah', 'Khabar setelah هذا berupa nakirah.'],
  ['____ لذيذ.', 'Makanannya enak.', 'الطعام', ['طعام', 'أطعمة', 'طعاما'], "Ma'rifah", MUBTADA],
  ['في الحديقة ____ جميلة.', 'Di taman ada bunga-bunga yang indah.', 'أزهار', ['الأزهار', 'زهرة', 'الزهرة'], 'Nakirah', "Mubtada' muakhkhar nakirah setelah khabar syibhul jumlah."],
  ['____ كبيرة.', 'Kota itu besar.', 'المدينة', ['مدينة', 'مدن', 'مدينتان'], "Ma'rifah", MUBTADA],
  ['هذا ____ كبير.', 'Ini sebuah rumah besar.', 'بيت', ['البيت', 'بيوت', 'بيتا'], 'Nakirah', NAKIRAH],
  ['____ في المطبخ.', 'Ibu itu ada di dapur.', 'الأم', ['أم', 'أمهات', 'أما'], "Ma'rifah", MUBTADA],
  ['هناك ____ أمام البيت.', 'Ada sebuah mobil di depan rumah.', 'سيارة', ['السيارة', 'سيارات', 'سيارتان'], 'Nakirah', 'Setelah هناك, benda yang ada berupa nakirah.'],
  ['____ بارد.', 'Air itu dingin.', 'الماء', ['ماء', 'مياه', 'ماءان'], "Ma'rifah", MUBTADA],
  ['رأيت ____ في الحديقة.', 'Saya melihat anak-anak itu di taman.', 'الأطفال', ['أطفالا', 'طفل', 'الطفل'], "Ma'rifah", MARIFAH],
  ['____ مجتهدة.', 'Siswi itu rajin.', 'الطالبة', ['طالبة', 'طالب', 'الطالب'], "Ma'rifah", MUBTADA],
  ['____ صغيرة.', 'Kamar itu kecil.', 'الغرفة', ['غرفة', 'غرف', 'الغرف'], "Ma'rifah", MUBTADA],
  ['عندي ____ جديد.', 'Saya punya seorang teman baru.', 'صديق', ['الصديق', 'صديقة', 'أصدقاء'], 'Nakirah', NAKIRAH],
  ['____ مزدحم.', 'Pasar itu ramai.', 'السوق', ['سوق', 'أسواق', 'سوقا'], "Ma'rifah", MUBTADA],
  ['هذا ____ وهذه مسطرة.', 'Ini pulpen dan ini penggaris.', 'قلم', ['القلم', 'أقلام', 'قلمان'], 'Nakirah', 'Khabar setelah هذا berupa nakirah.'],
  ['____ في العش.', 'Burung itu ada di sarangnya.', 'الطائر', ['طائر', 'طيور', 'طائرا'], "Ma'rifah", MUBTADA],
];

export const mediumArticles: ChoiceTuple[] = [
  ['قرأت الكتاب ____.', 'Saya membaca buku yang baru itu.', 'الجديد', ['جديد', 'جديدا', 'الجديدة'], "Na'at", NAAT],
  ['____ الطالب على المكتب.', 'Buku siswa itu ada di atas meja.', 'كتاب', ['الكتاب', 'كتابا', 'الكتب'], 'Idhafah', IDHAFAH],
  ['سكنت في ____ كبيرة.', 'Saya tinggal di sebuah kota besar.', 'مدينة', ['المدينة', 'مدينتي', 'المدن'], 'Nakirah', 'Nakirah disifati sifat nakirah: مدينة كبيرة.'],
  ['هذا ____ المدرسة.', 'Ini pintu sekolah.', 'باب', ['الباب', 'بابا', 'أبواب'], 'Idhafah', IDHAFAH],
  ['اشتريت السيارة ____.', 'Saya membeli mobil merah itu.', 'الحمراء', ['حمراء', 'الأحمر', 'أحمر'], "Na'at", NAAT],
  ['____ المدينة جميلة.', 'Jalan-jalan kota itu indah.', 'شوارع', ['الشوارع', 'شارع', 'شوارعا'], 'Idhafah', IDHAFAH],
  ['جلست على الكرسي ____.', 'Saya duduk di kursi yang kecil itu.', 'الصغير', ['صغير', 'الصغيرة', 'صغيرا'], "Na'at", NAAT],
  ['____ الجامعة واسعة.', 'Perpustakaan universitas itu luas.', 'مكتبة', ['المكتبة', 'مكتبات', 'مكتبتي'], 'Idhafah', IDHAFAH],
  ['هذه بنت ____.', 'Ini seorang anak perempuan yang rajin.', 'مجتهدة', ['المجتهدة', 'مجتهد', 'المجتهد'], "Na'at", 'Nakirah disifati sifat nakirah muannats.'],
  ['زرت ____ الكبير.', 'Saya mengunjungi masjid besar itu.', 'المسجد', ['مسجد', 'مسجدا', 'مساجد'], "Na'at", NAAT],
  ['____ الأستاذ في الفصل.', 'Tas pak guru ada di kelas.', 'حقيبة', ['الحقيبة', 'حقيبتي', 'حقائبا'], 'Idhafah', IDHAFAH],
  ['هو مهندس ____.', 'Dia seorang insinyur yang terkenal.', 'مشهور', ['المشهور', 'مشهورة', 'مشهورون'], "Na'at", 'Nakirah disifati sifat nakirah mudzakkar.'],
  ['نظرت إلى السماء ____.', 'Saya memandang langit yang biru.', 'الزرقاء', ['زرقاء', 'الأزرق', 'أزرق'], "Na'at", NAAT],
  ['قابلت مدير ____.', 'Saya bertemu direktur perusahaan itu.', 'الشركة', ['شركة', 'شركات', 'الشركتان'], 'Idhafah', 'Mudhaf ilaih memakai ال agar idhafah menjadi ma’rifah.'],
  ['____ البيت مفتوحة.', 'Jendela-jendela rumah itu terbuka.', 'نوافذ', ['النوافذ', 'نافذة', 'نوافذا'], 'Idhafah', IDHAFAH],
  ['قرأت قصة ____.', 'Saya membaca sebuah cerita pendek.', 'قصيرة', ['القصيرة', 'قصير', 'القصير'], "Na'at", 'Nakirah disifati sifat nakirah muannats.'],
  ['هذا ____ أحمد.', 'Ini pulpen Ahmad.', 'قلم', ['القلم', 'قلما', 'أقلام'], 'Idhafah', IDHAFAH],
  ['الطلاب ____ نجحوا.', 'Para siswa yang rajin itu lulus.', 'المجتهدون', ['مجتهدون', 'المجتهدين', 'المجتهد'], "Na'at", NAAT],
  ['____ البحر زرقاء.', 'Air laut itu biru.', 'مياه', ['المياه', 'ماء', 'البحر'], 'Idhafah', IDHAFAH],
  ['شربت قهوة ____.', 'Saya minum kopi yang panas.', 'ساخنة', ['الساخنة', 'ساخن', 'الساخن'], "Na'at", 'Nakirah disifati sifat nakirah muannats.'],
  ['هذه غرفة ____.', 'Ini kamar Fatimah.', 'فاطمة', ['الفاطمة', 'فاطمتان', 'الفاطمات'], 'Idhafah', 'Nama orang sebagai mudhaf ilaih tanpa ال.'],
  ['أحب اللغة ____.', 'Saya suka bahasa Arab.', 'العربية', ['عربية', 'العربي', 'عربي'], "Na'at", NAAT],
  ['____ المسجد كبيرة.', 'Kubah masjid itu besar.', 'قبة', ['القبة', 'قباب', 'قبتان'], 'Idhafah', IDHAFAH],
  ['ركبت القطار ____.', 'Saya naik kereta yang cepat itu.', 'السريع', ['سريع', 'سريعا', 'السريعة'], "Na'at", NAAT],
  ['في يدي ____ ثقيلة.', 'Di tanganku ada sebuah tas yang berat.', 'حقيبة', ['الحقيبة', 'حقائب', 'حقيبتان'], 'Nakirah', "Mubtada' nakirah setelah khabar syibhul jumlah."],
  ['ذهبنا إلى ____ الوطني.', 'Kami pergi ke museum nasional.', 'المتحف', ['متحف', 'متحفا', 'متاحف'], "Na'at", NAAT],
  ['هذا سؤال ____.', 'Ini pertanyaan yang sulit.', 'صعب', ['الصعب', 'صعبة', 'الصعبة'], "Na'at", 'Nakirah disifati sifat nakirah mudzakkar.'],
  ['____ الجامعة يدرسون كثيرا.', 'Mahasiswa universitas itu banyak belajar.', 'طلاب', ['الطلاب', 'طالب', 'طلابا'], 'Idhafah', IDHAFAH],
  ['أكلت التفاحة ____.', 'Saya memakan apel yang hijau itu.', 'الخضراء', ['خضراء', 'الأخضر', 'أخضر'], "Na'at", NAAT],
  ['هذه سيارة ____.', 'Ini mobil ayahku.', 'أبي', ['الأب', 'أبا', 'آباء'], 'Idhafah', 'Dhamir ي menjadikan mudhaf ilaih ma’rifah.'],
];

export const hardArticles: ChoiceTuple[] = [
  ['باب ____ مكسور.', 'Pintu rumah guru itu rusak.', 'بيت المعلم', ['البيت المعلم', 'بيت معلم', 'البيت معلم'], 'Idhafah bertingkat', 'Dalam idhafah bertingkat hanya kata terakhir memakai ال.'],
  ['هذه ____ التي اشتريتها.', 'Inilah mobil yang saya beli.', 'السيارة', ['سيارة', 'سيارات', 'سيارتان'], 'Ism maushul', 'التي mensifati benda ma’rifah.'],
  ['قرأت ____ الذي أعطيتني.', 'Saya membaca buku yang kamu berikan kepadaku.', 'الكتاب', ['كتاب', 'كتابا', 'الكتب'], 'Ism maushul', 'الذي mensifati benda ma’rifah mufrad mudzakkar.'],
  ['رأيت رجلا ____ في الشارع.', 'Saya melihat seorang pria yang sedang berlari di jalan.', 'يجري', ['الذي يجري', 'الجاري', 'يجرون'], 'Jumlah sifat', 'Nakirah disifati jumlah tanpa الذي.'],
  ['____ مدير الشركة جديدة.', 'Mobil direktur perusahaan itu baru.', 'سيارة', ['السيارة', 'سيارتا', 'سيارتي'], 'Idhafah bertingkat', IDHAFAH],
  ['هذه حقيبة الطالب ____.', 'Ini tas milik siswa yang baru itu.', 'الجديد', ['الجديدة', 'جديد', 'جديدة'], "Na'at", "Sifat mengikuti kata yang disifati: الطالب الجديد."],
  ['هذه حقيبة الطالب ____.', 'Ini tas baru milik siswa itu.', 'الجديدة', ['الجديد', 'جديدة', 'جديد'], "Na'at", "Sifat untuk mudhaf ditaruh setelah mudhaf ilaih dan ikut ma'rifah: حقيبة الطالب الجديدة."],
  ['اشتريت ثلاثة ____.', 'Saya membeli tiga pulpen.', 'أقلام', ['قلم', 'القلم', 'الأقلام'], "'Adad", "Bilangan 3–10 + jamak nakirah majrur."],
  ['في الفصل عشرون ____.', 'Di kelas ada dua puluh siswa.', 'طالبا', ['طلاب', 'الطلاب', 'طالب'], 'Tamyiz', 'Bilangan 11–99 + tamyiz mufrad manshub.'],
  ['____ الطالبين نظيفة.', 'Kamar kedua siswa itu bersih.', 'غرفة', ['الغرفة', 'غرفتي', 'غرفا'], 'Idhafah', IDHAFAH],
  ['جاء ____ الطلاب.', 'Semua siswa telah datang.', 'كل', ['الكل', 'كلا', 'جميعا'], 'Idhafah', 'كل sebagai mudhaf tanpa ال.'],
  ['قرأت الكتب ____.', 'Saya membaca buku-buku yang bermanfaat itu.', 'المفيدة', ['المفيدين', 'مفيدة', 'المفيد'], "Na'at", 'Jamak tak berakal disifati mufrad muannats.'],
  ['هذا ____ الذي يدرسنا.', 'Inilah guru yang mengajar kami.', 'المعلم', ['معلم', 'معلما', 'المعلمة'], 'Ism maushul', 'الذي mensifati ma’rifah mufrad mudzakkar.'],
  ['التقيت بمعلمة ____ العربية.', 'Saya bertemu seorang guru perempuan yang mengajar bahasa Arab.', 'تدرّس', ['التي تدرس', 'الذي يدرس', 'يدرسن'], 'Jumlah sifat', 'Nakirah disifati jumlah tanpa التي.'],
  ['____ نور.', 'Ilmu itu cahaya.', 'العلم', ['علم', 'علما', 'علوم'], 'Jenis', 'Ism jenis yang bermakna umum memakai ال.'],
  ['هو طالب ____.', 'Dia seorang mahasiswa Indonesia.', 'إندونيسي', ['الإندونيسي', 'إندونيسية', 'الإندونيسية'], 'Nisbah', 'Sifat nisbah mengikuti nakirah mudzakkar.'],
  ['مفتاح ____ مع أبي.', 'Kunci mobil kami ada pada ayah.', 'سيارتنا', ['السيارتنا', 'سيارة', 'السيارة'], 'Idhafah', 'Kata ber-dhamir sudah ma’rifah, tidak boleh memakai ال.'],
  ['الطالبتان ____ نجحتا.', 'Kedua siswi yang rajin itu lulus.', 'المجتهدتان', ['المجتهدتين', 'مجتهدتان', 'المجتهدات'], "Na'at", NAAT],
  ['____ الطلاب حاضرون.', 'Sebagian besar siswa hadir.', 'معظم', ['المعظم', 'معظما', 'عظيم'], 'Idhafah', 'معظم sebagai mudhaf tanpa ال.'],
  ['هذا كتاب ____ اللغة العربية.', 'Ini buku tata bahasa Arab.', 'قواعد', ['القواعد', 'قاعدة', 'قواعدا'], 'Idhafah bertingkat', 'Kata tengah dalam idhafah bertingkat tanpa ال.'],
  ['حضر الحفل ____ كثيرون.', 'Banyak orang menghadiri pesta itu.', 'ناس', ['الناس', 'ناسا', 'إنسان'], 'Nakirah', "Fa'il nakirah disifati nakirah: ناسٌ كثيرون."],
  ['كان يوم ____ يوما سعيدا.', 'Hari Jumat itu adalah hari yang membahagiakan.', 'الجمعة', ['جمعة', 'جمعات', 'الجمعات'], 'Idhafah', 'Nama hari sebagai mudhaf ilaih memakai ال.'],
  ['أسكن في الطابق ____.', 'Saya tinggal di lantai lima.', 'الخامس', ['خامس', 'الخامسة', 'خمسة'], "'Adad tartibi", 'Bilangan urutan mengikuti man’ut: الطابق الخامس.'],
  ['هذه هي ____ الأولى لي في مصر.', 'Ini adalah kunjungan pertamaku ke Mesir.', 'الزيارة', ['زيارة', 'زيارات', 'الزيارات'], "Na'at", NAAT],
  ['____ الذين حضروا سعداء.', 'Para tamu yang hadir merasa senang.', 'الضيوف', ['ضيوف', 'الضيف', 'ضيفا'], 'Ism maushul', 'الذين mensifati jamak ma’rifah berakal.'],
  ['قرأت مقالة ____ عن البيئة.', 'Saya membaca sebuah artikel menarik tentang lingkungan.', 'ممتعة', ['الممتعة', 'ممتع', 'ممتعا'], "Na'at", 'Nakirah disifati sifat nakirah muannats.'],
  ['____ القرية بسيطون.', 'Penduduk desa itu sederhana.', 'أهل', ['الأهل', 'أهلا', 'الأهالي'], 'Idhafah', IDHAFAH],
  ['كل ____ مسؤول عن عمله.', 'Setiap orang bertanggung jawab atas pekerjaannya.', 'إنسان', ['الإنسان', 'إنسانا', 'ناس'], 'Idhafah', 'كل + nakirah mufrad = "setiap".'],
  ['جاء الطلاب ____.', 'Para siswa datang semuanya.', 'كلهم', ['كل', 'الكل', 'كلها'], 'Taukid', 'كل sebagai taukid memakai dhamir yang sesuai: كلهم.'],
  ['هذا هو الرجل ____ ساعدني.', 'Inilah pria yang membantuku.', 'الذي', ['التي', 'الذين', 'اللذان'], 'Ism maushul', 'Ism maushul mengikuti jenis dan jumlah: الرجل الذي.'],
];

const MODAL_RULE = "ungkapan + أن + fi'il mudhari manshub";

export const easyModals: ChoiceTuple[] = [
  ['____ أقرأ العربية.', 'Saya bisa membaca bahasa Arab.', 'أستطيع أن', ['يجب أن', 'أريد أن', 'ممنوع أن'], 'Kemampuan', MODAL_RULE],
  ['____ أراجع الدرس.', 'Saya harus mengulang pelajaran.', 'يجب أن', ['أستطيع أن', 'أحب أن', 'ممنوع أن'], 'Kewajiban', MODAL_RULE],
  ['____ أتعلم كل يوم.', 'Saya ingin belajar setiap hari.', 'أريد أن', ['لا بد أن', 'لا أستطيع أن', 'ممنوع أن'], 'Keinginan', MODAL_RULE],
  ['____ أسبح.', 'Saya tidak bisa berenang.', 'لا أستطيع أن', ['أريد أن', 'يجب أن', 'أحب أن'], 'Ketidakmampuan', MODAL_RULE],
  ['____ أشرب الشاي في الصباح.', 'Saya suka minum teh di pagi hari.', 'أحب أن', ['يجب أن', 'ممنوع أن', 'لا أستطيع أن'], 'Kesukaan', MODAL_RULE],
  ['____ التدخين هنا.', 'Dilarang merokok di sini.', 'ممنوع', ['مسموح', 'أريد', 'أستطيع'], 'Larangan', 'ممنوع + masdar'],
  ['افتح الباب ____.', 'Bukalah pintunya, tolong.', 'من فضلك', ['ممنوع', 'يجب', 'لا بد'], 'Permintaan', 'من فضلك untuk meminta dengan sopan'],
  ['____ تساعدني؟', 'Bisakah kamu membantuku?', 'هل يمكنك أن', ['يجب أن', 'ممنوع أن', 'أحب أن'], 'Permintaan', 'هل يمكنك أن + mudhari'],
  ['____ أنام مبكرا.', 'Saya harus tidur lebih awal.', 'يجب أن', ['أستطيع أن', 'هل يمكن أن', 'أحب أن'], 'Kewajiban', MODAL_RULE],
  ['____ أزور جدتي.', 'Saya ingin mengunjungi nenek.', 'أريد أن', ['يجب أن', 'لا أستطيع أن', 'ممنوع أن'], 'Keinginan', MODAL_RULE],
  ['أخي ____ يركب الدراجة.', 'Adikku bisa naik sepeda.', 'يستطيع أن', ['يجب أن', 'يريد أن', 'ممنوع أن'], 'Kemampuan', MODAL_RULE],
  ['____ تدخل الآن.', 'Kamu boleh masuk sekarang.', 'يمكنك أن', ['يجب أن', 'لا تستطيع أن', 'ممنوع أن'], 'Izin', MODAL_RULE],
  ['____ تأكل في الفصل.', 'Kamu tidak boleh makan di kelas.', 'لا يجوز أن', ['يمكنك أن', 'تستطيع أن', 'تحب أن'], 'Larangan', MODAL_RULE],
  ['أختي ____ تطبخ.', 'Kakak perempuanku suka memasak.', 'تحب أن', ['يجب أن', 'لا تستطيع أن', 'ممنوع أن'], 'Kesukaan', MODAL_RULE],
  ['____ نصلي الآن.', 'Kita harus shalat sekarang.', 'يجب أن', ['نستطيع أن', 'نحب أن', 'ممنوع أن'], 'Kewajiban', MODAL_RULE],
  ['____ أسافر إلى مكة.', 'Saya ingin bepergian ke Mekah.', 'أريد أن', ['يجب أن', 'ممنوع أن', 'لا أستطيع أن'], 'Keinginan', MODAL_RULE],
  ['____ أكتب بالعربية.', 'Saya bisa menulis dalam bahasa Arab.', 'أستطيع أن', ['يجب أن', 'لا يجوز أن', 'أريد أن'], 'Kemampuan', MODAL_RULE],
  ['____ بالجلوس هنا.', 'Silakan duduk di sini.', 'تفضل', ['ممنوع', 'يجب', 'لا بد'], 'Mempersilakan', 'تفضل + بـ + masdar'],
  ['أعطني الملح ____.', 'Berikan aku garamnya, tolong.', 'من فضلك', ['ممنوع', 'لا بد', 'يجب'], 'Permintaan', 'من فضلك untuk meminta dengan sopan'],
  ['____ أذهب إلى الحمام؟', 'Bolehkah saya ke kamar mandi?', 'هل يمكنني أن', ['يجب أن', 'لا أستطيع أن', 'أحب أن'], 'Izin', 'هل يمكنني أن + mudhari'],
  ['____ ننتظر قليلا.', 'Kita harus menunggu sebentar.', 'يجب أن', ['نستطيع أن', 'ممنوع أن', 'نحب أن'], 'Kewajiban', MODAL_RULE],
  ['____ أتكلم مع المدير.', 'Saya ingin berbicara dengan direktur.', 'أريد أن', ['ممنوع أن', 'لا بد أن', 'لا أستطيع أن'], 'Keinginan', MODAL_RULE],
  ['____ أحمل هذه الحقيبة الثقيلة.', 'Saya tidak bisa membawa tas berat ini.', 'لا أستطيع أن', ['أحب أن', 'يجب أن', 'أريد أن'], 'Ketidakmampuan', MODAL_RULE],
  ['____ أشاهد الأفلام.', 'Saya suka menonton film.', 'أحب أن', ['يجب أن', 'ممنوع أن', 'لا أستطيع أن'], 'Kesukaan', MODAL_RULE],
  ['____ الكلام في المكتبة.', 'Dilarang berbicara di perpustakaan.', 'ممنوع', ['مسموح', 'أستطيع', 'أحب'], 'Larangan', 'ممنوع + masdar'],
  ['____ تكتب اسمك هنا.', 'Kamu harus menulis namamu di sini.', 'يجب أن', ['يمكنك أن', 'ممنوع أن', 'تحب أن'], 'Kewajiban', MODAL_RULE],
  ['____ نلعب بعد المدرسة.', 'Kami ingin bermain setelah sekolah.', 'نريد أن', ['يجب أن', 'ممنوع أن', 'لا نستطيع أن'], 'Keinginan', MODAL_RULE],
  ['____ تعيد السؤال؟', 'Bisakah kamu mengulang pertanyaannya?', 'هل يمكنك أن', ['يجب أن', 'ممنوع أن', 'أريد أن'], 'Permintaan', 'هل يمكنك أن + mudhari'],
  ['أبي ____ يتكلم ثلاث لغات.', 'Ayahku bisa berbicara tiga bahasa.', 'يستطيع أن', ['يجب أن', 'ممنوع أن', 'لا يجوز أن'], 'Kemampuan', MODAL_RULE],
  ['____ نحافظ على النظافة.', 'Kita harus menjaga kebersihan.', 'يجب أن', ['نستطيع أن', 'ممنوع أن', 'لا يجوز أن'], 'Kewajiban', MODAL_RULE],
];

export const mediumModals: ChoiceTuple[] = [
  ['____ تنام مبكرا.', 'Sebaiknya kamu tidur lebih awal.', 'ينبغي أن', ['ممنوع أن', 'لا تستطيع أن', 'أتمنى أن'], 'Nasihat', MODAL_RULE],
  ['____ أشتري خبزا.', 'Saya perlu membeli roti.', 'أحتاج أن', ['ممنوع أن', 'أخشى أن', 'لا يجوز أن'], 'Kebutuhan', MODAL_RULE],
  ['____ تنجح في الامتحان.', 'Saya berharap kamu lulus ujian.', 'أتمنى أن', ['ممنوع أن', 'يجب أن', 'أستطيع أن'], 'Harapan', MODAL_RULE],
  ['____ يمطر اليوم.', 'Mungkin hari ini hujan.', 'من الممكن أن', ['ممنوع أن', 'يجب أن', 'أريد أن'], 'Kemungkinan', MODAL_RULE],
  ['____ تستخدم الهاتف هنا.', 'Kamu boleh menggunakan ponsel di sini.', 'يجوز لك أن', ['يجب عليك أن', 'ممنوع أن', 'لا تستطيع أن'], 'Izin', MODAL_RULE],
  ['____ أعرّفك بنفسي.', 'Izinkan saya memperkenalkan diri.', 'اسمح لي أن', ['ممنوع أن', 'يجب أن', 'أخشى أن'], 'Permintaan sopan', MODAL_RULE],
  ['____ أتأخر عن الموعد.', 'Saya khawatir terlambat dari janji.', 'أخشى أن', ['أتمنى أن', 'ينبغي أن', 'أستطيع أن'], 'Kekhawatiran', MODAL_RULE],
  ['____ تشرب الماء كثيرا.', 'Kamu perlu banyak minum air.', 'من الضروري أن', ['ممنوع أن', 'أخشى أن', 'لا يجوز أن'], 'Keharusan', MODAL_RULE],
  ['____ أشرب الشاي بدلا من القهوة.', 'Saya lebih suka minum teh daripada kopi.', 'أفضل أن', ['يجب أن', 'أخشى أن', 'ممنوع أن'], 'Preferensi', MODAL_RULE],
  ['____ ترافقني إلى السوق؟', 'Maukah kamu menemaniku ke pasar?', 'هل تريد أن', ['يجب أن', 'ممنوع أن', 'أخشى أن'], 'Ajakan', MODAL_RULE],
  ['____ أراك قريبا.', 'Saya berharap bisa segera bertemu denganmu.', 'أرجو أن', ['ممنوع أن', 'يجب أن', 'لا أستطيع أن'], 'Harapan', MODAL_RULE],
  ['____ تحاول مرة أخرى.', 'Sebaiknya kamu mencoba sekali lagi.', 'يستحسن أن', ['ممنوع أن', 'أخشى أن', 'لا يجوز أن'], 'Nasihat', MODAL_RULE],
  ['____ يكون المدير في مكتبه الآن.', 'Mungkin direktur ada di kantornya sekarang.', 'ربما', ['ممنوع', 'أريد', 'من فضلك'], 'Kemungkinan', 'ربما + mudhari'],
  ['____ نغادر قبل الظلام.', 'Kita harus berangkat sebelum gelap.', 'لا بد أن', ['أتمنى أن', 'ممنوع أن', 'أخشى أن'], 'Keharusan', MODAL_RULE],
  ['____ تتصل بي غدا؟', 'Bisakah Anda menelepon saya besok?', 'هل بإمكانك أن', ['يجب أن', 'ممنوع أن', 'أخشى أن'], 'Permintaan', MODAL_RULE],
  ['____ أدفع الآن أم لاحقا؟', 'Apakah saya harus membayar sekarang atau nanti?', 'هل يجب أن', ['هل تحب أن', 'ممنوع أن', 'أتمنى أن'], 'Kewajiban', MODAL_RULE],
  ['____ أنسى موعدي مرة أخرى.', 'Saya tidak ingin lupa janjiku lagi.', 'لا أريد أن', ['يجب أن', 'أستطيع أن', 'يجوز أن'], 'Keinginan', MODAL_RULE],
  ['____ تصل الرسالة غدا.', 'Surat itu diperkirakan sampai besok.', 'يُتوقع أن', ['ممنوع أن', 'يجب عليك أن', 'لا أستطيع أن'], 'Perkiraan', MODAL_RULE],
  ['____ التصوير داخل المتحف.', 'Dilarang memotret di dalam museum.', 'يُمنع', ['يجوز', 'أريد', 'أستطيع'], 'Larangan', 'يُمنع + masdar'],
  ['____ أنهي العمل قبل الخامسة.', 'Saya harus menyelesaikan pekerjaan sebelum pukul lima.', 'عليّ أن', ['أتمنى أن', 'ممنوع أن', 'يجوز أن'], 'Kewajiban', 'على + dhamir + أن untuk kewajiban'],
  ['____ تكون أكثر صبرا.', 'Kamu seharusnya lebih sabar.', 'ينبغي عليك أن', ['ممنوع أن', 'أخشى أن', 'هل يمكنك أن'], 'Nasihat', MODAL_RULE],
  ['____ أساعدك؟', 'Bolehkah saya membantumu?', 'هل تسمح لي أن', ['يجب أن', 'ممنوع أن', 'أخشى أن'], 'Izin', MODAL_RULE],
  ['____ نصل في الوقت المحدد.', 'Kami berusaha sampai tepat waktu.', 'نحاول أن', ['ممنوع أن', 'نخشى أن', 'لا يجوز أن'], 'Usaha', MODAL_RULE],
  ['____ أدرس في الخارج يوما ما.', 'Saya bercita-cita belajar di luar negeri suatu hari.', 'أحلم بأن', ['ممنوع أن', 'يجب أن', 'أخشى أن'], 'Cita-cita', 'أحلم بأن + mudhari'],
  ['____ تقود السيارة بسرعة.', 'Kamu tidak boleh mengemudi dengan cepat.', 'لا يجوز أن', ['يمكنك أن', 'تحب أن', 'ينبغي أن'], 'Larangan', MODAL_RULE],
  ['____ أكون طبيبا.', 'Saya ingin menjadi dokter.', 'أريد أن', ['ممنوع أن', 'أخشى أن', 'يجب عليك أن'], 'Keinginan', MODAL_RULE],
  ['____ تأتي معنا.', 'Kamu boleh ikut bersama kami.', 'يمكنك أن', ['يجب عليك أن', 'ممنوع أن', 'أخشى أن'], 'Izin', MODAL_RULE],
  ['____ أرفض دعوتك.', 'Saya terpaksa menolak undanganmu.', 'أضطر إلى أن', ['أتمنى أن', 'يسرني أن', 'أحب أن'], 'Keterpaksaan', MODAL_RULE],
  ['____ أدعوك إلى حفلتي.', 'Saya senang mengundangmu ke pestaku.', 'يسرني أن', ['ممنوع أن', 'أخشى أن', 'يجب أن'], 'Kesenangan', MODAL_RULE],
  ['____ ننسى الماضي.', 'Lebih baik kita melupakan masa lalu.', 'من الأفضل أن', ['ممنوع أن', 'لا نستطيع أن', 'أخشى أن'], 'Nasihat', MODAL_RULE],
];

export const hardModals: ChoiceTuple[] = [
  ['____ ينتهي الفصل الدراسي.', 'Semester hampir berakhir.', 'يوشك أن', ['يجب أن', 'يجوز أن', 'أرجو أن'], 'Muqarabah', 'يوشك أن + mudhari = hampir'],
  ['____ نتغلب على هذه الصعوبات.', 'Semoga kita dapat mengatasi kesulitan-kesulitan ini.', 'لعلنا', ['ممنوع أن', 'لا يجوز أن', 'يجب ألا'], "Taraji", 'لعلّ + dhamir + mudhari'],
  ['____ نصل إلى اتفاق دون حوار.', 'Mustahil kita mencapai kesepakatan tanpa dialog.', 'من المستحيل أن', ['من الضروري أن', 'يسرنا أن', 'نود أن'], 'Kemustahilan', MODAL_RULE],
  ['____ نذكر أن الاجتماع سيبدأ مبكرا.', 'Perlu kita sebutkan bahwa rapat akan dimulai lebih awal.', 'يجدر بنا أن', ['يستحيل أن', 'نخشى ألا', 'يمنع أن'], 'Kepatutan', 'يجدر بـ + أن'],
  ['____ على كل موظف أن يلتزم بالمواعيد.', 'Setiap pegawai wajib disiplin waktu.', 'يتعين', ['يستحيل', 'يحتمل', 'يرجى'], 'Kewajiban formal', 'يتعيّن على + أن'],
  ['____ عدم التدخين في المبنى.', 'Mohon tidak merokok di gedung ini.', 'يرجى', ['يستحيل', 'لعل', 'يحتمل'], 'Permohonan formal', 'يُرجى + masdar'],
  ['____ الحضور قبل الموعد بعشر دقائق.', 'Diutamakan hadir sepuluh menit sebelum waktunya.', 'يُفضَّل', ['يستحيل', 'لعل', 'يُمنع'], 'Anjuran', 'يُفضَّل + masdar'],
  ['____ أعتذر عن التأخير.', 'Saya ingin meminta maaf atas keterlambatan.', 'أودّ أن', ['يستحيل أن', 'يُمنع أن', 'أخشى ألا'], 'Keinginan sopan', MODAL_RULE],
  ['____ يتأخر القطار بسبب الثلج.', 'Kereta kemungkinan terlambat karena salju.', 'يُحتمل أن', ['يتعين أن', 'يرجى أن', 'أود أن'], 'Kemungkinan', MODAL_RULE],
  ['____ نعيد النظر في الخطة.', 'Kita perlu meninjau ulang rencana itu.', 'لا بد لنا من أن', ['يستحيل أن', 'نخشى أن', 'يحظر أن'], 'Keharusan', 'لا بد من + أن'],
  ['____ ألا تتأخر مرة أخرى.', 'Saya harap kamu tidak terlambat lagi.', 'آمل', ['يستحيل', 'يحظر', 'أكاد'], 'Harapan', 'آمل + ألا + mudhari'],
  ['____ أصدق ما حدث.', 'Saya hampir tidak percaya apa yang terjadi.', 'لا أكاد', ['يتعين أن', 'يرجى أن', 'أود أن'], 'Muqarabah', 'لا أكاد + mudhari = hampir tidak'],
  ['____ تُسلَّم الأبحاث قبل نهاية الشهر.', 'Makalah harus diserahkan sebelum akhir bulan.', 'يجب أن', ['يستحيل أن', 'يسرني أن', 'أكاد'], 'Kewajiban', MODAL_RULE],
  ['____ الدخول إلا لحاملي التذاكر.', 'Masuk dilarang kecuali bagi pemegang tiket.', 'يُحظر', ['يُرجى', 'يتمنى', 'يستطيع'], 'Larangan formal', 'يُحظر + masdar'],
  ['____ أن أشكركم على حسن الاستقبال.', 'Izinkan saya berterima kasih atas sambutan baik Anda.', 'اسمحوا لي', ['يحظر علي', 'يستحيل', 'لا أكاد'], 'Permintaan sopan', 'اسمحوا لي أن'],
  ['____ يكون الطقس معتدلا غدا.', 'Cuaca besok diperkirakan sedang.', 'من المتوقع أن', ['من المستحيل أن', 'يحظر أن', 'أود أن'], 'Perkiraan', MODAL_RULE],
  ['____ نتعاون من أجل المصلحة العامة.', 'Kita sepatutnya bekerja sama demi kepentingan umum.', 'ينبغي لنا أن', ['يحظر علينا أن', 'يستحيل أن', 'نخشى أن'], 'Kepatutan', MODAL_RULE],
  ['____ تنجح الخطة إذا لم نستعد جيدا.', 'Saya khawatir rencana itu tidak berhasil jika kita tidak bersiap dengan baik.', 'أخشى ألا', ['يتعين أن', 'يُرجى أن', 'أود أن'], 'Kekhawatiran', 'أخشى ألا + mudhari'],
  ['____ أقدم لكم ضيفنا الكريم.', 'Dengan senang hati saya memperkenalkan tamu terhormat kita.', 'يسعدني أن', ['يحظر أن', 'أخشى أن', 'يستحيل أن'], 'Kesenangan', MODAL_RULE],
  ['____ تتخذ قرارا قبل أن تسمع الطرفين.', 'Tidak sepatutnya kamu mengambil keputusan sebelum mendengar kedua pihak.', 'لا ينبغي أن', ['يسعدني أن', 'آمل أن', 'يتعين أن'], 'Larangan halus', MODAL_RULE],
  ['____ على الطلاب إحضار بطاقاتهم.', 'Para siswa wajib membawa kartu mereka.', 'يجب', ['يستحيل', 'يسر', 'لعل'], 'Kewajiban', 'يجب على + masdar'],
  ['____ أن أجيب عن هذا السؤال الآن.', 'Saya tidak dapat menjawab pertanyaan ini sekarang.', 'لا يسعني', ['يسرني', 'آمل', 'يحتمل'], 'Ketidakmampuan', 'لا يسعني أن'],
  ['____ المشروع أن يكتمل.', 'Proyek itu hampir selesai.', 'كاد', ['يجب', 'يُرجى', 'يحظر'], 'Muqarabah', 'كاد + (أن) + mudhari'],
  ['____ أن أعبر عن امتناني.', 'Saya ingin menyampaikan rasa terima kasih saya.', 'أود', ['يحظر', 'يستحيل', 'كاد'], 'Keinginan sopan', 'أودّ أن'],
  ['____ تقديم الطلب إلكترونيا.', 'Permohonan dapat diajukan secara elektronik.', 'يمكن', ['يحظر', 'يستحيل', 'كاد'], 'Kemungkinan', 'يمكن + masdar'],
  ['____ التزام الهدوء أثناء الامتحان.', 'Harap tenang selama ujian.', 'يُرجى', ['يستحيل', 'كاد', 'لعل'], 'Permohonan formal', 'يُرجى + masdar'],
  ['____ أن ننجح دون عمل جاد.', 'Tidak mungkin kita berhasil tanpa kerja keras.', 'لا يمكن', ['يسرنا', 'نأمل', 'يتعين علينا'], 'Kemustahilan', 'لا يمكن أن'],
  ['____ الإشارة إلى أن البيانات أولية.', 'Perlu dicatat bahwa data ini masih awal.', 'تجدر', ['يحظر', 'يستحيل', 'كاد'], 'Kepatutan', 'تجدر الإشارة إلى'],
  ['____ أن أنصحك بالراحة.', 'Izinkan saya menasihatimu untuk beristirahat.', 'دعني', ['يحظر علي', 'يستحيل', 'كاد'], 'Permintaan sopan', 'دعني + أن'],
  ['____ أن يكون الخبر صحيحا.', 'Semoga saja berita itu benar.', 'عسى', ['يحظر', 'يتعين', 'لا يسعني'], 'Harapan', 'عسى أن + mudhari'],
];

const IDZA = 'إذا + madhi untuk syarat yang mungkin terjadi';
const IN = 'إنْ + dua fi’il mudhari majzum';
const LAW = 'لو + madhi, jawabnya memakai لـ';

export const easyConditionals: ChoiceTuple[] = [
  ['إذا ____ مبكرا سنصل في الوقت.', 'Jika kita berangkat lebih awal, kita akan sampai tepat waktu.', 'خرجنا', ['نخرجون', 'اخرج', 'خرجوا'], 'إذا', IDZA],
  ['إذا ____ فاشرب الماء.', 'Jika kamu haus, minumlah air.', 'عطشتَ', ['عطشنا', 'اعطش', 'عطشوا'], 'إذا', IDZA],
  ['إذا ____ المطر سنبقى في البيت.', 'Jika hujan turun, kami akan tetap di rumah.', 'نزل', ['ينزلون', 'انزل', 'نزلنا'], 'إذا', IDZA],
  ['إذا ____ الدرس فاسأل المعلم.', 'Jika kamu tidak paham pelajaran, tanyalah guru.', 'لم تفهم', ['لم يفهموا', 'افهم', 'فهمنا'], 'إذا', 'إذا + nafi + mudhari majzum'],
  ['إذا ____ إلى السوق فاشتر خبزا.', 'Jika kamu pergi ke pasar, belilah roti.', 'ذهبتَ', ['ذهبوا', 'اذهب', 'نذهبون'], 'إذا', IDZA],
  ['إذا ____ الشمس خرجنا إلى الحديقة.', 'Jika matahari bersinar, kami keluar ke taman.', 'أشرقت', ['أشرق', 'أشرقوا', 'أشرقي'], 'إذا', 'الشمس muannats: madhi memakai ـتْ'],
  ['إذا ____ فنم مبكرا.', 'Jika kamu lelah, tidurlah lebih awal.', 'تعبتَ', ['تعبوا', 'اتعب', 'تعبنا'], 'إذا', IDZA],
  ['إذا ____ الحافلة سنذهب مشيا.', 'Jika bus terlambat, kami akan berjalan kaki.', 'تأخرت', ['تأخروا', 'تأخرنا', 'تأخري'], 'إذا', 'الحافلة muannats, fi’il ikut muannats'],
  ['إذا ____ صديقي سأفرح كثيرا.', 'Jika temanku datang, saya akan sangat senang.', 'جاء', ['جاءت', 'جئنا', 'جاؤوا'], 'إذا', IDZA],
  ['إذا ____ جيدا تنجح.', 'Jika kamu belajar dengan baik, kamu berhasil.', 'درستَ', ['درسوا', 'ادرس', 'درسنا'], 'إذا', IDZA],
  ['إن ____ أحترمك.', 'Jika kamu menghormatiku, aku menghormatimu.', 'تحترمني', ['احترمني', 'يحترمونني', 'نحترمك'], 'إنْ', IN],
  ['إذا ____ الهاتف فأجب.', 'Jika telepon berdering, jawablah.', 'رنّ', ['رنّت', 'رنّوا', 'يرنّون'], 'إذا', IDZA],
  ['إذا ____ الطعام فكله.', 'Jika kamu suka makanan itu, makanlah.', 'أحببتَ', ['أحبوا', 'أحببنا', 'أحبّي'], 'إذا', IDZA],
  ['إذا ____ البرد فالبس معطفا.', 'Jika dingin semakin parah, pakailah mantel.', 'اشتد', ['اشتدت', 'اشتدوا', 'يشتدون'], 'إذا', IDZA],
  ['إذا ____ الباب فأغلقه بعدك.', 'Jika kamu membuka pintu, tutuplah setelahnya.', 'فتحتَ', ['فتحوا', 'افتح', 'فتحنا'], 'إذا', IDZA],
  ['إذا ____ أحمد فسلّم عليه.', 'Jika kamu bertemu Ahmad, sampaikan salam kepadanya.', 'قابلتَ', ['قابلوا', 'قابل', 'قابلنا'], 'إذا', IDZA],
  ['إذا ____ الطعام سنأكل معا.', 'Jika makanan sudah siap, kita akan makan bersama.', 'جهز', ['جهزت', 'جهزوا', 'جهزنا'], 'إذا', IDZA],
  ['إذا ____ فاتصل بي.', 'Jika kamu sudah sampai, teleponlah aku.', 'وصلتَ', ['وصلوا', 'صل', 'وصلنا'], 'إذا', IDZA],
  ['إذا ____ الأطفال فلا تزعجهم.', 'Jika anak-anak tidur, jangan ganggu mereka.', 'نام', ['ناموا', 'نامت', 'نمنا'], 'إذا', "fi'il di depan fa'il jamak tetap mufrad"],
  ['إذا ____ وقت فراغ نلعب الكرة.', 'Jika kami punya waktu luang, kami bermain bola.', 'كان لنا', ['كانوا لنا', 'كن لنا', 'يكونون لنا'], 'إذا', IDZA],
  ['إذا ____ ضيوف فاستقبلهم بابتسامة.', 'Jika tamu datang, sambutlah mereka dengan senyum.', 'جاءك', ['جئتُم', 'جئنا', 'جئتِ'], 'إذا', IDZA],
  ['إذا ____ الطريق مزدحما نتأخر.', 'Jika jalanan macet, kami terlambat.', 'كان', ['كانت', 'كانوا', 'كنا'], 'إذا', 'إذا + fi’il naqish + khabar manshub'],
  ['إذا ____ المعلم فقف احتراما.', 'Jika guru masuk, berdirilah untuk menghormati.', 'دخل', ['دخلت', 'دخلوا', 'ادخل'], 'إذا', IDZA],
  ['إذا ____ الامتحان سهلا نجح الجميع.', 'Jika ujiannya mudah, semua orang lulus.', 'كان', ['كانت', 'كانوا', 'كن'], 'إذا', 'إذا + fi’il naqish + khabar manshub'],
  ['إذا ____ شيئا فاكتبه.', 'Jika kamu mendengar sesuatu, tulislah.', 'سمعتَ', ['سمعوا', 'اسمع', 'سمعنا'], 'إذا', IDZA],
  ['إذا ____ الكتاب فأعده إلى المكتبة.', 'Jika kamu sudah selesai membaca buku itu, kembalikan ke perpustakaan.', 'قرأتَ', ['قرأوا', 'اقرأ', 'قرأنا'], 'إذا', IDZA],
  ['إذا ____ فاغسل يديك.', 'Jika kamu sudah makan, cucilah tanganmu.', 'أكلتَ', ['أكلوا', 'كُل', 'أكلنا'], 'إذا', IDZA],
  ['إذا ____ الماء في الكوب فاملأه.', 'Jika air di gelas habis, isilah.', 'نفد', ['نفدت', 'نفدوا', 'نفدنا'], 'إذا', IDZA],
  ['إذا ____ الطالب صحيحا فامدحه.', 'Jika siswa itu menjawab dengan benar, pujilah dia.', 'أجاب', ['أجابت', 'أجابوا', 'أجبنا'], 'إذا', IDZA],
  ['إذا ____ الحفلة فاتصل بي.', 'Jika kamu menghadiri pesta, hubungi aku.', 'حضرتَ', ['حضروا', 'احضر', 'حضرنا'], 'إذا', IDZA],
];

export const mediumConditionals: ChoiceTuple[] = [
  ['إن ____ تنجح.', 'Jika kamu belajar, kamu akan berhasil.', 'تدرسْ', ['درسوا', 'ادرس', 'يدرسون'], 'إنْ', IN],
  ['من ____ يجد.', 'Barang siapa bersungguh-sungguh, ia akan mendapatkan hasil.', 'يجتهدْ', ['يجتهدون', 'تجتهدين', 'نجتهد'], 'مَنْ', 'مَنْ syarthiyah + mudhari majzum'],
  ['كلما ____ القراءة زادت معرفتك.', 'Semakin sering kamu membaca, semakin bertambah pengetahuanmu.', 'أكثرتَ من', ['تكثر من', 'أكثروا من', 'أكثرنا من'], 'كلما', 'كلما + madhi'],
  ['متى ____ أخبرني.', 'Kapan pun kamu sampai, kabari aku.', 'تصلْ', ['وصلوا', 'صل', 'نصلون'], 'متى', 'متى + mudhari majzum'],
  ['أينما ____ أذهب معك.', 'Ke mana pun kamu pergi, aku ikut denganmu.', 'تذهبْ', ['ذهبوا', 'اذهب', 'يذهبون'], 'أينما', 'أينما + mudhari majzum'],
  ['ما ____ من خير تجده.', 'Kebaikan apa pun yang kamu lakukan, kamu akan menemukannya.', 'تفعلْ', ['فعلوا', 'افعل', 'يفعلون'], 'ما', 'ما syarthiyah + mudhari majzum'],
  ['إن ____ الصدق نجوت.', 'Jika kamu berkata jujur, kamu selamat.', 'قلتَ', ['تقولون', 'قل', 'قولوا'], 'إنْ', 'إنْ + madhi + madhi'],
  ['إن لم ____ الآن فاتك القطار.', 'Jika kamu tidak berangkat sekarang, kamu ketinggalan kereta.', 'تخرجْ', ['تخرجون', 'اخرج', 'خرجوا'], 'إنْ', 'إنْ لم + mudhari majzum'],
  ['مهما ____ فلن أغير رأيي.', 'Apa pun yang kamu katakan, aku tidak akan mengubah pendapatku.', 'تقلْ', ['قل', 'يقولون', 'نقولون'], 'مهما', 'مهما + mudhari majzum, jawab dengan فـ'],
  ['حيثما ____ تجد أصدقاء.', 'Di mana pun kamu tinggal, kamu menemukan teman.', 'تسكنْ', ['سكنوا', 'اسكن', 'يسكنون'], 'حيثما', 'حيثما + mudhari majzum'],
  ['من ____ الناس يحترموه.', 'Barang siapa menghormati orang, orang akan menghormatinya.', 'يحترمْ', ['يحترمون', 'تحترمين', 'نحترم'], 'مَنْ', 'مَنْ syarthiyah + mudhari majzum'],
  ['إذا ____ الطلاب الدرس فهموه.', 'Jika para siswa memperhatikan pelajaran, mereka memahaminya.', 'انتبه', ['انتبهوا', 'ينتبهون', 'انتبهي'], 'إذا', "fi'il di depan fa'il jamak tetap mufrad"],
  ['كلما ____ الصيف ازدادت الحرارة.', 'Setiap kali musim panas datang, panas meningkat.', 'جاء', ['يجيء', 'جاءت', 'جئنا'], 'كلما', 'كلما + madhi'],
  ['إن ____ الله ينصركم.', 'Jika kalian menolong (agama) Allah, Dia akan menolong kalian.', 'تنصروا', ['تنصرون', 'انصروا', 'نصرنا'], 'إنْ', 'af’al khamsah majzum membuang nun'],
  ['لو ____ مبكرا لما فاتك الدرس.', 'Seandainya kamu bangun lebih awal, kamu tidak akan ketinggalan pelajaran.', 'استيقظتَ', ['تستيقظون', 'استيقظوا', 'نستيقظ'], 'لو', LAW],
  ['لو كنتُ غنيا ____ بيتا كبيرا.', 'Seandainya saya kaya, saya akan membeli rumah besar.', 'لاشتريت', ['سأشتري', 'أشتري', 'اشترِ'], 'لو', LAW],
  ['إن ____ الواجب فلن تلعب.', 'Jika kamu tidak menyelesaikan PR, kamu tidak akan bermain.', 'لم تنهِ', ['لن تنهي', 'أنهوا', 'لا ينهون'], 'إنْ', 'إنْ + nafi majzum, jawab dengan فـ'],
  ['من ____ علما فليعلّمه.', 'Barang siapa mengetahui suatu ilmu, hendaklah ia mengajarkannya.', 'عرف', ['عرفوا', 'اعرف', 'يعرفون'], 'مَنْ', 'مَنْ + madhi, jawab dengan فـ + lam amr'],
  ['متى ____ الطلاب بدأ الدرس.', 'Begitu para siswa hadir, pelajaran dimulai.', 'حضر', ['حضروا', 'يحضرون', 'احضروا'], 'متى', "fi'il di depan fa'il jamak tetap mufrad"],
  ['إذا ____ العمل باكرا فسنذهب إلى السينما.', 'Jika pekerjaan selesai lebih awal, kita akan pergi ke bioskop.', 'انتهى', ['انتهت', 'انتهوا', 'انتهينا'], 'إذا', IDZA],
  ['أينما ____ في المدينة وجدت مساجد.', 'Ke mana pun kamu pergi di kota itu, kamu menemukan masjid.', 'ذهبتَ', ['تذهبون', 'اذهب', 'يذهبان'], 'أينما', 'أينما + madhi + madhi'],
  ['إن ____ الفرصة فلا تضيعها.', 'Jika kesempatan datang kepadamu, jangan sia-siakan.', 'جاءتك', ['جاءك', 'جاؤوك', 'جئتك'], 'إنْ', 'الفرصة muannats: جاءتْ'],
  ['كلما ____ الطفل ابتسمت أمه.', 'Setiap kali anak itu tertawa, ibunya tersenyum.', 'ضحك', ['يضحك', 'ضحكت', 'ضحكوا'], 'كلما', 'كلما + madhi'],
  ['لو ____ الحقيقة لأخبرتك.', 'Seandainya aku tahu kebenarannya, aku pasti memberitahumu.', 'عرفتُ', ['عرفوا', 'اعرف', 'يعرفون'], 'لو', LAW],
  ['إن ____ الامتحان فسأكافئك.', 'Jika kamu lulus ujian, aku akan memberimu hadiah.', 'نجحتَ في', ['نجحوا في', 'انجح في', 'ينجحون في'], 'إنْ', 'jawab dengan سـ memakai فـ'],
  ['ما ____ من مال ينفعك.', 'Harta apa pun yang kamu tabung akan bermanfaat bagimu.', 'تدخرْ', ['يدخرون', 'ندخرون', 'ادخروا'], 'ما', 'ما syarthiyah + mudhari majzum'],
  ['إن ____ صادقا صدّقك الناس.', 'Jika kamu jujur, orang-orang memercayaimu.', 'كنتَ', ['كانوا', 'كن', 'يكونون'], 'إنْ', 'إنْ + كان + khabar manshub'],
  ['كلما ____ المعلم سؤالا رفع الطلاب أيديهم.', 'Setiap kali guru mengajukan pertanyaan, para siswa mengangkat tangan.', 'طرح', ['يطرح', 'طرحت', 'طرحوا'], 'كلما', 'كلما + madhi'],
  ['إذا لم ____ البطاقة فلن تدخل.', 'Jika kamu tidak membawa kartu, kamu tidak akan masuk.', 'تحملْ', ['حملوا', 'احمل', 'يحملون'], 'إذا', 'إذا لم + mudhari majzum'],
  ['متى ما ____ إلى إندونيسيا فزرني.', 'Kapan pun kamu datang ke Indonesia, kunjungilah aku.', 'جئتَ', ['جاؤوا', 'تعال', 'يجيئون'], 'متى ما', 'متى ما + madhi, jawab perintah dengan فـ'],
];

export const hardConditionals: ChoiceTuple[] = [
  ['لولا ____ لغرقت السفينة.', 'Kalau bukan karena kapten, kapal itu tenggelam.', 'القبطانُ', ['القبطانَ', 'القبطانِ', 'قبطانًا'], 'لولا', "isim setelah لولا adalah mubtada' marfu'"],
  ['لولا المطر ____ المحصول.', 'Kalau bukan karena hujan, panen itu rusak.', 'لفسد', ['فسد', 'سيفسد', 'يفسد'], 'لولا', 'jawab لولا madhi + لـ'],
  ['لو اجتهدتَ ____.', 'Seandainya kamu rajin, kamu pasti berhasil.', 'لنجحتَ', ['ستنجح', 'تنجح', 'فنجحت'], 'لو', LAW],
  ['لو لم ____ المظلة لابتللت.', 'Seandainya aku tidak membawa payung, aku pasti basah.', 'أحملِ', ['حملتُ', 'سأحمل', 'احمل'], 'لو', 'لو لم + mudhari majzum'],
  ['إن ____ فستندم.', 'Jika kamu menunda, kamu akan menyesal.', 'تؤجلْ', ['تؤجلون', 'يؤجلان', 'نؤجلون'], 'إنْ', 'jawab dengan سـ memakai فـ'],
  ['من يزرعْ خيرا ____ خيرا.', 'Barang siapa menanam kebaikan, ia akan menuai kebaikan.', 'يحصدْ', ['يحصدون', 'تحصدين', 'احصدوا'], 'مَنْ', 'jawab syarat mudhari majzum'],
  ['إن تجتهدْ ____.', 'Jika kamu bersungguh-sungguh, kamu pasti akan sukses.', 'فستنجح', ['ستنجح', 'تنجحون', 'فنجحوا'], 'إنْ', 'jawab dengan سـ wajib didahului فـ'],
  ['إن تأتِ ____.', 'Jika kamu datang, aku akan memuliakanmu.', 'أكرمْك', ['سأكرمك', 'أكرمكم', 'أكرموك'], 'إنْ', IN],
  ['إذا جاءك سائل ____.', 'Jika datang peminta kepadamu, jangan menolaknya.', 'فلا تردّه', ['لا تردّه', 'لن ترده', 'رددته'], 'إذا', 'jawab berupa larangan wajib memakai فـ'],
  ['لو ____ الطالب السؤال لما أخطأ.', 'Seandainya siswa itu memahami soal, ia tidak akan salah.', 'فهم', ['يفهم', 'افهم', 'فهموا'], 'لو', 'لو + madhi, jawab negatif لما'],
  ['أمّا الطلاب ____ ناجحون.', 'Adapun para siswa, mereka lulus.', 'فهم', ['هم', 'فهما', 'فهو'], 'أمّا', 'أمّا ... فـ'],
  ['لولا أنك ساعدتني ____ المهمة.', 'Kalau bukan karena kamu membantuku, aku tidak akan menyelesaikan tugas.', 'لما أنهيتُ', ['لن أنهي', 'لا أنهي', 'سأنهي'], 'لولا', 'jawab لولا negatif memakai madhi'],
  ['إن كان الجو جميلا ____ إلى البحر.', 'Jika cuaca bagus, kami akan pergi ke pantai.', 'فسنذهب', ['سنذهب', 'نذهبوا', 'اذهبوا'], 'إنْ', 'jawab dengan سـ memakai فـ'],
  ['مَن ____ عن العلم ضاع.', 'Barang siapa berpaling dari ilmu, ia akan tersesat.', 'أعرض', ['يعرضون', 'أعرضوا', 'أعرضي'], 'مَنْ', 'مَنْ + madhi + madhi'],
  ['لو أن الوقت يسمح ____ معكم.', 'Seandainya waktu memungkinkan, aku akan ikut bersama kalian.', 'لذهبتُ', ['سأذهب', 'أذهب', 'اذهب'], 'لو', LAW],
  ['إن لم تجد ما تحب ____ ما تجد.', 'Jika kamu tidak mendapatkan apa yang kamu suka, sukailah apa yang ada.', 'فأحِبَّ', ['أحِبَّ', 'تحبُّ', 'ستحبُّ'], 'إنْ', 'jawab berupa perintah memakai فـ'],
  ['كلّما ازداد العلم ____ التواضع.', 'Semakin bertambah ilmu, semakin bertambah kerendahan hati.', 'ازداد', ['يزداد', 'سيزداد', 'ازدادت'], 'كلما', 'كلما + madhi ... madhi'],
  ['لولا ____ الطبيب لمات المريض.', 'Kalau bukan karena kedatangan dokter, pasien itu meninggal.', 'مجيءُ', ['جاء', 'يجيء', 'مجيئًا'], 'لولا', "setelah لولا isim (masdar) marfu'"],
  ['إن ____ فإن الله غفور رحيم.', 'Jika kalian bertaubat, sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.', 'تتوبوا', ['تتوبون', 'توبوا', 'يتوبان'], 'إنْ', 'af’al khamsah majzum membuang nun'],
  ['من كان يؤمن بالله واليوم الآخر ____ خيرا أو ليصمت.', 'Barang siapa beriman kepada Allah dan hari akhir, hendaklah ia berkata baik atau diam.', 'فليقل', ['يقول', 'قال', 'سيقول'], 'مَنْ', 'jawab dengan lam amr memakai فـ'],
  ['إذا ما ____ النتائج فسنعلنها.', 'Apabila hasilnya sudah keluar, kami akan mengumumkannya.', 'ظهرت', ['ظهر', 'ظهروا', 'تظهرون'], 'إذا ما', 'jamak tak berakal + madhi muannats'],
  ['لئن ____ لأزيدنكم.', 'Jika kalian bersyukur, pasti Aku tambah nikmat kalian.', 'شكرتم', ['تشكرون', 'اشكروا', 'شكروا'], 'لئن', 'لئن + madhi, jawab qasam'],
  ['لو ____ الشباب يعرفون قيمة الوقت لما ضيّعوه.', 'Seandainya para pemuda mengetahui nilai waktu, mereka tidak akan menyia-nyiakannya.', 'كان', ['كانوا', 'يكون', 'كن'], 'لو', "fi'il di depan fa'il jamak tetap mufrad"],
  ['إن ____ المؤتمر غدا فسأحضره.', 'Jika konferensi diadakan besok, aku akan menghadirinya.', 'عُقِدَ', ['عَقَدَ', 'يَعْقِدُونَ', 'اُعْقُدْ'], 'إنْ', 'madhi majhul dalam syarat'],
  ['إذا ____ الأمانة فانتظر الساعة.', 'Apabila amanah disia-siakan, tunggulah kehancuran.', 'ضُيِّعَتِ', ['ضَيَّعَتْ', 'ضُيِّعَ', 'ضَيَّعُوا'], 'إذا', 'madhi majhul muannats'],
  ['لو أنهم ____ بالنصيحة لنجحوا.', 'Seandainya mereka mengikuti nasihat, mereka pasti berhasil.', 'عملوا', ['يعملون', 'اعملوا', 'عمل'], 'لو', LAW],
  ['إن ____ فستصل إلى هدفك.', 'Jika kamu bersabar, kamu akan mencapai tujuanmu.', 'صبرتَ', ['تصبرون', 'اصبر', 'صبروا'], 'إنْ', 'jawab dengan سـ memakai فـ'],
  ['أينما تكونوا ____ الموت.', 'Di mana pun kalian berada, kematian akan mendapatkan kalian.', 'يُدْرِكْكُمُ', ['سَيُدْرِكُكُمُ', 'أَدْرِكُوا', 'يُدْرِكُونَكُمْ'], 'أينما', IN],
  ['لولا العلماء ____ الناس كالبهائم.', 'Kalau bukan karena para ulama, manusia akan seperti binatang ternak.', 'لكان', ['كان', 'يكون', 'سيكون'], 'لولا', 'jawab لولا madhi + لـ'],
  ['إن لم ____ فاسأل.', 'Jika kamu tidak tahu, bertanyalah.', 'تعلمْ', ['علمتُ', 'اعلم', 'يعلمون'], 'إنْ', 'إنْ لم + mudhari majzum'],
];

// Question Builder: label is the question type; the rule comes from the answer word.
export const questionRules: Record<string, string> = {
  'هل': 'هل untuk pertanyaan ya/tidak.',
  'أ': 'أ untuk pertanyaan ya/tidak atau memilih dengan أم.',
  'ما': 'ما untuk menanyakan benda/nama, biasanya sebelum isim.',
  'ماذا': 'ماذا untuk menanyakan benda, biasanya sebelum fi’il.',
  'من': 'من untuk menanyakan orang.',
  'أين': 'أين untuk menanyakan tempat.',
  'متى': 'متى untuk menanyakan waktu.',
  'كيف': 'كيف untuk menanyakan keadaan atau cara.',
  'كم': 'كم untuk jumlah; tamyiznya mufrad manshub.',
  'لماذا': 'لماذا untuk menanyakan alasan.',
  'أيّ': 'أيّ untuk memilih salah satu dari beberapa.',
  'بكم': 'بكم untuk menanyakan harga.',
  'من أين': 'من أين untuk menanyakan asal.',
  'إلى أين': 'إلى أين untuk menanyakan tujuan.',
  'لمن': 'لمن untuk menanyakan pemilik atau penerima.',
  'مع من': 'مع من untuk menanyakan teman/pendamping.',
  'منذ متى': 'منذ متى untuk menanyakan sejak kapan.',
  'كم مرة': 'كم مرة untuk menanyakan frekuensi.',
  'بماذا': 'بماذا untuk menanyakan alat/sarana.',
  'عمّ': 'عمّ = عن + ما: tentang apa.',
  'ممّ': 'ممّ = من + ما: dari apa.',
  'فيمَ': 'فيمَ = في + ما: tentang/dalam hal apa.',
  'بمَ': 'بمَ = بـ + ما: dengan apa.',
  'لِمَ': 'لِمَ = لـ + ما: mengapa.',
  'أليس': 'أليس untuk "bukankah", khabarnya manshub.',
  'أنّى': 'أنّى untuk "dari mana/bagaimana".',
  'إلامَ': 'إلامَ = إلى + ما: ke arah apa.',
  'هلّا': 'هلّا untuk ajakan/anjuran halus.',
  'ألم': 'ألم untuk "bukankah sudah" (lampau).',
  'أيّان': 'أيّان untuk waktu yang jauh/agung.',
  'ألا': 'ألا untuk menawarkan atau mengajak.',
  'علامَ': 'علامَ = على + ما: atas apa.',
  'إلى متى': 'إلى متى untuk menanyakan sampai kapan.',
};

export const easyQuestions: ChoiceTuple[] = [
  ['____ اسمك؟', 'Siapa namamu?', 'ما', ['أين', 'متى', 'كم'], 'Nama', ''],
  ['____ تسكن؟', 'Di mana kamu tinggal?', 'أين', ['هل', 'كم', 'من'], 'Tempat', ''],
  ['____ تتعلم العربية؟', 'Mengapa kamu belajar bahasa Arab?', 'لماذا', ['متى', 'كم', 'أين'], 'Alasan', ''],
  ['____ حالك؟', 'Bagaimana kabarmu?', 'كيف', ['ماذا', 'من', 'هل'], 'Keadaan', ''],
  ['____ هذا؟', 'Siapa ini?', 'من', ['كم', 'متى', 'أين'], 'Orang', ''],
  ['____ أنت طالب؟', 'Apakah kamu seorang siswa?', 'هل', ['ما', 'كيف', 'كم'], 'Ya/tidak', ''],
  ['____ عمرك؟', 'Berapa umurmu?', 'كم', ['أين', 'ماذا', 'هل'], 'Jumlah', ''],
  ['____ تأكل؟', 'Apa yang kamu makan?', 'ماذا', ['أين', 'من', 'كم'], 'Benda', ''],
  ['____ تنام؟', 'Kapan kamu tidur?', 'متى', ['ماذا', 'كم', 'من'], 'Waktu', ''],
  ['____ المدرسة؟', 'Di mana sekolahnya?', 'أين', ['كيف', 'ماذا', 'هل'], 'Tempat', ''],
  ['____ معلمك؟', 'Siapa gurumu?', 'من', ['ماذا', 'متى', 'كم'], 'Orang', ''],
  ['____ هذا الكتاب لك؟', 'Apakah buku ini milikmu?', 'هل', ['من', 'أين', 'ماذا'], 'Ya/tidak', ''],
  ['____ أخا لك؟', 'Berapa saudara laki-lakimu?', 'كم', ['هل', 'ماذا', 'لماذا'], 'Jumlah', ''],
  ['____ تشرب؟', 'Apa yang kamu minum?', 'ماذا', ['كم', 'أين', 'متى'], 'Benda', ''],
  ['____ الجو اليوم؟', 'Bagaimana cuaca hari ini?', 'كيف', ['من', 'هل', 'متى'], 'Keadaan', ''],
  ['____ تذهب إلى المدرسة؟', 'Kapan kamu pergi ke sekolah?', 'متى', ['ماذا', 'من', 'ما'], 'Waktu', ''],
  ['____ لونك المفضل؟', 'Apa warna favoritmu?', 'ما', ['من', 'أين', 'هل'], 'Benda', ''],
  ['____ في الفصل؟', 'Siapa yang ada di kelas?', 'من', ['متى', 'كيف', 'هل'], 'Orang', ''],
  ['____ تحب القهوة؟', 'Apakah kamu suka kopi?', 'هل', ['ماذا', 'من', 'كم'], 'Ya/tidak', ''],
  ['____ القلم؟', 'Di mana pulpennya?', 'أين', ['كم', 'هل', 'من'], 'Tempat', ''],
  ['____ أنت حزين؟', 'Mengapa kamu sedih?', 'لماذا', ['متى', 'كم', 'ماذا'], 'Alasan', ''],
  ['____ تكتب؟', 'Apa yang kamu tulis?', 'ماذا', ['من', 'أين', 'كم'], 'Benda', ''],
  ['____ تعود إلى البيت؟', 'Kapan kamu pulang ke rumah?', 'متى', ['ماذا', 'من', 'ما'], 'Waktu', ''],
  ['____ يوما في الأسبوع؟', 'Ada berapa hari dalam seminggu?', 'كم', ['ما', 'هل', 'أين'], 'Jumlah', ''],
  ['____ هذه؟', 'Apa ini?', 'ما', ['من', 'متى', 'كم'], 'Benda', ''],
  ['____ تصل إلى المطار؟', 'Bagaimana caramu sampai ke bandara?', 'كيف', ['ماذا', 'من', 'كم'], 'Cara', ''],
  ['____ الطبيب في المستشفى؟', 'Apakah dokter ada di rumah sakit?', 'هل', ['ماذا', 'كم', 'لماذا'], 'Ya/tidak', ''],
  ['____ أبوك؟', 'Di mana ayahmu?', 'أين', ['كم', 'ماذا', 'هل'], 'Tempat', ''],
  ['____ تضحك؟', 'Mengapa kamu tertawa?', 'لماذا', ['من', 'كم', 'ماذا'], 'Alasan', ''],
  ['____ جاء معك؟', 'Siapa yang datang bersamamu?', 'من', ['ماذا', 'متى', 'كم'], 'Orang', ''],
];

export const mediumQuestions: ChoiceTuple[] = [
  ['____ هذا القميص؟', 'Berapa harga kemeja ini?', 'بكم', ['مع من', 'من أين', 'لمن'], 'Harga', ''],
  ['____ أنت؟', 'Dari mana asalmu?', 'من أين', ['إلى أين', 'مع من', 'لمن'], 'Asal', ''],
  ['____ تذهب بعد الدرس؟', 'Ke mana kamu pergi setelah pelajaran?', 'إلى أين', ['من أين', 'لمن', 'منذ متى'], 'Tujuan', ''],
  ['____ هذه السيارة؟', 'Milik siapa mobil ini?', 'لمن', ['مع من', 'من أين', 'منذ متى'], 'Kepemilikan', ''],
  ['____ تسكن في جاكرتا؟', 'Dengan siapa kamu tinggal di Jakarta?', 'مع من', ['لمن', 'بكم', 'منذ متى'], 'Pendamping', ''],
  ['____ تدرس العربية؟', 'Sejak kapan kamu belajar bahasa Arab?', 'منذ متى', ['إلى أين', 'لمن', 'بكم'], 'Sejak', ''],
  ['____ تصلي في اليوم؟', 'Berapa kali kamu shalat dalam sehari?', 'كم مرة', ['لمن', 'من أين', 'منذ متى'], 'Frekuensi', ''],
  ['____ لغة تتكلم؟', 'Bahasa apa yang kamu kuasai?', 'أيّ', ['هل', 'لماذا', 'متى'], 'Pilihan', ''],
  ['____تحب الشاي أم القهوة؟', 'Kamu suka teh atau kopi?', 'أ', ['هل', 'ما', 'كيف'], 'Memilih', ''],
  ['____ فعلت في العطلة؟', 'Apa yang kamu lakukan saat liburan?', 'ماذا', ['لمن', 'من أين', 'منذ متى'], 'Benda', ''],
  ['____ الساعة الآن؟', 'Jam berapa sekarang?', 'كم', ['أيّ', 'لمن', 'من أين'], 'Jumlah', ''],
  ['____ كتاب قرأت؟', 'Buku apa yang kamu baca?', 'أيّ', ['لمن', 'كيف', 'منذ متى'], 'Pilihan', ''],
  ['____ تتصل بأمك؟', 'Seberapa sering kamu menelepon ibumu?', 'كم مرة', ['لمن', 'إلى أين', 'من أين'], 'Frekuensi', ''],
  ['____ هذا القلم؟', 'Milik siapa pulpen ini?', 'لمن', ['منذ متى', 'إلى أين', 'مع من'], 'Kepemilikan', ''],
  ['____ تسافر في العطلة؟', 'Dengan siapa kamu bepergian saat liburan?', 'مع من', ['لمن', 'منذ متى', 'بكم'], 'Pendamping', ''],
  ['____ وصلت هذه الرسالة؟', 'Dari mana surat ini datang?', 'من أين', ['إلى أين', 'لمن', 'كم مرة'], 'Asal', ''],
  ['____ تعمل في هذه الشركة؟', 'Sejak kapan kamu bekerja di perusahaan ini?', 'منذ متى', ['إلى أين', 'لمن', 'مع من'], 'Sejak', ''],
  ['____ الكيلو من التفاح؟', 'Berapa harga sekilo apel?', 'بكم', ['لمن', 'منذ متى', 'مع من'], 'Harga', ''],
  ['____ يوم تفضل؟', 'Hari apa yang kamu sukai?', 'أيّ', ['هل', 'لماذا', 'من أين'], 'Pilihan', ''],
  ['____ يذهب هذا القطار؟', 'Ke mana kereta ini pergi?', 'إلى أين', ['لمن', 'بكم', 'منذ متى'], 'Tujuan', ''],
  ['____ عمر أخيك؟', 'Berapa umur saudaramu?', 'كم', ['أيّ', 'لمن', 'من أين'], 'Jumlah', ''],
  ['____ تريد أن تشرب؟', 'Kamu mau minum apa?', 'ماذا', ['لمن', 'منذ متى', 'مع من'], 'Benda', ''],
  ['____ تذهب إلى الجامعة؟', 'Naik apa kamu pergi ke kampus?', 'بماذا', ['لمن', 'من أين', 'كم مرة'], 'Sarana', ''],
  ['____ ولدا في الفصل؟', 'Berapa anak laki-laki di kelas?', 'كم', ['بكم', 'لمن', 'منذ متى'], 'Jumlah', ''],
  ['____ تتكلم عن العمل؟', 'Dengan siapa kamu berbicara tentang pekerjaan?', 'مع من', ['لمن', 'بكم', 'منذ متى'], 'Pendamping', ''],
  ['____ موضوع الدرس اليوم؟', 'Apa topik pelajaran hari ini?', 'ما', ['من أين', 'لمن', 'كم مرة'], 'Benda', ''],
  ['____ مدينة زرت؟', 'Kota mana yang kamu kunjungi?', 'أيّ', ['لمن', 'كيف', 'كم مرة'], 'Pilihan', ''],
  ['____ ستعود من السفر؟', 'Kapan kamu akan kembali dari perjalanan?', 'متى', ['لمن', 'من أين', 'بكم'], 'Waktu', ''],
  ['____ اشتريت هذا الهاتف؟', 'Berapa harga ponsel yang kamu beli ini?', 'بكم', ['لمن', 'منذ متى', 'إلى أين'], 'Harga', ''],
  ['____ هو المسؤول عن هذا المشروع؟', 'Siapa yang bertanggung jawab atas proyek ini?', 'من', ['لمن', 'ماذا', 'منذ متى'], 'Orang', ''],
];

export const hardQuestions: ChoiceTuple[] = [
  ['____ تتحدثون؟', 'Tentang apa kalian berbicara?', 'عمّ', ['ممّ', 'لمن', 'أنّى'], 'Tentang apa', ''],
  ['____ يتكون الماء؟', 'Air terdiri dari apa?', 'ممّ', ['عمّ', 'فيمَ', 'بمَ'], 'Dari apa', ''],
  ['____ تفكر؟', 'Apa yang sedang kamu pikirkan?', 'فيمَ', ['ممّ', 'لمن', 'أيّان'], 'Dalam hal apa', ''],
  ['____ تكتب؟ بالقلم أم بالحاسوب؟', 'Dengan apa kamu menulis? Dengan pena atau komputer?', 'بمَ', ['ممّ', 'إلامَ', 'أيّان'], 'Dengan apa', ''],
  ['____ تأخرت؟', 'Mengapa kamu terlambat?', 'لِمَ', ['بمَ', 'عمّ', 'فيمَ'], 'Alasan', ''],
  ['____ الجو جميلا اليوم؟', 'Bukankah cuaca hari ini indah?', 'أليس', ['هلّا', 'أنّى', 'أيّان'], 'Penegasan', ''],
  ['____ لك هذا؟', 'Dari mana kamu mendapatkan ini?', 'أنّى', ['عمّ', 'بمَ', 'إلامَ'], 'Asal', ''],
  ['____ تنظر؟', 'Ke arah apa kamu memandang?', 'إلامَ', ['عمّ', 'ممّ', 'فيمَ'], 'Ke arah apa', ''],
  ['____ تزورني في بيتي؟', 'Maukah kamu mengunjungiku di rumah?', 'هلّا', ['أليس', 'أنّى', 'ممّ'], 'Ajakan', ''],
  ['____ أخبرك بالحقيقة؟', 'Bukankah aku sudah memberitahumu kebenarannya?', 'ألم', ['أليس', 'هلّا', 'أنّى'], 'Penegasan', ''],
  ['____ يوم الحساب؟', 'Kapan hari perhitungan itu?', 'أيّان', ['عمّ', 'ممّ', 'إلامَ'], 'Waktu', ''],
  ['____ صُنعت هذه الطاولة؟', 'Dari apa meja ini dibuat?', 'ممّ', ['عمّ', 'فيمَ', 'إلامَ'], 'Dari apa', ''],
  ['____ تبحث؟', 'Apa yang kamu cari?', 'عمّ', ['ممّ', 'بمَ', 'أيّان'], 'Tentang apa', ''],
  ['____ نذهب إلى الحديقة؟', 'Bagaimana kalau kita pergi ke taman?', 'ألا', ['أليس', 'أيّان', 'ممّ'], 'Ajakan', ''],
  ['____ قضيت العطلة؟', 'Bagaimana kamu menghabiskan liburan?', 'كيف', ['ممّ', 'أيّان', 'عمّ'], 'Cara', ''],
  ['____ تنتهي هذه الأزمة؟', 'Kapan krisis ini akan berakhir?', 'متى', ['ممّ', 'عمّ', 'فيمَ'], 'Waktu', ''],
  ['____ طالبا حضر اليوم؟', 'Berapa siswa yang hadir hari ini?', 'كم', ['أيّ', 'ممّ', 'عمّ'], 'Jumlah', ''],
  ['____ رجل هذا؟', 'Lelaki macam apa ini?', 'أيّ', ['كم', 'ممّ', 'عمّ'], 'Pilihan', ''],
  ['____ لا تصدقني؟', 'Mengapa kamu tidak memercayaiku?', 'لماذا', ['ممّ', 'أيّان', 'أنّى'], 'Alasan', ''],
  ['____ الشخص الذي اتصل بك؟', 'Siapa orang yang meneleponmu?', 'من', ['لمن', 'ممّ', 'أيّان'], 'Orang', ''],
  ['____ كتبت هذه الرسالة؟', 'Untuk siapa kamu menulis surat ini?', 'لمن', ['ممّ', 'أيّان', 'إلامَ'], 'Penerima', ''],
  ['____ يدلّ هذا الرمز؟', 'Apa yang ditunjukkan oleh simbol ini?', 'علامَ', ['ممّ', 'لمن', 'أيّان'], 'Atas apa', ''],
  ['____ كان أداء الطلاب في الامتحان؟', 'Bagaimana kinerja para siswa dalam ujian?', 'كيف', ['ممّ', 'عمّ', 'أيّان'], 'Keadaan', ''],
  ['____ يسافر الوفد؟', 'Kapan delegasi itu berangkat?', 'متى', ['ممّ', 'عمّ', 'لمن'], 'Waktu', ''],
  ['____ تريد أن تصبح في المستقبل؟', 'Kamu ingin menjadi apa di masa depan?', 'ماذا', ['ممّ', 'لمن', 'أيّان'], 'Benda', ''],
  ['____ أعطيت الكتاب؟', 'Kepada siapa kamu memberikan buku itu?', 'لمن', ['ممّ', 'عمّ', 'أيّان'], 'Penerima', ''],
  ['____ اعتمدت في بحثك؟', 'Pada apa kamu bersandar dalam penelitianmu?', 'علامَ', ['ممّ', 'لمن', 'أيّان'], 'Atas apa', ''],
  ['____ تشكو؟', 'Apa yang kamu keluhkan?', 'ممّ', ['عمّ', 'أيّان', 'علامَ'], 'Dari apa', ''],
  ['____هذا البيت أكبر أم ذاك؟', 'Rumah ini yang lebih besar atau rumah itu?', 'أ', ['هل', 'أيّان', 'ممّ'], 'Memilih', ''],
  ['____ ستنتظر؟', 'Sampai kapan kamu akan menunggu?', 'إلى متى', ['ممّ', 'عمّ', 'لمن'], 'Sampai kapan', ''],
];
