// Arabic Harfu Jar Path (preposition-path mode): huruf jar, zharf tempat/waktu and verb + preposition pairs, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule]
import type { ChoiceTuple } from './particles';

export const easyPrepositions: ChoiceTuple[] = [
  ['الكتاب ____ الحقيبة.', 'Buku ada di dalam tas.', 'في', ['على', 'إلى', 'من'], 'Tempat', 'في = di dalam.'],
  ['القلم ____ الطاولة.', 'Pulpen ada di atas meja.', 'على', ['في', 'إلى', 'من'], 'Tempat', 'على = di atas.'],
  ['ذهبت ____ المدرسة.', 'Saya pergi ke sekolah.', 'إلى', ['في', 'على', 'عن'], 'Arah', 'إلى = ke (tujuan).'],
  ['جئت ____ البيت.', 'Saya datang dari rumah.', 'من', ['إلى', 'في', 'على'], 'Asal', 'من = dari.'],
  ['أنا ____ إندونيسيا.', 'Saya dari Indonesia.', 'من', ['إلى', 'على', 'عن'], 'Asal', 'من = dari (asal).'],
  ['ذهبت إلى السوق ____ أبي.', 'Saya pergi ke pasar bersama ayah.', 'مع', ['عن', 'على', 'إلى'], 'Bersama', 'مع = bersama.'],
  ['كتبت الدرس ____ القلم.', 'Saya menulis pelajaran dengan pulpen.', 'بـ', ['في', 'عن', 'إلى'], 'Alat', 'بـ = dengan (alat).'],
  ['هذا الكتاب ____ أخي.', 'Buku ini milik saudaraku.', 'لـ', ['في', 'على', 'عن'], 'Kepemilikan', 'لـ = milik/untuk.'],
  ['القطة ____ السرير.', 'Kucing ada di bawah tempat tidur.', 'تحت', ['فوق', 'في', 'إلى'], 'Posisi', 'تحت = di bawah.'],
  ['الطائرة ____ السحاب.', 'Pesawat ada di atas awan.', 'فوق', ['تحت', 'إلى', 'من'], 'Posisi', 'فوق = di atas (tidak menempel).'],
  ['السيارة ____ البيت.', 'Mobil ada di depan rumah.', 'أمام', ['خلف', 'تحت', 'في'], 'Posisi', 'أمام = di depan.'],
  ['الحديقة ____ المدرسة.', 'Taman ada di belakang sekolah.', 'خلف', ['أمام', 'فوق', 'على'], 'Posisi', 'خلف = di belakang.'],
  ['جلست ____ أحمد وعلي.', 'Saya duduk di antara Ahmad dan Ali.', 'بين', ['فوق', 'تحت', 'إلى'], 'Posisi', 'بين = di antara.'],
  ['الماء ____ الكأس.', 'Air ada di dalam gelas.', 'في', ['على', 'إلى', 'عن'], 'Tempat', 'في = di dalam.'],
  ['رجعت ____ المدرسة ظهرا.', 'Saya pulang dari sekolah siang hari.', 'من', ['إلى', 'في', 'على'], 'Asal', 'من = dari.'],
  ['سافرنا ____ مكة.', 'Kami bepergian ke Makkah.', 'إلى', ['في', 'على', 'عن'], 'Arah', 'إلى = ke.'],
  ['الصورة ____ الجدار.', 'Gambar itu ada di dinding.', 'على', ['في', 'إلى', 'من'], 'Tempat', 'على = menempel di permukaan.'],
  ['أسكن ____ جاكرتا.', 'Saya tinggal di Jakarta.', 'في', ['على', 'إلى', 'من'], 'Tempat', 'في + kota.'],
  ['أذهب إلى المدرسة ____ الحافلة.', 'Saya ke sekolah naik bus.', 'بـ', ['في', 'على', 'عن'], 'Alat transportasi', 'بـ + kendaraan.'],
  ['الهدية ____ أمي.', 'Hadiah ini untuk ibuku.', 'لـ', ['في', 'على', 'عن'], 'Untuk', 'لـ = untuk.'],
  ['المعلم ____ الفصل.', 'Guru ada di kelas.', 'في', ['على', 'إلى', 'من'], 'Tempat', 'في = di.'],
  ['خرجت ____ الغرفة.', 'Saya keluar dari kamar.', 'من', ['إلى', 'على', 'في'], 'Asal', 'خرج من = keluar dari.'],
  ['دخلت ____ المسجد.', 'Saya masuk ke masjid.', 'إلى', ['من', 'على', 'عن'], 'Arah', 'دخل إلى = masuk ke.'],
  ['النافذة ____ الباب.', 'Jendela ada di samping pintu.', 'بجانب', ['تحت', 'فوق', 'بين'], 'Posisi', 'بجانب = di samping.'],
  ['البيت ____ المسجد.', 'Rumah itu dekat dari masjid.', 'قريب من', ['بعيد إلى', 'فوق', 'تحت'], 'Jarak', 'قريب من = dekat dari.'],
  ['أصلي ____ المسجد.', 'Saya salat di masjid.', 'في', ['على', 'إلى', 'عن'], 'Tempat', 'في = di.'],
  ['سلمت ____ المعلم.', 'Saya memberi salam kepada guru.', 'على', ['في', 'من', 'عن'], 'Kata kerja + jar', 'سلم على = memberi salam kepada.'],
  ['هذا الطعام ____ الضيوف.', 'Makanan ini untuk para tamu.', 'لـ', ['في', 'على', 'عن'], 'Untuk', 'لـ = untuk.'],
  ['الولد ____ الشجرة.', 'Anak itu ada di bawah pohon.', 'تحت', ['فوق', 'إلى', 'من'], 'Posisi', 'تحت = di bawah.'],
  ['أشرب الشاي ____ السكر.', 'Saya minum teh dengan gula.', 'مع', ['عن', 'على', 'إلى'], 'Bersama', 'مع = dengan/bersama.'],
];

export const mediumPrepositions: ChoiceTuple[] = [
  ['أدرس العربية ____ سنتين.', 'Saya belajar bahasa Arab sejak dua tahun.', 'منذ', ['حتى', 'بعد', 'قبل'], 'Waktu', 'منذ = sejak.'],
  ['انتظرتك ____ المساء.', 'Saya menunggumu sampai sore.', 'حتى', ['منذ', 'قبل', 'عن'], 'Batas waktu', 'حتى = sampai.'],
  ['أغسل يدي ____ الأكل.', 'Saya mencuci tangan sebelum makan.', 'قبل', ['بعد', 'منذ', 'حتى'], 'Waktu', 'قبل = sebelum.'],
  ['أنام ____ صلاة العشاء.', 'Saya tidur setelah salat Isya.', 'بعد', ['قبل', 'منذ', 'حتى'], 'Waktu', 'بعد = setelah.'],
  ['تكلمنا ____ الامتحان.', 'Kami berbicara tentang ujian.', 'عن', ['على', 'إلى', 'في'], 'Topik', 'تكلم عن = berbicara tentang.'],
  ['بحثت ____ المفتاح.', 'Saya mencari kunci.', 'عن', ['على', 'في', 'إلى'], 'Kata kerja + jar', 'بحث عن = mencari.'],
  ['استمعت ____ المحاضرة.', 'Saya mendengarkan ceramah.', 'إلى', ['على', 'عن', 'من'], 'Kata kerja + jar', 'استمع إلى = mendengarkan.'],
  ['حصلت ____ جائزة.', 'Saya mendapatkan hadiah.', 'على', ['في', 'إلى', 'عن'], 'Kata kerja + jar', 'حصل على = mendapatkan.'],
  ['اشتركت ____ المسابقة.', 'Saya ikut serta dalam lomba.', 'في', ['على', 'إلى', 'عن'], 'Kata kerja + jar', 'اشترك في = ikut serta dalam.'],
  ['يعتمد الأمر ____ الوقت.', 'Masalah itu tergantung waktu.', 'على', ['في', 'إلى', 'من'], 'Kata kerja + jar', 'اعتمد على = bergantung pada.'],
  ['خاف الطفل ____ الكلب.', 'Anak itu takut pada anjing.', 'من', ['على', 'إلى', 'عن'], 'Kata kerja + jar', 'خاف من = takut pada.'],
  ['انتهيت ____ الواجب.', 'Saya selesai mengerjakan PR.', 'من', ['على', 'إلى', 'في'], 'Kata kerja + jar', 'انتهى من = selesai dari.'],
  ['شكرته ____ مساعدته.', 'Saya berterima kasih kepadanya atas bantuannya.', 'على', ['في', 'إلى', 'من'], 'Kata kerja + jar', 'شكر على = berterima kasih atas.'],
  ['سألت المعلم ____ الدرس.', 'Saya bertanya kepada guru tentang pelajaran.', 'عن', ['على', 'إلى', 'في'], 'Kata kerja + jar', 'سأل عن = bertanya tentang.'],
  ['ساعدني ____ الواجب.', 'Dia membantuku dalam mengerjakan PR.', 'في', ['على', 'إلى', 'عن'], 'Kata kerja + jar', 'ساعد في = membantu dalam.'],
  ['وصلنا ____ المطار متأخرين.', 'Kami tiba di bandara terlambat.', 'إلى', ['في', 'على', 'عن'], 'Kata kerja + jar', 'وصل إلى = tiba di.'],
  ['نظرت ____ السماء.', 'Saya memandang ke langit.', 'إلى', ['على', 'عن', 'من'], 'Kata kerja + jar', 'نظر إلى = memandang ke.'],
  ['ابتعد ____ النار.', 'Menjauhlah dari api.', 'عن', ['إلى', 'على', 'في'], 'Kata kerja + jar', 'ابتعد عن = menjauh dari.'],
  ['يقع الفندق ____ المحطة والسوق.', 'Hotel terletak di antara stasiun dan pasar.', 'بين', ['حول', 'عند', 'منذ'], 'Posisi', 'بين = di antara.'],
  ['جلسنا ____ الطاولة.', 'Kami duduk mengelilingi meja.', 'حول', ['بين', 'منذ', 'حتى'], 'Posisi', 'حول = di sekeliling.'],
  ['كنت ____ صديقي أمس.', 'Kemarin saya berada di tempat temanku.', 'عند', ['حول', 'منذ', 'حتى'], 'Tempat', 'عند = di (tempat seseorang).'],
  ['أعطيت الكتاب ____ أخي.', 'Saya memberikan buku kepada saudaraku.', 'لـ', ['عن', 'في', 'من'], 'Penerima', 'أعطى لـ = memberi kepada.'],
  ['هذا الباب مصنوع ____ الخشب.', 'Pintu ini terbuat dari kayu.', 'من', ['على', 'في', 'إلى'], 'Bahan', 'مصنوع من = terbuat dari.'],
  ['رغب أخي ____ السفر.', 'Kakakku ingin bepergian.', 'في', ['عن', 'على', 'إلى'], 'Kata kerja + jar', 'رغب في = ingin/berminat.'],
  ['رغب الطالب ____ الكسل.', 'Siswa itu menjauhi kemalasan.', 'عن', ['في', 'على', 'إلى'], 'Kata kerja + jar', 'رغب عن = tidak menyukai/menjauhi.'],
  ['اتصلت ____ أمي.', 'Saya menelepon ibu.', 'بـ', ['عن', 'في', 'من'], 'Kata kerja + jar', 'اتصل بـ = menghubungi.'],
  ['آمنت ____ الله.', 'Saya beriman kepada Allah.', 'بـ', ['عن', 'على', 'إلى'], 'Kata kerja + jar', 'آمن بـ = beriman kepada.'],
  ['أنا مشتاق ____ أهلي.', 'Saya rindu kepada keluargaku.', 'إلى', ['على', 'عن', 'في'], 'Adjektiva + jar', 'مشتاق إلى = rindu kepada.'],
  ['هو مسؤول ____ المشروع.', 'Dia bertanggung jawab atas proyek itu.', 'عن', ['على', 'إلى', 'في'], 'Adjektiva + jar', 'مسؤول عن = bertanggung jawab atas.'],
  ['هي مشغولة ____ عملها.', 'Dia sibuk dengan pekerjaannya.', 'بـ', ['عن', 'إلى', 'من'], 'Adjektiva + jar', 'مشغول بـ = sibuk dengan.'],
];

export const hardPrepositions: ChoiceTuple[] = [
  ['قضى عمره ____ خدمة الناس.', 'Dia menghabiskan umurnya dalam melayani orang.', 'في', ['على', 'عن', 'إلى'], 'Kata kerja + jar', 'قضى … في = menghabiskan … dalam.'],
  ['قضى القاضي ____ المتهم بالسجن.', 'Hakim memutuskan hukuman penjara atas terdakwa.', 'على', ['في', 'عن', 'إلى'], 'Makna berubah', 'قضى على = memutuskan atas/membinasakan.'],
  ['يدل هذا ____ ذكائه.', 'Ini menunjukkan kecerdasannya.', 'على', ['في', 'عن', 'إلى'], 'Kata kerja + jar', 'دل على = menunjukkan.'],
  ['عبر الكاتب ____ رأيه بوضوح.', 'Penulis mengungkapkan pendapatnya dengan jelas.', 'عن', ['على', 'في', 'إلى'], 'Kata kerja + jar', 'عبر عن = mengungkapkan.'],
  ['انضم ____ الفريق الجديد.', 'Dia bergabung dengan tim baru.', 'إلى', ['على', 'عن', 'في'], 'Kata kerja + jar', 'انضم إلى = bergabung dengan.'],
  ['تخلص ____ عاداته السيئة.', 'Dia terbebas dari kebiasaan buruknya.', 'من', ['على', 'إلى', 'في'], 'Kata kerja + jar', 'تخلص من = terbebas dari.'],
  ['حافظ ____ صحتك.', 'Jagalah kesehatanmu.', 'على', ['في', 'عن', 'من'], 'Kata kerja + jar', 'حافظ على = menjaga.'],
  ['اعتذر ____ تأخره.', 'Dia minta maaf atas keterlambatannya.', 'عن', ['على', 'في', 'إلى'], 'Kata kerja + jar', 'اعتذر عن = minta maaf atas.'],
  ['استفدت كثيرا ____ هذا الكتاب.', 'Saya banyak mengambil manfaat dari buku ini.', 'من', ['على', 'إلى', 'عن'], 'Kata kerja + jar', 'استفاد من = mengambil manfaat dari.'],
  ['أصر ____ رأيه.', 'Dia bersikeras pada pendapatnya.', 'على', ['في', 'عن', 'إلى'], 'Kata kerja + jar', 'أصر على = bersikeras.'],
  ['يتكون البيت ____ ثلاث غرف.', 'Rumah itu terdiri dari tiga kamar.', 'من', ['على', 'في', 'إلى'], 'Kata kerja + jar', 'تكون من = terdiri dari.'],
  ['اتفقنا ____ موعد الاجتماع.', 'Kami sepakat tentang jadwal rapat.', 'على', ['في', 'عن', 'إلى'], 'Kata kerja + jar', 'اتفق على = sepakat atas.'],
  ['يختلف هذا ____ ذاك.', 'Ini berbeda dari itu.', 'عن', ['على', 'إلى', 'في'], 'Kata kerja + jar', 'اختلف عن = berbeda dari.'],
  ['ركز ____ دراستك.', 'Fokuslah pada pelajaranmu.', 'على', ['في', 'عن', 'من'], 'Kata kerja + jar', 'ركز على = fokus pada.'],
  ['شارك ____ النقاش.', 'Dia ikut serta dalam diskusi.', 'في', ['على', 'عن', 'إلى'], 'Kata kerja + jar', 'شارك في = berpartisipasi dalam.'],
  ['تعرفت ____ أصدقاء جدد.', 'Saya berkenalan dengan teman-teman baru.', 'على', ['في', 'عن', 'من'], 'Kata kerja + jar', 'تعرف على = berkenalan dengan.'],
  ['استغنى ____ مساعدة الآخرين.', 'Dia tidak lagi membutuhkan bantuan orang lain.', 'عن', ['على', 'في', 'إلى'], 'Kata kerja + jar', 'استغنى عن = tidak membutuhkan.'],
  ['يحتاج المشروع ____ وقت أطول.', 'Proyek ini membutuhkan waktu lebih lama.', 'إلى', ['على', 'عن', 'في'], 'Kata kerja + jar', 'احتاج إلى = membutuhkan.'],
  ['نجح ____ الامتحان بتفوق.', 'Dia lulus ujian dengan predikat istimewa.', 'في', ['على', 'عن', 'إلى'], 'Kata kerja + jar', 'نجح في = berhasil dalam.'],
  ['حرص ____ الحضور مبكرا.', 'Dia bersungguh-sungguh untuk hadir lebih awal.', 'على', ['في', 'عن', 'إلى'], 'Kata kerja + jar', 'حرص على = bersungguh-sungguh.'],
  ['____ الرغم من التعب، واصل العمل.', 'Meskipun lelah, dia melanjutkan pekerjaan.', 'على', ['في', 'من', 'إلى'], 'Ungkapan', 'على الرغم من = meskipun.'],
  ['قرأت الكتاب ____ البداية إلى النهاية.', 'Saya membaca buku dari awal sampai akhir.', 'من', ['على', 'عن', 'في'], 'Rentang', 'من … إلى = dari … sampai.'],
  ['تأثر الطلاب ____ كلام المعلم.', 'Para siswa terpengaruh oleh ucapan guru.', 'بـ', ['على', 'عن', 'إلى'], 'Kata kerja + jar', 'تأثر بـ = terpengaruh oleh.'],
  ['يهتم ____ تعليم أولاده.', 'Dia memperhatikan pendidikan anak-anaknya.', 'بـ', ['على', 'عن', 'إلى'], 'Kata kerja + jar', 'اهتم بـ = memperhatikan.'],
  ['انتقل ____ مدينة أخرى.', 'Dia pindah ke kota lain.', 'إلى', ['على', 'عن', 'في'], 'Kata kerja + jar', 'انتقل إلى = pindah ke.'],
  ['دافع ____ حقوق العمال.', 'Dia membela hak-hak buruh.', 'عن', ['على', 'إلى', 'في'], 'Kata kerja + jar', 'دافع عن = membela.'],
  ['أشرف ____ تنظيم الحفل.', 'Dia mengawasi penyelenggaraan acara.', 'على', ['في', 'عن', 'إلى'], 'Kata kerja + jar', 'أشرف على = mengawasi.'],
  ['سمح لي ____ الدخول.', 'Dia mengizinkan saya masuk.', 'بـ', ['على', 'عن', 'إلى'], 'Kata kerja + jar', 'سمح لـ … بـ = mengizinkan … untuk.'],
  ['هذا القرار ____ مصلحة الجميع.', 'Keputusan ini demi kepentingan semua.', 'في', ['على', 'عن', 'إلى'], 'Ungkapan', 'في مصلحة = demi kepentingan.'],
  ['يعاني المريض ____ ألم شديد.', 'Pasien menderita sakit yang parah.', 'من', ['على', 'إلى', 'في'], 'Kata kerja + jar', 'عانى من = menderita.'],
];
