// Arabic Sentence Builder: [Indonesian prompt, Arabic answer tokens], 30 per level.
export type SentenceTuple = [prompt: string, tokens: string];

export const easySentences: SentenceTuple[] = [
  ['Saya seorang siswa.', 'أنا طالب'],
  ['Ini rumah saya.', 'هذا بيتي'],
  ['Saya suka bahasa Arab.', 'أحب اللغة العربية'],
  ['Dia (lk) membaca buku.', 'هو يقرأ كتابا'],
  ['Kami pergi ke sekolah.', 'نذهب إلى المدرسة'],
  ['Air ini dingin.', 'هذا الماء بارد'],
  ['Guru ada di kelas.', 'المعلم في الفصل'],
  ['Saya punya pulpen.', 'عندي قلم'],
  ['Rumah itu dekat.', 'ذلك البيت قريب'],
  ['Temanku baik hati.', 'صديقي لطيف'],
  ['Ibuku memasak di dapur.', 'أمي تطبخ في المطبخ'],
  ['Ayahku bekerja di kantor.', 'أبي يعمل في المكتب'],
  ['Kucing (betina) itu kecil.', 'القطة صغيرة'],
  ['Saya minum susu setiap pagi.', 'أشرب الحليب كل صباح'],
  ['Buku itu ada di atas meja.', 'الكتاب على الطاولة'],
  ['Namaku Ahmad.', 'اسمي أحمد'],
  ['Saya dari Indonesia.', 'أنا من إندونيسيا'],
  ['Langit hari ini cerah.', 'السماء صافية اليوم'],
  ['Adik laki-lakiku bermain di taman.', 'أخي الصغير يلعب في الحديقة'],
  ['Fatimah menulis pelajaran.', 'فاطمة تكتب الدرس'],
  ['Pasar itu ramai.', 'السوق مزدحم'],
  ['Kami makan nasi.', 'نأكل الأرز'],
  ['Mobil ayahku baru.', 'سيارة أبي جديدة'],
  ['Saya tidur pukul sembilan.', 'أنام في الساعة التاسعة'],
  ['Pintu itu terbuka.', 'الباب مفتوح'],
  ['Siswa itu rajin.', 'الطالب مجتهد'],
  ['Masjid itu dekat dari rumah kami.', 'المسجد قريب من بيتنا'],
  ['Saya mencintai keluargaku.', 'أحب أسرتي'],
  ['Apel ini manis.', 'هذا التفاح حلو'],
  ['Mereka ada di perpustakaan.', 'هم في المكتبة'],
];

export const mediumSentences: SentenceTuple[] = [
  ['Saya belajar bahasa Arab setiap pagi.', 'أتعلم العربية كل صباح'],
  ['Dia pergi ke kantor dengan mobil.', 'يذهب إلى المكتب بالسيارة'],
  ['Kami makan di restoran baru.', 'نأكل في مطعم جديد'],
  ['Mereka tinggal di kota besar.', 'يسكنون في مدينة كبيرة'],
  ['Saya ingin membeli tiket kereta.', 'أريد أن أشتري تذكرة القطار'],
  ['Apakah kamu berbicara bahasa Arab?', 'هل تتكلم العربية'],
  ['Saya tidak mengerti pertanyaan ini.', 'لا أفهم هذا السؤال'],
  ['Kami akan bertemu besok pagi.', 'سنلتقي غدا صباحا'],
  ['Dokter memberiku obat.', 'أعطاني الطبيب دواء'],
  ['Hotel itu dekat dari bandara.', 'الفندق قريب من المطار'],
  ['Saya bangun pagi sebelum subuh.', 'أستيقظ مبكرا قبل الفجر'],
  ['Berapa harga kemeja ini?', 'كم سعر هذا القميص'],
  ['Kakak perempuanku kuliah di universitas.', 'أختي الكبيرة تدرس في الجامعة'],
  ['Kami pergi ke pasar pada hari Jumat.', 'نذهب إلى السوق يوم الجمعة'],
  ['Pesawat lepas landas pukul sepuluh.', 'تقلع الطائرة في الساعة العاشرة'],
  ['Saya sudah menulis pesan untuk temanku.', 'كتبت رسالة إلى صديقي'],
  ['Guru menjelaskan pelajaran dengan sabar.', 'يشرح المعلم الدرس بصبر'],
  ['Saya suka berolahraga di sore hari.', 'أحب ممارسة الرياضة في المساء'],
  ['Jalan ini macet setiap pagi.', 'هذا الشارع مزدحم كل صباح'],
  ['Para siswa duduk di kelas.', 'يجلس الطلاب في الفصل'],
  ['Saya lupa kunci di rumah.', 'نسيت المفتاح في البيت'],
  ['Kami menunggu bus di halte.', 'ننتظر الحافلة في المحطة'],
  ['Ibuku membeli sayur dan buah.', 'اشترت أمي خضارا وفواكه'],
  ['Udara di musim dingin sangat dingin.', 'الجو في الشتاء بارد جدا'],
  ['Dia membaca koran setiap pagi.', 'يقرأ الجريدة كل صباح'],
  ['Saya tinggal di sini sejak dua tahun.', 'أسكن هنا منذ سنتين'],
  ['Tolong buka jendela itu.', 'افتح النافذة من فضلك'],
  ['Hari ini saya sangat sibuk.', 'أنا مشغول جدا اليوم'],
  ['Kami berbicara tentang liburan.', 'نتحدث عن العطلة'],
  ['Perpustakaan tutup pada hari Minggu.', 'المكتبة مغلقة يوم الأحد'],
];

export const hardSentences: SentenceTuple[] = [
  ['Meskipun topiknya sulit, saya akan mencoba.', 'رغم أن الموضوع صعب سأحاول'],
  ['Jika saya punya waktu, saya akan membaca teks Arab.', 'إذا كان عندي وقت سأقرأ النص العربي'],
  ['Guru menjelaskan kaidah itu dengan jelas.', 'شرح المعلم القاعدة بوضوح'],
  ['Saya ingin meningkatkan kemampuan berbicara saya.', 'أريد تحسين مهارة الكلام عندي'],
  ['Setelah latihan, saya menjadi lebih percaya diri.', 'بعد التدريب أصبحت أكثر ثقة'],
  ['Kalimat yang benar membuat makna menjadi jelas.', 'الجملة الصحيحة تجعل المعنى واضحا'],
  ['Kami perlu mengulang mufradat sebelum ujian.', 'نحتاج إلى مراجعة المفردات قبل الاختبار'],
  ['Dia bertanya kepadaku mengapa saya belajar bahasa Arab.', 'سألني لماذا أتعلم العربية'],
  ['Saya memilih jawaban yang paling sesuai.', 'اخترت الجواب الأنسب'],
  ['Kita akan melanjutkan diskusi setelah istirahat.', 'سنواصل النقاش بعد الاستراحة'],
  ['Buku yang saya baca kemarin sangat bermanfaat.', 'الكتاب الذي قرأته أمس مفيد جدا'],
  ['Saya belum pernah mengunjungi Mesir sebelumnya.', 'لم أزر مصر من قبل'],
  ['Para siswi yang rajin itu lulus ujian.', 'نجحت الطالبات المجتهدات في الامتحان'],
  ['Seandainya saya tahu, saya pasti hadir.', 'لو كنت أعرف لحضرت'],
  ['Perusahaan itu membutuhkan pegawai yang berpengalaman.', 'تحتاج الشركة إلى موظفين ذوي خبرة'],
  ['Ketika saya sampai, kereta sudah berangkat.', 'عندما وصلت كان القطار قد غادر'],
  ['Membaca setiap hari memperluas wawasan.', 'القراءة اليومية توسع المدارك'],
  ['Saya tidak akan menyerah sampai berhasil.', 'لن أستسلم حتى أنجح'],
  ['Rapat ditunda karena direktur sakit.', 'تأجل الاجتماع لأن المدير مريض'],
  ['Semakin banyak kamu berlatih, semakin baik bicaramu.', 'كلما تدربت أكثر تحسن كلامك'],
  ['Pemerintah membangun jalan baru di antara kedua kota.', 'بنت الحكومة طريقا جديدا بين المدينتين'],
  ['Sebaiknya kamu tidur lebih awal.', 'من الأفضل أن تنام مبكرا'],
  ['Dia berbicara seolah-olah dia seorang ahli.', 'يتكلم كأنه خبير'],
  ['Saya menelepon temanku untuk memberinya ucapan selamat.', 'اتصلت بصديقي لأهنئه'],
  ['Masalah ini tidak bisa diselesaikan dengan mudah.', 'لا يمكن حل هذه المشكلة بسهولة'],
  ['Kami tiba lebih awal agar mendapat tempat duduk.', 'وصلنا مبكرين لنحصل على مقاعد'],
  ['Saya sudah membaca buku itu dua kali.', 'قرأت ذلك الكتاب مرتين'],
  ['Penelitian ini membahas pengaruh teknologi terhadap pendidikan.', 'يناقش هذا البحث أثر التكنولوجيا في التعليم'],
  ['Kota yang kami kunjungi terkenal dengan pantainya.', 'المدينة التي زرناها مشهورة بشواطئها'],
  ['Meskipun hujan, para pemain melanjutkan pertandingan.', 'رغم المطر واصل اللاعبون المباراة'],
];
