import type { AuthoredQuiz } from '../../advanced/shared/authoredQuiz';

// Fifteen authored questions per lesson (key = lesson number in LessonN.tsx).
export const upperInterPronunciationQuizBank: Record<number, AuthoredQuiz[]> = {
  1: [
    ["Which version shows the correct stress in 'photography'?", "pho-TOG-ra-phy", ["PHO-tog-ra-phy", "pho-tog-RA-phy", "pho-tog-ra-PHY"], "'Photography' /fəˈtɒɡrəfi/ ditekan pada suku kedua, TOG."],
    ["Which version shows the correct stress in 'photographic'?", "pho-to-GRAPH-ic", ["PHO-to-graph-ic", "pho-TO-graph-ic", "pho-to-graph-IC"], "Akhiran -ic menarik tekanan ke suku tepat sebelumnya, jadi /ˌfəʊtəˈɡræfɪk/."],
    ["Where is the main stress in 'economy'?", "e-CON-o-my", ["E-con-o-my", "e-con-O-my", "e-con-o-MY"], "'Economy' diucapkan /ɪˈkɒnəmi/ dengan tekanan pada suku kedua, CON."],
    ["Where is the main stress in 'economically'?", "e-co-NOM-ic-al-ly", ["E-co-nom-ic-al-ly", "e-CON-om-ic-al-ly", "e-co-nom-IC-al-ly"], "'Economically' /ˌiːkəˈnɒmɪkli/ mempertahankan tekanan pada NOM seperti 'economic'."],
    ["What happens to the main stress from 'synthesis' to 'synthetic'?", "It moves from the 1st to the 2nd syllable", ["It moves from the 2nd to the 1st syllable", "It stays on the 1st syllable in both words", "It moves from the 1st to the 3rd syllable"], "SYN-the-sis /ˈsɪnθəsɪs/ berubah menjadi syn-THET-ic /sɪnˈθetɪk/ karena akhiran -ic."],
    ["How is 'record' stressed in 'They plan to record the interview tonight'?", "re-CORD, because it is a verb", ["RE-cord, because it is a verb", "RE-cord, because it is a noun", "re-CORD, because it is a noun"], "Dalam kalimat ini 'record' adalah kata kerja, sehingga ditekan pada suku kedua: /rɪˈkɔːd/."],
    ["Where is the main stress in 'communication'?", "com-mu-ni-CA-tion", ["com-MU-ni-ca-tion", "COM-mu-ni-ca-tion", "com-mu-NI-ca-tion"], "Akhiran -tion menarik tekanan ke suku tepat sebelumnya: /kəˌmjuːnɪˈkeɪʃn/."],
    ["Where is the main stress in 'nationality'?", "na-tion-AL-i-ty", ["NA-tion-al-i-ty", "na-TION-al-i-ty", "na-tion-al-I-ty"], "Akhiran -ity menempatkan tekanan tepat sebelum akhiran: /ˌnæʃəˈnæləti/."],
    ["Where is the main stress in 'biology'?", "bi-OL-o-gy", ["BI-ol-o-gy", "bi-ol-O-gy", "bi-ol-o-GY"], "Kata berakhiran -ogy ditekan pada suku sebelum -o-gy: /baɪˈɒlədʒi/."],
    ["Which word is stressed on the SECOND syllable?", "technology", ["photograph", "synthesis", "family"], "'Technology' diucapkan /tekˈnɒlədʒi/, sedangkan tiga kata lain ditekan pada suku pertama."],
    ["Which word is stressed on the THIRD syllable?", "academic", ["majority", "photograph", "ability"], "'Academic' /ˌækəˈdemɪk/ ditekan pada suku ketiga karena akhiran -ic."],
    ["Where is the main stress in 'historical'?", "his-TOR-i-cal", ["HIS-tor-i-cal", "his-tor-I-cal", "his-tor-i-CAL"], "Akhiran -ical menarik tekanan ke suku sebelumnya: /hɪˈstɒrɪkl/."],
    ["In which pair does the main stress move to a different syllable?", "politics – political", ["employ – employment", "govern – government", "comfort – comfortable"], "POL-i-tics berubah menjadi po-LIT-i-cal, sedangkan pasangan lain mempertahankan posisi tekanan."],
    ["Where is the main stress in 'democracy'?", "de-MOC-ra-cy", ["DEM-oc-ra-cy", "de-moc-RA-cy", "de-moc-ra-CY"], "'Democracy' diucapkan /dɪˈmɒkrəsi/ dengan tekanan pada suku kedua."],
    ["Where is the main stress in 'originality'?", "o-rig-i-NAL-i-ty", ["o-RIG-i-nal-i-ty", "O-rig-i-nal-i-ty", "o-rig-I-nal-i-ty"], "Akhiran -ity menggeser tekanan ke suku tepat sebelumnya: /əˌrɪdʒəˈnæləti/."],
  ],
  2: [
    ["In 'a lot of time', how is 'of' normally pronounced?", "/əv/", ["/ɒv/", "/ɒf/", "/ʌf/"], "Sebagai kata fungsi tanpa tekanan, 'of' memakai weak form /əv/."],
    ["In 'Wait for me', how is 'for' normally pronounced?", "/fə/", ["/fɔː/", "/fɜː/", "/fəʊ/"], "'For' tanpa tekanan sebelum konsonan diucapkan dengan weak form /fə/."],
    ["In 'fish and chips', which is the natural weak form of 'and'?", "/ən/", ["/ænd/", "/end/", "/ɑːnd/"], "Dalam ucapan alami 'and' melemah menjadi /ən/, sedangkan /ænd/ adalah strong form."],
    ["In which sentence is 'for' pronounced in its STRONG form /fɔː/?", "What's this tool for?", ["This present is for you.", "I waited for an hour.", "Thanks for coming tonight."], "Preposisi di akhir kalimat tidak dilemahkan, jadi 'for' memakai strong form /fɔː/."],
    ["In which sentence is 'can' pronounced as /kæn/?", "Yes, I can.", ["I can swim quite well.", "You can sit here.", "We can try again."], "Di akhir kalimat (jawaban singkat) 'can' memakai strong form /kæn/."],
    ["In 'You can do it', how is 'can' normally pronounced?", "/kən/", ["/kæn/", "/kɑːn/", "/kɒn/"], "'Can' sebelum kata kerja utama tidak ditekan sehingga menjadi /kən/."],
    ["In relaxed speech, how does 'should have' in 'You should have told me' usually sound?", "/ˈʃʊdəv/", ["/ˈʃuːdəv/", "/ˈʃʊdæv/", "/ˈʃʊdəf/"], "'Should have' tereduksi menjadi /ˈʃʊdəv/ (should've) dalam percakapan santai."],
    ["Which word in 'He was at the station' carries a stressed syllable?", "station", ["was", "at", "the"], "'Station' adalah kata konten, sedangkan 'was', 'at' dan 'the' adalah kata fungsi yang dilemahkan."],
    ["In 'She was late again', how is 'was' normally pronounced?", "/wəz/", ["/wɒz/", "/wɑːz/", "/wʌz/"], "'Was' tanpa tekanan di tengah kalimat memakai weak form /wəz/."],
    ["In which sentence is 'at' pronounced in its strong form /æt/?", "Who are you looking at?", ["Meet me at noon.", "She's at work today.", "Look at this photo."], "'At' di akhir kalimat tidak dilemahkan, sehingga diucapkan /æt/."],
    ["In 'Tell them to wait', how is 'them' normally pronounced?", "/ðəm/", ["/ðem/", "/ðiːm/", "/dem/"], "'Them' tanpa tekanan memakai weak form /ðəm/."],
    ["In which sentence can 'going to' NOT be reduced to 'gonna'?", "I'm going to London tomorrow.", ["I'm going to call her later.", "It's going to rain soon.", "We're going to win this match."], "'Gonna' hanya untuk 'going to' + kata kerja; di sini 'going' berarti pergi ke suatu tempat."],
    ["Which statement about 'wanna' is accurate?", "It belongs to informal speech, not formal writing", ["It is acceptable in formal academic essays", "It is a reduction used only in British English", "It is the strong form used for emphasis"], "Reduksi seperti 'wanna' hanya untuk percakapan santai dan tidak dipakai dalam tulisan resmi."],
    ["In 'a letter from Tom', how is 'from' normally pronounced?", "/frəm/", ["/frɒm/", "/frʌm/", "/fruːm/"], "'From' tanpa tekanan memakai weak form /frəm/."],
    ["In which sentence is 'some' pronounced as weak /səm/?", "Would you like some tea?", ["Some people disagree with this.", "Some of them left early.", "I'll take some, not all."], "Sebagai determiner tak tentu sebelum kata benda, 'some' melemah menjadi /səm/; dalam makna 'sebagian' ia tetap /sʌm/."],
  ],
  3: [
    ["A friend says 'I'm moving to Iceland.' You reply 'Iceland?' with a rise. What does the rise show?", "Surprise or a request to confirm", ["Certainty about the information", "That you are closing the topic", "A polite command to continue"], "Echo question dengan nada naik menunjukkan keterkejutan atau permintaan konfirmasi."],
    ["What is the usual neutral tone at the end of 'Where are you going?'", "Falling", ["Rising", "Level", "Fall-rise"], "Wh-question netral biasanya diucapkan dengan nada turun."],
    ["'It's hot today, isn't it?' The speaker is sure and just wants agreement. Which tone is used on 'isn't it'?", "A fall", ["A rise", "A level tone", "A high rise"], "Tag dengan nada turun meminta persetujuan atas hal yang sudah diyakini pembicara."],
    ["'You're coming tomorrow, aren't you?' The speaker really doesn't know. Which tone is used on 'aren't you'?", "A rise", ["A fall", "A level tone", "A low fall"], "Tag dengan nada naik menandakan pertanyaan sungguhan karena pembicara tidak yakin."],
    ["How is 'Tea, coffee or water?' said when offering a choice of exactly these three drinks?", "Rise on tea and coffee, fall on water", ["Fall on all three of the items", "Rise on all three of the items", "Fall on tea, rise on coffee and water"], "Pada daftar pilihan tertutup, tiap item naik dan item terakhir turun."],
    ["'Would you like tea or coffee?' said with a rise at the end and no fall suggests what?", "A general offer of a drink", ["A choice between exactly two drinks", "Impatience with the listener", "That the speaker has no drinks"], "Nada naik di akhir menjadikannya pertanyaan ya/tidak tentang minuman secara umum, bukan pilihan antara dua."],
    ["'That's interesting...' said with a fall-rise usually implies what?", "Polite reservation, with an unspoken 'but'", ["Complete and enthusiastic agreement", "Genuine excitement about the idea", "A request for the speaker to repeat"], "Fall-rise menandakan sikap sopan namun ragu, seolah ada 'tetapi' yang tidak diucapkan."],
    ["Which tone typically ends the opening phrase in 'From my perspective, the plan needs work'?", "A rise, showing more is coming", ["A low fall, closing the topic", "A high fall, showing surprise", "No pitch movement at all"], "Frasa pembuka biasanya naik untuk memberi sinyal bahwa kalimat belum selesai."],
    ["'I've finished the report.' is said as plain news. Which tone is expected at the end?", "Falling", ["Rising", "Fall-rise", "Rise-fall"], "Pernyataan netral yang memberi informasi baru diakhiri dengan nada turun."],
    ["Someone says 'I sold my car' but you miss the last word. You ask 'You sold what?' Which tone fits?", "A rise on 'what'", ["A fall on 'what'", "A fall on 'sold'", "A level tone throughout"], "Echo question untuk meminta pengulangan diucapkan dengan nada naik pada kata tanya."],
    ["How does 'What's your name?' usually sound if said with a rise instead of a fall?", "Warmer and more encouraging", ["Colder and more businesslike", "Like a statement of fact", "Like the end of a list"], "Wh-question dengan nada naik terdengar lebih ramah dan lembut, misalnya kepada anak kecil."],
    ["What is the most typical tone for a neutral yes/no question like 'Are you coming?'", "Rising", ["Falling", "Level", "Rise-fall"], "Yes/no question netral umumnya diucapkan dengan nada naik di akhir."],
    ["Which utterance is a question ONLY because of its intonation?", "You've already eaten? ↗", ["Have you already eaten? ↗", "What have you eaten? ↘", "You've already eaten. ↘"], "Kalimat ini berstruktur pernyataan, dan hanya nada naik yang menjadikannya pertanyaan."],
    ["Which syllable of the discourse marker 'however' carries the stress?", "how-EV-er", ["HOW-ev-er", "how-ev-ER", "HOW-EV-er"], "'However' diucapkan /haʊˈevə/ dengan tekanan pada suku kedua."],
    ["'Did you enjoy the film?' — a low, flat 'Yes.' in reply most likely signals what?", "A lack of enthusiasm", ["Great excitement", "Surprise at the question", "A wish to hear more"], "Nada rendah dan datar terdengar tidak antusias atau bosan."],
  ],
  4: [
    ["Which words are normally stressed in 'She is the best candidate'?", "best, candidate", ["she, is", "the, best", "is, candidate"], "'Best' dan 'candidate' adalah kata konten, sementara 'she', 'is' dan 'the' adalah kata fungsi."],
    ["What does 'I didn't say she STOLE it' imply?", "She did something else with it", ["Someone else took it", "I never spoke about it", "I only hinted at it"], "Tekanan pada 'stole' mengontraskan tindakannya: dia melakukan hal lain, bukan mencuri."],
    ["What does 'I didn't SAY she stole it' imply?", "I suggested it without saying it", ["Someone else took it", "She did something else with it", "Someone else said it"], "Tekanan pada 'say' menyiratkan bahwa hal itu diisyaratkan, bukan diucapkan langsung."],
    ["What does 'I didn't say SHE stole it' imply?", "Someone else took it", ["She did something else with it", "I suggested it without saying it", "I deny saying anything"], "Tekanan pada 'she' mengontraskan orangnya: yang mencuri adalah orang lain."],
    ["'I DIDN'T say she stole it' is most likely a reply to which remark?", "You told everyone she stole it!", ["Who do you think stole it?", "What exactly did she take?", "Did she buy it or steal it?"], "Tekanan pada 'didn't' menyangkal tuduhan bahwa pembicara pernah mengatakannya."],
    ["'I bought a car. The car is red.' Which word gets the main stress in the second sentence?", "red", ["car", "is", "the"], "'Car' sudah disebut sehingga kehilangan tekanan (de-accenting), dan 'red' adalah informasi baru."],
    ["'So fifteen people came?' 'No, five people came.' Which word carries the main stress in the reply?", "five", ["people", "came", "five and came equally"], "Narrow focus untuk koreksi menempatkan tekanan utama hanya pada 'five'."],
    ["Which group contains only content words?", "explain, quickly, results, new", ["the, of, and, explain", "them, results, at, new", "is, quickly, a, for"], "Kata kerja, adverbia, kata benda dan adjektiva adalah kata konten yang biasanya ditekan."],
    ["Which word is normally UNSTRESSED in 'The students finished their project'?", "their", ["students", "finished", "project"], "'Their' adalah kata ganti posesif (kata fungsi) sehingga biasanya tidak ditekan."],
    ["'What did you do at the weekend?' 'I painted the kitchen.' Which word carries the main stress?", "kitchen", ["painted", "I", "the"], "Dalam wide focus, tekanan utama jatuh pada kata konten terakhir, 'kitchen'."],
    ["'Did you buy the red shirt?' 'No, I bought the BLUE shirt.' Why is 'shirt' unstressed?", "It is already given information", ["It is a function word", "Colours are always stressed", "Nouns are never stressed"], "'Shirt' sudah disebut sebelumnya, sehingga tekanan berpindah ke kata yang dikontraskan."],
    ["Which reply answers 'Who wrote the report?' most naturally?", "SARAH wrote it.", ["Sarah WROTE it.", "Sarah wrote IT.", "Sarah wrote it NOW."], "Informasi baru yang ditanyakan adalah pelakunya, jadi 'Sarah' menerima tekanan utama."],
    ["What usually happens when a speaker stresses almost every word in a sentence?", "The message becomes harder to follow", ["The speech sounds more fluent", "The tone sounds more polite", "The speech sounds more casual"], "Terlalu banyak tekanan membuat informasi penting tidak menonjol dan ucapan terdengar tidak alami."],
    ["Which words are stressed in a neutral reading of 'I'll meet you at the station'?", "meet, station", ["I'll, at", "you, the", "meet, at"], "'Meet' dan 'station' adalah kata konten, sisanya kata fungsi."],
    ["In which sentence is the pronoun stressed?", "I invited him, not her.", ["I invited him yesterday.", "She gave him a book.", "We told him the news."], "Kata ganti biasanya lemah, tetapi ditekan ketika dikontraskan seperti 'him, not her'."],
  ],
  5: [
    ["How many schwa sounds are there in 'banana' /bəˈnɑːnə/?", "Two", ["One", "Three", "None"], "Suku pertama dan terakhir 'banana' adalah schwa, sedangkan suku tengah /ɑː/."],
    ["Which syllables of 'policeman' contain a schwa?", "po- and -man", ["-lice- only", "po- and -lice-", "-lice- and -man"], "'Policeman' /pəˈliːsmən/ punya schwa pada 'po-' dan '-man' yang tidak ditekan."],
    ["Which IPA transcription of 'about' is correct?", "/əˈbaʊt/", ["/æˈbaʊt/", "/ʌˈbaʊt/", "/əˈbəʊt/"], "Suku pertama 'about' tidak ditekan sehingga menjadi schwa /ə/."],
    ["Which vowel is in the stressed syllable of 'government'?", "/ʌ/", ["/ɒ/", "/ə/", "/əʊ/"], "'Government' dimulai dengan /ˈɡʌv/, jadi huruf 'o' di sini dibaca /ʌ/."],
    ["Which British transcription of 'consider' is correct?", "/kənˈsɪdə/", ["/kɒnˈsɪdə/", "/kənˈsaɪdə/", "/ˈkɒnsɪdə/"], "Suku 'con-' dan '-der' tidak ditekan sehingga keduanya schwa, dan tekanan ada pada /ˈsɪd/."],
    ["Which transcription of 'famous' is correct?", "/ˈfeɪməs/", ["/ˈfeɪmʌs/", "/ˈfæməs/", "/ˈfeɪmuːs/"], "Huruf 'ou' pada suku tanpa tekanan dalam 'famous' dibaca schwa /ə/."],
    ["Which word has a schwa in its FIRST syllable?", "police", ["postman", "pocket", "poster"], "'Police' /pəˈliːs/ ditekan pada suku kedua, sehingga suku pertamanya schwa."],
    ["Which statement about schwa is TRUE?", "It occurs only in unstressed syllables", ["It is always spelt with the letter e", "It is used mainly in stressed syllables", "It is a long vowel like /ɜː/"], "Schwa adalah vokal pendek netral yang hanya muncul di suku tanpa tekanan dan bisa ditulis dengan huruf apa saja."],
    ["In British English 'particular', how is the first syllable pronounced?", "/pə/", ["/pɑː/", "/pæ/", "/pɜː/"], "'Particular' /pəˈtɪkjələ/ ditekan pada suku kedua sehingga 'par-' menjadi /pə/."],
    ["Which word does NOT contain a schwa?", "teaching", ["doctor", "sofa", "lemon"], "'Teaching' /ˈtiːtʃɪŋ/ tidak punya schwa, sedangkan doctor, sofa dan lemon semuanya punya."],
    ["Why does 'photography' begin with /fə/ while 'photograph' begins with /fəʊ/?", "The first syllable loses its stress", ["The -y ending is always a schwa", "The first syllable becomes stressed", "/əʊ/ cannot come before /t/"], "Pada 'photography' tekanan pindah ke suku kedua, sehingga suku pertama melemah menjadi schwa."],
    ["Which transcription shows 'today' as it is normally said?", "/təˈdeɪ/", ["/tuːˈdeɪ/", "/ˈtəʊdeɪ/", "/tɒˈdeɪ/"], "Suku pertama 'today' tidak ditekan sehingga diucapkan /tə/."],
    ["In the verb 'contrast' (con-TRAST), how is the first vowel usually pronounced?", "/ə/", ["/ɒ/", "/ʌ/", "/ɑː/"], "Pada verba /kənˈtrɑːst/ suku pertama tidak ditekan sehingga menjadi schwa."],
    ["Which vowel begins 'Canadian' /kəˈneɪdiən/, compared with 'Canada' /ˈkænədə/?", "/ə/", ["/æ/", "/eɪ/", "/ɑː/"], "Ketika tekanan pindah ke suku kedua pada 'Canadian', vokal pertama melemah menjadi schwa."],
    ["Which is the correct British transcription of 'banana'?", "/bəˈnɑːnə/", ["/bəˈnænə/", "/bæˈnɑːnə/", "/ˈbɑːnənə/"], "Dalam British English 'banana' memiliki /ɑː/ panjang pada suku tengah yang ditekan dan schwa di kedua sisinya."],
  ],
  6: [
    ["How many consonant sounds come after the vowel in 'text' /tekst/?", "Three", ["Two", "Four", "One"], "Setelah vokal /e/ ada cluster /kst/, yaitu tiga konsonan."],
    ["Which transcription of 'twelfth' is correct?", "/twelfθ/", ["/twelvθ/", "/twelft/", "/twelfəθ/"], "'Twelfth' berakhir dengan cluster /lfθ/ tanpa vokal sisipan."],
    ["In fast speech, which sound in 'last night' is most often elided?", "/t/ at the end of 'last'", ["/s/ at the end of 'last'", "/n/ at the start of 'night'", "/t/ at the end of 'night'"], "/t/ di antara dua konsonan sering hilang, sehingga terdengar /ˈlɑːs naɪt/."],
    ["In fast speech 'ten boys' often sounds like /tem bɔɪz/. What is this process called?", "Assimilation", ["Elision", "Intrusion", "Aspiration"], "/n/ berubah menjadi /m/ karena menyesuaikan dengan /b/ bilabial berikutnya, yaitu asimilasi."],
    ["In fast speech, what does the /s/ + /j/ in 'this year' often become?", "/ʃ/", ["/z/", "/tʃ/", "/θ/"], "/s/ dan /j/ melebur menjadi /ʃ/, sehingga terdengar /ðɪʃ jɪə/."],
    ["Which word ends in the sound /z/?", "bags", ["books", "cats", "maps"], "/ɡ/ bersuara, jadi akhiran -s pada 'bags' dibaca /z/."],
    ["How is the -es ending in 'churches' pronounced?", "/ɪz/", ["/s/", "/z/", "/es/"], "Setelah /tʃ/ akhiran -es menambah suku kata /ɪz/."],
    ["In 'button' /ˈbʌtn̩/, how is the final syllable formed?", "By a syllabic /n/ with no vowel", ["By a full /ɒ/ followed by /n/", "By a long /uː/ followed by /n/", "By an extra /ə/ after the /n/"], "Setelah /t/, /n/ menjadi konsonan silabik dan membentuk suku sendiri tanpa vokal."],
    ["Some learners add a vowel to 'street'. What is the correct British pronunciation?", "/striːt/", ["/səˈtriːt/", "/ɪsˈtriːt/", "/stəˈriːt/"], "'Street' adalah satu suku kata dengan cluster /str/, tanpa vokal sisipan."],
    ["Which word ends with four consonant sounds?", "texts", ["test", "next", "desk"], "'Texts' /teksts/ berakhir dengan /ksts/, empat konsonan."],
    ["Which word begins with the voiced sound /ð/?", "these", ["think", "thank", "theme"], "'These' dimulai dengan /ð/ bersuara, sedangkan tiga kata lain dimulai dengan /θ/."],
    ["In fast speech, which consonant in 'old friend' is most often dropped?", "/d/ at the end of 'old'", ["/d/ at the end of 'friend'", "/l/ in the middle of 'old'", "/f/ at the start of 'friend'"], "/d/ di antara /l/ dan /f/ sering dihilangkan, sehingga terdengar /əʊl frend/."],
    ["In which phrase is the final /t/ normally kept and linked, not elided?", "last of all", ["last night", "next week", "must be"], "Pada 'last of all' /t/ diikuti vokal, sehingga dihubungkan dan tidak dihilangkan."],
    ["How many consonant sounds come after the vowel in 'sixths' /sɪksθs/?", "Four", ["Three", "Five", "Two"], "Setelah vokal /ɪ/ ada /k/, /s/, /θ/ dan /s/, yaitu empat konsonan."],
    ["In fast speech, what often happens to the consonants in 'good boy'?", "/d/ becomes /b/", ["/b/ becomes /d/", "/d/ becomes /t/", "/ɡ/ becomes /k/"], "/d/ berasimilasi dengan /b/ berikutnya, sehingga terdengar /ɡʊb bɔɪ/."],
  ],
  7: [
    ["In connected speech, how does 'an orange' usually sound?", "a-norange", ["an-orange with a pause", "a-rorange", "an-worange"], "/n/ di akhir 'an' bergabung dengan vokal awal 'orange' (linking konsonan ke vokal)."],
    ["How are the words in 'hold on' linked in natural speech?", "The /d/ moves to start 'on'", ["A /w/ is added before 'on'", "An /r/ is added before 'on'", "The /d/ is dropped completely"], "Konsonan akhir /d/ bergabung dengan vokal awal 'on', sehingga terdengar /həʊl dɒn/."],
    ["Which sound do many British speakers insert in 'law and order'?", "/r/", ["/w/", "/j/", "/h/"], "Setelah /ɔː/ dan sebelum vokal, penutur British sering menyisipkan intrusive /r/: /lɔːr ən ˈɔːdə/."],
    ["Where does an intrusive /r/ appear in 'the idea of it'?", "Between 'idea' and 'of'", ["Between 'the' and 'idea'", "Between 'of' and 'it'", "Before the word 'the'"], "'Idea' berakhir dengan /ə/ dan 'of' dimulai dengan vokal, sehingga /r/ disisipkan di antaranya."],
    ["Which linking sound joins 'go' and 'out' in natural speech?", "/w/", ["/j/", "/r/", "/ʔ/"], "Setelah diftong /əʊ/ yang berakhir bulat, muncul linking /w/: go_w_out."],
    ["Which phrase contains a linking /w/?", "do it", ["say it", "far away", "she asked"], "/uː/ pada 'do' diikuti vokal, sehingga muncul /w/: do_w_it."],
    ["Which phrase contains a linking /j/?", "I am", ["go away", "two eggs", "law and order"], "Setelah /aɪ/ sebelum vokal muncul linking /j/: I_y_am."],
    ["Which sound links 'my' and 'opinion' in natural speech?", "/j/", ["/w/", "/r/", "/n/"], "Diftong /aɪ/ pada 'my' diikuti vokal, sehingga muncul linking /j/."],
    ["Why is the r in 'far away' pronounced by British RP speakers?", "A vowel follows, so a linking /r/ appears", ["RP always pronounces every written r", "The second word starts with a consonant", "It is an intrusive /r/ with no spelling"], "Dalam RP, huruf r di akhir kata hanya diucapkan jika kata berikutnya dimulai dengan vokal."],
    ["In which phrase would an RP speaker NOT pronounce a linking /r/?", "far behind", ["far away", "four apples", "car alarm"], "Pada 'far behind' kata berikutnya dimulai dengan konsonan, sehingga /r/ tidak diucapkan."],
    ["Which version shows how 'take it easy' is linked in fast speech?", "tay-ki-teasy", ["take / it / easy, with pauses", "tay-kwi-teasy", "tay-ri-teasy"], "Konsonan akhir tiap kata bergabung dengan vokal kata berikutnya: /teɪ kɪ tiːzi/."],
    ["In connected speech, 'fill it in' sounds closest to which version?", "fi-li-tin", ["fill / it / in, as separate words", "fi-wi-tin", "fi-ri-tin"], "/l/ dan /t/ berpindah ke awal suku berikutnya, sehingga terdengar /fɪ lɪ tɪn/."],
    ["Why does a learner who puts a glottal stop before every vowel-initial word sound choppy?", "It blocks natural linking between words", ["It adds too many weak forms", "It uses intrusive /r/ too often", "It makes every tone rise"], "Glottal stop sebelum setiap vokal memutus linking alami sehingga ucapan terdengar terpatah-patah."],
    ["What is an intrusive /r/?", "An /r/ said where no r is spelt", ["An r that is written but silent", "A rolled r used for emphasis", "An /r/ heard only in American English"], "Intrusive /r/ disisipkan di antara dua vokal walaupun tidak ada huruf r dalam ejaan."],
    ["Which phrase contains an intrusive /r/, with no r in the spelling?", "China and Japan", ["far away", "four eggs", "car engine"], "'China' berakhir dengan /ə/ tanpa huruf r, sehingga /r/ yang muncul adalah intrusive /r/."],
  ],
  8: [
    ["How many stressed beats are there in 'Dogs eat bones'?", "Three", ["Two", "Four", "One"], "Ketiga kata adalah kata konten sehingga ada tiga ketukan bertekanan."],
    ["How many stressed beats are there in 'The dogs are eating bones'?", "Three", ["Five", "Four", "Two"], "'The' dan 'are' dilemahkan, sehingga tetap ada tiga ketukan: dogs, eat-, bones."],
    ["How is English rhythm usually described?", "Stress-timed", ["Syllable-timed", "Mora-timed", "Tone-timed"], "Bahasa Inggris disebut stress-timed karena ketukan bertekanan muncul pada interval yang kira-kira sama."],
    ["In stress-timed speech, what happens to unstressed syllables between beats?", "They are squeezed and said faster", ["They are given extra length", "They receive a stress of their own", "They are always deleted completely"], "Suku tanpa tekanan 'diperas' agar jarak antar ketukan tetap kira-kira sama."],
    ["In fast British speech, 'probably' often becomes which form?", "/ˈprɒbli/", ["/prəˈbæbli/", "/ˈprəʊbəbli/", "/ˈprɒbəbəli/"], "Dalam ucapan cepat suku tengah 'probably' hilang sehingga menjadi /ˈprɒbli/."],
    ["Which sentence has the SAME number of stressed beats as 'Cats eat mice'?", "The cats have been eating the mice.", ["Big cats eat small mice.", "Cats eat mice and rats.", "Black cats eat mice."], "Kalimat ini tetap punya tiga ketukan (cats, eat-, mice) karena kata fungsinya dilemahkan."],
    ["A learner gives every syllable equal length in 'I'd like a cup of tea'. What is the main problem?", "The rhythm sounds unnatural", ["The grammar becomes incorrect", "The vowels become too short", "The sentence becomes a question"], "Memberi panjang sama pada tiap suku mengabaikan ritme stress-timed sehingga terdengar tidak alami."],
    ["Which syllables are stressed in 'a cup of tea'?", "cup, tea", ["a, of", "cup, of", "a, tea"], "'Cup' dan 'tea' adalah kata konten, sedangkan 'a' dan 'of' dilemahkan."],
    ["Which word follows the rhythm pattern da-DUM?", "begin", ["table", "window", "garden"], "'Begin' /bɪˈɡɪn/ ditekan pada suku kedua, sedangkan tiga kata lain pada suku pertama."],
    ["Which word follows the rhythm pattern DUM-da-da?", "yesterday", ["tomorrow", "computer", "understand"], "'Yesterday' ditekan pada suku pertama diikuti dua suku lemah."],
    ["Why do speakers divide a long sentence into sense groups?", "Each group gets its own rhythm and main stress", ["So that every word can be stressed equally", "So that the sentence ends with a rising tone", "So that weak forms are no longer needed"], "Sense group membagi kalimat panjang menjadi unit makna yang masing-masing punya puncak tekanan."],
    ["What do skilled presenters usually do when they reach a key point?", "Slow down", ["Speed up", "Drop all stress", "Whisper"], "Memperlambat tempo pada poin penting membantu pendengar memperhatikannya."],
    ["Which syllables are stressed in 'It's the end of the day'?", "end, day", ["the, of", "it's, end", "end, the"], "'End' dan 'day' adalah kata konten yang menjadi ketukan bertekanan."],
    ["Which phrase has the rhythm da-DUM-da-DUM?", "a cup of tea", ["fish and chips", "bread and butter", "a glass of water"], "'A CUP of TEA' terdiri dari suku lemah-kuat-lemah-kuat."],
    ["What does 'isochrony' refer to in English rhythm?", "Stressed beats come at roughly regular intervals", ["Every syllable has exactly the same length", "Pitch always rises at the end of a phrase", "All vowels are reduced to the schwa sound"], "Isochrony adalah kecenderungan ketukan bertekanan muncul pada jarak waktu yang kira-kira sama."],
  ],
  9: [
    ["Which is the standard British (RP) pronunciation of 'bath'?", "/bɑːθ/", ["/bæθ/", "/beɪθ/", "/bɒθ/"], "RP memakai vokal panjang /ɑː/ pada 'bath', sedangkan General American memakai /æ/."],
    ["Which is the RP pronunciation of 'car' said on its own?", "/kɑː/", ["/kɑːr/", "/kær/", "/kɔː/"], "RP non-rhotic, sehingga r di akhir kata tidak diucapkan jika tidak diikuti vokal."],
    ["Which is the RP pronunciation of 'lot'?", "/lɒt/", ["/lɑːt/", "/lʌt/", "/ləʊt/"], "RP memakai vokal bulat pendek /ɒ/ pada 'lot', sedangkan GA memakai /ɑː/."],
    ["In which accent is the /t/ in 'water' typically a quick flap that sounds like /d/?", "General American", ["RP (standard British)", "Both accents equally", "Neither accent"], "T-flapping adalah ciri khas General American, bukan RP."],
    ["Which is the RP pronunciation of 'new'?", "/njuː/", ["/nuː/", "/nəʊ/", "/naʊ/"], "RP mempertahankan /j/ setelah /n/, sedangkan GA menghilangkannya (yod-dropping)."],
    ["Where is the main stress in British 'advertisement'?", "ad-VER-tise-ment", ["AD-ver-tise-ment", "ad-ver-TISE-ment", "ad-ver-tise-MENT"], "Dalam RP 'advertisement' diucapkan /ədˈvɜːtɪsmənt/ dengan tekanan pada suku kedua."],
    ["Which word has /ɑː/ in RP but /æ/ in General American?", "class", ["cat", "hand", "map"], "'Class' termasuk kelompok BATH yang memakai /ɑː/ dalam RP."],
    ["Is the r in 'park' pronounced in RP?", "No, the vowel is /ɑː/ with no /r/", ["Yes, it is always pronounced", "Only in very formal speech", "Only at the start of a sentence"], "RP tidak mengucapkan r sebelum konsonan, sehingga 'park' menjadi /pɑːk/."],
    ["Which pair of words both have the RP vowel /ɒ/?", "hot, stop", ["hurt, word", "cart, park", "boat, home"], "'Hot' dan 'stop' memakai vokal LOT /ɒ/ dalam RP."],
    ["Which feature is NOT typical of RP?", "Pronouncing r before consonants", ["Long /ɑː/ in 'path'", "Rounded /ɒ/ in 'top'", "/j/ after /n/ in 'new'"], "Mengucapkan r sebelum konsonan adalah ciri aksen rhotic seperti GA, bukan RP."],
    ["Which is the RP pronunciation of 'can't'?", "/kɑːnt/", ["/kænt/", "/keɪnt/", "/kɒnt/"], "Dalam RP 'can't' memakai /ɑː/ panjang, berbeda dari 'can' /kæn/."],
    ["Which is the RP pronunciation of 'better'?", "/ˈbetə/", ["/ˈbedər/", "/ˈbetər/", "/ˈbeɾə/"], "RP memakai /t/ jelas dan tidak mengucapkan r di akhir kata."],
    ["Which is the standard British pronunciation of 'tomato'?", "/təˈmɑːtəʊ/", ["/təˈmeɪtəʊ/", "/təˈmætəʊ/", "/ˈtɒmətəʊ/"], "British English memakai /ɑː/ pada suku kedua 'tomato', sedangkan GA memakai /eɪ/."],
    ["For international intelligibility, what matters more than copying a native accent perfectly?", "Accurate word stress", ["Using only British vocabulary", "Speaking as fast as possible", "Flapping every /t/"], "Dalam konteks internasional, tekanan kata yang tepat lebih penting untuk dipahami daripada meniru aksen."],
    ["Which word would an RP speaker pronounce WITHOUT any /r/ sound?", "card", ["red", "carry", "around"], "Dalam 'card' r diikuti konsonan sehingga tidak diucapkan; pada kata lain r diikuti vokal."],
  ],
  10: [
    ["'I saw a BLACKbird in the garden.' What does 'blackbird' mean here?", "A particular species of bird", ["Any bird that is black", "A bird painted black", "A bird seen at night"], "Compound noun dengan tekanan pada bagian pertama memiliki makna khusus, yaitu jenis burung tertentu."],
    ["'They live in a green HOUSE.' What does this mean?", "A house painted green", ["A glass building for plants", "An eco-friendly office", "A house full of plants"], "Adjektiva + nomina ditekan pada nomina, jadi artinya rumah berwarna hijau."],
    ["How is 'post office' normally stressed?", "POST office", ["post OF-fice", "post of-FICE", "post office with no stress"], "'Post office' adalah compound noun sehingga ditekan pada bagian pertama."],
    ["Which word carries the main stress in 'Can you look it up?'", "up", ["look", "it", "can"], "Pada phrasal verb, partikel seperti 'up' menerima tekanan utama."],
    ["How is the noun 'lookout' stressed?", "LOOK-out", ["look-OUT", "LOOK-OUT equally", "look-out with no stress"], "Nomina yang dibentuk dari phrasal verb ditekan pada bagian pertama."],
    ["Which option shows the correct stress for the verb and the noun?", "My car broke DOWN. / It was a BREAKdown.", ["My car BROKE down. / It was a BREAKdown.", "My car broke DOWN. / It was a breakDOWN.", "My car BROKE down. / It was a breakDOWN."], "Phrasal verb ditekan pada partikel, sedangkan nomina hasilnya ditekan pada bagian pertama."],
    ["Where does the stress fall in the initialism 'BBC'?", "On the last letter, C", ["On the first letter, B", "On the second letter, B", "Equally on all three letters"], "Pada initialism, tekanan utama jatuh pada huruf terakhir: /ˌbiː biː ˈsiː/."],
    ["Which phrase is stressed on the FIRST element?", "bus stop", ["big cat", "fast car", "old friend"], "'Bus stop' adalah compound noun, sedangkan yang lain adalah adjektiva + nomina."],
    ["Which phrase is stressed on the SECOND element?", "a red car", ["a toothbrush", "a bedroom", "a sunflower"], "'A red car' adalah adjektiva + nomina sehingga tekanan jatuh pada 'car'."],
    ["'She's an ENGLISH teacher' (stress on 'English') usually means what?", "She teaches English", ["She comes from England", "She is a teacher in England", "She is an English person"], "Sebagai compound, tekanan pada 'English' berarti guru bahasa Inggris."],
    ["How is 'turnout' stressed in 'The turnout was high'?", "TURN-out", ["turn-OUT", "TURN-OUT equally", "turn-out with no stress"], "'Turnout' adalah nomina dari phrasal verb, sehingga ditekan pada bagian pertama."],
    ["How is the acronym 'NASA' pronounced?", "As a word: /ˈnæsə/", ["Letter by letter: N-A-S-A", "As a word: /ˈneɪsə/", "As a word: /nɑːˈsɑː/"], "Acronym seperti NASA dibaca sebagai satu kata, bukan dieja per huruf."],
    ["How is 'toothbrush' stressed?", "TOOTH-brush", ["tooth-BRUSH", "TOOTH-BRUSH equally", "tooth-brush with no stress"], "'Toothbrush' adalah compound noun sehingga tekanan jatuh pada bagian pertama."],
    ["Why is 'blackbird' stressed on its first part?", "It is a compound with its own meaning", ["Colour adjectives are always stressed", "Bird names always stress the second part", "The first part has more letters"], "Compound noun memiliki makna khusus dan biasanya ditekan pada elemen pertama."],
    ["Which part of 'bad-tempered' is stressed in 'He's very bad-tempered'?", "TEM in 'tempered'", ["BAD", "PERED in 'tempered'", "BAD and TEM equally"], "Compound adjective seperti 'bad-tempered' ditekan pada elemen kedua: bad-TEM-pered."],
  ],
  11: [
    ["'She's going to Paris.' is said as completely new information. Where is the nuclear stress?", "Paris", ["She's", "going", "to"], "Tanpa kontras, nuclear stress jatuh secara default pada kata konten terakhir."],
    ["What does 'SHE's going to Paris' (stress on 'she') imply?", "She, not someone else, is going", ["She is going to Paris, not Rome", "She is really going, not just planning", "She is going today, not tomorrow"], "Memindahkan nuclear stress ke 'she' mengontraskan orangnya."],
    ["'I want a dog. The dog should be small.' Where is the nuclear stress in the second sentence?", "small", ["dog", "should", "be"], "'Dog' sudah diketahui sehingga di-de-accent, dan 'small' adalah informasi baru."],
    ["'What happened?' 'She left the meeting early.' Where does the nuclear stress fall?", "early", ["left", "meeting", "She"], "Pada wide focus nuclear stress jatuh pada kata konten terakhir, 'early'."],
    ["Which words carry contrastive stress in 'The data suggest a correlation, not a cause'?", "correlation, cause", ["data, suggest", "suggest, not", "data, cause"], "Dua hal yang dikontraskan, 'correlation' dan 'cause', menerima tekanan kontrastif."],
    ["Which words get extra emphatic stress in 'It was absolutely brilliant!'?", "absolutely, brilliant", ["it, was", "was, absolutely", "it, brilliant"], "Penekanan emfatik jatuh pada intensifier dan adjektiva untuk menunjukkan intensitas."],
    ["What is a tone unit?", "A stretch of speech with one nuclear stress", ["A single word said with a rising tone", "A list of all the stressed syllables", "A pause between two sentences"], "Tone unit adalah kelompok ujaran yang memiliki satu nuclear stress."],
    ["'Did Tom call you?' 'No, I called HIM.' Why is 'him' stressed?", "To contrast who called whom", ["Because pronouns are always stressed", "Because it is the first content word", "Because it is new information about Tom"], "Pronomina biasanya lemah, tetapi ditekan di sini untuk membalik peran penelepon dan yang ditelepon."],
    ["Where does nuclear stress fall by default?", "On the last content word of the tone unit", ["On the first word of the tone unit", "On the longest word in the sentence", "On the main verb of every sentence"], "Secara default nuclear stress jatuh pada kata konten terakhir dalam tone unit."],
    ["When 'fifteen' is contrasted with 'fifty', how is 'fifteen' stressed?", "fif-TEEN", ["FIF-teen", "fif-teen with no stress", "FIF-TEEN equally"], "Untuk membedakan dengan 'FIF-ty', 'fifteen' diucapkan dengan tekanan pada suku kedua."],
    ["Where is the nuclear stress in a neutral 'I'd like a cup of tea'?", "tea", ["like", "cup", "I'd"], "Pada kalimat netral nuclear stress jatuh pada kata konten terakhir, 'tea'."],
    ["Which sentence puts nuclear stress on a function word for contrast?", "I said ON the box, not IN it.", ["I put it on the BOX.", "The BOX is on the table.", "I put the box on the TABLE."], "Preposisi biasanya lemah, tetapi ditekan saat dikontraskan seperti 'ON' vs 'IN'."],
    ["'Who's going to Paris?' 'Anna's going to Paris.' Which word carries the nuclear stress?", "Anna", ["going", "Paris", "to"], "'Anna' menjawab pertanyaan 'who', jadi kata itu informasi baru; sisanya sudah diketahui."],
    ["When the nuclear stress moves to an early word, how are the words after it usually said?", "With low pitch and no stress", ["With a strong rise on each word", "With extra stress on each word", "With a long pause between them"], "Setelah nuclear stress, kata-kata berikutnya diucapkan rendah dan tanpa tekanan karena sudah diketahui."],
    ["What is it called when only one word is highlighted to correct or contrast?", "Narrow focus", ["Wide focus", "De-accenting", "Weak form"], "Narrow focus menyoroti satu kata saja untuk koreksi atau kontras."],
  ],
  12: [
    ["In 'Although it rained, the match continued', what tone usually ends 'Although it rained'?", "A rise, showing the sentence isn't finished", ["A full fall, showing the idea is complete", "A high fall, showing strong surprise", "A level tone, showing a list item"], "Klausa subordinat di awal kalimat biasanya naik untuk menandakan bahwa klausa utama akan menyusul."],
    ["In the same sentence, what tone usually ends 'the match continued'?", "A fall", ["A rise", "A level tone", "A high rise"], "Klausa utama di akhir kalimat ditutup dengan nada turun untuk menandakan selesai."],
    ["How is the clause 'who had led the firm for years' usually said in 'The CEO, who had led the firm for years, resigned'?", "Lower and faster, like an aside", ["Higher and slower, as the key point", "With a strong fall on every word", "Exactly like the main clause"], "Non-defining relative clause diucapkan dengan pitch lebih rendah dan lebih cepat seperti informasi tambahan."],
    ["'My brother who lives in Leeds is a doctor' said with no pauses suggests what?", "I have more than one brother", ["I have only one brother", "My brother is moving to Leeds", "I am not sure where he lives"], "Tanpa jeda, klausa relatifnya defining sehingga membedakan saudara ini dari saudara lain."],
    ["Which version, said with pauses and lower pitch on the middle clause, means ALL the students passed?", "The students, who studied hard, passed.", ["The students who studied hard passed.", "Only students who studied hard passed.", "The students who studied passed hard."], "Jeda dan pitch rendah menandai non-defining clause, sehingga semua siswa lulus."],
    ["In 'First, we collect data, then we analyse it, and finally we report it', where does the final fall come?", "On the last item", ["On the first item", "On every item", "On 'then'"], "Pada daftar, tiap item naik dan nada turun muncul pada item terakhir."],
    ["In 'If the results are negative, we'll reconsider the approach', which clause ends with the fall?", "The main (result) clause", ["The if-clause", "Both clauses equally", "Neither of the clauses"], "Klausa if biasanya naik, sedangkan klausa hasil di akhir turun."],
    ["In 'While the plan was sound, the execution was poor', what tone does 'sound' typically get?", "A fall-rise", ["A high fall", "A low level", "A rise-fall"], "Elemen yang dikontraskan sering diberi fall-rise untuk menandakan 'benar, tetapi...'."],
    ["What does a fall-rise on 'It could be argued...' signal?", "Tentativeness", ["Total certainty", "Anger", "A list"], "Fall-rise pada klaim akademik menandakan sikap hati-hati atau tentatif."],
    ["Why shouldn't you read a long academic sentence as one single tone unit?", "Listeners need sense groups to follow its structure", ["Long sentences must always end with a rise", "Each word needs its own separate tone unit", "Tone units are only used in casual speech"], "Membagi kalimat panjang ke dalam sense group membantu pendengar mengikuti strukturnya."],
    ["'He didn't come to the party because he was tired' said as ONE tone unit with a final fall-rise means what?", "He came, but not because he was tired", ["He stayed at home because he was tired", "He came because he wasn't tired", "He came early because he was tired"], "Dalam satu tone unit dengan fall-rise, negasi berlaku pada alasannya, bukan pada kedatangannya."],
    ["Where is the most natural tone-unit boundary in 'When we arrived at the hotel the room wasn't ready'?", "After 'hotel'", ["After 'arrived'", "After 'room'", "After 'when'"], "Batas tone unit yang alami berada di antara klausa subordinat dan klausa utama."],
    ["Which tone on 'Furthermore,' signals that the main clause is still to come?", "A slight rise", ["A full low fall", "A rise-fall", "A long silence"], "Discourse marker di awal kalimat biasanya sedikit naik untuk menandai kelanjutan."],
    ["How many tone units are most natural in 'The report, which I read yesterday, is excellent'?", "Three", ["One", "Two", "Four"], "Non-defining clause membentuk tone unit sendiri, sehingga ada tiga: subjek, klausa sisipan, dan predikat."],
    ["'I like tea, coffee and juice.' Which tone on 'juice' shows the list is complete?", "A fall", ["A rise", "A level tone", "A fall-rise"], "Nada turun pada item terakhir menandakan daftar sudah lengkap."],
  ],
  13: [
    ["Which word contains the long vowel /iː/?", "sheep", ["ship", "bit", "fill"], "'Sheep' /ʃiːp/ memakai /iː/ panjang, sedangkan yang lain memakai /ɪ/ pendek."],
    ["Which word contains the vowel /æ/?", "bad", ["bed", "said", "head"], "'Bad' /bæd/ memakai /æ/ terbuka, sedangkan tiga kata lain memakai /e/."],
    ["Which word contains the long vowel /uː/?", "pool", ["pull", "full", "book"], "'Pool' /puːl/ memakai /uː/ panjang, sedangkan yang lain memakai /ʊ/ pendek."],
    ["Which transcription of 'hurt' is correct?", "/hɜːt/", ["/hɒt/", "/hʌt/", "/hɑːt/"], "'Hurt' memakai vokal tengah panjang /ɜː/ tanpa /r/ dalam RP."],
    ["Which is the RP transcription of 'cart'?", "/kɑːt/", ["/kæt/", "/kʌt/", "/kɔːt/"], "'Cart' memakai /ɑː/ panjang di belakang, berbeda dari 'cat' /kæt/."],
    ["Which word contains the diphthong /ɔɪ/?", "choice", ["chose", "chase", "cheese"], "'Choice' /tʃɔɪs/ memakai diftong /ɔɪ/."],
    ["Which pair is a minimal pair for /ɪ/ and /iː/?", "bit – beat", ["bit – bet", "bit – but", "beat – bat"], "'Bit' /bɪt/ dan 'beat' /biːt/ hanya berbeda pada vokal /ɪ/ dan /iː/."],
    ["Which pair differs only in /æ/ versus /ʌ/?", "cat – cut", ["cat – cart", "cut – cot", "cat – kite"], "'Cat' /kæt/ dan 'cut' /kʌt/ hanya berbeda pada vokal /æ/ dan /ʌ/."],
    ["Which vowel is in 'caught' in RP?", "/ɔː/", ["/ɒ/", "/əʊ/", "/ɑː/"], "'Caught' /kɔːt/ memakai /ɔː/ panjang, berbeda dari 'cot' /kɒt/."],
    ["Which word rhymes with 'word' /wɜːd/?", "heard", ["ward", "lord", "hard"], "'Heard' /hɜːd/ memiliki vokal /ɜː/ yang sama dengan 'word'."],
    ["In 'now' /naʊ/, in which direction does the diphthong glide?", "From /a/ towards /ʊ/", ["From /ʊ/ towards /a/", "From /a/ towards /ɪ/", "From /ə/ towards /ʊ/"], "Diftong /aʊ/ dimulai dari /a/ yang terbuka lalu meluncur ke arah /ʊ/."],
    ["Which word has the same vowel as 'love' /lʌv/?", "blood", ["food", "good", "move"], "'Blood' /blʌd/ memakai /ʌ/ walaupun ditulis dengan 'oo'."],
    ["Which word contains the diphthong /eɪ/?", "great", ["greet", "grit", "bread"], "'Great' /ɡreɪt/ memakai diftong /eɪ/ walaupun ditulis dengan 'ea'."],
    ["Which word contains the short vowel /ʊ/?", "could", ["cool", "food", "rude"], "'Could' /kʊd/ memakai /ʊ/ pendek, sedangkan yang lain memakai /uː/."],
    ["Which word has the vowel /ɒ/ in RP?", "want", ["won't", "walk", "work"], "'Want' /wɒnt/ memakai /ɒ/, sedangkan won't /əʊ/, walk /ɔː/ dan work /ɜː/."],
  ],
  14: [
    ["Which of these consonants is voiced?", "/v/", ["/f/", "/s/", "/θ/"], "/v/ diucapkan dengan getaran pita suara, sedangkan /f/, /s/ dan /θ/ tidak."],
    ["Which word begins with a voiceless consonant?", "pin", ["bin", "gin", "din"], "'Pin' dimulai dengan /p/ tak bersuara, sedangkan yang lain dimulai dengan konsonan bersuara."],
    ["What is the final consonant sound in 'phase'?", "/z/", ["/s/", "/ʃ/", "/ʒ/"], "'Phase' /feɪz/ berakhir dengan /z/ bersuara, berbeda dari 'face' /feɪs/."],
    ["How is the -s ending pronounced in 'cows'?", "/z/", ["/s/", "/ɪz/", "/ʃ/"], "Setelah vokal atau diftong, akhiran -s dibaca /z/."],
    ["How is the -es ending pronounced in 'watches'?", "/ɪz/", ["/s/", "/z/", "/ez/"], "Setelah bunyi /tʃ/, akhiran -es menambah suku /ɪz/."],
    ["In which word is the /p/ most strongly aspirated?", "pin", ["spin", "happy", "stopped"], "/p/ di awal suku kata yang ditekan, seperti 'pin', diikuti semburan udara yang kuat."],
    ["Which word begins with the voiceless sound /θ/?", "thin", ["this", "then", "those"], "'Thin' dimulai dengan /θ/ tak bersuara, sedangkan yang lain dimulai dengan /ð/."],
    ["Which consonant is in the middle of 'measure'?", "/ʒ/", ["/ʃ/", "/z/", "/dʒ/"], "'Measure' /ˈmeʒə/ mengandung /ʒ/, pasangan bersuara dari /ʃ/."],
    ["Which word begins with /dʒ/?", "gin", ["chin", "give", "yes"], "'Gin' /dʒɪn/ dimulai dengan afrikat bersuara /dʒ/."],
    ["What is a simple way to feel whether a consonant is voiced?", "Touch your throat and feel for vibration", ["Hold a mirror in front of your mouth", "Check whether your lips are rounded", "Count the letters in the written word"], "Konsonan bersuara membuat pita suara bergetar, yang bisa dirasakan di tenggorokan."],
    ["Which pair differs only in voicing?", "fan – van", ["fan – fun", "fan – pan", "van – ban"], "/f/ dan /v/ sama-sama labiodental dan hanya berbeda pada ada atau tidaknya suara."],
    ["Besides the final consonant, what helps listeners tell 'cab' from 'cap'?", "The vowel is longer before voiced /b/", ["The vowel is shorter before voiced /b/", "The /k/ is voiced in 'cab'", "The /k/ is silent in 'cap'"], "Vokal sebelum konsonan bersuara diucapkan lebih panjang daripada sebelum konsonan tak bersuara."],
    ["Which word ends with a voiced consonant sound?", "bag", ["back", "bat", "bus"], "'Bag' berakhir dengan /ɡ/ bersuara, sedangkan yang lain berakhir dengan konsonan tak bersuara."],
    ["In 'What's the use?', which sound ends 'use'?", "/s/", ["/z/", "/ʒ/", "/ʃ/"], "Nomina 'use' diucapkan /juːs/, sedangkan verba 'use' diucapkan /juːz/."],
    ["Which pair of sounds are BOTH voiceless?", "/k/ and /tʃ/", ["/ɡ/ and /k/", "/v/ and /f/", "/z/ and /ð/"], "/k/ dan /tʃ/ sama-sama tak bersuara, sedangkan setiap pasangan lain mengandung bunyi bersuara."],
  ],
  15: [
    ["What do presenters often do with their pitch when starting a new section?", "Start on a higher pitch", ["Start on a lower pitch", "Keep a perfectly flat pitch", "Use a rising tone on every word"], "Memulai bagian baru dengan pitch lebih tinggi (high key) menandakan topik baru."],
    ["How is a short aside in a lecture usually delivered?", "Lower in pitch and a little faster", ["Higher in pitch and much slower", "Louder and with a high fall", "With a long pause after every word"], "Informasi sampingan biasanya diucapkan dengan pitch lebih rendah dan lebih cepat."],
    ["What does a clear falling tone on 'The findings demonstrate a link' signal?", "Confidence in the claim", ["Doubt about the claim", "A question to the audience", "A list still to continue"], "Nada turun penuh pada klaim akademik menandakan keyakinan."],
    ["'The results are significant...' said with a fall-rise most likely implies what?", "A reservation is about to follow", ["The speaker is completely certain", "The talk has now finished", "The speaker is asking a question"], "Fall-rise menandakan ada pembatasan atau 'tetapi' yang akan menyusul."],
    ["What does a short pause just before a technical term signal to listeners?", "That the term is important", ["That the speaker is lost", "That the talk is ending", "That the term is optional"], "Jeda strategis sebelum istilah penting menarik perhatian pendengar pada kata berikutnya."],
    ["What is the usual effect of a flat, monotone delivery in a lecture?", "Listeners lose concentration", ["Listeners follow more easily", "Key points stand out more", "The speaker sounds more confident"], "Pitch yang datar membuat pendengar sulit fokus karena tidak ada sinyal informasi penting."],
    ["Where does the highest pitch peak usually fall in an utterance?", "On the most informative word", ["On the first word spoken", "On the last function word", "On every content word equally"], "Puncak pitch tertinggi menandai kata yang paling informatif."],
    ["How is background information typically delivered in an academic talk?", "With a narrower, more level pitch", ["With a very wide pitch range", "With a high fall on every phrase", "With a long pause before each word"], "Informasi latar diucapkan dengan pitch lebih datar karena tidak sepenting poin utama."],
    ["In 'pausing for effect', how is 'for' usually linked to 'effect'?", "As /fər/, with a linking /r/", ["As /fɔː/, with a glottal stop", "As /fə/, with a linking /w/", "As /fɔːr/, with full stress"], "'For' memakai weak form dan r-nya diucapkan sebagai linking /r/ karena 'effect' dimulai dengan vokal."],
    ["What does slowing down on one sentence in a talk usually signal?", "A key point", ["A joke", "An aside", "A mistake"], "Tempo yang diperlambat menandakan bahwa poin itu penting untuk dicatat."],
    ["A presenter concludes: 'So, cost is the main factor.' Which tone fits best on 'factor'?", "A clear fall", ["A high rise", "A fall-rise", "A level tone"], "Kesimpulan yang tegas diakhiri dengan nada turun yang jelas."],
    ["What is a pitch 'reset' in an academic presentation?", "Returning to a higher pitch for a new point", ["Dropping to a whisper at the end of a talk", "Repeating the previous sentence more slowly", "Changing from British to American accent"], "Pitch reset adalah kembali ke pitch lebih tinggi untuk menandai poin baru."],
    ["Which combination best signals background information?", "Faster tempo, narrower pitch range", ["Slower tempo, wider pitch range", "Long pauses, high pitch peaks", "Slower tempo, a final high fall"], "Informasi latar biasanya diucapkan lebih cepat dengan rentang pitch yang lebih sempit."],
    ["Which combination best highlights a key claim?", "Slower tempo and a higher pitch peak", ["Faster tempo and a narrower pitch range", "Lower pitch and a quicker delivery", "A flat pitch with no pauses at all"], "Memperlambat tempo dan menaikkan puncak pitch membuat klaim penting menonjol."],
    ["What tone usually ends a rhetorical question like 'So why does this matter?' in a talk?", "Falling", ["Rising", "Level", "Fall-rise"], "Pertanyaan retoris dengan kata tanya Wh- biasanya diucapkan dengan nada turun."],
  ],
  16: [
    ["In the common fast-speech form /ˈkʌmftəbl/, which part of 'comfortable' is not pronounced?", "The vowel of '-for-'", ["The vowel of 'com-'", "The final '-ble'", "The /t/ of '-ta-'"], "Dalam bentuk tereduksi, suku '-for-' hilang sehingga kata menjadi tiga suku."],
    ["How many syllables does 'interesting' have in its common reduced form /ˈɪntrəstɪŋ/?", "Three", ["Two", "Four", "Five"], "Bentuk tereduksi /ˈɪn.trə.stɪŋ/ terdiri dari tiga suku kata."],
    ["How is 'chocolate' normally pronounced in British English?", "/ˈtʃɒklət/", ["/ˈtʃɒkəleɪt/", "/tʃɒkəˈlɑːt/", "/ˈtʃəʊkəleɪt/"], "'Chocolate' biasanya diucapkan dua suku, /ˈtʃɒk.lət/, dengan 'o' tengah yang hilang."],
    ["Which written vowel is usually silent in 'vegetable' in everyday speech?", "The second 'e'", ["The first 'e'", "The 'a'", "The final 'e' only"], "'Vegetable' biasanya diucapkan /ˈvedʒtəbl/ dengan 'e' kedua yang hilang."],
    ["You hear /ˈjuːʒli/ in fast speech. Which word is it?", "usually", ["uselessly", "visually", "jewellery"], "/ˈjuːʒli/ adalah bentuk sangat tereduksi dari 'usually'."],
    ["Which part of 'different' is usually lost in natural speech?", "The middle '-er-'", ["The first 'di-'", "The final '-ent'", "The double 'ff'"], "'Different' biasanya diucapkan /ˈdɪfrənt/ dengan suku tengah '-er-' yang hilang."],
    ["Which word does NOT usually lose a syllable in fast speech?", "computer", ["camera", "every", "history"], "'Computer' ditekan di suku tengah sehingga tidak ada vokal lemah di antara konsonan yang bisa hilang."],
    ["Which vowels are most likely to disappear inside long words?", "Unstressed /ə/ or /ɪ/ between consonants", ["Stressed long vowels like /iː/ or /ɑː/", "Diphthongs at the start of words", "Any vowel at the end of a word"], "Vokal pendek tanpa tekanan yang diapit konsonan paling sering hilang dalam ucapan cepat."],
    ["Which reduced form of 'temperature' is natural in British English?", "/ˈtemprətʃə/", ["/ˌtempəˈreɪtʃə/", "/temˈprətʃə/", "/ˈtempreɪtʃə/"], "Dalam ucapan alami 'temperature' kehilangan satu vokal lemah: /ˈtem.prə.tʃə/."],
    ["How many syllables does 'every' normally have?", "Two", ["One", "Three", "Four"], "'Every' biasanya diucapkan /ˈevri/ dengan dua suku kata."],
    ["When is it best to pronounce every syllable of a long word?", "In slow, careful speech for clarity", ["In fast conversation with friends", "Whenever the word is unstressed", "Only when reading a text silently"], "Semua suku kata diucapkan dalam ucapan lambat dan formal yang memerlukan kejelasan maksimum."],
    ["Which day of the week has a silent 'd' and a silent middle 'e'?", "Wednesday", ["Tuesday", "Thursday", "Saturday"], "'Wednesday' diucapkan dengan /wenz/ di awal, sehingga 'd' dan 'e' tengah tidak terdengar."],
    ["In the fast-speech form /ˈhɪstri/, which letter of 'history' is not pronounced?", "o", ["i", "s", "y"], "Pada /ˈhɪs.tri/ vokal 'o' yang tidak ditekan hilang."],
    ["What is the loss of an unstressed vowel inside a word, as in /ˈkæmrə/ for 'camera', called?", "Elision", ["Assimilation", "Aspiration", "Intrusion"], "Penghilangan bunyi dalam ucapan seperti ini disebut elision (atau syncope)."],
    ["Which syllable of 'medicine' is often dropped in British English?", "The middle '-i-'", ["The first 'me-'", "The final '-cine'", "No syllable at all"], "British English sering mengucapkan 'medicine' sebagai /ˈmedsn/ tanpa suku tengah."],
  ],
  17: [
    ["How is the -ed ending pronounced in 'wanted'?", "/ɪd/", ["/t/", "/d/", "/ed/"], "Setelah /t/, akhiran -ed menambah suku /ɪd/."],
    ["How is the -ed ending pronounced in 'walked'?", "/t/", ["/d/", "/ɪd/", "/ed/"], "/k/ tak bersuara, sehingga -ed dibaca /t/."],
    ["How is the -ed ending pronounced in 'called'?", "/d/", ["/t/", "/ɪd/", "/ed/"], "/l/ bersuara, sehingga -ed dibaca /d/."],
    ["How is the -ed ending pronounced in 'laughed'?", "/t/", ["/d/", "/ɪd/", "/ɡd/"], "'Laugh' berakhir dengan bunyi /f/ tak bersuara, sehingga -ed dibaca /t/."],
    ["How is 'learned' pronounced in 'a learned professor'?", "/ˈlɜːnɪd/", ["/lɜːnd/", "/lɜːnt/", "/ˈliːnɪd/"], "Sebagai adjektiva yang berarti terpelajar, 'learned' diucapkan dengan /ɪd/."],
    ["Which verb's -ed ending adds an extra syllable?", "decided", ["played", "watched", "lived"], "'Decide' berakhir dengan /d/, sehingga -ed menambah suku /ɪd/."],
    ["In which word is the -ed ending pronounced /d/?", "allowed", ["stopped", "washed", "reached"], "'Allow' berakhir dengan diftong (bersuara), sehingga -ed dibaca /d/."],
    ["Which transcription of 'watched' is correct?", "/wɒtʃt/", ["/wɒtʃd/", "/ˈwɒtʃɪd/", "/wɔːtʃt/"], "/tʃ/ tak bersuara sehingga -ed dibaca /t/, dan vokalnya /ɒ/."],
    ["How is the adjective 'naked' pronounced?", "/ˈneɪkɪd/", ["/neɪkt/", "/neɪkd/", "/ˈnækɪd/"], "Adjektiva 'naked' selalu diucapkan dengan /ɪd/."],
    ["Which word's -ed ending sounds different from the others?", "played", ["worked", "kissed", "fixed"], "'Played' berakhir /d/, sedangkan worked, kissed dan fixed berakhir /t/."],
    ["How many syllables does 'needed' have?", "Two", ["One", "Three", "Four"], "'Need' berakhir dengan /d/, sehingga 'needed' /ˈniːdɪd/ punya dua suku."],
    ["How is 'aged' pronounced in 'He cared for his aged parents'?", "/ˈeɪdʒɪd/", ["/eɪdʒd/", "/eɪdʒt/", "/ˈeɪɡɪd/"], "'Aged' sebagai adjektiva berarti tua diucapkan /ˈeɪdʒɪd/, berbeda dari 'aged 20' /eɪdʒd/."],
    ["Why is the -ed ending in 'played' pronounced /d/?", "The verb ends in a voiced vowel sound", ["The verb ends in a /t/ or /d/ sound", "The verb ends in a voiceless sound", "All regular verbs end in /d/"], "Setelah vokal atau konsonan bersuara, akhiran -ed dibaca /d/."],
    ["How is the adjective 'crooked' pronounced in 'a crooked line'?", "/ˈkrʊkɪd/", ["/krʊkt/", "/krʊkd/", "/ˈkruːkɪd/"], "Adjektiva 'crooked' (bengkok) selalu diucapkan dengan /ɪd/."],
    ["How is the -ed ending pronounced in 'occurred'?", "/d/", ["/t/", "/ɪd/", "/ed/"], "'Occur' berakhir dengan vokal /ɜː/ dalam RP, sehingga -ed dibaca /d/: /əˈkɜːd/."],
  ],
  18: [
    ["How is '101' read aloud in British English?", "one hundred and one", ["one hundred one", "one zero one", "a hundred-one"], "British English mewajibkan 'and' setelah 'hundred': one hundred and one."],
    ["How is the decimal '3.5' read aloud?", "three point five", ["three comma five", "three and five", "three dot fifty"], "Titik desimal dibaca 'point', dan angka sesudahnya dibaca digit per digit."],
    ["Where is the stress in 'per cent'?", "per CENT", ["PER cent", "per cent with no stress", "PER CENT equally"], "'Per cent' diucapkan /pəˈsent/ dengan tekanan pada suku kedua."],
    ["How is the year '1999' normally read?", "nineteen ninety-nine", ["one thousand nine hundred ninety-nine", "one nine nine nine", "nineteen hundred ninety-nine"], "Tahun sebelum 2000 dibaca berpasangan: nineteen ninety-nine."],
    ["Where does the main stress fall in 'GDP'?", "On P", ["On G", "On D", "On G and P equally"], "Initialism ditekan pada huruf terakhir: /ˌdʒiː diː ˈpiː/."],
    ["How is 'NATO' pronounced?", "As a word: /ˈneɪtəʊ/", ["Letter by letter: N-A-T-O", "As a word: /ˈnætəʊ/", "As a word: /nəˈtəʊ/"], "NATO adalah acronym yang dibaca sebagai kata: /ˈneɪtəʊ/."],
    ["How is the fraction '3/4' read aloud?", "three quarters", ["three fourth", "three of four", "three quarter"], "Pecahan 3/4 dibaca 'three quarters', dengan bentuk jamak karena pembilangnya lebih dari satu."],
    ["How is '£10,000' read aloud?", "ten thousand pounds", ["pounds ten thousand", "ten thousands pounds", "ten thousand pound"], "Jumlah dibaca dahulu, lalu satuannya dalam bentuk jamak: ten thousand pounds."],
    ["How is '3.14' read aloud?", "three point one four", ["three point fourteen", "three comma one four", "three and fourteen"], "Digit setelah titik desimal dibaca satu per satu: one four."],
    ["In British English, how is '0' often read in a phone number?", "oh", ["nil", "zed", "nothing"], "Dalam nomor telepon, penutur British sering membaca 0 sebagai 'oh'."],
    ["How is '$5M' read aloud?", "five million dollars", ["five dollars million", "five millions dollars", "dollars five million"], "Angka dibaca dahulu, lalu satuan mata uang: five million dollars."],
    ["Which of these is an acronym (said as a word), not an initialism?", "NATO", ["BBC", "UN", "USA"], "NATO dibaca sebagai kata, sedangkan BBC, UN dan USA dieja per huruf."],
    ["How is the year '1066' normally read?", "ten sixty-six", ["one thousand sixty-six", "one zero six six", "ten hundred sixty-six"], "Tahun empat digit sebelum 2000 dibaca berpasangan: ten sixty-six."],
    ["When said on their own, how are 'thirteen' and 'thirty' stressed?", "thir-TEEN / THIR-ty", ["THIR-teen / thir-TY", "THIR-teen / THIR-ty", "thir-TEEN / thir-TY"], "Bilangan -teen ditekan pada suku kedua, sedangkan -ty ditekan pada suku pertama."],
    ["How is '2,305' read aloud in British English?", "two thousand, three hundred and five", ["two thousand, three hundred five", "two thousand and three hundred five", "twenty-three hundred and five"], "British English menambahkan 'and' sebelum angka puluhan atau satuan: three hundred and five."],
  ],
  19: [
    ["Which transcription of 'paradigm' is correct?", "/ˈpærədaɪm/", ["/ˈpærədɪɡm/", "/pəˈrædaɪm/", "/ˈpærədaɪɡəm/"], "Huruf 'g' dalam 'paradigm' tidak diucapkan, dan tekanan ada di suku pertama."],
    ["Where is the main stress in 'hierarchy'?", "HI-er-ar-chy", ["hi-ER-ar-chy", "hi-er-AR-chy", "hi-er-ar-CHY"], "'Hierarchy' diucapkan /ˈhaɪərɑːki/ dengan tekanan pada suku pertama."],
    ["Where is the main stress in 'deteriorate'?", "de-TE-ri-o-rate", ["DE-te-ri-o-rate", "de-te-RI-o-rate", "de-te-ri-o-RATE"], "'Deteriorate' diucapkan /dɪˈtɪəriəreɪt/ dengan tekanan pada suku kedua."],
    ["Which sound begins 'genre' in British English?", "/ʒ/", ["/dʒ/", "/ɡ/", "/ʃ/"], "'Genre' berasal dari bahasa Prancis dan diucapkan /ˈʒɒnrə/."],
    ["Which sound does 'th' represent in 'algorithm'?", "/ð/", ["/θ/", "/t/", "/d/"], "'Algorithm' diucapkan /ˈælɡərɪðəm/ dengan /ð/ bersuara."],
    ["Which sound is in the middle of 'cohesion'?", "/ʒ/", ["/z/", "/ʃ/", "/dʒ/"], "'Cohesion' diucapkan /kəʊˈhiːʒn/, dengan bunyi /ʒ/ seperti pada 'measure'."],
    ["Where is the main stress in 'hypothesis'?", "hy-POTH-e-sis", ["HY-poth-e-sis", "hy-poth-E-sis", "hy-poth-e-SIS"], "'Hypothesis' diucapkan /haɪˈpɒθəsɪs/ dengan tekanan pada suku kedua."],
    ["Where is the main stress in 'phenomena'?", "phe-NOM-e-na", ["PHE-nom-e-na", "phe-nom-E-na", "phe-nom-e-NA"], "'Phenomena' diucapkan /fəˈnɒmɪnə/ dengan tekanan pada suku kedua."],
    ["Where is the main stress in British 'liaison'?", "li-AI-son", ["LI-ai-son", "li-ai-SON", "LI-AI-son"], "Dalam British English 'liaison' diucapkan /liˈeɪzn/ dengan tekanan pada suku kedua."],
    ["Which transcription of 'pronunciation' is correct?", "/prəˌnʌnsiˈeɪʃn/", ["/prəˌnaʊnsiˈeɪʃn/", "/ˌprəʊnaʊnˈseɪʃn/", "/prəˈnʌnsieɪʃn/"], "'Pronunciation' memakai /ʌ/ ('nun'), bukan /aʊ/ seperti pada 'pronounce'."],
    ["Where is the main stress in 'mischievous'?", "MIS-chie-vous", ["mis-CHIE-vous", "mis-chie-VOUS", "mis-CHIE-vi-ous"], "'Mischievous' diucapkan /ˈmɪstʃɪvəs/, tiga suku dengan tekanan di awal."],
    ["Which letter is silent in 'psychology'?", "p", ["s", "y", "h"], "'Psychology' diucapkan /saɪˈkɒlədʒi/, dengan 'p' di awal yang tidak diucapkan."],
    ["Where is the main stress in 'entrepreneur'?", "en-tre-pre-NEUR", ["EN-tre-pre-neur", "en-TRE-pre-neur", "en-tre-PRE-neur"], "'Entrepreneur' berasal dari bahasa Prancis dan ditekan pada suku terakhir: /ˌɒntrəprəˈnɜː/."],
    ["Which transcription of 'epitome' is correct?", "/ɪˈpɪtəmi/", ["/ˈepɪtəʊm/", "/ˈepɪtaɪm/", "/ɪˈpɪtəʊm/"], "'Epitome' punya empat suku dengan tekanan di suku kedua dan 'e' akhir yang diucapkan."],
    ["Which pair shows the correct stress for 'analyse' and 'analysis'?", "AN-a-lyse / a-NAL-y-sis", ["a-NAL-yse / AN-a-ly-sis", "AN-a-lyse / AN-a-ly-sis", "a-NAL-yse / a-NAL-y-sis"], "Verba 'analyse' ditekan di suku pertama, sedangkan nomina 'analysis' di suku kedua."],
  ],
  20: [
    ["Which option shows the correct stress for 'photo', 'photography' and 'photographic'?", "PHO-to, pho-TOG-ra-phy, pho-to-GRAPH-ic", ["PHO-to, PHO-to-gra-phy, pho-to-GRAPH-ic", "pho-TO, pho-TOG-ra-phy, pho-TO-graph-ic", "PHO-to, pho-tog-RA-phy, PHO-to-graph-ic"], "Tekanan bergeser dalam keluarga kata ini: suku pertama, kedua, lalu ketiga."],
    ["How many schwa sounds are there in 'a cup of tea' /ə ˈkʌp əv ˈtiː/?", "Two", ["One", "Three", "Four"], "'A' dan 'of' memakai schwa, sedangkan 'cup' dan 'tea' memakai vokal penuh."],
    ["How is the -ed ending pronounced in 'started'?", "/ɪd/", ["/t/", "/d/", "/ed/"], "'Start' berakhir dengan /t/, sehingga -ed menambah suku /ɪd/."],
    ["How is the -ed ending pronounced in 'stopped'?", "/t/", ["/d/", "/ɪd/", "/pd/"], "/p/ tak bersuara, sehingga -ed dibaca /t/."],
    ["Which sound links 'two' and 'eggs' in natural speech?", "/w/", ["/j/", "/r/", "/h/"], "Setelah /uː/ sebelum vokal muncul linking /w/: two_w_eggs."],
    ["Which transcription of 'leave' is correct?", "/liːv/", ["/lɪv/", "/liːf/", "/leɪv/"], "'Leave' memakai /iː/ panjang, berbeda dari 'live' /lɪv/."],
    ["What is the final sound of the verb 'breathe'?", "/ð/", ["/θ/", "/z/", "/v/"], "Verba 'breathe' /briːð/ berakhir dengan /ð/ bersuara, sedangkan nomina 'breath' /breθ/ berakhir dengan /θ/."],
    ["'You wanted tea, right?' Which reply puts the stress where it belongs?", "No, I wanted COFFEE.", ["No, I WANTED coffee.", "No, YOU wanted coffee.", "No, I wanted coffee TOO."], "Kata yang mengoreksi informasi, 'coffee', menerima tekanan kontrastif."],
    ["Where does the stress fall in 'the EU'?", "On U", ["On E", "On 'the'", "On E and U equally"], "Initialism ditekan pada huruf terakhir: /ˌiː ˈjuː/."],
    ["Which letter is silent in 'subtle'?", "b", ["t", "s", "l"], "'Subtle' diucapkan /ˈsʌtl/, dengan huruf 'b' yang tidak diucapkan."],
    ["Which letter is silent in 'island'?", "s", ["l", "d", "n"], "'Island' diucapkan /ˈaɪlənd/, dengan huruf 's' yang tidak diucapkan."],
    ["Which letter is silent in 'receipt'?", "p", ["c", "t", "i"], "'Receipt' diucapkan /rɪˈsiːt/, dengan huruf 'p' yang tidak diucapkan."],
    ["What is 'shadowing' as a pronunciation practice technique?", "Repeating just after a recording, copying its rhythm and intonation", ["Reading a text silently while underlining every stressed word", "Writing out the IPA for every word in a long text", "Recording yourself once and never listening to it again"], "Shadowing berarti menirukan rekaman penutur asli segera setelah mendengarnya, termasuk ritme dan intonasinya."],
    ["Where is the main stress in 'photographer'?", "pho-TOG-ra-pher", ["PHO-tog-ra-pher", "pho-tog-RA-pher", "pho-tog-ra-PHER"], "'Photographer' diucapkan /fəˈtɒɡrəfə/, sama seperti 'photography' dengan tekanan pada suku kedua."],
    ["Which word contains the vowel /ʌ/?", "money", ["moment", "morning", "modern"], "'Money' /ˈmʌni/ memakai /ʌ/ walaupun ditulis dengan huruf 'o'."],
  ],
};
