import type { PassageSource } from './types';

// Graded English reading/listening passages for CEFR B1 (last one) and B2-C2.
export const englishPassagesUpper: PassageSource[] = [
  {
    id: 'en-b1-train', level: 'b1', title: 'Perjalanan kereta pertama', native: 'My first long train journey',
    sentences: [
      ['Last December I travelled from Jakarta to Surabaya by train for the first time.', '', 'Desember lalu saya pertama kali bepergian dari Jakarta ke Surabaya dengan kereta.'],
      ['I had always flown before, but this time I wanted to see the countryside.', '', 'Sebelumnya saya selalu naik pesawat, tetapi kali ini saya ingin melihat pedesaan.'],
      ['The journey took about nine hours, which was longer than I expected.', '', 'Perjalanannya sekitar sembilan jam, lebih lama dari perkiraan saya.'],
      ['Through the window I saw rice fields, volcanoes and small stations full of vendors.', '', 'Dari jendela saya melihat sawah, gunung berapi, dan stasiun kecil penuh pedagang.'],
      ['An elderly man sitting next to me told me stories about his childhood.', '', 'Seorang bapak tua di sebelah saya menceritakan masa kecilnya.'],
      ['Although my back hurt by the end, I did not regret it at all.', '', 'Meskipun punggung saya sakit di akhir, saya sama sekali tidak menyesal.'],
      ['Next time I will book a sleeper seat and take a good book.', '', 'Lain kali saya akan memesan kursi tidur dan membawa buku yang bagus.'],
    ],
    glossary: [['countryside', '', 'pedesaan'], ['vendor', '', 'pedagang'], ['elderly', '', 'lanjut usia'], ['regret', '', 'menyesal']],
    questions: [
      ['Mengapa penulis memilih kereta?', 'Ingin melihat pedesaan', ['Tiketnya lebih murah', 'Takut naik pesawat', 'Pesawat penuh']],
      ['Berapa lama perjalanannya?', 'Sekitar sembilan jam', ['Sekitar lima jam', 'Dua belas jam', 'Satu hari penuh']],
      ['Apa rencana penulis untuk perjalanan berikutnya?', 'Memesan kursi tidur dan membawa buku', ['Naik pesawat saja', 'Membawa makanan sendiri', 'Pergi bersama keluarga']],
    ],
  },
  // ---------------------------------------------------------------- B2
  {
    id: 'en-b2-gig', level: 'b2', title: 'Ekonomi pekerja lepas', native: 'The rise of the gig economy',
    sentences: [
      ['Over the past decade, millions of people have started earning a living through apps.', '', 'Selama satu dekade terakhir, jutaan orang mulai mencari nafkah lewat aplikasi.'],
      ['Drivers, couriers and freelance designers can choose when and how much they work.', '', 'Pengemudi, kurir, dan desainer lepas bisa memilih kapan dan berapa banyak mereka bekerja.'],
      ['For many, this flexibility is the main attraction, particularly for students and parents.', '', 'Bagi banyak orang, fleksibilitas ini daya tarik utama, terutama bagi pelajar dan orang tua.'],
      ['However, gig workers rarely receive health insurance, paid holidays or a pension.', '', 'Namun, pekerja lepas jarang mendapat asuransi kesehatan, cuti berbayar, atau pensiun.'],
      ['Their income can also drop suddenly if the company changes its rates.', '', 'Penghasilan mereka juga bisa turun tiba-tiba jika perusahaan mengubah tarif.'],
      ['Several governments are now debating whether these workers should be treated as employees.', '', 'Beberapa pemerintah kini memperdebatkan apakah pekerja ini harus diperlakukan sebagai karyawan.'],
      ['Critics warn that stricter rules could raise prices and reduce the number of jobs.', '', 'Para kritikus memperingatkan aturan lebih ketat bisa menaikkan harga dan mengurangi jumlah pekerjaan.'],
      ['Finding a balance between flexibility and security remains a major challenge.', '', 'Menemukan keseimbangan antara fleksibilitas dan keamanan tetap menjadi tantangan besar.'],
    ],
    glossary: [['earn a living', '', 'mencari nafkah'], ['flexibility', '', 'fleksibilitas'], ['pension', '', 'dana pensiun'], ['rate', '', 'tarif']],
    questions: [
      ['Apa daya tarik utama kerja lepas?', 'Fleksibilitas waktu kerja', ['Gaji tetap yang tinggi', 'Asuransi kesehatan', 'Jenjang karier jelas']],
      ['Apa kekurangan kerja lepas menurut teks?', 'Jarang mendapat asuransi, cuti, dan pensiun', ['Jam kerja terlalu kaku', 'Harus bekerja di kantor', 'Tidak boleh memilih klien']],
      ['Apa kekhawatiran para kritikus?', 'Aturan ketat bisa menaikkan harga dan mengurangi pekerjaan', ['Pekerja akan terlalu kaya', 'Aplikasi akan dilarang', 'Pajak akan dihapus']],
    ],
  },
  {
    id: 'en-b2-tourism', level: 'b2', title: 'Pariwisata berlebihan', native: 'When tourism becomes too much',
    sentences: [
      ['Tourism brings jobs and income, yet some destinations are now struggling with too many visitors.', '', 'Pariwisata membawa pekerjaan dan pendapatan, namun beberapa destinasi kini kewalahan dengan terlalu banyak pengunjung.'],
      ['In popular areas, rents have risen so sharply that local families can no longer afford to live there.', '', 'Di kawasan populer, sewa naik begitu tajam sehingga keluarga lokal tidak lagi mampu tinggal di sana.'],
      ['Traffic jams, rubbish and water shortages have become common during the high season.', '', 'Kemacetan, sampah, dan kekurangan air menjadi hal biasa saat musim ramai.'],
      ['Some places have responded by introducing tourist taxes or limiting daily visitor numbers.', '', 'Beberapa tempat merespons dengan memberlakukan pajak turis atau membatasi jumlah pengunjung harian.'],
      ['Others are promoting lesser-known villages to spread visitors more evenly.', '', 'Tempat lain mempromosikan desa yang kurang dikenal agar pengunjung lebih merata.'],
      ['Travellers can help too, for example by visiting outside peak months and staying in locally owned guesthouses.', '', 'Wisatawan juga bisa membantu, misalnya berkunjung di luar bulan puncak dan menginap di penginapan milik warga.'],
      ['The goal is not to stop tourism, but to make sure local communities benefit from it.', '', 'Tujuannya bukan menghentikan pariwisata, tetapi memastikan komunitas lokal mendapat manfaatnya.'],
    ],
    glossary: [['destination', '', 'tujuan wisata'], ['afford', '', 'mampu membayar'], ['shortage', '', 'kekurangan'], ['peak', '', 'puncak']],
    questions: [
      ['Mengapa keluarga lokal pindah dari kawasan populer?', 'Sewa naik terlalu tajam', ['Terlalu banyak banjir', 'Tidak ada pekerjaan', 'Sekolah ditutup']],
      ['Apa salah satu kebijakan yang disebutkan?', 'Pajak turis atau pembatasan pengunjung harian', ['Melarang semua turis asing', 'Menutup bandara', 'Menggratiskan hotel']],
      ['Apa tujuan utama menurut penulis?', 'Memastikan komunitas lokal mendapat manfaat', ['Menghentikan pariwisata sepenuhnya', 'Menambah hotel besar', 'Menaikkan harga tiket pesawat']],
    ],
  },
  {
    id: 'en-b2-ai-school', level: 'b2', title: 'AI di sekolah', native: 'Artificial intelligence in the classroom',
    sentences: [
      ['Chatbots that can write essays in seconds have forced schools to rethink how they assess students.', '', 'Chatbot yang bisa menulis esai dalam hitungan detik memaksa sekolah memikirkan ulang cara menilai siswa.'],
      ['Some teachers initially banned these tools, fearing widespread cheating.', '', 'Beberapa guru awalnya melarang alat ini karena khawatir kecurangan meluas.'],
      ['Others argue that banning them is unrealistic, since students will use them anyway.', '', 'Yang lain berpendapat melarangnya tidak realistis karena siswa tetap akan memakainya.'],
      ['Instead, they are teaching students how to check AI answers and identify mistakes.', '', 'Sebaliknya, mereka mengajari siswa cara memeriksa jawaban AI dan menemukan kesalahan.'],
      ['More assignments are now done in class, and oral presentations are becoming more common.', '', 'Lebih banyak tugas kini dikerjakan di kelas, dan presentasi lisan makin umum.'],
      ['Used wisely, AI can act as a patient tutor that explains difficult ideas in different ways.', '', 'Jika digunakan dengan bijak, AI bisa menjadi tutor sabar yang menjelaskan gagasan sulit dengan berbagai cara.'],
      ['The key question is no longer whether students use AI, but how they use it.', '', 'Pertanyaan kuncinya bukan lagi apakah siswa memakai AI, tetapi bagaimana mereka memakainya.'],
    ],
    glossary: [['assess', '', 'menilai'], ['widespread', '', 'meluas'], ['assignment', '', 'tugas'], ['tutor', '', 'guru privat']],
    questions: [
      ['Mengapa beberapa guru awalnya melarang chatbot?', 'Khawatir kecurangan meluas', ['Terlalu mahal', 'Merusak komputer', 'Dilarang pemerintah']],
      ['Apa perubahan dalam cara penilaian?', 'Lebih banyak tugas di kelas dan presentasi lisan', ['Ujian dihapus', 'Semua tugas dikerjakan AI', 'Nilai diberikan acak']],
      ['Apa pertanyaan kunci menurut teks?', 'Bagaimana siswa memakai AI', ['Apakah AI harus dilarang', 'Berapa harga AI', 'Siapa pembuat AI']],
    ],
  },
  {
    id: 'en-b2-urban-farm', level: 'b2', title: 'Kebun di atap kota', native: 'Farming on city rooftops',
    sentences: [
      ['In crowded cities where land is scarce, rooftops are being turned into vegetable gardens.', '', 'Di kota padat yang lahannya langka, atap-atap diubah menjadi kebun sayur.'],
      ['These urban farms supply restaurants and local residents with fresh produce.', '', 'Kebun kota ini memasok restoran dan warga sekitar dengan hasil panen segar.'],
      ['Because the food travels only a few metres, transport costs and emissions are reduced.', '', 'Karena makanan hanya menempuh beberapa meter, biaya transportasi dan emisi berkurang.'],
      ['The plants also help cool buildings, which lowers electricity bills in hot weather.', '', 'Tanaman juga membantu mendinginkan gedung sehingga tagihan listrik turun saat cuaca panas.'],
      ['However, setting up a rooftop farm is expensive, and not every roof is strong enough.', '', 'Namun, membangun kebun atap itu mahal, dan tidak semua atap cukup kuat.'],
      ['Some projects depend on volunteers and struggle to make a profit.', '', 'Beberapa proyek bergantung pada relawan dan kesulitan meraih keuntungan.'],
      ['Even so, supporters believe they reconnect city dwellers with where their food comes from.', '', 'Meski begitu, pendukungnya yakin kebun ini menghubungkan kembali warga kota dengan asal makanan mereka.'],
    ],
    glossary: [['scarce', '', 'langka'], ['produce', '', 'hasil pertanian'], ['emission', '', 'emisi'], ['dweller', '', 'penghuni']],
    questions: [
      ['Mengapa emisi berkurang?', 'Makanan hanya menempuh jarak pendek', ['Tidak memakai pupuk', 'Semua dikerjakan relawan', 'Sayurnya tidak dimasak']],
      ['Apa manfaat lain tanaman di atap?', 'Mendinginkan gedung', ['Menambah lantai gedung', 'Mengurangi kebisingan jalan', 'Menaikkan harga sewa']],
      ['Apa kendala kebun atap?', 'Mahal dan tidak semua atap cukup kuat', ['Tidak ada pembeli', 'Dilarang di semua kota', 'Tanaman tidak bisa tumbuh']],
    ],
  },
  {
    id: 'en-b2-fake-news', level: 'b2', title: 'Melawan berita palsu', native: 'Fighting fake news',
    sentences: [
      ['False stories often spread faster online than accurate ones, because they tend to be more shocking.', '', 'Berita palsu sering menyebar lebih cepat daripada berita akurat karena cenderung lebih mengejutkan.'],
      ['During elections and health emergencies, misinformation can have serious consequences.', '', 'Selama pemilu dan darurat kesehatan, disinformasi bisa berakibat serius.'],
      ['Fact-checking organizations investigate viral claims and publish corrections.', '', 'Organisasi pemeriksa fakta menyelidiki klaim viral dan menerbitkan koreksi.'],
      ['Unfortunately, corrections rarely reach as many people as the original rumour.', '', 'Sayangnya, koreksi jarang menjangkau sebanyak orang yang menerima rumor aslinya.'],
      ['Experts therefore recommend teaching media literacy from primary school onwards.', '', 'Karena itu para ahli menyarankan pengajaran literasi media sejak sekolah dasar.'],
      ['Simple habits, such as checking the source and the date, can prevent us from sharing false information.', '', 'Kebiasaan sederhana, seperti memeriksa sumber dan tanggal, bisa mencegah kita membagikan informasi palsu.'],
      ['Before forwarding a message, it is worth pausing for a moment and asking who benefits from it.', '', 'Sebelum meneruskan pesan, ada baiknya berhenti sejenak dan bertanya siapa yang diuntungkan.'],
    ],
    glossary: [['accurate', '', 'akurat'], ['misinformation', '', 'disinformasi'], ['rumour', '', 'rumor/kabar burung'], ['forward', '', 'meneruskan']],
    questions: [
      ['Mengapa berita palsu menyebar lebih cepat?', 'Cenderung lebih mengejutkan', ['Ditulis oleh wartawan', 'Lebih pendek', 'Selalu ada gambarnya']],
      ['Apa masalah dengan koreksi?', 'Jarang menjangkau sebanyak rumor aslinya', ['Selalu salah', 'Terlalu mahal', 'Dilarang disebarkan']],
      ['Kebiasaan apa yang disarankan?', 'Memeriksa sumber dan tanggal', ['Mematikan internet', 'Hanya membaca judul', 'Membagikan secepat mungkin']],
    ],
  },
  {
    id: 'en-b2-ev', level: 'b2', title: 'Motor listrik', native: 'The switch to electric motorbikes',
    sentences: [
      ['With millions of motorbikes on its roads, Indonesia is encouraging riders to switch to electric models.', '', 'Dengan jutaan motor di jalanan, Indonesia mendorong pengendara beralih ke model listrik.'],
      ['The government offers subsidies that reduce the purchase price considerably.', '', 'Pemerintah memberi subsidi yang menurunkan harga beli secara signifikan.'],
      ['Electric bikes are quiet, cheap to run and produce no exhaust fumes in the city.', '', 'Motor listrik senyap, murah dioperasikan, dan tidak mengeluarkan asap di kota.'],
      ['Nevertheless, many riders are hesitant because charging stations are still limited.', '', 'Meski demikian, banyak pengendara ragu karena stasiun pengisian masih terbatas.'],
      ['Battery-swap kiosks, where riders exchange an empty battery for a full one in a minute, are one solution.', '', 'Kios tukar baterai, tempat pengendara menukar baterai kosong dengan yang penuh dalam semenit, adalah salah satu solusi.'],
      ['Another concern is whether the electricity itself comes from clean sources.', '', 'Kekhawatiran lain adalah apakah listriknya sendiri berasal dari sumber bersih.'],
      ['If the grid still relies heavily on coal, the environmental benefit is smaller than it appears.', '', 'Jika jaringan listrik masih sangat bergantung pada batu bara, manfaat lingkungannya lebih kecil dari kelihatannya.'],
    ],
    glossary: [['subsidy', '', 'subsidi'], ['exhaust fumes', '', 'asap knalpot'], ['hesitant', '', 'ragu-ragu'], ['grid', '', 'jaringan listrik']],
    questions: [
      ['Apa yang diberikan pemerintah?', 'Subsidi untuk menurunkan harga beli', ['Bensin gratis', 'Parkir gratis', 'SIM gratis']],
      ['Mengapa banyak pengendara ragu?', 'Stasiun pengisian masih terbatas', ['Motornya terlalu cepat', 'Warnanya sedikit', 'Terlalu berisik']],
      ['Apa kekhawatiran terakhir dalam teks?', 'Listriknya mungkin masih dari batu bara', ['Baterainya meledak', 'Harganya naik lagi', 'Motor listrik dilarang']],
    ],
  },
  {
    id: 'en-b2-interview', level: 'b2', title: 'Tips wawancara kerja', native: 'Preparing for a job interview',
    sentences: [
      ['A job interview is not just a test of your skills; it is also a chance to show your personality.', '', 'Wawancara kerja bukan hanya ujian keterampilan; itu juga kesempatan menunjukkan kepribadianmu.'],
      ['Before the interview, research the company thoroughly, including its values and recent news.', '', 'Sebelum wawancara, pelajari perusahaan secara menyeluruh, termasuk nilai dan berita terbarunya.'],
      ['Prepare examples of situations where you solved a problem or worked well in a team.', '', 'Siapkan contoh situasi saat kamu memecahkan masalah atau bekerja baik dalam tim.'],
      ['Interviewers often ask about weaknesses; be honest, but explain how you are improving.', '', 'Pewawancara sering bertanya tentang kelemahan; jujurlah, tetapi jelaskan bagaimana kamu memperbaikinya.'],
      ['It is also wise to prepare one or two thoughtful questions of your own.', '', 'Bijak juga untuk menyiapkan satu atau dua pertanyaan yang bermakna.'],
      ['On the day, arrive early, dress appropriately and switch off your phone.', '', 'Pada harinya, datang lebih awal, berpakaian pantas, dan matikan ponsel.'],
      ['Finally, send a short thank-you message afterwards; it leaves a positive impression.', '', 'Terakhir, kirim pesan terima kasih singkat sesudahnya; itu meninggalkan kesan positif.'],
    ],
    glossary: [['thoroughly', '', 'secara menyeluruh'], ['weakness', '', 'kelemahan'], ['appropriately', '', 'dengan pantas'], ['impression', '', 'kesan']],
    questions: [
      ['Apa yang perlu diteliti sebelum wawancara?', 'Nilai dan berita terbaru perusahaan', ['Gaji semua karyawan', 'Alamat rumah pewawancara', 'Harga saham pesaing']],
      ['Bagaimana menjawab pertanyaan tentang kelemahan?', 'Jujur dan jelaskan cara memperbaikinya', ['Katakan tidak punya kelemahan', 'Alihkan pembicaraan', 'Salahkan atasan lama']],
      ['Apa yang disarankan setelah wawancara?', 'Mengirim pesan terima kasih singkat', ['Menelepon setiap hari', 'Meminta gaji lebih tinggi', 'Melamar di perusahaan lain']],
    ],
  },
  {
    id: 'en-b2-batik', level: 'b2', title: 'Batik di era modern', native: 'Batik in the modern age',
    sentences: [
      ['Batik, the traditional wax-resist dyeing technique, was recognized by UNESCO in 2009.', '', 'Batik, teknik pewarnaan tradisional dengan malam, diakui UNESCO pada 2009.'],
      ['Since then, it has enjoyed a remarkable revival among young Indonesians.', '', 'Sejak itu, batik mengalami kebangkitan luar biasa di kalangan anak muda Indonesia.'],
      ['Designers are combining classic motifs with modern cuts, making batik suitable for everyday wear.', '', 'Desainer memadukan motif klasik dengan potongan modern sehingga batik cocok dipakai sehari-hari.'],
      ['Many offices now encourage staff to wear batik on Fridays.', '', 'Banyak kantor kini mendorong staf memakai batik setiap Jumat.'],
      ['However, cheap printed fabrics have made life difficult for artisans who draw each pattern by hand.', '', 'Namun, kain cetak murah menyulitkan perajin yang menggambar setiap motif dengan tangan.'],
      ['A single piece of hand-drawn batik can take several weeks to complete.', '', 'Satu lembar batik tulis bisa memakan waktu beberapa minggu untuk diselesaikan.'],
      ['Buyers who understand this process are often willing to pay a fair price for genuine work.', '', 'Pembeli yang memahami proses ini sering bersedia membayar harga layak untuk karya asli.'],
    ],
    glossary: [['revival', '', 'kebangkitan'], ['motif', '', 'motif/pola'], ['artisan', '', 'perajin'], ['genuine', '', 'asli']],
    questions: [
      ['Kapan batik diakui UNESCO?', '2009', ['1999', '2015', '2019']],
      ['Apa ancaman bagi perajin batik tulis?', 'Kain cetak yang murah', ['Kurangnya bahan malam', 'Larangan ekspor', 'Kurangnya motif baru']],
      ['Berapa lama membuat satu batik tulis?', 'Beberapa minggu', ['Satu jam', 'Satu hari', 'Beberapa tahun']],
    ],
  },
  // ---------------------------------------------------------------- C1
  {
    id: 'en-c1-attention', level: 'c1', title: 'Ekonomi perhatian', native: 'The attention economy',
    sentences: [
      ['Many digital platforms are free to use, but they are far from costless.', '', 'Banyak platform digital gratis digunakan, tetapi sama sekali tidak tanpa biaya.'],
      ['Their revenue depends on capturing our attention and selling it to advertisers.', '', 'Pendapatan mereka bergantung pada menangkap perhatian kita dan menjualnya kepada pengiklan.'],
      ['Features such as infinite scrolling and autoplay are deliberately designed to keep us engaged.', '', 'Fitur seperti gulir tanpa akhir dan putar otomatis sengaja dirancang agar kita terus terlibat.'],
      ['Critics contend that this business model exploits psychological vulnerabilities, particularly among teenagers.', '', 'Kritikus berpendapat model bisnis ini mengeksploitasi kerentanan psikologis, terutama pada remaja.'],
      ['Defenders counter that users are free to switch off and that the services provide genuine value.', '', 'Para pembela membantah bahwa pengguna bebas berhenti dan layanan itu memberi nilai nyata.'],
      ['Regulators in several countries are now considering restrictions on design features aimed at minors.', '', 'Regulator di beberapa negara kini mempertimbangkan pembatasan fitur desain yang menyasar anak di bawah umur.'],
      ['Whatever the outcome, it is worth recognizing that when a product is free, our time is often the price.', '', 'Apa pun hasilnya, perlu disadari bahwa ketika produk gratis, waktu kita sering menjadi harganya.'],
    ],
    glossary: [['revenue', '', 'pendapatan'], ['deliberately', '', 'sengaja'], ['contend', '', 'berpendapat'], ['minor', '', 'anak di bawah umur']],
    questions: [
      ['Dari mana pendapatan platform itu berasal?', 'Menjual perhatian pengguna kepada pengiklan', ['Biaya langganan', 'Donasi pengguna', 'Subsidi pemerintah']],
      ['Apa argumen para pembela platform?', 'Pengguna bebas berhenti dan layanannya bernilai', ['Platform tidak menghasilkan uang', 'Remaja tidak memakai platform', 'Iklan tidak efektif']],
      ['Apa inti kalimat penutup?', 'Jika produk gratis, waktu kita sering menjadi harganya', ['Semua platform harus dilarang', 'Iklan harus dihapus', 'Remaja harus bekerja']],
    ],
  },
  {
    id: 'en-c1-memory', level: 'c1', title: 'Ingatan yang tidak bisa dipercaya', native: 'The unreliability of memory',
    sentences: [
      ['We tend to think of memory as a recording that we can replay whenever we wish.', '', 'Kita cenderung menganggap ingatan sebagai rekaman yang bisa diputar ulang kapan saja.'],
      ['In reality, each time we recall an event, we reconstruct it, and details may shift in the process.', '', 'Kenyataannya, setiap kali mengingat suatu peristiwa, kita merekonstruksinya, dan detail bisa bergeser dalam prosesnya.'],
      ['Psychologists have shown that leading questions can implant details that never occurred.', '', 'Psikolog menunjukkan bahwa pertanyaan yang menggiring dapat menanamkan detail yang tidak pernah terjadi.'],
      ['This has profound implications for the justice system, which has long relied on eyewitness testimony.', '', 'Ini berdampak besar bagi sistem peradilan, yang lama mengandalkan kesaksian saksi mata.'],
      ['A number of wrongful convictions have later been overturned on the basis of DNA evidence.', '', 'Sejumlah vonis keliru kemudian dibatalkan berdasarkan bukti DNA.'],
      ['Consequently, police in some countries have revised the way they conduct interviews and identity parades.', '', 'Akibatnya, polisi di beberapa negara merevisi cara melakukan wawancara dan barisan identifikasi.'],
      ['None of this means memory is worthless, merely that confidence is not the same as accuracy.', '', 'Semua ini tidak berarti ingatan tak berharga, hanya saja keyakinan tidak sama dengan ketepatan.'],
    ],
    glossary: [['reconstruct', '', 'merekonstruksi'], ['implant', '', 'menanamkan'], ['testimony', '', 'kesaksian'], ['overturn', '', 'membatalkan (putusan)']],
    questions: [
      ['Apa yang terjadi setiap kali kita mengingat?', 'Kita merekonstruksi peristiwa itu', ['Ingatan diputar persis sama', 'Ingatan terhapus', 'Ingatan menjadi lebih akurat']],
      ['Mengapa temuan ini penting bagi peradilan?', 'Peradilan mengandalkan kesaksian saksi mata', ['Hakim sering lupa', 'Polisi tidak memakai DNA', 'Pengacara terlalu mahal']],
      ['Apa kesimpulan penulis?', 'Keyakinan tidak sama dengan ketepatan', ['Ingatan sama sekali tidak berguna', 'Saksi mata selalu benar', 'DNA tidak bisa dipercaya']],
    ],
  },
  {
    id: 'en-c1-cities', level: 'c1', title: 'Kota lima belas menit', native: 'The fifteen-minute city',
    sentences: [
      ['The “fifteen-minute city” is an urban-planning concept in which daily needs are reachable within a short walk or cycle.', '', '“Kota lima belas menit” adalah konsep tata kota di mana kebutuhan harian terjangkau dengan jalan kaki atau bersepeda singkat.'],
      ['Schools, clinics, shops and parks are distributed across neighbourhoods rather than concentrated in the centre.', '', 'Sekolah, klinik, toko, dan taman tersebar di lingkungan-lingkungan, bukan terpusat di tengah kota.'],
      ['Proponents argue that this reduces congestion, cuts emissions and strengthens local communities.', '', 'Pendukungnya berpendapat ini mengurangi kemacetan, memangkas emisi, dan memperkuat komunitas lokal.'],
      ['The idea gained momentum after the pandemic, when many people began working closer to home.', '', 'Gagasan ini makin populer setelah pandemi, ketika banyak orang mulai bekerja lebih dekat dengan rumah.'],
      ['Nonetheless, it has provoked fierce opposition in some places, where residents fear restrictions on driving.', '', 'Namun, gagasan ini memicu penolakan keras di beberapa tempat, karena warga khawatir akan pembatasan berkendara.'],
      ['Planners stress that the aim is to expand choices, not to confine people to their districts.', '', 'Perencana menegaskan tujuannya memperluas pilihan, bukan mengurung orang di wilayahnya.'],
      ['Applying the model to sprawling, car-dependent cities remains a formidable challenge.', '', 'Menerapkan model ini pada kota yang meluas dan bergantung pada mobil tetap menjadi tantangan berat.'],
    ],
    glossary: [['proponent', '', 'pendukung'], ['congestion', '', 'kemacetan'], ['momentum', '', 'momentum'], ['sprawling', '', 'meluas tak teratur']],
    questions: [
      ['Apa inti konsep kota lima belas menit?', 'Kebutuhan harian terjangkau dengan jalan kaki atau sepeda', ['Semua orang wajib bekerja dari rumah', 'Mobil dilarang total', 'Semua fasilitas di pusat kota']],
      ['Mengapa sebagian warga menolak?', 'Khawatir akan pembatasan berkendara', ['Takut pajak naik', 'Tidak suka taman', 'Sekolah akan ditutup']],
      ['Apa tantangan terbesar menurut teks?', 'Menerapkannya di kota yang bergantung pada mobil', ['Kurangnya pesepeda', 'Kurangnya dana untuk jalan tol', 'Terlalu banyak taman']],
    ],
  },
  {
    id: 'en-c1-translation', level: 'c1', title: 'Seni penerjemahan', native: 'The art of translation',
    sentences: [
      ['Translation is often imagined as a mechanical exchange of words, but skilled translators know otherwise.', '', 'Penerjemahan sering dibayangkan sebagai pertukaran kata mekanis, tetapi penerjemah terampil tahu itu keliru.'],
      ['Every language carves up experience differently, so exact equivalents are surprisingly rare.', '', 'Setiap bahasa memilah pengalaman secara berbeda, sehingga padanan persis ternyata jarang.'],
      ['Humour, wordplay and cultural references pose particular difficulties.', '', 'Humor, permainan kata, dan rujukan budaya menimbulkan kesulitan khusus.'],
      ['A translator must constantly decide whether to stay faithful to the original wording or to its effect on the reader.', '', 'Penerjemah terus-menerus harus memutuskan setia pada susunan kata asli atau pada efeknya bagi pembaca.'],
      ['Machine translation has improved dramatically, and it now handles routine documents with impressive fluency.', '', 'Terjemahan mesin meningkat drastis dan kini menangani dokumen rutin dengan kefasihan mengesankan.'],
      ['Literary texts, however, still benefit from human judgement and sensitivity to tone.', '', 'Namun, teks sastra masih diuntungkan oleh penilaian manusia dan kepekaan terhadap nada.'],
      ['In that sense, a good translation is less a copy than a thoughtful re-creation.', '', 'Dalam hal itu, terjemahan yang baik bukan salinan melainkan penciptaan ulang yang cermat.'],
    ],
    glossary: [['equivalent', '', 'padanan'], ['wordplay', '', 'permainan kata'], ['faithful', '', 'setia'], ['judgement', '', 'penilaian']],
    questions: [
      ['Mengapa padanan persis jarang ditemukan?', 'Setiap bahasa memilah pengalaman secara berbeda', ['Kamus kurang lengkap', 'Penerjemah malas', 'Tata bahasa selalu sama']],
      ['Apa kelebihan terjemahan mesin menurut teks?', 'Menangani dokumen rutin dengan fasih', ['Memahami humor dengan sempurna', 'Menggantikan semua penerjemah', 'Menulis puisi lebih baik']],
      ['Bagaimana penulis menggambarkan terjemahan yang baik?', 'Penciptaan ulang yang cermat', ['Salinan kata demi kata', 'Ringkasan singkat', 'Parafrasa bebas tanpa aturan']],
    ],
  },
  {
    id: 'en-c1-coral', level: 'c1', title: 'Terumbu karang yang terancam', native: 'Coral reefs under threat',
    sentences: [
      ['Coral reefs cover less than one percent of the ocean floor, yet they support about a quarter of all marine species.', '', 'Terumbu karang menutupi kurang dari satu persen dasar laut, namun menopang sekitar seperempat seluruh spesies laut.'],
      ['Indonesia lies at the heart of the Coral Triangle, the most biodiverse marine region on Earth.', '', 'Indonesia terletak di jantung Segitiga Terumbu Karang, kawasan laut paling beragam hayati di Bumi.'],
      ['Rising sea temperatures cause corals to expel the algae that feed them, a process known as bleaching.', '', 'Kenaikan suhu laut membuat karang mengeluarkan alga yang memberinya makan, proses yang disebut pemutihan.'],
      ['If temperatures remain high for too long, the bleached corals die.', '', 'Jika suhu tetap tinggi terlalu lama, karang yang memutih akan mati.'],
      ['Destructive fishing practices and coastal pollution compound the damage.', '', 'Praktik penangkapan ikan yang merusak dan polusi pesisir memperparah kerusakan.'],
      ['Community-managed marine reserves have shown that reefs can recover when local pressures are reduced.', '', 'Kawasan konservasi laut yang dikelola masyarakat menunjukkan terumbu bisa pulih ketika tekanan lokal dikurangi.'],
      ['Ultimately, though, their survival hinges on curbing global emissions.', '', 'Namun pada akhirnya, kelangsungan hidupnya bergantung pada pengendalian emisi global.'],
    ],
    glossary: [['biodiverse', '', 'kaya keanekaragaman hayati'], ['expel', '', 'mengeluarkan'], ['compound', '', 'memperparah'], ['hinge on', '', 'bergantung pada']],
    questions: [
      ['Apa itu pemutihan karang?', 'Karang mengeluarkan alga yang memberinya makan', ['Karang dicat putih', 'Pasir menutupi karang', 'Ikan memakan karang']],
      ['Apa yang terbukti dari kawasan konservasi masyarakat?', 'Terumbu bisa pulih bila tekanan lokal dikurangi', ['Terumbu tidak bisa diselamatkan', 'Nelayan harus pindah', 'Wisata harus dilarang']],
      ['Pada akhirnya, kelangsungan terumbu bergantung pada apa?', 'Pengendalian emisi global', ['Jumlah penyelam', 'Harga ikan', 'Pembangunan pelabuhan']],
    ],
  },
  {
    id: 'en-c1-four-day', level: 'c1', title: 'Empat hari kerja seminggu', native: 'The four-day working week',
    sentences: [
      ['Trials of a four-day working week, with no reduction in pay, have been conducted in several countries.', '', 'Uji coba empat hari kerja seminggu tanpa pengurangan gaji telah dilakukan di beberapa negara.'],
      ['Most participating companies reported that productivity remained stable or even rose.', '', 'Sebagian besar perusahaan peserta melaporkan produktivitas tetap stabil atau bahkan naik.'],
      ['Employees described lower stress levels and fewer sick days.', '', 'Karyawan menggambarkan tingkat stres yang lebih rendah dan lebih sedikit hari sakit.'],
      ['Sceptics point out that the trials were voluntary, so the firms involved may have been unusually suited to the model.', '', 'Kaum skeptis menunjukkan uji coba itu sukarela, jadi perusahaan yang terlibat mungkin sangat cocok dengan model itu.'],
      ['Sectors such as healthcare and retail, which require continuous staffing, face obvious practical obstacles.', '', 'Sektor seperti kesehatan dan ritel, yang membutuhkan staf terus-menerus, menghadapi hambatan praktis yang jelas.'],
      ['Moreover, compressing the same workload into fewer days can intensify pressure rather than relieve it.', '', 'Lagi pula, memadatkan beban kerja yang sama ke hari yang lebih sedikit bisa memperberat tekanan, bukan meringankannya.'],
      ['The evidence so far is encouraging, but it is premature to declare the five-day week obsolete.', '', 'Bukti sejauh ini menggembirakan, tetapi terlalu dini menyatakan lima hari kerja sudah usang.'],
    ],
    glossary: [['trial', '', 'uji coba'], ['sceptic', '', 'orang skeptis'], ['compress', '', 'memadatkan'], ['obsolete', '', 'usang']],
    questions: [
      ['Apa hasil umum uji coba itu?', 'Produktivitas stabil atau naik', ['Produktivitas turun tajam', 'Gaji dipotong', 'Banyak perusahaan bangkrut']],
      ['Apa keberatan kaum skeptis?', 'Perusahaan peserta bersifat sukarela dan mungkin sangat cocok', ['Karyawan tidak mau libur', 'Datanya dipalsukan', 'Pemerintah melarangnya']],
      ['Apa sikap akhir penulis?', 'Menggembirakan tetapi terlalu dini untuk menyimpulkan', ['Harus segera diwajibkan', 'Sepenuhnya gagal', 'Hanya cocok untuk rumah sakit']],
    ],
  },
  {
    id: 'en-c1-multilingual', level: 'c1', title: 'Otak multibahasa', native: 'The multilingual brain',
    sentences: [
      ['For much of the twentieth century, raising children with two languages was thought to confuse them.', '', 'Sepanjang sebagian besar abad ke-20, membesarkan anak dengan dua bahasa dianggap membingungkan mereka.'],
      ['Research has since overturned this assumption.', '', 'Penelitian sejak itu membalikkan anggapan tersebut.'],
      ['Bilingual children may initially have smaller vocabularies in each language, but their combined knowledge is comparable.', '', 'Anak dwibahasa mungkin awalnya punya kosakata lebih sedikit di tiap bahasa, tetapi gabungan pengetahuannya sebanding.'],
      ['Some studies suggest that switching between languages strengthens the ability to focus and ignore distractions.', '', 'Beberapa studi menunjukkan berpindah antarbahasa memperkuat kemampuan fokus dan mengabaikan gangguan.'],
      ['These cognitive advantages are debated, as not all experiments have replicated them.', '', 'Keunggulan kognitif ini diperdebatkan karena tidak semua eksperimen berhasil mereplikasinya.'],
      ['What is less contested are the social and economic benefits of speaking several languages.', '', 'Yang kurang diperdebatkan adalah manfaat sosial dan ekonomi dari menguasai beberapa bahasa.'],
      ['In a country as linguistically diverse as Indonesia, multilingualism is less an exception than the norm.', '', 'Di negara seberagam Indonesia secara bahasa, multibahasa bukan pengecualian melainkan kebiasaan.'],
    ],
    glossary: [['assumption', '', 'anggapan'], ['comparable', '', 'sebanding'], ['replicate', '', 'mereplikasi'], ['contested', '', 'diperdebatkan']],
    questions: [
      ['Apa anggapan lama tentang anak dwibahasa?', 'Dua bahasa membingungkan mereka', ['Mereka lebih pintar', 'Mereka tidak bisa membaca', 'Mereka lebih cepat berjalan']],
      ['Mengapa keunggulan kognitif masih diperdebatkan?', 'Tidak semua eksperimen berhasil mereplikasinya', ['Belum ada yang meneliti', 'Hanya diuji pada orang dewasa', 'Dilarang diteliti']],
      ['Apa yang dikatakan tentang Indonesia?', 'Multibahasa adalah kebiasaan', ['Hanya ada satu bahasa', 'Multibahasa sangat langka', 'Bahasa daerah sudah punah']],
    ],
  },
  {
    id: 'en-c1-museum', level: 'c1', title: 'Mengembalikan artefak', native: 'Should museums return artefacts?',
    sentences: [
      ['Many of the world’s great museums hold objects that were acquired during the colonial era.', '', 'Banyak museum besar dunia menyimpan benda yang diperoleh pada masa kolonial.'],
      ['Some were purchased legitimately, but others were taken by force or under unequal conditions.', '', 'Sebagian dibeli secara sah, tetapi yang lain diambil secara paksa atau dalam kondisi tidak setara.'],
      ['In recent years, the Netherlands has returned hundreds of artefacts to Indonesia, including treasures from Lombok.', '', 'Dalam beberapa tahun terakhir, Belanda mengembalikan ratusan artefak ke Indonesia, termasuk harta dari Lombok.'],
      ['Supporters of repatriation argue that these objects belong to the cultures that created them.', '', 'Pendukung repatriasi berpendapat benda-benda ini milik budaya yang menciptakannya.'],
      ['Opponents worry about conservation standards and claim that global museums make heritage accessible to a wider audience.', '', 'Penentang khawatir soal standar konservasi dan mengklaim museum global membuat warisan lebih mudah diakses khalayak luas.'],
      ['Increasingly, institutions are seeking compromises such as long-term loans and joint research.', '', 'Semakin banyak lembaga mencari kompromi seperti pinjaman jangka panjang dan riset bersama.'],
      ['The debate ultimately raises a deeper question: who has the right to tell a nation’s history?', '', 'Perdebatan ini akhirnya memunculkan pertanyaan lebih dalam: siapa yang berhak menceritakan sejarah suatu bangsa?'],
    ],
    glossary: [['acquire', '', 'memperoleh'], ['legitimately', '', 'secara sah'], ['repatriation', '', 'pemulangan'], ['heritage', '', 'warisan budaya']],
    questions: [
      ['Negara mana yang disebut mengembalikan artefak ke Indonesia?', 'Belanda', ['Inggris', 'Prancis', 'Jepang']],
      ['Apa argumen penentang repatriasi?', 'Standar konservasi dan akses khalayak luas', ['Artefak tidak bernilai', 'Biaya pengiriman mahal', 'Indonesia tidak memintanya']],
      ['Kompromi apa yang disebutkan?', 'Pinjaman jangka panjang dan riset bersama', ['Menjual artefak', 'Membuat replika saja', 'Menyimpan di gudang']],
    ],
  },
  // ---------------------------------------------------------------- C2
  {
    id: 'en-c2-progress', level: 'c2', title: 'Mitos kemajuan', native: 'The myth of inevitable progress',
    sentences: [
      ['It is tempting to view history as a steady ascent from ignorance to enlightenment.', '', 'Menggoda untuk memandang sejarah sebagai pendakian mantap dari kebodohan menuju pencerahan.'],
      ['Such a narrative flatters the present and implies that our own values are the culmination of human development.', '', 'Narasi semacam itu menyanjung masa kini dan menyiratkan nilai-nilai kita adalah puncak perkembangan manusia.'],
      ['Yet the historical record is punctuated by reversals, in which hard-won knowledge was lost for centuries.', '', 'Namun catatan sejarah diselingi kemunduran, ketika pengetahuan yang diperoleh susah payah hilang berabad-abad.'],
      ['Technological sophistication, moreover, has not invariably been matched by moral progress.', '', 'Lagi pula, kecanggihan teknologi tidak selalu diimbangi kemajuan moral.'],
      ['This is not to embrace a fashionable pessimism; measurable gains in health and literacy are undeniable.', '', 'Ini bukan berarti merangkul pesimisme yang sedang tren; kemajuan terukur dalam kesehatan dan literasi tak terbantahkan.'],
      ['Rather, it is to insist that progress is contingent: it must be defended, not presumed.', '', 'Sebaliknya, ini menegaskan bahwa kemajuan bersifat kontingen: harus dipertahankan, bukan diandaikan.'],
      ['Complacency, in this light, may be the most insidious threat to the achievements we take for granted.', '', 'Dalam terang ini, rasa puas diri mungkin ancaman paling licik bagi pencapaian yang kita anggap biasa.'],
    ],
    glossary: [['ascent', '', 'pendakian'], ['culmination', '', 'puncak'], ['contingent', '', 'bergantung pada keadaan'], ['complacency', '', 'rasa puas diri']],
    questions: [
      ['Apa yang dikritik penulis?', 'Pandangan bahwa sejarah selalu maju dengan mantap', ['Kemajuan dalam kesehatan', 'Pendidikan modern', 'Penelitian sejarah']],
      ['Apakah penulis bersikap pesimis?', 'Tidak, ia mengakui kemajuan terukur', ['Ya, sepenuhnya pesimis', 'Ia menolak semua kemajuan', 'Ia tidak berpendapat']],
      ['Apa ancaman terbesar menurut penulis?', 'Rasa puas diri', ['Teknologi', 'Literasi', 'Ilmu kedokteran']],
    ],
  },
  {
    id: 'en-c2-silence', level: 'c2', title: 'Nilai keheningan', native: 'In praise of silence',
    sentences: [
      ['Modern life has made silence something of a luxury, rationed between notifications and background noise.', '', 'Kehidupan modern menjadikan keheningan semacam kemewahan, dijatah di sela notifikasi dan kebisingan latar.'],
      ['We fill every pause, as though an unoccupied moment were a problem to be solved.', '', 'Kita mengisi setiap jeda, seolah momen kosong adalah masalah yang harus dipecahkan.'],
      ['Yet many contemplative traditions regard silence not as absence but as a form of attention.', '', 'Namun banyak tradisi kontemplatif memandang keheningan bukan sebagai ketiadaan, melainkan bentuk perhatian.'],
      ['Neuroscientists have found that periods of quiet may foster the kind of unfocused thinking from which insight often emerges.', '', 'Ahli saraf menemukan bahwa masa tenang dapat menumbuhkan pemikiran tak terfokus yang sering melahirkan wawasan.'],
      ['In conversation, too, a well-placed silence can convey more than a torrent of words.', '', 'Dalam percakapan pun, keheningan yang tepat bisa menyampaikan lebih banyak daripada semburan kata.'],
      ['To reclaim silence need not entail retreating to a monastery; it may simply mean resisting the reflex to reach for a screen.', '', 'Merebut kembali keheningan tidak harus berarti mundur ke biara; mungkin cukup dengan menahan refleks meraih layar.'],
      ['Paradoxically, it is in saying and hearing nothing that we sometimes understand the most.', '', 'Secara paradoks, justru ketika tidak berkata dan tidak mendengar apa pun, kita kadang paling memahami.'],
    ],
    glossary: [['ration', '', 'menjatah'], ['contemplative', '', 'kontemplatif'], ['torrent', '', 'semburan deras'], ['reclaim', '', 'merebut kembali']],
    questions: [
      ['Bagaimana tradisi kontemplatif memandang keheningan?', 'Sebagai bentuk perhatian', ['Sebagai hukuman', 'Sebagai tanda kesepian', 'Sebagai kemalasan']],
      ['Apa temuan ahli saraf yang disebut?', 'Masa tenang dapat menumbuhkan wawasan', ['Keheningan merusak otak', 'Musik meningkatkan IQ', 'Notifikasi meningkatkan fokus']],
      ['Menurut penulis, bagaimana merebut kembali keheningan?', 'Menahan refleks meraih layar', ['Tinggal di biara', 'Berhenti bekerja', 'Pindah ke desa']],
    ],
  },
  {
    id: 'en-c2-meritocracy', level: 'c2', title: 'Batas meritokrasi', native: 'The limits of meritocracy',
    sentences: [
      ['Meritocracy, the principle that rewards should follow talent and effort, commands near-universal assent.', '', 'Meritokrasi, prinsip bahwa imbalan harus mengikuti bakat dan usaha, diterima hampir secara universal.'],
      ['Few would openly defend a system in which positions are inherited rather than earned.', '', 'Hanya sedikit yang terang-terangan membela sistem di mana posisi diwariskan, bukan diraih.'],
      ['Critics nevertheless contend that meritocracy, as practised, often launders privilege.', '', 'Namun para kritikus berpendapat meritokrasi, dalam praktiknya, sering “mencuci” hak istimewa.'],
      ['Affluent families can purchase tutoring, networks and second chances that are invisible on a CV.', '', 'Keluarga kaya bisa membeli les, jaringan, dan kesempatan kedua yang tak terlihat di CV.'],
      ['Moreover, those who succeed may come to believe their position is wholly deserved, breeding disdain for those who do not.', '', 'Lagi pula, yang berhasil bisa meyakini posisinya sepenuhnya pantas, menumbuhkan sikap meremehkan mereka yang tidak berhasil.'],
      ['The remedy is not to abandon merit but to acknowledge the role of luck and to widen genuine opportunity.', '', 'Solusinya bukan meninggalkan prestasi, melainkan mengakui peran keberuntungan dan memperluas kesempatan yang nyata.'],
      ['A society that honours merit without humility risks becoming as rigid as the aristocracies it replaced.', '', 'Masyarakat yang menghormati prestasi tanpa kerendahan hati berisiko menjadi sekaku aristokrasi yang digantikannya.'],
    ],
    glossary: [['assent', '', 'persetujuan'], ['launder', '', 'mencuci (menyamarkan)'], ['affluent', '', 'makmur/kaya'], ['disdain', '', 'sikap meremehkan']],
    questions: [
      ['Apa kritik utama terhadap meritokrasi dalam praktik?', 'Sering menyamarkan hak istimewa', ['Terlalu adil', 'Menghapus pendidikan', 'Tidak menghargai usaha']],
      ['Apa solusi yang ditawarkan penulis?', 'Mengakui peran keberuntungan dan memperluas kesempatan', ['Menghapus prestasi', 'Kembali ke sistem warisan', 'Menutup sekolah swasta']],
      ['Apa risiko meritokrasi tanpa kerendahan hati?', 'Menjadi sekaku aristokrasi', ['Menjadi terlalu santai', 'Ekonomi berhenti tumbuh', 'Semua orang menjadi sama']],
    ],
  },
  {
    id: 'en-c2-nostalgia', level: 'c2', title: 'Politik nostalgia', native: 'The politics of nostalgia',
    sentences: [
      ['Nostalgia, once classified as a medical disorder, is now recognised as a nearly universal emotion.', '', 'Nostalgia, yang dulu digolongkan sebagai gangguan medis, kini diakui sebagai emosi yang hampir universal.'],
      ['In moderation it can bolster a sense of identity and continuity amid rapid change.', '', 'Dalam kadar wajar, nostalgia dapat memperkuat rasa identitas dan kesinambungan di tengah perubahan cepat.'],
      ['Politicians, however, have learned to harness it, invoking an idealised past that never quite existed.', '', 'Namun para politisi belajar memanfaatkannya, membangkitkan masa lalu ideal yang tidak pernah benar-benar ada.'],
      ['Such appeals are potent precisely because they are vague; each listener supplies their own golden age.', '', 'Seruan semacam itu ampuh justru karena samar; tiap pendengar mengisi zaman keemasannya sendiri.'],
      ['The danger lies in mistaking selective memory for a policy programme.', '', 'Bahayanya terletak pada salah mengira ingatan selektif sebagai program kebijakan.'],
      ['Historians can serve as a corrective, reminding us of the hardships and exclusions that the rosy version omits.', '', 'Sejarawan dapat menjadi penyeimbang, mengingatkan kita pada kesulitan dan pengucilan yang dihilangkan versi indahnya.'],
      ['To remember well is not to reject the past, but to see it whole.', '', 'Mengingat dengan baik bukan menolak masa lalu, melainkan melihatnya secara utuh.'],
    ],
    glossary: [['bolster', '', 'memperkuat'], ['harness', '', 'memanfaatkan'], ['potent', '', 'ampuh'], ['corrective', '', 'penyeimbang/koreksi']],
    questions: [
      ['Mengapa seruan nostalgia politik ampuh?', 'Karena samar sehingga tiap orang membayangkan versinya', ['Karena selalu akurat', 'Karena didukung data', 'Karena hanya untuk anak muda']],
      ['Apa peran sejarawan menurut teks?', 'Menjadi penyeimbang dengan menunjukkan sisi yang dihilangkan', ['Menulis pidato politik', 'Menghapus masa lalu', 'Memuji zaman keemasan']],
      ['Apa arti “mengingat dengan baik”?', 'Melihat masa lalu secara utuh', ['Melupakan masa lalu', 'Hanya mengingat yang indah', 'Menolak sejarah']],
    ],
  },
  {
    id: 'en-c2-expertise', level: 'c2', title: 'Krisis kepercayaan pada pakar', native: 'The crisis of expertise',
    sentences: [
      ['Never has specialised knowledge been more accessible, yet trust in experts appears to be eroding.', '', 'Belum pernah pengetahuan khusus semudah ini diakses, namun kepercayaan pada pakar tampak terkikis.'],
      ['Part of the explanation lies in high-profile failures, from financial crises to faulty forecasts.', '', 'Sebagian penjelasannya ada pada kegagalan besar, dari krisis keuangan hingga prakiraan yang keliru.'],
      ['Another factor is the conflation of expertise with elitism, which casts specialists as a remote and self-serving caste.', '', 'Faktor lain adalah pencampuradukan keahlian dengan elitisme, yang menggambarkan para spesialis sebagai kasta yang jauh dan mementingkan diri.'],
      ['The internet compounds this by granting every opinion the same typographical authority.', '', 'Internet memperparah hal ini dengan memberi setiap opini otoritas tampilan yang sama.'],
      ['Restoring trust will require experts to be candid about uncertainty rather than projecting infallibility.', '', 'Memulihkan kepercayaan menuntut pakar jujur tentang ketidakpastian alih-alih menampilkan diri tak pernah salah.'],
      ['It will also require citizens to distinguish between healthy scepticism and reflexive dismissal.', '', 'Ini juga menuntut warga membedakan skeptisisme sehat dari penolakan refleks.'],
      ['Democracy depends not on deference to authority but on informed judgement, which in turn depends on reliable knowledge.', '', 'Demokrasi bergantung bukan pada kepatuhan kepada otoritas, melainkan pada penilaian yang terinformasi, yang pada gilirannya bergantung pada pengetahuan yang andal.'],
    ],
    glossary: [['erode', '', 'terkikis'], ['conflation', '', 'pencampuradukan'], ['candid', '', 'terus terang'], ['infallibility', '', 'ketidakmungkinan salah']],
    questions: [
      ['Apa salah satu penyebab menurunnya kepercayaan pada pakar?', 'Kegagalan besar seperti krisis keuangan', ['Pakar terlalu sedikit', 'Buku terlalu mahal', 'Universitas ditutup']],
      ['Apa yang dituntut dari para pakar?', 'Jujur tentang ketidakpastian', ['Tidak pernah berbicara di publik', 'Selalu tampak yakin', 'Menghindari internet']],
      ['Menurut penulis, demokrasi bergantung pada apa?', 'Penilaian yang terinformasi', ['Kepatuhan pada otoritas', 'Jumlah pakar', 'Media sosial']],
    ],
  },
  {
    id: 'en-c2-rivers', level: 'c2', title: 'Hak hukum sungai', native: 'Should rivers have rights?',
    sentences: [
      ['In a handful of jurisdictions, rivers have been granted legal personhood.', '', 'Di segelintir yurisdiksi, sungai telah diberi status badan hukum.'],
      ['The idea, which strikes some as whimsical, draws on indigenous worldviews in which nature is kin rather than property.', '', 'Gagasan ini, yang bagi sebagian orang terkesan aneh, berakar pada pandangan dunia masyarakat adat yang menganggap alam sebagai kerabat, bukan milik.'],
      ['Legally, it allows guardians to sue on the river’s behalf when it is polluted or diverted.', '', 'Secara hukum, ini memungkinkan wali menggugat atas nama sungai ketika tercemar atau dialihkan.'],
      ['Sceptics question how the interests of a river can be ascertained, let alone represented.', '', 'Kaum skeptis mempertanyakan bagaimana kepentingan sungai dapat dipastikan, apalagi diwakili.'],
      ['Others fear that symbolic rights may substitute for the unglamorous work of enforcement.', '', 'Yang lain khawatir hak simbolis bisa menggantikan kerja penegakan hukum yang tidak glamor.'],
      ['Proponents reply that the law already treats corporations as persons, so the conceptual leap is smaller than it seems.', '', 'Pendukung menjawab bahwa hukum sudah memperlakukan korporasi sebagai pribadi, jadi lompatan konseptualnya lebih kecil dari kelihatannya.'],
      ['Whatever its merits, the movement forces a reconsideration of whom, or what, the law exists to protect.', '', 'Apa pun kelebihannya, gerakan ini memaksa kita mempertimbangkan ulang siapa, atau apa, yang dilindungi hukum.'],
    ],
    glossary: [['personhood', '', 'status sebagai pribadi hukum'], ['whimsical', '', 'aneh/tak lazim'], ['ascertain', '', 'memastikan'], ['enforcement', '', 'penegakan']],
    questions: [
      ['Dari mana gagasan hak hukum sungai berasal?', 'Pandangan dunia masyarakat adat', ['Undang-undang dagang', 'Ilmu teknik sipil', 'Partai politik']],
      ['Apa kekhawatiran kaum skeptis?', 'Sulit memastikan dan mewakili kepentingan sungai', ['Sungai akan kering', 'Biaya pengacara murah', 'Korporasi akan bangkrut']],
      ['Apa argumen para pendukung?', 'Korporasi pun sudah diperlakukan sebagai pribadi', ['Sungai bisa berbicara', 'Hukum tidak penting', 'Semua sungai sudah bersih']],
    ],
  },
  {
    id: 'en-c2-irony', level: 'c2', title: 'Ironi di era internet', native: 'Irony in the age of the internet',
    sentences: [
      ['Irony has become the lingua franca of online culture.', '', 'Ironi telah menjadi bahasa pengantar budaya daring.'],
      ['Its appeal is understandable: a knowing wink protects the speaker from appearing naive or overly earnest.', '', 'Daya tariknya bisa dipahami: kedipan penuh arti melindungi pembicara agar tidak tampak naif atau terlalu serius.'],
      ['Yet pervasive irony carries a cost, for when everything is said in jest, nothing need be defended.', '', 'Namun ironi yang merata ada harganya, sebab ketika semua diucapkan sebagai lelucon, tak ada yang perlu dipertahankan.'],
      ['Extremist views, cloaked in humour, can thereby circulate while evading scrutiny.', '', 'Pandangan ekstrem yang dibungkus humor pun dapat beredar sambil menghindari pengawasan.'],
      ['Some writers have called for a “new sincerity” that risks vulnerability in place of detachment.', '', 'Sebagian penulis menyerukan “ketulusan baru” yang berani rentan alih-alih bersikap berjarak.'],
      ['This is not a plea for humourlessness; satire remains one of the sharpest tools of dissent.', '', 'Ini bukan seruan untuk tanpa humor; satire tetap salah satu alat perlawanan paling tajam.'],
      ['The distinction lies in whether irony illuminates a truth or merely excuses us from having to hold one.', '', 'Perbedaannya terletak pada apakah ironi menerangi kebenaran atau sekadar membebaskan kita dari keharusan memegangnya.'],
    ],
    glossary: [['lingua franca', '', 'bahasa pengantar bersama'], ['earnest', '', 'sungguh-sungguh'], ['pervasive', '', 'merata/meresap'], ['dissent', '', 'perbedaan pendapat/perlawanan']],
    questions: [
      ['Mengapa ironi menarik bagi pengguna daring?', 'Melindungi dari kesan naif atau terlalu serius', ['Lebih mudah diterjemahkan', 'Diwajibkan platform', 'Selalu lebih sopan']],
      ['Apa bahaya ironi yang merata?', 'Pandangan ekstrem bisa beredar tanpa pengawasan', ['Orang berhenti tertawa', 'Internet menjadi lambat', 'Satire menjadi ilegal']],
      ['Apakah penulis menolak humor?', 'Tidak, satire tetap alat perlawanan yang tajam', ['Ya, semua humor harus dihapus', 'Ya, humor berbahaya', 'Penulis tidak menyinggung humor']],
    ],
  },
  {
    id: 'en-c2-archive', level: 'c2', title: 'Arsip digital yang rapuh', native: 'The fragile digital archive',
    sentences: [
      ['We generate more records than any civilisation in history, yet much of it may prove more ephemeral than clay tablets.', '', 'Kita menghasilkan lebih banyak catatan daripada peradaban mana pun, namun sebagian besar mungkin terbukti lebih fana daripada lempeng tanah liat.'],
      ['File formats become obsolete, storage media degrade, and websites vanish without trace.', '', 'Format berkas menjadi usang, media penyimpanan rusak, dan situs web lenyap tanpa jejak.'],
      ['Archivists warn of a potential “digital dark age”, in which future historians find our era curiously silent.', '', 'Para arsiparis memperingatkan kemungkinan “zaman kegelapan digital”, ketika sejarawan masa depan mendapati era kita anehnya sunyi.'],
      ['Preservation is not merely a technical matter; it entails decisions about what is worth keeping.', '', 'Pelestarian bukan sekadar urusan teknis; ia melibatkan keputusan tentang apa yang layak disimpan.'],
      ['Those decisions inevitably reflect the priorities, and the blind spots, of the institutions making them.', '', 'Keputusan itu pasti mencerminkan prioritas, dan titik buta, lembaga yang membuatnya.'],
      ['Community archives have emerged partly to rescue voices that official collections overlooked.', '', 'Arsip komunitas muncul sebagian untuk menyelamatkan suara-suara yang terlewat oleh koleksi resmi.'],
      ['The paradox is stark: an age of unprecedented documentation could leave remarkably little behind.', '', 'Paradoksnya nyata: zaman dokumentasi yang belum pernah terjadi bisa meninggalkan sangat sedikit jejak.'],
    ],
    glossary: [['ephemeral', '', 'fana/sementara'], ['degrade', '', 'menurun kualitasnya'], ['preservation', '', 'pelestarian'], ['unprecedented', '', 'belum pernah terjadi']],
    questions: [
      ['Apa yang dimaksud “zaman kegelapan digital”?', 'Era kita mungkin tampak sunyi bagi sejarawan masa depan', ['Internet akan dimatikan', 'Listrik akan padam', 'Komputer akan dilarang']],
      ['Mengapa pelestarian bukan hanya urusan teknis?', 'Melibatkan keputusan tentang apa yang layak disimpan', ['Karena terlalu mahal', 'Karena dilarang hukum', 'Karena tidak ada teknologinya']],
      ['Mengapa arsip komunitas muncul?', 'Menyelamatkan suara yang terlewat koleksi resmi', ['Menggantikan semua museum', 'Menjual data', 'Menghapus catatan lama']],
    ],
  },
];
