import type { PassageSource } from './types';

// Graded English reading/listening passages for CEFR A1-B1.
export const englishPassagesLower: PassageSource[] = [
  // ---------------------------------------------------------------- A1
  {
    id: 'en-a1-family', level: 'a1', title: 'Keluarga saya', native: 'My family',
    sentences: [
      ['My name is Rina and I am twelve years old.', '', 'Nama saya Rina dan saya berumur dua belas tahun.'],
      ['I live in a small house in Yogyakarta.', '', 'Saya tinggal di rumah kecil di Yogyakarta.'],
      ['My father is a driver and my mother is a cook.', '', 'Ayah saya sopir dan ibu saya juru masak.'],
      ['I have one brother. His name is Budi.', '', 'Saya punya satu saudara laki-laki. Namanya Budi.'],
      ['Budi is eight. He likes cars and football.', '', 'Budi berumur delapan. Dia suka mobil dan sepak bola.'],
      ['We also have a white cat called Snow.', '', 'Kami juga punya kucing putih bernama Snow.'],
      ['I love my family very much.', '', 'Saya sangat menyayangi keluarga saya.'],
    ],
    glossary: [['live', '', 'tinggal'], ['driver', '', 'sopir'], ['cook', '', 'juru masak'], ['called', '', 'bernama']],
    questions: [
      ['Berapa umur Rina?', 'Dua belas tahun', ['Delapan tahun', 'Sepuluh tahun', 'Lima belas tahun']],
      ['Apa pekerjaan ibu Rina?', 'Juru masak', ['Sopir', 'Guru', 'Perawat']],
      ['Apa yang disukai Budi?', 'Mobil dan sepak bola', ['Kucing dan buku', 'Musik dan menggambar', 'Berenang dan lari']],
    ],
  },
  {
    id: 'en-a1-day', level: 'a1', title: 'Hari Senin saya', native: 'My Monday',
    sentences: [
      ['I get up at half past five on Monday.', '', 'Saya bangun jam setengah enam pada hari Senin.'],
      ['I take a shower and eat bread for breakfast.', '', 'Saya mandi dan makan roti untuk sarapan.'],
      ['At seven o’clock I go to school by bike.', '', 'Jam tujuh saya pergi ke sekolah naik sepeda.'],
      ['My first lesson is English. I like it a lot.', '', 'Pelajaran pertama saya bahasa Inggris. Saya sangat menyukainya.'],
      ['I have lunch with my friends at twelve.', '', 'Saya makan siang bersama teman-teman jam dua belas.'],
      ['In the afternoon I do my homework.', '', 'Pada sore hari saya mengerjakan PR.'],
      ['I go to bed at nine o’clock.', '', 'Saya tidur jam sembilan.'],
    ],
    glossary: [['get up', '', 'bangun'], ['take a shower', '', 'mandi'], ['lesson', '', 'pelajaran'], ['homework', '', 'PR']],
    questions: [
      ['Jam berapa penulis bangun?', 'Jam setengah enam', ['Jam enam', 'Jam tujuh', 'Jam lima']],
      ['Bagaimana penulis pergi ke sekolah?', 'Naik sepeda', ['Naik bus', 'Berjalan kaki', 'Naik mobil']],
      ['Apa pelajaran pertama penulis?', 'Bahasa Inggris', ['Matematika', 'Olahraga', 'Musik']],
    ],
  },
  {
    id: 'en-a1-market', level: 'a1', title: 'Di pasar', native: 'At the market',
    sentences: [
      ['On Saturday I go to the market with my mother.', '', 'Pada hari Sabtu saya pergi ke pasar bersama ibu.'],
      ['The market is big and very busy.', '', 'Pasarnya besar dan sangat ramai.'],
      ['We buy rice, eggs, tomatoes and fish.', '', 'Kami membeli beras, telur, tomat, dan ikan.'],
      ['The fish is fresh but a little expensive.', '', 'Ikannya segar tetapi agak mahal.'],
      ['My mother asks, "How much are the bananas?"', '', 'Ibu bertanya, "Berapa harga pisangnya?"'],
      ['The man says, "Ten thousand rupiah."', '', 'Bapak itu berkata, "Sepuluh ribu rupiah."'],
      ['We go home by taxi because the bags are heavy.', '', 'Kami pulang naik taksi karena tasnya berat.'],
    ],
    glossary: [['busy', '', 'ramai'], ['fresh', '', 'segar'], ['expensive', '', 'mahal'], ['heavy', '', 'berat']],
    questions: [
      ['Kapan penulis pergi ke pasar?', 'Hari Sabtu', ['Hari Minggu', 'Hari Senin', 'Hari Jumat']],
      ['Bagaimana ikannya?', 'Segar tetapi agak mahal', ['Murah dan segar', 'Tidak segar', 'Sangat murah']],
      ['Mengapa mereka pulang naik taksi?', 'Karena tasnya berat', ['Karena hujan', 'Karena jauh', 'Karena sudah malam']],
    ],
  },
  {
    id: 'en-a1-room', level: 'a1', title: 'Kamar saya', native: 'My room',
    sentences: [
      ['This is my room. It is small but nice.', '', 'Ini kamar saya. Kecil tapi bagus.'],
      ['There is a bed next to the window.', '', 'Ada tempat tidur di sebelah jendela.'],
      ['There is a desk and a chair in the corner.', '', 'Ada meja belajar dan kursi di sudut.'],
      ['My books are on the desk.', '', 'Buku-buku saya ada di atas meja.'],
      ['The walls are blue. Blue is my favorite color.', '', 'Dindingnya biru. Biru warna favorit saya.'],
      ['There is a picture of my family on the wall.', '', 'Ada foto keluarga saya di dinding.'],
      ['I read and study in my room every evening.', '', 'Saya membaca dan belajar di kamar setiap malam.'],
    ],
    glossary: [['next to', '', 'di sebelah'], ['corner', '', 'sudut'], ['wall', '', 'dinding'], ['picture', '', 'gambar/foto']],
    questions: [
      ['Di mana tempat tidurnya?', 'Di sebelah jendela', ['Di sudut', 'Di dekat pintu', 'Di bawah meja']],
      ['Apa warna dinding kamar?', 'Biru', ['Putih', 'Hijau', 'Kuning']],
      ['Apa yang ada di dinding?', 'Foto keluarga', ['Jam', 'Peta', 'Cermin']],
    ],
  },
  {
    id: 'en-a1-weekend', level: 'a1', title: 'Akhir pekan di pantai', native: 'A weekend at the beach',
    sentences: [
      ['Last Sunday we went to the beach.', '', 'Minggu lalu kami pergi ke pantai.'],
      ['The weather was hot and sunny.', '', 'Cuacanya panas dan cerah.'],
      ['My sister and I swam in the sea.', '', 'Saya dan kakak berenang di laut.'],
      ['My father sat under a tree and read a book.', '', 'Ayah duduk di bawah pohon dan membaca buku.'],
      ['We ate fried fish and drank coconut water.', '', 'Kami makan ikan goreng dan minum air kelapa.'],
      ['In the evening we watched the sunset.', '', 'Sore harinya kami menonton matahari terbenam.'],
      ['It was a happy day.', '', 'Itu hari yang menyenangkan.'],
    ],
    glossary: [['went', '', 'pergi (lampau)'], ['swam', '', 'berenang (lampau)'], ['sunset', '', 'matahari terbenam'], ['coconut', '', 'kelapa']],
    questions: [
      ['Bagaimana cuacanya?', 'Panas dan cerah', ['Hujan', 'Dingin dan berangin', 'Berawan']],
      ['Apa yang dilakukan ayah?', 'Membaca buku di bawah pohon', ['Berenang', 'Memancing', 'Tidur di mobil']],
      ['Apa yang mereka minum?', 'Air kelapa', ['Teh manis', 'Kopi', 'Jus jeruk']],
    ],
  },
  {
    id: 'en-a1-friend', level: 'a1', title: 'Sahabat saya', native: 'My best friend',
    sentences: [
      ['My best friend is Ayu.', '', 'Sahabat saya adalah Ayu.'],
      ['She is tall and she has long black hair.', '', 'Dia tinggi dan rambutnya panjang hitam.'],
      ['She is very kind and funny.', '', 'Dia sangat baik dan lucu.'],
      ['We are in the same class at school.', '', 'Kami satu kelas di sekolah.'],
      ['Ayu can sing very well, but she cannot swim.', '', 'Ayu bisa bernyanyi dengan sangat baik, tetapi tidak bisa berenang.'],
      ['After school we often play badminton.', '', 'Sepulang sekolah kami sering bermain bulu tangkis.'],
      ['On her birthday I gave her a book.', '', 'Pada hari ulang tahunnya saya memberinya buku.'],
    ],
    glossary: [['best friend', '', 'sahabat'], ['kind', '', 'baik hati'], ['funny', '', 'lucu'], ['often', '', 'sering']],
    questions: [
      ['Seperti apa rambut Ayu?', 'Panjang dan hitam', ['Pendek dan hitam', 'Panjang dan cokelat', 'Keriting']],
      ['Apa yang tidak bisa dilakukan Ayu?', 'Berenang', ['Bernyanyi', 'Bermain bulu tangkis', 'Membaca']],
      ['Apa hadiah ulang tahun untuk Ayu?', 'Buku', ['Tas', 'Boneka', 'Bunga']],
    ],
  },
  {
    id: 'en-a1-cafe', level: 'a1', title: 'Di kafe', native: 'At the cafe',
    sentences: [
      ['Waiter: Good morning. What would you like?', '', 'Pelayan: Selamat pagi. Mau pesan apa?'],
      ['Customer: A cup of coffee and a cheese sandwich, please.', '', 'Pelanggan: Secangkir kopi dan roti lapis keju.'],
      ['Waiter: Hot or iced coffee?', '', 'Pelayan: Kopi panas atau es?'],
      ['Customer: Iced coffee, please. It is very hot today.', '', 'Pelanggan: Kopi es. Hari ini sangat panas.'],
      ['Waiter: Anything else?', '', 'Pelayan: Ada lagi?'],
      ['Customer: No, thank you. How much is it?', '', 'Pelanggan: Tidak, terima kasih. Berapa semuanya?'],
      ['Waiter: That is forty-five thousand rupiah.', '', 'Pelayan: Empat puluh lima ribu rupiah.'],
    ],
    glossary: [['waiter', '', 'pelayan'], ['customer', '', 'pelanggan'], ['iced', '', 'pakai es'], ['anything else', '', 'ada lagi']],
    questions: [
      ['Apa makanan yang dipesan pelanggan?', 'Roti lapis keju', ['Nasi goreng', 'Kue cokelat', 'Sup ayam']],
      ['Mengapa pelanggan memilih kopi es?', 'Karena hari sangat panas', ['Karena lebih murah', 'Karena tidak suka kopi panas', 'Karena disarankan pelayan']],
      ['Berapa total harganya?', 'Empat puluh lima ribu rupiah', ['Lima puluh ribu rupiah', 'Empat puluh ribu rupiah', 'Lima belas ribu rupiah']],
    ],
  },
  {
    id: 'en-a1-town', level: 'a1', title: 'Kota kecil saya', native: 'My small town',
    sentences: [
      ['I live in a small town near the mountains.', '', 'Saya tinggal di kota kecil dekat pegunungan.'],
      ['There is one school, two banks and a big mosque.', '', 'Ada satu sekolah, dua bank, dan satu masjid besar.'],
      ['There is no cinema, but there is a nice park.', '', 'Tidak ada bioskop, tetapi ada taman yang bagus.'],
      ['The people here are friendly.', '', 'Orang-orang di sini ramah.'],
      ['It is cool in the morning and warm in the afternoon.', '', 'Pagi hari sejuk dan siang hari hangat.'],
      ['Many people grow vegetables and coffee.', '', 'Banyak orang menanam sayur dan kopi.'],
      ['I like my town because it is quiet and green.', '', 'Saya suka kota saya karena tenang dan hijau.'],
    ],
    glossary: [['town', '', 'kota kecil'], ['mosque', '', 'masjid'], ['friendly', '', 'ramah'], ['grow', '', 'menanam']],
    questions: [
      ['Apa yang tidak ada di kota itu?', 'Bioskop', ['Sekolah', 'Taman', 'Bank']],
      ['Apa yang ditanam banyak orang?', 'Sayur dan kopi', ['Padi dan jagung', 'Teh dan buah', 'Bunga']],
      ['Mengapa penulis menyukai kotanya?', 'Tenang dan hijau', ['Ramai dan modern', 'Dekat pantai', 'Banyak toko']],
    ],
  },
  // ---------------------------------------------------------------- A2
  {
    id: 'en-a2-holiday', level: 'a2', title: 'Liburan ke Bali', native: 'A holiday in Bali',
    sentences: [
      ['Last year my family and I spent a week in Bali.', '', 'Tahun lalu saya dan keluarga menghabiskan seminggu di Bali.'],
      ['We stayed in a small hotel near the beach in Sanur.', '', 'Kami menginap di hotel kecil dekat pantai di Sanur.'],
      ['Every morning we walked along the beach before breakfast.', '', 'Setiap pagi kami berjalan menyusuri pantai sebelum sarapan.'],
      ['On the third day we rented a car and drove to Ubud.', '', 'Pada hari ketiga kami menyewa mobil dan pergi ke Ubud.'],
      ['We visited the rice fields and a monkey forest.', '', 'Kami mengunjungi sawah dan hutan monyet.'],
      ['A monkey took my brother’s hat, and everybody laughed.', '', 'Seekor monyet mengambil topi adik saya, dan semua orang tertawa.'],
      ['The trip was expensive, but it was the best holiday of my life.', '', 'Perjalanannya mahal, tetapi itu liburan terbaik dalam hidup saya.'],
    ],
    glossary: [['spent', '', 'menghabiskan (waktu)'], ['stayed', '', 'menginap'], ['rented', '', 'menyewa'], ['rice field', '', 'sawah']],
    questions: [
      ['Berapa lama mereka di Bali?', 'Seminggu', ['Tiga hari', 'Dua minggu', 'Sebulan']],
      ['Apa yang terjadi di hutan monyet?', 'Monyet mengambil topi adik penulis', ['Mereka tersesat', 'Mobil mereka rusak', 'Hujan turun deras']],
      ['Bagaimana pendapat penulis tentang liburan itu?', 'Mahal tetapi yang terbaik', ['Murah dan membosankan', 'Terlalu singkat', 'Melelahkan']],
    ],
  },
  {
    id: 'en-a2-job', level: 'a2', title: 'Pekerjaan baru Dani', native: 'Dani’s new job',
    sentences: [
      ['Dani started a new job at a bookshop two weeks ago.', '', 'Dani mulai bekerja di toko buku dua minggu lalu.'],
      ['He works from Tuesday to Saturday, from ten to six.', '', 'Dia bekerja Selasa sampai Sabtu, jam sepuluh sampai enam.'],
      ['He helps customers find books and he uses the cash register.', '', 'Dia membantu pelanggan mencari buku dan menggunakan mesin kasir.'],
      ['The work is not difficult, but he must stand all day.', '', 'Pekerjaannya tidak sulit, tetapi dia harus berdiri seharian.'],
      ['His manager is patient and explains everything clearly.', '', 'Manajernya sabar dan menjelaskan semuanya dengan jelas.'],
      ['Dani gets a discount on books, so he reads a lot now.', '', 'Dani mendapat diskon buku, jadi sekarang dia banyak membaca.'],
      ['He is happy because he loves books.', '', 'Dia senang karena dia mencintai buku.'],
    ],
    glossary: [['cash register', '', 'mesin kasir'], ['stand', '', 'berdiri'], ['patient', '', 'sabar'], ['discount', '', 'diskon']],
    questions: [
      ['Kapan Dani mulai bekerja?', 'Dua minggu lalu', ['Kemarin', 'Dua bulan lalu', 'Tahun lalu']],
      ['Apa bagian yang berat dari pekerjaannya?', 'Harus berdiri seharian', ['Manajernya galak', 'Gajinya kecil', 'Jaraknya jauh']],
      ['Mengapa Dani sekarang banyak membaca?', 'Dia mendapat diskon buku', ['Dia punya banyak waktu luang', 'Manajernya menyuruh', 'Dia sedang kuliah']],
    ],
  },
  {
    id: 'en-a2-lost', level: 'a2', title: 'Dompet yang hilang', native: 'The lost wallet',
    sentences: [
      ['Yesterday I was waiting for the bus when I noticed my wallet was gone.', '', 'Kemarin saya sedang menunggu bus ketika sadar dompet saya hilang.'],
      ['I checked all my pockets and my bag, but I could not find it.', '', 'Saya memeriksa semua saku dan tas, tetapi tidak menemukannya.'],
      ['My ID card, my bank card and some money were inside.', '', 'KTP, kartu bank, dan sejumlah uang ada di dalamnya.'],
      ['I walked back to the cafe where I had lunch.', '', 'Saya berjalan kembali ke kafe tempat saya makan siang.'],
      ['The waitress smiled and said, "Is this yours?"', '', 'Pelayan tersenyum dan berkata, "Apakah ini milik Anda?"'],
      ['She had found it under my table.', '', 'Dia menemukannya di bawah meja saya.'],
      ['I thanked her and left a big tip.', '', 'Saya berterima kasih dan memberi tip besar.'],
    ],
    glossary: [['notice', '', 'menyadari'], ['pocket', '', 'saku'], ['ID card', '', 'kartu identitas'], ['tip', '', 'uang tip']],
    questions: [
      ['Kapan penulis sadar dompetnya hilang?', 'Saat menunggu bus', ['Saat makan siang', 'Saat di rumah', 'Saat belanja']],
      ['Di mana dompet itu ditemukan?', 'Di bawah meja di kafe', ['Di dalam bus', 'Di halte', 'Di tas penulis']],
      ['Apa yang dilakukan penulis untuk berterima kasih?', 'Memberi tip besar', ['Membelikan bunga', 'Menulis ulasan', 'Mentraktir makan']],
    ],
  },
  {
    id: 'en-a2-cooking', level: 'a2', title: 'Belajar memasak', native: 'Learning to cook',
    sentences: [
      ['When I moved to a new city for university, I could not cook at all.', '', 'Ketika pindah ke kota baru untuk kuliah, saya sama sekali tidak bisa memasak.'],
      ['I usually bought instant noodles or fast food.', '', 'Saya biasanya membeli mi instan atau makanan cepat saji.'],
      ['After a few months I felt tired and unhealthy.', '', 'Setelah beberapa bulan saya merasa lelah dan tidak sehat.'],
      ['So I called my mother and asked for some easy recipes.', '', 'Jadi saya menelepon ibu dan meminta beberapa resep mudah.'],
      ['First I learned to make fried rice and vegetable soup.', '', 'Pertama saya belajar membuat nasi goreng dan sup sayur.'],
      ['Now I cook four times a week and I save a lot of money.', '', 'Sekarang saya memasak empat kali seminggu dan banyak berhemat.'],
      ['My friends often come to my room for dinner.', '', 'Teman-teman sering datang ke kamar saya untuk makan malam.'],
    ],
    glossary: [['at all', '', 'sama sekali'], ['fast food', '', 'makanan cepat saji'], ['recipe', '', 'resep'], ['save money', '', 'berhemat']],
    questions: [
      ['Apa yang biasa penulis makan dulu?', 'Mi instan atau makanan cepat saji', ['Masakan ibu', 'Salad', 'Nasi padang']],
      ['Dari siapa penulis mendapat resep?', 'Dari ibunya', ['Dari internet', 'Dari teman', 'Dari buku']],
      ['Apa manfaat memasak sendiri menurut teks?', 'Menghemat banyak uang', ['Menurunkan berat badan', 'Mendapat pekerjaan', 'Lulus lebih cepat']],
    ],
  },
  {
    id: 'en-a2-email', level: 'a2', title: 'Surel untuk teman', native: 'An email to a friend',
    sentences: [
      ['Hi Maya, thanks for your email. I am sorry I did not reply sooner.', '', 'Hai Maya, terima kasih atas surelmu. Maaf aku tidak membalas lebih cepat.'],
      ['I have been very busy with exams this month.', '', 'Aku sangat sibuk dengan ujian bulan ini.'],
      ['The good news is that I passed all of them!', '', 'Kabar baiknya, aku lulus semuanya!'],
      ['Next month I am going to visit Jakarta for a few days.', '', 'Bulan depan aku akan ke Jakarta selama beberapa hari.'],
      ['Are you free on the weekend of the 14th?', '', 'Apakah kamu luang di akhir pekan tanggal 14?'],
      ['Maybe we could go to a museum or try a new restaurant.', '', 'Mungkin kita bisa ke museum atau mencoba restoran baru.'],
      ['Write back soon. Love, Nadia', '', 'Segera balas ya. Salam sayang, Nadia'],
    ],
    glossary: [['reply', '', 'membalas'], ['passed', '', 'lulus (ujian)'], ['free', '', 'luang'], ['write back', '', 'membalas surat']],
    questions: [
      ['Mengapa Nadia terlambat membalas?', 'Sibuk dengan ujian', ['Sedang sakit', 'Sedang liburan', 'Ponselnya rusak']],
      ['Apa rencana Nadia bulan depan?', 'Mengunjungi Jakarta', ['Pindah rumah', 'Mulai bekerja', 'Mengikuti ujian lagi']],
      ['Apa yang Nadia usulkan?', 'Ke museum atau restoran baru', ['Menonton konser', 'Berenang', 'Belanja di pasar']],
    ],
  },
  {
    id: 'en-a2-doctor', level: 'a2', title: 'Ke dokter', native: 'A visit to the doctor',
    sentences: [
      ['Last Tuesday I woke up with a sore throat and a high temperature.', '', 'Selasa lalu saya bangun dengan sakit tenggorokan dan demam tinggi.'],
      ['I called my office and said I could not come to work.', '', 'Saya menelepon kantor dan bilang tidak bisa masuk kerja.'],
      ['In the afternoon I went to the clinic near my house.', '', 'Siangnya saya pergi ke klinik dekat rumah.'],
      ['The doctor looked at my throat and listened to my chest.', '', 'Dokter memeriksa tenggorokan dan mendengarkan dada saya.'],
      ['She said it was only a bad cold, not the flu.', '', 'Dia bilang itu hanya pilek berat, bukan flu.'],
      ['She told me to rest, drink warm water and take the medicine three times a day.', '', 'Dia menyuruh saya beristirahat, minum air hangat, dan minum obat tiga kali sehari.'],
      ['After three days I felt much better.', '', 'Setelah tiga hari saya merasa jauh lebih baik.'],
    ],
    glossary: [['sore throat', '', 'sakit tenggorokan'], ['temperature', '', 'suhu/demam'], ['chest', '', 'dada'], ['medicine', '', 'obat']],
    questions: [
      ['Apa keluhan penulis?', 'Sakit tenggorokan dan demam', ['Sakit perut', 'Sakit gigi', 'Patah tangan']],
      ['Apa kata dokter?', 'Hanya pilek berat', ['Terkena flu berat', 'Harus dirawat', 'Perlu operasi']],
      ['Berapa kali sehari obat diminum?', 'Tiga kali', ['Sekali', 'Dua kali', 'Empat kali']],
    ],
  },
  {
    id: 'en-a2-festival', level: 'a2', title: 'Festival makanan', native: 'The food festival',
    sentences: [
      ['Every August our city has a big food festival in the main square.', '', 'Setiap Agustus kota kami mengadakan festival makanan besar di alun-alun.'],
      ['There are more than a hundred stalls from all over Indonesia.', '', 'Ada lebih dari seratus kios dari seluruh Indonesia.'],
      ['You can try rendang from Padang, gudeg from Yogyakarta and many kinds of cake.', '', 'Kamu bisa mencoba rendang dari Padang, gudeg dari Yogyakarta, dan banyak jenis kue.'],
      ['This year I went with my cousins on the first night.', '', 'Tahun ini saya pergi dengan sepupu pada malam pertama.'],
      ['It was very crowded, so we waited a long time for satay.', '', 'Sangat ramai, jadi kami lama mengantre sate.'],
      ['There was also live music and a cooking competition.', '', 'Ada juga musik langsung dan lomba memasak.'],
      ['We ate too much, but we want to go again next year.', '', 'Kami makan terlalu banyak, tetapi ingin datang lagi tahun depan.'],
    ],
    glossary: [['main square', '', 'alun-alun'], ['stall', '', 'kios'], ['crowded', '', 'ramai/padat'], ['competition', '', 'lomba']],
    questions: [
      ['Kapan festival itu diadakan?', 'Setiap Agustus', ['Setiap Desember', 'Setiap Ramadan', 'Setiap Januari']],
      ['Mengapa mereka lama menunggu sate?', 'Karena sangat ramai', ['Karena satenya habis', 'Karena hujan', 'Karena kiosnya belum buka']],
      ['Apa lagi yang ada di festival selain makanan?', 'Musik langsung dan lomba memasak', ['Pameran mobil', 'Pertandingan sepak bola', 'Bioskop terbuka']],
    ],
  },
  {
    id: 'en-a2-phone', level: 'a2', title: 'Satu hari tanpa ponsel', native: 'A day without my phone',
    sentences: [
      ['Last Saturday my phone stopped working, so I spent a whole day without it.', '', 'Sabtu lalu ponsel saya mati, jadi saya menghabiskan sehari penuh tanpanya.'],
      ['At first I felt nervous because I could not check my messages.', '', 'Awalnya saya gugup karena tidak bisa memeriksa pesan.'],
      ['Then I decided to go for a long walk in the park.', '', 'Lalu saya memutuskan berjalan-jalan lama di taman.'],
      ['I noticed birds, flowers and people I never saw before.', '', 'Saya memperhatikan burung, bunga, dan orang-orang yang belum pernah saya lihat.'],
      ['In the afternoon I finished a book that I started months ago.', '', 'Sorenya saya menyelesaikan buku yang saya mulai berbulan-bulan lalu.'],
      ['I even talked to my neighbor for an hour.', '', 'Saya bahkan mengobrol dengan tetangga selama satu jam.'],
      ['Now I try to switch off my phone every Saturday morning.', '', 'Sekarang saya mencoba mematikan ponsel setiap Sabtu pagi.'],
    ],
    glossary: [['stop working', '', 'rusak/mati'], ['nervous', '', 'gugup'], ['notice', '', 'memperhatikan'], ['switch off', '', 'mematikan']],
    questions: [
      ['Bagaimana perasaan penulis pada awalnya?', 'Gugup', ['Senang', 'Marah', 'Mengantuk']],
      ['Apa yang diselesaikan penulis sore itu?', 'Sebuah buku', ['Pekerjaan kantor', 'Lukisan', 'Membersihkan rumah']],
      ['Apa kebiasaan baru penulis?', 'Mematikan ponsel setiap Sabtu pagi', ['Jalan pagi setiap hari', 'Membeli buku setiap minggu', 'Tidak memakai media sosial']],
    ],
  },
  // ---------------------------------------------------------------- B1
  {
    id: 'en-b1-remote', level: 'b1', title: 'Bekerja dari rumah', native: 'Working from home',
    sentences: [
      ['Since last year, Sinta has been working from home three days a week.', '', 'Sejak tahun lalu, Sinta bekerja dari rumah tiga hari seminggu.'],
      ['She no longer spends two hours a day stuck in traffic.', '', 'Dia tidak lagi menghabiskan dua jam sehari terjebak macet.'],
      ['As a result, she has more time for exercise and her family.', '', 'Akibatnya, dia punya lebih banyak waktu untuk olahraga dan keluarga.'],
      ['However, working at home is not always easy.', '', 'Namun, bekerja di rumah tidak selalu mudah.'],
      ['Her children often interrupt her during online meetings.', '', 'Anak-anaknya sering mengganggu saat rapat daring.'],
      ['She also misses chatting with her colleagues over lunch.', '', 'Dia juga rindu mengobrol dengan rekan kerja saat makan siang.'],
      ['To stay focused, she has set up a small office in a quiet corner and keeps regular hours.', '', 'Agar tetap fokus, dia membuat kantor kecil di sudut yang tenang dan menjaga jam kerja teratur.'],
      ['Overall, she believes the advantages outweigh the disadvantages.', '', 'Secara keseluruhan, dia yakin kelebihannya lebih besar daripada kekurangannya.'],
    ],
    glossary: [['stuck', '', 'terjebak'], ['interrupt', '', 'menyela'], ['colleague', '', 'rekan kerja'], ['outweigh', '', 'lebih besar daripada']],
    questions: [
      ['Apa keuntungan utama bagi Sinta?', 'Lebih banyak waktu untuk olahraga dan keluarga', ['Gaji lebih besar', 'Rapat lebih sedikit', 'Dapat promosi']],
      ['Apa salah satu kesulitannya?', 'Anak-anak sering mengganggu saat rapat', ['Internet selalu mati', 'Atasannya tidak setuju', 'Rumahnya terlalu kecil']],
      ['Apa yang dilakukan Sinta agar tetap fokus?', 'Membuat kantor kecil dan menjaga jam kerja', ['Bekerja di kafe', 'Bekerja malam hari', 'Menyewa pengasuh']],
    ],
  },
  {
    id: 'en-b1-plastic', level: 'b1', title: 'Mengurangi plastik', native: 'Cutting down on plastic',
    sentences: [
      ['Indonesia is one of the countries that produces the most plastic waste in the sea.', '', 'Indonesia adalah salah satu negara penghasil sampah plastik terbanyak di laut.'],
      ['Many cities have now banned single-use plastic bags in shops.', '', 'Banyak kota kini melarang kantong plastik sekali pakai di toko.'],
      ['At first, some shoppers complained because they had to bring their own bags.', '', 'Awalnya, beberapa pembeli mengeluh karena harus membawa tas sendiri.'],
      ['Now most people are used to it.', '', 'Sekarang kebanyakan orang sudah terbiasa.'],
      ['Some cafes give a discount to customers who bring their own cups.', '', 'Beberapa kafe memberi diskon kepada pelanggan yang membawa gelas sendiri.'],
      ['Young volunteers also organize beach clean-ups every month.', '', 'Relawan muda juga mengadakan bersih-bersih pantai setiap bulan.'],
      ['Experts say that small changes by millions of people can make a real difference.', '', 'Para ahli mengatakan perubahan kecil oleh jutaan orang dapat membawa perbedaan nyata.'],
    ],
    glossary: [['waste', '', 'sampah/limbah'], ['ban', '', 'melarang'], ['single-use', '', 'sekali pakai'], ['volunteer', '', 'relawan']],
    questions: [
      ['Apa yang dilarang di banyak kota?', 'Kantong plastik sekali pakai', ['Botol kaca', 'Sedotan kertas', 'Makanan cepat saji']],
      ['Apa yang diberikan kafe tertentu?', 'Diskon bagi yang membawa gelas sendiri', ['Kantong gratis', 'Minuman gratis', 'Sedotan logam']],
      ['Apa pesan utama para ahli?', 'Perubahan kecil banyak orang membawa perbedaan', ['Hanya pemerintah yang bisa bertindak', 'Plastik tidak berbahaya', 'Daur ulang tidak berguna']],
    ],
  },
  {
    id: 'en-b1-language', level: 'b1', title: 'Cara saya belajar bahasa', native: 'How I learn languages',
    sentences: [
      ['I have been learning English for three years, and I have tried many methods.', '', 'Saya sudah belajar bahasa Inggris selama tiga tahun dan mencoba banyak metode.'],
      ['At school we mostly memorized grammar rules, which I found boring.', '', 'Di sekolah kami kebanyakan menghafal aturan tata bahasa, yang menurut saya membosankan.'],
      ['Things changed when I started watching series with English subtitles.', '', 'Semuanya berubah ketika saya mulai menonton serial dengan subtitel bahasa Inggris.'],
      ['I wrote down useful phrases in a notebook and reviewed them every evening.', '', 'Saya mencatat frasa berguna di buku dan mengulangnya setiap malam.'],
      ['Later, I joined an online group where members practise speaking together.', '', 'Kemudian saya bergabung dengan grup daring tempat anggota berlatih berbicara bersama.'],
      ['I was shy at first, but everyone was supportive.', '', 'Awalnya saya malu, tetapi semua orang mendukung.'],
      ['My advice is simple: find something you enjoy and practise a little every day.', '', 'Saran saya sederhana: temukan sesuatu yang kamu sukai dan berlatih sedikit setiap hari.'],
    ],
    glossary: [['memorize', '', 'menghafal'], ['subtitles', '', 'teks terjemahan'], ['review', '', 'mengulang'], ['supportive', '', 'mendukung']],
    questions: [
      ['Mengapa penulis merasa bosan di sekolah?', 'Kebanyakan menghafal aturan tata bahasa', ['Gurunya galak', 'Kelasnya terlalu besar', 'Tidak ada buku']],
      ['Apa yang mengubah cara belajar penulis?', 'Menonton serial dengan subtitel', ['Kursus mahal', 'Pindah ke luar negeri', 'Membaca novel']],
      ['Apa saran penulis?', 'Temukan hal yang disukai dan berlatih setiap hari', ['Belajar lima jam sehari', 'Hafalkan kamus', 'Hanya belajar tata bahasa']],
    ],
  },
  {
    id: 'en-b1-complaint', level: 'b1', title: 'Surat keluhan', native: 'A letter of complaint',
    sentences: [
      ['Dear Sir or Madam, I am writing to complain about a jacket I ordered from your website.', '', 'Yang terhormat, saya menulis untuk mengeluhkan jaket yang saya pesan dari situs Anda.'],
      ['I placed the order on 3 March, and I was told it would arrive within five days.', '', 'Saya memesan pada 3 Maret dan diberi tahu barangnya tiba dalam lima hari.'],
      ['However, it did not arrive until 20 March.', '', 'Namun, barangnya baru tiba pada 20 Maret.'],
      ['When I opened the package, I found that the jacket was the wrong size and one button was missing.', '', 'Saat membuka paket, saya mendapati ukuran jaketnya salah dan satu kancing hilang.'],
      ['I contacted customer service twice, but nobody replied.', '', 'Saya menghubungi layanan pelanggan dua kali, tetapi tidak ada yang membalas.'],
      ['I would like a full refund, including the delivery cost.', '', 'Saya ingin pengembalian dana penuh, termasuk biaya kirim.'],
      ['I look forward to hearing from you soon. Yours faithfully, Andi Pratama', '', 'Saya menantikan balasan Anda segera. Hormat saya, Andi Pratama'],
    ],
    glossary: [['complain', '', 'mengeluh'], ['place an order', '', 'memesan'], ['missing', '', 'hilang'], ['refund', '', 'pengembalian dana']],
    questions: [
      ['Kapan jaket itu akhirnya tiba?', '20 Maret', ['3 Maret', '8 Maret', '25 Maret']],
      ['Apa masalah pada jaket itu?', 'Ukuran salah dan satu kancing hilang', ['Warnanya salah', 'Robek di lengan', 'Terlalu mahal']],
      ['Apa yang diminta Andi?', 'Pengembalian dana penuh', ['Jaket pengganti', 'Diskon untuk pesanan berikutnya', 'Permintaan maaf tertulis saja']],
    ],
  },
  {
    id: 'en-b1-volunteer', level: 'b1', title: 'Menjadi relawan', native: 'Volunteering at the library',
    sentences: [
      ['Every Saturday morning, Fajar volunteers at a small library in his village.', '', 'Setiap Sabtu pagi, Fajar menjadi relawan di perpustakaan kecil di desanya.'],
      ['The library was opened by a group of students who collected second-hand books.', '', 'Perpustakaan itu dibuka oleh sekelompok mahasiswa yang mengumpulkan buku bekas.'],
      ['Fajar reads stories to young children and helps older ones with their homework.', '', 'Fajar membacakan cerita untuk anak kecil dan membantu anak yang lebih besar mengerjakan PR.'],
      ['Many of the children do not have books at home, so they love coming.', '', 'Banyak anak tidak punya buku di rumah, jadi mereka senang datang.'],
      ['Last month the library received a donation of two hundred new books.', '', 'Bulan lalu perpustakaan menerima sumbangan dua ratus buku baru.'],
      ['Fajar says that volunteering has taught him patience and responsibility.', '', 'Fajar mengatakan menjadi relawan mengajarinya kesabaran dan tanggung jawab.'],
      ['He hopes to become a teacher after he graduates.', '', 'Dia berharap menjadi guru setelah lulus.'],
    ],
    glossary: [['second-hand', '', 'bekas'], ['donation', '', 'sumbangan'], ['patience', '', 'kesabaran'], ['graduate', '', 'lulus']],
    questions: [
      ['Siapa yang membuka perpustakaan itu?', 'Sekelompok mahasiswa', ['Pemerintah desa', 'Seorang guru', 'Sebuah perusahaan']],
      ['Apa yang diterima perpustakaan bulan lalu?', 'Dua ratus buku baru', ['Komputer baru', 'Gedung baru', 'Uang tunai']],
      ['Apa cita-cita Fajar?', 'Menjadi guru', ['Menjadi dokter', 'Menjadi penulis', 'Membuka toko buku']],
    ],
  },
  {
    id: 'en-b1-sleep', level: 'b1', title: 'Pentingnya tidur', native: 'Why sleep matters',
    sentences: [
      ['Many teenagers sleep less than seven hours a night, especially during exams.', '', 'Banyak remaja tidur kurang dari tujuh jam semalam, terutama saat ujian.'],
      ['Scientists say that young people actually need eight to ten hours.', '', 'Ilmuwan mengatakan anak muda sebenarnya butuh delapan sampai sepuluh jam.'],
      ['When we sleep, the brain organizes the information we learned during the day.', '', 'Saat kita tidur, otak mengatur informasi yang kita pelajari seharian.'],
      ['Without enough sleep, it is harder to concentrate and remember things.', '', 'Tanpa cukup tidur, lebih sulit berkonsentrasi dan mengingat.'],
      ['Screens are one of the biggest problems, because their light keeps us awake.', '', 'Layar adalah salah satu masalah terbesar, karena cahayanya membuat kita terjaga.'],
      ['Doctors recommend putting phones away at least an hour before bed.', '', 'Dokter menyarankan menyingkirkan ponsel setidaknya satu jam sebelum tidur.'],
      ['So if you want better grades, staying up all night may not be the answer.', '', 'Jadi jika ingin nilai lebih baik, begadang semalaman mungkin bukan jawabannya.'],
    ],
    glossary: [['teenager', '', 'remaja'], ['concentrate', '', 'berkonsentrasi'], ['awake', '', 'terjaga'], ['stay up', '', 'begadang']],
    questions: [
      ['Berapa jam tidur yang dibutuhkan anak muda?', 'Delapan sampai sepuluh jam', ['Lima sampai enam jam', 'Tujuh jam', 'Dua belas jam']],
      ['Apa yang dilakukan otak saat tidur?', 'Mengatur informasi yang dipelajari', ['Berhenti bekerja', 'Menghapus semua ingatan', 'Membakar lemak']],
      ['Apa saran dokter?', 'Menyingkirkan ponsel satu jam sebelum tidur', ['Minum kopi sebelum belajar', 'Tidur siang tiga jam', 'Belajar sampai larut malam']],
    ],
  },
  {
    id: 'en-b1-market', level: 'b1', title: 'Pasar tradisional vs. supermarket', native: 'Traditional markets or supermarkets?',
    sentences: [
      ['In many Indonesian towns, people can choose between traditional markets and modern supermarkets.', '', 'Di banyak kota Indonesia, orang bisa memilih antara pasar tradisional dan supermarket modern.'],
      ['Supermarkets are clean, air-conditioned and open until late.', '', 'Supermarket bersih, ber-AC, dan buka sampai malam.'],
      ['Prices are fixed, so you do not need to bargain.', '', 'Harganya tetap, jadi kamu tidak perlu menawar.'],
      ['Traditional markets, on the other hand, usually sell fresher fruit, vegetables and fish.', '', 'Sebaliknya, pasar tradisional biasanya menjual buah, sayur, dan ikan yang lebih segar.'],
      ['They are often cheaper, and buying there supports local farmers.', '', 'Harganya sering lebih murah, dan berbelanja di sana mendukung petani lokal.'],
      ['Some markets have been renovated to make them cleaner and more attractive.', '', 'Beberapa pasar telah direnovasi agar lebih bersih dan menarik.'],
      ['Personally, I buy fresh food at the market and household items at the supermarket.', '', 'Secara pribadi, saya membeli makanan segar di pasar dan barang rumah tangga di supermarket.'],
    ],
    glossary: [['air-conditioned', '', 'ber-AC'], ['fixed', '', 'tetap'], ['bargain', '', 'menawar'], ['renovate', '', 'merenovasi']],
    questions: [
      ['Apa kelebihan supermarket menurut teks?', 'Bersih, ber-AC, dan buka sampai malam', ['Harganya selalu termurah', 'Barangnya lebih segar', 'Bisa menawar']],
      ['Mengapa berbelanja di pasar tradisional dianggap baik?', 'Mendukung petani lokal', ['Ada parkir luas', 'Menerima kartu kredit', 'Buka 24 jam']],
      ['Apa kebiasaan penulis?', 'Makanan segar di pasar, barang rumah tangga di supermarket', ['Semua belanja di supermarket', 'Semua belanja daring', 'Hanya ke pasar tradisional']],
    ],
  },
];
