import type { PassageSource } from './types';

// Long reading/listening passages for JLPT N3-N1 (level ids follow the study bank).
export const japanesePassages: PassageSource[] = [
  // ---------------------------------------------------------------- N3
  {
    id: 'n3-hikkoshi', level: 'intermediate', title: 'Pindah ke kota baru', native: '新しい町への引っ越し',
    sentences: [
      ['先月、仕事のために大阪から名古屋へ引っ越しました。', '', 'Bulan lalu saya pindah dari Osaka ke Nagoya karena pekerjaan.'],
      ['最初は知り合いが一人もいなくて、とても寂しかったです。', '', 'Awalnya saya tidak punya satu kenalan pun, jadi sangat kesepian.'],
      ['ある日、近所のスーパーで同じアパートに住んでいる人に会いました。', '', 'Suatu hari saya bertemu orang yang tinggal di apartemen yang sama di supermarket dekat rumah.'],
      ['その人は町の便利な店や安いレストランを教えてくれました。', '', 'Orang itu memberi tahu saya toko-toko praktis dan restoran murah di kota.'],
      ['週末には一緒に公園を散歩するようになりました。', '', 'Pada akhir pekan kami mulai berjalan-jalan bersama di taman.'],
      ['今では、名古屋の生活にもだいぶ慣れてきました。', '', 'Sekarang saya sudah cukup terbiasa dengan kehidupan di Nagoya.'],
      ['新しい場所では、自分から話しかけることが大切だと思います。', '', 'Menurut saya, di tempat baru penting untuk memulai percakapan sendiri.'],
    ],
    glossary: [['引っ越す', 'ひっこす', 'pindah rumah'], ['近所', 'きんじょ', 'lingkungan sekitar rumah'], ['慣れる', 'なれる', 'terbiasa'], ['話しかける', 'はなしかける', 'mengajak bicara']],
    questions: [
      ['Mengapa penulis pindah ke Nagoya?', 'Karena pekerjaan', ['Karena kuliah', 'Karena menikah', 'Karena biaya hidup murah']],
      ['Di mana penulis bertemu tetangganya?', 'Di supermarket dekat rumah', ['Di kantor', 'Di stasiun', 'Di taman']],
      ['Apa pendapat penulis di akhir teks?', 'Penting memulai percakapan sendiri', ['Lebih baik tinggal di kota besar', 'Tetangga biasanya tidak ramah', 'Pindah rumah itu mahal']],
    ],
  },
  {
    id: 'n3-mensetsu', level: 'intermediate', title: 'Wawancara kerja paruh waktu', native: 'アルバイトの面接',
    sentences: [
      ['昨日、駅前のカフェでアルバイトの面接を受けました。', '', 'Kemarin saya mengikuti wawancara kerja paruh waktu di kafe depan stasiun.'],
      ['店長に「どうしてこの店で働きたいのですか」と聞かれました。', '', 'Manajer bertanya, "Mengapa kamu ingin bekerja di toko ini?"'],
      ['私は「日本語を使ってお客さんと話したいからです」と答えました。', '', 'Saya menjawab, "Karena saya ingin berbicara dengan pelanggan memakai bahasa Jepang."'],
      ['店長は、朝六時から働けるかどうかも確認しました。', '', 'Manajer juga memastikan apakah saya bisa bekerja mulai pukul enam pagi.'],
      ['朝は少し苦手ですが、週に三回なら大丈夫だと伝えました。', '', 'Saya agak tidak kuat bangun pagi, tetapi saya bilang tiga kali seminggu tidak masalah.'],
      ['面接の後、来週から研修を始めることになりました。', '', 'Setelah wawancara, diputuskan saya mulai pelatihan minggu depan.'],
    ],
    glossary: [['面接', 'めんせつ', 'wawancara'], ['店長', 'てんちょう', 'manajer toko'], ['確認する', 'かくにんする', 'memastikan'], ['研修', 'けんしゅう', 'pelatihan']],
    questions: [
      ['Mengapa penulis ingin bekerja di kafe itu?', 'Ingin berbicara bahasa Jepang dengan pelanggan', ['Gajinya tinggi', 'Dekat dengan rumah', 'Suka kopi']],
      ['Berapa kali seminggu penulis bisa bekerja pagi?', 'Tiga kali', ['Setiap hari', 'Dua kali', 'Lima kali']],
      ['Apa hasil wawancaranya?', 'Mulai pelatihan minggu depan', ['Ditolak', 'Harus wawancara lagi', 'Langsung bekerja hari itu']],
    ],
  },
  {
    id: 'n3-densha', level: 'intermediate', title: 'Etika di kereta Jepang', native: '電車の中のマナー',
    sentences: [
      ['日本の電車は、朝と夕方にとても込みます。', '', 'Kereta di Jepang sangat penuh pada pagi dan sore hari.'],
      ['電車の中では、携帯電話で話さないようにと言われています。', '', 'Di dalam kereta, orang diminta untuk tidak berbicara di telepon genggam.'],
      ['また、大きいかばんは前に持つか、棚に置くのがマナーです。', '', 'Selain itu, tas besar sebaiknya dipegang di depan atau diletakkan di rak.'],
      ['お年寄りや体の不自由な人のために、優先席があります。', '', 'Ada kursi prioritas untuk lansia dan penyandang disabilitas.'],
      ['外国人の中には、電車が静かすぎて驚く人も多いそうです。', '', 'Konon banyak orang asing yang kaget karena keretanya terlalu sunyi.'],
      ['しかし、みんなが気持ちよく乗るためのルールなのです。', '', 'Namun, itu adalah aturan agar semua orang bisa naik dengan nyaman.'],
    ],
    glossary: [['込む', 'こむ', 'penuh sesak'], ['棚', 'たな', 'rak'], ['優先席', 'ゆうせんせき', 'kursi prioritas'], ['驚く', 'おどろく', 'terkejut']],
    questions: [
      ['Apa yang sebaiknya tidak dilakukan di kereta?', 'Berbicara di telepon', ['Membaca buku', 'Duduk', 'Mendengarkan musik dengan earphone']],
      ['Untuk siapa kursi prioritas disediakan?', 'Lansia dan penyandang disabilitas', ['Pelajar', 'Turis asing', 'Pegawai kereta']],
      ['Mengapa sebagian orang asing terkejut?', 'Keretanya terlalu sunyi', ['Keretanya terlambat', 'Tiketnya mahal', 'Keretanya kosong']],
    ],
  },
  {
    id: 'n3-kenkoushindan', level: 'intermediate', title: 'Pemeriksaan kesehatan', native: '健康診断',
    sentences: [
      ['会社では毎年一回、健康診断を受けなければなりません。', '', 'Di perusahaan, setiap tahun kami wajib menjalani pemeriksaan kesehatan sekali.'],
      ['前の日の夜九時からは、何も食べてはいけません。', '', 'Mulai pukul sembilan malam sehari sebelumnya, tidak boleh makan apa pun.'],
      ['今年の結果を見ると、体重が去年より五キロ増えていました。', '', 'Melihat hasil tahun ini, berat badan saya naik lima kilo dibanding tahun lalu.'],
      ['医者には、甘い飲み物を減らして、もっと歩くように言われました。', '', 'Dokter menyuruh saya mengurangi minuman manis dan lebih banyak berjalan.'],
      ['それで、毎朝一つ前の駅で降りて、会社まで歩くことにしました。', '', 'Karena itu, saya memutuskan turun satu stasiun lebih awal setiap pagi dan berjalan ke kantor.'],
      ['一か月続けたら、体が軽くなった気がします。', '', 'Setelah sebulan melakukannya, badan saya terasa lebih ringan.'],
    ],
    glossary: [['健康診断', 'けんこうしんだん', 'pemeriksaan kesehatan'], ['体重', 'たいじゅう', 'berat badan'], ['減らす', 'へらす', 'mengurangi'], ['続ける', 'つづける', 'melanjutkan']],
    questions: [
      ['Mulai kapan penulis tidak boleh makan?', 'Pukul sembilan malam sehari sebelumnya', ['Pagi hari pemeriksaan', 'Tengah hari', 'Dua hari sebelumnya']],
      ['Apa saran dokter?', 'Kurangi minuman manis dan lebih banyak berjalan', ['Makan lebih banyak sayur', 'Tidur lebih lama', 'Berhenti bekerja']],
      ['Apa yang penulis lakukan setiap pagi?', 'Turun satu stasiun lebih awal lalu berjalan', ['Berlari di taman', 'Naik sepeda ke kantor', 'Berenang']],
    ],
  },
  {
    id: 'n3-ryokou', level: 'intermediate', title: 'Rencana liburan bersama teman', native: '友達との旅行計画',
    sentences: [
      ['夏休みに、大学の友達三人と京都へ旅行することになりました。', '', 'Pada libur musim panas, saya akan berwisata ke Kyoto bersama tiga teman kuliah.'],
      ['お寺を見たい人もいれば、買い物をしたい人もいます。', '', 'Ada yang ingin melihat kuil, ada juga yang ingin berbelanja.'],
      ['話し合った結果、一日目はお寺、二日目は自由行動にしました。', '', 'Setelah berdiskusi, hari pertama untuk kuil dan hari kedua bebas.'],
      ['ホテルは駅から近くて、朝ご飯が付いているところを予約しました。', '', 'Kami memesan hotel yang dekat stasiun dan sudah termasuk sarapan.'],
      ['新幹線は高いので、夜行バスで行くことにしました。', '', 'Karena shinkansen mahal, kami memutuskan pergi dengan bus malam.'],
      ['旅行の準備をしている時間も、とても楽しいです。', '', 'Waktu mempersiapkan perjalanan pun sangat menyenangkan.'],
    ],
    glossary: [['自由行動', 'じゆうこうどう', 'kegiatan bebas'], ['予約する', 'よやくする', 'memesan'], ['夜行バス', 'やこうバス', 'bus malam'], ['準備', 'じゅんび', 'persiapan']],
    questions: [
      ['Apa rencana hari kedua?', 'Kegiatan bebas', ['Melihat kuil', 'Pulang', 'Pergi ke Osaka']],
      ['Mengapa mereka tidak naik shinkansen?', 'Karena mahal', ['Karena penuh', 'Karena lambat', 'Karena tidak ada jadwal']],
      ['Hotel seperti apa yang dipesan?', 'Dekat stasiun dan termasuk sarapan', ['Di pegunungan', 'Paling murah tanpa sarapan', 'Hotel mewah dengan kolam']],
    ],
  },
  {
    id: 'n3-toshokan', level: 'intermediate', title: 'Pengumuman perpustakaan', native: '図書館からのお知らせ',
    sentences: [
      ['市立図書館は、来月一日から十日まで工事のため休館します。', '', 'Perpustakaan kota tutup dari tanggal 1 sampai 10 bulan depan karena renovasi.'],
      ['この期間は、本を返すことも借りることもできません。', '', 'Selama periode ini, buku tidak bisa dikembalikan maupun dipinjam.'],
      ['返す期限が休館中になる本は、十一日まで延長します。', '', 'Buku yang batas pengembaliannya jatuh saat tutup diperpanjang sampai tanggal 11.'],
      ['インターネットでの予約は、休館中も使えます。', '', 'Pemesanan lewat internet tetap bisa dipakai selama tutup.'],
      ['工事の後は、子ども用のコーナーが広くなります。', '', 'Setelah renovasi, sudut anak-anak akan menjadi lebih luas.'],
      ['ご迷惑をおかけしますが、よろしくお願いいたします。', '', 'Mohon maaf atas ketidaknyamanannya, terima kasih atas pengertiannya.'],
    ],
    glossary: [['休館', 'きゅうかん', 'tutup (gedung)'], ['工事', 'こうじ', 'konstruksi / renovasi'], ['期限', 'きげん', 'batas waktu'], ['延長する', 'えんちょうする', 'memperpanjang']],
    questions: [
      ['Mengapa perpustakaan tutup?', 'Karena renovasi', ['Karena libur nasional', 'Karena kekurangan staf', 'Karena pindah gedung']],
      ['Apa yang tetap bisa dilakukan selama tutup?', 'Memesan lewat internet', ['Meminjam buku', 'Mengembalikan buku', 'Membaca di ruang baca']],
      ['Apa yang berubah setelah renovasi?', 'Sudut anak-anak lebih luas', ['Jam buka lebih panjang', 'Ada kafe baru', 'Buku bisa dipinjam lebih banyak']],
    ],
  },
  {
    id: 'n3-gomi', level: 'intermediate', title: 'Cara memilah sampah', native: 'ゴミの分け方',
    sentences: [
      ['日本では、ゴミを種類ごとに分けて出さなければなりません。', '', 'Di Jepang, sampah harus dipilah menurut jenisnya sebelum dibuang.'],
      ['燃えるゴミは月曜日と木曜日、プラスチックは水曜日に出します。', '', 'Sampah yang bisa dibakar dibuang Senin dan Kamis, plastik pada hari Rabu.'],
      ['ペットボトルは、キャップとラベルを取ってから洗います。', '', 'Botol plastik dicuci setelah tutup dan labelnya dilepas.'],
      ['ゴミは朝八時までに決められた場所に出すことになっています。', '', 'Sampah harus diletakkan di tempat yang ditentukan paling lambat pukul delapan pagi.'],
      ['ルールを守らないと、ゴミを持って行ってもらえないこともあります。', '', 'Jika aturan tidak dipatuhi, sampah bisa saja tidak diangkut.'],
      ['最初は大変でしたが、今は環境のために大切なことだと感じています。', '', 'Awalnya merepotkan, tetapi sekarang saya merasa itu penting bagi lingkungan.'],
    ],
    glossary: [['燃える', 'もえる', 'terbakar'], ['種類', 'しゅるい', 'jenis'], ['守る', 'まもる', 'mematuhi / menjaga'], ['環境', 'かんきょう', 'lingkungan']],
    questions: [
      ['Kapan sampah plastik dibuang?', 'Hari Rabu', ['Senin dan Kamis', 'Hari Jumat', 'Setiap hari']],
      ['Apa yang dilakukan pada botol plastik?', 'Lepas tutup dan label lalu dicuci', ['Dibakar', 'Dihancurkan', 'Dicampur dengan sampah lain']],
      ['Apa akibat jika aturan tidak dipatuhi?', 'Sampah bisa tidak diangkut', ['Harus membayar pajak', 'Dipanggil polisi', 'Tidak ada akibat']],
    ],
  },
  {
    id: 'n3-fujisan', level: 'intermediate', title: 'Catatan harian: mendaki Fuji', native: '日記：初めての富士山',
    sentences: [
      ['八月十日、初めて富士山に登りました。', '', 'Tanggal 10 Agustus, saya mendaki Gunung Fuji untuk pertama kalinya.'],
      ['夜の十時に五合目を出発して、朝日を見るために一晩中歩きました。', '', 'Saya berangkat dari pos kelima pukul sepuluh malam dan berjalan semalaman untuk melihat matahari terbit.'],
      ['山の上は思っていたよりずっと寒くて、手が冷たくなりました。', '', 'Di puncak jauh lebih dingin dari yang saya kira, sampai tangan saya membeku.'],
      ['途中で何度もやめたいと思いましたが、友達が励ましてくれました。', '', 'Di tengah jalan berkali-kali saya ingin berhenti, tetapi teman menyemangati saya.'],
      ['頂上から見た朝日は、言葉にできないほどきれいでした。', '', 'Matahari terbit yang terlihat dari puncak begitu indah hingga tak terlukiskan.'],
      ['もう一度登りたいかと聞かれたら、少し考えてしまいます。', '', 'Kalau ditanya apakah ingin mendaki lagi, saya jadi berpikir sejenak.'],
    ],
    glossary: [['登る', 'のぼる', 'mendaki'], ['出発する', 'しゅっぱつする', 'berangkat'], ['励ます', 'はげます', 'menyemangati'], ['頂上', 'ちょうじょう', 'puncak']],
    questions: [
      ['Mengapa penulis berjalan semalaman?', 'Untuk melihat matahari terbit', ['Karena tersesat', 'Karena bus terlambat', 'Untuk menghindari panas']],
      ['Bagaimana suhu di puncak?', 'Jauh lebih dingin dari perkiraan', ['Panas', 'Sama seperti di bawah', 'Hangat dan nyaman']],
      ['Siapa yang menyemangati penulis?', 'Temannya', ['Pemandu gunung', 'Keluarganya', 'Orang asing']],
    ],
  },
  // ---------------------------------------------------------------- N2
  {
    id: 'n2-zaitaku', level: 'advanced', title: 'Meluasnya kerja dari rumah', native: '在宅勤務の広がり',
    sentences: [
      ['感染症の流行をきっかけに、在宅勤務を導入する企業が急増した。', '', 'Dipicu oleh wabah penyakit menular, perusahaan yang menerapkan kerja dari rumah meningkat pesat.'],
      ['通勤時間がなくなったことで、家族と過ごす時間が増えたという声は多い。', '', 'Banyak yang mengatakan waktu bersama keluarga bertambah karena waktu perjalanan kerja hilang.'],
      ['一方で、仕事と私生活の境目があいまいになり、かえって長く働いてしまう人もいる。', '', 'Di sisi lain, ada orang yang justru bekerja lebih lama karena batas kerja dan kehidupan pribadi menjadi kabur.'],
      ['また、同僚と雑談する機会が減り、孤独を感じるという調査結果もある。', '', 'Ada pula hasil survei bahwa kesempatan mengobrol dengan rekan berkurang sehingga orang merasa kesepian.'],
      ['そのため、週に二、三日だけ出社する「ハイブリッド型」を選ぶ会社が増えている。', '', 'Karena itu, semakin banyak perusahaan memilih model "hibrida" dengan masuk kantor hanya dua atau tiga hari seminggu.'],
      ['働き方の多様化は、今後も続いていくに違いない。', '', 'Keberagaman cara bekerja pasti akan terus berlanjut ke depannya.'],
    ],
    glossary: [['導入する', 'どうにゅうする', 'menerapkan'], ['境目', 'さかいめ', 'batas'], ['雑談', 'ざつだん', 'obrolan santai'], ['多様化', 'たようか', 'diversifikasi']],
    questions: [
      ['Apa dampak positif kerja dari rumah menurut teks?', 'Waktu bersama keluarga bertambah', ['Gaji naik', 'Rapat lebih banyak', 'Kantor lebih besar']],
      ['Mengapa sebagian orang justru bekerja lebih lama?', 'Batas kerja dan kehidupan pribadi kabur', ['Atasan memaksa', 'Internet lambat', 'Mereka dibayar per jam']],
      ['Apa itu model "hibrida" dalam teks?', 'Masuk kantor dua atau tiga hari seminggu', ['Bekerja di dua perusahaan', 'Kerja malam dan siang', 'Kerja penuh di kantor']],
    ],
  },
  {
    id: 'n2-shokuhinrosu', level: 'advanced', title: 'Pemborosan makanan', native: '食品ロスの問題',
    sentences: [
      ['日本では、まだ食べられるのに捨てられる食品が年間数百万トンにのぼる。', '', 'Di Jepang, makanan yang masih bisa dimakan tetapi dibuang mencapai jutaan ton per tahun.'],
      ['その原因の一つは、賞味期限に対する消費者の厳しい意識だと言われている。', '', 'Salah satu penyebabnya dikatakan adalah sikap konsumen yang sangat ketat terhadap tanggal kedaluwarsa.'],
      ['賞味期限は「おいしく食べられる期限」であり、過ぎてもすぐに食べられなくなるわけではない。', '', 'Tanggal "best before" adalah batas makanan terasa enak; lewat tanggal itu tidak berarti langsung tidak bisa dimakan.'],
      ['最近では、期限が近い商品を安く売るアプリも登場している。', '', 'Belakangan muncul aplikasi yang menjual murah produk yang mendekati batas tanggal.'],
      ['また、余った食品を福祉施設に寄付する「フードバンク」の活動も広がりつつある。', '', 'Kegiatan "bank makanan" yang menyumbangkan makanan sisa ke lembaga sosial juga mulai meluas.'],
      ['一人一人が買いすぎないことこそ、最も身近な対策であろう。', '', 'Tidak membeli berlebihan secara pribadi mungkin justru merupakan langkah paling dekat dengan kita.'],
    ],
    glossary: [['賞味期限', 'しょうみきげん', 'tanggal best before'], ['意識', 'いしき', 'kesadaran / sikap'], ['寄付する', 'きふする', 'menyumbangkan'], ['対策', 'たいさく', 'langkah penanganan']],
    questions: [
      ['Apa salah satu penyebab pemborosan makanan menurut teks?', 'Sikap konsumen yang ketat pada tanggal kedaluwarsa', ['Kurangnya lahan pertanian', 'Harga makanan murah', 'Restoran yang sedikit']],
      ['Apa fungsi aplikasi yang disebut dalam teks?', 'Menjual murah produk mendekati batas tanggal', ['Menghitung kalori', 'Memesan restoran', 'Mengirim makanan ke luar negeri']],
      ['Menurut penulis, langkah paling dekat dengan kita adalah...', 'Tidak membeli berlebihan', ['Membuat aplikasi', 'Mengubah undang-undang', 'Menutup supermarket']],
    ],
  },
  {
    id: 'n2-chihou', level: 'advanced', title: 'Penuaan dan daerah', native: '高齢化と地方の課題',
    sentences: [
      ['地方の多くの町では、若者が都市へ出て行き、高齢者の割合が高くなっている。', '', 'Di banyak kota daerah, anak muda pergi ke kota besar sehingga proporsi lansia meningkat.'],
      ['バスの本数が減り、車を運転できない高齢者は買い物にも困っている。', '', 'Jumlah bus berkurang, dan lansia yang tidak bisa menyetir kesulitan bahkan untuk berbelanja.'],
      ['そこで、移動販売車が週に数回、村を回るサービスが始まった。', '', 'Maka dimulailah layanan mobil jualan keliling yang berkeliling desa beberapa kali seminggu.'],
      ['この車は商品を届けるだけでなく、住民の安否を確認する役割も果たしている。', '', 'Mobil ini tidak hanya mengantar barang, tetapi juga berperan memeriksa keadaan warga.'],
      ['行政と民間が協力することで、地域の暮らしを支える仕組みが生まれつつある。', '', 'Melalui kerja sama pemerintah dan swasta, mulai lahir sistem yang menopang kehidupan daerah.'],
      ['しかし、担い手不足という根本的な問題は依然として残っている。', '', 'Namun, masalah mendasar berupa kekurangan tenaga pelaksana masih tetap ada.'],
    ],
    glossary: [['割合', 'わりあい', 'proporsi'], ['移動販売', 'いどうはんばい', 'penjualan keliling'], ['安否', 'あんぴ', 'keselamatan / keadaan'], ['担い手', 'にないて', 'pelaksana / penerus']],
    questions: [
      ['Mengapa lansia kesulitan berbelanja?', 'Bus berkurang dan mereka tidak bisa menyetir', ['Toko terlalu mahal', 'Mereka tidak punya uang', 'Toko hanya buka malam']],
      ['Apa peran tambahan mobil jualan keliling?', 'Memeriksa keadaan warga', ['Mengantar anak sekolah', 'Mengumpulkan sampah', 'Menjual tiket bus']],
      ['Masalah apa yang masih tersisa?', 'Kekurangan tenaga pelaksana', ['Kekurangan barang', 'Jalan rusak', 'Terlalu banyak anak muda']],
    ],
  },
  {
    id: 'n2-sns', level: 'advanced', title: 'Media sosial dan anak muda', native: 'SNSと若者',
    sentences: [
      ['今の若者にとって、SNSは友人とつながるための欠かせない道具となっている。', '', 'Bagi anak muda sekarang, media sosial menjadi alat yang tak tergantikan untuk terhubung dengan teman.'],
      ['自分の生活を写真で発信し、多くの「いいね」を集めることに喜びを感じる人も多い。', '', 'Banyak yang merasa senang membagikan kehidupannya lewat foto dan mengumpulkan banyak "suka".'],
      ['ところが、他人の華やかな投稿と比べて、落ち込んでしまうケースも少なくない。', '', 'Namun, tidak sedikit kasus orang menjadi murung karena membandingkan diri dengan unggahan orang lain yang gemerlap.'],
      ['専門家は、画面に映るのはその人の生活のほんの一部にすぎないと指摘する。', '', 'Para ahli menunjukkan bahwa yang tampil di layar hanyalah sebagian kecil kehidupan orang itu.'],
      ['最近は、一定期間SNSから離れる「デジタルデトックス」を試す若者も増えている。', '', 'Belakangan, makin banyak anak muda mencoba "detoks digital" dengan menjauhi media sosial untuk sementara.'],
      ['大切なのは、道具に振り回されず、上手に距離を取ることだろう。', '', 'Yang penting mungkin adalah tidak dikendalikan oleh alat itu dan pandai menjaga jarak.'],
    ],
    glossary: [['発信する', 'はっしんする', 'menyebarkan / membagikan'], ['投稿', 'とうこう', 'unggahan'], ['指摘する', 'してきする', 'menunjukkan / menyoroti'], ['振り回す', 'ふりまわす', 'mengombang-ambingkan']],
    questions: [
      ['Mengapa sebagian anak muda menjadi murung?', 'Membandingkan diri dengan unggahan orang lain', ['Tidak punya ponsel', 'Terlalu sedikit teman', 'Dilarang orang tua']],
      ['Apa yang ditunjukkan para ahli?', 'Yang tampil di layar hanya sebagian kecil kehidupan', ['Media sosial harus dilarang', 'Foto selalu palsu', 'Anak muda tidak butuh teman']],
      ['Apa itu "detoks digital" dalam teks?', 'Menjauhi media sosial untuk sementara', ['Membersihkan ponsel', 'Membeli ponsel baru', 'Menghapus semua foto']],
    ],
  },
  {
    id: 'n2-kankou', level: 'advanced', title: 'Lonjakan wisatawan asing', native: '訪日観光客の増加',
    sentences: [
      ['近年、日本を訪れる外国人観光客の数は過去最高を記録している。', '', 'Dalam beberapa tahun terakhir, jumlah wisatawan asing yang mengunjungi Jepang mencetak rekor tertinggi.'],
      ['観光収入の増加は、地域経済にとって大きな追い風となっている。', '', 'Peningkatan pendapatan pariwisata menjadi dorongan besar bagi ekonomi daerah.'],
      ['その一方で、有名な観光地では混雑やごみの問題が深刻化している。', '', 'Di sisi lain, di tempat wisata terkenal masalah kepadatan dan sampah semakin serius.'],
      ['住民の生活に支障が出る、いわゆる「観光公害」も話題になっている。', '', 'Apa yang disebut "polusi pariwisata" yang mengganggu kehidupan warga juga menjadi perbincangan.'],
      ['対策として、入場料を引き上げたり、観光客を分散させたりする取り組みが行われている。', '', 'Sebagai langkah penanganan, dilakukan upaya seperti menaikkan tiket masuk dan menyebarkan wisatawan.'],
      ['観光と住民の暮らしをどう両立させるかが、今後の課題である。', '', 'Bagaimana menyeimbangkan pariwisata dan kehidupan warga adalah tantangan ke depan.'],
    ],
    glossary: [['記録する', 'きろくする', 'mencatat / mencetak rekor'], ['追い風', 'おいかぜ', 'angin pendorong'], ['支障', 'ししょう', 'gangguan'], ['両立', 'りょうりつ', 'menyeimbangkan dua hal']],
    questions: [
      ['Apa dampak positif peningkatan wisatawan?', 'Mendorong ekonomi daerah', ['Mengurangi sampah', 'Menurunkan harga', 'Mengurangi kepadatan']],
      ['Apa itu "polusi pariwisata" menurut teks?', 'Pariwisata yang mengganggu kehidupan warga', ['Asap dari pesawat', 'Limbah pabrik', 'Kebisingan bandara saja']],
      ['Manakah langkah penanganan yang disebut?', 'Menaikkan tiket masuk', ['Menutup semua bandara', 'Melarang turis asing', 'Membangun lebih banyak hotel']],
    ],
  },
  {
    id: 'n2-suimin', level: 'advanced', title: 'Kurang tidur', native: '睡眠不足の影響',
    sentences: [
      ['日本人の平均睡眠時間は、先進国の中でも特に短いと言われている。', '', 'Rata-rata waktu tidur orang Jepang dikatakan sangat pendek bahkan di antara negara maju.'],
      ['睡眠不足が続くと、集中力が下がり、仕事のミスが増える恐れがある。', '', 'Jika kurang tidur terus berlanjut, konsentrasi menurun dan kesalahan kerja berisiko bertambah.'],
      ['さらに、生活習慣病のリスクを高めることも明らかになっている。', '', 'Lebih lanjut, telah jelas bahwa hal itu juga meningkatkan risiko penyakit gaya hidup.'],
      ['寝る直前までスマートフォンを見る習慣は、眠りの質を下げる原因の一つだ。', '', 'Kebiasaan melihat ponsel sampai tepat sebelum tidur adalah salah satu penyebab turunnya kualitas tidur.'],
      ['専門家は、毎朝同じ時間に起きて日光を浴びることを勧めている。', '', 'Para ahli menganjurkan bangun pada jam yang sama setiap pagi dan terkena sinar matahari.'],
      ['睡眠を削って働くことが美徳とされた時代は、もう終わりつつあるのかもしれない。', '', 'Zaman ketika bekerja dengan mengorbankan tidur dianggap kebajikan mungkin mulai berakhir.'],
    ],
    glossary: [['集中力', 'しゅうちゅうりょく', 'konsentrasi'], ['恐れ', 'おそれ', 'risiko / kekhawatiran'], ['浴びる', 'あびる', 'terkena (sinar/air)'], ['美徳', 'びとく', 'kebajikan']],
    questions: [
      ['Apa akibat kurang tidur menurut teks?', 'Konsentrasi turun dan kesalahan bertambah', ['Nafsu makan hilang', 'Gaji turun', 'Mata menjadi rabun']],
      ['Kebiasaan apa yang menurunkan kualitas tidur?', 'Melihat ponsel tepat sebelum tidur', ['Minum air putih', 'Olahraga pagi', 'Membaca buku kertas']],
      ['Apa saran para ahli?', 'Bangun di jam yang sama dan terkena sinar matahari', ['Tidur siang tiga jam', 'Minum kopi malam hari', 'Tidur lebih larut']],
    ],
  },
  {
    id: 'n2-dokusho', level: 'advanced', title: 'Menurunnya minat membaca', native: '読書離れ',
    sentences: [
      ['一か月に一冊も本を読まない人の割合が、年々増えているという調査がある。', '', 'Ada survei yang menunjukkan proporsi orang yang tidak membaca satu buku pun dalam sebulan terus meningkat.'],
      ['その背景には、スマートフォンで短い記事や動画を見る時間の増加がある。', '', 'Latar belakangnya adalah meningkatnya waktu melihat artikel pendek dan video di ponsel.'],
      ['しかし、読書が減ったからといって、人々が文字を読まなくなったわけではない。', '', 'Namun, berkurangnya membaca buku tidak berarti orang berhenti membaca teks.'],
      ['問題は、長い文章をじっくり読み、深く考える機会が減っていることだ。', '', 'Masalahnya adalah berkurangnya kesempatan membaca tulisan panjang dengan saksama dan berpikir mendalam.'],
      ['ある小学校では、毎朝十分間の読書時間を設けたところ、子どもたちの集中力が高まったという。', '', 'Konon di sebuah SD, setelah diadakan waktu membaca sepuluh menit setiap pagi, konsentrasi anak-anak meningkat.'],
      ['本を読む習慣は、小さな工夫から取り戻せるのではないだろうか。', '', 'Bukankah kebiasaan membaca buku bisa dipulihkan dari upaya-upaya kecil?'],
    ],
    glossary: [['割合', 'わりあい', 'proporsi'], ['背景', 'はいけい', 'latar belakang'], ['じっくり', 'じっくり', 'dengan saksama'], ['取り戻す', 'とりもどす', 'memulihkan']],
    questions: [
      ['Apa latar belakang menurunnya minat membaca?', 'Meningkatnya waktu melihat artikel pendek dan video', ['Buku semakin mahal', 'Perpustakaan tutup', 'Sekolah melarang buku']],
      ['Menurut penulis, apa masalah sebenarnya?', 'Berkurangnya kesempatan membaca panjang dan berpikir mendalam', ['Orang berhenti membaca teks', 'Penulis buku berkurang', 'Anak-anak tidak sekolah']],
      ['Apa hasil waktu membaca pagi di SD?', 'Konsentrasi anak meningkat', ['Nilai matematika turun', 'Anak-anak bosan', 'Perpustakaan penuh']],
    ],
  },
  {
    id: 'n2-cashless', level: 'advanced', title: 'Pembayaran nontunai', native: 'キャッシュレス決済',
    sentences: [
      ['日本は長い間、現金を好む国として知られてきた。', '', 'Jepang lama dikenal sebagai negara yang menyukai uang tunai.'],
      ['しかし最近は、スマートフォンで支払う人が急速に増えている。', '', 'Namun belakangan, orang yang membayar dengan ponsel meningkat pesat.'],
      ['店にとっては、レジの作業が減り、人手不足の解消につながるというメリットがある。', '', 'Bagi toko, ada keuntungan berupa berkurangnya pekerjaan kasir yang membantu mengatasi kekurangan tenaga kerja.'],
      ['一方で、高齢者の中には使い方が分からず、不安を感じる人もいる。', '', 'Di sisi lain, sebagian lansia merasa cemas karena tidak tahu cara menggunakannya.'],
      ['また、災害で停電が起きた場合には、キャッシュレス決済が使えなくなる危険もある。', '', 'Selain itu, ada risiko pembayaran nontunai tidak bisa digunakan jika terjadi pemadaman listrik akibat bencana.'],
      ['便利さと安心をどう両立させるかが問われている。', '', 'Bagaimana menyeimbangkan kepraktisan dan rasa aman kini dipertanyakan.'],
    ],
    glossary: [['現金', 'げんきん', 'uang tunai'], ['人手不足', 'ひとでぶそく', 'kekurangan tenaga kerja'], ['停電', 'ていでん', 'pemadaman listrik'], ['災害', 'さいがい', 'bencana']],
    questions: [
      ['Apa keuntungan nontunai bagi toko?', 'Pekerjaan kasir berkurang', ['Harga barang naik', 'Pelanggan bertambah tua', 'Pajak berkurang']],
      ['Mengapa sebagian lansia merasa cemas?', 'Tidak tahu cara menggunakannya', ['Tidak punya rekening', 'Tokonya jauh', 'Ponselnya mahal']],
      ['Risiko apa yang disebut saat bencana?', 'Tidak bisa dipakai saat listrik padam', ['Uang tunai hilang', 'Toko tutup selamanya', 'Harga naik drastis']],
    ],
  },
  // ---------------------------------------------------------------- N1
  {
    id: 'n1-ai-souzou', level: 'proficiency', title: 'AI dan kreativitas', native: 'AIと創造性',
    sentences: [
      ['文章や絵を生成するAIの登場により、「創造性とは何か」という問いが改めて突きつけられている。', '', 'Dengan munculnya AI yang menghasilkan tulisan dan gambar, pertanyaan "apa itu kreativitas" kembali diajukan dengan tajam.'],
      ['AIは膨大なデータから統計的にもっともらしい組み合わせを導き出すにすぎない、という見方がある。', '', 'Ada pandangan bahwa AI hanyalah menurunkan kombinasi yang secara statistik paling masuk akal dari data yang sangat besar.'],
      ['だが、人間の創作もまた、先人の作品を吸収し組み替える営みであることは否めない。', '', 'Namun, tidak dapat disangkal bahwa karya manusia pun merupakan kegiatan menyerap dan menyusun ulang karya para pendahulu.'],
      ['両者を分けるのは、作品に込められた意図や、経験に裏打ちされた切実さではないだろうか。', '', 'Bukankah yang membedakan keduanya adalah niat yang tertanam dalam karya dan kesungguhan yang didukung pengalaman?'],
      ['もっとも、受け手がその違いを常に見分けられるとは限らない。', '', 'Meski begitu, penerima karya tidak selalu mampu membedakan perbedaan itu.'],
      ['結局のところ、問われているのはAIの能力というより、私たちが作品に何を求めているかなのである。', '', 'Pada akhirnya, yang dipertanyakan bukan kemampuan AI, melainkan apa yang kita cari dari sebuah karya.'],
    ],
    glossary: [['突きつける', 'つきつける', 'menyodorkan dengan tegas'], ['否めない', 'いなめない', 'tak dapat disangkal'], ['切実さ', 'せつじつさ', 'kesungguhan / urgensi batin'], ['見分ける', 'みわける', 'membedakan']],
    questions: [
      ['Menurut satu pandangan, apa yang dilakukan AI?', 'Menurunkan kombinasi yang secara statistik masuk akal', ['Merasakan emosi', 'Meniru satu seniman saja', 'Menciptakan dari nol tanpa data']],
      ['Apa yang menurut penulis membedakan manusia dan AI?', 'Niat dan kesungguhan dari pengalaman', ['Kecepatan membuat karya', 'Jumlah karya', 'Harga karya']],
      ['Apa kesimpulan penulis?', 'Yang dipertanyakan adalah apa yang kita cari dari karya', ['AI harus dilarang', 'AI lebih kreatif dari manusia', 'Seni akan hilang']],
    ],
  },
  {
    id: 'n1-kuuki', level: 'proficiency', title: 'Budaya "membaca suasana"', native: '「空気を読む」文化',
    sentences: [
      ['日本社会では、言葉にされない期待を察して行動する「空気を読む」力が重んじられてきた。', '', 'Dalam masyarakat Jepang, kemampuan "membaca suasana", yaitu bertindak dengan menangkap harapan yang tak diucapkan, telah lama dijunjung.'],
      ['この文化は、無用な衝突を避け、集団の調和を保つうえで一定の役割を果たしてきた。', '', 'Budaya ini berperan dalam menghindari konflik yang tidak perlu dan menjaga harmoni kelompok.'],
      ['しかしその反面、少数意見が表に出にくく、問題の発見が遅れるという弊害も指摘されている。', '', 'Namun sebaliknya, juga ditunjukkan dampak buruknya: pendapat minoritas sulit muncul dan penemuan masalah menjadi terlambat.'],
      ['多様な背景を持つ人々が共に働く現代の職場では、暗黙の了解に頼ることには限界がある。', '', 'Di tempat kerja modern tempat orang dari beragam latar belakang bekerja bersama, bergantung pada pemahaman tersirat ada batasnya.'],
      ['察する力を否定する必要はないが、言葉で確認し合う姿勢もまた不可欠であろう。', '', 'Kemampuan menangkap isyarat tidak perlu disangkal, tetapi sikap saling memastikan dengan kata-kata juga mutlak diperlukan.'],
    ],
    glossary: [['察する', 'さっする', 'menangkap isyarat / menduga'], ['重んじる', 'おもんじる', 'menjunjung'], ['弊害', 'へいがい', 'dampak buruk'], ['暗黙の了解', 'あんもくのりょうかい', 'pemahaman tersirat']],
    questions: [
      ['Apa peran positif budaya ini?', 'Menghindari konflik dan menjaga harmoni', ['Mempercepat keputusan', 'Menaikkan gaji', 'Mengurangi jam kerja']],
      ['Apa dampak buruk yang disebut?', 'Pendapat minoritas sulit muncul', ['Orang terlalu banyak bicara', 'Rapat terlalu pendek', 'Atasan tidak dihormati']],
      ['Apa sikap yang dianjurkan penulis?', 'Juga saling memastikan dengan kata-kata', ['Menghapus budaya membaca suasana', 'Diam saja dalam rapat', 'Mengikuti atasan']],
    ],
  },
  {
    id: 'n1-chihousousei', level: 'proficiency', title: 'Revitalisasi daerah', native: '地方創生の行方',
    sentences: [
      ['人口減少に歯止めをかけるべく、各地で移住者を呼び込む施策が打ち出されている。', '', 'Untuk menahan penurunan populasi, berbagai daerah meluncurkan kebijakan untuk menarik pendatang.'],
      ['住宅の無償提供や子育て支援金など、その内容は年々手厚くなっている。', '', 'Isinya, seperti rumah gratis dan dana bantuan pengasuhan anak, semakin murah hati dari tahun ke tahun.'],
      ['とはいえ、自治体同士が限られた移住希望者を奪い合う構図になっているとの批判も根強い。', '', 'Meski demikian, kritik bahwa pemerintah daerah justru saling berebut calon pendatang yang terbatas tetap kuat.'],
      ['真に求められているのは、一時的な補助ではなく、住民が誇りを持てる仕事と暮らしの基盤である。', '', 'Yang benar-benar dibutuhkan bukan subsidi sementara, melainkan fondasi pekerjaan dan kehidupan yang membuat warga bangga.'],
      ['地元の資源を生かした産業を育てた町では、若い世代の定着率が高いという。', '', 'Di kota yang menumbuhkan industri berbasis sumber daya lokal, tingkat bertahannya generasi muda dikatakan tinggi.'],
    ],
    glossary: [['歯止め', 'はどめ', 'rem / penahan'], ['施策', 'しさく', 'kebijakan / langkah'], ['奪い合う', 'うばいあう', 'saling berebut'], ['定着率', 'ていちゃくりつ', 'tingkat bertahan']],
    questions: [
      ['Apa kritik terhadap kebijakan menarik pendatang?', 'Daerah saling berebut calon pendatang yang terbatas', ['Biayanya terlalu kecil', 'Tidak ada yang tertarik pindah', 'Hanya untuk lansia']],
      ['Menurut penulis, apa yang benar-benar dibutuhkan?', 'Fondasi pekerjaan dan kehidupan yang membanggakan', ['Subsidi yang lebih besar', 'Rumah gratis lebih banyak', 'Jalan tol baru']],
      ['Di kota seperti apa generasi muda cenderung bertahan?', 'Kota yang menumbuhkan industri berbasis sumber daya lokal', ['Kota dengan pusat belanja besar', 'Kota dekat Tokyo', 'Kota dengan pajak rendah']],
    ],
  },
  {
    id: 'n1-gengo', level: 'proficiency', title: 'Punahnya bahasa', native: '消えゆく言語',
    sentences: [
      ['世界には約七千の言語が存在するが、その半数近くが今世紀中に消滅するおそれがあるという。', '', 'Di dunia ada sekitar tujuh ribu bahasa, dan hampir separuhnya dikhawatirkan punah dalam abad ini.'],
      ['言語が失われることは、単に単語や文法が消えることにとどまらない。', '', 'Hilangnya sebuah bahasa tidak terbatas pada lenyapnya kosakata dan tata bahasa.'],
      ['その土地の自然や歴史に根ざした知恵、世界の捉え方そのものが失われるのである。', '', 'Yang hilang adalah kearifan yang berakar pada alam dan sejarah setempat, bahkan cara memandang dunia itu sendiri.'],
      ['日本でも、アイヌ語をはじめ、いくつかの言語が危機的な状況にある。', '', 'Di Jepang pun, beberapa bahasa, dimulai dari bahasa Ainu, berada dalam situasi kritis.'],
      ['近年は、録音資料の整備や学習アプリの開発など、継承に向けた試みが広がっている。', '', 'Belakangan, upaya pewarisan seperti penataan rekaman dan pengembangan aplikasi belajar semakin meluas.'],
      ['言語の多様性を守ることは、人類の知的遺産を守ることに等しい。', '', 'Menjaga keragaman bahasa sama dengan menjaga warisan intelektual umat manusia.'],
    ],
    glossary: [['消滅', 'しょうめつ', 'kepunahan'], ['根ざす', 'ねざす', 'berakar'], ['危機的', 'ききてき', 'kritis'], ['継承', 'けいしょう', 'pewarisan']],
    questions: [
      ['Berapa bahasa yang dikhawatirkan punah dalam abad ini?', 'Hampir separuh dari sekitar tujuh ribu', ['Semua bahasa kecuali Inggris', 'Sekitar seratus', 'Tidak ada']],
      ['Menurut teks, apa yang hilang bersama bahasa?', 'Kearifan lokal dan cara memandang dunia', ['Hanya kosakata', 'Hanya sistem tulisan', 'Nama-nama tempat saja']],
      ['Upaya pewarisan apa yang disebut?', 'Penataan rekaman dan aplikasi belajar', ['Melarang bahasa lain', 'Mewajibkan ujian nasional', 'Menerjemahkan semua buku ke bahasa Inggris']],
    ],
  },
  {
    id: 'n1-kagaku-rinri', level: 'proficiency', title: 'Sains dan etika', native: '科学技術と倫理',
    sentences: [
      ['遺伝子編集技術の進歩は、難病の治療に大きな希望をもたらした。', '', 'Kemajuan teknologi penyuntingan gen membawa harapan besar bagi pengobatan penyakit langka.'],
      ['その一方で、技術的に可能であることと、倫理的に許されることとは必ずしも一致しない。', '', 'Di sisi lain, apa yang mungkin secara teknis tidak selalu sejalan dengan apa yang dibenarkan secara etis.'],
      ['とりわけ、次世代に受け継がれる改変については、慎重な議論が欠かせない。', '', 'Terutama untuk perubahan yang diwariskan ke generasi berikutnya, diskusi yang hati-hati sangat diperlukan.'],
      ['規制が厳しすぎれば研究が停滞し、緩すぎれば取り返しのつかない事態を招きかねない。', '', 'Jika regulasi terlalu ketat penelitian mandek, jika terlalu longgar bisa menimbulkan keadaan yang tak dapat diperbaiki.'],
      ['科学者だけでなく、市民も交えた開かれた対話こそが求められている。', '', 'Yang dibutuhkan justru dialog terbuka yang melibatkan bukan hanya ilmuwan, tetapi juga warga.'],
    ],
    glossary: [['遺伝子編集', 'いでんしへんしゅう', 'penyuntingan gen'], ['必ずしも', 'かならずしも', 'belum tentu / tidak selalu'], ['停滞', 'ていたい', 'mandek'], ['取り返しのつかない', 'とりかえしのつかない', 'tak dapat diperbaiki']],
    questions: [
      ['Apa harapan dari teknologi penyuntingan gen?', 'Pengobatan penyakit langka', ['Membuat makanan murah', 'Menghentikan penuaan total', 'Menggantikan dokter']],
      ['Apa risiko regulasi yang terlalu ketat?', 'Penelitian mandek', ['Keadaan tak terkendali', 'Biaya obat turun', 'Ilmuwan pindah profesi']],
      ['Dialog seperti apa yang dianjurkan?', 'Dialog terbuka yang melibatkan warga', ['Rapat tertutup para ahli', 'Keputusan pemerintah saja', 'Pemungutan suara ilmuwan']],
    ],
  },
  {
    id: 'n1-kyouiku-kakusa', level: 'proficiency', title: 'Kesenjangan pendidikan', native: '教育格差をめぐって',
    sentences: [
      ['家庭の経済状況が子どもの学力や進学に影響を与えることは、多くの調査で示されている。', '', 'Banyak survei menunjukkan bahwa kondisi ekonomi keluarga memengaruhi kemampuan akademik dan kelanjutan sekolah anak.'],
      ['塾や習い事に通えるかどうかで、学校外での学習機会に差が生じるためだ。', '', 'Hal itu karena terjadi perbedaan kesempatan belajar di luar sekolah, tergantung apakah anak bisa ikut bimbel atau kursus.'],
      ['この格差が世代を超えて固定化すれば、社会全体の活力が損なわれかねない。', '', 'Jika kesenjangan ini mengeras lintas generasi, vitalitas masyarakat secara keseluruhan bisa rusak.'],
      ['無料の学習支援教室を運営するNPOの活動は、こうした課題に対する一つの答えである。', '', 'Kegiatan LSM yang menjalankan kelas bimbingan belajar gratis adalah salah satu jawaban atas masalah ini.'],
      ['ただし、民間の善意に頼るだけでは限界があり、公的な制度設計が不可欠だ。', '', 'Namun, hanya bergantung pada niat baik swasta ada batasnya; perancangan sistem publik mutlak diperlukan.'],
    ],
    glossary: [['進学', 'しんがく', 'melanjutkan sekolah'], ['固定化', 'こていか', 'pengerasan / fiksasi'], ['損なう', 'そこなう', 'merusak'], ['善意', 'ぜんい', 'niat baik']],
    questions: [
      ['Mengapa kondisi ekonomi memengaruhi prestasi anak?', 'Ada perbedaan kesempatan belajar di luar sekolah', ['Guru pilih kasih', 'Sekolah negeri tutup', 'Anak kaya lebih pintar sejak lahir']],
      ['Apa risiko jika kesenjangan mengeras lintas generasi?', 'Vitalitas masyarakat rusak', ['Sekolah menjadi gratis', 'Bimbel dilarang', 'Jumlah guru bertambah']],
      ['Apa pendapat penulis tentang peran LSM?', 'Berguna tetapi perlu sistem publik', ['Tidak berguna', 'Cukup tanpa pemerintah', 'Harus dihentikan']],
    ],
  },
  {
    id: 'n1-toshi-kodoku', level: 'proficiency', title: 'Kota dan kesepian', native: '都市と孤独',
    sentences: [
      ['都市には多くの人が暮らしているにもかかわらず、孤独を感じる人は少なくない。', '', 'Meskipun banyak orang tinggal di kota, tidak sedikit yang merasa kesepian.'],
      ['隣に住む人の顔も知らないという生活は、自由である反面、支え合いの網を細くしている。', '', 'Hidup tanpa mengenal wajah tetangga memang bebas, tetapi sekaligus menipiskan jaring saling menopang.'],
      ['孤独は健康に深刻な影響を及ぼし、一日に十五本の煙草を吸うのに匹敵するとの研究もある。', '', 'Ada penelitian yang menyebut kesepian berdampak serius pada kesehatan, setara dengan merokok lima belas batang sehari.'],
      ['そうした中、誰もが気軽に立ち寄れる「居場所」づくりが各地で進められている。', '', 'Dalam situasi itu, pembuatan "tempat singgah" yang bisa didatangi siapa pun dengan santai digalakkan di berbagai tempat.'],
      ['孤独を個人の問題として片付けず、社会の課題として捉え直す視点が求められている。', '', 'Dibutuhkan sudut pandang yang tidak menganggap kesepian sebagai masalah pribadi, melainkan memandangnya ulang sebagai tantangan sosial.'],
    ],
    glossary: [['支え合い', 'ささえあい', 'saling menopang'], ['及ぼす', 'およぼす', 'menimbulkan (dampak)'], ['匹敵する', 'ひってきする', 'setara'], ['居場所', 'いばしょ', 'tempat merasa diterima']],
    questions: [
      ['Kesepian dibandingkan dengan apa dalam penelitian?', 'Merokok lima belas batang sehari', ['Minum kopi setiap hari', 'Kurang olahraga seminggu', 'Makan makanan cepat saji']],
      ['Upaya apa yang digalakkan?', 'Membuat tempat singgah yang mudah didatangi', ['Membangun apartemen besar', 'Melarang tinggal sendiri', 'Menambah jam kerja']],
      ['Sudut pandang apa yang dianjurkan penulis?', 'Kesepian sebagai tantangan sosial', ['Kesepian sebagai kesalahan pribadi', 'Kesepian tidak perlu dibahas', 'Kesepian hanya masalah lansia']],
    ],
  },
  {
    id: 'n1-dentou', level: 'proficiency', title: 'Pewarisan kerajinan tradisional', native: '伝統工芸の継承',
    sentences: [
      ['漆器や和紙などの伝統工芸は、後継者不足により存続の危機に直面している。', '', 'Kerajinan tradisional seperti pernis dan kertas washi menghadapi krisis kelangsungan karena kurangnya penerus.'],
      ['一人前の職人になるには十年以上の修業が必要とされ、その間の収入も安定しない。', '', 'Untuk menjadi perajin yang mandiri dibutuhkan pelatihan lebih dari sepuluh tahun, dan penghasilan selama itu pun tidak stabil.'],
      ['近年、伝統の技を現代の生活に合う製品に生かす若手職人が注目を集めている。', '', 'Belakangan, perajin muda yang memanfaatkan teknik tradisional untuk produk yang sesuai kehidupan modern menarik perhatian.'],
      ['海外の市場に活路を見いだし、高く評価される例も出てきた。', '', 'Muncul pula contoh yang menemukan jalan keluar di pasar luar negeri dan mendapat penilaian tinggi.'],
      ['伝統とは形をそのまま守ることではなく、本質を受け継ぎながら変わり続けることなのかもしれない。', '', 'Tradisi mungkin bukan menjaga bentuk apa adanya, melainkan terus berubah sambil mewarisi esensinya.'],
    ],
    glossary: [['後継者', 'こうけいしゃ', 'penerus'], ['修業', 'しゅぎょう', 'masa latihan / magang'], ['活路', 'かつろ', 'jalan keluar'], ['本質', 'ほんしつ', 'esensi']],
    questions: [
      ['Mengapa kerajinan tradisional terancam?', 'Kurangnya penerus', ['Bahan baku habis', 'Dilarang pemerintah', 'Tidak ada pembeli sama sekali']],
      ['Berapa lama pelatihan untuk menjadi perajin mandiri?', 'Lebih dari sepuluh tahun', ['Satu tahun', 'Tiga bulan', 'Lima tahun tepat']],
      ['Bagaimana penulis memaknai tradisi?', 'Terus berubah sambil mewarisi esensi', ['Menjaga bentuk apa adanya', 'Meninggalkan masa lalu', 'Menjual ke luar negeri saja']],
    ],
  },
];
