import type { PassageSource } from './types';

// Long reading/listening passages for HSK 3-6 (level ids follow the study bank).
// Pinyin is generated from the Hanzi: npm run content:pinyin
export const mandarinPassages: PassageSource[] = [
  // ---------------------------------------------------------------- HSK 3
  {
    id: 'hsk3-banjia', level: 'intermediate', title: 'Pindah rumah', native: '搬家',
    sentences: [
      ['上个月我搬家了，新家离公司很近。', 'Shàng gè yuè wǒ bān jiā le, xīn jiā lí gōng sī hěn jìn.', 'Bulan lalu saya pindah rumah; rumah baru dekat dengan kantor.'],
      ['以前我每天坐一个小时的地铁上班，现在走路十分钟就到了。', 'Yǐ qián wǒ měi tiān zuò yí gè xiǎo shí de dì tiě shàng bān, xiàn zài zǒu lù shí fēn zhōng jiù dào le.', 'Dulu setiap hari saya naik kereta bawah tanah satu jam untuk bekerja, sekarang jalan kaki sepuluh menit sudah sampai.'],
      ['新家虽然不大，但是很干净，而且有一个小阳台。', 'Xīn jiā suī rán bú dà, dàn shì hěn gān jìng, ér qiě yǒu yí gè xiǎo yáng tái.', 'Rumah baru tidak besar, tetapi bersih dan ada balkon kecil.'],
      ['我在阳台上种了一些花，每天早上都给它们浇水。', 'Wǒ zài yáng tái shàng zhǒng le yì xiē huā, měi tiān zǎo shàng dōu gěi tā men jiāo shuǐ.', 'Saya menanam beberapa bunga di balkon dan menyiramnya setiap pagi.'],
      ['邻居们都很热情，楼下的阿姨还送给我一些饺子。', 'Lín jū men dōu hěn rè qíng, lóu xià de ā yí hái sòng gěi wǒ yì xiē jiǎo zǐ.', 'Tetangga-tetangga sangat ramah; bibi di lantai bawah bahkan memberi saya pangsit.'],
      ['我觉得搬家以后，生活变得更轻松了。', 'Wǒ jué de bān jiā yǐ hòu, shēng huó biàn de gèng qīng sōng le.', 'Saya merasa setelah pindah rumah, hidup menjadi lebih santai.'],
    ],
    glossary: [['搬家', 'bānjiā', 'pindah rumah'], ['阳台', 'yángtái', 'balkon'], ['浇水', 'jiāoshuǐ', 'menyiram'], ['邻居', 'línjū', 'tetangga']],
    questions: [
      ['Berapa lama penulis berjalan ke kantor sekarang?', 'Sepuluh menit', ['Satu jam', 'Tiga puluh menit', 'Dua jam']],
      ['Apa yang ditanam penulis di balkon?', 'Bunga', ['Sayur', 'Pohon buah', 'Teh']],
      ['Apa yang diberikan bibi di lantai bawah?', 'Pangsit', ['Bunga', 'Buku', 'Teh']],
    ],
  },
  {
    id: 'hsk3-shengri', level: 'intermediate', title: 'Hadiah ulang tahun', native: '生日礼物',
    sentences: [
      ['下个星期六是我妈妈的五十岁生日。', 'Xià gè xīng qī liù shì wǒ mā ma de wǔ shí suì shēng rì.', 'Sabtu depan adalah ulang tahun ke-50 ibu saya.'],
      ['我和姐姐想给她一个特别的礼物。', 'Wǒ hé jiě jie xiǎng gěi tā yí gè tè bié de lǐ wù.', 'Saya dan kakak perempuan ingin memberinya hadiah istimewa.'],
      ['姐姐说妈妈喜欢唱歌，可以送她一个新的音箱。', 'Jiě jie shuō mā ma xǐ huan chàng gē, kě yǐ sòng tā yí gè xīn de yīn xiāng.', 'Kakak bilang ibu suka menyanyi, jadi bisa diberi speaker baru.'],
      ['我觉得妈妈更需要休息，所以想请她去海边玩两天。', 'Wǒ jué de mā ma gèng xū yào xiū xi, suǒ yǐ xiǎng qǐng tā qù hǎi biān wán liǎng tiān.', 'Saya merasa ibu lebih butuh istirahat, jadi ingin mengajaknya berlibur dua hari ke pantai.'],
      ['最后我们决定两个都送，因为妈妈为我们做了太多事情。', 'Zuì hòu wǒ men jué dìng liǎng gè dōu sòng, yīn wèi mā ma wèi wǒ men zuò le tài duō shì qíng.', 'Akhirnya kami memutuskan memberi keduanya, karena ibu sudah melakukan terlalu banyak hal untuk kami.'],
      ['我希望妈妈那天能过得非常开心。', 'Wǒ xī wàng mā ma nà tiān néng guò de fēi cháng kāi xīn.', 'Saya berharap hari itu ibu bisa sangat bahagia.'],
    ],
    glossary: [['礼物', 'lǐwù', 'hadiah'], ['音箱', 'yīnxiāng', 'speaker'], ['海边', 'hǎibiān', 'tepi laut'], ['决定', 'juédìng', 'memutuskan']],
    questions: [
      ['Ibu penulis berulang tahun ke berapa?', 'Ke-50', ['Ke-40', 'Ke-60', 'Ke-45']],
      ['Mengapa kakak ingin memberi speaker?', 'Ibu suka menyanyi', ['Speaker lama rusak', 'Harganya murah', 'Ibu suka menonton film']],
      ['Apa keputusan akhir mereka?', 'Memberi kedua hadiah', ['Hanya liburan ke pantai', 'Hanya speaker', 'Memberi uang']],
    ],
  },
  {
    id: 'hsk3-tianqi', level: 'intermediate', title: 'Cuaca di kota baru', native: '北方的冬天',
    sentences: [
      ['我是南方人，去年冬天第一次来到北京。', 'Wǒ shì nán fāng rén, qù nián dōng tiān dì yī cì lái dào běi jīng.', 'Saya orang selatan; musim dingin tahun lalu pertama kali datang ke Beijing.'],
      ['北京的冬天非常冷，有时候气温在零下十度。', 'Běi jīng de dōng tiān fēi cháng lěng, yǒu shí hòu qì wēn zài líng xià shí dù.', 'Musim dingin di Beijing sangat dingin, kadang suhunya minus sepuluh derajat.'],
      ['不过，房间里有暖气，所以在家里一点儿也不冷。', 'Bú guò, fáng jiān lǐ yǒu nuǎn qì, suǒ yǐ zài jiā lǐ yì diǎnr yě bù lěng.', 'Namun, di kamar ada pemanas, jadi di rumah sama sekali tidak dingin.'],
      ['我最喜欢下雪的时候，外面的一切都变成了白色。', 'Wǒ zuì xǐ huan xià xuě de shí hòu, wài miàn de yí qiè dōu biàn chéng le bái sè.', 'Saya paling suka saat turun salju, semua di luar berubah menjadi putih.'],
      ['我的朋友教我怎么穿衣服，比如一定要戴帽子和手套。', 'Wǒ de péng yǒu jiào wǒ zěn me chuān yī fu, bǐ rú yī dìng yào dài mào zi hé shǒu tào.', 'Teman saya mengajari cara berpakaian, misalnya harus memakai topi dan sarung tangan.'],
      ['现在我已经习惯了北方的冬天。', 'Xiàn zài wǒ yǐ jīng xí guàn le běi fāng de dōng tiān.', 'Sekarang saya sudah terbiasa dengan musim dingin di utara.'],
    ],
    glossary: [['气温', 'qìwēn', 'suhu'], ['暖气', 'nuǎnqì', 'pemanas ruangan'], ['手套', 'shǒutào', 'sarung tangan'], ['习惯', 'xíguàn', 'terbiasa']],
    questions: [
      ['Mengapa di rumah tidak dingin?', 'Ada pemanas ruangan', ['Rumahnya kecil', 'Jendelanya tertutup', 'Ada banyak orang']],
      ['Kapan penulis paling senang?', 'Saat turun salju', ['Saat musim panas', 'Saat hujan', 'Saat berangin']],
      ['Apa yang diajarkan teman penulis?', 'Cara berpakaian di musim dingin', ['Cara memasak', 'Cara naik kereta', 'Cara berbicara dialek Beijing']],
    ],
  },
  {
    id: 'hsk3-tushuguan', level: 'intermediate', title: 'Di perpustakaan', native: '在图书馆',
    sentences: [
      ['每个周末，我都会去学校的图书馆学习。', 'Měi gè zhōu mò, wǒ dōu huì qù xué xiào de tú shū guǎn xué xí.', 'Setiap akhir pekan, saya pergi belajar ke perpustakaan kampus.'],
      ['图书馆很安静，而且有很多中文书和杂志。', 'Tú shū guǎn hěn ān jìng, ér qiě yǒu hěn duō zhōng wén shū hé zá zhì.', 'Perpustakaan sangat tenang dan ada banyak buku serta majalah berbahasa Mandarin.'],
      ['我一般先复习这个星期学的生词，然后读一本简单的小说。', 'Wǒ yì bān xiān fù xí zhè ge xīng qī xué de shēng cí, rán hòu dú yì běn jiǎn dān de xiǎo shuō.', 'Biasanya saya mengulang kosakata minggu ini dulu, lalu membaca novel sederhana.'],
      ['如果遇到不认识的字，我就查手机上的词典。', 'Rú guǒ yù dào bú rèn shi de zì, wǒ jiù chá shǒu jī shàng de cí diǎn.', 'Jika bertemu karakter yang tidak saya kenal, saya mencarinya di kamus ponsel.'],
      ['中午我会去旁边的咖啡店，吃一个面包，喝一杯咖啡。', 'Zhōng wǔ wǒ huì qù páng biān de kā fēi diàn, chī yí gè miàn bāo, hē yì bēi kā fēi.', 'Siang hari saya pergi ke kafe di sebelah, makan roti dan minum secangkir kopi.'],
      ['在图书馆学习比在宿舍学习效果好多了。', 'Zài tú shū guǎn xué xí bǐ zài sù shè xué xí xiào guǒ hǎo duō le.', 'Belajar di perpustakaan jauh lebih efektif daripada belajar di asrama.'],
    ],
    glossary: [['杂志', 'zázhì', 'majalah'], ['复习', 'fùxí', 'mengulang pelajaran'], ['词典', 'cídiǎn', 'kamus'], ['宿舍', 'sùshè', 'asrama']],
    questions: [
      ['Apa yang pertama kali dilakukan penulis di perpustakaan?', 'Mengulang kosakata minggu ini', ['Membaca koran', 'Menulis surat', 'Menonton video']],
      ['Apa yang dilakukan penulis jika tidak tahu sebuah karakter?', 'Mencari di kamus ponsel', ['Bertanya pada pustakawan', 'Melewatinya', 'Menelepon guru']],
      ['Menurut penulis, di mana belajar lebih efektif?', 'Di perpustakaan', ['Di asrama', 'Di kafe', 'Di kelas']],
    ],
  },
  {
    id: 'hsk3-yundong', level: 'intermediate', title: 'Mulai berolahraga', native: '开始运动',
    sentences: [
      ['以前我工作很忙，几乎不运动，身体也不太好。', 'Yǐ qián wǒ gōng zuò hěn máng, jī hū bú yùn dòng, shēn tǐ yě bú tài hǎo.', 'Dulu saya sangat sibuk bekerja, hampir tidak berolahraga, dan badan kurang sehat.'],
      ['医生告诉我，每天应该运动半个小时。', 'Yī shēng gào sù wǒ, měi tiān yīng gāi yùn dòng bàn gè xiǎo shí.', 'Dokter memberi tahu saya bahwa setiap hari sebaiknya berolahraga setengah jam.'],
      ['所以我开始每天晚上去公园跑步。', 'Suǒ yǐ wǒ kāi shǐ měi tiān wǎn shàng qù gōng yuán pǎo bù.', 'Jadi saya mulai berlari di taman setiap malam.'],
      ['刚开始的时候很累，跑了十分钟就想回家。', 'Gāng kāi shǐ de shí hòu hěn lèi, pǎo le shí fēn zhōng jiù xiǎng huí jiā.', 'Pada awalnya sangat lelah; berlari sepuluh menit saja sudah ingin pulang.'],
      ['后来我认识了几个一起跑步的朋友，就越跑越远了。', 'Hòu lái wǒ rèn shi le jǐ gè yì qǐ pǎo bù de péng yǒu, jiù yuè pǎo yuè yuǎn le.', 'Kemudian saya berkenalan dengan beberapa teman lari, dan saya berlari semakin jauh.'],
      ['现在我不但身体好了，心情也比以前好多了。', 'Xiàn zài wǒ bú dàn shēn tǐ hǎo le, xīn qíng yě bǐ yǐ qián hǎo duō le.', 'Sekarang bukan hanya badan saya lebih sehat, suasana hati pun jauh lebih baik dari sebelumnya.'],
    ],
    glossary: [['几乎', 'jīhū', 'hampir'], ['跑步', 'pǎobù', 'berlari'], ['越…越…', 'yuè... yuè...', 'semakin ... semakin ...'], ['心情', 'xīnqíng', 'suasana hati']],
    questions: [
      ['Berapa lama dokter menyarankan olahraga setiap hari?', 'Setengah jam', ['Satu jam', 'Sepuluh menit', 'Dua jam']],
      ['Di mana penulis berlari?', 'Di taman', ['Di pusat kebugaran', 'Di sekolah', 'Di pantai']],
      ['Apa yang membuat penulis berlari semakin jauh?', 'Berkenalan dengan teman lari', ['Membeli sepatu baru', 'Disuruh dokter', 'Ikut lomba']],
    ],
  },
  {
    id: 'hsk3-dianying', level: 'intermediate', title: 'Menonton film', native: '看电影',
    sentences: [
      ['昨天晚上，我和同事一起去电影院看了一个新电影。', 'Zuó tiān wǎn shàng, wǒ hé tóng shì yì qǐ qù diàn yǐng yuàn kàn le yí gè xīn diàn yǐng.', 'Kemarin malam, saya dan rekan kerja menonton film baru di bioskop.'],
      ['电影讲的是一个小男孩找妈妈的故事。', 'Diàn yǐng jiǎng de shì yí gè xiǎo nán hái zhǎo mā ma de gù shì.', 'Film itu menceritakan kisah seorang anak laki-laki mencari ibunya.'],
      ['电影的音乐很好听，很多地方都让人想哭。', 'Diàn yǐng de yīn yuè hěn hǎo tīng, hěn duō dì fāng dōu ràng rén xiǎng kū.', 'Musik filmnya enak didengar, banyak bagian yang membuat ingin menangis.'],
      ['我的同事哭了好几次，可是我一次也没哭。', 'Wǒ de tóng shì kū le hǎo jǐ cì, kě shì wǒ yí cì yě méi kū.', 'Rekan kerja saya menangis beberapa kali, tetapi saya tidak menangis sekali pun.'],
      ['看完电影，我们去吃了火锅，一边吃一边聊电影。', 'Kàn wán diàn yǐng, wǒ men qù chī le huǒ guō, yì biān chī yì biān liáo diàn yǐng.', 'Setelah menonton, kami makan hotpot sambil mengobrol tentang film.'],
      ['我觉得这个电影值得再看一遍。', 'Wǒ jué de zhè ge diàn yǐng zhí dé zài kàn yí biàn.', 'Saya rasa film ini layak ditonton sekali lagi.'],
    ],
    glossary: [['同事', 'tóngshì', 'rekan kerja'], ['故事', 'gùshì', 'cerita'], ['火锅', 'huǒguō', 'hotpot'], ['值得', 'zhídé', 'layak']],
    questions: [
      ['Tentang apa film itu?', 'Anak laki-laki mencari ibunya', ['Perjalanan ke luar negeri', 'Kisah cinta di sekolah', 'Pertandingan olahraga']],
      ['Siapa yang menangis beberapa kali?', 'Rekan kerja penulis', ['Penulis', 'Anak kecil di bioskop', 'Tidak ada']],
      ['Apa yang mereka lakukan setelah menonton?', 'Makan hotpot sambil mengobrol', ['Pulang langsung', 'Menonton film lain', 'Berbelanja']],
    ],
  },
  {
    id: 'hsk3-lvyou', level: 'intermediate', title: 'Liburan ke Hangzhou', native: '去杭州旅游',
    sentences: [
      ['国庆节的时候，我跟朋友坐高铁去了杭州。', 'Guó qìng jié de shí hòu, wǒ gēn péng yǒu zuò gāo tiě qù le háng zhōu.', 'Saat libur Hari Nasional, saya dan teman naik kereta cepat ke Hangzhou.'],
      ['杭州的西湖非常有名，风景特别漂亮。', 'Háng zhōu de xī hú fēi cháng yǒu míng, fēng jǐng tè bié piào liang.', 'Danau Barat di Hangzhou sangat terkenal, pemandangannya sangat indah.'],
      ['因为是假期，所以到处都是人，我们排了很长时间的队。', 'Yīn wèi shì jià qī, suǒ yǐ dào chù dōu shì rén, wǒ men pái le hěn cháng shí jiān de duì.', 'Karena musim libur, di mana-mana penuh orang, kami antre lama sekali.'],
      ['我们还去了一个茶园，喝了当地有名的龙井茶。', 'Wǒ men hái qù le yí gè chá yuán, hē le dāng dì yǒu míng de lóng jǐng chá.', 'Kami juga pergi ke kebun teh dan minum teh Longjing yang terkenal di sana.'],
      ['虽然有点儿累，但是这次旅游让我很难忘。', 'Suī rán yǒu diǎnr lèi, dàn shì zhè cì lǚ yóu ràng wǒ hěn nán wàng.', 'Meskipun agak lelah, perjalanan ini tak terlupakan bagi saya.'],
      ['下次我想在人少的时候再去一次。', 'Xià cì wǒ xiǎng zài rén shǎo de shí hòu zài qù yí cì.', 'Lain kali saya ingin pergi lagi saat tidak ramai.'],
    ],
    glossary: [['高铁', 'gāotiě', 'kereta cepat'], ['风景', 'fēngjǐng', 'pemandangan'], ['排队', 'páiduì', 'antre'], ['难忘', 'nánwàng', 'tak terlupakan']],
    questions: [
      ['Dengan apa mereka pergi ke Hangzhou?', 'Kereta cepat', ['Pesawat', 'Bus', 'Mobil pribadi']],
      ['Mengapa mereka harus antre lama?', 'Karena musim libur dan ramai', ['Karena hujan', 'Karena tiket habis', 'Karena tempatnya kecil']],
      ['Kapan penulis ingin pergi lagi?', 'Saat tidak ramai', ['Tahun depan saat libur yang sama', 'Musim dingin', 'Tidak ingin kembali']],
    ],
  },
  {
    id: 'hsk3-xuezhongwen', level: 'intermediate', title: 'Belajar bahasa Mandarin', native: '我学中文的经历',
    sentences: [
      ['我学习中文已经两年了。', 'Wǒ xué xí zhōng wén yǐ jīng liǎng nián le.', 'Saya sudah belajar bahasa Mandarin selama dua tahun.'],
      ['刚开始的时候，我觉得声调最难，常常把“买”和“卖”说错。', 'Gāng kāi shǐ de shí hòu, wǒ jué de shēng diào zuì nán, cháng cháng bǎ "mǎi" hé "mài" shuō cuò.', 'Pada awalnya saya merasa nada paling sulit, sering salah mengucapkan "membeli" dan "menjual".'],
      ['后来老师让我每天听中文歌，跟着一起唱。', 'Hòu lái lǎo shī ràng wǒ měi tiān tīng zhōng wén gē, gēn zhe yì qǐ chàng.', 'Kemudian guru menyuruh saya mendengarkan lagu Mandarin setiap hari dan ikut bernyanyi.'],
      ['慢慢地，我的发音越来越好，也敢跟中国人聊天了。', 'Màn màn dì, wǒ de fā yīn yuè lái yuè hǎo, yě gǎn gēn zhōng guó rén liáo tiān le.', 'Perlahan-lahan pelafalan saya semakin baik dan saya berani mengobrol dengan orang Tiongkok.'],
      ['现在我最大的问题是汉字，很多字看起来都差不多。', 'Xiàn zài wǒ zuì dà de wèn tí shì hàn zì, hěn duō zì kàn qǐ lái dōu chà bù duō.', 'Sekarang masalah terbesar saya adalah hanzi; banyak karakter tampak mirip.'],
      ['我打算明年参加HSK四级考试。', 'Wǒ dǎ suàn míng nián cān jiā HSK sì jí kǎo shì.', 'Saya berencana mengikuti ujian HSK level 4 tahun depan.'],
    ],
    glossary: [['声调', 'shēngdiào', 'nada'], ['发音', 'fāyīn', 'pelafalan'], ['敢', 'gǎn', 'berani'], ['打算', 'dǎsuàn', 'berencana']],
    questions: [
      ['Apa yang paling sulit bagi penulis pada awalnya?', 'Nada', ['Hanzi', 'Tata bahasa', 'Kosakata']],
      ['Apa saran guru?', 'Mendengarkan dan menyanyikan lagu Mandarin', ['Menonton berita', 'Menulis hanzi 100 kali', 'Pergi ke Tiongkok']],
      ['Apa masalah terbesar penulis sekarang?', 'Hanzi yang tampak mirip', ['Nada', 'Berbicara dengan orang', 'Mendengarkan']],
    ],
  },
  // ---------------------------------------------------------------- HSK 4
  {
    id: 'hsk4-mianshi', level: 'upper-intermediate', title: 'Pengalaman wawancara kerja', native: '一次难忘的面试',
    sentences: [
      ['毕业以后，我参加了一家大公司的面试。', 'Bì yè yǐ hòu, wǒ cān jiā le yì jiā dà gōng sī de miàn shì.', 'Setelah lulus, saya mengikuti wawancara di sebuah perusahaan besar.'],
      ['面试之前，我在网上查了很多关于这家公司的材料。', 'Miàn shì zhī qián, wǒ zài wǎng shàng chá le hěn duō guān yú zhè jiā gōng sī de cái liào.', 'Sebelum wawancara, saya mencari banyak bahan tentang perusahaan itu di internet.'],
      ['没想到，经理的第一个问题是：“你最大的缺点是什么？”', 'méi xiǎng dào, jīng lǐ de dì yī gè wèn tí shì: "nǐ zuì dà de quē diǎn shì shén me?"', 'Tak disangka, pertanyaan pertama manajer adalah: "Apa kelemahan terbesarmu?"'],
      ['我紧张得说不出话来，过了一会儿才回答说，我有时候太追求完美。', 'Wǒ jǐn zhāng de shuō bù chū huà lái, guò le yí huì er cái huí dá shuō, wǒ yǒu shí hòu tài zhuī qiú wán měi.', 'Saya begitu tegang sampai tidak bisa bicara; setelah beberapa saat baru menjawab bahwa kadang saya terlalu perfeksionis.'],
      ['经理笑了笑，说诚实比完美的答案更重要。', 'Jīng lǐ xiào le xiào, shuō chéng shí bǐ wán měi de dá àn gèng zhòng yào.', 'Manajer tersenyum dan berkata kejujuran lebih penting daripada jawaban yang sempurna.'],
      ['一个星期以后，我收到了公司的通知，他们决定录用我。', 'Yí gè xīng qī yǐ hòu, wǒ shōu dào le gōng sī de tōng zhī, tā men jué dìng lù yòng wǒ.', 'Seminggu kemudian, saya menerima pemberitahuan dari perusahaan bahwa mereka memutuskan menerima saya.'],
      ['这次经历让我明白，面试时表现真实的自己最重要。', 'Zhè cì jīng lì ràng wǒ míng bái, miàn shì shí biǎo xiàn zhēn shí de zì jǐ zuì zhòng yào.', 'Pengalaman ini membuat saya mengerti bahwa saat wawancara, menampilkan diri apa adanya adalah yang terpenting.'],
    ],
    glossary: [['缺点', 'quēdiǎn', 'kelemahan'], ['紧张', 'jǐnzhāng', 'tegang'], ['诚实', 'chéngshí', 'jujur'], ['录用', 'lùyòng', 'menerima (kerja)']],
    questions: [
      ['Apa pertanyaan pertama manajer?', 'Apa kelemahan terbesarmu', ['Berapa gaji yang kamu inginkan', 'Di mana kamu kuliah', 'Mengapa memilih perusahaan ini']],
      ['Apa kata manajer tentang jawaban penulis?', 'Kejujuran lebih penting daripada jawaban sempurna', ['Jawabannya salah', 'Jawabannya terlalu panjang', 'Penulis harus belajar lagi']],
      ['Apa hasil wawancaranya?', 'Penulis diterima', ['Penulis ditolak', 'Harus wawancara ulang', 'Belum ada kabar']],
    ],
  },
  {
    id: 'hsk4-wanggou', level: 'upper-intermediate', title: 'Belanja daring', native: '网上购物',
    sentences: [
      ['现在越来越多的人喜欢在网上购物。', 'Xiàn zài yuè lái yuè duō de rén xǐ huan zài wǎng shàng gòu wù.', 'Sekarang semakin banyak orang suka berbelanja daring.'],
      ['网上购物的好处是方便、选择多，而且价格往往比商店便宜。', 'Wǎng shàng gòu wù de hǎo chù shì fāng biàn, xuǎn zé duō, ér qiě jià gé wǎng wǎng bǐ shāng diàn pián yi.', 'Keuntungan belanja daring adalah praktis, banyak pilihan, dan harganya sering lebih murah daripada toko.'],
      ['不过，网上的照片有时候和真实的商品不太一样。', 'Bú guò, wǎng shàng de zhào piàn yǒu shí hòu hé zhēn shí de shāng pǐn bú tài yí yàng.', 'Namun, foto di internet kadang tidak sama dengan barang aslinya.'],
      ['上个月我买了一件毛衣，收到以后发现颜色比照片深多了。', 'Shàng gè yuè wǒ mǎi le yí jiàn máo yī, shōu dào yǐ hòu fā xiàn yán sè bǐ zhào piàn shēn duō le.', 'Bulan lalu saya membeli sweter; setelah diterima ternyata warnanya jauh lebih gelap dari foto.'],
      ['幸好这家店允许七天内退货，我很快就把钱拿回来了。', 'Xìng hǎo zhè jiā diàn yǔn xǔ qī tiān nèi tuì huò, wǒ hěn kuài jiù bǎ qián ná huí lái le.', 'Untungnya toko ini mengizinkan pengembalian barang dalam tujuh hari, jadi uang saya cepat kembali.'],
      ['所以我建议大家购物前先看看别人的评价。', 'Suǒ yǐ wǒ jiàn yì dà jiā gòu wù qián xiān kàn kàn bié rén de píng jià.', 'Karena itu saya menyarankan semua orang melihat ulasan orang lain sebelum berbelanja.'],
    ],
    glossary: [['购物', 'gòuwù', 'berbelanja'], ['商品', 'shāngpǐn', 'barang dagangan'], ['退货', 'tuìhuò', 'mengembalikan barang'], ['评价', 'píngjià', 'ulasan']],
    questions: [
      ['Apa masalah yang dialami penulis?', 'Warna sweter lebih gelap dari foto', ['Sweter terlalu kecil', 'Barang tidak datang', 'Harganya naik']],
      ['Berapa lama batas pengembalian barang di toko itu?', 'Tujuh hari', ['Tiga hari', 'Satu bulan', 'Tidak bisa dikembalikan']],
      ['Apa saran penulis?', 'Melihat ulasan sebelum membeli', ['Hanya belanja di toko fisik', 'Membeli barang termurah', 'Tidak membeli pakaian daring']],
    ],
  },
  {
    id: 'hsk4-shouji', level: 'upper-intermediate', title: 'Ponsel dan kehidupan', native: '手机改变了生活',
    sentences: [
      ['手机已经成为我们生活中不可缺少的一部分。', 'Shǒu jī yǐ jīng chéng wéi wǒ men shēng huó zhōng bù kě quē shǎo de yí bù fen.', 'Ponsel telah menjadi bagian yang tak terpisahkan dari hidup kita.'],
      ['我们用手机付钱、叫车、点外卖，甚至看病也可以在网上预约。', 'Wǒ men yòng shǒu jī fù qián, jiào chē, diǎn wài mài, shèn zhì kàn bìng yě kě yǐ zài wǎng shàng yù yuē.', 'Kita memakai ponsel untuk membayar, memesan mobil, memesan makanan, bahkan berobat pun bisa dijadwalkan daring.'],
      ['但是，很多人吃饭的时候也一直看手机，很少和家人交流。', 'Dàn shì, hěn duō rén chī fàn de shí hòu yě yì zhí kàn shǒu jī, hěn shǎo hé jiā rén jiāo liú.', 'Tetapi banyak orang terus melihat ponsel bahkan saat makan, dan jarang berkomunikasi dengan keluarga.'],
      ['有调查显示，年轻人平均每天用手机的时间超过五个小时。', 'Yǒu tiáo chá xiǎn shì, nián qīng rén píng jūn měi tiān yòng shǒu jī de shí jiān chāo guò wǔ gè xiǎo shí.', 'Sebuah survei menunjukkan anak muda rata-rata memakai ponsel lebih dari lima jam per hari.'],
      ['为了改变这个习惯，我们家规定吃晚饭时大家都要把手机放在客厅。', 'Wèi le gǎi biàn zhè gè xí guàn, wǒ men jiā guī dìng chī wǎn fàn shí dà jiā dōu yào bǎ shǒu jī fàng zài kè tīng.', 'Untuk mengubah kebiasaan ini, keluarga kami menetapkan bahwa saat makan malam semua ponsel harus ditaruh di ruang tamu.'],
      ['虽然一开始不习惯，但是现在我们聊天的时间多了很多。', 'Suī rán yì kāi shǐ bù xí guàn, dàn shì xiàn zài wǒ men liáo tiān de shí jiān duō le hěn duō.', 'Meskipun awalnya tidak terbiasa, sekarang waktu kami mengobrol jauh lebih banyak.'],
    ],
    glossary: [['不可缺少', 'bùkě quēshǎo', 'tak tergantikan'], ['预约', 'yùyuē', 'membuat janji'], ['调查', 'diàochá', 'survei'], ['规定', 'guīdìng', 'menetapkan aturan']],
    questions: [
      ['Berapa lama rata-rata anak muda memakai ponsel per hari?', 'Lebih dari lima jam', ['Satu jam', 'Dua jam', 'Sepuluh jam']],
      ['Aturan apa yang dibuat keluarga penulis?', 'Ponsel ditaruh di ruang tamu saat makan malam', ['Tidak boleh punya ponsel', 'Ponsel hanya di akhir pekan', 'Ponsel dimatikan pukul sembilan']],
      ['Apa hasil aturan tersebut?', 'Waktu mengobrol bertambah', ['Semua orang marah', 'Tidak ada perubahan', 'Makan malam lebih cepat']],
    ],
  },
  {
    id: 'hsk4-huanbao', level: 'upper-intermediate', title: 'Menjaga lingkungan dari hal kecil', native: '从小事做起保护环境',
    sentences: [
      ['保护环境不只是政府的责任，也是每个人的责任。', 'Bǎo hù huán jìng bù zhǐ shì zhèng fǔ de zé rèn, yě shì měi gè rén de zé rèn.', 'Melindungi lingkungan bukan hanya tanggung jawab pemerintah, tetapi tanggung jawab setiap orang.'],
      ['其实，很多小事都可以减少污染。', 'Qí shí, hěn duō xiǎo shì dōu kě yǐ jiǎn shǎo wū rǎn.', 'Sebenarnya, banyak hal kecil yang bisa mengurangi polusi.'],
      ['比如，出门购物时带上自己的购物袋，就能少用塑料袋。', 'Bǐ rú, chū mén gòu wù shí dài shàng zì jǐ de gòu wù dài, jiù néng shǎo yòng sù liào dài.', 'Misalnya, membawa tas belanja sendiri saat berbelanja dapat mengurangi penggunaan kantong plastik.'],
      ['离开房间时随手关灯，也可以节约不少电。', 'Lí kāi fáng jiān shí suí shǒu guān dēng, yě kě yǐ jié yuē bù shǎo diàn.', 'Mematikan lampu saat meninggalkan ruangan juga bisa menghemat banyak listrik.'],
      ['另外，短距离出行的时候，尽量骑自行车或者走路。', 'Lìng wài, duǎn jù lí chū xíng de shí hòu, jǐn liàng qí zì xíng chē huò zhě zǒu lù.', 'Selain itu, untuk perjalanan jarak pendek, sebisa mungkin naik sepeda atau berjalan kaki.'],
      ['如果每个人都能坚持这些习惯，我们的城市一定会变得更干净。', 'Rú guǒ měi gè rén dōu néng jiān chí zhè xiē xí guàn, wǒ men de chéng shì yí dìng huì biàn de gèng gān jìng.', 'Jika setiap orang bisa konsisten dengan kebiasaan ini, kota kita pasti akan menjadi lebih bersih.'],
    ],
    glossary: [['责任', 'zérèn', 'tanggung jawab'], ['污染', 'wūrǎn', 'polusi'], ['节约', 'jiéyuē', 'menghemat'], ['坚持', 'jiānchí', 'konsisten / bertahan']],
    questions: [
      ['Menurut teks, siapa yang bertanggung jawab melindungi lingkungan?', 'Setiap orang', ['Hanya pemerintah', 'Hanya perusahaan', 'Hanya sekolah']],
      ['Bagaimana cara mengurangi kantong plastik?', 'Membawa tas belanja sendiri', ['Membeli lebih sedikit makanan', 'Belanja daring', 'Membakar plastik']],
      ['Apa saran untuk perjalanan jarak pendek?', 'Naik sepeda atau berjalan kaki', ['Naik taksi', 'Naik mobil pribadi', 'Tidak keluar rumah']],
    ],
  },
  {
    id: 'hsk4-liuxue', level: 'upper-intermediate', title: 'Kuliah di luar negeri', native: '出国留学',
    sentences: [
      ['高中毕业以后，我去上海留学，学习国际贸易。', 'Gāo zhōng bì yè yǐ hòu, wǒ qù shàng hǎi liú xué, xué xí guó jì mào yì.', 'Setelah lulus SMA, saya kuliah di Shanghai dan belajar perdagangan internasional.'],
      ['刚到的时候，上课的内容我只能听懂一半。', 'Gāng dào de shí hòu, shàng kè de nèi róng wǒ zhǐ néng tīng dǒng yí bàn.', 'Saat baru tiba, saya hanya bisa memahami separuh isi kuliah.'],
      ['为了跟上进度，我每天下课后都把老师的课件再看一遍。', 'Wèi le gēn shàng jìn dù, wǒ měi tiān xià kè hòu dōu bǎ lǎo shī de kè jiàn zài kàn yí biàn.', 'Untuk mengikuti kemajuan, setiap selesai kuliah saya membaca ulang materi dosen.'],
      ['我还参加了学校的语言交换活动，认识了很多中国同学。', 'Wǒ hái cān jiā le xué xiào de yǔ yán jiāo huàn huó dòng, rèn shi le hěn duō zhōng guó tóng xué.', 'Saya juga mengikuti kegiatan pertukaran bahasa kampus dan berkenalan dengan banyak mahasiswa Tiongkok.'],
      ['他们帮我练习口语，我教他们印尼语。', 'Tā men bāng wǒ liàn xí kǒu yǔ, wǒ jiào tā men yìn ní yǔ.', 'Mereka membantu saya berlatih berbicara, saya mengajari mereka bahasa Indonesia.'],
      ['留学不仅提高了我的中文水平，还让我学会了独立生活。', 'Liú xué bù jǐn tí gāo le wǒ de zhōng wén shuǐ píng, hái ràng wǒ xué huì le dú lì shēng huó.', 'Kuliah di luar negeri tidak hanya meningkatkan kemampuan Mandarin saya, tetapi juga membuat saya belajar hidup mandiri.'],
    ],
    glossary: [['留学', 'liúxué', 'kuliah di luar negeri'], ['贸易', 'màoyì', 'perdagangan'], ['进度', 'jìndù', 'kemajuan / jadwal pelajaran'], ['独立', 'dúlì', 'mandiri']],
    questions: [
      ['Apa jurusan penulis?', 'Perdagangan internasional', ['Kedokteran', 'Sastra Tiongkok', 'Teknik']],
      ['Apa yang dilakukan penulis setiap selesai kuliah?', 'Membaca ulang materi dosen', ['Bekerja paruh waktu', 'Bermain gim', 'Tidur siang']],
      ['Apa yang penulis ajarkan kepada teman Tiongkok?', 'Bahasa Indonesia', ['Bahasa Inggris', 'Matematika', 'Memasak']],
    ],
  },
  {
    id: 'hsk4-laoren', level: 'upper-intermediate', title: 'Kakek belajar ponsel pintar', native: '爷爷学用智能手机',
    sentences: [
      ['我的爷爷今年七十五岁了，以前他只用老式手机打电话。', 'Wǒ de yé ye jīn nián qī shí wǔ suì le, yǐ qián tā zhǐ yòng lǎo shì shǒu jī dǎ diàn huà.', 'Kakek saya tahun ini berusia 75 tahun; dulu dia hanya memakai ponsel lama untuk menelepon.'],
      ['去年过年的时候，我给他买了一部智能手机。', 'Qù nián guò nián de shí hòu, wǒ gěi tā mǎi le yí bù zhì néng shǒu jī.', 'Saat Tahun Baru Imlek tahun lalu, saya membelikannya sebuah ponsel pintar.'],
      ['一开始，他连怎么打开微信都不知道，总是按错。', 'Yì kāi shǐ, tā lián zěn me dǎ kāi wēi xìn dōu bù zhī dào, zǒng shì àn cuò.', 'Awalnya dia bahkan tidak tahu cara membuka WeChat dan selalu salah tekan.'],
      ['我把每个步骤写在纸上，让他照着练习。', 'Wǒ bǎ měi gè bù zhòu xiě zài zhǐ shàng, ràng tā zhào zhe liàn xí.', 'Saya menuliskan setiap langkah di kertas dan menyuruhnya berlatih mengikutinya.'],
      ['现在爷爷不但会发语音，还学会了在网上看新闻。', 'Xiàn zài yé ye bú dàn huì fā yǔ yīn, hái xué huì le zài wǎng shàng kàn xīn wén.', 'Sekarang kakek bukan hanya bisa mengirim pesan suara, tetapi juga belajar membaca berita daring.'],
      ['他常说：活到老，学到老。', 'Tā cháng shuō: huó dào lǎo, xué dào lǎo.', 'Dia sering berkata: belajar sampai tua.'],
    ],
    glossary: [['智能手机', 'zhìnéng shǒujī', 'ponsel pintar'], ['步骤', 'bùzhòu', 'langkah'], ['照着', 'zhàozhe', 'mengikuti (contoh)'], ['语音', 'yǔyīn', 'pesan suara']],
    questions: [
      ['Kapan penulis membelikan kakek ponsel pintar?', 'Saat Tahun Baru Imlek', ['Saat ulang tahun kakek', 'Saat libur musim panas', 'Minggu lalu']],
      ['Bagaimana penulis membantu kakek belajar?', 'Menulis setiap langkah di kertas', ['Mengirim video tutorial', 'Mendaftarkan kursus', 'Meminta tetangga membantu']],
      ['Apa arti ungkapan kakek?', 'Belajar sampai tua', ['Tua itu indah', 'Hidup harus hemat', 'Teknologi itu sulit']],
    ],
  },
  {
    id: 'hsk4-canting', level: 'upper-intermediate', title: 'Membuka restoran kecil', native: '开一家小饭馆',
    sentences: [
      ['我的表哥辞掉了银行的工作，在老家开了一家小饭馆。', 'Wǒ de biǎo gē cí diào le yín háng de gōng zuò, zài lǎo jiā kāi le yì jiā xiǎo fàn guǎn.', 'Sepupu saya berhenti dari pekerjaan di bank dan membuka restoran kecil di kampung halaman.'],
      ['很多亲戚都反对，认为银行的工作又稳定又体面。', 'Hěn duō qīn qi dōu fǎn duì, rèn wéi yín háng de gōng zuò yòu wěn dìng yòu tǐ miàn.', 'Banyak kerabat menentang, menganggap pekerjaan bank stabil dan terpandang.'],
      ['可是表哥从小就喜欢做菜，他觉得应该做自己感兴趣的事。', 'Kě shì biǎo gē cóng xiǎo jiù xǐ huan zuò cài, tā jué de yīng gāi zuò zì jǐ gǎn xìng qù de shì.', 'Tetapi sejak kecil sepupu saya suka memasak, dan dia merasa harus melakukan hal yang dia minati.'],
      ['开业的前几个月，客人很少，他几乎每天都在亏钱。', 'Kāi yè de qián jǐ gè yuè, kè rén hěn shǎo, tā jī hū měi tiān dōu zài kuī qián.', 'Beberapa bulan pertama setelah buka, pelanggan sangat sedikit dan hampir setiap hari dia merugi.'],
      ['后来他在网上发了做菜的视频，饭馆慢慢有了名气。', 'Hòu lái tā zài wǎng shàng fā le zuò cài de shì pín, fàn guǎn màn màn yǒu le míng qì.', 'Kemudian dia mengunggah video memasak di internet, dan restorannya perlahan menjadi terkenal.'],
      ['现在周末去吃饭，常常需要提前预订。', 'Xiàn zài zhōu mò qù chī fàn, cháng cháng xū yào tí qián yù dìng.', 'Sekarang kalau makan di sana akhir pekan, sering harus memesan tempat lebih dulu.'],
    ],
    glossary: [['辞掉', 'cídiào', 'berhenti (dari pekerjaan)'], ['反对', 'fǎnduì', 'menentang'], ['亏钱', 'kuīqián', 'merugi'], ['名气', 'míngqì', 'ketenaran']],
    questions: [
      ['Apa pekerjaan sepupu sebelumnya?', 'Pegawai bank', ['Koki hotel', 'Guru', 'Dokter']],
      ['Mengapa kerabat menentang?', 'Pekerjaan bank stabil dan terpandang', ['Restoran terlalu mahal', 'Sepupu tidak bisa memasak', 'Kampungnya terlalu kecil']],
      ['Apa yang membuat restoran terkenal?', 'Video memasak di internet', ['Iklan di televisi', 'Harga sangat murah', 'Lokasinya di kota besar']],
    ],
  },
  {
    id: 'hsk4-shuimian', level: 'upper-intermediate', title: 'Tidur yang cukup', native: '睡眠与健康',
    sentences: [
      ['很多上班族晚上加班，回家以后还要看手机，常常到半夜才睡觉。', 'Hěn duō shàng bān zú wǎn shàng jiā bān, huí jiā yǐ hòu hái yào kàn shǒu jī, cháng cháng dào bàn yè cái shuì jiào.', 'Banyak pekerja lembur malam hari, di rumah masih melihat ponsel, sering baru tidur tengah malam.'],
      ['医生提醒，成年人每天最好睡七到八个小时。', 'Yī shēng tí xǐng, chéng nián rén měi tiān zuì hǎo shuì qī dào bā gè xiǎo shí.', 'Dokter mengingatkan, orang dewasa sebaiknya tidur tujuh sampai delapan jam sehari.'],
      ['长期睡眠不足会让人记忆力下降，也容易生病。', 'Cháng qī shuì mián bù zú huì ràng rén jì yì lì xià jiàng, yě róng yì shēng bìng.', 'Kurang tidur jangka panjang membuat daya ingat menurun dan mudah sakit.'],
      ['想要睡得好，睡前一个小时最好不要看手机。', 'Xiǎng yào shuì dé hǎo, shuì qián yí gè xiǎo shí zuì hǎo bú yào kàn shǒu jī.', 'Jika ingin tidur nyenyak, sebaiknya tidak melihat ponsel satu jam sebelum tidur.'],
      ['还可以喝一杯热牛奶，或者听一些轻松的音乐。', 'Hái kě yǐ hē yì bēi rè niú nǎi, huò zhě tīng yì xiē qīng sōng de yīn yuè.', 'Bisa juga minum segelas susu hangat atau mendengarkan musik yang menenangkan.'],
      ['好的睡眠是健康生活的基础。', 'Hǎo de shuì mián shì jiàn kāng shēng huó de jī chǔ.', 'Tidur yang baik adalah dasar hidup sehat.'],
    ],
    glossary: [['上班族', 'shàngbānzú', 'pekerja kantoran'], ['提醒', 'tíxǐng', 'mengingatkan'], ['记忆力', 'jìyì lì', 'daya ingat'], ['基础', 'jīchǔ', 'dasar']],
    questions: [
      ['Berapa jam tidur yang disarankan untuk orang dewasa?', 'Tujuh sampai delapan jam', ['Lima jam', 'Sepuluh jam', 'Enam jam']],
      ['Apa akibat kurang tidur jangka panjang?', 'Daya ingat menurun dan mudah sakit', ['Berat badan turun', 'Mata menjadi merah saja', 'Tidak ada akibat']],
      ['Apa yang sebaiknya dihindari satu jam sebelum tidur?', 'Melihat ponsel', ['Minum susu', 'Mendengarkan musik', 'Membaca buku']],
    ],
  },
  // ---------------------------------------------------------------- HSK 5
  {
    id: 'hsk5-kuaidi', level: 'advanced', title: 'Kurir dan kota', native: '快递小哥',
    sentences: [
      ['在中国的大城市里，快递员几乎随处可见。', 'Zài zhōng guó de dà chéng shì lǐ, kuài dì yuán jī hū suí chù kě jiàn.', 'Di kota-kota besar Tiongkok, kurir paket bisa ditemui hampir di mana-mana.'],
      ['他们每天要送一两百个包裹，从早上七点一直忙到晚上。', 'Tā men měi tiān yào sòng yì liǎng bǎi gè bāo guǒ, cóng zǎo shàng qī diǎn yì zhí máng dào wǎn shàng.', 'Setiap hari mereka mengantar seratus sampai dua ratus paket, sibuk dari pukul tujuh pagi hingga malam.'],
      ['遇到刮风下雨的天气，工作就更加辛苦了。', 'Yù dào guā fēng xià yǔ de tiān qì, gōng zuò jiù gèng jiā xīn kǔ le.', 'Saat cuaca berangin dan hujan, pekerjaan menjadi lebih berat lagi.'],
      ['尽管如此，很多快递员仍然对顾客非常有礼貌。', 'Jǐn guǎn rú cǐ, hěn duō kuài dì yuán réng rán duì gù kè fēi cháng yǒu lǐ mào.', 'Meskipun demikian, banyak kurir tetap sangat sopan kepada pelanggan.'],
      ['近年来，一些社区专门为他们设立了休息站，提供热水和充电服务。', 'Jìn nián lái, yì xiē shè qū zhuān mén wèi tā men shè lì le xiū xi zhàn, tí gōng rè shuǐ hé chōng diàn fú wù.', 'Belakangan, beberapa komunitas khusus mendirikan pos istirahat bagi mereka, menyediakan air panas dan layanan isi daya.'],
      ['这些小小的关怀，让城市显得更有温度。', 'Zhè xiē xiǎo xiǎo de guān huái, ràng chéng shì xiǎn de gèng yǒu wēn dù.', 'Perhatian kecil ini membuat kota terasa lebih hangat.'],
      ['我们在享受便利的同时，也应该尊重每一份劳动。', 'Wǒ men zài xiǎng shòu biàn lì de tóng shí, yě yīng gāi zūn zhòng měi yí fèn láo dòng.', 'Sambil menikmati kemudahan, kita juga harus menghargai setiap jerih payah.'],
    ],
    glossary: [['包裹', 'bāoguǒ', 'paket'], ['辛苦', 'xīnkǔ', 'berat / melelahkan'], ['设立', 'shèlì', 'mendirikan'], ['关怀', 'guānhuái', 'kepedulian']],
    questions: [
      ['Berapa paket yang diantar kurir setiap hari?', 'Seratus sampai dua ratus', ['Sepuluh sampai dua puluh', 'Lima ratus', 'Seribu']],
      ['Apa yang disediakan pos istirahat?', 'Air panas dan layanan isi daya', ['Makanan gratis', 'Tempat tidur', 'Paket asuransi']],
      ['Apa pesan penulis di akhir?', 'Menghargai setiap jerih payah', ['Kurangi belanja daring', 'Kurir harus lebih cepat', 'Kota harus lebih besar']],
    ],
  },
  {
    id: 'hsk5-guzhen', level: 'advanced', title: 'Kota kuno dan pariwisata', native: '古镇的变化',
    sentences: [
      ['十年前，这个古镇还很安静，居民过着简单的生活。', 'Shí nián qián, zhè ge gǔ zhèn hái hěn ān jìng, jū mín guò zhe jiǎn dān de shēng huó.', 'Sepuluh tahun lalu, kota kuno ini masih tenang, warganya menjalani hidup sederhana.'],
      ['自从被一部电视剧拍成外景地以后，游客突然多了起来。', 'Zì cóng bèi yí bù diàn shì jù pāi chéng wài jǐng dì yǐ hòu, yóu kè tū rán duō le qǐ lái.', 'Sejak dijadikan lokasi syuting sebuah drama televisi, wisatawan tiba-tiba bertambah banyak.'],
      ['街上开满了卖纪念品和小吃的商店，房租也涨了好几倍。', 'Jiē shàng kāi mǎn le mài jì niàn pǐn hé xiǎo chī de shāng diàn, fáng zū yě zhǎng le hǎo jǐ bèi.', 'Jalanan dipenuhi toko suvenir dan jajanan, dan sewa rumah naik beberapa kali lipat.'],
      ['许多老居民为了赚钱，把房子租给了外地商人。', 'Xǔ duō lǎo jū mín wèi le zhuàn qián, bǎ fáng zi zū gěi le wài dì shāng rén.', 'Banyak warga lama menyewakan rumahnya kepada pedagang dari luar demi mendapat uang.'],
      ['有人认为旅游业带动了当地经济，也有人担心古镇失去了原来的味道。', 'Yǒu rén rèn wéi lǚ yóu yè dài dòng le dāng dì jīng jì, yě yǒu rén dān xīn gǔ zhèn shī qù le yuán lái de wèi dào.', 'Ada yang berpendapat pariwisata mendorong ekonomi lokal, ada pula yang khawatir kota kuno kehilangan cita rasa aslinya.'],
      ['如何在发展和保护之间找到平衡，是很多古镇面临的共同问题。', 'Rú hé zài fā zhǎn hé bǎo hù zhī jiān zhǎo dào píng héng, shì hěn duō gǔ zhèn miàn lín de gòng tóng wèn tí.', 'Cara menemukan keseimbangan antara pembangunan dan pelestarian adalah masalah bersama banyak kota kuno.'],
    ],
    glossary: [['古镇', 'gǔzhèn', 'kota kuno'], ['外景地', 'wàijǐng dì', 'lokasi syuting'], ['纪念品', 'jìniàn pǐn', 'suvenir'], ['带动', 'dàidòng', 'mendorong / menggerakkan']],
    questions: [
      ['Mengapa wisatawan tiba-tiba bertambah?', 'Kota dijadikan lokasi syuting drama', ['Ada bandara baru', 'Ada festival tahunan', 'Harga hotel turun']],
      ['Apa yang terjadi pada sewa rumah?', 'Naik beberapa kali lipat', ['Turun', 'Tetap sama', 'Dihapus']],
      ['Apa kekhawatiran sebagian orang?', 'Kota kuno kehilangan cita rasa aslinya', ['Wisatawan terlalu sedikit', 'Ekonomi memburuk', 'Tidak ada suvenir']],
    ],
  },
  {
    id: 'hsk5-duanshipin', level: 'advanced', title: 'Video pendek dan perhatian', native: '短视频与注意力',
    sentences: [
      ['短视频平台让人们可以在几十秒内获得大量信息。', 'Duǎn shì pín píng tái ràng rén men kě yǐ zài jǐ shí miǎo nèi huò dé dà liàng xìn xī.', 'Platform video pendek memungkinkan orang memperoleh banyak informasi dalam puluhan detik.'],
      ['很多人本来只想看五分钟，结果一刷就是一个小时。', 'Hěn duō rén běn lái zhǐ xiǎng kàn wǔ fēn zhōng, jié guǒ yì shuā jiù shì yí gè xiǎo shí.', 'Banyak orang awalnya hanya ingin menonton lima menit, akhirnya menggulir selama satu jam.'],
      ['研究发现，长期接触碎片化的内容，可能会降低人的专注能力。', 'Yán jiū fā xiàn, cháng qī jiē chù suì piàn huà de nèi róng, kě néng huì jiàng dī rén de zhuān zhù néng lì.', 'Penelitian menemukan bahwa paparan jangka panjang terhadap konten yang terpotong-potong dapat menurunkan kemampuan fokus.'],
      ['不过，短视频也有积极的一面，比如普及科学知识、传播传统文化。', 'Bú guò, duǎn shì pín yě yǒu jī jí de yí miàn, bǐ rú pǔ jí kē xué zhī shi, chuán bō chuán tǒng wén huà.', 'Namun, video pendek juga punya sisi positif, misalnya menyebarkan pengetahuan sains dan budaya tradisional.'],
      ['关键在于我们如何使用它，而不是被它控制。', 'Guān jiàn zài yú wǒ men rú hé shǐ yòng tā, ér bú shì bèi tā kòng zhì.', 'Kuncinya adalah bagaimana kita menggunakannya, bukan dikendalikan olehnya.'],
      ['给自己设定使用时间，是一个简单而有效的办法。', 'Gěi zì jǐ shè dìng shǐ yòng shí jiān, shì yí gè jiǎn dān ér yǒu xiào de bàn fǎ.', 'Menetapkan batas waktu penggunaan untuk diri sendiri adalah cara yang sederhana dan efektif.'],
    ],
    glossary: [['碎片化', 'suìpiànhuà', 'terpotong-potong / terfragmentasi'], ['专注', 'zhuānzhù', 'fokus'], ['普及', 'pǔjí', 'memasyarakatkan'], ['控制', 'kòngzhì', 'mengendalikan']],
    questions: [
      ['Apa risiko paparan konten terpotong-potong?', 'Kemampuan fokus menurun', ['Mata menjadi rabun', 'Pengetahuan bertambah', 'Tidur lebih nyenyak']],
      ['Manakah sisi positif video pendek?', 'Menyebarkan pengetahuan sains dan budaya', ['Menghemat listrik', 'Mengurangi iklan', 'Menggantikan sekolah']],
      ['Apa cara yang disarankan penulis?', 'Menetapkan batas waktu penggunaan', ['Menghapus semua aplikasi', 'Menonton lebih banyak', 'Hanya menonton malam hari']],
    ],
  },
  {
    id: 'hsk5-yangzhi', level: 'advanced', title: 'Memelihara hewan di kota', native: '城市养宠物',
    sentences: [
      ['随着生活水平的提高，越来越多的城市家庭开始养宠物。', 'Suí zhe shēng huó shuǐ píng de tí gāo, yuè lái yuè duō de chéng shì jiā tíng kāi shǐ yǎng chǒng wù.', 'Seiring meningkatnya taraf hidup, semakin banyak keluarga kota mulai memelihara hewan.'],
      ['对独居的年轻人和老人来说，宠物是重要的陪伴。', 'Duì dú jū de nián qīng rén hé lǎo rén lái shuō, chǒng wù shì zhòng yào de péi bàn.', 'Bagi anak muda dan lansia yang tinggal sendiri, hewan peliharaan adalah teman penting.'],
      ['然而，也有一些主人不注意管理，引起了邻里矛盾。', 'Rán ér, yě yǒu yì xiē zhǔ rén bú zhù yì guǎn lǐ, yǐn qǐ le lín lǐ máo dùn.', 'Namun, ada juga pemilik yang tidak memperhatikan pengelolaan sehingga memicu konflik antartetangga.'],
      ['例如，狗在夜里叫个不停，或者主人不清理宠物的粪便。', 'Lì rú, gǒu zài yè lǐ jiào gè bù tíng, huò zhě zhǔ rén bù qīng lǐ chǒng wù de fèn biàn.', 'Misalnya, anjing menggonggong tanpa henti di malam hari atau pemilik tidak membersihkan kotoran hewannya.'],
      ['为此，不少城市出台了文明养宠的规定，要求遛狗时必须拴绳。', 'Wèi cǐ, bù shǎo chéng shì chū tái le wén míng yǎng chǒng de guī dìng, yāo qiú liú gǒu shí bì xū shuān shéng.', 'Karena itu, banyak kota mengeluarkan aturan memelihara hewan secara beradab, mewajibkan tali saat mengajak anjing berjalan.'],
      ['养宠物是一种快乐，也是一种责任。', 'Yǎng chǒng wù shì yì zhǒng kuài lè, yě shì yì zhǒng zé rèn.', 'Memelihara hewan adalah kebahagiaan, sekaligus tanggung jawab.'],
    ],
    glossary: [['陪伴', 'péibàn', 'teman / menemani'], ['矛盾', 'máodùn', 'konflik'], ['出台', 'chūtái', 'mengeluarkan (kebijakan)'], ['拴绳', 'shuānshéng', 'memasang tali']],
    questions: [
      ['Bagi siapa hewan peliharaan menjadi teman penting?', 'Anak muda dan lansia yang tinggal sendiri', ['Anak sekolah', 'Pedagang', 'Keluarga besar']],
      ['Apa contoh penyebab konflik tetangga?', 'Anjing menggonggong di malam hari', ['Kucing tidur siang', 'Hewan terlalu mahal', 'Dokter hewan jauh']],
      ['Apa yang diwajibkan aturan kota?', 'Memakai tali saat mengajak anjing berjalan', ['Melarang semua hewan', 'Membayar pajak bulanan', 'Hanya boleh memelihara kucing']],
    ],
  },
  {
    id: 'hsk5-gongxiang', level: 'advanced', title: 'Sepeda berbagi', native: '共享单车',
    sentences: [
      ['几年前，共享单车在中国各大城市迅速流行起来。', 'Jǐ nián qián, gòng xiǎng dān chē zài zhōng guó gè dà chéng shì xùn sù liú xíng qǐ lái.', 'Beberapa tahun lalu, sepeda berbagi dengan cepat populer di kota-kota besar Tiongkok.'],
      ['人们只要用手机扫一扫，就能随时骑车出行。', 'Rén men zhǐ yào yòng shǒu jī sǎo yi sǎo, jiù néng suí shí qí chē chū xíng.', 'Orang hanya perlu memindai dengan ponsel untuk bersepeda kapan saja.'],
      ['它解决了“最后一公里”的问题，也减少了汽车尾气的排放。', 'Tā jiě jué le "zuì hòu yì gōng lǐ" de wèn tí, yě jiǎn shǎo le qì chē wěi qì de pái fàng.', 'Ia menyelesaikan masalah "kilometer terakhir" dan juga mengurangi emisi gas buang mobil.'],
      ['但是由于投放过多，一些街道上堆满了无人使用的单车。', 'Dàn shì yóu yú tóu fàng guò duō, yì xiē jiē dào shàng duī mǎn le wú rén shǐ yòng de dān chē.', 'Namun karena ditaruh terlalu banyak, beberapa jalan dipenuhi tumpukan sepeda yang tidak dipakai.'],
      ['后来，政府开始限制数量，并规定了专门的停车区域。', 'Hòu lái, zhèng fǔ kāi shǐ xiàn zhì shù liàng, bìng guī dìng le zhuān mén de tíng chē qū yù.', 'Kemudian pemerintah mulai membatasi jumlahnya dan menetapkan area parkir khusus.'],
      ['共享单车的经历说明，新事物需要合理的管理才能健康发展。', 'Gòng xiǎng dān chē de jīng lì shuō míng, xīn shì wù xū yào hé lǐ de guǎn lǐ cái néng jiàn kāng fā zhǎn.', 'Pengalaman sepeda berbagi menunjukkan bahwa hal baru memerlukan pengelolaan yang tepat agar berkembang sehat.'],
    ],
    glossary: [['迅速', 'xùnsù', 'cepat'], ['排放', 'páifàng', 'emisi'], ['投放', 'tóufàng', 'menyebarkan / menaruh (ke pasar)'], ['区域', 'qūyù', 'area']],
    questions: [
      ['Masalah apa yang diselesaikan sepeda berbagi?', 'Masalah "kilometer terakhir"', ['Kemacetan bandara', 'Kekurangan parkir mobil', 'Harga bensin']],
      ['Apa masalah yang muncul kemudian?', 'Jalan dipenuhi sepeda yang tidak dipakai', ['Tidak ada yang mau naik sepeda', 'Sepeda terlalu mahal', 'Aplikasi sering rusak']],
      ['Apa pelajaran dari pengalaman ini?', 'Hal baru memerlukan pengelolaan yang tepat', ['Sepeda harus dilarang', 'Mobil lebih baik', 'Teknologi selalu gagal']],
    ],
  },
  {
    id: 'hsk5-chengshi-lvhua', level: 'advanced', title: 'Taman atap di kota', native: '屋顶花园',
    sentences: [
      ['城市越来越拥挤，绿地却越来越少。', 'Chéng shì yuè lái yuè yōng jǐ, lǜ dì què yuè lái yuè shǎo.', 'Kota semakin padat, tetapi ruang hijau semakin sedikit.'],
      ['为了改善环境，一些城市鼓励居民在楼顶建设花园。', 'Wèi le gǎi shàn huán jìng, yì xiē chéng shì gǔ lì jū mín zài lóu dǐng jiàn shè huā yuán.', 'Untuk memperbaiki lingkungan, beberapa kota mendorong warga membangun taman di atap gedung.'],
      ['屋顶花园不仅能美化城市，还能在夏天降低室内温度。', 'Wū dǐng huā yuán bù jǐn néng měi huà chéng shì, hái néng zài xià tiān jiàng dī shì nèi wēn dù.', 'Taman atap tidak hanya mempercantik kota, tetapi juga menurunkan suhu dalam ruangan di musim panas.'],
      ['有的社区还在楼顶种菜，让孩子们了解食物是怎么长出来的。', 'Yǒu de shè qū hái zài lóu dǐng zhòng cài, ràng hái zi men liǎo jiě shí wù shì zěn me cháng chū lái de.', 'Sebagian komunitas bahkan menanam sayur di atap, agar anak-anak tahu bagaimana makanan tumbuh.'],
      ['当然，建设屋顶花园需要考虑建筑的承重和防水问题。', 'Dāng rán, jiàn shè wū dǐng huā yuán xū yào kǎo lǜ jiàn zhù de chéng zhòng hé fáng shuǐ wèn tí.', 'Tentu saja, membangun taman atap perlu mempertimbangkan daya tahan beban dan kedap air gedung.'],
      ['只要规划合理，屋顶也能成为城市的“第二片土地”。', 'Zhǐ yào guī huà hé lǐ, wū dǐng yě néng chéng wéi chéng shì de "dì èr piàn tǔ dì".', 'Asalkan direncanakan dengan baik, atap pun dapat menjadi "lahan kedua" kota.'],
    ],
    glossary: [['拥挤', 'yōngjǐ', 'padat'], ['改善', 'gǎishàn', 'memperbaiki'], ['承重', 'chéngzhòng', 'menahan beban'], ['规划', 'guīhuà', 'perencanaan']],
    questions: [
      ['Apa manfaat taman atap di musim panas?', 'Menurunkan suhu dalam ruangan', ['Menambah hujan', 'Mengurangi kebisingan jalan', 'Menaikkan harga rumah']],
      ['Mengapa sebagian komunitas menanam sayur di atap?', 'Agar anak-anak tahu bagaimana makanan tumbuh', ['Untuk dijual ke luar negeri', 'Karena sayur mahal', 'Untuk lomba']],
      ['Apa yang perlu dipertimbangkan saat membangun taman atap?', 'Daya tahan beban dan kedap air', ['Warna bunga', 'Jumlah penghuni', 'Arah angin saja']],
    ],
  },
  {
    id: 'hsk5-zhiyuanzhe', level: 'advanced', title: 'Menjadi relawan pengajar', native: '支教的一年',
    sentences: [
      ['大学毕业后，我报名参加了一年的支教项目，去了西南山区的一所小学。', 'Dà xué bì yè hòu, wǒ bào míng cān jiā le yì nián de zhī jiào xiàng mù, qù le xī nán shān qū de yì suǒ xiǎo xué.', 'Setelah lulus kuliah, saya mendaftar program mengajar sukarela setahun di sebuah SD di pegunungan barat daya.'],
      ['学校条件很艰苦，冬天教室里没有暖气，孩子们的手常常冻得通红。', 'Xué xiào tiáo jiàn hěn jiān kǔ, dōng tiān jiào shì lǐ méi yǒu nuǎn qì, hái zi men de shǒu cháng cháng dòng dé tōng hóng.', 'Kondisi sekolah sangat sulit; musim dingin tidak ada pemanas di kelas, tangan anak-anak sering merah membeku.'],
      ['可是他们的眼睛里充满了对知识的渴望。', 'Kě shì tā men de yǎn jīng lǐ chōng mǎn le duì zhī shi de kě wàng.', 'Tetapi mata mereka penuh dengan kerinduan akan pengetahuan.'],
      ['我教他们英语和音乐，他们教我当地的山歌。', 'Wǒ jiào tā men yīng yǔ hé yīn yuè, tā men jiào wǒ dāng dì de shān gē.', 'Saya mengajari mereka bahasa Inggris dan musik, mereka mengajari saya lagu gunung setempat.'],
      ['离开的那天，全班同学送给我一本亲手做的相册。', 'Lí kāi de nà tiān, quán bān tóng xué sòng gěi wǒ yì běn qīn shǒu zuò de xiàng cè.', 'Pada hari saya pergi, seluruh kelas memberi saya album foto buatan tangan.'],
      ['这一年让我明白，教育不只是传授知识，更是点亮希望。', 'Zhè yì nián ràng wǒ míng bái, jiào yù bù zhǐ shì chuán shòu zhī shi, gèng shì diǎn liàng xī wàng.', 'Tahun ini membuat saya mengerti bahwa pendidikan bukan hanya mentransfer pengetahuan, tetapi terlebih menyalakan harapan.'],
    ],
    glossary: [['支教', 'zhījiào', 'mengajar sukarela'], ['艰苦', 'jiānkǔ', 'serba sulit'], ['渴望', 'kěwàng', 'kerinduan / hasrat'], ['传授', 'chuánshòu', 'mengajarkan / mewariskan']],
    questions: [
      ['Di mana penulis mengajar?', 'SD di pegunungan barat daya', ['Universitas di Beijing', 'SMA di Shanghai', 'Sekolah internasional']],
      ['Apa yang diajarkan anak-anak kepada penulis?', 'Lagu gunung setempat', ['Bahasa Inggris', 'Cara bertani', 'Memasak']],
      ['Apa hadiah dari kelas saat penulis pergi?', 'Album foto buatan tangan', ['Surat dari kepala sekolah', 'Syal rajutan', 'Teh lokal']],
    ],
  },
  {
    id: 'hsk5-yuedu', level: 'advanced', title: 'Mengapa membaca buku kertas', native: '纸质书的价值',
    sentences: [
      ['电子书方便携带，一个阅读器可以装下几千本书。', 'Diàn zǐ shū fāng biàn xié dài, yí gè yuè dú qì kě yǐ zhuāng xià jǐ qiān běn shū.', 'Buku elektronik mudah dibawa; satu e-reader bisa memuat ribuan buku.'],
      ['尽管如此，仍有不少人坚持阅读纸质书。', 'Jǐn guǎn rú cǐ, réng yǒu bù shǎo rén jiān chí yuè dú zhǐ zhì shū.', 'Meskipun demikian, masih banyak orang yang tetap membaca buku kertas.'],
      ['他们认为，翻动书页的感觉能让人更加专注。', 'Tā men rèn wéi, fān dòng shū yè de gǎn jué néng ràng rén gèng jiā zhuān zhù.', 'Mereka berpendapat sensasi membalik halaman membuat orang lebih fokus.'],
      ['一些研究也表明，读纸质书时，读者对内容的记忆更深刻。', 'Yì xiē yán jiū yě biǎo míng, dú zhǐ zhì shū shí, dú zhě duì nèi róng de jì yì gèng shēn kè.', 'Beberapa penelitian juga menunjukkan bahwa saat membaca buku kertas, ingatan pembaca terhadap isi lebih mendalam.'],
      ['此外，在书上做笔记、画重点，也是一种独特的乐趣。', 'Cǐ wài, zài shū shàng zuò bǐ jì, huà zhòng diǎn, yě shì yì zhǒng dú tè de lè qù.', 'Selain itu, mencatat dan menandai hal penting di buku juga merupakan kesenangan tersendiri.'],
      ['电子书和纸质书各有优点，我们可以根据需要灵活选择。', 'Diàn zǐ shū hé zhǐ zhì shū gè yǒu yōu diǎn, wǒ men kě yǐ gēn jù xū yào líng huó xuǎn zé.', 'Buku elektronik dan buku kertas masing-masing punya kelebihan; kita bisa memilih secara fleksibel sesuai kebutuhan.'],
    ],
    glossary: [['携带', 'xiédài', 'membawa'], ['纸质书', 'zhǐzhì shū', 'buku kertas'], ['深刻', 'shēnkè', 'mendalam'], ['乐趣', 'lèqù', 'kesenangan']],
    questions: [
      ['Apa kelebihan buku elektronik menurut teks?', 'Mudah dibawa dan memuat ribuan buku', ['Lebih murah dari buku kertas', 'Lebih baik untuk mata', 'Tidak perlu listrik']],
      ['Apa hasil penelitian yang disebut?', 'Ingatan terhadap isi lebih mendalam saat membaca buku kertas', ['Membaca buku elektronik lebih cepat', 'Tidak ada perbedaan', 'Buku kertas membuat mengantuk']],
      ['Apa kesimpulan penulis?', 'Memilih secara fleksibel sesuai kebutuhan', ['Hanya membaca buku kertas', 'Buku kertas akan hilang', 'Buku elektronik lebih unggul']],
    ],
  },
  // ---------------------------------------------------------------- HSK 6
  {
    id: 'hsk6-jianzhu', level: 'proficiency', title: 'Arsitektur dan ingatan kota', native: '建筑与城市记忆',
    sentences: [
      ['一座城市的老建筑，往往承载着几代人的共同记忆。', 'Yí zuò chéng shì de lǎo jiàn zhù, wǎng wǎng chéng zài zhe jǐ dài rén de gòng tóng jì yì.', 'Bangunan tua di sebuah kota sering memikul ingatan bersama beberapa generasi.'],
      ['在快速城市化的过程中，不少老建筑因“影响市容”而被拆除。', 'Zài kuài sù chéng shì huà de guò chéng zhōng, bù shǎo lǎo jiàn zhù yīn "yǐng xiǎng shì róng" ér bèi chāi chú.', 'Dalam proses urbanisasi yang cepat, tidak sedikit bangunan tua dibongkar karena dianggap "merusak wajah kota".'],
      ['取而代之的高楼虽然整齐气派，却常常千城一面，缺乏个性。', 'Qǔ ér dài zhī de gāo lóu suī rán zhěng qí qì pài, què cháng cháng qiān chéng yí miàn, quē fá gè xìng.', 'Gedung-gedung tinggi penggantinya memang rapi dan megah, tetapi sering seragam di semua kota dan kurang berkarakter.'],
      ['近年来，“微改造”的理念逐渐受到重视，即在保留原有格局的前提下进行有限的更新。', 'Jìn nián lái, "wēi gǎi zào" de lǐ niàn zhú jiàn shòu dào zhòng shì, jí zài bǎo liú yuán yǒu gé jú de qián tí xià jìn xíng yǒu xiàn de gēng xīn.', 'Belakangan, konsep "renovasi mikro" makin diperhatikan, yakni pembaruan terbatas dengan tetap mempertahankan tata ruang asli.'],
      ['这种做法既改善了居民的生活条件，又延续了街区的历史脉络。', 'Zhè zhǒng zuò fǎ jì gǎi shàn le jū mín de shēng huó tiáo jiàn, yòu yán xù le jiē qū de lì shǐ mài luò.', 'Cara ini memperbaiki kondisi hidup warga sekaligus melanjutkan alur sejarah kawasan.'],
      ['可见，城市发展不必以牺牲记忆为代价。', 'Kě jiàn, chéng shì fā zhǎn bú bì yǐ xī shēng jì yì wèi dài jià.', 'Terlihat bahwa pembangunan kota tidak harus mengorbankan ingatan.'],
    ],
    glossary: [['承载', 'chéngzài', 'memikul / memuat'], ['拆除', 'chāichú', 'membongkar'], ['千城一面', 'qiānchéng yímiàn', 'semua kota tampak seragam'], ['脉络', 'màiluò', 'alur / jalinan']],
    questions: [
      ['Mengapa banyak bangunan tua dibongkar?', 'Dianggap merusak wajah kota', ['Terlalu mahal dirawat', 'Rawan gempa', 'Pemiliknya pindah']],
      ['Apa kritik terhadap gedung tinggi pengganti?', 'Seragam dan kurang berkarakter', ['Terlalu rendah', 'Tidak rapi', 'Terlalu murah']],
      ['Apa itu "renovasi mikro"?', 'Pembaruan terbatas dengan mempertahankan tata ruang asli', ['Membongkar seluruh kawasan', 'Membangun gedung mini', 'Mengecat ulang saja']],
    ],
  },
  {
    id: 'hsk6-fanyi', level: 'proficiency', title: 'Seni menerjemahkan', native: '翻译的艺术',
    sentences: [
      ['严复提出的“信、达、雅”，至今仍是讨论翻译标准时绕不开的话题。', 'Yán fù tí chū de "xìn, dá, yǎ", zhì jīn réng shì tǎo lùn fān yì biāo zhǔn shí rào bù kāi de huà tí.', '"Setia, lancar, elegan" yang dikemukakan Yan Fu hingga kini masih menjadi topik yang tak terhindarkan saat membahas standar terjemahan.'],
      ['“信”要求忠实于原文，“达”要求译文通顺，“雅”则追求语言的优美。', '"xìn" yāo qiú zhōng shí yú yuán wén, "dá" yāo qiú yì wén tōng shùn, "yǎ" zé zhuī qiú yǔ yán de yōu měi.', '"Setia" menuntut kesetiaan pada teks asli, "lancar" menuntut terjemahan yang mengalir, dan "elegan" mengejar keindahan bahasa.'],
      ['然而，三者之间常常存在张力，难以兼顾。', 'Rán ér, sān zhě zhī jiān cháng cháng cún zài zhāng lì, nán yǐ jiān gù.', 'Namun, ketiganya sering saling tarik dan sulit dipenuhi sekaligus.'],
      ['比如诗歌翻译，过分拘泥于字面，往往会丢失原作的韵味。', 'Bǐ rú shī gē fān yì, guò fèn jū nì yú zì miàn, wǎng wǎng huì diū shī yuán zuò de yùn wèi.', 'Misalnya dalam menerjemahkan puisi, terlalu terpaku pada kata harfiah sering menghilangkan cita rasa karya asli.'],
      ['因此，有人说翻译是一种“戴着镣铐的舞蹈”。', 'Yīn cǐ, yǒu rén shuō fān yì shì yì zhǒng "dài zhe liào kào de wǔ dǎo".', 'Karena itu, ada yang mengatakan terjemahan adalah "tarian dengan belenggu".'],
      ['优秀的译者不仅精通两种语言，更要深刻理解两种文化。', 'Yōu xiù de yì zhě bù jǐn jīng tōng liǎng zhǒng yǔ yán, gèng yào shēn kè lǐ jiě liǎng zhǒng wén huà.', 'Penerjemah unggul tidak hanya menguasai dua bahasa, tetapi terlebih memahami dua budaya secara mendalam.'],
    ],
    glossary: [['忠实', 'zhōngshí', 'setia'], ['通顺', 'tōngshùn', 'lancar'], ['兼顾', 'jiāngù', 'memenuhi sekaligus'], ['拘泥', 'jūnì', 'terpaku kaku']],
    questions: [
      ['Apa arti “达” dalam teks?', 'Terjemahan yang mengalir', ['Setia pada teks asli', 'Keindahan bahasa', 'Kecepatan menerjemahkan']],
      ['Apa risiko terlalu terpaku pada kata harfiah dalam puisi?', 'Cita rasa karya asli hilang', ['Terjemahan terlalu panjang', 'Pembaca bosan', 'Rima menjadi sempurna']],
      ['Apa syarat penerjemah unggul menurut penulis?', 'Memahami dua budaya secara mendalam', ['Menguasai banyak bahasa', 'Menerjemahkan dengan cepat', 'Memakai mesin penerjemah']],
    ],
  },
  {
    id: 'hsk6-kexue-jiangzuo', level: 'proficiency', title: 'Kuliah umum tentang otak', native: '大脑的可塑性',
    sentences: [
      ['过去人们普遍认为，成年人的大脑结构基本固定，难以改变。', 'Guò qù rén men pǔ biàn rèn wéi, chéng nián rén de dà nǎo jié gòu jī běn gù dìng, nán yǐ gǎi biàn.', 'Dulu orang umumnya percaya bahwa struktur otak orang dewasa pada dasarnya tetap dan sulit berubah.'],
      ['然而，神经科学的研究表明，大脑在一生中都具有可塑性。', 'Rán ér, shén jīng kē xué de yán jiū biǎo míng, dà nǎo zài yì shēng zhōng dōu jù yǒu kě sù xìng.', 'Namun, penelitian neurosains menunjukkan bahwa otak memiliki plastisitas sepanjang hidup.'],
      ['学习一门新语言或一种乐器，都会促使神经元之间形成新的连接。', 'Xué xí yì mén xīn yǔ yán huò yì zhǒng yuè qì, dōu huì cù shǐ shén jīng yuán zhī jiān xíng chéng xīn de lián jiē.', 'Mempelajari bahasa baru atau alat musik mendorong terbentuknya koneksi baru antarneuron.'],
      ['研究者曾对伦敦出租车司机进行扫描，发现他们负责空间记忆的区域明显较大。', 'Yán jiū zhě céng duì lún dūn chū zū chē sī jī jìn xíng sǎo miáo, fā xiàn tā men fù zé kōng jiān jì yì de qū yù míng xiǎn jiào dà.', 'Peneliti pernah memindai sopir taksi London dan menemukan area otak untuk memori spasial mereka jelas lebih besar.'],
      ['这一发现颠覆了“年纪大了就学不会”的成见。', 'Zhè yì fā xiàn diān fù le "nián jì dà le jiù xué bú huì" de chéng jiàn.', 'Temuan ini menjungkirbalikkan anggapan bahwa "sudah tua tidak bisa belajar".'],
      ['当然，可塑性并非无限，持续而有针对性的练习才是关键。', 'Dāng rán, kě sù xìng bìng fēi wú xiàn, chí xù ér yǒu zhēn duì xìng de liàn xí cái shì guān jiàn.', 'Tentu saja, plastisitas tidak tak terbatas; latihan yang konsisten dan terarah adalah kuncinya.'],
    ],
    glossary: [['可塑性', 'kěsùxìng', 'plastisitas'], ['神经元', 'shénjīng yuán', 'neuron'], ['颠覆', 'diānfù', 'menjungkirbalikkan'], ['成见', 'chéngjiàn', 'prasangka / anggapan tetap']],
    questions: [
      ['Apa yang ditunjukkan penelitian neurosains?', 'Otak memiliki plastisitas sepanjang hidup', ['Otak berhenti berkembang di usia 20', 'Hanya anak-anak yang bisa belajar', 'Otak tidak bisa berubah']],
      ['Apa temuan pada sopir taksi London?', 'Area memori spasial mereka lebih besar', ['Mereka lebih cepat lelah', 'Mereka tidak bisa belajar bahasa', 'Otak mereka lebih kecil']],
      ['Apa kunci menurut penulis?', 'Latihan yang konsisten dan terarah', ['Tidur lebih lama', 'Minum suplemen', 'Belajar hanya saat muda']],
    ],
  },
  {
    id: 'hsk6-gongzuo-yiyi', level: 'proficiency', title: 'Makna bekerja', native: '工作的意义',
    sentences: [
      ['对于上一代人而言，一份稳定的工作往往意味着一生的保障。', 'Duì yú shàng yí dài rén ér yán, yí fèn wěn dìng de gōng zuò wǎng wǎng yì wèi zhe yì shēng de bǎo zhàng.', 'Bagi generasi sebelumnya, pekerjaan yang stabil sering berarti jaminan seumur hidup.'],
      ['而如今不少年轻人更看重工作能否带来成就感和个人成长。', 'Ér rú jīn bù shǎo nián qīng rén gèng kàn zhòng gōng zuò néng fǒu dài lái chéng jiù gǎn hé gè rén chéng zhǎng.', 'Sedangkan kini banyak anak muda lebih mementingkan apakah pekerjaan memberi rasa pencapaian dan pertumbuhan pribadi.'],
      ['这种观念的转变，与社会经济条件的改善密不可分。', 'Zhè zhǒng guān niàn de zhuǎn biàn, yǔ shè huì jīng jì tiáo jiàn de gǎi shàn mì bù kě fēn.', 'Pergeseran pandangan ini tidak terlepas dari membaiknya kondisi sosial ekonomi.'],
      ['但也有人批评，过分追求“热爱”可能让人频繁跳槽，难以积累专业经验。', 'Dàn yě yǒu rén pī píng, guò fēn zhuī qiú "rè ài" kě néng ràng rén pín fán tiào cáo, nán yǐ jī lěi zhuān yè jīng yàn.', 'Namun ada juga kritik bahwa terlalu mengejar "passion" bisa membuat orang sering berpindah kerja dan sulit mengumpulkan pengalaman profesional.'],
      ['事实上，热爱往往不是预先存在的，而是在投入和钻研中逐渐培养出来的。', 'Shì shí shàng, rè ài wǎng wǎng bú shì yù xiān cún zài de, ér shì zài tóu rù hé zuān yán zhōng zhú jiàn péi yǎng chū lái de.', 'Faktanya, passion sering tidak sudah ada sebelumnya, melainkan tumbuh perlahan melalui dedikasi dan pendalaman.'],
      ['找到工作的意义，或许需要的不是等待，而是行动。', 'Zhǎo dào gōng zuò de yì yì, huò xǔ xū yào de bú shì děng dài, ér shì xíng dòng.', 'Menemukan makna bekerja mungkin tidak membutuhkan penantian, tetapi tindakan.'],
    ],
    glossary: [['保障', 'bǎozhàng', 'jaminan'], ['成就感', 'chéngjiùgǎn', 'rasa pencapaian'], ['跳槽', 'tiàocáo', 'berpindah kerja'], ['钻研', 'zuānyán', 'mendalami']],
    questions: [
      ['Apa yang lebih dipentingkan anak muda sekarang?', 'Rasa pencapaian dan pertumbuhan pribadi', ['Jaminan seumur hidup', 'Dekat dengan rumah', 'Jam kerja pendek saja']],
      ['Apa kritik terhadap terlalu mengejar passion?', 'Sering berpindah kerja dan sulit mengumpulkan pengalaman', ['Gaji menjadi terlalu tinggi', 'Tidak punya waktu luang', 'Terlalu lama di satu perusahaan']],
      ['Menurut penulis, bagaimana passion terbentuk?', 'Tumbuh melalui dedikasi dan pendalaman', ['Sudah ada sejak lahir', 'Datang dari gaji besar', 'Ditentukan orang tua']],
    ],
  },
  {
    id: 'hsk6-chuantong-jieri', level: 'proficiency', title: 'Perayaan tradisional di era modern', native: '传统节日的现代意义',
    sentences: [
      ['春节期间，数亿人踏上回乡之路，形成了世界上规模最大的人口流动。', 'Chūn jié qī jiān, shù yì rén tà shàng huí xiāng zhī lù, xíng chéng le shì jiè shàng guī mó zuì dà de rén kǒu liú dòng.', 'Selama Tahun Baru Imlek, ratusan juta orang pulang kampung, membentuk arus perpindahan penduduk terbesar di dunia.'],
      ['在人们越来越分散的今天，传统节日为家庭团聚提供了难得的契机。', 'Zài rén men yuè lái yuè fēn sàn de jīn tiān, chuán tǒng jié rì wèi jiā tíng tuán jù tí gōng le nán dé de qì jī.', 'Di masa kini ketika orang semakin tersebar, perayaan tradisional memberi kesempatan langka untuk berkumpul dengan keluarga.'],
      ['不过，部分习俗也在悄然改变，例如微信红包逐渐取代了纸质红包。', 'Bú guò, bù fēn xí sú yě zài qiǎo rán gǎi biàn, lì rú wēi xìn hóng bāo zhú jiàn qǔ dài le zhǐ zhì hóng bāo.', 'Namun, sebagian adat diam-diam berubah, misalnya angpau WeChat perlahan menggantikan angpau kertas.'],
      ['有人担心，节日的仪式感正在被商业化和数字化冲淡。', 'Yǒu rén dān xīn, jié rì de yí shì gǎn zhèng zài bèi shāng yè huà hé shù zì huà chōng dàn.', 'Ada yang khawatir makna ritual perayaan sedang dilunturkan oleh komersialisasi dan digitalisasi.'],
      ['也有人认为，形式的变化并不妨碍其核心——亲情与祝福——的传承。', 'Yě yǒu rén rèn wéi, xíng shì de biàn huà bìng bù fáng ài qí hé xīn -- qīn qíng yǔ zhù fú -- de chuán chéng.', 'Ada pula yang berpendapat perubahan bentuk tidak menghalangi pewarisan intinya, yaitu kasih keluarga dan doa baik.'],
      ['传统之所以有生命力，正是因为它能够不断适应新的时代。', 'Chuán tǒng zhī suǒ yǐ yǒu shēng mìng lì, zhèng shì yīn wèi tā néng gòu bú duàn shì yìng xīn de shí dài.', 'Tradisi memiliki daya hidup justru karena ia mampu terus beradaptasi dengan zaman baru.'],
    ],
    glossary: [['团聚', 'tuánjù', 'berkumpul kembali'], ['契机', 'qìjī', 'kesempatan'], ['悄然', 'qiǎorán', 'diam-diam'], ['冲淡', 'chōngdàn', 'melunturkan']],
    questions: [
      ['Apa contoh adat yang berubah?', 'Angpau WeChat menggantikan angpau kertas', ['Makan malam bersama dihapus', 'Libur dipersingkat', 'Kembang api dilarang']],
      ['Apa kekhawatiran sebagian orang?', 'Makna ritual luntur oleh komersialisasi dan digitalisasi', ['Orang tidak mau pulang kampung', 'Harga tiket turun', 'Perayaan terlalu panjang']],
      ['Mengapa tradisi memiliki daya hidup menurut penulis?', 'Mampu terus beradaptasi dengan zaman', ['Tidak pernah berubah', 'Didukung undang-undang', 'Hanya dirayakan orang tua']],
    ],
  },
  {
    id: 'hsk6-shuju-yinsi', level: 'proficiency', title: 'Data dan privasi', native: '数据时代的隐私',
    sentences: [
      ['我们在享受个性化推荐带来的便利时，往往忽视了自己交出的个人数据。', 'Wǒ men zài xiǎng shòu gè xìng huà tuī jiàn dài lái de biàn lì shí, wǎng wǎng hū shì le zì jǐ jiāo chū de gè rén shù jù.', 'Saat menikmati kemudahan rekomendasi personal, kita sering mengabaikan data pribadi yang kita serahkan.'],
      ['从浏览记录到位置信息，这些数据被收集、分析，甚至被转卖。', 'Cóng liú lǎn jì lù dào wèi zhì xìn xī, zhè xiē shù jù bèi shōu jí, fēn xī, shèn zhì bèi zhuǎn mài.', 'Dari riwayat penjelajahan hingga informasi lokasi, data ini dikumpulkan, dianalisis, bahkan dijual kembali.'],
      ['更值得警惕的是，许多用户在不知情的情况下就点击了“同意”。', 'Gèng zhí dé jǐng tì de shì, xǔ duō yòng hù zài bù zhī qíng de qíng kuàng xià jiù diǎn jī le "tóng yì".', 'Yang lebih patut diwaspadai, banyak pengguna menekan "setuju" tanpa mengetahui isinya.'],
      ['近年来出台的个人信息保护法，明确了企业收集数据时必须遵循“最小必要”原则。', 'Jìn nián lái chū tái de gè rén xìn xī bǎo hù fǎ, míng què le qǐ yè shōu jí shù jù shí bì xū zūn xún "zuì xiǎo bì yào" yuán zé.', 'Undang-undang perlindungan informasi pribadi yang dikeluarkan belakangan menegaskan bahwa perusahaan harus mengikuti prinsip "minimal yang diperlukan" saat mengumpulkan data.'],
      ['然而，法律的落实还有赖于监管力度和公众意识的提升。', 'Rán ér, fǎ lǜ de luò shí hái yǒu lài yú jiān guǎn lì dù hé gōng zhòng yì shí de tí shēng.', 'Namun, penerapan hukum masih bergantung pada ketegasan pengawasan dan meningkatnya kesadaran publik.'],
      ['在数据时代，保护隐私既是权利，也是一种能力。', 'Zài shù jù shí dài, bǎo hù yǐn sī jì shì quán lì, yě shì yì zhǒng néng lì.', 'Di era data, melindungi privasi adalah hak sekaligus kemampuan.'],
    ],
    glossary: [['个性化', 'gèxìnghuà', 'personalisasi'], ['警惕', 'jǐngtì', 'waspada'], ['遵循', 'zūnxún', 'mengikuti / mematuhi'], ['落实', 'luòshí', 'penerapan']],
    questions: [
      ['Apa yang lebih patut diwaspadai menurut teks?', 'Pengguna menekan "setuju" tanpa mengetahui isinya', ['Harga aplikasi naik', 'Rekomendasi yang tidak akurat', 'Ponsel cepat rusak']],
      ['Prinsip apa yang ditegaskan undang-undang?', '"Minimal yang diperlukan"', ['"Sebanyak mungkin"', '"Gratis untuk semua"', '"Data milik perusahaan"']],
      ['Apa pandangan penulis tentang privasi?', 'Hak sekaligus kemampuan', ['Sudah tidak penting', 'Hanya urusan pemerintah', 'Hanya untuk orang terkenal']],
    ],
  },
  {
    id: 'hsk6-nongye', level: 'proficiency', title: 'Pertanian cerdas', native: '智慧农业',
    sentences: [
      ['在一些农村，无人机正在代替农民喷洒农药。', 'Zài yì xiē nóng cūn, wú rén jī zhèng zài dài tì nóng mín pēn sǎ nóng yào.', 'Di beberapa desa, drone sedang menggantikan petani menyemprotkan pestisida.'],
      ['通过传感器，农民可以实时了解土壤的湿度和养分状况。', 'Tōng guò chuán gǎn qì, nóng mín kě yǐ shí shí liǎo jiě tǔ rǎng de shī dù hé yǎng fèn zhuàng kuàng.', 'Melalui sensor, petani dapat mengetahui kelembapan dan kondisi nutrisi tanah secara real time.'],
      ['这种精准管理不仅提高了产量，还减少了化肥和水资源的浪费。', 'Zhè zhǒng jīng zhǔn guǎn lǐ bù jǐn tí gāo le chǎn liàng, hái jiǎn shǎo le huà féi hé shuǐ zī yuán de làng fèi.', 'Pengelolaan presisi ini tidak hanya meningkatkan hasil panen, tetapi juga mengurangi pemborosan pupuk dan air.'],
      ['然而，高昂的设备成本让许多小农户望而却步。', 'Rán ér, gāo áng de shè bèi chéng běn ràng xǔ duō xiǎo nóng hù wàng ér què bù.', 'Namun, biaya peralatan yang tinggi membuat banyak petani kecil mundur.'],
      ['为此，一些地方推出了设备共享和技术培训服务。', 'Wèi cǐ, yì xiē dì fāng tuī chū le shè bèi gòng xiǎng hé jì shù péi xùn fú wù.', 'Karena itu, beberapa daerah meluncurkan layanan berbagi peralatan dan pelatihan teknis.'],
      ['科技只有真正惠及普通农民，才能推动农业的转型升级。', 'Kē jì zhǐ yǒu zhēn zhèng huì jí pǔ tōng nóng mín, cái néng tuī dòng nóng yè de zhuǎn xíng shēng jí.', 'Teknologi hanya dapat mendorong transformasi pertanian jika benar-benar bermanfaat bagi petani biasa.'],
    ],
    glossary: [['喷洒', 'pēnsǎ', 'menyemprotkan'], ['传感器', 'chuángǎnqì', 'sensor'], ['精准', 'jīngzhǔn', 'presisi'], ['望而却步', 'wàng\'ér quèbù', 'mundur karena gentar']],
    questions: [
      ['Apa yang dilakukan drone di desa?', 'Menyemprotkan pestisida', ['Mengantar hasil panen', 'Menanam benih padi', 'Memotret wisatawan']],
      ['Mengapa banyak petani kecil mundur?', 'Biaya peralatan tinggi', ['Tidak ada internet', 'Tanahnya terlalu luas', 'Dilarang pemerintah']],
      ['Apa solusi yang diluncurkan beberapa daerah?', 'Berbagi peralatan dan pelatihan teknis', ['Subsidi pupuk saja', 'Menjual tanah petani', 'Mengimpor beras']],
    ],
  },
  {
    id: 'hsk6-kexue-jingshen', level: 'proficiency', title: 'Semangat ilmiah', native: '科学精神',
    sentences: [
      ['科学精神的核心在于怀疑与求证。', 'Kē xué jīng shén de hé xīn zài yú huái yí yǔ qiú zhèng.', 'Inti semangat ilmiah terletak pada keraguan dan pembuktian.'],
      ['一个结论再权威，只要出现新的证据，就应当接受重新检验。', 'Yí gè jié lùn zài quán wēi, zhǐ yào chū xiàn xīn de zhèng jù, jiù yīng dāng jiē shòu chóng xīn jiǎn yàn.', 'Seotoritatif apa pun sebuah kesimpulan, begitu ada bukti baru, ia harus diuji ulang.'],
      ['历史上，许多重大突破正是源于对“常识”的质疑。', 'Lì shǐ shàng, xǔ duō chóng dà tū pò zhèng shì yuán yú duì "cháng shí" de zhì yí.', 'Dalam sejarah, banyak terobosan besar justru berasal dari mempertanyakan "akal sehat".'],
      ['然而，怀疑并不等于否定一切，更不等于相信毫无根据的说法。', 'Rán ér, huái yí bìng bù děng yú fǒu dìng yí qiè, gèng bù děng yú xiāng xìn háo wú gēn jù de shuō fǎ.', 'Namun, meragukan bukan berarti menyangkal segalanya, apalagi mempercayai klaim tanpa dasar.'],
      ['在信息泛滥的时代，普通人同样需要具备基本的科学素养。', 'Zài xìn xī fàn làn de shí dài, pǔ tōng rén tóng yàng xū yào jù bèi jī běn de kē xué sù yǎng.', 'Di era banjir informasi, orang biasa juga perlu memiliki literasi sains dasar.'],
      ['学会区分事实与观点，是抵御谣言最有效的方式。', 'Xué huì qū fēn shì shí yǔ guān diǎn, shì dǐ yù yáo yán zuì yǒu xiào de fāng shì.', 'Belajar membedakan fakta dan opini adalah cara paling efektif menangkal rumor.'],
    ],
    glossary: [['求证', 'qiúzhèng', 'mencari bukti'], ['权威', 'quánwēi', 'otoritatif'], ['质疑', 'zhìyí', 'mempertanyakan'], ['泛滥', 'fànlàn', 'membanjir']],
    questions: [
      ['Apa inti semangat ilmiah menurut teks?', 'Keraguan dan pembuktian', ['Kepatuhan pada otoritas', 'Kecepatan publikasi', 'Hafalan teori']],
      ['Apa yang harus terjadi jika ada bukti baru?', 'Kesimpulan diuji ulang', ['Bukti diabaikan', 'Kesimpulan dipertahankan', 'Peneliti diganti']],
      ['Apa cara paling efektif menangkal rumor?', 'Membedakan fakta dan opini', ['Tidak membaca berita', 'Mempercayai otoritas', 'Menyebarkan lebih cepat']],
    ],
  },
];
