import type { PassageSource } from './types';

// Reading/listening passages for HSK 1-2 and HSK 7-9 (level ids follow the
// Mandarin course). Pinyin is generated from the Hanzi: npm run content:pinyin
export const mandarinPassagesBasic: PassageSource[] = [
  // ---------------------------------------------------------------- HSK 1
  {
    id: 'hsk1-wodejia', level: 'beginner', title: 'Keluarga saya', native: '我的家',
    sentences: [
      ['我叫王明，我是中国人。', 'Wǒ jiào wáng míng, wǒ shì zhōng guó rén.', 'Nama saya Wang Ming, saya orang Tiongkok.'],
      ['我家有四口人。', 'Wǒ jiā yǒu sì kǒu rén.', 'Keluarga saya ada empat orang.'],
      ['爸爸是医生，妈妈是老师。', 'Bà ba shì yī shēng, mā ma shì lǎo shī.', 'Ayah seorang dokter, ibu seorang guru.'],
      ['我有一个妹妹，她今年六岁。', 'Wǒ yǒu yí gè mèi mei, tā jīn nián liù suì.', 'Saya punya satu adik perempuan; tahun ini dia berumur enam tahun.'],
      ['我们都很喜欢猫。', 'Wǒ men dōu hěn xǐ huan māo.', 'Kami semua suka kucing.'],
      ['我爱我的家。', 'Wǒ ài wǒ de jiā.', 'Saya mencintai keluarga saya.'],
    ],
    glossary: [['医生', 'yīshēng', 'dokter'], ['老师', 'lǎoshī', 'guru'], ['妹妹', 'mèimei', 'adik perempuan'], ['喜欢', 'xǐhuan', 'suka']],
    questions: [
      ['Apa pekerjaan ayah Wang Ming?', 'Dokter', ['Guru', 'Sopir', 'Koki']],
      ['Berapa umur adik perempuannya?', 'Enam tahun', ['Lima tahun', 'Delapan tahun', 'Sepuluh tahun']],
      ['Hewan apa yang mereka sukai?', 'Kucing', ['Anjing', 'Burung', 'Ikan']],
    ],
  },
  {
    id: 'hsk1-xuexiao', level: 'beginner', title: 'Di sekolah', native: '在学校',
    sentences: [
      ['今天是星期一，我去学校。', 'Jīn tiān shì xīng qī yī, wǒ qù xué xiào.', 'Hari ini hari Senin, saya pergi ke sekolah.'],
      ['我坐出租车去学校。', 'Wǒ zuò chū zū chē qù xué xiào.', 'Saya naik taksi ke sekolah.'],
      ['我们八点上课。', 'Wǒ men bā diǎn shàng kè.', 'Kami mulai pelajaran jam delapan.'],
      ['中午我和同学在学校吃饭。', 'Zhōng wǔ wǒ hé tóng xué zài xué xiào chī fàn.', 'Siang hari saya makan di sekolah bersama teman sekelas.'],
      ['下午我们学习汉字。', 'Xià wǔ wǒ men xué xí hàn zì.', 'Sore hari kami belajar hanzi.'],
      ['我很喜欢学习汉字。', 'Wǒ hěn xǐ huan xué xí hàn zì.', 'Saya sangat suka belajar hanzi.'],
    ],
    glossary: [['学校', 'xuéxiào', 'sekolah'], ['出租车', 'chūzū chē', 'taksi'], ['同学', 'tóngxué', 'teman sekelas'], ['汉字', 'hànzì', 'hanzi']],
    questions: [
      ['Hari apa hari ini?', 'Senin', ['Selasa', 'Minggu', 'Jumat']],
      ['Naik apa penulis ke sekolah?', 'Taksi', ['Bus', 'Sepeda', 'Jalan kaki']],
      ['Apa yang dipelajari pada sore hari?', 'Hanzi', ['Matematika', 'Bahasa Inggris', 'Musik']],
    ],
  },
  {
    id: 'hsk1-maidongxi', level: 'beginner', title: 'Berbelanja', native: '买东西',
    sentences: [
      ['昨天下午我和妈妈去商店买东西。', 'Zuó tiān xià wǔ wǒ hé mā ma qù shāng diàn mǎi dōng xī.', 'Kemarin sore saya dan ibu pergi berbelanja ke toko.'],
      ['妈妈想买一些水果。', 'Mā ma xiǎng mǎi yì xiē shuǐ guǒ.', 'Ibu ingin membeli buah.'],
      ['苹果很好，一斤十块钱。', 'Píng guǒ hěn hǎo, yì jīn shí kuài qián.', 'Apelnya bagus, satu jin sepuluh yuan.'],
      ['我们买了三斤苹果。', 'Wǒ men mǎi le sān jīn píng guǒ.', 'Kami membeli tiga jin apel.'],
      ['我还买了一本书和一个杯子。', 'Wǒ hái mǎi le yì běn shū hé yí gè bēi zi.', 'Saya juga membeli sebuah buku dan sebuah gelas.'],
      ['我们是坐出租车回家的。', 'Wǒ men shì zuò chū zū chē huí jiā de.', 'Kami pulang naik taksi.'],
    ],
    glossary: [['商店', 'shāngdiàn', 'toko'], ['水果', 'shuǐguǒ', 'buah'], ['苹果', 'píngguǒ', 'apel'], ['杯子', 'bēizi', 'gelas']],
    questions: [
      ['Kapan mereka berbelanja?', 'Kemarin sore', ['Pagi ini', 'Hari Minggu', 'Kemarin malam']],
      ['Berapa harga satu jin apel?', 'Sepuluh yuan', ['Lima yuan', 'Dua puluh yuan', 'Tiga yuan']],
      ['Apa lagi yang dibeli penulis?', 'Buku dan gelas', ['Baju', 'Teh', 'Kursi']],
    ],
  },
  {
    id: 'hsk1-tianqi', level: 'beginner', title: 'Cuaca hari ini', native: '今天的天气',
    sentences: [
      ['今天天气很好，不冷也不热。', 'Jīn tiān tiān qì hěn hǎo, bù lěng yě bú rè.', 'Cuaca hari ini bagus, tidak dingin dan tidak panas.'],
      ['我想和朋友去看电影。', 'Wǒ xiǎng hé péng yǒu qù kàn diàn yǐng.', 'Saya ingin menonton film bersama teman.'],
      ['朋友说明天会下雨。', 'Péng yǒu shuō míng tiān huì xià yǔ.', 'Teman bilang besok akan hujan.'],
      ['我们今天下午去吧。', 'Wǒ men jīn tiān xià wǔ qù ba.', 'Ayo kita pergi sore ini.'],
      ['电影三点开始，我们两点半在电影院前面见。', 'Diàn yǐng sān diǎn kāi shǐ, wǒ men liǎng diǎn bàn zài diàn yǐng yuàn qián miàn jiàn.', 'Filmnya mulai jam tiga; kami bertemu di depan bioskop jam setengah tiga.'],
      ['看完电影，我们去饭馆吃饭。', 'Kàn wán diàn yǐng, wǒ men qù fàn guǎn chī fàn.', 'Setelah menonton film, kami makan di restoran.'],
    ],
    glossary: [['天气', 'tiānqì', 'cuaca'], ['电影', 'diànyǐng', 'film'], ['下雨', 'xiàyǔ', 'hujan'], ['饭馆', 'fànguǎn', 'restoran']],
    questions: [
      ['Bagaimana cuaca hari ini?', 'Tidak dingin dan tidak panas', ['Sangat panas', 'Hujan', 'Sangat dingin']],
      ['Kapan akan hujan?', 'Besok', ['Hari ini', 'Sore ini', 'Lusa']],
      ['Jam berapa filmnya mulai?', 'Jam tiga', ['Jam setengah tiga', 'Jam dua', 'Jam empat']],
    ],
  },
  {
    id: 'hsk1-dadianhua', level: 'beginner', title: 'Menelepon', native: '打电话',
    sentences: [
      ['喂，你好！请问李老师在家吗？', 'Wèi, nǐ hǎo! qǐng wèn lǐ lǎo shī zài jiā ma?', 'Halo! Permisi, apakah Guru Li ada di rumah?'],
      ['她不在家，她去医院了。', 'Tā bú zài jiā, tā qù yī yuàn le.', 'Dia tidak di rumah, dia pergi ke rumah sakit.'],
      ['她什么时候回来？', 'Tā shén me shí hòu huí lái?', 'Kapan dia kembali?'],
      ['她下午四点回来。', 'Tā xià wǔ sì diǎn huí lái.', 'Dia kembali jam empat sore.'],
      ['好的，谢谢你！我下午再打电话。', 'Hǎo de, xiè xiè nǐ! wǒ xià wǔ zài dǎ diàn huà.', 'Baik, terima kasih! Saya akan menelepon lagi sore nanti.'],
      ['不客气，再见！', 'Bú kè qì, zài jiàn!', 'Sama-sama, sampai jumpa!'],
    ],
    glossary: [['打电话', 'dǎdiànhuà', 'menelepon'], ['医院', 'yīyuàn', 'rumah sakit'], ['回来', 'huílái', 'kembali'], ['不客气', 'búkèqì', 'sama-sama']],
    questions: [
      ['Siapa yang dicari penelepon?', 'Guru Li', ['Dokter Wang', 'Ibu', 'Teman sekelas']],
      ['Di mana Guru Li sekarang?', 'Di rumah sakit', ['Di sekolah', 'Di toko', 'Di restoran']],
      ['Jam berapa Guru Li kembali?', 'Jam empat sore', ['Jam dua siang', 'Jam enam sore', 'Jam sembilan pagi']],
    ],
  },
  {
    id: 'hsk1-xingqiliu', level: 'beginner', title: 'Hari Sabtu', native: '星期六',
    sentences: [
      ['星期六上午我在家看书。', 'Xīng qī liù shàng wǔ wǒ zài jiā kàn shū.', 'Sabtu pagi saya membaca buku di rumah.'],
      ['中午我做饭，我做的米饭很好吃。', 'Zhōng wǔ wǒ zuò fàn, wǒ zuò de mǐ fàn hěn hǎo chī.', 'Siang hari saya memasak; nasi buatan saya enak.'],
      ['下午我去朋友家。', 'Xià wǔ wǒ qù péng yǒu jiā.', 'Sore hari saya pergi ke rumah teman.'],
      ['我们喝茶，说汉语。', 'Wǒ men hē chá, shuō hàn yǔ.', 'Kami minum teh dan berbicara bahasa Mandarin.'],
      ['他的狗很小，很漂亮。', 'Tā de gǒu hěn xiǎo, hěn piào liang.', 'Anjingnya kecil dan cantik.'],
      ['晚上九点我回家了。', 'Wǎn shàng jiǔ diǎn wǒ huí jiā le.', 'Jam sembilan malam saya pulang.'],
    ],
    glossary: [['上午', 'shàngwǔ', 'pagi'], ['做饭', 'zuòfàn', 'memasak'], ['喝茶', 'hēchá', 'minum teh'], ['漂亮', 'piàoliang', 'cantik']],
    questions: [
      ['Apa yang dilakukan penulis Sabtu pagi?', 'Membaca buku', ['Memasak', 'Menonton TV', 'Tidur']],
      ['Apa yang mereka minum?', 'Teh', ['Kopi', 'Susu', 'Air putih']],
      ['Seperti apa anjing teman penulis?', 'Kecil dan cantik', ['Besar dan hitam', 'Tua dan galak', 'Besar dan cantik']],
    ],
  },
  {
    id: 'hsk1-fanguan', level: 'beginner', title: 'Di restoran', native: '在饭馆',
    sentences: [
      ['服务员：你好，你们几个人？', 'Fú wù yuán: nǐ hǎo, nǐ men jǐ gè rén?', 'Pelayan: Halo, kalian berapa orang?'],
      ['我们三个人。', 'Wǒ men sān gè rén.', 'Kami tiga orang.'],
      ['服务员：你们想吃什么？', 'Fú wù yuán: nǐ men xiǎng chī shén me?', 'Pelayan: Kalian mau makan apa?'],
      ['我们要三碗米饭、一个鱼和一些菜。', 'Wǒ men yào sān wǎn mǐ fàn, yí gè yú hé yì xiē cài.', 'Kami mau tiga mangkuk nasi, satu ikan, dan beberapa sayur.'],
      ['服务员：喝什么？', 'Fú wù yuán: hē shén me?', 'Pelayan: Minumnya apa?'],
      ['我们都喝茶。谢谢！', 'Wǒ men dōu hē chá. xiè xiè!', 'Kami semua minum teh. Terima kasih!'],
    ],
    glossary: [['服务员', 'fúwù yuán', 'pelayan'], ['米饭', 'mǐfàn', 'nasi'], ['菜', 'cài', 'sayur/lauk'], ['喝', 'hē', 'minum']],
    questions: [
      ['Berapa orang tamunya?', 'Tiga', ['Dua', 'Empat', 'Lima']],
      ['Apa yang dipesan?', 'Nasi, ikan, dan sayur', ['Mi dan ayam', 'Pangsit', 'Roti']],
      ['Apa minumannya?', 'Teh', ['Kopi', 'Air putih', 'Jus']],
    ],
  },
  {
    id: 'hsk1-pengyou', level: 'beginner', title: 'Teman saya', native: '我的朋友',
    sentences: [
      ['我有一个好朋友，他叫大卫。', 'Wǒ yǒu yí gè hǎo péng yǒu, tā jiào dà wèi.', 'Saya punya seorang sahabat, namanya David.'],
      ['大卫是美国人，他住在北京。', 'Dà wèi shì měi guó rén, tā zhù zài běi jīng.', 'David orang Amerika, dia tinggal di Beijing.'],
      ['他会说汉语，也会写很多汉字。', 'Tā huì shuō hàn yǔ, yě huì xiě hěn duō hàn zì.', 'Dia bisa berbicara Mandarin dan juga bisa menulis banyak hanzi.'],
      ['他在北京的一个大学学习。', 'Tā zài běi jīng de yí gè dà xué xué xí.', 'Dia belajar di sebuah universitas di Beijing.'],
      ['我们常常一起吃饭，看电影。', 'Wǒ men cháng cháng yì qǐ chī fàn, kàn diàn yǐng.', 'Kami sering makan dan menonton film bersama.'],
      ['我很高兴认识他。', 'Wǒ hěn gāo xìng rèn shi tā.', 'Saya senang mengenalnya.'],
    ],
    glossary: [['朋友', 'péngyǒu', 'teman'], ['美国', 'měiguó', 'Amerika'], ['住', 'zhù', 'tinggal'], ['认识', 'rènshi', 'mengenal']],
    questions: [
      ['Dari negara mana David berasal?', 'Amerika', ['Inggris', 'Jepang', 'Prancis']],
      ['Di mana David tinggal?', 'Beijing', ['Shanghai', 'New York', 'Tokyo']],
      ['Apa yang bisa dilakukan David?', 'Berbicara Mandarin dan menulis hanzi', ['Memasak masakan Tiongkok', 'Bernyanyi lagu Mandarin', 'Menyetir mobil']],
    ],
  },
  // ---------------------------------------------------------------- HSK 2
  {
    id: 'hsk2-paobu', level: 'elementary', title: 'Lari pagi', native: '跑步',
    sentences: [
      ['我每天早上六点起床去跑步。', 'Wǒ měi tiān zǎo shàng liù diǎn qǐ chuáng qù pǎo bù.', 'Setiap pagi saya bangun jam enam untuk lari.'],
      ['我家旁边有一个公园，那儿的空气很好。', 'Wǒ jiā páng biān yǒu yí gè gōng yuán, nàr de kōng qì hěn hǎo.', 'Di sebelah rumah saya ada taman; udaranya bagus.'],
      ['以前我身体不太好，常常生病。', 'Yǐ qián wǒ shēn tǐ bú tài hǎo, cháng cháng shēng bìng.', 'Dulu badan saya kurang sehat dan sering sakit.'],
      ['医生说我应该多运动。', 'Yī shēng shuō wǒ yīng gāi duō yùn dòng.', 'Dokter bilang saya sebaiknya banyak berolahraga.'],
      ['跑了一年以后，我的身体好多了。', 'Pǎo le yì nián yǐ hòu, wǒ de shēn tǐ hǎo duō le.', 'Setelah berlari selama setahun, badan saya jauh lebih sehat.'],
      ['现在我觉得跑步是一件快乐的事情。', 'Xiàn zài wǒ jué de pǎo bù shì yí jiàn kuài lè de shì qíng.', 'Sekarang saya merasa berlari adalah hal yang menyenangkan.'],
    ],
    glossary: [['跑步', 'pǎobù', 'lari'], ['起床', 'qǐchuáng', 'bangun tidur'], ['生病', 'shēngbìng', 'sakit'], ['运动', 'yùndòng', 'olahraga']],
    questions: [
      ['Jam berapa penulis bangun?', 'Jam enam', ['Jam lima', 'Jam tujuh', 'Jam delapan']],
      ['Siapa yang menyarankan olahraga?', 'Dokter', ['Ibu', 'Teman', 'Guru']],
      ['Bagaimana badan penulis sekarang?', 'Jauh lebih sehat', ['Masih sering sakit', 'Lebih gemuk', 'Sama saja']],
    ],
  },
  {
    id: 'hsk2-shanghai', level: 'elementary', title: 'Wisata ke Shanghai', native: '去上海旅游',
    sentences: [
      ['上个月我和丈夫去上海旅游了。', 'Shàng gè yuè wǒ hé zhàng fu qù shàng hǎi lǚ yóu le.', 'Bulan lalu saya dan suami berwisata ke Shanghai.'],
      ['我们是坐火车去的，路上用了五个小时。', 'Wǒ men shì zuò huǒ chē qù de, lù shang yòng le wǔ gè xiǎo shí.', 'Kami naik kereta; perjalanannya lima jam.'],
      ['上海的饭菜有点儿贵，但是非常好吃。', 'Shàng hǎi de fàn cài yǒu diǎnr guì, dàn shì fēi cháng hǎo chī.', 'Makanan di Shanghai agak mahal, tetapi sangat enak.'],
      ['晚上我们在江边看了很漂亮的夜景。', 'Wǎn shàng wǒ men zài jiāng biān kàn le hěn piào liang de yè jǐng.', 'Malam hari kami melihat pemandangan malam yang indah di tepi sungai.'],
      ['第三天下雨了，我们就去了博物馆。', 'Dì sān tiān xià yǔ le, wǒ men jiù qù le bó wù guǎn.', 'Pada hari ketiga hujan, jadi kami pergi ke museum.'],
      ['这次旅游让我们非常快乐。', 'Zhè cì lǚ yóu ràng wǒ men fēi cháng kuài lè.', 'Wisata kali ini membuat kami sangat bahagia.'],
    ],
    glossary: [['旅游', 'lǚyóu', 'berwisata'], ['丈夫', 'zhàngfu', 'suami'], ['火车', 'huǒchē', 'kereta'], ['博物馆', 'bówù guǎn', 'museum']],
    questions: [
      ['Naik apa mereka ke Shanghai?', 'Kereta', ['Pesawat', 'Bus', 'Mobil']],
      ['Berapa lama perjalanannya?', 'Lima jam', ['Tiga jam', 'Delapan jam', 'Dua jam']],
      ['Mengapa mereka ke museum pada hari ketiga?', 'Karena hujan', ['Museumnya gratis', 'Mereka sudah lelah', 'Diajak teman']],
    ],
  },
  {
    id: 'hsk2-ganmao', level: 'elementary', title: 'Sakit flu', native: '我感冒了',
    sentences: [
      ['昨天晚上我觉得头很疼，身体也很累。', 'Zuó tiān wǎn shàng wǒ jué de tóu hěn téng, shēn tǐ yě hěn lèi.', 'Tadi malam kepala saya sakit dan badan saya lelah.'],
      ['今天早上起床的时候，我发烧了。', 'Jīn tiān zǎo shàng qǐ chuáng de shí hòu, wǒ fā shāo le.', 'Pagi ini saat bangun, saya demam.'],
      ['我给公司打电话，说今天不能去上班。', 'Wǒ gěi gōng sī dǎ diàn huà, shuō jīn tiān bù néng qù shàng bān.', 'Saya menelepon kantor dan bilang hari ini tidak bisa masuk kerja.'],
      ['妻子带我去医院看医生。', 'Qī zǐ dài wǒ qù yī yuàn kàn yī shēng.', 'Istri mengantar saya ke rumah sakit untuk periksa ke dokter.'],
      ['医生说我感冒了，要多喝水，多休息。', 'Yī shēng shuō wǒ gǎn mào le, yào duō hē shuǐ, duō xiū xi.', 'Dokter bilang saya flu dan harus banyak minum serta istirahat.'],
      ['吃了药以后，我睡了一下午，现在好一点儿了。', 'Chī le yào yǐ hòu, wǒ shuì le yí xià wǔ, xiàn zài hǎo yì diǎnr le.', 'Setelah minum obat, saya tidur sepanjang sore dan sekarang sedikit membaik.'],
    ],
    glossary: [['疼', 'téng', 'sakit/nyeri'], ['医院', 'yīyuàn', 'rumah sakit'], ['感冒', 'gǎnmào', 'flu'], ['休息', 'xiūxi', 'istirahat']],
    questions: [
      ['Apa yang dirasakan penulis tadi malam?', 'Sakit kepala dan lelah', ['Sakit perut', 'Sakit gigi', 'Batuk']],
      ['Siapa yang mengantar ke rumah sakit?', 'Istrinya', ['Ibunya', 'Teman kantor', 'Anaknya']],
      ['Apa kata dokter?', 'Flu, harus banyak minum dan istirahat', ['Harus dioperasi', 'Harus dirawat inap', 'Tidak sakit apa-apa']],
    ],
  },
  {
    id: 'hsk2-zhaofangzi', level: 'elementary', title: 'Mencari rumah sewa', native: '找房子',
    sentences: [
      ['我在找新房子，因为现在的房子离公司太远了。', 'Wǒ zài zhǎo xīn fáng zi, yīn wèi xiàn zài de fáng zi lí gōng sī tài yuǎn le.', 'Saya sedang mencari rumah baru karena rumah sekarang terlalu jauh dari kantor.'],
      ['昨天我看了两个房子。', 'Zuó tiān wǒ kàn le liǎng gè fáng zi.', 'Kemarin saya melihat dua rumah.'],
      ['第一个房子很大，但是一个月要五千块。', 'Dì yī gè fáng zi hěn dà, dàn shì yí gè yuè yào wǔ qiān kuài.', 'Rumah pertama besar, tetapi sewanya lima ribu yuan sebulan.'],
      ['第二个房子小一点儿，一个月三千块，走路到公司只要十分钟。', 'Dì èr gè fáng zi xiǎo yì diǎnr, yí gè yuè sān qiān kuài, zǒu lù dào gōng sī zhǐ yào shí fēn zhōng.', 'Rumah kedua sedikit lebih kecil, tiga ribu yuan sebulan, dan jalan kaki ke kantor hanya sepuluh menit.'],
      ['我觉得第二个更好。', 'Wǒ jué de dì èr gè gèng hǎo.', 'Saya rasa yang kedua lebih baik.'],
      ['下个星期我就要搬家了。', 'Xià gè xīng qī wǒ jiù yào bān jiā le.', 'Minggu depan saya akan pindah rumah.'],
    ],
    glossary: [['房子', 'fángzi', 'rumah'], ['离', 'lí', 'berjarak dari'], ['公司', 'gōngsī', 'kantor/perusahaan'], ['搬家', 'bānjiā', 'pindah rumah']],
    questions: [
      ['Mengapa penulis mencari rumah baru?', 'Rumah sekarang terlalu jauh dari kantor', ['Terlalu kecil', 'Terlalu mahal', 'Tetangganya berisik']],
      ['Berapa sewa rumah kedua?', 'Tiga ribu yuan sebulan', ['Lima ribu yuan sebulan', 'Dua ribu yuan sebulan', 'Empat ribu yuan sebulan']],
      ['Kapan penulis pindah?', 'Minggu depan', ['Besok', 'Bulan depan', 'Tahun depan']],
    ],
  },
  {
    id: 'hsk2-shengri', level: 'elementary', title: 'Pesta ulang tahun', native: '生日晚会',
    sentences: [
      ['今天是我女儿的七岁生日。', 'Jīn tiān shì wǒ nǚ ér de qī suì shēng rì.', 'Hari ini ulang tahun ketujuh putri saya.'],
      ['下午我们在家准备了一个小晚会。', 'Xià wǔ wǒ men zài jiā zhǔn bèi le yí gè xiǎo wǎn huì.', 'Sore hari kami menyiapkan pesta kecil di rumah.'],
      ['她的同学们都来了，还给她送了很多礼物。', 'Tā de tóng xué men dōu lái le, hái gěi tā sòng le hěn duō lǐ wù.', 'Teman-teman sekelasnya datang dan memberinya banyak hadiah.'],
      ['我给她买了一个很大的蛋糕。', 'Wǒ gěi tā mǎi le yí gè hěn dà de dàn gāo.', 'Saya membelikannya kue yang sangat besar.'],
      ['孩子们一起唱歌、跳舞，玩得非常高兴。', 'Hái zi men yì qǐ chàng gē, tiào wǔ, wán de fēi cháng gāo xìng.', 'Anak-anak bernyanyi dan menari bersama, bermain dengan sangat gembira.'],
      ['女儿说这是她最快乐的一天。', 'Nǚ ér shuō zhè shì tā zuì kuài lè de yì tiān.', 'Putri saya bilang ini hari paling bahagianya.'],
    ],
    glossary: [['女儿', 'nǚ\'ér', 'putri'], ['准备', 'zhǔnbèi', 'menyiapkan'], ['蛋糕', 'dàngāo', 'kue'], ['跳舞', 'tiàowǔ', 'menari']],
    questions: [
      ['Berapa umur putri penulis?', 'Tujuh tahun', ['Enam tahun', 'Delapan tahun', 'Sepuluh tahun']],
      ['Apa yang dibeli penulis?', 'Kue yang besar', ['Boneka', 'Sepeda', 'Baju baru']],
      ['Apa yang dilakukan anak-anak?', 'Bernyanyi dan menari', ['Menonton film', 'Berenang', 'Belajar']],
    ],
  },
  {
    id: 'hsk2-xingongzuo', level: 'elementary', title: 'Pekerjaan baru', native: '新工作',
    sentences: [
      ['我姐姐上个星期开始了新工作。', 'Wǒ jiě jie shàng gè xīng qī kāi shǐ le xīn gōng zuò.', 'Kakak perempuan saya mulai pekerjaan baru minggu lalu.'],
      ['她在一家大公司卖电脑。', 'Tā zài yì jiā dà gōng sī mài diàn nǎo.', 'Dia menjual komputer di sebuah perusahaan besar.'],
      ['公司离她家很近，她每天走路去上班。', 'Gōng sī lí tā jiā hěn jìn, tā měi tiān zǒu lù qù shàng bān.', 'Kantornya dekat rumah, jadi setiap hari dia berjalan kaki ke kantor.'],
      ['工作有点儿忙，但是同事们都对她很好。', 'Gōng zuò yǒu diǎnr máng, dàn shì tóng shì men dōu duì tā hěn hǎo.', 'Pekerjaannya agak sibuk, tetapi rekan-rekan kerja baik kepadanya.'],
      ['她说这个工作比以前的工作有意思。', 'Tā shuō zhè ge gōng zuò bǐ yǐ qián de gōng zuò yǒu yì sī.', 'Dia bilang pekerjaan ini lebih menarik daripada pekerjaan sebelumnya.'],
      ['我希望她能一直快乐地工作。', 'Wǒ xī wàng tā néng yì zhí kuài lè de gōng zuò.', 'Saya berharap dia bisa terus bekerja dengan bahagia.'],
    ],
    glossary: [['开始', 'kāishǐ', 'mulai'], ['电脑', 'diànnǎo', 'komputer'], ['同事', 'tóngshì', 'rekan kerja'], ['希望', 'xīwàng', 'berharap']],
    questions: [
      ['Apa pekerjaan baru kakak penulis?', 'Menjual komputer', ['Mengajar', 'Memasak', 'Menyetir']],
      ['Bagaimana dia pergi ke kantor?', 'Berjalan kaki', ['Naik bus', 'Naik taksi', 'Naik sepeda']],
      ['Bagaimana rekan-rekan kerjanya?', 'Baik kepadanya', ['Sangat sibuk', 'Tidak ramah', 'Semuanya baru']],
    ],
  },
  {
    id: 'hsk2-xuehanyu', level: 'elementary', title: 'Belajar bahasa Mandarin', native: '学汉语',
    sentences: [
      ['我学习汉语已经两年了。', 'Wǒ xué xí hàn yǔ yǐ jīng liǎng nián le.', 'Saya sudah belajar bahasa Mandarin selama dua tahun.'],
      ['刚开始的时候，我觉得汉字特别难。', 'Gāng kāi shǐ de shí hòu, wǒ jué de hàn zì tè bié nán.', 'Waktu baru mulai, saya merasa hanzi sangat sulit.'],
      ['我的老师告诉我，每天写十个汉字。', 'Wǒ de lǎo shī gào sù wǒ, měi tiān xiě shí gè hàn zì.', 'Guru saya menyuruh saya menulis sepuluh hanzi setiap hari.'],
      ['我还常常看中国电影，听中文歌。', 'Wǒ hái cháng cháng kàn zhōng guó diàn yǐng, tīng zhōng wén gē.', 'Saya juga sering menonton film Tiongkok dan mendengarkan lagu Mandarin.'],
      ['现在我可以和中国朋友聊天了。', 'Xiàn zài wǒ kě yǐ hé zhōng guó péng yǒu liáo tiān le.', 'Sekarang saya sudah bisa mengobrol dengan teman dari Tiongkok.'],
      ['明年我想去北京上大学。', 'Míng nián wǒ xiǎng qù běi jīng shàng dà xué.', 'Tahun depan saya ingin kuliah di Beijing.'],
    ],
    glossary: [['已经', 'yǐjīng', 'sudah'], ['特别', 'tèbié', 'sangat/khusus'], ['告诉', 'gàosù', 'memberi tahu'], ['聊天', 'liáotiān', 'mengobrol']],
    questions: [
      ['Sudah berapa lama penulis belajar Mandarin?', 'Dua tahun', ['Satu tahun', 'Tiga tahun', 'Enam bulan']],
      ['Berapa hanzi yang ditulis setiap hari?', 'Sepuluh', ['Lima', 'Dua puluh', 'Lima puluh']],
      ['Apa rencana penulis tahun depan?', 'Kuliah di Beijing', ['Bekerja di Shanghai', 'Berwisata ke Tiongkok', 'Mengajar Mandarin']],
    ],
  },
  {
    id: 'hsk2-zhaomao', level: 'elementary', title: 'Mencari kucing', native: '找猫',
    sentences: [
      ['昨天下午我的猫不见了。', 'Zuó tiān xià wǔ wǒ de māo bú jiàn le.', 'Kemarin sore kucing saya hilang.'],
      ['我在房间里、门外面都找了，可是没有找到。', 'Wǒ zài fáng jiān lǐ, mén wài miàn dōu zhǎo le, kě shì méi yǒu zhǎo dào.', 'Saya sudah mencari di kamar dan di luar pintu, tetapi tidak menemukannya.'],
      ['我问了很多人，他们都说没看见。', 'Wǒ wèn le hěn duō rén, tā men dōu shuō méi kàn jiàn.', 'Saya bertanya ke banyak orang, semuanya bilang tidak melihat.'],
      ['晚上我很累，也很难过。', 'Wǎn shàng wǒ hěn lèi, yě hěn nán guò.', 'Malam harinya saya lelah dan sedih.'],
      ['十点的时候，我听见门外有猫叫。', 'Shí diǎn de shí hòu, wǒ tīng jiàn mén wài yǒu māo jiào.', 'Pada jam sepuluh, saya mendengar suara kucing di luar pintu.'],
      ['开门一看，我的猫回来了！', 'Kāi mén yí kàn, wǒ de māo huí lái le!', 'Begitu pintu saya buka, ternyata kucing saya sudah pulang!'],
    ],
    glossary: [['不见', 'bújiàn', 'hilang'], ['找到', 'zhǎodào', 'menemukan'], ['难过', 'nánguò', 'sedih'], ['看见', 'kànjiàn', 'melihat']],
    questions: [
      ['Kapan kucingnya hilang?', 'Kemarin sore', ['Tadi pagi', 'Kemarin malam', 'Minggu lalu']],
      ['Bagaimana perasaan penulis malam itu?', 'Lelah dan sedih', ['Senang', 'Marah', 'Takut']],
      ['Jam berapa kucingnya pulang?', 'Jam sepuluh', ['Jam delapan', 'Jam sembilan', 'Jam sebelas']],
    ],
  },
  // ---------------------------------------------------------------- HSK 7-9
  {
    id: 'hsk79-suanfa', level: 'hsk-7-9', title: 'Kecerdasan buatan dan tata kelola', native: '人工智能与社会治理',
    sentences: [
      ['人工智能正以前所未有的速度渗透到社会治理的各个环节。', 'Rén gōng zhì néng zhèng yǐ qián suǒ wèi yǒu de sù dù shèn tòu dào shè huì zhì lǐ de gè gè huán jié.', 'Kecerdasan buatan merambah setiap aspek tata kelola sosial dengan kecepatan yang belum pernah terjadi.'],
      ['从交通调度到公共卫生预警，算法在提升效率方面的作用有目共睹。', 'Cóng jiāo tōng diào dù dào gōng gòng wèi shēng yù jǐng, suàn fǎ zài tí shēng xiào lǜ fāng miàn de zuò yòng yǒu mù gòng dǔ.', 'Dari pengaturan lalu lintas hingga peringatan dini kesehatan masyarakat, peran algoritme dalam meningkatkan efisiensi terlihat jelas.'],
      ['然而，算法并非价值中立，其背后的数据往往折射出既有的社会偏见。', 'Rán ér, suàn fǎ bìng fēi jià zhí zhōng lì, qí bèi hòu de shù jù wǎng wǎng zhé shè chū jì yǒu de shè huì piān jiàn.', 'Namun, algoritme tidak netral nilai; data di baliknya sering mencerminkan bias sosial yang sudah ada.'],
      ['一旦决策过程缺乏透明度，公众的信任便难以建立。', 'Yí dàn jué cè guò chéng quē fá tòu míng dù, gōng zhòng de xìn rèn biàn nán yǐ jiàn lì.', 'Begitu proses pengambilan keputusan kurang transparan, kepercayaan publik sulit dibangun.'],
      ['因此，有学者主张建立算法审计制度，让技术接受社会监督。', 'Yīn cǐ, yǒu xué zhě zhǔ zhāng jiàn lì suàn fǎ shěn jì zhì dù, ràng jì shù jiē shòu shè huì jiān dū.', 'Karena itu, sebagian akademisi mengusulkan sistem audit algoritme agar teknologi diawasi masyarakat.'],
      ['如何在创新与规制之间找到平衡，考验着治理者的智慧。', 'Rú hé zài chuàng xīn yǔ guī zhì zhī jiān zhǎo dào píng héng, kǎo yàn zhe zhì lǐ zhě de zhì huì.', 'Menemukan keseimbangan antara inovasi dan regulasi menguji kebijaksanaan para pengelola pemerintahan.'],
    ],
    glossary: [['渗透', 'shèntòu', 'meresap/merambah'], ['有目共睹', 'yǒumùgòngdǔ', 'terlihat jelas oleh semua'], ['偏见', 'piānjiàn', 'bias/prasangka'], ['审计', 'shěnjì', 'audit']],
    questions: [
      ['Apa yang dicerminkan data di balik algoritme?', 'Bias sosial yang sudah ada', ['Kebenaran objektif', 'Opini pemerintah', 'Tren pasar']],
      ['Apa usulan sebagian akademisi?', 'Sistem audit algoritme', ['Melarang kecerdasan buatan', 'Menghapus data publik', 'Menyerahkan semuanya ke perusahaan']],
      ['Apa yang menguji kebijaksanaan pengelola pemerintahan?', 'Menyeimbangkan inovasi dan regulasi', ['Mengurangi pengangguran', 'Membangun jalan', 'Menaikkan pajak']],
    ],
  },
  {
    id: 'hsk79-fangyan', level: 'hsk-7-9', title: 'Nasib dialek', native: '方言的命运',
    sentences: [
      ['随着普通话的全面普及，许多方言正面临传承断层的危机。', 'Suí zhe pǔ tōng huà de quán miàn pǔ jí, xǔ duō fāng yán zhèng miàn lín chuán chéng duàn céng de wēi jī.', 'Seiring meluasnya Putonghua, banyak dialek menghadapi krisis terputusnya pewarisan.'],
      ['在一些城市，年轻一代虽然听得懂方言，却已很少开口说。', 'Zài yì xiē chéng shì, nián qīng yí dài suī rán tīng de dǒng fāng yán, què yǐ hěn shǎo kāi kǒu shuō.', 'Di sebagian kota, generasi muda memahami dialek tetapi jarang lagi memakainya.'],
      ['语言学家指出，方言不仅是交流工具，更承载着地方的历史记忆与文化认同。', 'Yǔ yán xué jiā zhǐ chū, fāng yán bù jǐn shì jiāo liú gōng jù, gèng chéng zài zhe dì fāng de lì shǐ jì yì yǔ wén huà rèn tóng.', 'Ahli bahasa menunjukkan bahwa dialek bukan hanya alat komunikasi, tetapi juga membawa memori sejarah dan identitas budaya daerah.'],
      ['一种方言的消失，意味着一套独特的世界观随之湮没。', 'Yì zhǒng fāng yán de xiāo shī, yì wèi zhe yí tào dú tè de shì jiè guān suí zhī yān mò.', 'Hilangnya satu dialek berarti ikut tenggelamnya satu pandangan dunia yang unik.'],
      ['近年来，不少地方通过录音存档、方言节目等方式加以保护。', 'Jìn nián lái, bù shǎo dì fāng tōng guò lù yīn cún dàng, fāng yán jié mù děng fāng shì jiā yǐ bǎo hù.', 'Beberapa tahun terakhir, banyak daerah melindunginya lewat arsip rekaman dan program berbahasa dialek.'],
      ['推广通用语与保护方言并非此消彼长，而是可以相辅相成。', 'Tuī guǎng tōng yòng yǔ yǔ bǎo hù fāng yán bìng fēi cǐ xiāo bǐ zhǎng, ér shì kě yǐ xiāng fǔ xiāng chéng.', 'Mempromosikan bahasa umum dan melindungi dialek bukanlah saling meniadakan, melainkan dapat saling melengkapi.'],
    ],
    glossary: [['普及', 'pǔjí', 'meluas/merata'], ['断层', 'duàncéng', 'keterputusan'], ['湮没', 'yānmò', 'tenggelam/terlupakan'], ['相辅相成', 'xiāngfǔ xiāngchéng', 'saling melengkapi']],
    questions: [
      ['Apa yang terjadi pada generasi muda di sebagian kota?', 'Memahami dialek tetapi jarang memakainya', ['Tidak memahami Putonghua', 'Tidak mau bersekolah', 'Pindah ke luar negeri']],
      ['Apa arti hilangnya satu dialek menurut teks?', 'Hilangnya satu pandangan dunia yang unik', ['Hilangnya satu kota', 'Kemajuan ekonomi', 'Komunikasi menjadi lebih mudah']],
      ['Bagaimana hubungan bahasa umum dan dialek menurut penulis?', 'Dapat saling melengkapi', ['Saling meniadakan', 'Dialek harus dihapus', 'Tidak saling berhubungan']],
    ],
  },
  {
    id: 'hsk79-xiangcun', level: 'hsk-7-9', title: 'Revitalisasi desa', native: '乡村振兴',
    sentences: [
      ['过去几十年，大量青壮年劳动力涌向城市，许多村庄出现了“空心化”现象。', 'Guò qù jǐ shí nián, dà liàng qīng zhuàng nián láo dòng lì yǒng xiàng chéng shì, xǔ duō cūn zhuāng chū xiàn le "kōng xīn huà" xiàn xiàng.', 'Beberapa dekade terakhir, banyak tenaga kerja muda membanjiri kota, dan banyak desa mengalami fenomena “desa kosong”.'],
      ['乡村振兴战略试图扭转这一趋势，让农村重新焕发活力。', 'Xiāng cūn zhèn xīng zhàn lüè shì tú niǔ zhuǎn zhè yì qū shì, ràng nóng cūn chóng xīn huàn fā huó lì.', 'Strategi revitalisasi desa berusaha membalikkan tren ini agar desa kembali bergairah.'],
      ['电商平台让偏远山区的农产品直接走进城市消费者的餐桌。', 'Diàn shāng píng tái ràng piān yuǎn shān qū de nóng chǎn pǐn zhí jiē zǒu jìn chéng shì xiāo fèi zhě de cān zhuō.', 'Platform e-commerce membuat hasil tani dari pegunungan terpencil langsung sampai ke meja makan konsumen kota.'],
      ['一些返乡青年将传统手工艺与文创设计结合，开辟了新的收入来源。', 'Yì xiē fǎn xiāng qīng nián jiāng chuán tǒng shǒu gōng yì yǔ wén chuàng shè jì jié hé, kāi pì le xīn de shōu rù lái yuán.', 'Sebagian pemuda yang pulang kampung memadukan kerajinan tradisional dengan desain kreatif dan membuka sumber penghasilan baru.'],
      ['不过，基础设施薄弱、人才匮乏等问题依然制约着发展。', 'Bú guò, jī chǔ shè shī bó ruò, rén cái kuì fá děng wèn tí yī rán zhì yuē zhe fā zhǎn.', 'Namun, masalah seperti infrastruktur yang lemah dan kurangnya tenaga ahli masih membatasi perkembangan.'],
      ['振兴乡村，归根结底要让村民成为发展的真正受益者。', 'Zhèn xīng xiāng cūn, guī gēn jié dǐ yào ràng cūn mín chéng wéi fā zhǎn de zhēn zhèng shòu yì zhě.', 'Pada akhirnya, revitalisasi desa harus menjadikan warga desa penerima manfaat sejati dari pembangunan.'],
    ],
    glossary: [['涌向', 'yǒngxiàng', 'membanjiri'], ['焕发', 'huànfā', 'memancarkan'], ['匮乏', 'kuìfá', 'kekurangan'], ['归根结底', 'guīgēn jiédǐ', 'pada akhirnya']],
    questions: [
      ['Apa yang dimaksud fenomena “desa kosong”?', 'Tenaga kerja muda pindah ke kota', ['Desa dilanda banjir', 'Sawah menjadi pabrik', 'Turis memenuhi desa']],
      ['Apa peran platform e-commerce menurut teks?', 'Membawa hasil tani terpencil ke konsumen kota', ['Menggantikan petani', 'Menaikkan harga tanah', 'Membangun jalan desa']],
      ['Apa yang masih membatasi perkembangan desa?', 'Infrastruktur lemah dan kurangnya tenaga ahli', ['Terlalu banyak turis', 'Pajak yang tinggi', 'Cuaca buruk']],
    ],
  },
  {
    id: 'hsk79-yuedu', level: 'hsk-7-9', title: 'Merosotnya membaca mendalam', native: '深度阅读的式微',
    sentences: [
      ['在信息碎片化的时代，人们的注意力被切割成无数个短暂的片段。', 'Zài xìn xī suì piàn huà de shí dài, rén men de zhù yì lì bèi qiē gē chéng wú shù gè duǎn zàn de piàn duàn.', 'Di era informasi yang terfragmentasi, perhatian orang terpotong menjadi kepingan-kepingan singkat yang tak terhitung.'],
      ['刷短视频、浏览标题成了许多人获取信息的主要方式。', 'Shuā duǎn shì pín, liú lǎn biāo tí chéng le xǔ duō rén huò qǔ xìn xī de zhǔ yào fāng shì.', 'Menggulir video pendek dan membaca judul menjadi cara utama banyak orang memperoleh informasi.'],
      ['研究表明，长期浅层阅读会削弱人们持续专注和深入思考的能力。', 'Yán jiū biǎo míng, cháng qī qiǎn céng yuè dú huì xuē ruò rén men chí xù zhuān zhù hé shēn rù sī kǎo de néng lì.', 'Penelitian menunjukkan bahwa membaca dangkal dalam jangka panjang melemahkan kemampuan fokus berkelanjutan dan berpikir mendalam.'],
      ['深度阅读要求读者与文本反复对话，在理解中形成自己的判断。', 'Shēn dù yuè dú yāo qiú dú zhě yǔ wén běn fǎn fù duì huà, zài lǐ jiě zhōng xíng chéng zì jǐ de pàn duàn.', 'Membaca mendalam menuntut pembaca berdialog berulang kali dengan teks dan membentuk penilaiannya sendiri.'],
      ['有人因此提倡“慢阅读”，每天留出固定时间远离屏幕。', 'Yǒu rén yīn cǐ tí chàng "màn yuè dú", měi tiān liú chū gù dìng shí jiān yuǎn lí píng mù.', 'Karena itu ada yang menganjurkan “membaca lambat”, yaitu menyisihkan waktu tetap setiap hari jauh dari layar.'],
      ['阅读的深度，某种程度上决定了思想的深度。', 'Yuè dú de shēn dù, mǒu zhǒng chéng dù shàng jué dìng le sī xiǎng de shēn dù.', 'Kedalaman membaca, sampai batas tertentu, menentukan kedalaman pemikiran.'],
    ],
    glossary: [['碎片化', 'suìpiànhuà', 'terfragmentasi'], ['削弱', 'xuēruò', 'melemahkan'], ['浅层', 'qiǎncéng', 'dangkal'], ['提倡', 'tíchàng', 'menganjurkan']],
    questions: [
      ['Apa efek membaca dangkal jangka panjang?', 'Melemahkan fokus dan pemikiran mendalam', ['Menambah kosakata', 'Mempercepat membaca', 'Memperbaiki ingatan']],
      ['Apa yang dituntut dari membaca mendalam?', 'Berdialog berulang kali dengan teks', ['Membaca secepat mungkin', 'Hanya membaca judul', 'Menghafal seluruh isi']],
      ['Apa yang dianjurkan dalam “membaca lambat”?', 'Waktu tetap setiap hari jauh dari layar', ['Membaca di ponsel', 'Menonton video', 'Membaca sambil bekerja']],
    ],
  },
  {
    id: 'hsk79-laolinghua', level: 'hsk-7-9', title: 'Masyarakat yang menua', native: '老龄化社会',
    sentences: [
      ['中国正快速步入深度老龄化社会，六十岁以上人口已超过两亿。', 'Zhōng guó zhèng kuài sù bù rù shēn dù lǎo líng huà shè huì, liù shí suì yǐ shàng rén kǒu yǐ chāo guò liǎng yì.', 'Tiongkok dengan cepat memasuki masyarakat yang sangat menua; penduduk berusia di atas 60 tahun telah melampaui dua ratus juta.'],
      ['养老金的可持续性和医疗资源的分配成为亟待解决的难题。', 'Yǎng lǎo jīn de kě chí xù xìng hé yī liáo zī yuán de fēn pèi chéng wéi jí dài jiě jué de nán tí.', 'Keberlanjutan dana pensiun dan distribusi sumber daya medis menjadi persoalan yang mendesak.'],
      ['传统的家庭养老模式在城市化浪潮中受到冲击。', 'Chuán tǒng de jiā tíng yǎng lǎo mó shì zài chéng shì huà làng cháo zhōng shòu dào chōng jī.', 'Model perawatan lansia tradisional berbasis keluarga terguncang oleh gelombang urbanisasi.'],
      ['社区养老、智慧养老等新模式应运而生。', 'Shè qū yǎng lǎo, zhì huì yǎng lǎo děng xīn mó shì yìng yùn ér shēng.', 'Model baru seperti perawatan lansia berbasis komunitas dan berbasis teknologi pintar pun bermunculan.'],
      ['与此同时，“银发经济”也蕴藏着巨大的市场潜力。', 'Yǔ cǐ tóng shí, "yín fà jīng jì" yě yùn cáng zhe jù dà de shì chǎng qián lì.', 'Pada saat yang sama, “ekonomi perak” juga menyimpan potensi pasar yang besar.'],
      ['如何让老年人老有所养、老有所乐，是对整个社会的考验。', 'Rú hé ràng lǎo nián rén lǎo yǒu suǒ yǎng, lǎo yǒu suǒ lè, shì duì zhěng gè shè huì de kǎo yàn.', 'Bagaimana memastikan lansia terawat dan bahagia di hari tua merupakan ujian bagi seluruh masyarakat.'],
    ],
    glossary: [['老龄化', 'lǎolínghuà', 'penuaan penduduk'], ['亟待', 'jídài', 'sangat perlu segera'], ['应运而生', 'yìngyùn\'érshēng', 'lahir menjawab kebutuhan zaman'], ['蕴藏', 'yùncáng', 'menyimpan']],
    questions: [
      ['Berapa jumlah penduduk berusia di atas 60 tahun?', 'Lebih dari dua ratus juta', ['Seratus juta', 'Lima puluh juta', 'Satu miliar']],
      ['Apa yang terguncang oleh urbanisasi?', 'Perawatan lansia berbasis keluarga', ['Sistem sekolah', 'Industri pertanian', 'Transportasi umum']],
      ['Apa yang disebut menyimpan potensi pasar besar?', 'Ekonomi perak', ['Ekonomi digital', 'Pariwisata desa', 'Industri film']],
    ],
  },
  {
    id: 'hsk79-kexue', level: 'hsk-7-9', title: 'Semangat ilmiah', native: '科学精神',
    sentences: [
      ['科学精神的核心，不在于掌握多少结论，而在于对待知识的态度。', 'Kē xué jīng shén de hé xīn, bú zài yú zhǎng wò duō shǎo jié lùn, ér zài yú duì dài zhī shi de tài dù.', 'Inti semangat ilmiah bukan pada berapa banyak kesimpulan yang dikuasai, melainkan pada sikap terhadap pengetahuan.'],
      ['它要求我们敢于质疑权威，同时尊重证据。', 'Tā yāo qiú wǒ men gǎn yú zhì yí quán wēi, tóng shí zūn zhòng zhèng jù.', 'Semangat itu menuntut kita berani mempertanyakan otoritas sekaligus menghormati bukti.'],
      ['任何理论都应当接受检验，经不起检验的观点终将被淘汰。', 'Rèn hé lǐ lùn dōu yīng dāng jiē shòu jiǎn yàn, jīng bù qǐ jiǎn yàn de guān diǎn zhōng jiāng bèi táo tài.', 'Setiap teori harus diuji; pandangan yang tidak tahan uji pada akhirnya akan tersingkir.'],
      ['然而，在网络谣言盛行的今天，许多人更愿意相信符合自己立场的说法。', 'Rán ér, zài wǎng luò yáo yán shèng xíng de jīn tiān, xǔ duō rén gèng yuàn yì xiāng xìn fú hé zì jǐ lì chǎng de shuō fǎ.', 'Namun, di masa rumor internet merajalela, banyak orang lebih suka memercayai klaim yang sesuai dengan sikapnya.'],
      ['这种“确认偏误”使理性讨论变得愈发困难。', 'Zhè zhǒng "què rèn piān wù" shǐ lǐ xìng tǎo lùn biàn de yù fā kùn nán.', '“Bias konfirmasi” semacam ini membuat diskusi rasional semakin sulit.'],
      ['普及科学精神，比普及科学知识更为根本。', 'Pǔ jí kē xué jīng shén, bǐ pǔ jí kē xué zhī shi gèng wéi gēn běn.', 'Menyebarkan semangat ilmiah lebih mendasar daripada menyebarkan pengetahuan ilmiah.'],
    ],
    glossary: [['质疑', 'zhìyí', 'mempertanyakan'], ['检验', 'jiǎnyàn', 'menguji'], ['淘汰', 'táotài', 'tersingkir'], ['盛行', 'shèngxíng', 'merajalela']],
    questions: [
      ['Apa inti semangat ilmiah menurut teks?', 'Sikap terhadap pengetahuan', ['Jumlah kesimpulan yang dihafal', 'Gelar akademik', 'Penguasaan teknologi']],
      ['Apa yang terjadi pada pandangan yang tidak tahan uji?', 'Akhirnya tersingkir', ['Menjadi hukum', 'Dilindungi', 'Dibiarkan saja']],
      ['Apa yang membuat diskusi rasional semakin sulit?', 'Bias konfirmasi', ['Kurangnya internet', 'Bahasa asing', 'Sedikitnya ilmuwan']],
    ],
  },
  {
    id: 'hsk79-chengshi', level: 'hsk-7-9', title: 'Pembaruan kota dan ingatan', native: '城市更新与记忆',
    sentences: [
      ['在大规模城市更新中，许多老街区被拆除，取而代之的是整齐划一的高楼。', 'Zài dà guī mó chéng shì gēng xīn zhōng, xǔ duō lǎo jiē qū bèi chāi chú, qǔ ér dài zhī de shì zhěng qí huà yī de gāo lóu.', 'Dalam pembaruan kota besar-besaran, banyak kawasan lama dibongkar dan digantikan gedung tinggi yang seragam.'],
      ['居住条件固然改善了，但一些居民却感到失去了熟悉的邻里关系。', 'Jū zhù tiáo jiàn gù rán gǎi shàn le, dàn yì xiē jū mín què gǎn dào shī qù le shú xī de lín lǐ guān xì.', 'Kondisi hunian memang membaik, tetapi sebagian warga merasa kehilangan hubungan bertetangga yang akrab.'],
      ['老建筑不仅是砖瓦，更是几代人生活的见证。', 'Lǎo jiàn zhù bù jǐn shì zhuān wǎ, gèng shì jǐ dài rén shēng huó de jiàn zhèng.', 'Bangunan lama bukan sekadar bata dan genteng, tetapi saksi kehidupan beberapa generasi.'],
      ['近年来，“微改造”的理念逐渐被接受，强调在保留原有肌理的基础上改善环境。', 'Jìn nián lái, "wēi gǎi zào" de lǐ niàn zhú jiàn bèi jiē shòu, qiáng diào zài bǎo liú yuán yǒu jī lǐ de jī chǔ shàng gǎi shàn huán jìng.', 'Beberapa tahun terakhir, konsep “renovasi mikro” mulai diterima; konsep ini menekankan perbaikan lingkungan sambil mempertahankan tekstur asli kawasan.'],
      ['这样的更新方式成本更低，也更能留住城市的温度。', 'Zhè yàng de gēng xīn fāng shì chéng běn gèng dī, yě gèng néng liú zhù chéng shì de wēn dù.', 'Cara pembaruan seperti ini lebih murah dan lebih mampu mempertahankan kehangatan kota.'],
      ['一座城市的魅力，往往藏在它的记忆之中。', 'Yí zuò chéng shì de mèi lì, wǎng wǎng cáng zài tā de jì yì zhī zhōng.', 'Pesona sebuah kota sering tersembunyi di dalam ingatannya.'],
    ],
    glossary: [['拆除', 'chāichú', 'membongkar'], ['见证', 'jiànzhèng', 'saksi'], ['肌理', 'jīlǐ', 'tekstur/jalinan'], ['魅力', 'mèilì', 'pesona']],
    questions: [
      ['Apa yang dirasakan hilang oleh sebagian warga?', 'Hubungan bertetangga yang akrab', ['Pekerjaan', 'Akses transportasi', 'Sekolah']],
      ['Apa yang ditekankan konsep “renovasi mikro”?', 'Perbaikan sambil mempertahankan tekstur asli', ['Membangun gedung tinggi', 'Membongkar semua bangunan', 'Memindahkan warga']],
      ['Di mana pesona kota tersembunyi menurut penulis?', 'Di dalam ingatannya', ['Di gedung tertinggi', 'Di pusat belanja', 'Di jalan tol']],
    ],
  },
  {
    id: 'hsk79-fanyi', level: 'hsk-7-9', title: 'Budaya dalam penerjemahan', native: '翻译中的文化',
    sentences: [
      ['翻译从来不只是语言符号之间的简单转换。', 'Fān yì cóng lái bù zhǐ shì yǔ yán fú hào zhī jiān de jiǎn dān zhuǎn huàn.', 'Penerjemahan tidak pernah sekadar konversi sederhana antarsimbol bahasa.'],
      ['许多词语承载着深厚的文化内涵，在另一种语言中很难找到完全对应的表达。', 'Xǔ duō cí yǔ chéng zài zhe shēn hòu de wén huà nèi hán, zài lìng yì zhǒng yǔ yán zhōng hěn nán zhǎo dào wán quán duì yìng de biǎo dá.', 'Banyak kata mengandung makna budaya yang dalam dan sulit dicari padanan persisnya dalam bahasa lain.'],
      ['例如“江湖”一词，直译往往会让外国读者不知所云。', 'Lì rú "jiāng hú" yì cí, zhí yì wǎng wǎng huì ràng wài guó dú zhě bù zhī suǒ yún.', 'Misalnya kata “jianghu”; terjemahan harfiahnya sering membuat pembaca asing tidak paham maksudnya.'],
      ['译者因此需要在忠实原文与照顾读者之间反复权衡。', 'Yì zhě yīn cǐ xū yào zài zhōng shí yuán wén yǔ zhào gù dú zhě zhī jiān fǎn fù quán héng.', 'Karena itu penerjemah harus berulang kali menimbang antara setia pada teks asli dan memperhatikan pembaca.'],
      ['优秀的译作能够让不同文化的读者产生相似的共鸣。', 'Yōu xiù de yì zuò néng gòu ràng bù tóng wén huà de dú zhě chǎn shēng xiāng shì de gòng míng.', 'Karya terjemahan yang unggul dapat membangkitkan resonansi yang serupa pada pembaca dari budaya berbeda.'],
      ['从这个意义上说，译者是文明之间的摆渡人。', 'Cóng zhè ge yì yì shàng shuō, yì zhě shì wén míng zhī jiān de bǎi dù rén.', 'Dalam arti ini, penerjemah adalah penyeberang antarperadaban.'],
    ],
    glossary: [['内涵', 'nèihán', 'makna/konotasi'], ['不知所云', 'bùzhīsuǒyún', 'tidak paham maksudnya'], ['权衡', 'quánhéng', 'menimbang'], ['共鸣', 'gòngmíng', 'resonansi']],
    questions: [
      ['Mengapa sebagian kata sulit diterjemahkan?', 'Mengandung makna budaya yang dalam', ['Terlalu panjang', 'Jarang dipakai', 'Tidak ada di kamus']],
      ['Apa yang harus ditimbang penerjemah?', 'Setia pada teks asli dan memperhatikan pembaca', ['Kecepatan dan harga', 'Panjang dan pendek teks', 'Tata bahasa dan ejaan']],
      ['Penerjemah digambarkan sebagai apa?', 'Penyeberang antarperadaban', ['Penjaga perpustakaan', 'Hakim bahasa', 'Penulis ulang']],
    ],
  },
];
