// Mandarin Clause Connect: conjunction pairs, sequence and relative 的, 30 per level.
// Conditionals (如果/只要/只有) live in Conditional Run; this bank covers cause, contrast, addition and sequence.
import type { ChoiceTuple } from './questions';

export const easyClauses: ChoiceTuple[] = [
  ['____下雨，所以我没去。', 'Karena hujan, saya tidak pergi.', '因为', ['虽然', '但是', '或者'], 'Sebab', '因为 … 所以 = karena … maka.'],
  ['因为他病了，____没来上课。', 'Karena sakit, dia tidak masuk kelas.', '所以', ['但是', '虽然', '还是'], 'Akibat', '因为 … 所以.'],
  ['我想去，____没有时间。', 'Saya ingin pergi, tetapi tidak punya waktu.', '但是', ['所以', '因为', '或者'], 'Kontras', '但是 = tetapi.'],
  ['你喝茶____喝咖啡？', 'Kamu minum teh atau kopi?', '还是', ['或者', '和', '但是'], 'Pilihan (tanya)', '还是 = atau, dalam pertanyaan.'],
  ['周末我看书____看电影。', 'Akhir pekan saya membaca buku atau menonton film.', '或者', ['还是', '和', '但是'], 'Pilihan (pernyataan)', '或者 = atau, dalam pernyataan.'],
  ['我有一个哥哥____一个妹妹。', 'Saya punya seorang kakak laki-laki dan seorang adik perempuan.', '和', ['还是', '但是', '所以'], 'Tambahan', '和 menghubungkan kata benda.'],
  ['我先吃饭，____去学校。', 'Saya makan dulu, lalu ke sekolah.', '然后', ['所以', '但是', '还是'], 'Urutan', '先 … 然后 = dulu … lalu.'],
  ['这是我买____书。', 'Ini buku yang saya beli.', '的', ['地', '得', '了'], 'Klausa relatif', 'klausa + 的 + kata benda.'],
  ['穿红衣服____人是我姐姐。', 'Orang yang memakai baju merah adalah kakakku.', '的', ['地', '得', '着'], 'Klausa relatif', 'klausa + 的 + kata benda.'],
  ['我吃饭____时候看电视。', 'Saya menonton TV ketika makan.', '的', ['了', '地', '得'], 'Waktu', '… 的时候 = ketika.'],
  ['____天气很冷，但是他没穿外套。', 'Meskipun dingin, dia tidak memakai jaket.', '虽然', ['因为', '所以', '或者'], 'Konsesi', '虽然 … 但是 = meskipun … tetapi.'],
  ['他很聪明，____很努力。', 'Dia pintar, juga rajin.', '也', ['还是', '但是', '所以'], 'Tambahan', '也 = juga (sebelum predikat).'],
  ['我一边听音乐，____做作业。', 'Saya mengerjakan PR sambil mendengarkan musik.', '一边', ['然后', '所以', '还是'], 'Bersamaan', '一边 … 一边 = sambil.'],
  ['下课____，我们去吃饭。', 'Setelah kelas, kita pergi makan.', '以后', ['以前', '的时候', '虽然'], 'Waktu', '… 以后 = setelah.'],
  ['睡觉____，我刷牙。', 'Sebelum tidur, saya sikat gigi.', '以前', ['以后', '然后', '所以'], 'Waktu', '… 以前 = sebelum.'],
  ['我喜欢猫，____不喜欢狗。', 'Saya suka kucing, tapi tidak suka anjing.', '可是', ['所以', '因为', '或者'], 'Kontras', '可是 = tetapi (lisan).'],
  ['今天很忙，____我不去了。', 'Hari ini sibuk, jadi saya tidak pergi.', '所以', ['但是', '因为', '还是'], 'Akibat', '所以 = jadi.'],
  ['你想去北京____上海？', 'Kamu mau ke Beijing atau Shanghai?', '还是', ['或者', '和', '但是'], 'Pilihan (tanya)', '还是 dalam pertanyaan.'],
  ['我昨天认识____朋友是日本人。', 'Teman yang saya kenal kemarin orang Jepang.', '的', ['地', '得', '了'], 'Klausa relatif', 'klausa + 的 + kata benda.'],
  ['这个苹果又大____甜。', 'Apel ini besar dan manis.', '又', ['也', '还', '就'], 'Dua sifat', '又 … 又 = … dan juga ….'],
  ['他先洗手，____吃饭。', 'Dia cuci tangan dulu, lalu makan.', '再', ['又', '就', '才'], 'Urutan', '先 … 再 = dulu … baru.'],
  ['我饿了，____想吃点儿东西。', 'Saya lapar, jadi ingin makan sesuatu.', '所以', ['但是', '或者', '还是'], 'Akibat', '所以 = jadi.'],
  ['她会说中文，____会说英文。', 'Dia bisa bahasa Mandarin, juga bisa bahasa Inggris.', '也', ['还是', '所以', '但是'], 'Tambahan', '也 = juga.'],
  ['我们____吃饭一边聊天。', 'Kami mengobrol sambil makan.', '一边', ['然后', '所以', '还是'], 'Bersamaan', '一边 … 一边 = sambil.'],
  ['这是老师给我____礼物。', 'Ini hadiah yang diberikan guru kepada saya.', '的', ['地', '得', '了'], 'Klausa relatif', 'klausa + 的 + kata benda.'],
  ['我想喝水，____想吃饭。', 'Saya ingin minum, bukan makan.', '不', ['也', '还', '就'], 'Penyangkalan', '…，不 … = bukan ….'],
  ['你来____我去？', 'Kamu yang datang atau saya yang pergi?', '还是', ['或者', '和', '但是'], 'Pilihan (tanya)', '还是 dalam pertanyaan.'],
  ['我到家____，给你打电话。', 'Setelah sampai rumah, saya meneleponmu.', '以后', ['以前', '然后', '虽然'], 'Waktu', '… 以后 = setelah.'],
  ['她长得漂亮，____很善良。', 'Dia cantik, dan juga baik hati.', '而且', ['所以', '但是', '还是'], 'Tambahan', '而且 = lagi pula/dan juga.'],
  ['我们明天____后天去都可以。', 'Kita pergi besok atau lusa sama-sama bisa.', '或者', ['还是', '但是', '所以'], 'Pilihan (pernyataan)', '或者 = atau, dalam pernyataan.'],
];

export const mediumClauses: ChoiceTuple[] = [
  ['他____会说中文，而且会说日语。', 'Dia tidak hanya bisa Mandarin, tetapi juga Jepang.', '不但', ['虽然', '因为', '或者'], 'Tambahan bertingkat', '不但 … 而且 = tidak hanya … tetapi juga.'],
  ['这家饭店不但便宜，____好吃。', 'Restoran ini tidak hanya murah, tetapi juga enak.', '而且', ['但是', '所以', '还是'], 'Tambahan bertingkat', '不但 … 而且.'],
  ['他不是老师，____学生。', 'Dia bukan guru, melainkan murid.', '而是', ['但是', '所以', '或者'], 'Koreksi', '不是 … 而是 = bukan … melainkan.'],
  ['与其去爬山，____去游泳吧。', 'Daripada mendaki gunung, lebih baik kita berenang.', '不如', ['但是', '所以', '而且'], 'Perbandingan pilihan', '与其 … 不如 = daripada … lebih baik.'],
  ['____你帮了我，我才能完成。', 'Berkat bantuanmu, saya bisa menyelesaikannya.', '因为', ['虽然', '而且', '或者'], 'Sebab', '因为 … 才 = karena … baru.'],
  ['他学习很努力，____考了第一名。', 'Dia belajar keras, sehingga meraih juara satu.', '因此', ['但是', '而且', '或者'], 'Akibat formal', '因此 = oleh karena itu.'],
  ['我们等了很久，他____没来。', 'Kami menunggu lama, tapi dia tetap tidak datang.', '还是', ['所以', '而且', '或者'], 'Tetap', '还是 = tetap saja.'],
  ['他一回家____开始玩游戏。', 'Begitu pulang, dia langsung main game.', '就', ['才', '还', '也'], 'Segera', '一 … 就 = begitu … langsung.'],
  ['我等了半天他____来。', 'Saya menunggu lama, baru dia datang.', '才', ['就', '还', '也'], 'Terlambat', '… 才 = baru (terlambat).'],
  ['他又帅____有钱。', 'Dia tampan dan kaya.', '又', ['也', '还', '就'], 'Dua sifat', '又 … 又.'],
  ['我们先讨论，____做决定。', 'Kita diskusikan dulu, setelah itu baru memutuskan.', '然后', ['所以', '虽然', '而且'], 'Urutan', '先 … 然后.'],
  ['他没复习，____考得不好。', 'Dia tidak mengulang pelajaran, akibatnya nilai ujiannya jelek.', '结果', ['但是', '而且', '或者'], 'Hasil', '结果 = akibatnya.'],
  ['我本来想去，____临时有事。', 'Tadinya saya ingin pergi, tapi mendadak ada urusan.', '可是', ['所以', '而且', '还是'], 'Kontras', '本来 … 可是.'],
  ['我觉得冷，____关上了窗户。', 'Saya merasa dingin, maka menutup jendela.', '于是', ['但是', '而且', '或者'], 'Urutan akibat', '于是 = maka (lalu).'],
  ['____我说的是对的，他也不听。', 'Walaupun yang saya katakan benar, dia tetap tidak mendengarkan.', '尽管', ['因为', '所以', '而且'], 'Konsesi', '尽管 … 也/还是 = walaupun.'],
  ['我喜欢看书，____喜欢旅行。', 'Saya suka membaca, selain itu suka bepergian.', '另外', ['所以', '但是', '还是'], 'Tambahan', '另外 = selain itu.'],
  ['他说的话我____不懂。', 'Kata-katanya sama sekali tidak saya pahami.', '一点儿也', ['又', '还是', '而且'], 'Penegasan negatif', '一点儿也不 = sama sekali tidak.'],
  ['你跟我来，____你会迷路。', 'Ikut aku, kalau tidak kamu akan tersesat.', '不然', ['所以', '而且', '还是'], 'Peringatan', '不然 = kalau tidak.'],
  ['妈妈做____菜很好吃。', 'Masakan yang dibuat ibu sangat enak.', '的', ['地', '得', '了'], 'Klausa relatif', 'klausa + 的 + kata benda.'],
  ['我们____吃饭，一边聊天吧。', 'Ayo kita makan sambil mengobrol.', '一边', ['然后', '所以', '还是'], 'Bersamaan', '一边 … 一边 = sambil.'],
  ['他学了三年中文，____说得很流利。', 'Dia belajar Mandarin tiga tahun, jadi bicaranya lancar.', '所以', ['但是', '或者', '而是'], 'Akibat', '所以 = jadi.'],
  ['我不是不想去，____没时间。', 'Bukannya saya tidak mau pergi, melainkan tidak ada waktu.', '而是', ['但是', '所以', '而且'], 'Koreksi', '不是 … 而是.'],
  ['他工作很忙，____还坚持学习。', 'Pekerjaannya sibuk, tapi dia tetap rutin belajar.', '但', ['所以', '或者', '而是'], 'Kontras', '但 = tetapi (ringkas).'],
  ['你最好早点儿走，____会堵车。', 'Sebaiknya kamu berangkat lebih awal, kalau tidak bisa macet.', '否则', ['所以', '而且', '还是'], 'Peringatan', '否则 = kalau tidak.'],
  ['____他很忙，还是来帮我了。', 'Meskipun sibuk, dia tetap datang membantuku.', '虽然', ['因为', '所以', '而且'], 'Konsesi', '虽然 … 还是.'],
  ['他每天锻炼，____身体很好。', 'Dia berolahraga setiap hari, sehingga badannya sehat.', '所以', ['但是', '或者', '而是'], 'Akibat', '所以 = jadi.'],
  ['我做完作业____，就睡觉了。', 'Setelah selesai mengerjakan PR, saya langsung tidur.', '以后', ['以前', '而且', '所以'], 'Waktu', '… 以后，就 ….'],
  ['他____走边唱。', 'Dia berjalan sambil bernyanyi.', '边', ['又', '就', '才'], 'Bersamaan', '边 V1 边 V2 = sambil.'],
  ['这个问题既重要____复杂。', 'Masalah ini penting sekaligus rumit.', '又', ['也', '还', '就'], 'Dua sifat', '既 … 又 = … sekaligus ….'],
  ['他是我们班学习最好____学生。', 'Dia murid yang paling bagus belajarnya di kelas kami.', '的', ['地', '得', '了'], 'Klausa relatif', 'klausa + 的 + kata benda.'],
];

export const hardClauses: ChoiceTuple[] = [
  ['他很有能力，____缺少经验。', 'Dia sangat mampu, namun kurang pengalaman.', '然而', ['因此', '而且', '于是'], 'Kontras formal', '然而 = namun.'],
  ['____我们努力，结果还是失败了。', 'Meskipun kami berusaha, hasilnya tetap gagal.', '尽管', ['既然', '因此', '而且'], 'Konsesi', '尽管 … 还是 = meskipun.'],
  ['____大家都同意，那我们就开始吧。', 'Karena semua sudah setuju, mari kita mulai.', '既然', ['尽管', '然而', '因此'], 'Premis', '既然 … 就 = karena memang ….'],
  ['他连饭____没吃就走了。', 'Dia pergi bahkan tanpa makan.', '都', ['就', '才', '再'], 'Penekanan', '连 … 都 = bahkan … pun.'],
  ['这本书不仅内容丰富，____语言生动。', 'Buku ini tidak hanya isinya kaya, bahasanya juga hidup.', '而且', ['然而', '因而', '尽管'], 'Tambahan bertingkat', '不仅 … 而且 = tidak hanya … tetapi juga.'],
  ['这件事____你不说，我也知道。', 'Hal ini meskipun kamu tidak bilang, aku tetap tahu.', '即使', ['既然', '因此', '于是'], 'Konsesi hipotetis', '即使 … 也 = sekalipun.'],
  ['他工作认真，____得到了领导的表扬。', 'Dia bekerja dengan serius, maka mendapat pujian pimpinan.', '因而', ['然而', '尽管', '何况'], 'Akibat formal', '因而 = oleh karena itu.'],
  ['这个问题连专家都解决不了，____我们呢？', 'Masalah ini ahli pun tidak bisa menyelesaikan, apalagi kami?', '何况', ['因而', '然而', '既然'], 'Apalagi', '连 … 都 …，何况 = apalagi.'],
  ['要么你去，____我去，总得有人去。', 'Entah kamu atau aku yang pergi, pokoknya harus ada yang pergi.', '要么', ['不但', '尽管', '既然'], 'Pilihan tegas', '要么 … 要么 = entah … atau.'],
  ['他宁可走路，____不坐出租车。', 'Dia lebih rela berjalan kaki daripada naik taksi.', '也', ['就', '才', '还'], 'Preferensi', '宁可 … 也不 = lebih rela … daripada.'],
  ['我们应该多运动，____保持健康。', 'Kita harus banyak berolahraga agar tetap sehat.', '以便', ['因而', '然而', '何况'], 'Tujuan', '以便 = agar (formal).'],
  ['你要早点儿出发，____迟到。', 'Kamu harus berangkat lebih awal, supaya tidak terlambat.', '以免', ['以便', '因而', '何况'], 'Mencegah', '以免 = supaya tidak.'],
  ['他并非不聪明，____不够努力。', 'Bukannya dia tidak pintar, melainkan kurang rajin.', '而是', ['然而', '因而', '何况'], 'Koreksi formal', '并非 … 而是 = bukannya … melainkan.'],
  ['学习____为了考试，而是为了提高能力。', 'Belajar bukan untuk ujian, melainkan untuk meningkatkan kemampuan.', '不是', ['不仅', '尽管', '既然'], 'Koreksi', '不是 … 而是.'],
  ['他是一个既热情____负责的人。', 'Dia orang yang ramah sekaligus bertanggung jawab.', '又', ['也', '还', '就'], 'Dua sifat', '既 … 又.'],
  ['____发生了什么，我都支持你。', 'Apa pun yang terjadi, aku mendukungmu.', '无论', ['尽管', '既然', '因而'], 'Tanpa syarat', '无论 … 都 = apa pun.'],
  ['这次失败不但没让他放弃，____让他更努力了。', 'Kegagalan ini bukan membuatnya menyerah, malah membuatnya lebih giat.', '反而', ['而且', '因而', '何况'], 'Kebalikan', '不但没 … 反而 = bukannya … malah.'],
  ['我们先完成这个，____再说别的。', 'Kita selesaikan ini dulu, hal lain nanti saja.', '然后', ['然而', '因而', '何况'], 'Urutan', '先 … 然后 … 再.'],
  ['他说的____你说的完全不同。', 'Yang dia katakan sama sekali berbeda dengan yang kamu katakan.', '跟', ['给', '为', '离'], 'Perbandingan', 'A 跟 B 不同.'],
  ['____这样，我们还是要试一试。', 'Meski demikian, kita tetap harus mencoba.', '即便', ['因而', '于是', '何况'], 'Konsesi', '即便如此 = meski demikian.'],
  ['他们讨论了很久，____得出了结论。', 'Mereka berdiskusi lama, akhirnya mencapai kesimpulan.', '终于', ['然而', '何况', '以免'], 'Akhirnya', '终于 = akhirnya.'],
  ['____你已经知道了，我就不多说了。', 'Karena kamu sudah tahu, saya tidak akan bicara banyak.', '既然', ['尽管', '何况', '以免'], 'Premis', '既然 … 就.'],
  ['____他年纪大了，但是身体很好。', 'Meskipun dia sudah tua, badannya sehat.', '虽然', ['既然', '因而', '以便'], 'Konsesi', '虽然 … 但是.'],
  ['这个方法简单，____效果很好。', 'Cara ini sederhana, dan lagi hasilnya bagus.', '并且', ['然而', '因而', '以免'], 'Tambahan formal', '并且 = dan lagi.'],
  ['他总是说得多做得少，____大家都不信任他。', 'Dia selalu banyak bicara sedikit kerja, sehingga semua orang tidak percaya padanya.', '以致', ['以便', '以免', '何况'], 'Akibat buruk', '以致 = sehingga (akibat buruk).'],
  ['与其说他不想来，____说他没时间来。', 'Daripada dibilang dia tidak mau datang, lebih tepat dia tidak punya waktu.', '不如', ['而且', '因而', '何况'], 'Perbandingan pilihan', '与其说 … 不如说 = daripada dibilang … lebih tepat ….'],
  ['不管问题大____小，都要认真对待。', 'Masalah besar atau kecil, semuanya harus ditangani serius.', '还是', ['而且', '但是', '所以'], 'Tanpa syarat', '不管 … 还是 … 都.'],
  ['我以为他不会来，____他真的来了。', 'Saya kira dia tidak akan datang, tak disangka dia benar-benar datang.', '没想到', ['因而', '以便', '何况'], 'Di luar dugaan', '没想到 = tak disangka.'],
  ['这些话有的是真的，____是假的。', 'Kata-kata ini sebagian benar, sebagian palsu.', '有的', ['不仅', '尽管', '既然'], 'Sebagian', '有的 … 有的 = sebagian … sebagian.'],
  ['他努力了这么多年，____实现了梦想。', 'Setelah berusaha bertahun-tahun, dia akhirnya mewujudkan mimpinya.', '终于', ['然而', '以免', '何况'], 'Akhirnya', '终于 = akhirnya.'],
];
