// Mandarin Error Fix: [wrong sentence, corrected sentence, translation, type, rule, two more wrong versions], 30 per level.
// Every alternative is ungrammatical, so exactly one option is correct.
export type ErrorFixTuple = [wrong: string, correct: string, translation: string, type: string, rule: string, alternatives: [string, string]];

const WORD_ORDER = 'Urutan dasar: Subjek + Waktu + Tempat/Cara + Kata kerja + Objek.';
const MEASURE = 'Bilangan + kata bantu bilangan + kata benda.';
const PAST_NEG = 'Kejadian lampau dinegasikan dengan 没, bukan 不.';
const ADJ = 'Adjektiva menjadi predikat tanpa 是, biasanya dengan 很.';
const Q_PARTICLE = 'Pertanyaan dengan kata tanya atau pola positif-negatif tidak memakai 吗.';

export const easyErrors: ErrorFixTuple[] = [
  ['我是很高兴。', '我很高兴。', 'Saya sangat senang.', 'Predikat adjektiva', ADJ, ['我是高兴。', '我高兴是。']],
  ['我不去了昨天。', '昨天我没去。', 'Kemarin saya tidak pergi.', 'Negasi lampau', PAST_NEG, ['昨天我不去。', '我没去了昨天。']],
  ['他有二个姐姐。', '他有两个姐姐。', 'Dia punya dua kakak perempuan.', '两 vs 二', 'Sebelum kata bantu bilangan, angka 2 memakai 两.', ['他有二姐姐。', '他有两姐姐。']],
  ['我吃饭在家。', '我在家吃饭。', 'Saya makan di rumah.', 'Urutan tempat', 'Keterangan tempat (在 …) diletakkan sebelum kata kerja.', ['在家我饭吃。', '我吃在家饭。']],
  ['你是不是学生吗？', '你是不是学生？', 'Kamu pelajar, bukan?', 'Partikel tanya', Q_PARTICLE, ['你是不学生吗？', '你是不是学生呢吗？']],
  ['我很喜欢吃苹果们。', '我很喜欢吃苹果。', 'Saya sangat suka makan apel.', 'Penanda jamak', '们 hanya dipakai untuk orang, bukan benda.', ['我很喜欢苹果们吃。', '我喜欢很吃苹果们。']],
  ['这是书我的。', '这是我的书。', 'Ini bukuku.', 'Kepemilikan', 'Pemilik + 的 diletakkan sebelum kata benda.', ['这是的我书。', '这是书的我。']],
  ['我明天去了北京。', '我明天去北京。', 'Besok saya ke Beijing.', 'Aspek 了', '了 menandai tindakan selesai, tidak untuk rencana besok.', ['我明天去过北京。', '我去了明天北京。']],
  ['他不是高。', '他不高。', 'Dia tidak tinggi.', 'Predikat adjektiva', 'Adjektiva dinegasikan langsung dengan 不, tanpa 是.', ['他没是高。', '他高不是。']],
  ['我不有钱。', '我没有钱。', 'Saya tidak punya uang.', 'Negasi 有', '有 selalu dinegasikan dengan 没.', ['我有不钱。', '我没钱有。']],
  ['我在学校学习中文每天。', '我每天在学校学习中文。', 'Setiap hari saya belajar Mandarin di sekolah.', 'Urutan waktu', WORD_ORDER, ['每天我学习中文在学校。', '我在学校每天中文学习。']],
  ['我买了三书。', '我买了三本书。', 'Saya membeli tiga buku.', 'Kata bantu bilangan', MEASURE, ['我买了书三本。', '我买了三个本书。']],
  ['我妈妈医生是。', '我妈妈是医生。', 'Ibu saya dokter.', 'Kalimat 是', 'Subjek + 是 + kata benda.', ['我的妈妈是的医生。', '是我妈妈医生。']],
  ['我去学校坐公交车。', '我坐公交车去学校。', 'Saya ke sekolah naik bus.', 'Urutan cara', 'Cara (naik …) diletakkan sebelum kata kerja tujuan.', ['我去坐公交车学校。', '坐公交车我学校去。']],
  ['他喝了咖啡昨天。', '他昨天喝了咖啡。', 'Kemarin dia minum kopi.', 'Urutan waktu', WORD_ORDER, ['昨天他了喝咖啡。', '他喝咖啡了昨天。']],
  ['他比我很高。', '他比我高。', 'Dia lebih tinggi dariku.', 'Perbandingan 比', '很 tidak dipakai dalam kalimat 比.', ['他比我是高。', '他高比我。']],
  ['我叫的王明。', '我叫王明。', 'Nama saya Wang Ming.', '叫 + nama', '叫 langsung diikuti nama.', ['王明我叫是。', '我叫是王明的。']],
  ['你去哪儿吗？', '你去哪儿？', 'Kamu pergi ke mana?', 'Partikel tanya', Q_PARTICLE, ['你吗去哪儿？', '你去吗哪儿？']],
  ['我昨天不看电视。', '我昨天没看电视。', 'Kemarin saya tidak menonton TV.', 'Negasi lampau', PAST_NEG, ['我昨天没看了电视。', '我昨天不看了电视。']],
  ['这个是很好。', '这个很好。', 'Ini sangat bagus.', 'Predikat adjektiva', ADJ, ['这个是好很。', '这个好是很。']],
  ['我有一书。', '我有一本书。', 'Saya punya satu buku.', 'Kata bantu bilangan', MEASURE, ['我有书一本。', '我有一书本。']],
  ['我们去吃饭一起。', '我们一起去吃饭。', 'Kita pergi makan bersama.', 'Posisi 一起', '一起 diletakkan sebelum kata kerja.', ['我们吃饭一起去。', '一起我们去吃饭。']],
  ['他很喜欢狗和也喜欢猫。', '他很喜欢狗，也喜欢猫。', 'Dia suka anjing dan juga kucing.', '和 vs 也', '和 hanya menghubungkan kata benda, bukan klausa.', ['他很喜欢狗和猫也。', '他很喜欢狗，和喜欢猫。']],
  ['我八点起床每天。', '我每天八点起床。', 'Setiap hari saya bangun jam delapan.', 'Urutan waktu', 'Waktu umum (setiap hari) sebelum jam, keduanya sebelum kata kerja.', ['我起床八点每天。', '每天我起床八点。']],
  ['她很漂亮的女孩。', '她是很漂亮的女孩。', 'Dia gadis yang sangat cantik.', 'Kalimat 是', '是 diperlukan sebelum frasa kata benda.', ['她很是漂亮女孩。', '她漂亮的很女孩。']],
  ['我爸爸银行在工作。', '我爸爸在银行工作。', 'Ayah saya bekerja di bank.', 'Urutan tempat', 'Keterangan tempat (在 …) diletakkan sebelum kata kerja.', ['我爸爸是在银行的工作。', '在我爸爸银行工作。']],
  ['我们是学生都。', '我们都是学生。', 'Kami semua pelajar.', 'Posisi 都', '都 diletakkan setelah subjek, sebelum kata kerja/是.', ['都我们是学生。', '我们是都学生。']],
  ['他是老师也。', '他也是老师。', 'Dia juga guru.', 'Posisi 也', '也 diletakkan setelah subjek, sebelum kata kerja/是.', ['也他是老师。', '他是也老师。']],
  ['你喝不喝咖啡吗？', '你喝不喝咖啡？', 'Kamu minum kopi atau tidak?', 'Partikel tanya', Q_PARTICLE, ['你不喝喝咖啡？', '你喝咖啡不喝吗？']],
  ['我在吃饭现在。', '我现在在吃饭。', 'Saya sedang makan sekarang.', 'Urutan waktu', WORD_ORDER, ['现在我吃饭在。', '我在现在吃饭。']],
];

export const mediumErrors: ErrorFixTuple[] = [
  ['我把书看。', '我把书看完了。', 'Saya sudah selesai membaca buku itu.', 'Kalimat 把', '把 memerlukan hasil/komplemen setelah kata kerja.', ['我把看完书了。', '我看完把书了。']],
  ['他跑很快。', '他跑得很快。', 'Dia berlari sangat cepat.', 'Komplemen derajat', 'V + 得 + penilaian.', ['他跑的很快。', '他很快得跑。']],
  ['我两年学中文了。', '我学了两年中文了。', 'Saya sudah belajar Mandarin dua tahun.', 'Durasi', 'Durasi diletakkan setelah kata kerja.', ['我学中文了两年。', '我两年了学中文。']],
  ['我比他没有高。', '我没有他高。', 'Saya tidak setinggi dia.', 'Perbandingan negatif', 'A + 没有 + B + adjektiva.', ['我高没有他。', '我没有高他。']],
  ['我见面他了。', '我跟他见面了。', 'Saya bertemu dengannya.', 'Kata kerja terpisah', '见面 tidak langsung diikuti objek; pakai 跟 … 见面.', ['我见面了他。', '我见他面了。']],
  ['我已经吃饭过。', '我已经吃饭了。', 'Saya sudah makan.', '已经 … 了', '已经 berpasangan dengan 了.', ['我已经了吃饭。', '我已经吃了饭过。']],
  ['我帮忙你。', '我帮你。', 'Saya membantumu.', 'Kata kerja terpisah', '帮忙 tidak langsung diikuti objek.', ['我帮忙了你。', '我你帮忙。']],
  ['这本书被我看。', '这本书被我看完了。', 'Buku ini sudah selesai saya baca.', 'Kalimat 被', '被 memerlukan hasil atau 了 setelah kata kerja.', ['这本书我被看完了。', '被这本书我看完了。']],
  ['我很感兴趣中国文化。', '我对中国文化很感兴趣。', 'Saya sangat tertarik dengan budaya Tiongkok.', '对 … 感兴趣', 'Topik diletakkan dengan 对 sebelum 感兴趣.', ['我感兴趣对中国文化。', '我很对感兴趣中国文化。']],
  ['我从来不去过上海。', '我从来没去过上海。', 'Saya belum pernah ke Shanghai.', 'Negasi pengalaman', 'Pengalaman (V + 过) dinegasikan dengan 没.', ['我从来不去上海过。', '我从来没去上海了过。']],
  ['你说得中文很好。', '你中文说得很好。', 'Bahasa Mandarinmu bagus.', 'Komplemen + objek', 'Objek diletakkan sebelum V + 得, atau ulangi kata kerjanya.', ['你说中文得很好。', '你中文得说很好。']],
  ['我们是在2020年认识。', '我们是在2020年认识的。', 'Kami berkenalan pada tahun 2020.', '是 … 的', '是 … 的 menekankan waktu/tempat/cara kejadian lampau.', ['我们在2020年认识是的。', '我们是认识的在2020年。']],
  ['他慢慢儿走得了。', '他慢慢儿地走了。', 'Dia berjalan perlahan.', 'Keterangan 地', 'Keterangan cara + 地 + kata kerja.', ['他走慢慢儿地了。', '他地慢慢儿走了。']],
  ['我两次去过北京。', '我去过两次北京。', 'Saya pernah ke Beijing dua kali.', 'Frekuensi', 'Frekuensi diletakkan setelah V + 过.', ['我去两次过北京。', '我去过北京二次。']],
  ['这个电影很有意思极了。', '这个电影有意思极了。', 'Film ini menarik sekali.', '极了', '… 极了 tidak dipakai bersama 很.', ['这个电影极了有意思。', '这个电影很极了有意思。']],
  ['他还没有来了。', '他还没有来。', 'Dia belum datang.', 'Negasi 了', 'Kalimat dengan 没(有) tidak memakai 了.', ['他没有还来。', '他还没有了来。']],
  ['我在等你半个小时了。', '我等了你半个小时了。', 'Saya sudah menunggumu setengah jam.', 'Durasi', 'Durasi diletakkan setelah V (+ 了) + objek.', ['我半个小时等了你了。', '我等半个小时了你了。']],
  ['他打篮球得很好。', '他打篮球打得很好。', 'Dia bermain basket dengan bagus.', 'Pengulangan kata kerja', 'V + O + V + 得 + penilaian.', ['他打得篮球很好。', '他很好打篮球得。']],
  ['我觉得他对是。', '我觉得他是对的。', 'Saya rasa dia benar.', '是 … 的', 'Penilaian ditegaskan dengan 是 … 的.', ['我是觉得对他的。', '我觉得的他是对。']],
  ['你能不能帮我吗？', '你能不能帮我？', 'Bisakah kamu membantuku?', 'Partikel tanya', Q_PARTICLE, ['你能帮不帮我吗？', '你不能能帮我？']],
  ['我们见面在咖啡馆。', '我们在咖啡馆见面。', 'Kami bertemu di kafe.', 'Urutan tempat', 'Keterangan tempat (在 …) diletakkan sebelum kata kerja.', ['在咖啡馆我们面见。', '我们见在咖啡馆面。']],
  ['我把作业忘了在家。', '我把作业忘在家里了。', 'PR saya tertinggal di rumah.', '把 + V在', '把 + O + V + 在 + tempat.', ['我把忘作业在家了。', '我在家把忘了作业。']],
  ['我们一起去看电影，好不好吗？', '我们一起去看电影，好不好？', 'Ayo nonton film bersama, ya?', 'Partikel tanya', Q_PARTICLE, ['我们一起去看电影，好吗不好？', '我们一起去看电影，不好好？']],
  ['他说中文比我很好。', '他中文说得比我好。', 'Bahasa Mandarinnya lebih baik dariku.', 'Perbandingan + 得', 'O + V + 得 + 比 + B + adjektiva, tanpa 很.', ['他中文说比我得好。', '他说中文得比我好。']],
  ['天气越来越很冷。', '天气越来越冷了。', 'Cuaca makin dingin.', '越来越', '越来越 + adjektiva, tanpa 很.', ['天气越来越冷很。', '天气越很来越冷。']],
  ['他会来明天。', '他明天会来。', 'Besok dia akan datang.', 'Urutan waktu', WORD_ORDER, ['明天他来会。', '他来会明天。']],
  ['这件衣服太贵了很。', '这件衣服太贵了。', 'Baju ini terlalu mahal.', '太 … 了', '太 + adjektiva + 了, tanpa 很.', ['这件衣服很太贵了。', '这件衣服贵太了。']],
  ['他已经家回了。', '他已经回家了。', 'Dia sudah pulang.', 'Urutan objek', 'Kata kerja diletakkan sebelum objek tempat.', ['他已经回了去家。', '他家已经回了。']],
  ['我不听懂他说的话。', '我听不懂他说的话。', 'Saya tidak paham ucapannya.', 'Komplemen potensial', 'Tidak bisa = V + 不 + hasil.', ['我听懂不他说的话。', '我没听得懂他说的话。']],
  ['你吃过饭了没有吗？', '你吃过饭了没有？', 'Kamu sudah makan belum?', 'Partikel tanya', Q_PARTICLE, ['你吃过没有饭了吗？', '你没有吃过饭了吗？']],
];

export const hardErrors: ErrorFixTuple[] = [
  ['因为天气不好，但是我们没去。', '因为天气不好，所以我们没去。', 'Karena cuaca buruk, kami tidak pergi.', 'Pasangan konjungsi', '因为 berpasangan dengan 所以.', ['因为天气不好，而且我们没去。', '虽然天气不好，所以我们没去。']],
  ['虽然他很累，所以他还在工作。', '虽然他很累，但是他还在工作。', 'Meskipun lelah, dia masih bekerja.', 'Pasangan konjungsi', '虽然 berpasangan dengan 但是/可是.', ['虽然他很累，因此他还在工作。', '因为他很累，但是他还在工作。']],
  ['只要你努力，才能成功。', '只要你努力，就能成功。', 'Asalkan berusaha, kamu bisa berhasil.', '只要 … 就', '只要 (syarat cukup) berpasangan dengan 就.', ['只有你努力，就能成功。', '只要你努力，都能成功。']],
  ['只有多练习，就能说得流利。', '只有多练习，才能说得流利。', 'Hanya dengan banyak berlatih baru bisa lancar.', '只有 … 才', '只有 (syarat mutlak) berpasangan dengan 才.', ['只要多练习，才能说得流利。', '只有多练习，都能说得流利。']],
  ['我的钱包被偷。', '我的钱包被偷了。', 'Dompet saya dicuri.', 'Kalimat 被', '被 memerlukan hasil atau 了 setelah kata kerja.', ['我的钱包偷被了。', '被我的钱包偷了。']],
  ['他把这本书没看完。', '他没把这本书看完。', 'Dia tidak menyelesaikan membaca buku ini.', 'Negasi 把', 'Negasi diletakkan sebelum 把.', ['他把没这本书看完。', '他把这本书看没完。']],
  ['他会说中文不但，而且会说日语。', '他不但会说中文，而且会说日语。', 'Dia tidak hanya bisa Mandarin, tetapi juga Jepang.', 'Posisi 不但', '不但 diletakkan setelah subjek bila subjeknya sama.', ['他不但会说中文，但是会说日语。', '不但会说中文他，而且会说日语。']],
  ['连小孩子知道。', '连小孩子都知道。', 'Bahkan anak kecil pun tahu.', '连 … 都', '连 berpasangan dengan 都/也.', ['连小孩子就知道。', '小孩子连知道。']],
  ['我越学越很喜欢中文。', '我越学越喜欢中文。', 'Makin belajar, saya makin suka Mandarin.', '越 … 越', '越 … 越 + adjektiva/kata kerja, tanpa 很.', ['我越学越喜欢很中文。', '我越学很越喜欢中文。']],
  ['除了中文以外，我都会说英语。', '除了中文以外，我还会说英语。', 'Selain Mandarin, saya juga bisa bahasa Inggris.', '除了 … 还', '除了 … (以外) + 还 = selain itu juga.', ['除了中文以外，我就会说英语。', '除了中文以外，我才会说英语。']],
  ['即使下雨，我们就去。', '即使下雨，我们也去。', 'Meskipun hujan, kami tetap pergi.', '即使 … 也', '即使 berpasangan dengan 也.', ['即使下雨，我们才去。', '即使下雨，我们所以去。']],
  ['不管天气好，我们都去。', '不管天气好不好，我们都去。', 'Baik cuaca bagus atau tidak, kami tetap pergi.', '不管 … 都', '不管 diikuti pilihan atau kata tanya.', ['不管天气很好，我们都去。', '不管天气好，我们就去。']],
  ['我把作业做了完。', '我把作业做完了。', 'Saya sudah menyelesaikan PR.', 'Komplemen hasil', '了 diletakkan setelah komplemen hasil, bukan di antaranya.', ['我把作业了做完。', '我把做完作业了。']],
  ['他是去年来中国了。', '他是去年来中国的。', 'Dia datang ke Tiongkok tahun lalu.', '是 … 的', 'Pola 是 … 的 ditutup dengan 的, bukan 了.', ['他是来中国去年的。', '他去年是来了中国。']],
  ['我想不出来他的名字。', '我想不起来他的名字。', 'Saya tidak bisa mengingat namanya.', '起来 vs 出来', '起来 = mengingat kembali; 出来 = menemukan ide baru.', ['我想得起来不他的名字。', '我想起来不他的名字。']],
  ['他一下课，才回家了。', '他一下课就回家了。', 'Begitu kelas selesai, dia langsung pulang.', '一 … 就', '一 berpasangan dengan 就.', ['他就下课一回家了。', '他一下课都回家了。']],
  ['他跟我一样很高。', '他跟我一样高。', 'Dia sama tinggi denganku.', '跟 … 一样', '一样 + adjektiva, tanpa 很.', ['他一样跟我高。', '他跟我很一样高。']],
  ['你把窗户开。', '你把窗户打开。', 'Bukalah jendela.', 'Kalimat 把', '把 memerlukan kata kerja lengkap dengan hasilnya.', ['你把打开窗户。', '你打开把窗户。']],
  ['他比我三岁大。', '他比我大三岁。', 'Dia tiga tahun lebih tua dariku.', 'Selisih 比', 'Selisih diletakkan setelah adjektiva.', ['他三岁比我大。', '他大比我三岁。']],
  ['学中文很有帮助对我。', '学中文对我很有帮助。', 'Belajar Mandarin sangat membantu saya.', '对 … 有帮助', '对 + orang diletakkan sebelum 有帮助.', ['学中文很对我有帮助。', '对我学中文很帮助有。']],
  ['这件事我已经告诉了过他。', '这件事我已经告诉过他了。', 'Hal ini sudah pernah saya beritahukan kepadanya.', 'Aspek 过', '过 langsung setelah kata kerja; 了 di akhir kalimat.', ['这件事我已经过告诉他了。', '这件事我已经告诉他过了。']],
  ['保护环境是每个人们的责任。', '保护环境是每个人的责任。', 'Melindungi lingkungan adalah tanggung jawab setiap orang.', '每 + 们', 'Setelah 每个 tidak memakai 们.', ['保护环境是每个的人责任。', '保护环境是人每个的责任。']],
  ['他累得很睡着了。', '他累得睡着了。', 'Dia lelah sampai tertidur.', 'Komplemen akibat', 'Adj + 得 + akibat, tanpa 很.', ['他得累睡着了。', '他累睡得着了。']],
  ['与其坐出租车，还是坐地铁。', '与其坐出租车，不如坐地铁。', 'Daripada naik taksi, lebih baik naik subway.', '与其 … 不如', '与其 berpasangan dengan 不如.', ['与其坐出租车，而且坐地铁。', '与其坐出租车，就坐地铁。']],
  ['他不是老师，但是医生。', '他不是老师，而是医生。', 'Dia bukan guru, melainkan dokter.', '不是 … 而是', '不是 A 而是 B = bukan A melainkan B.', ['他不是老师，所以医生。', '他不是老师，并且医生。']],
  ['既然你来了，才多坐一会儿。', '既然你来了，就多坐一会儿。', 'Karena sudah datang, duduklah lebih lama.', '既然 … 就', '既然 berpasangan dengan 就.', ['既然你来了，都多坐一会儿。', '既然你来了，但是多坐一会儿。']],
  ['为了健康，所以我每天跑步。', '为了健康，我每天跑步。', 'Demi kesehatan, saya lari setiap hari.', '为了', '为了 (tujuan) tidak berpasangan dengan 所以.', ['为了健康，但是我每天跑步。', '为了健康，因此我每天跑步。']],
  ['他把杯子打破。', '他把杯子打破了。', 'Dia memecahkan gelasnya.', 'Kalimat 把', 'Kalimat 把 yang sudah terjadi ditutup dengan 了.', ['他把打破杯子了。', '他打破把杯子了。']],
  ['这个菜被吃完我了。', '这个菜被我吃完了。', 'Masakan ini sudah saya habiskan.', 'Kalimat 被', 'Objek + 被 + pelaku + V + hasil.', ['这个菜我被吃完了。', '被这个菜我吃完了。']],
  ['如果明天下雨，我们才不去了。', '如果明天下雨，我们就不去了。', 'Kalau besok hujan, kami tidak jadi pergi.', '如果 … 就', '如果 berpasangan dengan 就.', ['如果明天下雨，所以我们不去了。', '如果明天下雨，但是我们不去了。']],
];
