// Mandarin Liangci Dash (article-dash mode): measure words, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule]
// Wrong options leave out measure words that would also be correct (个 for 人, 张 for 椅子, 条 for 狗).
import type { ChoiceTuple } from './questions';

export const easyMeasureWords: ChoiceTuple[] = [
  ['我有三____书。', 'Saya punya tiga buku.', '本', ['张', '只', '条'], 'Buku', '本 untuk buku, kamus, majalah.'],
  ['我家有两____猫。', 'Di rumahku ada dua kucing.', '只', ['本', '条', '张'], 'Hewan kecil', '只 untuk banyak hewan kecil: kucing, burung.'],
  ['桌子上有一____纸。', 'Di meja ada selembar kertas.', '张', ['本', '只', '条'], 'Benda datar', '张 untuk benda datar: kertas, tiket, meja.'],
  ['他买了一____裤子。', 'Dia membeli sehelai celana.', '条', ['件', '张', '本'], 'Benda panjang', '条 untuk benda panjang: celana, jalan, sungai.'],
  ['我想买一____衣服。', 'Saya ingin membeli sepotong baju.', '件', ['条', '张', '只'], 'Pakaian atas', '件 untuk baju atasan dan urusan.'],
  ['这____人是我的老师。', 'Orang ini guruku.', '个', ['只', '本', '条'], 'Umum', '个 adalah kata bantu bilangan umum, juga untuk orang.'],
  ['我要一____咖啡。', 'Saya mau secangkir kopi.', '杯', ['张', '本', '只'], 'Wadah', '杯 = secangkir/segelas.'],
  ['他喝了两____水。', 'Dia minum dua botol air.', '瓶', ['本', '张', '件'], 'Wadah', '瓶 = sebotol.'],
  ['我买了一____鞋。', 'Saya membeli sepasang sepatu.', '双', ['条', '张', '本'], 'Pasangan', '双 untuk benda berpasangan: sepatu, sumpit.'],
  ['那____车是我的。', 'Mobil itu milikku.', '辆', ['条', '张', '本'], 'Kendaraan', '辆 untuk kendaraan beroda.'],
  ['我买了一____鱼。', 'Saya membeli seekor ikan.', '条', ['张', '本', '件'], 'Hewan panjang', '条 untuk ikan, ular, anjing.'],
  ['我家有四____人。', 'Keluargaku ada empat orang.', '口', ['本', '张', '条'], 'Anggota keluarga', '口 untuk jumlah anggota keluarga.'],
  ['这____椅子很舒服。', 'Kursi ini nyaman.', '把', ['本', '条', '只'], 'Bergagang', '把 untuk benda bergagang: kursi, payung, pisau.'],
  ['他有一____狗。', 'Dia punya seekor anjing.', '只', ['本', '张', '件'], 'Hewan kecil', '只 (atau 条) untuk anjing.'],
  ['我写了一____信。', 'Saya menulis sepucuk surat.', '封', ['本', '件', '只'], 'Surat', '封 untuk surat dan email.'],
  ['这____词典很有用。', 'Kamus ini sangat berguna.', '本', ['张', '条', '只'], 'Buku', '本 untuk buku, kamus, majalah.'],
  ['我借了一____笔。', 'Saya meminjam sebatang pulpen.', '支', ['本', '张', '条'], 'Batang', '支 untuk pulpen dan benda seperti batang.'],
  ['那____树很高。', 'Pohon itu tinggi.', '棵', ['本', '张', '件'], 'Tanaman', '棵 untuk pohon dan tanaman.'],
  ['她送我一____花。', 'Dia memberiku setangkai bunga.', '朵', ['本', '件', '张'], 'Kuntum', '朵 untuk bunga dan awan.'],
  ['我们今天有三____课。', 'Hari ini kami ada tiga jam pelajaran.', '节', ['本', '张', '件'], 'Sesi', '节 untuk jam pelajaran.'],
  ['这____歌很好听。', 'Lagu ini enak didengar.', '首', ['本', '件', '张'], 'Lagu/puisi', '首 untuk lagu dan puisi.'],
  ['我看了一____电影。', 'Saya menonton sebuah film.', '部', ['本', '首', '件'], 'Karya', '部 untuk film dan karya panjang.'],
  ['我要两____票。', 'Saya mau dua lembar tiket.', '张', ['本', '件', '只'], 'Benda datar', '张 untuk tiket dan benda datar.'],
  ['他吃了一____苹果。', 'Dia makan sebuah apel.', '个', ['本', '张', '条'], 'Umum', '个 untuk buah dan benda umum.'],
  ['我们学校有一百____老师。', 'Sekolah kami ada seratus guru.', '位', ['本', '张', '条'], 'Orang (sopan)', '位 adalah kata bantu bilangan sopan untuk orang.'],
  ['我想喝一____茶。', 'Saya mau minum secangkir teh.', '杯', ['本', '张', '只'], 'Wadah', '杯 = secangkir/segelas.'],
  ['这____山很高。', 'Gunung ini tinggi.', '座', ['本', '条', '件'], 'Bangunan/gunung', '座 untuk gunung, jembatan, gedung.'],
  ['我们家有一____电脑。', 'Rumah kami punya satu komputer.', '台', ['本', '条', '张'], 'Mesin', '台 untuk mesin dan alat elektronik.'],
  ['这个苹果三____钱。', 'Apel ini harganya tiga yuan.', '块', ['本', '张', '条'], 'Uang', '块 = yuan dalam bahasa lisan.'],
  ['我买了一____蛋糕。', 'Saya membeli sepotong kue.', '块', ['本', '张', '条'], 'Potongan', '块 untuk potongan: kue, sabun, daging.'],
];

export const mediumMeasureWords: ChoiceTuple[] = [
  ['我写了一____文章。', 'Saya menulis sebuah artikel.', '篇', ['本', '首', '部'], 'Tulisan', '篇 untuk artikel, esai, karangan.'],
  ['昨天下了一____大雨。', 'Kemarin turun hujan deras.', '场', ['本', '条', '件'], 'Peristiwa', '场 untuk hujan, pertandingan, pertunjukan.'],
  ['我要一____牛肉面。', 'Saya mau semangkuk mi daging sapi.', '碗', ['杯', '瓶', '本'], 'Wadah', '碗 = semangkuk.'],
  ['他戴着一____帽子。', 'Dia memakai sebuah topi.', '顶', ['件', '条', '双'], 'Topi', '顶 untuk topi dan tenda.'],
  ['我家附近有一____银行。', 'Dekat rumahku ada sebuah bank.', '家', ['本', '条', '张'], 'Usaha', '家 untuk toko, bank, perusahaan.'],
  ['这是一____很大的房间。', 'Ini kamar yang sangat besar.', '间', ['本', '条', '张'], 'Ruangan', '间 untuk kamar dan ruangan.'],
  ['我买了一____巧克力。', 'Saya membeli sekotak cokelat.', '盒', ['瓶', '杯', '本'], 'Wadah', '盒 = sekotak.'],
  ['我买了一____饼干。', 'Saya membeli sebungkus biskuit.', '包', ['瓶', '杯', '本'], 'Wadah', '包 = sebungkus.'],
  ['我去过两____北京。', 'Saya sudah dua kali ke Beijing.', '次', ['本', '张', '条'], 'Frekuensi', '次 = kali (frekuensi).'],
  ['这本书我看了三____。', 'Buku ini sudah saya baca tiga kali (dari awal sampai akhir).', '遍', ['本', '张', '条'], 'Frekuensi utuh', '遍 = kali, dari awal sampai akhir.'],
  ['我去了一____超市。', 'Saya pergi ke supermarket (sekali jalan).', '趟', ['本', '张', '条'], 'Perjalanan', '趟 = sekali pergi-pulang.'],
  ['我们一天吃三____饭。', 'Kami makan tiga kali sehari.', '顿', ['本', '张', '条'], 'Waktu makan', '顿 untuk waktu makan.'],
  ['他做了一____菜。', 'Dia membuat satu hidangan.', '道', ['本', '张', '条'], 'Hidangan', '道 untuk hidangan, soal, pintu.'],
  ['农场里有十____牛。', 'Di peternakan ada sepuluh ekor sapi.', '头', ['本', '张', '件'], 'Hewan besar', '头 untuk sapi, babi, gajah.'],
  ['他骑着一____马。', 'Dia menunggang seekor kuda.', '匹', ['本', '张', '件'], 'Kuda', '匹 untuk kuda dan kain.'],
  ['我买了一____西装。', 'Saya membeli satu setel jas.', '套', ['本', '张', '条'], 'Set', '套 untuk set: jas, buku seri, apartemen.'],
  ['我需要一____剪刀。', 'Saya butuh sebuah gunting.', '把', ['本', '张', '条'], 'Bergagang', '把 untuk benda bergagang.'],
  ['请给我一____面包。', 'Tolong beri saya seiris roti.', '片', ['瓶', '杯', '双'], 'Irisan', '片 untuk irisan dan lembaran tipis.'],
  ['他吃了一____药。', 'Dia minum sebutir obat.', '颗', ['本', '张', '件'], 'Butir', '颗 untuk benda kecil bulat: obat, permen, bintang.'],
  ['我想说一____话。', 'Saya ingin mengucapkan satu kalimat.', '句', ['本', '张', '件'], 'Kalimat', '句 untuk kalimat dan ucapan.'],
  ['这座楼有二十____。', 'Gedung ini ada dua puluh lantai.', '层', ['本', '张', '条'], 'Lantai', '层 untuk lantai dan lapisan.'],
  ['这学期我选了四____课。', 'Semester ini saya mengambil empat mata kuliah.', '门', ['本', '张', '只'], 'Mata pelajaran', '门 untuk mata pelajaran/kuliah.'],
  ['他给我一____礼物。', 'Dia memberiku sebuah hadiah.', '份', ['本', '张', '条'], 'Bagian', '份 untuk hadiah, porsi, dokumen.'],
  ['桌子上有一____报纸。', 'Di meja ada sebuah koran.', '份', ['本', '条', '只'], 'Bagian', '份 (atau 张) untuk koran.'],
  ['我有一____眼镜。', 'Saya punya sebuah kacamata.', '副', ['本', '张', '条'], 'Set pasangan', '副 untuk kacamata dan sarung tangan.'],
  ['他买了一____袜子。', 'Dia membeli sepasang kaus kaki.', '双', ['本', '张', '件'], 'Pasangan', '双 untuk benda berpasangan.'],
  ['门口有一____自行车。', 'Di depan pintu ada sebuah sepeda.', '辆', ['本', '张', '条'], 'Kendaraan', '辆 untuk kendaraan beroda.'],
  ['我听了一____音乐。', 'Saya mendengarkan sepenggal musik.', '段', ['本', '张', '件'], 'Penggalan', '段 untuk penggalan musik, teks, waktu.'],
  ['我收到了一____短信。', 'Saya menerima sebuah SMS.', '条', ['本', '张', '件'], 'Pesan', '条 untuk pesan, berita, saran.'],
  ['他画了一____画。', 'Dia melukis sebuah lukisan.', '幅', ['本', '条', '件'], 'Lukisan', '幅 untuk lukisan dan peta.'],
];

export const hardMeasureWords: ChoiceTuple[] = [
  ['他找到了一____新工作。', 'Dia mendapat pekerjaan baru.', '份', ['件', '张', '道'], 'Pekerjaan', '份 untuk pekerjaan dan dokumen.'],
  ['我想给你提一____建议。', 'Saya ingin memberimu satu saran.', '条', ['件', '张', '本'], 'Saran', '条 untuk saran, berita, aturan.'],
  ['这是一____重要的任务。', 'Ini tugas yang penting.', '项', ['张', '本', '只'], 'Tugas formal', '项 untuk tugas, proyek, aturan formal.'],
  ['那里有一____大学。', 'Di sana ada sebuah universitas.', '所', ['间', '本', '张'], 'Institusi', '所 untuk sekolah, universitas, rumah sakit.'],
  ['这____桥很长。', 'Jembatan ini panjang.', '座', ['条', '本', '张'], 'Bangunan', '座 untuk jembatan, gunung, kota.'],
  ['刚才下了一____雨。', 'Tadi sempat turun hujan sebentar.', '阵', ['本', '张', '只'], 'Sejenak', '阵 untuk hujan/angin yang sebentar.'],
  ['门外来了一____学生。', 'Di luar pintu datang sekelompok murid.', '群', ['本', '张', '只'], 'Kelompok', '群 untuk kerumunan orang/hewan.'],
  ['公司今年招了一____新员工。', 'Tahun ini perusahaan merekrut satu angkatan karyawan baru.', '批', ['本', '张', '只'], 'Gelombang', '批 untuk gelombang/angkatan orang atau barang.'],
  ['他存了一____钱。', 'Dia menabung sejumlah uang.', '笔', ['本', '张', '只'], 'Sejumlah uang', '笔 untuk sejumlah uang dan transaksi.'],
  ['我刚做完一____数学题。', 'Saya baru selesai mengerjakan satu soal matematika.', '道', ['本', '张', '只'], 'Soal', '道 untuk soal dan hidangan.'],
  ['昨天发生了一____交通事故。', 'Kemarin terjadi sebuah kecelakaan lalu lintas.', '起', ['本', '张', '只'], 'Insiden', '起 untuk kejadian/insiden.'],
  ['我看到一____森林。', 'Saya melihat sebuah hutan.', '片', ['本', '张', '只'], 'Hamparan', '片 untuk hamparan: hutan, laut, ladang.'],
  ['屋里有一____香味。', 'Di dalam ruangan ada semerbak wangi.', '股', ['本', '张', '只'], 'Aliran', '股 untuk bau, aliran, kekuatan.'],
  ['他是我们班的一____学生。', 'Dia salah satu murid di kelas kami.', '名', ['本', '张', '只'], 'Anggota', '名 untuk orang dengan peran/status.'],
  ['我们看了一____足球比赛。', 'Kami menonton sebuah pertandingan sepak bola.', '场', ['本', '张', '只'], 'Peristiwa', '场 untuk pertandingan dan pertunjukan.'],
  ['他写了一____论文。', 'Dia menulis sebuah makalah.', '篇', ['张', '只', '件'], 'Tulisan', '篇 untuk makalah, artikel, esai.'],
  ['这是第十____运动会。', 'Ini pekan olahraga ke-10 (penyelenggaraan).', '届', ['本', '张', '只'], 'Penyelenggaraan', '届 untuk acara berkala dan angkatan lulusan.'],
  ['她有一____长头发。', 'Dia berambut panjang.', '头', ['本', '张', '只'], 'Rambut', '头 untuk rambut di kepala.'],
  ['这是一____新的方法。', 'Ini jenis metode baru.', '种', ['本', '张', '只'], 'Jenis', '种 = jenis/macam.'],
  ['我听到一____好消息。', 'Saya mendengar sebuah kabar baik.', '条', ['本', '张', '只'], 'Kabar', '条 untuk kabar dan berita.'],
  ['我们需要一____完整的方案。', 'Kami butuh satu set rencana lengkap.', '套', ['本', '张', '只'], 'Set', '套 untuk set rencana, sistem, peralatan.'],
  ['天上有一____星星特别亮。', 'Ada sebutir bintang yang sangat terang.', '颗', ['本', '张', '只'], 'Butir', '颗 untuk bintang dan benda kecil bulat.'],
  ['这是一____古老的城市。', 'Ini kota kuno.', '座', ['本', '张', '只'], 'Kota', '座 untuk kota, gunung, jembatan.'],
  ['他们有一____很强的足球队。', 'Mereka punya tim sepak bola yang kuat.', '支', ['本', '张', '只'], 'Tim', '支 untuk tim, pasukan, lagu.'],
  ['我写了一____报告。', 'Saya menulis sebuah laporan.', '份', ['本', '张', '只'], 'Dokumen', '份 untuk laporan dan dokumen.'],
  ['他对我说了一____心里话。', 'Dia mengungkapkan isi hatinya kepadaku.', '番', ['本', '张', '只'], 'Rangkaian', '番 untuk ucapan/usaha yang panjang.'],
  ['我买了一____葡萄。', 'Saya membeli setandan anggur.', '串', ['本', '张', '只'], 'Untaian', '串 untuk untaian: anggur, kunci, sate.'],
  ['桌子上有一____书。', 'Di meja ada setumpuk buku.', '堆', ['张', '只', '件'], 'Tumpukan', '堆 untuk tumpukan.'],
  ['杯子里只剩下一____水。', 'Di gelas hanya tersisa setetes air.', '滴', ['本', '张', '只'], 'Tetes', '滴 untuk tetesan.'],
  ['他开了一____公司。', 'Dia mendirikan sebuah perusahaan.', '家', ['本', '张', '只'], 'Usaha', '家 untuk perusahaan dan toko.'],
];
