// Mandarin Preposition Path: coverbs (在/从/往/给/对/跟/离/...) and location words, 30 per level.
// [prompt, Indonesian translation, answer, three wrong options, label, rule]
import type { ChoiceTuple } from './questions';

export const easyPrepositions: ChoiceTuple[] = [
  ['我____学校学习。', 'Saya belajar di sekolah.', '在', ['从', '给', '对'], 'Tempat kegiatan', '在 + tempat + V.'],
  ['他____北京来。', 'Dia datang dari Beijing.', '从', ['在', '给', '往'], 'Asal', '从 + tempat + 来/去 = dari.'],
  ['我____妈妈打电话。', 'Saya menelepon ibu.', '给', ['从', '在', '离'], 'Penerima', '给 + orang + V = kepada/untuk.'],
  ['我____朋友一起去。', 'Saya pergi bersama teman.', '跟', ['从', '给', '离'], 'Bersama', '跟 … 一起 = bersama.'],
  ['我家____学校很近。', 'Rumahku dekat dari sekolah.', '离', ['从', '在', '给'], 'Jarak', 'A 离 B 近/远 = jarak A dari B.'],
  ['书在桌子____。', 'Bukunya di atas meja.', '上', ['下', '里', '前'], 'Posisi', 'kata benda + 上 = di atas.'],
  ['猫在桌子____。', 'Kucingnya di bawah meja.', '下', ['上', '里', '外'], 'Posisi', 'kata benda + 下 = di bawah.'],
  ['钱在包____。', 'Uangnya di dalam tas.', '里', ['上', '下', '前'], 'Posisi', 'kata benda + 里 = di dalam.'],
  ['我们____家吃饭。', 'Kami makan di rumah.', '在', ['从', '往', '给'], 'Tempat kegiatan', '在 + tempat + V.'],
  ['一直____前走。', 'Jalan lurus ke depan.', '往', ['在', '给', '跟'], 'Arah', '往 + arah = ke arah.'],
  ['医院在银行____边。', 'Rumah sakit ada di sebelah kiri bank.', '左', ['上', '里', '下'], 'Arah', '左边 = sebelah kiri.'],
  ['公园在学校____面。', 'Taman ada di belakang sekolah.', '后', ['上', '里', '下'], 'Posisi', '后面 = di belakang.'],
  ['他坐在我____边。', 'Dia duduk di sebelahku.', '旁', ['里', '上', '下'], 'Posisi', '旁边 = di samping.'],
  ['____这儿到那儿要十分钟。', 'Dari sini ke sana butuh sepuluh menit.', '从', ['在', '给', '离'], 'Rentang', '从 A 到 B = dari A ke B.'],
  ['我____你买了一本书。', 'Saya membelikan kamu sebuah buku.', '给', ['从', '在', '离'], 'Penerima', '给 + orang + V = untuk.'],
  ['老师____我们很好。', 'Guru sangat baik kepada kami.', '对', ['从', '在', '往'], 'Sikap', '对 + orang + adj = terhadap.'],
  ['我住____上海。', 'Saya tinggal di Shanghai.', '在', ['从', '往', '给'], 'Tempat', 'V + 在 + tempat.'],
  ['超市在电影院____面。', 'Supermarket ada di depan bioskop.', '前', ['里', '上', '下'], 'Posisi', '前面 = di depan.'],
  ['他____我借了一支笔。', 'Dia meminjam pulpen dariku.', '跟', ['给', '在', '离'], 'Sumber', '跟 + orang + 借 = meminjam dari.'],
  ['我们____八点开始上课。', 'Kami mulai pelajaran dari jam delapan.', '从', ['在', '给', '往'], 'Titik mulai', '从 + waktu + 开始.'],
  ['教室____有很多学生。', 'Di dalam kelas ada banyak murid.', '里', ['上', '外', '前'], 'Posisi', 'tempat + 里 + 有 = di dalam ada.'],
  ['请____右拐。', 'Silakan belok ke kanan.', '往', ['在', '从', '给'], 'Arah', '往 + arah + V.'],
  ['我____他说："你好。"', 'Saya berkata kepadanya: "Halo."', '对', ['从', '在', '离'], 'Sasaran ucapan', '对 + orang + 说.'],
  ['飞机____天上飞。', 'Pesawat terbang di langit.', '在', ['从', '给', '往'], 'Tempat', '在 + tempat + V.'],
  ['杯子在冰箱____。', 'Gelasnya di dalam kulkas.', '里', ['上', '外', '旁'], 'Posisi', 'kata benda + 里 = di dalam.'],
  ['我____哥哥一样高。', 'Saya setinggi kakak laki-laki.', '跟', ['给', '在', '往'], 'Kesamaan', 'A 跟 B 一样 + adj.'],
  ['你____哪儿来？', 'Kamu datang dari mana?', '从', ['在', '给', '对'], 'Asal', '从 + tempat + 来.'],
  ['他们____公园跑步。', 'Mereka berlari di taman.', '在', ['从', '往', '给'], 'Tempat kegiatan', '在 + tempat + V.'],
  ['车站离这儿____远？', 'Seberapa jauh stasiun dari sini?', '多', ['很', '太', '最'], 'Jarak', '离 … 多远 = seberapa jauh.'],
  ['学校在我家____边。', 'Sekolah ada di sebelah timur rumahku.', '东', ['上', '里', '下'], 'Arah mata angin', '东边 = sebelah timur.'],
];

export const mediumPrepositions: ChoiceTuple[] = [
  ['我____中国文化很感兴趣。', 'Saya sangat tertarik dengan budaya Tiongkok.', '对', ['给', '跟', '往'], 'Topik minat', '对 … 感兴趣.'],
  ['我____你介绍一下。', 'Saya perkenalkan sebentar kepadamu.', '给', ['对', '从', '在'], 'Penerima', '给 + orang + 介绍.'],
  ['这件事____我来说很重要。', 'Bagi saya hal ini sangat penting.', '对', ['给', '跟', '从'], 'Sudut pandang', '对 … 来说 = bagi.'],
  ['我们____火车站出发。', 'Kami berangkat dari stasiun kereta.', '从', ['往', '在', '向'], 'Titik berangkat', '从 + tempat + 出发.'],
  ['他____我笑了笑。', 'Dia tersenyum kepadaku.', '向', ['从', '离', '在'], 'Arah sasaran', '向 + orang + V = ke arah.'],
  ['火车____上海开去。', 'Kereta melaju menuju Shanghai.', '往', ['从', '在', '离'], 'Arah', '往 + tempat + 开去.'],
  ['____考试还有三天。', 'Masih tiga hari lagi menuju ujian.', '离', ['从', '在', '往'], 'Jarak waktu', '离 + kejadian + 还有 = masih … lagi.'],
  ['____明天起，我每天跑步。', 'Mulai besok, saya lari setiap hari.', '从', ['在', '离', '往'], 'Titik mulai', '从 … 起 = mulai.'],
  ['我____同学借了一本词典。', 'Saya meminjam kamus dari teman sekelas.', '向', ['给', '离', '往'], 'Sumber', '向/跟 + orang + 借.'],
  ['他____大家道歉了。', 'Dia minta maaf kepada semua orang.', '向', ['从', '离', '在'], 'Sasaran', '向 + orang + 道歉.'],
  ['我____这个问题有不同的看法。', 'Saya punya pandangan berbeda tentang masalah ini.', '对', ['给', '往', '离'], 'Topik', '对 + hal + 有看法.'],
  ['____天气不好，比赛取消了。', 'Karena cuaca buruk, pertandingan dibatalkan.', '由于', ['关于', '对于', '为了'], 'Sebab', '由于 = karena (formal).'],
  ['____健康，他每天锻炼。', 'Demi kesehatan, dia berolahraga setiap hari.', '为了', ['由于', '关于', '对于'], 'Tujuan', '为了 = demi/untuk.'],
  ['这是一本____中国历史的书。', 'Ini buku tentang sejarah Tiongkok.', '关于', ['为了', '由于', '对'], 'Topik', '关于 = tentang.'],
  ['____这个计划，大家都同意。', 'Terhadap rencana ini, semua setuju.', '对于', ['为了', '由于', '从'], 'Topik', '对于 = terhadap/mengenai.'],
  ['我把书放____桌子上了。', 'Saya menaruh buku di atas meja.', '在', ['往', '从', '对'], 'Lokasi hasil', 'V + 在 + tempat.'],
  ['他把信寄____美国了。', 'Dia mengirim surat ke Amerika.', '到', ['在', '从', '对'], 'Tujuan hasil', 'V + 到 + tempat.'],
  ['请把这个交____老师。', 'Tolong serahkan ini ke guru.', '给', ['在', '从', '对'], 'Penerima hasil', 'V + 给 + orang.'],
  ['____北京到上海坐高铁要五个小时。', 'Dari Beijing ke Shanghai naik kereta cepat butuh lima jam.', '从', ['离', '往', '在'], 'Rentang', '从 A 到 B.'],
  ['他的家____公司只有五分钟。', 'Rumahnya hanya lima menit dari kantor.', '离', ['从', '往', '对'], 'Jarak', 'A 离 B + jarak.'],
  ['我____这件事一点儿也不了解。', 'Saya sama sekali tidak tahu tentang hal ini.', '对', ['给', '往', '离'], 'Topik', '对 + hal + 了解.'],
  ['____我看，这个办法不错。', 'Menurut saya, cara ini bagus.', '依', ['对', '为', '离'], 'Pendapat', '依我看 = menurut saya.'],
  ['____朋友的帮助下，我完成了任务。', 'Dengan bantuan teman, saya menyelesaikan tugas.', '在', ['从', '对', '为'], 'Kondisi', '在 … 下 = di bawah/dengan (kondisi).'],
  ['他____窗外看了看。', 'Dia melihat ke luar jendela.', '往', ['在', '离', '对'], 'Arah', '往 + arah + 看.'],
  ['我们____人民服务。', 'Kami melayani rakyat.', '为', ['对', '从', '离'], 'Penerima manfaat', '为 + orang + 服务.'],
  ['____现在开始，不许说话。', 'Mulai sekarang, dilarang bicara.', '从', ['在', '离', '往'], 'Titik mulai', '从 + waktu + 开始.'],
  ['他____我们讲了一个故事。', 'Dia menceritakan sebuah kisah kepada kami.', '给', ['从', '离', '往'], 'Penerima', '给 + orang + 讲.'],
  ['公司____员工很关心。', 'Perusahaan sangat peduli terhadap karyawan.', '对', ['给', '往', '从'], 'Sikap', '对 + orang + 关心.'],
  ['我____她学习做饭。', 'Saya belajar memasak darinya.', '跟', ['给', '离', '往'], 'Sumber belajar', '跟 + orang + 学.'],
  ['这个城市____海边不远。', 'Kota ini tidak jauh dari pantai.', '离', ['从', '往', '对'], 'Jarak', 'A 离 B 不远.'],
];

export const hardPrepositions: ChoiceTuple[] = [
  ['____这次调查，我们发现了很多问题。', 'Melalui survei ini, kami menemukan banyak masalah.', '通过', ['根据', '按照', '随着'], 'Melalui', '通过 = melalui.'],
  ['____天气预报，明天有雨。', 'Menurut ramalan cuaca, besok hujan.', '根据', ['通过', '随着', '沿着'], 'Dasar informasi', '根据 = berdasarkan/menurut.'],
  ['请____规定办理手续。', 'Silakan urus prosedurnya sesuai peraturan.', '按照', ['随着', '通过', '沿着'], 'Sesuai aturan', '按照 = sesuai dengan.'],
  ['____经济的发展，人们的生活越来越好。', 'Seiring perkembangan ekonomi, kehidupan orang makin baik.', '随着', ['按照', '根据', '通过'], 'Seiring', '随着 = seiring dengan.'],
  ['我们____河边散步。', 'Kami berjalan-jalan menyusuri tepi sungai.', '沿着', ['随着', '按照', '通过'], 'Menyusuri', '沿着 = menyusuri.'],
  ['____他的努力，公司成功了。', 'Berkat usahanya, perusahaan berhasil.', '凭着', ['沿着', '随着', '关于'], 'Berkat', '凭着 = dengan mengandalkan.'],
  ['我们必须____困难。', 'Kita harus menghadapi kesulitan.', '面对', ['对于', '关于', '至于'], 'Menghadapi', '面对 = menghadapi.'],
  ['____这个问题，我们明天再讨论。', 'Adapun masalah ini, kita bahas besok.', '至于', ['由于', '为了', '随着'], 'Beralih topik', '至于 = adapun/mengenai (topik lain).'],
  ['____中国，印度的人口也很多。', 'Selain Tiongkok, populasi India juga besar.', '除了', ['关于', '至于', '由于'], 'Selain', '除了 … (以外) = selain.'],
  ['他____工作忙，没时间休息。', 'Karena sibuk bekerja, dia tidak sempat istirahat.', '由于', ['关于', '为了', '至于'], 'Sebab formal', '由于 = karena.'],
  ['这项研究____环境保护有重要意义。', 'Penelitian ini penting bagi perlindungan lingkungan.', '对', ['给', '从', '往'], 'Dampak', '对 … 有意义.'],
  ['____老师的指导下，我写完了论文。', 'Di bawah bimbingan guru, saya menyelesaikan makalah.', '在', ['从', '对', '为'], 'Kondisi', '在 … 的指导下.'],
  ['____经验来看，这个方法有效。', 'Dilihat dari pengalaman, cara ini efektif.', '从', ['对', '在', '为'], 'Sudut pandang', '从 … 来看 = dilihat dari.'],
  ['____安全起见，请系好安全带。', 'Demi keamanan, harap kenakan sabuk pengaman.', '为了', ['由于', '关于', '至于'], 'Tujuan', '为了 … 起见 = demi.'],
  ['他____大家的期望，取得了第一名。', 'Dia tidak mengecewakan harapan semua orang, meraih juara satu.', '不负', ['不顾', '不论', '不管'], 'Ungkapan', '不负 … 期望 = tidak mengecewakan harapan.'],
  ['他____父母的反对，去了国外。', 'Dia pergi ke luar negeri tanpa memedulikan penolakan orang tua.', '不顾', ['不负', '按照', '根据'], 'Mengabaikan', '不顾 = tanpa memedulikan.'],
  ['____大家的意见，我们修改了计划。', 'Berdasarkan pendapat semua orang, kami merevisi rencana.', '根据', ['随着', '沿着', '对于'], 'Dasar', '根据 = berdasarkan.'],
  ['我们____时间顺序介绍。', 'Kami menjelaskan menurut urutan waktu.', '按', ['随', '沿', '朝'], 'Urutan', '按 + urutan = menurut.'],
  ['窗户____南开。', 'Jendelanya menghadap ke selatan.', '朝', ['按', '随', '离'], 'Menghadap', '朝 + arah = menghadap ke.'],
  ['这个问题____我们来说太难了。', 'Masalah ini terlalu sulit bagi kami.', '对', ['给', '为', '从'], 'Sudut pandang', '对 … 来说 = bagi.'],
  ['他____同事一起完成了项目。', 'Dia menyelesaikan proyek bersama rekan kerja.', '和', ['对', '为', '离'], 'Bersama', '和/跟 … 一起 = bersama.'],
  ['公司____年轻人提供培训。', 'Perusahaan menyediakan pelatihan bagi anak muda.', '为', ['对', '从', '离'], 'Penerima manfaat', '为 + orang + 提供.'],
  ['这家店____周一到周五营业。', 'Toko ini buka dari Senin sampai Jumat.', '从', ['离', '往', '对'], 'Rentang', '从 A 到 B.'],
  ['____大会的决定，下个月开始实施。', 'Sesuai keputusan rapat, mulai diterapkan bulan depan.', '按照', ['随着', '沿着', '凭着'], 'Sesuai', '按照 = sesuai.'],
  ['____科技的进步，手机越来越便宜。', 'Seiring kemajuan teknologi, ponsel makin murah.', '随着', ['按照', '根据', '凭着'], 'Seiring', '随着 = seiring.'],
  ['我们____这条路一直走就到了。', 'Kita ikuti jalan ini terus, nanti sampai.', '沿着', ['随着', '根据', '凭着'], 'Menyusuri', '沿着 = menyusuri.'],
  ['____努力学习，他考上了大学。', 'Dengan belajar keras, dia diterima di universitas.', '通过', ['随着', '沿着', '至于'], 'Cara', '通过 = melalui/dengan cara.'],
  ['____别人的批评，我们要虚心接受。', 'Terhadap kritik orang lain, kita harus menerimanya dengan rendah hati.', '对于', ['由于', '为了', '随着'], 'Topik', '对于 = terhadap.'],
  ['这次会议____教育问题展开讨论。', 'Rapat ini membahas seputar masalah pendidikan.', '围绕', ['沿着', '随着', '凭着'], 'Seputar', '围绕 = seputar/berpusat pada.'],
  ['____他以外，大家都到了。', 'Kecuali dia, semua orang sudah datang.', '除了', ['关于', '对于', '至于'], 'Kecuali', '除了 … 以外，都 = kecuali.'],
];
