// English Clause Connect: conjunctions, linkers and relative pronouns, 30 per level.
import type { ChoiceTuple } from '../mandarin/questions';

export const easyClauses: ChoiceTuple[] = [
  ['I stayed home ____ I was sick.', 'Saya di rumah karena sakit.', 'because', ['but', 'so', 'or'], 'Sebab', 'because + alasan.'],
  ['I was tired, ____ I went to bed early.', 'Saya lelah, jadi saya tidur lebih awal.', 'so', ['because', 'but', 'or'], 'Akibat', 'so + akibat.'],
  ['I like tea, ____ I don\'t like coffee.', 'Saya suka teh, tetapi tidak suka kopi.', 'but', ['so', 'because', 'or'], 'Kontras', 'but = tetapi.'],
  ['Do you want rice ____ noodles?', 'Kamu mau nasi atau mi?', 'or', ['and', 'but', 'so'], 'Pilihan', 'or = atau.'],
  ['She bought apples ____ oranges.', 'Dia membeli apel dan jeruk.', 'and', ['or', 'but', 'so'], 'Tambahan', 'and = dan.'],
  ['Wash your hands ____ you eat.', 'Cuci tangan sebelum makan.', 'before', ['after', 'because', 'so'], 'Waktu', 'before = sebelum.'],
  ['I brush my teeth ____ I eat breakfast.', 'Saya sikat gigi setelah sarapan.', 'after', ['before', 'because', 'or'], 'Waktu', 'after = setelah.'],
  ['Call me ____ you arrive.', 'Telepon aku ketika kamu sampai.', 'when', ['because', 'but', 'or'], 'Waktu', 'when = ketika.'],
  ['The man ____ lives next door is a doctor.', 'Pria yang tinggal di sebelah adalah dokter.', 'who', ['which', 'where', 'what'], 'Klausa relatif', 'who untuk orang.'],
  ['This is the book ____ I bought.', 'Ini buku yang saya beli.', 'which', ['who', 'where', 'when'], 'Klausa relatif', 'which untuk benda.'],
  ['It was raining, ____ we played outside.', 'Hujan turun, tetapi kami tetap bermain di luar.', 'but', ['so', 'because', 'or'], 'Kontras', 'but = tetapi.'],
  ['I study hard ____ I want to pass.', 'Saya belajar keras karena ingin lulus.', 'because', ['so', 'but', 'or'], 'Sebab', 'because + alasan.'],
  ['It was cold, ____ I wore a jacket.', 'Cuaca dingin, jadi saya memakai jaket.', 'so', ['because', 'but', 'or'], 'Akibat', 'so + akibat.'],
  ['He is tall ____ strong.', 'Dia tinggi dan kuat.', 'and', ['or', 'but', 'so'], 'Tambahan', 'and = dan.'],
  ['Hurry up, ____ you will be late.', 'Cepat, atau kamu akan terlambat.', 'or', ['and', 'so', 'because'], 'Peringatan', 'or = kalau tidak.'],
  ['I was reading ____ the phone rang.', 'Saya sedang membaca ketika telepon berbunyi.', 'when', ['because', 'so', 'or'], 'Waktu', 'when = ketika.'],
  ['The girl ____ won the race is my sister.', 'Gadis yang memenangkan lomba itu adalah adikku.', 'who', ['which', 'where', 'when'], 'Klausa relatif', 'who untuk orang.'],
  ['I like the dress ____ is blue.', 'Saya suka gaun yang berwarna biru.', 'which', ['who', 'where', 'when'], 'Klausa relatif', 'which untuk benda.'],
  ['This is the house ____ I was born.', 'Ini rumah tempat saya lahir.', 'where', ['which', 'who', 'when'], 'Klausa relatif', 'where untuk tempat.'],
  ['He was hungry, ____ he ate two plates.', 'Dia lapar, jadi dia makan dua piring.', 'so', ['because', 'but', 'or'], 'Akibat', 'so + akibat.'],
  ['She smiled ____ she saw me.', 'Dia tersenyum ketika melihatku.', 'when', ['because', 'or', 'so'], 'Waktu', 'when = ketika.'],
  ['I can swim, ____ I can\'t dive.', 'Saya bisa berenang, tetapi tidak bisa menyelam.', 'but', ['so', 'because', 'or'], 'Kontras', 'but = tetapi.'],
  ['Wait here ____ I get the car.', 'Tunggu di sini sementara saya mengambil mobil.', 'while', ['because', 'so', 'or'], 'Waktu', 'while = sementara.'],
  ['We went home ____ the movie ended.', 'Kami pulang setelah film selesai.', 'after', ['before', 'because', 'so'], 'Waktu', 'after = setelah.'],
  ['Turn off the lights ____ you leave.', 'Matikan lampu sebelum pergi.', 'before', ['after', 'so', 'because'], 'Waktu', 'before = sebelum.'],
  ['I missed the bus, ____ I took a taxi.', 'Saya ketinggalan bus, jadi naik taksi.', 'so', ['because', 'but', 'or'], 'Akibat', 'so + akibat.'],
  ['She is happy ____ she passed the test.', 'Dia senang karena lulus tes.', 'because', ['so', 'but', 'or'], 'Sebab', 'because + alasan.'],
  ['The dog ____ barks all night is ours.', 'Anjing yang menggonggong sepanjang malam itu milik kami.', 'that', ['who', 'where', 'what'], 'Klausa relatif', 'that untuk benda/hewan (atau orang).'],
  ['I like cats ____ dogs.', 'Saya suka kucing dan anjing.', 'and', ['or', 'but', 'so'], 'Tambahan', 'and = dan.'],
  ['Is he your brother ____ your cousin?', 'Dia kakakmu atau sepupumu?', 'or', ['and', 'but', 'so'], 'Pilihan', 'or = atau.'],
];

export const mediumClauses: ChoiceTuple[] = [
  ['____ it was raining, we went out.', 'Meskipun hujan, kami tetap keluar.', 'Although', ['Because', 'So', 'Unless'], 'Konsesi', 'although + klausa = meskipun.'],
  ['I saved money ____ I could buy a bike.', 'Saya menabung supaya bisa membeli sepeda.', 'so that', ['because', 'although', 'unless'], 'Tujuan', 'so that + klausa = supaya.'],
  ['She was singing ____ she was cooking.', 'Dia bernyanyi sambil memasak.', 'while', ['because', 'although', 'so'], 'Bersamaan', 'while = sementara/sambil.'],
  ['I haven\'t seen him ____ he moved.', 'Saya belum bertemu dia sejak dia pindah.', 'since', ['until', 'while', 'after'], 'Waktu', 'since + kejadian awal.'],
  ['Stay here ____ the rain stops.', 'Tetaplah di sini sampai hujan berhenti.', 'until', ['since', 'while', 'so'], 'Waktu', 'until = sampai.'],
  ['____ I arrived, everyone had left.', 'Saat saya tiba, semua orang sudah pergi.', 'By the time', ['Although', 'Unless', 'So that'], 'Waktu', 'by the time = pada saat (sudah).'],
  ['The woman ____ car was stolen called the police.', 'Wanita yang mobilnya dicuri menelepon polisi.', 'whose', ['who', 'which', 'whom'], 'Klausa relatif', 'whose = yang … -nya (kepemilikan).'],
  ['I remember the day ____ we met.', 'Saya ingat hari ketika kita bertemu.', 'when', ['where', 'which', 'who'], 'Klausa relatif', 'when untuk waktu.'],
  ['He is rich. ____, he is not happy.', 'Dia kaya. Namun, dia tidak bahagia.', 'However', ['Therefore', 'Because', 'Besides'], 'Kontras antar kalimat', 'however = namun.'],
  ['It rained all day. ____, the match was cancelled.', 'Hujan seharian. Oleh karena itu, pertandingan dibatalkan.', 'Therefore', ['However', 'Although', 'Instead'], 'Akibat antar kalimat', 'therefore = oleh karena itu.'],
  ['She speaks English ____ French.', 'Dia berbicara bahasa Inggris dan juga bahasa Prancis.', 'as well as', ['as long as', 'as if', 'as soon as'], 'Tambahan', 'as well as = dan juga.'],
  ['Call me ____ you get home.', 'Telepon aku begitu kamu sampai di rumah.', 'as soon as', ['as well as', 'as if', 'even though'], 'Waktu', 'as soon as = begitu.'],
  ['He talks ____ he knows everything.', 'Dia berbicara seolah-olah tahu segalanya.', 'as if', ['as soon as', 'so that', 'even if'], 'Perumpamaan', 'as if = seolah-olah.'],
  ['I like summer, ____ my sister likes winter.', 'Saya suka musim panas, sedangkan adikku suka musim dingin.', 'whereas', ['so that', 'because', 'unless'], 'Perbandingan', 'whereas = sedangkan.'],
  ['____ she was tired, she kept working.', 'Walaupun lelah, dia terus bekerja.', 'Even though', ['Because', 'So that', 'As soon as'], 'Konsesi', 'even though = walaupun.'],
  ['The hotel ____ we stayed was clean.', 'Hotel tempat kami menginap bersih.', 'where', ['which', 'who', 'whose'], 'Klausa relatif', 'where untuk tempat.'],
  ['____ you finish your homework, you can play.', 'Setelah PR-mu selesai, kamu boleh main.', 'Once', ['Although', 'Unless', 'Whereas'], 'Waktu', 'once = begitu/setelah.'],
  ['I\'ll take an umbrella ____ it rains.', 'Saya akan membawa payung untuk berjaga-jaga kalau hujan.', 'in case', ['unless', 'so that', 'although'], 'Antisipasi', 'in case = untuk berjaga-jaga.'],
  ['She left early ____ catch the train.', 'Dia berangkat lebih awal untuk mengejar kereta.', 'in order to', ['so that', 'because', 'although'], 'Tujuan', 'in order to + V1.'],
  ['He is not only smart ____ kind.', 'Dia tidak hanya pintar tetapi juga baik.', 'but also', ['and so', 'or else', 'as well'], 'Tambahan', 'not only … but also.'],
  ['You can have ____ tea or coffee.', 'Kamu boleh memilih teh atau kopi.', 'either', ['neither', 'both', 'whether'], 'Pilihan', 'either … or.'],
  ['____ my brother nor I went.', 'Baik kakakku maupun saya tidak pergi.', 'Neither', ['Either', 'Both', 'Whether'], 'Negatif ganda', 'neither … nor.'],
  ['____ John and Mary passed.', 'John dan Mary sama-sama lulus.', 'Both', ['Either', 'Neither', 'Whether'], 'Tambahan', 'both … and.'],
  ['I don\'t know ____ he will come.', 'Saya tidak tahu apakah dia akan datang.', 'whether', ['either', 'neither', 'unless'], 'Klausa nomina', 'whether = apakah.'],
  ['This is the reason ____ I called.', 'Inilah alasan saya menelepon.', 'why', ['which', 'where', 'whose'], 'Klausa relatif', 'the reason why.'],
  ['The man to ____ I spoke was helpful.', 'Pria yang saya ajak bicara sangat membantu.', 'whom', ['who', 'which', 'whose'], 'Klausa relatif', 'whom setelah preposisi.'],
  ['I was late ____ the traffic was terrible.', 'Saya terlambat karena lalu lintas parah.', 'because', ['so', 'although', 'unless'], 'Sebab', 'because + klausa.'],
  ['The film was boring. ____, we stayed until the end.', 'Filmnya membosankan. Meski begitu, kami bertahan sampai akhir.', 'Nevertheless', ['Therefore', 'Besides', 'Otherwise'], 'Kontras antar kalimat', 'nevertheless = meski begitu.'],
  ['Wear a coat; ____, you\'ll catch a cold.', 'Pakai mantel; kalau tidak, kamu akan masuk angin.', 'otherwise', ['however', 'therefore', 'moreover'], 'Peringatan', 'otherwise = kalau tidak.'],
  ['The room was small. ____, it was expensive.', 'Kamarnya kecil. Selain itu, mahal.', 'Moreover', ['However', 'Otherwise', 'Instead'], 'Tambahan antar kalimat', 'moreover = selain itu.'],
];

export const hardClauses: ChoiceTuple[] = [
  ['____ having little money, they were happy.', 'Meskipun punya sedikit uang, mereka bahagia.', 'Despite', ['Although', 'Even though', 'Whereas'], 'Konsesi + V-ing', 'despite + kata benda/V-ing.'],
  ['____ he had studied, he failed.', 'Walaupun sudah belajar, dia gagal.', 'Although', ['Despite', 'In spite of', 'Because of'], 'Konsesi + klausa', 'although + klausa.'],
  ['____ did I expect to win.', 'Saya sama sekali tidak menyangka akan menang.', 'Little', ['Few', 'Less', 'Least'], 'Inversi', 'Little did + S + V1 (penekanan).'],
  ['____ had I arrived than it started to rain.', 'Begitu saya tiba, hujan mulai turun.', 'No sooner', ['Hardly', 'As soon', 'Barely'], 'Inversi', 'No sooner … than.'],
  ['____ had we sat down when the phone rang.', 'Baru saja kami duduk, telepon berbunyi.', 'Hardly', ['No sooner', 'Rarely', 'Only'], 'Inversi', 'Hardly … when.'],
  ['The project, ____ began last year, is almost done.', 'Proyek itu, yang dimulai tahun lalu, hampir selesai.', 'which', ['that', 'what', 'who'], 'Klausa relatif non-definisi', 'Setelah koma pakai which, bukan that.'],
  ['____ you need is a good rest.', 'Yang kamu butuhkan adalah istirahat yang cukup.', 'What', ['Which', 'That', 'Who'], 'Klausa nomina', 'What = hal yang.'],
  ['The reason ____ he left is unclear.', 'Alasan dia pergi tidak jelas.', 'why', ['which', 'what', 'whose'], 'Klausa relatif', 'the reason why.'],
  ['____ the weather improves, the event will be cancelled.', 'Kecuali cuaca membaik, acara akan dibatalkan.', 'Unless', ['Provided', 'As long', 'Whereas'], 'Pengecualian', 'unless = kecuali jika.'],
  ['You can borrow it ____ you return it tomorrow.', 'Kamu boleh meminjamnya asalkan mengembalikannya besok.', 'provided that', ['unless', 'whereas', 'even though'], 'Syarat', 'provided that = asalkan.'],
  ['The more you practise, ____ you become.', 'Semakin sering berlatih, semakin baik kamu.', 'the better', ['the best', 'better', 'more better'], 'Komparatif ganda', 'The more …, the + komparatif.'],
  ['____ tired she was, she finished the report.', 'Selelah apa pun dia, laporannya tetap selesai.', 'However', ['Whatever', 'Although', 'Despite'], 'Konsesi', 'However + adjektiva + S + V.'],
  ['____ you decide, I will support you.', 'Apa pun keputusanmu, aku mendukungmu.', 'Whatever', ['However', 'Whoever', 'Whether'], 'Konsesi', 'whatever = apa pun.'],
  ['The scientist ____ discovery changed medicine won a prize.', 'Ilmuwan yang penemuannya mengubah dunia kedokteran memenangkan hadiah.', 'whose', ['who', 'whom', 'which'], 'Klausa relatif', 'whose + kata benda.'],
  ['She studied hard; ____, she passed with honours.', 'Dia belajar keras; akibatnya, dia lulus dengan pujian.', 'consequently', ['nevertheless', 'whereas', 'meanwhile'], 'Akibat formal', 'consequently = akibatnya.'],
  ['I\'ll go, ____ it means missing dinner.', 'Aku akan pergi, sekalipun itu berarti melewatkan makan malam.', 'even if', ['as if', 'only if', 'if only'], 'Konsesi hipotetis', 'even if = sekalipun.'],
  ['____ I known, I would have helped.', 'Seandainya saya tahu, saya pasti membantu.', 'Had', ['Have', 'If', 'Should'], 'Inversi kondisional', 'Had + S + V3 = if + S + had V3.'],
  ['____ you need help, call me.', 'Jika kamu memerlukan bantuan, hubungi saya.', 'Should', ['Had', 'Would', 'Were'], 'Inversi kondisional', 'Should + S + V1 = if (formal).'],
  ['He spoke slowly ____ everyone could understand.', 'Dia berbicara perlahan agar semua orang mengerti.', 'so that', ['in order to', 'such that', 'as though'], 'Tujuan', 'so that + klausa.'],
  ['It was ____ a good film that we watched it twice.', 'Filmnya sangat bagus sehingga kami menontonnya dua kali.', 'such', ['so', 'too', 'very'], 'Akibat', 'such + a + adj + kata benda + that.'],
  ['The box was ____ heavy that I couldn\'t lift it.', 'Kotaknya sangat berat sehingga saya tidak bisa mengangkatnya.', 'so', ['such', 'too', 'very'], 'Akibat', 'so + adjektiva + that.'],
  ['____ the rain, the match continued.', 'Meskipun hujan, pertandingan berlanjut.', 'In spite of', ['Although', 'Even though', 'However'], 'Konsesi + kata benda', 'in spite of + kata benda.'],
  ['____ his age, he runs every day.', 'Terlepas dari usianya, dia lari setiap hari.', 'Regardless of', ['Although', 'Whereas', 'Unless'], 'Konsesi', 'regardless of + kata benda.'],
  ['Not until I got home ____ I lost my wallet.', 'Baru setelah sampai rumah saya sadar kehilangan dompet.', 'did I realise', ['I realised', 'I did realise', 'realised I'], 'Inversi', 'Not until … + did + S + V1.'],
  ['____ is known about the planet is limited.', 'Hal yang diketahui tentang planet itu terbatas.', 'What', ['That', 'Which', 'It'], 'Klausa nomina', 'What + klausa sebagai subjek.'],
  ['The news ____ he resigned surprised us.', 'Kabar bahwa dia mengundurkan diri mengejutkan kami.', 'that', ['which', 'what', 'whose'], 'Klausa aposisi', 'the news that + klausa lengkap.'],
  ['She left ____ saying goodbye.', 'Dia pergi tanpa berpamitan.', 'without', ['unless', 'despite', 'instead'], 'Preposisi + V-ing', 'without + V-ing.'],
  ['____ finishing the exam, he left the room.', 'Setelah menyelesaikan ujian, dia keluar ruangan.', 'After', ['Since', 'Until', 'While'], 'Klausa partisipel', 'After + V-ing.'],
  ['The city, ____ population is growing, needs more schools.', 'Kota itu, yang penduduknya bertambah, butuh lebih banyak sekolah.', 'whose', ['which', 'where', 'that'], 'Klausa relatif non-definisi', 'whose + kata benda.'],
  ['You may leave ____ you have finished.', 'Kamu boleh pergi hanya jika sudah selesai.', 'only if', ['even if', 'as if', 'if only'], 'Syarat ketat', 'only if = hanya jika.'],
];
