// English Preposition Path: [prompt, Indonesian translation, answer, three wrong options, label, rule], 30 per level.
// Wrong options never include a preposition that would also be correct in the sentence.
import type { ChoiceTuple } from '../mandarin/questions';

export const easyPrepositions: ChoiceTuple[] = [
  ['The book is ____ the table.', 'Buku itu ada di atas meja.', 'on', ['in', 'at', 'to'], 'Tempat', 'on = di atas permukaan.'],
  ['My keys are ____ my bag.', 'Kunciku ada di dalam tas.', 'in', ['on', 'at', 'to'], 'Tempat', 'in = di dalam ruang/wadah.'],
  ['I wake up ____ six o\'clock.', 'Saya bangun jam enam.', 'at', ['in', 'on', 'to'], 'Waktu', 'at + jam.'],
  ['We have class ____ Monday.', 'Kami ada kelas hari Senin.', 'on', ['in', 'at', 'to'], 'Waktu', 'on + hari/tanggal.'],
  ['She was born ____ 2010.', 'Dia lahir tahun 2010.', 'in', ['on', 'at', 'to'], 'Waktu', 'in + tahun/bulan.'],
  ['I go ____ school by bus.', 'Saya pergi ke sekolah naik bus.', 'to', ['in', 'at', 'on'], 'Arah', 'to = ke (tujuan).'],
  ['This gift is ____ you.', 'Hadiah ini untukmu.', 'for', ['to', 'at', 'in'], 'Tujuan', 'for = untuk.'],
  ['He comes ____ Indonesia.', 'Dia berasal dari Indonesia.', 'from', ['to', 'in', 'at'], 'Asal', 'from = dari.'],
  ['I live ____ Jakarta.', 'Saya tinggal di Jakarta.', 'in', ['on', 'at', 'to'], 'Tempat', 'in + kota/negara.'],
  ['The cat is ____ the bed.', 'Kucing itu ada di bawah tempat tidur.', 'under', ['on', 'in', 'at'], 'Posisi', 'under = di bawah.'],
  ['I go to school ____ my sister.', 'Saya pergi ke sekolah bersama kakakku.', 'with', ['from', 'at', 'on'], 'Bersama', 'with = bersama.'],
  ['The bank is ____ the post office and the shop.', 'Bank ada di antara kantor pos dan toko.', 'between', ['among', 'under', 'on'], 'Posisi', 'between = di antara dua hal.'],
  ['There is a tree ____ my house.', 'Ada pohon di depan rumahku.', 'in front of', ['between', 'under', 'on'], 'Posisi', 'in front of = di depan.'],
  ['The park is ____ the school.', 'Taman itu di sebelah sekolah.', 'next to', ['between', 'in', 'on'], 'Posisi', 'next to = di sebelah.'],
  ['I drink milk ____ the morning.', 'Saya minum susu di pagi hari.', 'in', ['on', 'at', 'to'], 'Waktu', 'in the morning/afternoon/evening.'],
  ['I sleep ____ night.', 'Saya tidur di malam hari.', 'at', ['in', 'on', 'to'], 'Waktu', 'at night (ungkapan tetap).'],
  ['She is ____ home now.', 'Dia di rumah sekarang.', 'at', ['in', 'on', 'to'], 'Tempat', 'at home (ungkapan tetap).'],
  ['The picture is ____ the wall.', 'Gambar itu ada di dinding.', 'on', ['in', 'at', 'to'], 'Tempat', 'on = menempel di permukaan.'],
  ['I write ____ a pen.', 'Saya menulis dengan pulpen.', 'with', ['by', 'on', 'from'], 'Alat', 'with + alat.'],
  ['We go to Bandung ____ train.', 'Kami ke Bandung naik kereta.', 'by', ['with', 'on', 'in'], 'Transportasi', 'by + kendaraan (tanpa the).'],
  ['My birthday is ____ May.', 'Ulang tahunku di bulan Mei.', 'in', ['on', 'at', 'to'], 'Waktu', 'in + bulan.'],
  ['Our holiday starts ____ 5 June.', 'Liburan kami mulai tanggal 5 Juni.', 'on', ['in', 'at', 'to'], 'Waktu', 'on + tanggal.'],
  ['The bird flies ____ the house.', 'Burung itu terbang di atas rumah.', 'over', ['on', 'in', 'at'], 'Posisi', 'over = di atas (tidak menyentuh).'],
  ['I walk ____ the bridge.', 'Saya berjalan menyeberangi jembatan.', 'across', ['on', 'at', 'in'], 'Gerak', 'across = menyeberangi.'],
  ['She got ____ the car.', 'Dia masuk ke dalam mobil.', 'into', ['onto', 'at', 'from'], 'Gerak', 'into = masuk ke dalam.'],
  ['He jumped ____ the pool.', 'Dia melompat ke dalam kolam.', 'into', ['at', 'on', 'from'], 'Gerak', 'into = masuk ke dalam.'],
  ['The shop is open ____ Sundays.', 'Toko itu buka pada hari Minggu.', 'on', ['in', 'at', 'to'], 'Waktu', 'on + hari.'],
  ['This book is ____ animals.', 'Buku ini tentang hewan.', 'about', ['at', 'on', 'from'], 'Topik', 'about = tentang.'],
  ['He is ____ the kitchen.', 'Dia ada di dapur.', 'in', ['on', 'at', 'to'], 'Tempat', 'in + ruangan.'],
  ['We sat ____ the teacher.', 'Kami duduk di belakang guru.', 'behind', ['between', 'on', 'at'], 'Posisi', 'behind = di belakang.'],
];

export const mediumPrepositions: ChoiceTuple[] = [
  ['I have lived here ____ 2015.', 'Saya tinggal di sini sejak 2015.', 'since', ['for', 'during', 'from'], 'Durasi', 'since + titik waktu awal.'],
  ['I have lived here ____ five years.', 'Saya tinggal di sini selama lima tahun.', 'for', ['since', 'during', 'from'], 'Durasi', 'for + lamanya waktu.'],
  ['He fell asleep ____ the movie.', 'Dia tertidur selama film berlangsung.', 'during', ['since', 'for', 'until'], 'Durasi', 'during + kejadian/periode.'],
  ['Wait here ____ I come back.', 'Tunggu di sini sampai saya kembali.', 'until', ['since', 'during', 'for'], 'Batas waktu', 'until = sampai.'],
  ['Please finish the report ____ Friday.', 'Tolong selesaikan laporan paling lambat Jumat.', 'by', ['until', 'since', 'during'], 'Tenggat', 'by = paling lambat.'],
  ['The shop is open ____ 9 a.m. to 9 p.m.', 'Toko buka dari jam 9 pagi sampai 9 malam.', 'from', ['since', 'for', 'by'], 'Rentang', 'from … to … = dari … sampai.'],
  ['She is good ____ math.', 'Dia pandai matematika.', 'at', ['in', 'on', 'for'], 'Adjektiva + preposisi', 'good at = pandai dalam.'],
  ['I am interested ____ music.', 'Saya tertarik pada musik.', 'in', ['on', 'at', 'for'], 'Adjektiva + preposisi', 'interested in.'],
  ['He is afraid ____ dogs.', 'Dia takut anjing.', 'of', ['from', 'with', 'about'], 'Adjektiva + preposisi', 'afraid of.'],
  ['We are proud ____ you.', 'Kami bangga padamu.', 'of', ['for', 'with', 'on'], 'Adjektiva + preposisi', 'proud of.'],
  ['I am looking ____ my glasses.', 'Saya sedang mencari kacamataku.', 'for', ['at', 'after', 'to'], 'Kata kerja + preposisi', 'look for = mencari.'],
  ['Please listen ____ the teacher.', 'Tolong dengarkan guru.', 'to', ['at', 'for', 'with'], 'Kata kerja + preposisi', 'listen to.'],
  ['It depends ____ the weather.', 'Itu tergantung cuaca.', 'on', ['of', 'in', 'from'], 'Kata kerja + preposisi', 'depend on.'],
  ['I agree ____ you.', 'Saya setuju denganmu.', 'with', ['to', 'on', 'for'], 'Kata kerja + preposisi', 'agree with + orang.'],
  ['She is married ____ a doctor.', 'Dia menikah dengan seorang dokter.', 'to', ['with', 'by', 'for'], 'Adjektiva + preposisi', 'married to.'],
  ['This bag is different ____ mine.', 'Tas ini berbeda dari tasku.', 'from', ['of', 'with', 'at'], 'Adjektiva + preposisi', 'different from.'],
  ['He apologized ____ being late.', 'Dia minta maaf karena terlambat.', 'for', ['of', 'about', 'with'], 'Kata kerja + preposisi', 'apologize for + V-ing.'],
  ['We talked ____ the trip.', 'Kami membicarakan perjalanan itu.', 'about', ['at', 'for', 'with'], 'Kata kerja + preposisi', 'talk about.'],
  ['I\'m waiting ____ the bus.', 'Saya sedang menunggu bus.', 'for', ['to', 'at', 'on'], 'Kata kerja + preposisi', 'wait for.'],
  ['She shared the cake ____ her friends.', 'Dia membagi kue di antara teman-temannya.', 'among', ['between', 'during', 'over'], 'Posisi', 'among = di antara (lebih dari dua).'],
  ['The cat jumped ____ the table.', 'Kucing itu melompat ke atas meja.', 'onto', ['into', 'over', 'at'], 'Gerak', 'onto = ke atas permukaan.'],
  ['We walked ____ the river.', 'Kami berjalan menyusuri sungai.', 'along', ['across', 'into', 'among'], 'Gerak', 'along = menyusuri.'],
  ['The train went ____ the tunnel.', 'Kereta melaju menembus terowongan.', 'through', ['across', 'onto', 'over'], 'Gerak', 'through = melewati bagian dalam.'],
  ['He is responsible ____ the project.', 'Dia bertanggung jawab atas proyek itu.', 'for', ['of', 'on', 'with'], 'Adjektiva + preposisi', 'responsible for.'],
  ['I\'m tired ____ waiting.', 'Saya bosan menunggu.', 'of', ['about', 'for', 'with'], 'Adjektiva + preposisi', 'tired of = bosan.'],
  ['The room is full ____ people.', 'Ruangan itu penuh orang.', 'of', ['with', 'in', 'by'], 'Adjektiva + preposisi', 'full of.'],
  ['This book was written ____ my teacher.', 'Buku ini ditulis oleh guruku.', 'by', ['from', 'with', 'of'], 'Pasif', 'by + pelaku pada kalimat pasif.'],
  ['Thank you ____ your help.', 'Terima kasih atas bantuanmu.', 'for', ['of', 'to', 'about'], 'Ungkapan', 'thank you for.'],
  ['She is kind ____ animals.', 'Dia baik kepada hewan.', 'to', ['with', 'for', 'at'], 'Adjektiva + preposisi', 'kind to.'],
  ['He succeeded ____ passing the exam.', 'Dia berhasil lulus ujian.', 'in', ['on', 'at', 'for'], 'Kata kerja + preposisi', 'succeed in + V-ing.'],
];

export const hardPrepositions: ChoiceTuple[] = [
  ['The team consists ____ five members.', 'Tim itu terdiri dari lima anggota.', 'of', ['from', 'in', 'with'], 'Kata kerja + preposisi', 'consist of.'],
  ['She insisted ____ paying the bill.', 'Dia bersikeras membayar tagihan.', 'on', ['in', 'at', 'for'], 'Kata kerja + preposisi', 'insist on + V-ing.'],
  ['The heavy rain resulted ____ flooding.', 'Hujan deras mengakibatkan banjir.', 'in', ['from', 'of', 'to'], 'Kata kerja + preposisi', 'result in = mengakibatkan.'],
  ['The flooding resulted ____ heavy rain.', 'Banjir itu disebabkan oleh hujan deras.', 'from', ['in', 'of', 'to'], 'Kata kerja + preposisi', 'result from = disebabkan oleh.'],
  ['All staff must comply ____ the rules.', 'Semua staf harus mematuhi aturan.', 'with', ['to', 'on', 'for'], 'Kata kerja + preposisi', 'comply with.'],
  ['He was accused ____ stealing.', 'Dia dituduh mencuri.', 'of', ['for', 'with', 'about'], 'Kata kerja + preposisi', 'accuse someone of.'],
  ['She was blamed ____ the mistake.', 'Dia disalahkan atas kesalahan itu.', 'for', ['of', 'with', 'about'], 'Kata kerja + preposisi', 'blame someone for.'],
  ['I congratulated him ____ his promotion.', 'Saya memberinya selamat atas promosinya.', 'on', ['for', 'with', 'about'], 'Kata kerja + preposisi', 'congratulate someone on.'],
  ['The museum is famous ____ its paintings.', 'Museum itu terkenal karena lukisannya.', 'for', ['of', 'with', 'by'], 'Adjektiva + preposisi', 'famous for.'],
  ['He is capable ____ solving it.', 'Dia mampu menyelesaikannya.', 'of', ['for', 'to', 'in'], 'Adjektiva + preposisi', 'capable of + V-ing.'],
  ['She is aware ____ the risks.', 'Dia sadar akan risikonya.', 'of', ['about', 'for', 'with'], 'Adjektiva + preposisi', 'aware of.'],
  ['This medicine is similar ____ the old one.', 'Obat ini mirip dengan yang lama.', 'to', ['with', 'as', 'from'], 'Adjektiva + preposisi', 'similar to.'],
  ['The decision is ____ my control.', 'Keputusan itu di luar kendaliku.', 'beyond', ['above', 'over', 'across'], 'Ungkapan', 'beyond my control = di luar kendali.'],
  ['____ the bad weather, the flight left on time.', 'Meskipun cuaca buruk, penerbangan berangkat tepat waktu.', 'Despite', ['Although', 'Because of', 'However'], 'Preposisi kontras', 'despite + kata benda (bukan klausa).'],
  ['The game was cancelled ____ the storm.', 'Pertandingan dibatalkan karena badai.', 'because of', ['because', 'despite', 'although'], 'Preposisi sebab', 'because of + kata benda.'],
  ['____ the manager, we should finish today.', 'Menurut manajer, kita harus selesai hari ini.', 'According to', ['Due', 'Instead of', 'In spite'], 'Ungkapan', 'according to = menurut.'],
  ['He drank tea ____ coffee.', 'Dia minum teh alih-alih kopi.', 'instead of', ['because of', 'in spite of', 'according to'], 'Ungkapan', 'instead of = alih-alih.'],
  ['The meeting was postponed ____ the director\'s absence.', 'Rapat ditunda karena direktur tidak hadir.', 'due to', ['despite', 'instead of', 'apart from'], 'Preposisi sebab', 'due to = disebabkan oleh.'],
  ['____ English, she speaks French and Spanish.', 'Selain bahasa Inggris, dia bisa bahasa Prancis dan Spanyol.', 'Apart from', ['Instead of', 'Because of', 'According to'], 'Ungkapan', 'apart from = selain.'],
  ['We arrived ____ time for the show.', 'Kami tiba tepat sebelum pertunjukan (tidak terlambat).', 'in', ['on', 'at', 'by'], 'Ungkapan waktu', 'in time = tidak terlambat; on time = tepat jadwal.'],
  ['The train left exactly ____ time.', 'Kereta berangkat tepat sesuai jadwal.', 'on', ['in', 'at', 'by'], 'Ungkapan waktu', 'on time = tepat jadwal.'],
  ['I met her ____ chance at the station.', 'Saya bertemu dengannya secara kebetulan di stasiun.', 'by', ['on', 'in', 'at'], 'Ungkapan', 'by chance = secara kebetulan.'],
  ['The products are ____ sale this week.', 'Produk-produk itu sedang diskon minggu ini.', 'on', ['in', 'at', 'for'], 'Ungkapan', 'on sale = sedang diskon.'],
  ['He is ____ charge of the department.', 'Dia memimpin departemen itu.', 'in', ['on', 'at', 'for'], 'Ungkapan', 'in charge of = bertanggung jawab memimpin.'],
  ['She is an expert ____ marketing.', 'Dia ahli di bidang pemasaran.', 'in', ['of', 'at', 'for'], 'Kata benda + preposisi', 'expert in.'],
  ['There has been an increase ____ prices.', 'Terjadi kenaikan harga.', 'in', ['of', 'on', 'at'], 'Kata benda + preposisi', 'an increase in + hal yang naik.'],
  ['Prices rose ____ 10 percent.', 'Harga naik sebesar 10 persen.', 'by', ['of', 'in', 'to'], 'Selisih', 'by + besar perubahan.'],
  ['Prices rose ____ 50 dollars.', 'Harga naik menjadi 50 dolar.', 'to', ['by', 'of', 'in'], 'Hasil akhir', 'to + angka akhir.'],
  ['He objected ____ the new plan.', 'Dia menolak rencana baru itu.', 'to', ['against', 'with', 'on'], 'Kata kerja + preposisi', 'object to.'],
  ['The solution ____ this problem is simple.', 'Solusi untuk masalah ini sederhana.', 'to', ['for', 'of', 'on'], 'Kata benda + preposisi', 'the solution to.'],
];
