export const vocabularyMeanings: Record<string, string> = {
  routine: 'rutinitas',
  breakfast: 'sarapan',
  commute: 'perjalanan kerja/sekolah',
  appointment: 'janji temu',
  errand: 'urusan singkat',
  neighbor: 'tetangga',
  laundry: 'cucian',
  groceries: 'belanja kebutuhan',
  schedule: 'jadwal',
  habit: 'kebiasaan',
  assignment: 'tugas',
  classmate: 'teman sekelas',
  deadline: 'batas waktu',
  notebook: 'buku catatan',
  presentation: 'presentasi',
  subject: 'mata pelajaran',
  grade: 'nilai',
  library: 'perpustakaan',
  exam: 'ujian',
  attendance: 'kehadiran',
  meeting: 'rapat',
  client: 'klien',
  revenue: 'pendapatan',
  proposal: 'proposal',
  invoice: 'faktur/tagihan',
  strategy: 'strategi',
  contract: 'kontrak',
  feedback: 'masukan',
  negotiation: 'negosiasi',
  departure: 'keberangkatan',
  arrival: 'kedatangan',
  luggage: 'bagasi',
  passport: 'paspor',
  booking: 'pemesanan',
  itinerary: 'rencana perjalanan',
  customs: 'bea cukai',
  destination: 'tujuan',
  'boarding pass': 'kartu naik pesawat',
  accommodation: 'akomodasi',
  device: 'perangkat',
  software: 'perangkat lunak',
  update: 'pembaruan',
  password: 'kata sandi',
  privacy: 'privasi',
  network: 'jaringan',
  platform: 'platform',
  download: 'unduh',
  cloud: 'cloud/penyimpanan awan',
  feature: 'fitur',
  awesome: 'keren',
  'hang out': 'nongkrong',
  'no worries': 'tidak apa-apa',
  'kind of': 'agak/lumayan',
  'catch up': 'mengobrol kabar terbaru',
  chill: 'santai',
  'my bad': 'salahku',
  'for sure': 'tentu saja',
  'sounds good': 'kedengarannya bagus',
  "what's up": 'apa kabar/ada apa',
  name: 'nama',
  friend: 'teman',
  home: 'rumah',
  food: 'makanan',
  water: 'air',
  school: 'sekolah',
  book: 'buku',
  happy: 'senang',
  go: 'pergi',
  learn: 'belajar',
  usually: 'biasanya',
  prepare: 'menyiapkan',
  invite: 'mengundang',
  borrow: 'meminjam',
  choose: 'memilih',
  simple: 'sederhana',
  travel: 'bepergian',
  practice: 'berlatih',
  favorite: 'favorit',
  message: 'pesan',
  improve: 'meningkatkan',
  explain: 'menjelaskan',
  request: 'permintaan',
  compare: 'membandingkan',
  support: 'mendukung',
  confident: 'percaya diri',
  decision: 'keputusan',
  experience: 'pengalaman',
  opportunity: 'peluang',
  solution: 'solusi',
  greeting: 'sapaan',
  introduction: 'perkenalan',
  family: 'keluarga',
  relationship: 'hubungan',
  activity: 'aktivitas',
  conversation: 'percakapan',
  opinion: 'pendapat',
  reason: 'alasan',
  example: 'contoh',
  detail: 'detail',
  choice: 'pilihan',
  plan: 'rencana',
  goal: 'tujuan',
  problem: 'masalah',
  feeling: 'perasaan',
  place: 'tempat',
  object: 'benda',
  person: 'orang',
  event: 'peristiwa',
  change: 'perubahan',
  interest: 'minat',
  skill: 'kemampuan',
  progress: 'kemajuan',
  chores: 'pekerjaan rumah',
  alarm: 'alarm',
  shower: 'mandi',
  meal: 'makanan',
  snack: 'camilan',
  traffic: 'lalu lintas',
  wallet: 'dompet',
  keys: 'kunci',
  umbrella: 'payung',
  weather: 'cuaca',
  weekend: 'akhir pekan',
  weekday: 'hari kerja/sekolah',
  exercise: 'olahraga',
  relax: 'bersantai',
  clean: 'membersihkan',
  cook: 'memasak',
  finish: 'menyelesaikan',
  sometimes: 'kadang-kadang',
  teacher: 'guru',
  student: 'murid',
  lesson: 'pelajaran',
  homework: 'pekerjaan rumah',
  quiz: 'kuis',
  project: 'proyek',
  whiteboard: 'papan tulis',
  textbook: 'buku pelajaran',
  dictionary: 'kamus',
  question: 'pertanyaan',
  answer: 'jawaban',
  review: 'mengulas',
  study: 'belajar',
  pass: 'lulus',
  fail: 'gagal',
  semester: 'semester',
  campus: 'kampus',
  budget: 'anggaran',
  profit: 'keuntungan',
  loss: 'kerugian',
  manager: 'manajer',
  employee: 'karyawan',
  colleague: 'rekan kerja',
  agenda: 'agenda',
  report: 'laporan',
  target: 'target',
  growth: 'pertumbuhan',
  market: 'pasar',
  brand: 'merek',
  customer: 'pelanggan',
  supplier: 'pemasok',
  agreement: 'kesepakatan',
  performance: 'kinerja',
  ticket: 'tiket',
  flight: 'penerbangan',
  trip: 'perjalanan',
  bus: 'bus',
  airport: 'bandara',
  station: 'stasiun',
  beach: 'pantai',
  city: 'kota',
  room: 'kamar',
  shop: 'toko',
  come: 'datang',
  visit: 'mengunjungi',
  leave: 'berangkat/meninggalkan',
  arrive: 'tiba',
  near: 'dekat',
  far: 'jauh',
  open: 'buka',
  closed: 'tutup',
  cheap: 'murah',
  expensive: 'mahal',
  today: 'hari ini',
  tomorrow: 'besok',
  gate: 'gerbang',
  terminal: 'terminal',
  delay: 'keterlambatan',
  cancel: 'membatalkan',
  hotel: 'hotel',
  reservation: 'reservasi',
  tourist: 'turis',
  map: 'peta',
  guide: 'pemandu',
  souvenir: 'oleh-oleh',
  currency: 'mata uang',
  exchange: 'penukaran',
  taxi: 'taksi',
  train: 'kereta',
  journey: 'perjalanan',
  suitcase: 'koper',
  visa: 'visa',
  'check-in': 'check-in/lapor masuk',
  'single ticket': 'tiket sekali jalan',
  'return ticket': 'tiket pulang-pergi',
  'travel agency': 'agen perjalanan',
  'city center': 'pusat kota',
  'train station': 'stasiun kereta',
  'bus stop': 'halte bus',
  'hotel room': 'kamar hotel',
  'travel plan': 'rencana perjalanan',
  'safe trip': 'perjalanan aman',
  'local food': 'makanan lokal',
  'travel app': 'aplikasi perjalanan',
  transportation: 'transportasi',
  insurance: 'asuransi',
  backpack: 'ransel',
  landmark: 'tengara/tempat terkenal',
  route: 'rute',
  tour: 'tur',
  'reservation desk': 'meja reservasi',
  'travel document': 'dokumen perjalanan',
  'lost luggage': 'bagasi hilang',
  'public transport': 'transportasi umum',
  'direct flight': 'penerbangan langsung',
  'round trip': 'perjalanan pulang-pergi',
  'layover': 'transit',
  overbooked: 'kelebihan pemesanan',
  cancellation: 'pembatalan',
  'travel restriction': 'pembatasan perjalanan',
  'entry requirement': 'syarat masuk',
  'travel advisory': 'imbauan perjalanan',
  'peak season': 'musim ramai',
  'off-season': 'musim sepi',
  'connecting flight': 'penerbangan lanjutan',
  'baggage allowance': 'jatah bagasi',
  'departure lounge': 'ruang tunggu keberangkatan',
  'immigration officer': 'petugas imigrasi',
  reimbursement: 'penggantian biaya',
  'cancellation policy': 'kebijakan pembatalan',
  'visa waiver': 'bebas visa',
  'travel authorization': 'otorisasi perjalanan',
  'border control': 'kontrol perbatasan',
  'travel disruption': 'gangguan perjalanan',
  repatriation: 'repatriasi/pemulangan',
  'consular assistance': 'bantuan konsuler',
  'contingency planning': 'perencanaan cadangan',
  'over-tourism': 'pariwisata berlebihan',
  application: 'aplikasi',
  browser: 'browser',
  website: 'situs web',
  database: 'basis data',
  screen: 'layar',
  keyboard: 'papan ketik',
  charger: 'pengisi daya',
  battery: 'baterai',
  storage: 'penyimpanan',
  account: 'akun',
  login: 'masuk',
  logout: 'keluar',
  notification: 'notifikasi',
  setting: 'pengaturan',
  security: 'keamanan',
  backup: 'cadangan',
  upload: 'unggah',
  connection: 'koneksi',
  bug: 'bug/masalah',
  'got it': 'mengerti',
  'no big deal': 'bukan masalah besar',
  'I guess': 'kurasa',
  'pretty good': 'cukup bagus',
  totally: 'sepenuhnya',
  seriously: 'serius',
  'right away': 'segera',
  'by the way': 'ngomong-ngomong',
  'come on': 'ayolah',
  'just kidding': 'hanya bercanda',
  'take it easy': 'santai saja',
  'see you': 'sampai jumpa',
  'long time no see': 'lama tidak bertemu',
  'that makes sense': 'itu masuk akal',
  'I am down': 'aku mau/aku ikut',
  'same here': 'aku juga',
  'not really': 'tidak juga',
  'all set': 'sudah siap',
  'good call': 'keputusan bagus',
  'fair enough': 'masuk akal/cukup adil',
  hello: 'halo',
  hi: 'hai',
  'good morning': 'selamat pagi',
  'good afternoon': 'selamat siang/sore',
  'good evening': 'selamat malam',
  goodbye: 'selamat tinggal',
  'thank you': 'terima kasih',
  please: 'tolong/silakan',
  sorry: 'maaf',
  'first name': 'nama depan',
  'last name': 'nama belakang',
  'full name': 'nama lengkap',
  country: 'negara',
  age: 'umur',
  'phone number': 'nomor telepon',
  address: 'alamat',
  email: 'email',
  'email address': 'alamat email',
  hobby: 'hobi',
  nice: 'baik/menyenangkan',
  fine: 'baik',
  meet: 'bertemu',
  live: 'tinggal',
  introduce: 'memperkenalkan',
  nationality: 'kewarganegaraan',
  occupation: 'pekerjaan',
  job: 'pekerjaan',
  profession: 'profesi',
  'personal details': 'detail pribadi',
  'contact information': 'informasi kontak',
  'date of birth': 'tanggal lahir',
  'marital status': 'status pernikahan',
  single: 'lajang',
  married: 'menikah',
  surname: 'nama keluarga',
  nickname: 'nama panggilan',
  hometown: 'kampung halaman',
  form: 'formulir',
  spell: 'mengeja',
  repeat: 'mengulang',
  welcome: 'selamat datang',
  'pleased to meet you': 'senang bertemu denganmu',
  'how are you': 'apa kabar',
  'i am from': 'saya berasal dari',
  'i live in': 'saya tinggal di',
  'nice to meet you': 'senang bertemu denganmu',
  'see you soon': 'sampai jumpa lagi',
};

export const vocabularyParts: Record<string, string> = {
  departure: 'noun',
  arrival: 'noun',
  luggage: 'noun',
  passport: 'noun',
  booking: 'noun',
  itinerary: 'noun',
  customs: 'noun',
  destination: 'noun',
  'boarding pass': 'noun',
  accommodation: 'noun',
  ticket: 'noun',
  flight: 'noun',
  gate: 'noun',
  terminal: 'noun',
  delay: 'noun',
  cancel: 'verb',
  hotel: 'noun',
  reservation: 'noun',
  tourist: 'noun',
  map: 'noun',
  guide: 'noun',
  souvenir: 'noun',
  currency: 'noun',
  exchange: 'verb',
  taxi: 'noun',
  train: 'noun',
  platform: 'noun',
  journey: 'noun',
  suitcase: 'noun',
  visa: 'noun',
  routine: 'noun',
  breakfast: 'noun',
  commute: 'noun',
  appointment: 'noun',
  errand: 'noun',
  neighbor: 'noun',
  laundry: 'noun',
  groceries: 'noun',
  schedule: 'noun',
  habit: 'noun',
  exercise: 'noun',
  relax: 'verb',
  clean: 'verb',
  cook: 'verb',
  prepare: 'verb',
  finish: 'verb',
  usually: 'adverb',
  sometimes: 'adverb',
  assignment: 'noun',
  classmate: 'noun',
  deadline: 'noun',
  notebook: 'noun',
  presentation: 'noun',
  subject: 'noun',
  grade: 'noun',
  library: 'noun',
  exam: 'noun',
  attendance: 'noun',
  study: 'verb',
  learn: 'verb',
  pass: 'verb',
  fail: 'verb',
  meeting: 'noun',
  client: 'noun',
  revenue: 'noun',
  proposal: 'noun',
  invoice: 'noun',
  strategy: 'noun',
  contract: 'noun',
  feedback: 'noun',
  negotiation: 'noun',
  improve: 'verb',
  explain: 'verb',
  compare: 'verb',
  support: 'verb',
  confident: 'adjective',
  hello: 'interjection',
  hi: 'interjection',
  'good morning': 'phrase',
  'good afternoon': 'phrase',
  'good evening': 'phrase',
  goodbye: 'interjection',
  'thank you': 'phrase',
  please: 'adverb',
  sorry: 'adjective',
  'first name': 'noun',
  'last name': 'noun',
  'full name': 'noun',
  country: 'noun',
  age: 'noun',
  'phone number': 'noun',
  address: 'noun',
  email: 'noun',
  'email address': 'noun',
  hobby: 'noun',
  nice: 'adjective',
  fine: 'adjective',
  meet: 'verb',
  live: 'verb',
  introduce: 'verb',
  introduction: 'noun',
  greeting: 'noun',
  nationality: 'noun',
  occupation: 'noun',
  job: 'noun',
  profession: 'noun',
  'personal details': 'noun',
  'contact information': 'noun',
  'date of birth': 'noun',
  'marital status': 'noun',
  single: 'adjective',
  married: 'adjective',
  surname: 'noun',
  nickname: 'noun',
  hometown: 'noun',
  form: 'noun',
  spell: 'verb',
  repeat: 'verb',
  welcome: 'interjection',
  'pleased to meet you': 'phrase',
  'how are you': 'phrase',
  'i am from': 'phrase',
  'i live in': 'phrase',
  'nice to meet you': 'phrase',
  'see you soon': 'phrase',
};

export const vocabularyExamples: Record<string, string> = {
  trip: 'We have a trip tomorrow.',
  bus: 'The bus is late today.',
  airport: 'The airport is very busy.',
  station: 'The station is near my hotel.',
  beach: 'The beach is beautiful.',
  city: 'This city is very big.',
  room: 'My room is clean.',
  shop: 'The shop is open.',
  come: 'Please come to the gate now.',
  visit: 'I want to visit Singapore.',
  leave: 'We leave the hotel at seven.',
  arrive: 'We arrive in Bali at noon.',
  near: 'The cafe is near the station.',
  far: 'The airport is far from here.',
  open: 'The museum is open today.',
  closed: 'The ticket office is closed.',
  cheap: 'This ticket is cheap.',
  expensive: 'The hotel is expensive.',
  today: 'We travel today.',
  tomorrow: 'Our trip starts tomorrow.',
  departure: 'Our departure is at 8 a.m.',
  arrival: 'What time is your arrival?',
  luggage: 'My luggage is in the taxi.',
  passport: 'Please show your passport at the counter.',
  booking: 'I made a hotel booking online.',
  itinerary: 'The itinerary includes a city tour.',
  customs: 'We waited in line at customs.',
  destination: 'Bali is our holiday destination.',
  'boarding pass': 'Please keep your boarding pass with you.',
  accommodation: 'We need cheap accommodation near the station.',
  ticket: 'I bought a train ticket this morning.',
  flight: 'My flight leaves at noon.',
  gate: 'The plane leaves from gate seven.',
  terminal: 'We met at the international terminal.',
  delay: 'There is a short delay because of the rain.',
  cancel: 'I need to cancel my hotel reservation.',
  hotel: 'Our hotel is close to the beach.',
  reservation: 'I have a reservation for two nights.',
  tourist: 'A tourist asked me for directions.',
  map: 'Use this map to find the museum.',
  guide: 'Our guide speaks English very well.',
  souvenir: 'I bought a small souvenir for my friend.',
  currency: 'The local currency is yen.',
  exchange: 'Where can I exchange money?',
  taxi: 'We took a taxi to the airport.',
  train: 'The train arrives at platform three.',
  platform: 'Please wait on platform two.',
  journey: 'The journey took three hours.',
  suitcase: 'My suitcase is too heavy.',
  visa: 'Do you need a visa to visit Japan?',
  'check-in': 'Check-in starts two hours before the flight.',
  'single ticket': 'I need a single ticket to London.',
  'return ticket': 'A return ticket is cheaper.',
  'travel agency': 'The travel agency booked our tour.',
  'city center': 'Our hotel is in the city center.',
  'train station': 'The train station is across the road.',
  'bus stop': 'Wait at the bus stop near the hotel.',
  'hotel room': 'Our hotel room has a small balcony.',
  'travel plan': 'My travel plan is simple.',
  'safe trip': 'Have a safe trip home.',
  'local food': 'We tried local food at the market.',
  'travel app': 'This travel app shows cheap flights.',
  transportation: 'Transportation in this city is easy.',
  connection: 'We missed our connection in Doha.',
  insurance: 'Travel insurance can protect your trip.',
  backpack: 'I put my clothes in my backpack.',
  landmark: 'The tower is a famous landmark.',
  route: 'This route is faster.',
  tour: 'We joined a walking tour.',
  'reservation desk': 'Ask for help at the reservation desk.',
  'travel document': 'Keep your travel document safe.',
  'lost luggage': 'She reported her lost luggage.',
  'public transport': 'Public transport is cheaper than a taxi.',
  'direct flight': 'A direct flight is more convenient.',
  'round trip': 'We booked a round trip to Tokyo.',
  routine: 'My morning routine starts at six.',
  breakfast: 'I eat breakfast before school.',
  commute: 'My commute takes thirty minutes.',
  appointment: 'I have a doctor appointment today.',
  errand: 'I need to run an errand after lunch.',
  neighbor: 'My neighbor is very friendly.',
  laundry: 'I do the laundry every Sunday.',
  groceries: 'We buy groceries after work.',
  schedule: 'My schedule is full today.',
  habit: 'Reading before bed is a good habit.',
  assignment: 'The assignment is due on Friday.',
  classmate: 'My classmate helped me study.',
  deadline: 'The deadline is tomorrow.',
  notebook: 'I wrote the answer in my notebook.',
  presentation: 'She gave a short presentation in class.',
  subject: 'English is my favorite subject.',
  grade: 'I got a good grade on the quiz.',
  library: 'We studied at the library.',
  exam: 'The exam starts at nine.',
  attendance: 'Attendance is important in this class.',
  meeting: 'The meeting starts at ten.',
  client: 'The client asked for a new proposal.',
  revenue: 'The company increased its revenue this year.',
  proposal: 'I sent the proposal by email.',
  invoice: 'Please pay the invoice this week.',
  strategy: 'Our strategy is simple and clear.',
  contract: 'They signed the contract yesterday.',
  feedback: 'Thank you for your helpful feedback.',
  negotiation: 'The negotiation took two hours.',
  name: 'My name is Indah.',
  friend: 'My friend lives near my house.',
  home: 'I go home after school.',
  food: 'This food is delicious.',
  water: 'I drink water every morning.',
  school: 'My school is near the park.',
  book: 'This book is easy to read.',
  happy: 'I am happy today.',
  go: 'I go to class at eight.',
  learn: 'I learn English every day.',
  practice: 'I practice speaking after dinner.',
  improve: 'I want to improve my pronunciation.',
  explain: 'Can you explain this word?',
  confident: 'I feel confident when I practice.',
  hello: 'Hello, my name is Indah.',
  hi: 'Hi, I am Wahib.',
  'good morning': 'Good morning, how are you?',
  'good afternoon': 'Good afternoon, Teacher.',
  'good evening': 'Good evening, everyone.',
  goodbye: 'Goodbye, see you tomorrow.',
  'thank you': 'Thank you for your help.',
  please: 'Please spell your name.',
  sorry: 'Sorry, can you repeat that?',
  'first name': 'My first name is Indah.',
  'last name': 'My last name is Putri.',
  'full name': 'My full name is Indah Putri.',
  country: 'My country is Indonesia.',
  age: 'My age is sixteen.',
  'phone number': 'My phone number is on the form.',
  address: 'My address is in Jakarta.',
  email: 'Please write your email clearly.',
  'email address': 'My email address is easy to remember.',
  hobby: 'My hobby is reading.',
  nice: 'It is nice to meet you.',
  fine: 'I am fine, thank you.',
  meet: 'I meet my friend at school.',
  live: 'I live in Bandung.',
  introduce: 'Let me introduce myself.',
  introduction: 'My introduction is short and simple.',
  greeting: 'A friendly greeting can start a good conversation.',
  nationality: 'My nationality is Indonesian.',
  occupation: 'What is your occupation?',
  job: 'My job is teaching English.',
  profession: 'Teaching is a meaningful profession.',
  'personal details': 'Please fill in your personal details.',
  'contact information': 'My contact information is in my profile.',
  'date of birth': 'My date of birth is May 6.',
  'marital status': 'Please choose your marital status.',
  single: 'I am single.',
  married: 'She is married.',
  surname: 'Smith is a common surname.',
  nickname: 'My nickname is Bimo.',
  hometown: 'My hometown is Yogyakarta.',
  form: 'Please complete this form.',
  spell: 'Can you spell your name?',
  repeat: 'Can you repeat that, please?',
  welcome: 'Welcome to our class.',
  'pleased to meet you': 'Hi, I am Indah. Pleased to meet you.',
  'how are you': 'Hello, how are you today?',
  'i am from': 'I am from Indonesia.',
  'i live in': 'I live in Jakarta.',
  'nice to meet you': 'Nice to meet you, Karina.',
  'see you soon': 'See you soon after class.',
};

export const vocabularyPhonetics: Record<string, string> = {
  routine: '/ruːˈtiːn/',
  breakfast: '/ˈbrekfəst/',
  commute: '/kəˈmjuːt/',
  appointment: '/əˈpɔɪntmənt/',
  errand: '/ˈerənd/',
  neighbor: '/ˈneɪbər/',
  laundry: '/ˈlɔːndri/',
  groceries: '/ˈɡroʊsəriz/',
  schedule: '/ˈskedʒuːl/',
  habit: '/ˈhæbɪt/',
  chores: '/tʃɔːrz/',
  alarm: '/əˈlɑːrm/',
  shower: '/ˈʃaʊər/',
  meal: '/miːl/',
  snack: '/snæk/',
  traffic: '/ˈtræfɪk/',
  wallet: '/ˈwɑːlɪt/',
  keys: '/kiːz/',
  umbrella: '/ʌmˈbrelə/',
  weather: '/ˈweðər/',
  weekend: '/ˈwiːkend/',
  weekday: '/ˈwiːkdeɪ/',
  exercise: '/ˈeksərsaɪz/',
  relax: '/rɪˈlæks/',
  clean: '/kliːn/',
  cook: '/kʊk/',
  prepare: '/prɪˈper/',
  finish: '/ˈfɪnɪʃ/',
  usually: '/ˈjuːʒuəli/',
  sometimes: '/ˈsʌmtaɪmz/',
  assignment: '/əˈsaɪnmənt/',
  classmate: '/ˈklæsmeɪt/',
  deadline: '/ˈdedlaɪn/',
  notebook: '/ˈnoʊtbʊk/',
  presentation: '/ˌprezənˈteɪʃən/',
  subject: '/ˈsʌbdʒekt/',
  grade: '/ɡreɪd/',
  library: '/ˈlaɪbreri/',
  exam: '/ɪɡˈzæm/',
  attendance: '/əˈtendəns/',
  teacher: '/ˈtiːtʃər/',
  student: '/ˈstuːdənt/',
  lesson: '/ˈlesən/',
  homework: '/ˈhoʊmwɜːrk/',
  quiz: '/kwɪz/',
  project: '/ˈprɑːdʒekt/',
  whiteboard: '/ˈwaɪtbɔːrd/',
  textbook: '/ˈtekstbʊk/',
  dictionary: '/ˈdɪkʃəneri/',
  question: '/ˈkwestʃən/',
  answer: '/ˈænsər/',
  review: '/rɪˈvjuː/',
  study: '/ˈstʌdi/',
  learn: '/lɜːrn/',
  pass: '/pæs/',
  fail: '/feɪl/',
  semester: '/səˈmestər/',
  campus: '/ˈkæmpəs/',
  meeting: '/ˈmiːtɪŋ/',
  client: '/ˈklaɪənt/',
  revenue: '/ˈrevənuː/',
  proposal: '/prəˈpoʊzəl/',
  invoice: '/ˈɪnvɔɪs/',
  strategy: '/ˈstrætədʒi/',
  contract: '/ˈkɑːntrækt/',
  feedback: '/ˈfiːdbæk/',
  negotiation: '/nɪˌɡoʊʃiˈeɪʃən/',
  budget: '/ˈbʌdʒɪt/',
  profit: '/ˈprɑːfɪt/',
  loss: '/lɔːs/',
  manager: '/ˈmænɪdʒər/',
  employee: '/ɪmˈplɔɪiː/',
  colleague: '/ˈkɑːliːɡ/',
  agenda: '/əˈdʒendə/',
  report: '/rɪˈpɔːrt/',
  target: '/ˈtɑːrɡɪt/',
  growth: '/ɡroʊθ/',
  market: '/ˈmɑːrkɪt/',
  brand: '/brænd/',
  customer: '/ˈkʌstəmər/',
  supplier: '/səˈplaɪər/',
  agreement: '/əˈɡriːmənt/',
  priority: '/praɪˈɔːrəti/',
  decision: '/dɪˈsɪʒən/',
  departure: '/dɪˈpɑːrtʃər/',
  arrival: '/əˈraɪvəl/',
  luggage: '/ˈlʌɡɪdʒ/',
  passport: '/ˈpæspɔːrt/',
  booking: '/ˈbʊkɪŋ/',
  itinerary: '/aɪˈtɪnəreri/',
  customs: '/ˈkʌstəmz/',
  destination: '/ˌdestɪˈneɪʃən/',
  accommodation: '/əˌkɑːməˈdeɪʃən/',
  ticket: '/ˈtɪkɪt/',
  flight: '/flaɪt/',
  trip: '/trɪp/',
  bus: '/bʌs/',
  airport: '/ˈerpɔːrt/',
  station: '/ˈsteɪʃən/',
  beach: '/biːtʃ/',
  city: '/ˈsɪti/',
  room: '/ruːm/',
  shop: '/ʃɑːp/',
  come: '/kʌm/',
  visit: '/ˈvɪzɪt/',
  leave: '/liːv/',
  arrive: '/əˈraɪv/',
  near: '/nɪr/',
  far: '/fɑːr/',
  open: '/ˈoʊpən/',
  closed: '/kloʊzd/',
  cheap: '/tʃiːp/',
  expensive: '/ɪkˈspensɪv/',
  today: '/təˈdeɪ/',
  tomorrow: '/təˈmɑːroʊ/',
  gate: '/ɡeɪt/',
  terminal: '/ˈtɜːrmɪnəl/',
  delay: '/dɪˈleɪ/',
  cancel: '/ˈkænsəl/',
  hotel: '/hoʊˈtel/',
  reservation: '/ˌrezərˈveɪʃən/',
  tourist: '/ˈtʊrɪst/',
  map: '/mæp/',
  guide: '/ɡaɪd/',
  souvenir: '/ˌsuːvəˈnɪr/',
  currency: '/ˈkɜːrənsi/',
  exchange: '/ɪksˈtʃeɪndʒ/',
  taxi: '/ˈtæksi/',
  train: '/treɪn/',
  platform: '/ˈplætfɔːrm/',
  journey: '/ˈdʒɜːrni/',
  suitcase: '/ˈsuːtkeɪs/',
  visa: '/ˈviːzə/',
  transportation: '/ˌtrænspərˈteɪʃən/',
  connection: '/kəˈnekʃən/',
  insurance: '/ɪnˈʃʊrəns/',
  backpack: '/ˈbækpæk/',
  landmark: '/ˈlændmɑːrk/',
  route: '/ruːt/',
  tour: '/tʊr/',
  layover: '/ˈleɪoʊvər/',
  overbooked: '/ˌoʊvərˈbʊkt/',
  cancellation: '/ˌkænsəˈleɪʃən/',
  reimbursement: '/ˌriːɪmˈbɜːrsmənt/',
  repatriation: '/ˌriːpeɪtriˈeɪʃən/',
  device: '/dɪˈvaɪs/',
  software: '/ˈsɔːftwer/',
  update: '/ˈʌpdeɪt/',
  password: '/ˈpæswɜːrd/',
  privacy: '/ˈpraɪvəsi/',
  network: '/ˈnetwɜːrk/',
  download: '/ˈdaʊnloʊd/',
  cloud: '/klaʊd/',
  feature: '/ˈfiːtʃər/',
  application: '/ˌæplɪˈkeɪʃən/',
  browser: '/ˈbraʊzər/',
  website: '/ˈwebsaɪt/',
  database: '/ˈdeɪtəbeɪs/',
  screen: '/skriːn/',
  keyboard: '/ˈkiːbɔːrd/',
  charger: '/ˈtʃɑːrdʒər/',
  battery: '/ˈbætəri/',
  storage: '/ˈstɔːrɪdʒ/',
  account: '/əˈkaʊnt/',
  login: '/ˈlɔːɡɪn/',
  logout: '/ˈlɔːɡaʊt/',
  notification: '/ˌnoʊtɪfɪˈkeɪʃən/',
  setting: '/ˈsetɪŋ/',
  security: '/sɪˈkjʊrəti/',
  backup: '/ˈbækʌp/',
  upload: '/ˈʌploʊd/',
  bug: '/bʌɡ/',
  awesome: '/ˈɔːsəm/',
  chill: '/tʃɪl/',
  totally: '/ˈtoʊtəli/',
  seriously: '/ˈsɪriəsli/',
  name: '/neɪm/',
  friend: '/frend/',
  home: '/hoʊm/',
  food: '/fuːd/',
  water: '/ˈwɔːtər/',
  school: '/skuːl/',
  book: '/bʊk/',
  happy: '/ˈhæpi/',
  go: '/ɡoʊ/',
  day: '/deɪ/',
  night: '/naɪt/',
  morning: '/ˈmɔːrnɪŋ/',
  house: '/haʊs/',
  family: '/ˈfæməli/',
  bag: '/bæɡ/',
  phone: '/foʊn/',
  table: '/ˈteɪbəl/',
  chair: '/tʃer/',
  big: '/bɪɡ/',
  small: '/smɔːl/',
  new: '/nuː/',
  old: '/oʊld/',
  like: '/laɪk/',
  want: '/wɑːnt/',
  hello: '/həˈloʊ/',
  hi: '/haɪ/',
  'good morning': '/ɡʊd ˈmɔːrnɪŋ/',
  'good afternoon': '/ɡʊd ˌæftərˈnuːn/',
  'good evening': '/ɡʊd ˈiːvnɪŋ/',
  goodbye: '/ˌɡʊdˈbaɪ/',
  'thank you': '/ˈθæŋk juː/',
  please: '/pliːz/',
  sorry: '/ˈsɑːri/',
  'first name': '/ˈfɜːrst neɪm/',
  'last name': '/ˈlæst neɪm/',
  'full name': '/ˈfʊl neɪm/',
  country: '/ˈkʌntri/',
  age: '/eɪdʒ/',
  'phone number': '/ˈfoʊn nʌmbər/',
  address: '/ˈædres/',
  email: '/ˈiːmeɪl/',
  'email address': '/ˈiːmeɪl ˈædres/',
  hobby: '/ˈhɑːbi/',
  nice: '/naɪs/',
  fine: '/faɪn/',
  meet: '/miːt/',
  live: '/lɪv/',
  introduce: '/ˌɪntrəˈduːs/',
  introduction: '/ˌɪntrəˈdʌkʃən/',
  greeting: '/ˈɡriːtɪŋ/',
  nationality: '/ˌnæʃəˈnæləti/',
  occupation: '/ˌɑːkjuˈpeɪʃən/',
  job: '/dʒɑːb/',
  profession: '/prəˈfeʃən/',
  'personal details': '/ˈpɜːrsənəl ˈdiːteɪlz/',
  'contact information': '/ˈkɑːntækt ˌɪnfərˈmeɪʃən/',
  'date of birth': '/ˌdeɪt əv ˈbɜːrθ/',
  'marital status': '/ˈmærɪtəl ˈsteɪtəs/',
  single: '/ˈsɪŋɡəl/',
  married: '/ˈmærid/',
  surname: '/ˈsɜːrneɪm/',
  nickname: '/ˈnɪkneɪm/',
  hometown: '/ˈhoʊmtaʊn/',
  form: '/fɔːrm/',
  spell: '/spel/',
  repeat: '/rɪˈpiːt/',
  welcome: '/ˈwelkəm/',
  'pleased to meet you': '/pliːzd tə ˈmiːt juː/',
  'how are you': '/ˈhaʊ ər juː/',
  'i am from': '/aɪ æm frəm/',
  'i live in': '/aɪ lɪv ɪn/',
  'nice to meet you': '/naɪs tə ˈmiːt juː/',
  'see you soon': '/ˈsiː juː suːn/',
  invite: '/ɪnˈvaɪt/',
  borrow: '/ˈbɑːroʊ/',
  choose: '/tʃuːz/',
  simple: '/ˈsɪmpəl/',
  travel: '/ˈtrævəl/',
  practice: '/ˈpræktɪs/',
  favorite: '/ˈfeɪvərɪt/',
  message: '/ˈmesɪdʒ/',
  plan: '/plæn/',
  order: '/ˈɔːrdər/',
  pay: '/peɪ/',
  helpful: '/ˈhelpfəl/',
  busy: '/ˈbɪzi/',
  early: '/ˈɜːrli/',
  late: '/leɪt/',
  nearby: '/ˌnɪrˈbaɪ/',
  during: '/ˈdʊrɪŋ/',
  because: '/bɪˈkɔːz/',
  before: '/bɪˈfɔːr/',
  after: '/ˈæftər/',
  bring: '/brɪŋ/',
  carry: '/ˈkæri/',
  check: '/tʃek/',
  change: '/tʃeɪndʒ/',
  enough: '/ɪˈnʌf/',
  improve: '/ɪmˈpruːv/',
  explain: '/ɪkˈspleɪn/',
  request: '/rɪˈkwest/',
  compare: '/kəmˈper/',
  support: '/səˈpɔːrt/',
  confident: '/ˈkɑːnfɪdənt/',
  experience: '/ɪkˈspɪriəns/',
  opportunity: '/ˌɑːpərˈtuːnəti/',
  solution: '/səˈluːʃən/',
  suggest: '/səˈdʒest/',
  avoid: '/əˈvɔɪd/',
  manage: '/ˈmænɪdʒ/',
  describe: '/dɪˈskraɪb/',
  recommend: '/ˌrekəˈmend/',
  organize: '/ˈɔːrɡənaɪz/',
  advantage: '/ədˈvæntɪdʒ/',
  disadvantage: '/ˌdɪsədˈvæntɪdʒ/',
  comfortable: '/ˈkʌmftərbəl/',
  necessary: '/ˈnesəseri/',
  available: '/əˈveɪləbəl/',
  probably: '/ˈprɑːbəbli/',
  especially: '/ɪˈspeʃəli/',
  instead: '/ɪnˈsted/',
  although: '/ɔːlˈðoʊ/',
  however: '/haʊˈevər/',
  require: '/rɪˈkwaɪər/',
  include: '/ɪnˈkluːd/',
  depend: '/dɪˈpend/',
  consider: '/kənˈsɪdər/',
};
