/**
 * Expand QUIZ_QUESTIONS in every elementary pronunciation lesson to 20 questions.
 * Questions are topic-aligned per lesson title.
 */
const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, '..', 'src', 'pages', 'module', 'english', 'elementary', 'pronunciation');

const Q = {
  1: [ // Tinjauan: Suara & Akurasi
    { q: "Kata mana yang memiliki suara vokal PENDEK?", o: ['Late', 'Cat', 'Feet'], a: 'Cat', e: "Cat /æ/ adalah vokal pendek; Late dan Feet vokal panjang." },
    { q: "Untuk membuat suara 'TH', lidahmu harus...", o: ['Menyentuh langit-langit', 'Berada di antara gigi', 'Tetap datar'], a: 'Berada di antara gigi', e: "Lidah sedikit menjulur di antara gigi." },
    { q: "'Ship' vs 'Sheep' — mana yang lebih panjang?", o: ['Ship', 'Sheep'], a: 'Sheep', e: "Sheep /iː/ adalah vokal panjang." },
    { q: "Huruf apa yang mengubah vokal pendek menjadi panjang?", o: ['Silent E', 'Double S', 'Hard C'], a: 'Silent E', e: "Magic 'E' di akhir kata: Hop → Hope." },
    { q: "V vs W: Mana yang bibir 'membulat'?", o: ['V (Vet)', 'W (Wet)'], a: 'W (Wet)', e: "W dibuat dengan membentuk lingkaran kecil dengan bibir." },
    { q: "Suara /θ/ (unvoiced TH) ada pada kata...", o: ['This', 'Think', 'Them'], a: 'Think', e: "Think /θɪŋk/ tanpa suara; This /ðɪs/ bersuara." },
    { q: "Suara /ð/ (voiced TH) ada pada kata...", o: ['Thin', 'That', 'Bath'], a: 'That', e: "That /ðæt/ adalah TH bersuara." },
    { q: "Kata 'Hate' mengandung vokal...", o: ['/æ/ pendek', '/eɪ/ panjang', '/ɪ/ pendek'], a: '/eɪ/ panjang', e: "Magic E membuat A menyebut namanya: /eɪ/." },
    { q: "Kata 'Hop' menggunakan vokal...", o: ['/ɒ/ pendek', '/oʊ/ panjang', '/ʌ/'], a: '/ɒ/ pendek', e: "Hop memiliki O pendek /ɒ/; Hope O panjang /oʊ/." },
    { q: "Pasangan manakah yang memakai vokal yang SAMA?", o: ['Sit — Seat', 'Hit — Hip', 'Ship — Sheep'], a: 'Hit — Hip', e: "Keduanya /ɪ/ pendek." },
    { q: "R vs L: R dibuat dengan...", o: ['Lidah menyentuh langit-langit', 'Lidah tertarik ke belakang', 'Bibir membulat penuh'], a: 'Lidah tertarik ke belakang', e: "R bahasa Inggris tidak menggetarkan ujung lidah." },
    { q: "Konsonan akhir pada 'Cute' diikuti oleh suara...", o: ['/uː/', '/juː/', '/ʌ/'], a: '/juː/', e: "Cute /kjuːt/ memiliki glide Y sebelum U." },
    { q: "Kata mana yang TIDAK memiliki Magic E?", o: ['Bike', 'Cake', 'Cat'], a: 'Cat', e: "Cat tidak diakhiri Silent E." },
    { q: "Mana yang mengandung suara /ʌ/ (U pendek)?", o: ['Cut', 'Cute', 'Coat'], a: 'Cut', e: "Cut /kʌt/ menggunakan suara geraman pendek /ʌ/." },
    { q: "'Meet' dan 'Meat' diucapkan...", o: ['Berbeda', 'Sama (/miːt/)', 'Hanya beda tekanan'], a: 'Sama (/miːt/)', e: "Keduanya homofon — diucapkan identik." },
    { q: "Kata 'Thought' diawali dengan suara...", o: ['/t/', '/θ/', '/ð/'], a: '/θ/', e: "Thought memakai TH tanpa suara /θ/." },
    { q: "Pasangan minimal untuk /v/ vs /w/ adalah...", o: ['Vet — Wet', 'Bet — Set', 'Hat — Hot'], a: 'Vet — Wet', e: "Hanya konsonan awal yang berbeda /v/ vs /w/." },
    { q: "Saat mengucapkan /l/, ujung lidah ada di...", o: ['Antara gigi', 'Langit-langit di belakang gigi atas', 'Bibir bawah'], a: 'Langit-langit di belakang gigi atas', e: "L dibuat dengan ujung lidah menempel di alveolar ridge." },
    { q: "Vokal pada 'Feet' adalah...", o: ['/ɪ/', '/iː/', '/e/'], a: '/iː/', e: "Feet /fiːt/ memakai vokal panjang /iː/." },
    { q: "Mana yang akurasinya paling penting untuk kejelasan?", o: ['Kecepatan bicara', 'Panjang-pendek vokal', 'Volume suara'], a: 'Panjang-pendek vokal', e: "Perbedaan vokal pendek/panjang krusial agar lawan bicara paham." },
  ],
  2: [ // Vokal Lanjutan
    { q: "Untuk suara /iː/ (Sheep), mulut harus...", o: ['Rileks', 'Tersenyum lebar', 'Rahang turun'], a: 'Tersenyum lebar', e: "E panjang /iː/ membutuhkan ketegangan senyum." },
    { q: "Kata mana memakai suara /ʊ/ (seperti Good)?", o: ['Food', 'Look', 'Blood'], a: 'Look', e: "Good dan Look sama /ʊ/." },
    { q: "Mana mulutnya paling terbuka?", o: ['Men', 'Man', 'Min'], a: 'Man', e: "/æ/ di Man butuh rahang turun paling rendah." },
    { q: "'Fill' vs 'Feel' — mana yang lebih panjang?", o: ['Fill', 'Feel'], a: 'Feel', e: "Feel /iː/ vokal panjang." },
    { q: "Kata 'Bed' menggunakan vokal...", o: ['/e/', '/æ/', '/ɪ/'], a: '/e/', e: "Bed /bed/ memakai E pendek." },
    { q: "Kata 'Bad' menggunakan vokal...", o: ['/e/', '/æ/', '/ʌ/'], a: '/æ/', e: "Bad /bæd/ memakai A pendek dengan rahang lebih turun." },
    { q: "Pool vs Pull — mana yang bibirnya lebih membulat ketat?", o: ['Pool', 'Pull'], a: 'Pool', e: "Pool /uː/ bibir membulat ketat." },
    { q: "'Sit' dan 'Seat' berbeda pada...", o: ['Konsonan awal', 'Panjang vokal', 'Tekanan'], a: 'Panjang vokal', e: "/ɪ/ pendek vs /iː/ panjang." },
    { q: "Mana yang rileks dan cepat?", o: ['/iː/', '/ɪ/', '/æ/'], a: '/ɪ/', e: "/ɪ/ adalah vokal santai yang pendek." },
    { q: "'Hit' vs 'Heat' — Heat diucapkan...", o: ['Lebih pendek', 'Lebih panjang', 'Sama'], a: 'Lebih panjang', e: "Heat /iː/ lebih panjang dari Hit /ɪ/." },
    { q: "Vokal pada 'Said' sama dengan vokal pada...", o: ['Sad', 'Bed', 'Seat'], a: 'Bed', e: "Said /sed/ = Bed /bed/, keduanya /e/." },
    { q: "Suara 'OO' pada 'Food' adalah...", o: ['/ʊ/', '/uː/', '/ʌ/'], a: '/uː/', e: "Food memakai OO panjang /uː/." },
    { q: "Suara 'OO' pada 'Book' adalah...", o: ['/ʊ/', '/uː/', '/oʊ/'], a: '/ʊ/', e: "Book /bʊk/ memakai OO pendek /ʊ/." },
    { q: "Pasangan 'Pen — Pan' membedakan...", o: ['/e/ vs /æ/', '/ɪ/ vs /iː/', '/ʊ/ vs /uː/'], a: '/e/ vs /æ/', e: "Rahang turun lebih jauh untuk Pan /æ/." },
    { q: "Kata mana memakai /æ/?", o: ['Apple', 'Egg', 'Ink'], a: 'Apple', e: "Apple /ˈæpəl/ memakai A pendek." },
    { q: "'Luke' vs 'Look' — Look memakai...", o: ['/uː/ panjang', '/ʊ/ pendek'], a: '/ʊ/ pendek', e: "Look memakai vokal lebih santai /ʊ/." },
    { q: "Vokal manakah yang membutuhkan bibir paling membulat?", o: ['/iː/', '/uː/', '/æ/'], a: '/uː/', e: "/uː/ memakai bibir seperti lingkaran kecil." },
    { q: "Suara /iː/ biasanya dieja dengan...", o: ['i', 'ee / ea', 'a'], a: 'ee / ea', e: "See, Sea, Bee, Meat — pola /iː/." },
    { q: "Kata 'Ship' memakai...", o: ['/iː/', '/ɪ/', '/e/'], a: '/ɪ/', e: "Ship /ʃɪp/ vokal pendek santai." },
    { q: "Yang paling penting untuk /æ/ adalah...", o: ['Mulut lebar & rahang turun', 'Bibir membulat', 'Lidah di atas'], a: 'Mulut lebar & rahang turun', e: "/æ/ butuh pembukaan rahang yang jelas." },
  ],
  3: [ // Tekanan Multi-suku kata
    { q: "Kata 'photograph' ditekan di suku kata...", o: ['ke-1 (PHO-to-graph)', 'ke-2 (pho-TO-graph)', 'ke-3'], a: 'ke-1 (PHO-to-graph)', e: "Kata benda 3 suku → tekanan biasanya di depan." },
    { q: "Kata 'photography' ditekan di suku kata...", o: ['ke-1', 'ke-2 (pho-TO-graphy)', 'ke-3'], a: 'ke-2 (pho-TO-graphy)', e: "Akhiran -graphy menggeser tekanan ke suku ke-2." },
    { q: "Kata 'important' ditekan di...", o: ['IM-portant', 'im-POR-tant', 'im-por-TANT'], a: 'im-POR-tant', e: "Akhiran -ant tidak ditekan; tekanan di suku sebelumnya." },
    { q: "Kata 'computer' ditekan di...", o: ['COM-puter', 'com-PU-ter', 'com-pu-TER'], a: 'com-PU-ter', e: "Tekanan di suku tengah." },
    { q: "Akhiran -tion selalu meletakkan tekanan pada...", o: ['Akhiran itu sendiri', 'Suku sebelum akhiran', 'Suku pertama'], a: 'Suku sebelum akhiran', e: "edu-CA-tion, infor-MA-tion." },
    { q: "Kata 'education' ditekan di...", o: ['ED-ucation', 'edu-CA-tion', 'education'], a: 'edu-CA-tion', e: "Aturan -tion: tekanan di suku sebelumnya." },
    { q: "Kata 'banana' ditekan di...", o: ['BA-nana', 'ba-NA-na', 'bana-NA'], a: 'ba-NA-na', e: "Tekanan di suku tengah." },
    { q: "Kata mana DIAKHIRI dengan akhiran -ic?", o: ['Music', 'Electric', 'Happy'], a: 'Electric', e: "Akhiran -ic: tekanan di suku sebelumnya (e-LEC-tric)." },
    { q: "Kata 'electric' ditekan di...", o: ['E-lectric', 'e-LEC-tric', 'elec-TRIC'], a: 'e-LEC-tric', e: "-ic menggeser tekanan ke suku sebelumnya." },
    { q: "Suku kata tanpa tekanan biasanya memakai vokal...", o: ['/æ/', '/ə/ schwa', '/iː/'], a: '/ə/ schwa', e: "Schwa /ə/ adalah vokal paling umum di suku tanpa tekanan." },
    { q: "Dalam 'PHOtograph', vokal pada 'gra' paling mungkin...", o: ['Tertekan & jelas', 'Tereduksi ke schwa', 'Panjang /iː/'], a: 'Tereduksi ke schwa', e: "Suku tanpa tekanan sering tereduksi." },
    { q: "Kata 'develop' ditekan di...", o: ['DE-velop', 'de-VEL-op', 'deve-LOP'], a: 'de-VEL-op', e: "Tekanan di suku tengah." },
    { q: "Kata 'beautiful' ditekan di...", o: ['BEAU-tiful', 'beau-TI-ful', 'beauti-FUL'], a: 'BEAU-tiful', e: "Tekanan di suku pertama." },
    { q: "Kata 'necessary' ditekan di...", o: ['NEC-essary', 'ne-CES-sary', 'neces-SAR-y'], a: 'NEC-essary', e: "Tekanan di suku pertama." },
    { q: "Kata 'examination' ditekan di...", o: ['E-xamination', 'exa-MI-nation', 'exami-NA-tion'], a: 'exami-NA-tion', e: "Aturan -tion." },
    { q: "Kata 'economic' ditekan di...", o: ['E-conomic', 'e-CON-omic', 'eco-NOM-ic'], a: 'eco-NOM-ic', e: "Aturan -ic." },
    { q: "Tekanan sekunder (secondary stress) biasanya...", o: ['Lebih lemah dari utama', 'Sama dengan utama', 'Tidak ada dalam Inggris'], a: 'Lebih lemah dari utama', e: "Satu tekanan utama + satu atau lebih sekunder." },
    { q: "Akhiran -ity menggeser tekanan ke...", o: ['Akhiran itu', 'Suku sebelum -ity', 'Suku pertama selalu'], a: 'Suku sebelum -ity', e: "a-BIL-ity, pos-si-BIL-ity." },
    { q: "Kata 'ability' ditekan di...", o: ['A-bility', 'a-BIL-ity', 'abili-TY'], a: 'a-BIL-ity', e: "Aturan -ity." },
    { q: "Mengapa penekanan kata penting?", o: ['Agar kata terdengar lebih keras', 'Mengubah arti & kejelasan', 'Menghemat waktu'], a: 'Mengubah arti & kejelasan', e: "Tekanan salah bisa membingungkan pendengar." },
  ],
  4: [ // Ritme Kalimat
    { q: "Dalam bahasa Inggris, kata-kata yang DITEKANKAN adalah...", o: ['Kata fungsi (to, the, of)', 'Kata isi (Noun, Verb, Adj)', 'Semua kata sama'], a: 'Kata isi (Noun, Verb, Adj)', e: "Content words membawa makna, jadi ditekankan." },
    { q: "Kata 'the' dalam kalimat biasanya diucapkan...", o: ['Dengan jelas /ðiː/', 'Lemah /ðə/', 'Selalu ditekankan'], a: 'Lemah /ðə/', e: "Kata fungsi tereduksi ke schwa." },
    { q: "Pada kalimat 'I want to go', kata yang DITEKANKAN adalah...", o: ['I, want, go', 'to, the, a', 'Semua'], a: 'I, want, go', e: "'to' adalah kata fungsi — dilemahkan." },
    { q: "Ritme Bahasa Inggris bersifat...", o: ['Syllable-timed', 'Stress-timed', 'Tone-timed'], a: 'Stress-timed', e: "Jarak antar tekanan cenderung merata." },
    { q: "Bahasa Indonesia cenderung...", o: ['Stress-timed', 'Syllable-timed', 'Tone-timed'], a: 'Syllable-timed', e: "Setiap suku kata di Indonesia panjangnya mirip." },
    { q: "Kata 'can' dalam 'I can swim' diucapkan...", o: ['/kæn/ jelas', '/kən/ lemah', '/keɪn/'], a: '/kən/ lemah', e: "Modal 'can' tereduksi ke schwa saat tidak ditekankan." },
    { q: "Kalimat 'She is a teacher' memiliki berapa tekanan utama?", o: ['1', '2', '4'], a: '2', e: "She, TEACHer. 'is' dan 'a' dilemahkan." },
    { q: "Mana yang termasuk 'kata fungsi'?", o: ['book', 'run', 'of'], a: 'of', e: "Of, to, the, a — kata fungsi lemah." },
    { q: "Mana yang termasuk 'kata isi'?", o: ['the', 'beautiful', 'an'], a: 'beautiful', e: "Adjective membawa makna → ditekankan." },
    { q: "Pada kalimat 'I'll see him tomorrow', yang ditekankan adalah...", o: ['I\\'ll, see, him', 'see, tomorrow', 'semua kata'], a: 'see, tomorrow', e: "Verb utama + adverb waktu." },
    { q: "Tekanan kalimat membantu pendengar...", o: ['Menemukan informasi penting', 'Mengukur kecepatan', 'Menerjemahkan kata demi kata'], a: 'Menemukan informasi penting', e: "Tekanan menandai kata-kata inti." },
    { q: "Dalam 'Did you eat?', kata 'you' biasanya...", o: ['Ditekankan', 'Dilemahkan ke /jə/', 'Dihilangkan'], a: 'Dilemahkan ke /jə/', e: "Pronoun dalam posisi ini sering tereduksi." },
    { q: "Ucapan alami: 'I want to go' sering berubah menjadi...", o: ['I wanna go', 'I want-to go', 'Tidak berubah'], a: 'I wanna go', e: "'Want to' → 'wanna' dalam informal." },
    { q: "Kalimat 'Give me the book' — yang ditekankan...", o: ['Give, book', 'me, the', 'semua'], a: 'Give, book', e: "Verb + Noun objek." },
    { q: "Kata 'and' dalam ritme sering diucapkan...", o: ['/ænd/', '/ən/ atau /n/', '/eɪnd/'], a: '/ən/ atau /n/', e: "Fish 'n chips — 'and' sangat tereduksi." },
    { q: "Jarak waktu antar tekanan dalam bahasa Inggris cenderung...", o: ['Bervariasi liar', 'Relatif sama', 'Bergantung kata'], a: 'Relatif sama', e: "Ciri stress-timed language." },
    { q: "Untuk terdengar natural, penutur asing harus...", o: ['Menekankan setiap suku', 'Melemahkan kata fungsi', 'Bicara sangat pelan'], a: 'Melemahkan kata fungsi', e: "Reduksi kata fungsi kunci ritme alami." },
    { q: "Auxiliary 'have' dalam 'I have seen' biasanya...", o: ['Ditekankan /hæv/', 'Dilemahkan /(h)əv/', 'Dihilangkan total'], a: 'Dilemahkan /(h)əv/', e: "Auxiliary verb tereduksi." },
    { q: "Pada 'He's going to leave', 'to' diucapkan...", o: ['/tuː/', '/tə/', '/toʊ/'], a: '/tə/', e: "'to' → schwa /tə/ dalam ucapan cepat." },
    { q: "Ritme yang baik membuat bahasa Inggris terdengar...", o: ['Monoton', 'Musikal dengan naik-turun', 'Patah-patah'], a: 'Musikal dengan naik-turun', e: "Stress timing memberi irama mirip musik." },
  ],
  5: [ // Bentuk Lemah
    { q: "Suara schwa adalah...", o: ['/æ/', '/ə/', '/iː/'], a: '/ə/', e: "Schwa vokal netral paling umum di bahasa Inggris." },
    { q: "Kata 'to' dalam bentuk lemah diucapkan...", o: ['/tuː/', '/tə/', '/toʊ/'], a: '/tə/', e: "Bentuk lemah /tə/." },
    { q: "Kata 'of' dalam bentuk lemah...", o: ['/ɒv/', '/əv/', '/ʌf/'], a: '/əv/', e: "Cup of tea → /kʌp əv tiː/." },
    { q: "Kata 'and' dalam bentuk lemah bisa jadi...", o: ['/ænd/', '/ən/ atau /n/', '/eɪnd/'], a: '/ən/ atau /n/', e: "Fish and chips → fish-n-chips." },
    { q: "Kata 'for' dalam bentuk lemah...", o: ['/fɔːr/', '/fər/', '/foʊr/'], a: '/fər/', e: "A gift for you → /fər juː/." },
    { q: "Kata 'from' dalam bentuk lemah...", o: ['/frɒm/', '/frəm/', '/fraʊm/'], a: '/frəm/', e: "From London → /frəm ˈlʌndən/." },
    { q: "Bentuk lemah 'can' adalah...", o: ['/kæn/', '/kən/', '/kaʊn/'], a: '/kən/', e: "I can swim → /aɪ kən swɪm/." },
    { q: "Bentuk kuat dipakai saat...", o: ['Kata di akhir kalimat atau ditekankan', 'Kata sebelum noun', 'Selalu'], a: 'Kata di akhir kalimat atau ditekankan', e: "Yes, I can! → /kæn/ kuat." },
    { q: "Kata 'was' dalam bentuk lemah...", o: ['/wɒz/', '/wəz/', '/weɪz/'], a: '/wəz/', e: "He was tired → /hi wəz/." },
    { q: "Kata 'are' dalam bentuk lemah...", o: ['/ɑːr/', '/ər/', '/eər/'], a: '/ər/', e: "They are here → /ðeɪ ər/." },
    { q: "Kata 'have' sebagai auxiliary (lemah)...", o: ['/hæv/', '/(h)əv/', '/heɪv/'], a: '/(h)əv/', e: "I have seen → /aɪ əv siːn/." },
    { q: "Kata 'has' sebagai auxiliary (lemah)...", o: ['/hæz/', '/(h)əz/', '/heɪz/'], a: '/(h)əz/', e: "She has gone → /ʃi əz ɡɒn/." },
    { q: "Kata 'the' sebelum konsonan (lemah)...", o: ['/ðə/', '/ðiː/', '/ðeɪ/'], a: '/ðə/', e: "The book → /ðə bʊk/." },
    { q: "Kata 'the' sebelum vokal...", o: ['/ðə/', '/ðiː/', '/ðeɪ/'], a: '/ðiː/', e: "The apple → /ðiː ˈæpəl/." },
    { q: "Kata 'a' (article) dalam bentuk lemah...", o: ['/eɪ/', '/ə/', '/æ/'], a: '/ə/', e: "A book → /ə bʊk/." },
    { q: "Kata 'some' (weak) dalam 'Buy some bread' diucapkan...", o: ['/sʌm/', '/səm/', '/soʊm/'], a: '/səm/', e: "Determiner 'some' tereduksi ke /səm/." },
    { q: "Mana yang salah? Bentuk lemah selalu...", o: ['Memakai schwa atau vokal pendek', 'Lebih cepat dari bentuk kuat', 'Ditekankan keras'], a: 'Ditekankan keras', e: "Bentuk lemah JUSTRU tidak ditekankan." },
    { q: "'Do' dalam 'Do you like it?' (lemah) diucapkan...", o: ['/duː/', '/də/ atau /d/', '/doʊ/'], a: '/də/ atau /d/', e: "Auxiliary 'do' di awal pertanyaan bisa sangat pendek." },
    { q: "Menguasai bentuk lemah membuat bicaramu...", o: ['Terdengar robotik', 'Lebih natural & cepat', 'Sulit dipahami'], a: 'Lebih natural & cepat', e: "Bentuk lemah adalah ciri ucapan alami." },
    { q: "Schwa /ə/ paling banyak ditemukan di...", o: ['Suku kata tertekan', 'Suku kata tanpa tekanan', 'Awal kalimat'], a: 'Suku kata tanpa tekanan', e: "Vokal tereduksi ke schwa saat tidak ditekan." },
  ],
  6: [ // Ucapan Terhubung
    { q: "'Wake up' diucapkan secara natural sebagai...", o: ['Wake...up', 'Wa-kup', 'Wake-oop'], a: 'Wa-kup', e: "Konsonan K pindah ke vokal U." },
    { q: "Linking terjadi paling umum saat...", o: ['Konsonan + vokal', 'Vokal + vokal', 'Konsonan + konsonan'], a: 'Konsonan + vokal', e: "C+V linking: pick it up → pi-kit-up." },
    { q: "'Turn off' secara natural...", o: ['Turn...off', 'Tur-noff', 'Turnnoff'], a: 'Tur-noff', e: "Konsonan N pindah ke vokal O." },
    { q: "'Come in' menjadi...", o: ['Come...in', 'Co-min', 'Comein'], a: 'Co-min', e: "M pindah ke vokal I." },
    { q: "'I am' sering diucapkan sebagai...", o: ['I am terpisah', 'I'm (satu kesatuan)', 'Ayam'], a: "I'm (satu kesatuan)", e: "Kontraksi adalah bentuk linking yang umum." },
    { q: "'Going to' secara informal menjadi...", o: ['goin-to', 'gonna', 'go-to'], a: 'gonna', e: "Asimilasi umum dalam informal English." },
    { q: "'Want to' informal menjadi...", o: ['wan-to', 'wanna', 'won-to'], a: 'wanna', e: "'Want to' → wanna." },
    { q: "'Got to' informal menjadi...", o: ['got-to', 'gotta', 'go-to'], a: 'gotta', e: "'Got to' → gotta." },
    { q: "Saat 'two apples' diucapkan, sering terdengar...", o: ['tu-wapples', 'two apples terpisah', 'too-apples'], a: 'tu-wapples', e: "Linking /w/ antara dua vokal." },
    { q: "'Go on' sering menjadi...", o: ['go-won', 'go-on putus', 'gwon'], a: 'go-won', e: "Linking /w/ setelah /oʊ/." },
    { q: "'She is' saat cepat...", o: ['She-yis', 'She-is putus', 'She\\'s'], a: "She's", e: "Kontraksi alami." },
    { q: "'Did you' dalam ucapan cepat...", o: ['Did yoo', 'Di-ju (/dɪdʒə/)', 'Did-you'], a: 'Di-ju (/dɪdʒə/)', e: "Asimilasi /d/ + /j/ → /dʒ/." },
    { q: "'Don't you' menjadi...", o: ['Don-chu (/doʊntʃə/)', 'Don-you', 'Dontyoo'], a: 'Don-chu (/doʊntʃə/)', e: "Asimilasi /t/ + /j/ → /tʃ/." },
    { q: "Fenomena saat 2 kata seakan menjadi 1 disebut...", o: ['Elision', 'Linking/Liaison', 'Intonation'], a: 'Linking/Liaison', e: "Liaison/linking menghubungkan kata." },
    { q: "'Next day' sering kehilangan bunyi...", o: ['/t/', '/n/', '/d/'], a: '/t/', e: "'Nex-day' — T di antara 2 konsonan sering hilang (elision)." },
    { q: "Elision adalah...", o: ['Penambahan suara', 'Penghilangan suara', 'Pergantian suara'], a: 'Penghilangan suara', e: "Suara dihilangkan untuk kelancaran." },
    { q: "'Mustn't' diucapkan...", o: ['mus-ENT', 'muss-nt', 'mustent'], a: 'muss-nt', e: "T di 'mustn't' dihilangkan." },
    { q: "Connected speech membuat bahasa Inggris terdengar...", o: ['Formal kaku', 'Lancar & alami', 'Lambat'], a: 'Lancar & alami', e: "Liaison, elision, asimilasi = alami." },
    { q: "Apa yang terjadi saat /n/ bertemu /b/ (seperti 'ten boys')?", o: ['/n/ menjadi /m/', '/n/ menjadi /ŋ/', 'Tidak berubah'], a: '/n/ menjadi /m/', e: "Asimilasi tempat artikulasi." },
    { q: "Fenomena 'n' berubah menjadi 'm' sebelum 'b/p/m' disebut...", o: ['Elision', 'Asimilasi', 'Reduksi'], a: 'Asimilasi', e: "Asimilasi = suara meniru tetangga." },
  ],
  7: [ // -ed & -s (Lanjutan)
    { q: "Akhiran -ed pada 'walked' diucapkan...", o: ['/t/', '/d/', '/ɪd/'], a: '/t/', e: "Setelah konsonan tak bersuara /k/, -ed = /t/." },
    { q: "Akhiran -ed pada 'played' diucapkan...", o: ['/t/', '/d/', '/ɪd/'], a: '/d/', e: "Setelah konsonan bersuara atau vokal, -ed = /d/." },
    { q: "Akhiran -ed pada 'wanted' diucapkan...", o: ['/t/', '/d/', '/ɪd/'], a: '/ɪd/', e: "Setelah /t/ atau /d/, -ed = /ɪd/ (suku kata tambahan)." },
    { q: "Akhiran -ed pada 'started' diucapkan...", o: ['/t/', '/d/', '/ɪd/'], a: '/ɪd/', e: "Berakhir /t/ → /ɪd/." },
    { q: "Akhiran -ed pada 'loved' diucapkan...", o: ['/t/', '/d/', '/ɪd/'], a: '/d/', e: "Setelah /v/ (bersuara) → /d/." },
    { q: "Akhiran -s pada 'cats' diucapkan...", o: ['/s/', '/z/', '/ɪz/'], a: '/s/', e: "Setelah /t/ tak bersuara → /s/." },
    { q: "Akhiran -s pada 'dogs' diucapkan...", o: ['/s/', '/z/', '/ɪz/'], a: '/z/', e: "Setelah /g/ bersuara → /z/." },
    { q: "Akhiran -s pada 'buses' diucapkan...", o: ['/s/', '/z/', '/ɪz/'], a: '/ɪz/', e: "Setelah /s/, /z/, /ʃ/, /tʃ/, /dʒ/ → /ɪz/." },
    { q: "Akhiran -s pada 'watches' diucapkan...", o: ['/s/', '/z/', '/ɪz/'], a: '/ɪz/', e: "Setelah /tʃ/ → /ɪz/." },
    { q: "Akhiran -s pada 'books' diucapkan...", o: ['/s/', '/z/', '/ɪz/'], a: '/s/', e: "Setelah /k/ → /s/." },
    { q: "Akhiran -s pada 'boys' diucapkan...", o: ['/s/', '/z/', '/ɪz/'], a: '/z/', e: "Setelah vokal (bersuara) → /z/." },
    { q: "Kata 'fixed' berakhir dengan suara...", o: ['/t/', '/d/', '/ɪd/'], a: '/t/', e: "'Fix' berakhir /ks/ tak bersuara → /t/." },
    { q: "Kata 'decided' berakhir dengan suara...", o: ['/t/', '/d/', '/ɪd/'], a: '/ɪd/', e: "Berakhir /d/ → suku tambahan /ɪd/." },
    { q: "Kata 'needed' berakhir dengan suara...", o: ['/t/', '/d/', '/ɪd/'], a: '/ɪd/', e: "Berakhir /d/ → /ɪd/." },
    { q: "Kata 'closed' berakhir dengan suara...", o: ['/t/', '/d/', '/ɪd/'], a: '/d/', e: "Berakhir /z/ bersuara → /d/." },
    { q: "Kata 'passed' berakhir dengan suara...", o: ['/t/', '/d/', '/ɪd/'], a: '/t/', e: "Berakhir /s/ tak bersuara → /t/." },
    { q: "Kata 'cleaned' berakhir dengan suara...", o: ['/t/', '/d/', '/ɪd/'], a: '/d/', e: "Berakhir /n/ bersuara → /d/." },
    { q: "Kata 'waited' menambah...", o: ['Satu suku kata', 'Tidak ada suku baru', 'Dua suku kata'], a: 'Satu suku kata', e: "/ɪd/ menambah 1 suku kata." },
    { q: "Kata 'laughed' berakhir /f/ → -ed adalah...", o: ['/t/', '/d/', '/ɪd/'], a: '/t/', e: "Setelah /f/ tak bersuara → /t/." },
    { q: "Mengapa aturan -ed/-s penting?", o: ['Biar terdengar natural & benar', 'Hanya untuk ujian', 'Tidak penting'], a: 'Biar terdengar natural & benar', e: "Salah ucap -ed/-s terdengar janggal." },
  ],
  8: [ // Pola Intonasi
    { q: "Pertanyaan Yes/No biasanya berintonasi...", o: ['Turun ↘', 'Naik ↗', 'Datar →'], a: 'Naik ↗', e: "Do you like it? ↗" },
    { q: "Pertanyaan Wh- (what, where) biasanya...", o: ['Turun ↘', 'Naik ↗', 'Datar'], a: 'Turun ↘', e: "Where do you live? ↘" },
    { q: "Kalimat pernyataan biasanya...", o: ['Turun ↘', 'Naik ↗', 'Datar'], a: 'Turun ↘', e: "I'm going home. ↘" },
    { q: "Daftar (list) di tengah menggunakan...", o: ['Turun ↘', 'Naik ↗', 'Datar'], a: 'Naik ↗', e: "Apple↗, banana↗, and orange↘." },
    { q: "Item terakhir dari daftar memakai intonasi...", o: ['Turun ↘', 'Naik ↗'], a: 'Turun ↘', e: "Penutup daftar = turun." },
    { q: "Question tag untuk konfirmasi (yakin) memakai...", o: ['Turun ↘', 'Naik ↗'], a: 'Turun ↘', e: "It's a nice day, isn't it↘ (mencari persetujuan)." },
    { q: "Question tag untuk ragu memakai...", o: ['Turun ↘', 'Naik ↗'], a: 'Naik ↗', e: "You're coming, aren't you↗ (sebenar bertanya)." },
    { q: "Kata 'Really?' dengan intonasi naik menandakan...", o: ['Kekecewaan', 'Keterkejutan/ragu', 'Kebahagiaan'], a: 'Keterkejutan/ragu', e: "Really↗ = 'Benarkah?'" },
    { q: "Perintah (imperative) biasanya...", o: ['Turun ↘', 'Naik ↗'], a: 'Turun ↘', e: "Close the door↘." },
    { q: "Kalimat 'Oh really' nada turun menandakan...", o: ['Tertarik', 'Tidak peduli/sarkastik', 'Bertanya'], a: 'Tidak peduli/sarkastik', e: "Oh really↘ bisa datar/tak antusias." },
    { q: "Intonasi membantu menyampaikan...", o: ['Emosi & maksud', 'Hanya tata bahasa', 'Tidak penting'], a: 'Emosi & maksud', e: "Intonasi = musik bahasa." },
    { q: "Pertanyaan pilihan (A or B?) biasanya...", o: ['Naik-naik', 'Naik↗ lalu Turun↘', 'Turun-turun'], a: 'Naik↗ lalu Turun↘', e: "Tea↗ or coffee↘?" },
    { q: "Sapaan 'Hi!' dengan nada naik terdengar...", o: ['Ramah', 'Marah', 'Tidak antusias'], a: 'Ramah', e: "Hi!↗ sapaan hangat." },
    { q: "Nada datar dalam kalimat menandakan...", o: ['Bosan/monoton', 'Antusias', 'Marah'], a: 'Bosan/monoton', e: "Flat tone = disinterest." },
    { q: "Untuk menekankan kata penting, kamu...", o: ['Berbicara pelan', 'Menaikkan nada pada kata itu', 'Mengulangnya'], a: 'Menaikkan nada pada kata itu', e: "Pitch rise menandai informasi baru/penting." },
    { q: "Sarkasme dalam bahasa Inggris ditandai oleh...", o: ['Intonasi yang tidak sesuai konteks', 'Hanya pilihan kata', 'Volume keras'], a: 'Intonasi yang tidak sesuai konteks', e: "Intonasi mismatch = sarcasm." },
    { q: "'You did what?!' dengan nada naik keras menunjukkan...", o: ['Ketidakpercayaan', 'Ketenangan', 'Kebaikan'], a: 'Ketidakpercayaan', e: "Surprise + disbelief." },
    { q: "Ungkapan 'Thank you' dengan nada turun...", o: ['Sopan formal', 'Sarkastik', 'Bertanya'], a: 'Sopan formal', e: "Thank you↘ standar sopan." },
    { q: "Intonasi 'Goodbye' yang panjang-turun menandakan...", o: ['Perpisahan emosional', 'Salam santai', 'Marah'], a: 'Perpisahan emosional', e: "Long falling tone = emotional." },
    { q: "Untuk bertanya sambil menunjukkan ragu, pakai...", o: ['Nada datar', 'Nada naik ↗', 'Nada turun ↘'], a: 'Nada naik ↗', e: "Rising pitch = uncertainty/question." },
  ],
  9: [ // Pergeseran Penekanan Kata
    { q: "Kata 'record' sebagai NOUN ditekan di...", o: ['RE-cord', 're-CORD'], a: 'RE-cord', e: "Noun: tekanan di depan." },
    { q: "Kata 'record' sebagai VERB ditekan di...", o: ['RE-cord', 're-CORD'], a: 're-CORD', e: "Verb: tekanan di belakang." },
    { q: "Kata 'present' sebagai NOUN ditekan di...", o: ['PRE-sent', 'pre-SENT'], a: 'PRE-sent', e: "Noun/adjective: depan." },
    { q: "Kata 'present' sebagai VERB ditekan di...", o: ['PRE-sent', 'pre-SENT'], a: 'pre-SENT', e: "Verb: belakang." },
    { q: "Kata 'object' sebagai NOUN ditekan di...", o: ['OB-ject', 'ob-JECT'], a: 'OB-ject', e: "Noun: OB-ject (benda)." },
    { q: "Kata 'object' sebagai VERB ditekan di...", o: ['OB-ject', 'ob-JECT'], a: 'ob-JECT', e: "Verb: ob-JECT (menolak)." },
    { q: "Kata 'conduct' sebagai NOUN ditekan di...", o: ['CON-duct', 'con-DUCT'], a: 'CON-duct', e: "Noun: perilaku." },
    { q: "Kata 'conduct' sebagai VERB ditekan di...", o: ['CON-duct', 'con-DUCT'], a: 'con-DUCT', e: "Verb: memimpin/mengadakan." },
    { q: "Pola umum pergeseran adalah...", o: ['Noun depan, Verb belakang', 'Selalu di depan', 'Selalu di belakang'], a: 'Noun depan, Verb belakang', e: "Pola 'Noun-Verb pair'." },
    { q: "Kata 'permit' sebagai NOUN...", o: ['PER-mit', 'per-MIT'], a: 'PER-mit', e: "Noun: izin (PER-mit)." },
    { q: "Kata 'permit' sebagai VERB...", o: ['PER-mit', 'per-MIT'], a: 'per-MIT', e: "Verb: mengizinkan." },
    { q: "Kata 'import' sebagai NOUN...", o: ['IM-port', 'im-PORT'], a: 'IM-port', e: "Noun: impor." },
    { q: "Kata 'import' sebagai VERB...", o: ['IM-port', 'im-PORT'], a: 'im-PORT', e: "Verb: mengimpor." },
    { q: "Kata 'export' sebagai NOUN...", o: ['EX-port', 'ex-PORT'], a: 'EX-port', e: "Noun: ekspor." },
    { q: "Kata 'export' sebagai VERB...", o: ['EX-port', 'ex-PORT'], a: 'ex-PORT', e: "Verb: mengekspor." },
    { q: "Kata 'increase' sebagai NOUN...", o: ['IN-crease', 'in-CREASE'], a: 'IN-crease', e: "Noun: kenaikan." },
    { q: "Kata 'increase' sebagai VERB...", o: ['IN-crease', 'in-CREASE'], a: 'in-CREASE', e: "Verb: meningkat." },
    { q: "Kata 'decrease' sebagai VERB...", o: ['DE-crease', 'de-CREASE'], a: 'de-CREASE', e: "Verb: menurun." },
    { q: "Kata 'produce' sebagai NOUN (hasil tani)...", o: ['PRO-duce', 'pro-DUCE'], a: 'PRO-duce', e: "Noun: produk tani." },
    { q: "Kata 'produce' sebagai VERB (menghasilkan)...", o: ['PRO-duce', 'pro-DUCE'], a: 'pro-DUCE', e: "Verb: memproduksi." },
  ],
  10: [ // Ulasan & Latihan
    { q: "Mana vokal panjang?", o: ['Bit', 'Beat', 'Bet'], a: 'Beat', e: "/iː/ panjang." },
    { q: "Mana -ed = /ɪd/?", o: ['Walked', 'Played', 'Wanted'], a: 'Wanted', e: "Berakhir /t/ → /ɪd/." },
    { q: "Mana -s = /ɪz/?", o: ['Cats', 'Dogs', 'Buses'], a: 'Buses', e: "Berakhir /s/ → /ɪz/." },
    { q: "Kata 'Comfortable' paling alami diucapkan...", o: ['4 suku', '3 suku (comf-ta-ble)', '5 suku'], a: '3 suku (comf-ta-ble)', e: "Elisi schwa." },
    { q: "Pasangan minimal /f/ vs /v/ adalah...", o: ['Cat — Dog', 'Fan — Van', 'Big — Small'], a: 'Fan — Van', e: "Hanya konsonan awal beda." },
    { q: "Intonasi pertanyaan Yes/No adalah...", o: ['Naik ↗', 'Turun ↘', 'Datar'], a: 'Naik ↗', e: "Yes/No = naik." },
    { q: "Kata 'to' dalam 'I want to go' diucapkan...", o: ['/tuː/', '/tə/', '/toʊ/'], a: '/tə/', e: "Bentuk lemah." },
    { q: "Kata 'record' (Noun) ditekan di...", o: ['RE-cord', 're-CORD'], a: 'RE-cord', e: "Noun: depan." },
    { q: "Akhiran -tion meletakkan tekanan di...", o: ['Akhiran itu', 'Suku sebelum -tion', 'Suku pertama'], a: 'Suku sebelum -tion', e: "info-MA-tion." },
    { q: "TH tak bersuara pada kata...", o: ['This', 'Think', 'Them'], a: 'Think', e: "/θ/ tak bersuara." },
    { q: "Kata fungsi (function words) biasanya...", o: ['Ditekankan', 'Dilemahkan', 'Dihilangkan'], a: 'Dilemahkan', e: "Weak forms." },
    { q: "'Going to' informal menjadi...", o: ['goin-to', 'gonna', 'go-to'], a: 'gonna', e: "Asimilasi natural." },
    { q: "Ritme Inggris bersifat...", o: ['Syllable-timed', 'Stress-timed', 'Tone-timed'], a: 'Stress-timed', e: "Jarak antar stress konsisten." },
    { q: "Magic E membuat vokal...", o: ['Pendek', 'Panjang', 'Schwa'], a: 'Panjang', e: "Hop → Hope." },
    { q: "Kata 'eco-NOM-ic' ditekan di suku ke-?", o: ['1', '2', '3'], a: '3', e: "Akhiran -ic menggeser." },
    { q: "Kata 'fixed' berakhir...", o: ['/t/', '/d/', '/ɪd/'], a: '/t/', e: "Setelah /ks/ tak bersuara → /t/." },
    { q: "'Next day' → bunyi yang sering hilang?", o: ['/t/', '/n/', '/d/'], a: '/t/', e: "Elision /t/." },
    { q: "Question tag ragu pakai...", o: ['Turun ↘', 'Naik ↗'], a: 'Naik ↗', e: "Rising = uncertain." },
    { q: "'Don't you' dalam ucapan cepat menjadi...", o: ['Don-you', 'Don-chu', 'Donta'], a: 'Don-chu', e: "Asimilasi /t+j/." },
    { q: "Tujuan utama pronunciation training adalah...", o: ['Aksen sempurna', 'Kejelasan & keterpahaman', 'Akurasi ejaan'], a: 'Kejelasan & keterpahaman', e: "Intelligibility > accent perfection." },
  ],
  11: [ // Panduan Penutur Indonesia
    { q: "Konsonan mana yang sering SULIT bagi penutur Indonesia?", o: ['TH /θ/', 'K', 'N'], a: 'TH /θ/', e: "Indonesia tidak punya /θ/." },
    { q: "Kata 'think' sering salah diucapkan menjadi...", o: ['sink / tink', 'thing', 'ting-ting'], a: 'sink / tink', e: "TH sering diganti S atau T." },
    { q: "Suara V vs F — mana yang lebih umum bermasalah?", o: ['V (karena mirip F)', 'F', 'Keduanya mudah'], a: 'V (karena mirip F)', e: "Indonesia sering samakan V dan F." },
    { q: "Akhiran -ed di 'walked' sering salah diucapkan menjadi...", o: ['walk-ed (3 suku)', 'walked (/t/)', 'walk'], a: 'walk-ed (3 suku)', e: "Penutur Indonesia sering tambah suku kata." },
    { q: "Vokal /æ/ dalam 'cat' sering menjadi...", o: ['/e/ (cet)', '/ɒ/ (cot)', '/ɪ/ (cit)'], a: '/e/ (cet)', e: "Tidak ada /æ/ di Indonesia — dibulat ke /e/." },
    { q: "Bunyi /ʃ/ dalam 'ship' sering menjadi...", o: ['/s/', '/tʃ/', '/ʒ/'], a: '/s/', e: "SH sering tereduksi ke S." },
    { q: "Schwa /ə/ sulit karena...", o: ['Tidak ada di Bahasa Indonesia', 'Terlalu panjang', 'Terlalu keras'], a: 'Tidak ada di Bahasa Indonesia', e: "Schwa tidak dikenal dalam fonem Indonesia." },
    { q: "Penutur Indonesia cenderung menekankan...", o: ['Setiap suku sama kuat', 'Hanya suku depan', 'Hanya suku belakang'], a: 'Setiap suku sama kuat', e: "Bahasa Indonesia syllable-timed." },
    { q: "Untuk menguasai TH, trik-nya adalah...", o: ['Lidah di antara gigi', 'Gigit bibir', 'Buka mulut lebar'], a: 'Lidah di antara gigi', e: "TH = lidah menjulur antar gigi." },
    { q: "Konsonan akhir /p,t,k/ sering...", o: ['Dihilangkan atau lembut', 'Diucapkan ganda', 'Diganti B/D/G'], a: 'Dihilangkan atau lembut', e: "Penutur Indonesia sering 'menelan' konsonan akhir." },
    { q: "Kata 'important' sering salah tekan di...", o: ['IM-portant', 'im-POR-tant', 'im-por-TANT'], a: 'im-POR-tant', e: "Yang benar: im-POR-tant." },
    { q: "Untuk V, yang harus dilakukan bibir...", o: ['Membulat', 'Gigi atas menggigit bibir bawah', 'Menutup rapat'], a: 'Gigi atas menggigit bibir bawah', e: "V = labiodental fricative." },
    { q: "Kata 'very' sering salah menjadi...", o: ['fery/berry', 'wary', 'vury'], a: 'fery/berry', e: "V diganti F atau B." },
    { q: "Linking (wake up → wa-kup) terasa aneh karena...", o: ['Tidak dipakai di Indonesia', 'Sulit dengar', 'Melanggar ejaan'], a: 'Tidak dipakai di Indonesia', e: "Bahasa Indonesia: batas kata jelas." },
    { q: "Perbedaan /iː/ vs /ɪ/ penting karena...", o: ['Sheep vs Ship bisa bikin miskomunikasi', 'Hanya gaya', 'Sama saja'], a: 'Sheep vs Ship bisa bikin miskomunikasi', e: "Minimal pair = beda makna." },
    { q: "Cara melatih -ed = /t/ tanpa menambah suku:", o: ['Gabungkan dengan akhir kata', 'Pisahkan jelas', 'Berbisik'], a: 'Gabungkan dengan akhir kata', e: "Walked = /wɔːkt/ — 1 suku." },
    { q: "Masalah umum intonasi penutur Indonesia:", o: ['Terlalu datar/monoton', 'Terlalu naik-turun', 'Tidak ada masalah'], a: 'Terlalu datar/monoton', e: "Indonesia lebih rata dari English." },
    { q: "R dalam Bahasa Inggris Amerika:", o: ['Digetarkan (trill)', 'Ditarik ke belakang (bunched)', 'Seperti L'], a: 'Ditarik ke belakang (bunched)', e: "American R ≠ Indonesian R." },
    { q: "Untuk memperbaiki pelafalan, kuncinya:", o: ['Mendengar & mengulang banyak', 'Hanya membaca', 'Hanya menulis'], a: 'Mendengar & mengulang banyak', e: "Pelafalan = keterampilan fisik." },
    { q: "Realitas penutur asing yang sukses:", o: ['Aksennya selalu sempurna', 'Dipahami dengan jelas', 'Tidak pernah salah'], a: 'Dipahami dengan jelas', e: "Tujuan: kejelasan, bukan aksen asli." },
  ],
  12: [ // Teknik Shadowing
    { q: "Shadowing adalah teknik...", o: ['Membaca dalam hati', 'Mengulang sesegera mungkin audio penutur asli', 'Menulis ulang teks'], a: 'Mengulang sesegera mungkin audio penutur asli', e: "Shadow = mengikuti 'seperti bayangan'." },
    { q: "Manfaat utama shadowing adalah...", o: ['Kosakata bertambah', 'Pelafalan, ritme & intonasi natural', 'Tata bahasa'], a: 'Pelafalan, ritme & intonasi natural', e: "Shadowing melatih fitur suprasegmental." },
    { q: "Bahan shadowing terbaik adalah...", o: ['Podcast atau video penutur asli', 'Teks formal', 'Grammar book'], a: 'Podcast atau video penutur asli', e: "Audio natural = model terbaik." },
    { q: "Langkah pertama shadowing:", o: ['Langsung ucap ulang', 'Dengar dulu tanpa berbicara', 'Tulis transkrip'], a: 'Dengar dulu tanpa berbicara', e: "Kenali audio dulu." },
    { q: "Jarak waktu ideal antara audio dan ucapanmu:", o: ['3-5 detik', 'Sekitar 1 kata tertinggal', 'Bersamaan persis'], a: 'Sekitar 1 kata tertinggal', e: "Delay pendek — mengikuti 'bayangan'." },
    { q: "Shadowing 'berbisik' cocok untuk...", o: ['Pemula yang mau fokus pelafalan', 'Ahli saja', 'Tidak berguna'], a: 'Pemula yang mau fokus pelafalan', e: "Whisper shadowing kurangi beban vokal." },
    { q: "Content shadowing fokus pada...", o: ['Meniru bunyi persis', 'Memahami makna sambil ikuti', 'Hanya menghafal'], a: 'Memahami makna sambil ikuti', e: "Content > mimicry stage." },
    { q: "Fitur yang harus ditiru saat shadowing:", o: ['Kata per kata saja', 'Intonasi, ritme, jeda, kecepatan', 'Hanya vokal'], a: 'Intonasi, ritme, jeda, kecepatan', e: "Tiru semuanya." },
    { q: "Frekuensi latihan shadowing yang efektif:", o: ['Setiap hari 10-20 menit', 'Sekali seminggu 3 jam', 'Sekali sebulan'], a: 'Setiap hari 10-20 menit', e: "Konsisten > lama tapi jarang." },
    { q: "Jika sulit mengikuti, kamu harus...", o: ['Menyerah', 'Memperlambat audio', 'Mempercepat audio'], a: 'Memperlambat audio', e: "Turunkan speed 0.75-0.8x." },
    { q: "Kesalahan umum dalam shadowing:", o: ['Menunggu audio selesai baru bicara', 'Mengikuti segera', 'Fokus intonasi'], a: 'Menunggu audio selesai baru bicara', e: "Itu bukan shadowing, itu repetition." },
    { q: "Idealnya audio shadowing adalah...", o: ['Satu suku kata per 5 detik', 'Kecepatan natural penutur asli', 'Terlalu pelan'], a: 'Kecepatan natural penutur asli', e: "Natural pace = target." },
    { q: "Untuk melihat progres, rekam...", o: ['Suaramu & bandingkan dengan original', 'Teks bacaan', 'Gerakan bibir'], a: 'Suaramu & bandingkan dengan original', e: "Self-recording penting." },
    { q: "Fokus shadowing minggu 1 sebaiknya:", o: ['Intonasi & ritme', 'Makna lengkap', 'Grammar'], a: 'Intonasi & ritme', e: "Bangun 'musik' bahasa dulu." },
    { q: "Apakah penting paham SEMUA kata saat shadowing?", o: ['Ya, 100%', 'Tidak — fokus bunyi dulu', 'Hanya grammar'], a: 'Tidak — fokus bunyi dulu', e: "Meaning bisa diperiksa terpisah." },
    { q: "Teknik shadowing digunakan juga oleh...", o: ['Penerjemah simultan profesional', 'Hanya pelajar bahasa', 'Guru saja'], a: 'Penerjemah simultan profesional', e: "Simultaneous interpreters berlatih shadowing." },
    { q: "Saat shadowing, postur harus...", o: ['Membungkuk', 'Tegak & rileks', 'Tiduran'], a: 'Tegak & rileks', e: "Posture mendukung napas & suara." },
    { q: "Lingkungan shadowing yang ideal:", o: ['Ramai agar terbiasa', 'Tenang dengan headphone', 'Di luar ruangan'], a: 'Tenang dengan headphone', e: "Minimalkan distraksi di awal." },
    { q: "Apa yang BUKAN manfaat shadowing?", o: ['Pelafalan', 'Kecepatan bicara', 'Kemampuan menulis esai'], a: 'Kemampuan menulis esai', e: "Shadowing adalah speaking/listening." },
    { q: "Tingkat teks shadowing idealnya...", o: ['Jauh di atas levelmu', 'Sedikit di atas atau sejajar', 'Jauh di bawah'], a: 'Sedikit di atas atau sejajar', e: "i+1 principle." },
  ],
  13: [ // Membangun Kefasihan
    { q: "Kefasihan (fluency) berbeda dengan akurasi — fluency fokus pada...", o: ['Grammar sempurna', 'Kelancaran tanpa banyak jeda', 'Kosakata kompleks'], a: 'Kelancaran tanpa banyak jeda', e: "Fluency = flow." },
    { q: "Untuk mengurangi jeda panjang, gunakan...", o: ['Filler natural (um, well, you know)', 'Diam total', 'Mengulang kata'], a: 'Filler natural (um, well, you know)', e: "Native speakers juga pakai filler." },
    { q: "Teknik 'chunking' maksudnya...", o: ['Memotong kalimat acak', 'Mengucapkan frasa sebagai satu kesatuan', 'Menghindari kalimat panjang'], a: 'Mengucapkan frasa sebagai satu kesatuan', e: "Chunk = unit of meaning." },
    { q: "Untuk fluency, fokus utama pertama:", o: ['Hindari semua kesalahan', 'Keep going — jangan berhenti di setiap kata', 'Bicara pelan sekali'], a: 'Keep going — jangan berhenti di setiap kata', e: "Flow > perfection di tahap ini." },
    { q: "Collocation umum seperti 'make a decision' harus...", o: ['Dihafal sebagai chunk', 'Diterjemahkan kata demi kata', 'Dihindari'], a: 'Dihafal sebagai chunk', e: "Chunks meningkatkan kecepatan." },
    { q: "'Thinking aloud' dalam L1 dulu sebelum L2:", o: ['Tidak membantu', 'Berguna untuk merancang struktur', 'Wajib selalu'], a: 'Berguna untuk merancang struktur', e: "Pre-planning bantu fluency." },
    { q: "Kecepatan bicara yang terlalu pelan bisa:", o: ['Membuat terlihat profesional', 'Mengurangi kefasihan dan intonasi natural', 'Selalu lebih baik'], a: 'Mengurangi kefasihan dan intonasi natural', e: "Too slow kills rhythm." },
    { q: "Latihan 4/3/2 artinya:", o: ['Cerita yang sama dalam 4, 3, dan 2 menit', 'Empat topik dalam 3 menit 2 kali', 'Tidak ada hubungan dengan waktu'], a: 'Cerita yang sama dalam 4, 3, dan 2 menit', e: "Nation's fluency technique." },
    { q: "'Parroting' pada penutur asli:", o: ['Meniru frasa apa adanya', 'Menghindari frasa itu', 'Hanya menulisnya'], a: 'Meniru frasa apa adanya', e: "Copy natural chunks." },
    { q: "Agar lebih fasih, ukur progresmu dengan:", o: ['Jumlah kata per menit', 'Nilai ujian saja', 'Jumlah halaman buku'], a: 'Jumlah kata per menit', e: "WPM = metrik objektif." },
    { q: "Ketika lupa kata, strategi yang baik:", o: ['Diam lama mencari kata', 'Parafrase — deskripsikan', 'Ganti bahasa Indonesia'], a: 'Parafrase — deskripsikan', e: "Circumlocution menjaga flow." },
    { q: "Membaca keras (read aloud) membantu fluency karena:", o: ['Menyelaraskan mata-mulut-telinga', 'Menghafalkan teks', 'Membuat ngantuk'], a: 'Menyelaraskan mata-mulut-telinga', e: "Read aloud = multi-channel." },
    { q: "Menghafal dialog pendek membantu karena:", o: ['Menyediakan chunk siap pakai', 'Mengurangi kosa kata', 'Tidak membantu'], a: 'Menyediakan chunk siap pakai', e: "Ready-made phrases." },
    { q: "Topik yang sering kamu bahas dalam bahasa Ibu — di English:", o: ['Latih dulu agar otomatis', 'Hindari', 'Tidak perlu dilatih'], a: 'Latih dulu agar otomatis', e: "Automatize frequent topics." },
    { q: "Untuk variasi, latih fluency dengan:", o: ['Monolog, dialog role-play, & diskusi', 'Hanya membaca', 'Hanya menulis'], a: 'Monolog, dialog role-play, & diskusi', e: "Variety strengthens skill." },
    { q: "Ketika bingung, strategi terbaik:", o: ['Pause singkat + filler', 'Stop total', 'Ganti topik'], a: 'Pause singkat + filler', e: "Keep the channel open." },
    { q: "Fluency yang baik punya ciri:", o: ['Berbicara seperti robot', 'Ritme alami dengan jeda wajar di batas frasa', 'Tidak pernah berhenti'], a: 'Ritme alami dengan jeda wajar di batas frasa', e: "Natural breaks di boundary." },
    { q: "Apa yang perlu dihindari untuk fluency:", o: ['Self-correction berulang mid-sentence', 'Berlatih rutin', 'Meniru native'], a: 'Self-correction berulang mid-sentence', e: "Over-monitoring menghambat flow." },
    { q: "Fluency dapat dilatih dengan berbicara sendiri (self-talk)?", o: ['Ya, efektif untuk otomatisasi', 'Tidak, harus ada lawan bicara', 'Merugikan'], a: 'Ya, efektif untuk otomatisasi', e: "Self-talk = low-stakes practice." },
    { q: "Manakah BUKAN kriteria fluency?", o: ['Kecepatan', 'Kelancaran', 'Aksen identik native'], a: 'Aksen identik native', e: "Fluency ≠ accent." },
  ],
  14: [ // Kesadaran Aksen
    { q: "Kata 'schedule' dalam aksen Amerika (US):", o: ['/ˈskedʒuːl/', '/ˈʃedjuːl/', 'Keduanya'], a: '/ˈskedʒuːl/', e: "US: 'ske-jool'; UK: 'shed-yool'." },
    { q: "Kata 'schedule' dalam aksen British (UK):", o: ['/ˈskedʒuːl/', '/ˈʃedjuːl/'], a: '/ˈʃedjuːl/', e: "UK umumnya /ʃ/." },
    { q: "Kata 'water' dalam US sering terdengar seperti...", o: ['wa-ter jelas', 'wa-der (flap T)', 'wa-tah'], a: 'wa-der (flap T)', e: "American flap-T." },
    { q: "Kata 'water' dalam UK (RP)...", o: ['wa-tuh', 'wa-der', 'wa-ter jelas atau glottal'], a: 'wa-ter jelas atau glottal', e: "RP tidak pakai flap." },
    { q: "Kata 'dance' dalam US vs UK:", o: ['Sama', 'US /æ/, UK /ɑː/', 'US /ɑː/, UK /æ/'], a: 'US /æ/, UK /ɑː/', e: "UK 'dahnce', US 'dance'." },
    { q: "Aksen 'rhotic' artinya...", o: ['Menghilangkan R di akhir', 'Mengucapkan R di akhir (car = kar)', 'Tidak ada R'], a: 'Mengucapkan R di akhir (car = kar)', e: "US rhotic; British RP non-rhotic." },
    { q: "Kata 'car' dalam RP British:", o: ['/kɑːr/', '/kɑː/', '/kær/'], a: '/kɑː/', e: "Tanpa R akhir (non-rhotic)." },
    { q: "Kata 'can't' dalam UK vs US:", o: ['US /kænt/, UK /kɑːnt/', 'Sama', 'US /kɑːnt/, UK /kænt/'], a: 'US /kænt/, UK /kɑːnt/', e: "UK 'cahn\\'t'." },
    { q: "Kata 'tomato' dalam US:", o: ['/təˈmeɪtoʊ/', '/təˈmɑːtoʊ/'], a: '/təˈmeɪtoʊ/', e: "US: 'tuh-MAY-toh'." },
    { q: "Kata 'tomato' dalam UK:", o: ['/təˈmeɪtəʊ/', '/təˈmɑːtəʊ/'], a: '/təˈmɑːtəʊ/', e: "UK: 'tuh-MAH-toh'." },
    { q: "Kata 'bath' dalam US vs UK:", o: ['US /æ/, UK /ɑː/', 'Keduanya /ɑː/', 'Keduanya /æ/'], a: 'US /æ/, UK /ɑː/', e: "UK 'bahth'." },
    { q: "'Mobile' dalam US:", o: ['/ˈmoʊbəl/', '/ˈmoʊbaɪl/'], a: '/ˈmoʊbəl/', e: "US sering 'MOH-bull'." },
    { q: "'Mobile' dalam UK:", o: ['/ˈməʊbəl/', '/ˈməʊbaɪl/'], a: '/ˈməʊbaɪl/', e: "UK: 'MOH-byle'." },
    { q: "Aksen Australia cenderung...", o: ['Lebih rhotic dari US', 'Non-rhotic seperti RP', 'Identik dengan US'], a: 'Non-rhotic seperti RP', e: "Australian English non-rhotic." },
    { q: "Memilih aksen mana untuk dipelajari:", o: ['Wajib US', 'Wajib UK', 'Sesuai tujuan komunikasimu'], a: 'Sesuai tujuan komunikasimu', e: "Pilih yang paling relevan." },
    { q: "Paling penting dalam komunikasi global:", o: ['Aksen identik native', 'Kejelasan & keterpahaman', 'Kosakata slang'], a: 'Kejelasan & keterpahaman', e: "Intelligibility first." },
    { q: "Kata 'either' bisa diucapkan...", o: ['/ˈaɪðər/ atau /ˈiːðər/', 'Hanya /ˈaɪðər/', 'Hanya /ˈiːðər/'], a: '/ˈaɪðər/ atau /ˈiːðər/', e: "Kedua varian diterima." },
    { q: "Aksen GA (General American) vs RP — tingkat kesepakatan:", o: ['Dipahami luas di dunia', 'Hanya di negara asalnya', 'Sangat berbeda sampai tidak bisa saling paham'], a: 'Dipahami luas di dunia', e: "Both are widely understood." },
    { q: "Mencampur aksen US dan UK:", o: ['Dilarang', 'Wajar — banyak penutur bilingual/global lakukan', 'Aneh dan salah'], a: 'Wajar — banyak penutur bilingual/global lakukan', e: "Mixing is common." },
    { q: "Tujuan 'accent awareness' bukanlah...", o: ['Mengubah aksenmu drastis', 'Memahami variasi yang kamu dengar', 'Memilih target aksen'], a: 'Mengubah aksenmu drastis', e: "Awareness ≠ imitation." },
  ],
  15: [ // Penilaian Akhir
    { q: "Kata mana dengan vokal PANJANG?", o: ['Sit', 'Seat', 'Bit'], a: 'Seat', e: "/iː/ panjang." },
    { q: "Akhiran -ed pada 'Started' adalah...", o: ['/t/', '/d/', '/ɪd/'], a: '/ɪd/', e: "Berakhir /t/ → /ɪd/." },
    { q: "Kalimat 'She went to the park' — kata yang ditekan:", o: ['to', 'the', 'park'], a: 'park', e: "Kata isi (noun) ditekan." },
    { q: "'Wake up' terhubung menjadi...", o: ['Wake...up', 'Wa-kup'], a: 'Wa-kup', e: "Linking konsonan-vokal." },
    { q: "Pertanyaan Yes/No berintonasi...", o: ['Turun ↘', 'Naik ↗'], a: 'Naik ↗', e: "Yes/No = rising." },
    { q: "'Comfortable' alami diucapkan...", o: ['4 suku', '3 suku (comf-ta-ble)'], a: '3 suku (comf-ta-ble)', e: "Elisi schwa." },
    { q: "'Vegetable' tekanan di...", o: ['Suku ke-1 (VEG-ta-ble)', 'Suku ke-2'], a: 'Suku ke-1 (VEG-ta-ble)', e: "Stress di depan." },
    { q: "Minimal pair /f/ vs /v/:", o: ['Cat-Dog', 'Fan-Van', 'Big-Small'], a: 'Fan-Van', e: "Hanya konsonan awal berbeda." },
    { q: "TH tak bersuara pada kata...", o: ['This', 'Think', 'That'], a: 'Think', e: "/θ/." },
    { q: "'Record' sebagai NOUN ditekan di...", o: ['RE-cord', 're-CORD'], a: 'RE-cord', e: "Noun: depan." },
    { q: "Kata 'can' dalam 'I can swim' diucapkan...", o: ['/kæn/', '/kən/'], a: '/kən/', e: "Weak form." },
    { q: "Akhiran -s pada 'buses' adalah...", o: ['/s/', '/z/', '/ɪz/'], a: '/ɪz/', e: "Setelah /s/ → /ɪz/." },
    { q: "Question tag konfirmasi (yakin) pakai...", o: ['Turun ↘', 'Naik ↗'], a: 'Turun ↘', e: "Falling = confident." },
    { q: "Magic E membuat vokal menjadi...", o: ['Panjang', 'Pendek'], a: 'Panjang', e: "Hop→Hope." },
    { q: "'Going to' informal:", o: ['gonna', 'go-to'], a: 'gonna', e: "Assimilation." },
    { q: "Aksen yang menjatuhkan R di akhir kata disebut...", o: ['Rhotic', 'Non-rhotic', 'Flap-R'], a: 'Non-rhotic', e: "RP British = non-rhotic." },
    { q: "'Bath' dalam UK diucapkan dengan vokal...", o: ['/æ/', '/ɑː/'], a: '/ɑː/', e: "UK broad A." },
    { q: "Kata tak bertekanan sering memakai vokal...", o: ['/æ/', '/ə/ schwa', '/iː/'], a: '/ə/ schwa', e: "Schwa = unstressed." },
    { q: "'Don't you' cepat menjadi...", o: ['Don-you', 'Don-chu'], a: 'Don-chu', e: "Asimilasi /t+j/ → /tʃ/." },
    { q: "Tujuan paling penting dalam pronunciation:", o: ['Aksen identik native', 'Keterpahaman (intelligibility)', 'Kecepatan maksimal'], a: 'Keterpahaman (intelligibility)', e: "Clarity > accent perfection." },
  ],
};

function buildQuizBlock(arr, indent = '  ') {
  const items = arr.map((it, i) => {
    const id = i + 1;
    const opts = it.o.map(o => `'${o.replace(/'/g, "\\'")}'`).join(', ');
    return `${indent}{
${indent}  id: ${id},
${indent}  question: "${it.q.replace(/"/g, '\\"')}",
${indent}  options: [${opts}],
${indent}  answer: '${it.a.replace(/'/g, "\\'")}',
${indent}  explanation: "${it.e.replace(/"/g, '\\"')}"
${indent}}`;
  });
  return items.join(',\n');
}

for (let n = 1; n <= 15; n++) {
  const file = path.join(DIR, `Lesson${n}.tsx`);
  let code = fs.readFileSync(file, 'utf8');
  const arr = Q[n];
  if (!arr) { console.log(`- Skip Lesson${n} (no data)`); continue; }

  const varName = n === 15 ? 'FINAL_QUIZ_QUESTIONS' : 'QUIZ_QUESTIONS';
  const re = new RegExp(`const ${varName}\\s*=\\s*\\[[\\s\\S]*?\\];`);
  if (!re.test(code)) { console.log(`! Pattern not found in Lesson${n}`); continue; }

  const block = `const ${varName} = [\n${buildQuizBlock(arr)}\n];`;
  code = code.replace(re, block);
  fs.writeFileSync(file, code);
  console.log(`✓ Lesson${n}: 20 pertanyaan`);
}
