import type { LexiconEntry } from './types';

export const a1Extra: LexiconEntry[] = [
  ['mother', 'ibu', 'My mother cooks rice every day.'], ['father', 'ayah', 'My father works in a bank.'],
  ['brother', 'saudara laki-laki', 'My brother is ten years old.'], ['sister', 'saudara perempuan', 'My sister likes music.'],
  ['baby', 'bayi', 'The baby is sleeping.'], ['child', 'anak', 'The child is playing in the park.'],
  ['man', 'pria', 'That man is my uncle.'], ['woman', 'wanita', 'The woman in red is a doctor.'],
  ['boy', 'anak laki-laki', 'The boy has a blue bike.'], ['girl', 'anak perempuan', 'The girl is reading a book.'],
  ['cat', 'kucing', 'My cat is black and white.'], ['dog', 'anjing', 'The dog is under the table.'],
  ['bird', 'burung', 'A small bird is on the tree.'], ['fish', 'ikan', 'We eat fish on Friday.'],
  ['rice', 'nasi / beras', 'I eat rice for lunch.'], ['bread', 'roti', 'She buys bread every morning.'],
  ['egg', 'telur', 'I want one egg, please.'], ['milk', 'susu', 'The milk is in the fridge.'],
  ['tea', 'teh', 'Do you want tea or coffee?'], ['coffee', 'kopi', 'My father drinks coffee at seven.'],
  ['apple', 'apel', 'This apple is very sweet.'], ['banana', 'pisang', 'Monkeys like bananas.'],
  ['chicken', 'ayam', 'We have chicken soup today.'], ['breakfast', 'sarapan', 'I have breakfast at six.'],
  ['lunch', 'makan siang', 'Lunch is at twelve o clock.'], ['dinner', 'makan malam', 'We have dinner together.'],
  ['eat', 'makan', 'I eat vegetables every day.'], ['drink', 'minum', 'Drink some water after sport.'],
  ['sleep', 'tidur', 'I sleep at ten every night.'], ['wake up', 'bangun tidur', 'I wake up at five.'],
  ['walk', 'berjalan', 'We walk to school.'], ['run', 'berlari', 'He can run very fast.'],
  ['swim', 'berenang', 'Can you swim?'], ['read', 'membaca', 'I read the news on my phone.'],
  ['write', 'menulis', 'Please write your name here.'], ['listen', 'mendengarkan', 'Listen to the teacher.'],
  ['speak', 'berbicara', 'Do you speak English?'], ['see', 'melihat', 'I can see the sea from here.'],
  ['watch', 'menonton', 'We watch TV in the evening.'], ['play', 'bermain', 'The children play football.'],
  ['buy', 'membeli', 'I want to buy a new bag.'], ['open', 'membuka', 'Please open the window.'],
  ['close', 'menutup', 'Close the door, please.'], ['come', 'datang', 'Come to my house on Sunday.'],
  ['sit', 'duduk', 'Please sit down.'], ['stand', 'berdiri', 'Stand in the line, please.'],
  ['give', 'memberi', 'Give me the pen, please.'], ['help', 'membantu', 'Can you help me?'],
  ['love', 'mencintai / sangat suka', 'I love my family.'], ['know', 'tahu', 'I know her name.'],
  ['car', 'mobil', 'My uncle has a white car.'], ['bus', 'bus', 'I go to work by bus.'],
  ['train', 'kereta', 'The train is late today.'], ['bike', 'sepeda', 'I ride my bike to school.'],
  ['road', 'jalan', 'This road is very long.'], ['park', 'taman', 'We play in the park.'],
  ['market', 'pasar', 'My mother goes to the market.'], ['hospital', 'rumah sakit', 'The hospital is near here.'],
  ['station', 'stasiun', 'The station is on the left.'], ['beach', 'pantai', 'The beach is beautiful.'],
  ['door', 'pintu', 'The door is open.'], ['window', 'jendela', 'Open the window, please.'],
  ['bed', 'tempat tidur', 'My bed is next to the window.'], ['kitchen', 'dapur', 'Mom is in the kitchen.'],
  ['bathroom', 'kamar mandi', 'The bathroom is upstairs.'], ['garden', 'kebun / taman', 'We have flowers in the garden.'],
  ['pen', 'pulpen', 'Can I borrow your pen?'], ['pencil', 'pensil', 'Write with a pencil.'],
  ['clock', 'jam dinding', 'The clock is on the wall.'], ['money', 'uang', 'I do not have much money.'],
  ['shirt', 'kemeja', 'He wears a white shirt.'], ['shoes', 'sepatu', 'My shoes are new.'],
  ['hat', 'topi', 'Wear a hat in the sun.'], ['red', 'merah', 'I like the red car.'],
  ['blue', 'biru', 'The sky is blue.'], ['green', 'hijau', 'The leaves are green.'],
  ['black', 'hitam', 'My cat is black.'], ['white', 'putih', 'The wall is white.'],
  ['hot', 'panas', 'It is hot today.'], ['cold', 'dingin', 'The water is cold.'],
  ['good', 'baik / bagus', 'This is a good film.'], ['bad', 'buruk', 'The weather is bad today.'],
  ['beautiful', 'indah / cantik', 'Bali is beautiful.'], ['tall', 'tinggi', 'My brother is very tall.'],
  ['short', 'pendek', 'She has short hair.'], ['long', 'panjang', 'It is a long road.'],
  ['fast', 'cepat', 'This train is fast.'], ['slow', 'lambat', 'The old bus is slow.'],
  ['tired', 'lelah', 'I am tired after work.'], ['hungry', 'lapar', 'I am hungry. Let us eat.'],
  ['sad', 'sedih', 'He is sad today.'], ['sick', 'sakit', 'I am sick, so I stay home.'],
  ['today', 'hari ini', 'Today is Monday.'], ['tomorrow', 'besok', 'See you tomorrow.'],
  ['yesterday', 'kemarin', 'I was at home yesterday.'], ['week', 'minggu', 'I work five days a week.'],
  ['month', 'bulan', 'My birthday is next month.'], ['year', 'tahun', 'This year I study English.'],
  ['hour', 'jam (60 menit)', 'The class is one hour long.'], ['minute', 'menit', 'Wait a minute, please.'],
  ['weather', 'cuaca', 'The weather is nice.'], ['rain', 'hujan', 'The rain is heavy.'],
  ['sun', 'matahari', 'The sun is very hot.'], ['hand', 'tangan', 'Wash your hands.'],
  ['head', 'kepala', 'My head hurts.'], ['eye', 'mata', 'She has brown eyes.'],
  ['job', 'pekerjaan', 'I like my new job.'], ['doctor', 'dokter', 'The doctor is very kind.'],
  ['sport', 'olahraga', 'My favorite sport is badminton.'], ['music', 'musik', 'I listen to music every day.'],
  ['film', 'film', 'This film is funny.'], ['game', 'permainan', 'We play a game after class.'],
  ['picture', 'gambar / foto', 'Look at this picture.'], ['question', 'pertanyaan', 'I have a question.'],
  ['answer', 'jawaban', 'Your answer is correct.'], ['word', 'kata', 'Learn five new words a day.'],
  ['here', 'di sini', 'Come here, please.'], ['there', 'di sana', 'The bank is over there.'],
  ['always', 'selalu', 'I always drink tea in the morning.'], ['never', 'tidak pernah', 'I never eat meat.'],
];

export const a2Extra: LexiconEntry[] = [
  ['weekend', 'akhir pekan', 'We visit my grandparents every weekend.'], ['holiday', 'liburan', 'Our holiday starts next week.'],
  ['ticket', 'tiket', 'I bought a ticket online.'], ['airport', 'bandara', 'The airport is far from the city.'],
  ['passport', 'paspor', 'Do not forget your passport.'], ['luggage', 'bagasi', 'My luggage is too heavy.'],
  ['hotel', 'hotel', 'The hotel is near the beach.'], ['reservation', 'reservasi', 'I have a reservation for two nights.'],
  ['map', 'peta', 'Can you show me on the map?'], ['direction', 'arah', 'Which direction is the station?'],
  ['corner', 'sudut / tikungan', 'The café is on the corner.'], ['straight', 'lurus', 'Go straight and turn left.'],
  ['turn', 'belok', 'Turn right at the bank.'], ['cross', 'menyeberang', 'Cross the road carefully.'],
  ['price', 'harga', 'The price is too high.'], ['cheap', 'murah', 'These shoes are cheap.'],
  ['expensive', 'mahal', 'The hotel is expensive.'], ['discount', 'diskon', 'There is a discount on Fridays.'],
  ['receipt', 'struk / kuitansi', 'Can I have the receipt, please?'], ['size', 'ukuran', 'What size do you need?'],
  ['try on', 'mencoba (pakaian)', 'Can I try on this jacket?'], ['refund', 'pengembalian uang', 'I want a refund for this bag.'],
  ['menu', 'menu', 'Can I see the menu, please?'], ['bill', 'tagihan', 'We asked for the bill.'],
  ['spicy', 'pedas', 'This soup is very spicy.'], ['delicious', 'lezat', 'The cake was delicious.'],
  ['recipe', 'resep', 'My grandmother gave me her recipe.'], ['ingredient', 'bahan', 'Rice is the main ingredient.'],
  ['kitchen', 'dapur', 'The kitchen is clean now.'], ['fridge', 'kulkas', 'Put the milk in the fridge.'],
  ['neighbor', 'tetangga', 'Our neighbor has a big dog.'], ['apartment', 'apartemen', 'We live in a small apartment.'],
  ['rent', 'sewa / menyewa', 'The rent is due on Monday.'], ['furniture', 'perabot', 'We need new furniture.'],
  ['cousin', 'sepupu', 'My cousin lives in Surabaya.'], ['uncle', 'paman', 'My uncle is a pilot.'],
  ['aunt', 'bibi / tante', 'My aunt makes great cakes.'], ['grandmother', 'nenek', 'My grandmother is eighty.'],
  ['married', 'menikah', 'My sister is married.'], ['wedding', 'pernikahan', 'The wedding is in June.'],
  ['birthday', 'ulang tahun', 'Happy birthday to you!'], ['party', 'pesta', 'We had a party last night.'],
  ['gift', 'hadiah', 'Thank you for the gift.'], ['celebrate', 'merayakan', 'We celebrate Eid with family.'],
  ['hobby', 'hobi', 'My hobby is painting.'], ['camera', 'kamera', 'I took photos with my camera.'],
  ['guitar', 'gitar', 'He plays the guitar well.'], ['museum', 'museum', 'We visited the museum on Sunday.'],
  ['concert', 'konser', 'The concert was amazing.'], ['team', 'tim', 'Our team won the match.'],
  ['match', 'pertandingan', 'The match starts at eight.'], ['exercise', 'olahraga / latihan', 'I exercise three times a week.'],
  ['healthy', 'sehat', 'Fruit is healthy food.'], ['medicine', 'obat', 'Take this medicine after meals.'],
  ['fever', 'demam', 'The child has a fever.'], ['headache', 'sakit kepala', 'I have a bad headache.'],
  ['appointment', 'janji temu', 'I have a doctor appointment at ten.'], ['pharmacy', 'apotek', 'The pharmacy closes at nine.'],
  ['office', 'kantor', 'My office is on the third floor.'], ['meeting', 'rapat', 'The meeting starts at two.'],
  ['colleague', 'rekan kerja', 'My colleague helped me today.'], ['boss', 'atasan', 'My boss is very friendly.'],
  ['salary', 'gaji', 'The salary is paid monthly.'], ['interview', 'wawancara', 'I have a job interview tomorrow.'],
  ['subject', 'mata pelajaran', 'My favorite subject is history.'], ['exam', 'ujian', 'The exam was difficult.'],
  ['homework', 'pekerjaan rumah', 'Did you finish your homework?'], ['library', 'perpustakaan', 'I study in the library.'],
  ['dictionary', 'kamus', 'Look up the word in the dictionary.'], ['mistake', 'kesalahan', 'I made a small mistake.'],
  ['weather', 'cuaca', 'The weather was sunny yesterday.'], ['cloudy', 'berawan', 'It is cloudy this morning.'],
  ['windy', 'berangin', 'It was windy at the beach.'], ['season', 'musim', 'The rainy season starts in November.'],
  ['temperature', 'suhu', 'The temperature is thirty degrees.'], ['umbrella', 'payung', 'Take an umbrella with you.'],
  ['mountain', 'gunung', 'We climbed a mountain last year.'], ['river', 'sungai', 'The river is very wide.'],
  ['island', 'pulau', 'Indonesia has many islands.'], ['village', 'desa', 'My grandparents live in a village.'],
  ['feel', 'merasa', 'I feel better today.'], ['worried', 'khawatir', 'She is worried about the test.'],
  ['excited', 'bersemangat', 'I am excited about the trip.'], ['bored', 'bosan', 'I was bored at home.'],
  ['angry', 'marah', 'He was angry about the noise.'], ['surprised', 'terkejut', 'We were surprised by the news.'],
  ['send', 'mengirim', 'Please send me a message.'], ['call', 'menelepon', 'I will call you tonight.'],
  ['answer', 'menjawab', 'Please answer the phone.'], ['download', 'mengunduh', 'Download the app for free.'],
  ['password', 'kata sandi', 'Do not share your password.'], ['online', 'daring', 'I buy clothes online.'],
  ['remember', 'ingat', 'I remember his name.'], ['forget', 'lupa', 'Do not forget your keys.'],
  ['wait', 'menunggu', 'Please wait here.'], ['hope', 'berharap', 'I hope you feel better.'],
  ['decide', 'memutuskan', 'We decided to stay home.'], ['agree', 'setuju', 'I agree with you.'],
  ['explain', 'menjelaskan', 'Can you explain the rule?'], ['need', 'membutuhkan', 'I need more time.'],
  ['quiet', 'tenang / sepi', 'The library is quiet.'], ['noisy', 'bising', 'The street is noisy at night.'],
  ['crowded', 'ramai / padat', 'The market was crowded.'], ['dangerous', 'berbahaya', 'This road is dangerous at night.'],
  ['safe', 'aman', 'Is it safe to swim here?'], ['easy', 'mudah', 'The test was easy.'],
  ['difficult', 'sulit', 'Chinese is difficult for me.'], ['important', 'penting', 'This meeting is important.'],
  ['sometimes', 'kadang-kadang', 'I sometimes cook dinner.'], ['often', 'sering', 'We often go to the beach.'],
  ['already', 'sudah', 'I have already eaten.'], ['yet', 'belum (dalam pertanyaan/negatif)', 'Have you finished yet?'],
  ['soon', 'segera', 'The bus will come soon.'], ['later', 'nanti', 'See you later.'],
  ['together', 'bersama', 'We study together.'], ['alone', 'sendirian', 'She lives alone.'],
  ['towards', 'menuju', 'Walk towards the station.'], ['between', 'di antara', 'The bank is between the café and the shop.'],
  ['opposite', 'di seberang', 'The school is opposite the park.'], ['next to', 'di sebelah', 'Sit next to me.'],
  ['stay', 'tinggal / menginap', 'We stayed in a small hotel.'], ['return', 'kembali', 'I will return on Monday.'],
  ['rent a car', 'menyewa mobil', 'We decided to rent a car.'], ['book a room', 'memesan kamar', 'I want to book a room for Friday.'],
];
