import type { LexiconEntry } from './types';

export const b1Extra: LexiconEntry[] = [
  ['achieve', 'mencapai', 'She worked hard to achieve her goal.'], ['goal', 'tujuan / target', 'My goal is to pass the exam.'],
  ['effort', 'usaha', 'Learning a language takes effort.'], ['progress', 'kemajuan', 'You are making good progress.'],
  ['skill', 'keterampilan', 'Communication is an important skill.'], ['knowledge', 'pengetahuan', 'Reading increases your knowledge.'],
  ['career', 'karier', 'He wants a career in medicine.'], ['apply', 'melamar / menerapkan', 'I applied for a job at the bank.'],
  ['candidate', 'kandidat', 'The best candidate got the job.'], ['employee', 'karyawan', 'The company has fifty employees.'],
  ['employer', 'pemberi kerja', 'My employer pays for training.'], ['deadline', 'tenggat waktu', 'The deadline is next Friday.'],
  ['responsible', 'bertanggung jawab', 'Who is responsible for this project?'], ['task', 'tugas', 'Finish this task before lunch.'],
  ['project', 'proyek', 'Our project is almost finished.'], ['customer', 'pelanggan', 'The customer asked for a refund.'],
  ['service', 'layanan', 'The service in this hotel is excellent.'], ['complaint', 'keluhan', 'We received a complaint about the noise.'],
  ['complain', 'mengeluh', 'He complained about the cold food.'], ['apologize', 'meminta maaf', 'I apologize for the delay.'],
  ['delay', 'keterlambatan', 'There was a delay at the airport.'], ['cancel', 'membatalkan', 'They cancelled the meeting.'],
  ['arrange', 'mengatur', 'I will arrange a meeting for Monday.'], ['confirm', 'mengonfirmasi', 'Please confirm your booking.'],
  ['environment', 'lingkungan', 'We must protect the environment.'], ['pollution', 'polusi', 'Air pollution is a big problem.'],
  ['recycle', 'mendaur ulang', 'We recycle plastic bottles.'], ['waste', 'limbah / membuang', 'Do not waste water.'],
  ['energy', 'energi', 'Solar energy is clean.'], ['climate', 'iklim', 'The climate is changing.'],
  ['health', 'kesehatan', 'Sleep is important for your health.'], ['diet', 'pola makan', 'A balanced diet keeps you healthy.'],
  ['stress', 'stres', 'Exercise helps reduce stress.'], ['relax', 'bersantai', 'I relax by reading.'],
  ['habit', 'kebiasaan', 'Reading every day is a good habit.'], ['routine', 'rutinitas', 'My morning routine is simple.'],
  ['technology', 'teknologi', 'Technology makes life easier.'], ['device', 'perangkat', 'Turn off your devices in class.'],
  ['social media', 'media sosial', 'She spends hours on social media.'], ['website', 'situs web', 'Check the website for details.'],
  ['information', 'informasi', 'I need more information.'], ['advertisement', 'iklan', 'I saw an advertisement for the course.'],
  ['news', 'berita', 'Did you hear the news?'], ['article', 'artikel', 'I read an interesting article.'],
  ['opinion', 'pendapat', 'In my opinion, the film is too long.'], ['reason', 'alasan', 'What is the reason for your decision?'],
  ['example', 'contoh', 'Can you give me an example?'], ['result', 'hasil', 'The result was surprising.'],
  ['cause', 'penyebab / menyebabkan', 'Smoking can cause health problems.'], ['effect', 'efek / akibat', 'The medicine had a good effect.'],
  ['increase', 'meningkat', 'Prices increase every year.'], ['decrease', 'menurun', 'The number of visitors decreased.'],
  ['reduce', 'mengurangi', 'We need to reduce plastic waste.'], ['prevent', 'mencegah', 'Washing hands prevents illness.'],
  ['protect', 'melindungi', 'Sunscreen protects your skin.'], ['provide', 'menyediakan', 'The hotel provides free breakfast.'],
  ['offer', 'menawarkan', 'They offered me a job.'], ['accept', 'menerima', 'I accepted the invitation.'],
  ['refuse', 'menolak', 'He refused to answer.'], ['allow', 'mengizinkan', 'Phones are not allowed in the exam.'],
  ['expect', 'mengharapkan', 'I expect the package tomorrow.'], ['realize', 'menyadari', 'I realized I was wrong.'],
  ['notice', 'memperhatikan / pengumuman', 'Did you notice the new sign?'], ['discover', 'menemukan', 'Scientists discovered a new species.'],
  ['develop', 'mengembangkan', 'The company developed a new app.'], ['create', 'menciptakan', 'She created a beautiful design.'],
  ['share', 'berbagi', 'Share your ideas with the class.'], ['discuss', 'membahas', 'We discussed the plan.'],
  ['argue', 'berargumen / bertengkar', 'They argued about money.'], ['persuade', 'membujuk', 'I persuaded him to come.'],
  ['celebrate', 'merayakan', 'We celebrated our success.'], ['tradition', 'tradisi', 'Batik is part of our tradition.'],
  ['culture', 'budaya', 'I love learning about other cultures.'], ['festival', 'festival', 'The festival lasts three days.'],
  ['community', 'komunitas', 'Our community cleans the park monthly.'], ['volunteer', 'relawan', 'She works as a volunteer.'],
  ['government', 'pemerintah', 'The government built a new bridge.'], ['law', 'hukum / undang-undang', 'Everyone must follow the law.'],
  ['rule', 'aturan', 'The rules are clear.'], ['public', 'umum / publik', 'Public transport is cheap here.'],
  ['private', 'pribadi / swasta', 'He goes to a private school.'], ['population', 'penduduk', 'The population is growing.'],
  ['traffic', 'lalu lintas', 'Traffic is terrible in the morning.'], ['journey', 'perjalanan', 'The journey took six hours.'],
  ['destination', 'tujuan (perjalanan)', 'Bali is a popular destination.'], ['abroad', 'di luar negeri', 'She studied abroad for a year.'],
  ['foreign', 'asing', 'Learning a foreign language is useful.'], ['accommodation', 'akomodasi', 'The price includes accommodation.'],
  ['equipment', 'peralatan', 'The gym has modern equipment.'], ['instructions', 'petunjuk', 'Read the instructions carefully.'],
  ['patient', 'sabar / pasien', 'Be patient with beginners.'], ['honest', 'jujur', 'Thank you for being honest.'],
  ['polite', 'sopan', 'It is polite to say thank you.'], ['friendly', 'ramah', 'The staff were very friendly.'],
  ['nervous', 'gugup', 'I was nervous before the interview.'], ['proud', 'bangga', 'My parents are proud of me.'],
  ['disappointed', 'kecewa', 'We were disappointed with the result.'], ['embarrassed', 'malu', 'I felt embarrassed about my mistake.'],
  ['similar', 'mirip', 'Our ideas are similar.'], ['different', 'berbeda', 'Every culture is different.'],
  ['popular', 'populer', 'This song is very popular.'], ['common', 'umum / biasa', 'Rice is a common food in Asia.'],
  ['possible', 'mungkin', 'Is it possible to change the date?'], ['impossible', 'mustahil', 'Nothing is impossible.'],
  ['successful', 'sukses', 'The event was successful.'], ['useful', 'berguna', 'This app is very useful.'],
  ['actually', 'sebenarnya', 'Actually, I agree with you.'], ['recently', 'baru-baru ini', 'I recently moved to Jakarta.'],
  ['finally', 'akhirnya', 'We finally found the hotel.'], ['unfortunately', 'sayangnya', 'Unfortunately, the shop was closed.'],
  ['therefore', 'oleh karena itu', 'It rained; therefore, we stayed home.'], ['unless', 'kecuali jika', 'We will go unless it rains.'],
  ['while', 'sementara / saat', 'I listened to music while I cooked.'], ['since', 'sejak / karena', 'I have lived here since 2020.'],
  ['whether', 'apakah', 'I do not know whether he is coming.'], ['instead of', 'alih-alih', 'Walk instead of taking the bus.'],
];

export const b2Extra: LexiconEntry[] = [
  ['acknowledge', 'mengakui', 'He acknowledged his mistake.'], ['address', 'menangani (masalah)', 'We need to address the problem quickly.'],
  ['allocate', 'mengalokasikan', 'The school allocated more money to books.'], ['analyze', 'menganalisis', 'We analyzed the survey results.'],
  ['attitude', 'sikap', 'She has a positive attitude.'], ['awareness', 'kesadaran', 'The campaign raised awareness of recycling.'],
  ['behavior', 'perilaku', 'Children copy their parents behavior.'], ['boost', 'meningkatkan', 'Exercise can boost your mood.'],
  ['budget', 'anggaran', 'We are over budget this month.'], ['campaign', 'kampanye', 'The campaign was a success.'],
  ['capacity', 'kapasitas', 'The stadium has a capacity of 50,000.'], ['collaborate', 'berkolaborasi', 'The two teams collaborated on the project.'],
  ['commitment', 'komitmen', 'Learning requires long-term commitment.'], ['compromise', 'kompromi', 'Both sides reached a compromise.'],
  ['concern', 'kekhawatiran', 'Safety is our main concern.'], ['consequence', 'konsekuensi', 'Every choice has consequences.'],
  ['considerable', 'cukup besar', 'The project needs considerable time.'], ['conclude', 'menyimpulkan', 'The report concludes that prices will rise.'],
  ['conduct', 'melakukan', 'They conducted a survey of students.'], ['criticize', 'mengkritik', 'The plan was criticized by experts.'],
  ['crucial', 'sangat penting', 'Sleep is crucial for learning.'], ['demand', 'permintaan', 'Demand for electric cars is growing.'],
  ['determine', 'menentukan', 'Tests determine your level.'], ['diverse', 'beragam', 'Jakarta is a diverse city.'],
  ['emerge', 'muncul', 'New problems emerged during the test.'], ['encounter', 'menemui / menghadapi', 'We encountered several problems.'],
  ['enhance', 'meningkatkan kualitas', 'Good lighting can enhance a photo.'], ['ensure', 'memastikan', 'Please ensure the door is locked.'],
  ['estimate', 'memperkirakan', 'We estimate the cost at two million.'], ['evidence', 'bukti', 'There is no evidence for that claim.'],
  ['expand', 'memperluas', 'The company plans to expand abroad.'], ['expertise', 'keahlian', 'We need your expertise in design.'],
  ['factor', 'faktor', 'Price is an important factor.'], ['feasible', 'layak / memungkinkan', 'Is the plan feasible?'],
  ['focus', 'fokus', 'Focus on one task at a time.'], ['fundamental', 'mendasar', 'Trust is fundamental in a team.'],
  ['generate', 'menghasilkan', 'Solar panels generate electricity.'], ['guarantee', 'menjamin / jaminan', 'The shop offers a one-year guarantee.'],
  ['identify', 'mengidentifikasi', 'Can you identify the main problem?'], ['implement', 'menerapkan', 'The school implemented new rules.'],
  ['indicate', 'menunjukkan', 'The data indicate a clear trend.'], ['influence', 'pengaruh / memengaruhi', 'Parents influence their children.'],
  ['initiative', 'inisiatif', 'She took the initiative to help.'], ['innovation', 'inovasi', 'Innovation drives growth.'],
  ['investment', 'investasi', 'Education is a good investment.'], ['issue', 'isu / masalah', 'Housing is a major issue.'],
  ['justify', 'membenarkan', 'Can you justify the extra cost?'], ['lack', 'kekurangan', 'The project failed due to lack of funding.'],
  ['likely', 'kemungkinan besar', 'It is likely to rain tonight.'], ['measure', 'langkah / mengukur', 'The city took measures to reduce traffic.'],
  ['method', 'metode', 'This method works well.'], ['minimize', 'meminimalkan', 'We want to minimize risk.'],
  ['motivation', 'motivasi', 'Motivation is key to learning.'], ['objective', 'tujuan / objektif', 'The main objective is to cut costs.'],
  ['obstacle', 'hambatan', 'Language can be an obstacle.'], ['obtain', 'memperoleh', 'You must obtain a visa first.'],
  ['occur', 'terjadi', 'The accident occurred at night.'], ['option', 'pilihan', 'We have two options.'],
  ['participate', 'berpartisipasi', 'All students participated in the event.'], ['potential', 'potensi', 'She has great potential.'],
  ['previous', 'sebelumnya', 'My previous job was in sales.'], ['principle', 'prinsip', 'Honesty is my main principle.'],
  ['procedure', 'prosedur', 'Follow the safety procedure.'], ['promote', 'mempromosikan', 'The campaign promotes healthy eating.'],
  ['proportion', 'proporsi', 'A large proportion of students work part-time.'], ['pursue', 'mengejar', 'She wants to pursue a master degree.'],
  ['range', 'rentang / berbagai', 'The shop sells a wide range of products.'], ['rapid', 'pesat', 'The city has seen rapid growth.'],
  ['recover', 'pulih', 'The economy is starting to recover.'], ['reflect', 'mencerminkan / merenungkan', 'The results reflect our hard work.'],
  ['relevant', 'relevan', 'Please include only relevant information.'], ['rely on', 'mengandalkan', 'Many people rely on public transport.'],
  ['require', 'mensyaratkan', 'The job requires good English.'], ['resource', 'sumber daya', 'Water is a precious resource.'],
  ['respond', 'menanggapi', 'The company responded to complaints quickly.'], ['reveal', 'mengungkapkan', 'The survey revealed interesting facts.'],
  ['sector', 'sektor', 'Tourism is an important sector.'], ['seek', 'mencari', 'Many graduates seek jobs abroad.'],
  ['shift', 'pergeseran', 'There is a shift towards online shopping.'], ['solve', 'menyelesaikan', 'We solved the problem together.'],
  ['source', 'sumber', 'Check the source of the news.'], ['stable', 'stabil', 'Prices have been stable this year.'],
  ['sufficient', 'cukup', 'We do not have sufficient data.'], ['sustainable', 'berkelanjutan', 'We need sustainable energy.'],
  ['target', 'sasaran', 'We reached our sales target.'], ['tend', 'cenderung', 'People tend to spend more online.'],
  ['trend', 'tren', 'Remote work is a growing trend.'], ['ultimately', 'pada akhirnya', 'Ultimately, the decision is yours.'],
  ['valuable', 'berharga', 'This experience was valuable.'], ['variety', 'variasi', 'The menu offers a variety of dishes.'],
  ['whereby', 'yang dengannya', 'We created a system whereby staff can work from home.'], ['widespread', 'meluas', 'The use of smartphones is widespread.'],
  ['moreover', 'selain itu', 'The flat is cheap; moreover, it is close to work.'], ['furthermore', 'lebih lanjut', 'Furthermore, the plan saves money.'],
  ['despite', 'meskipun', 'Despite the rain, we went out.'], ['nonetheless', 'namun demikian', 'It was hard; nonetheless, we finished.'],
  ['in terms of', 'dari segi', 'In terms of price, this phone is better.'], ['as a result', 'akibatnya', 'As a result, sales increased.'],
  ['on the other hand', 'di sisi lain', 'On the other hand, it is expensive.'], ['to some extent', 'sampai batas tertentu', 'I agree to some extent.'],
  ['take into account', 'memperhitungkan', 'Take the weather into account.'], ['come up with', 'mencetuskan', 'She came up with a great idea.'],
  ['deal with', 'menangani', 'He deals with customer complaints.'], ['carry out', 'melaksanakan', 'They carried out the research in May.'],
  ['point out', 'menunjukkan', 'She pointed out a mistake in the report.'], ['bring about', 'menyebabkan', 'Technology brought about big changes.'],
];
