import type { LexiconEntry } from './types';

export const c1Extra: LexiconEntry[] = [
  ['accountability', 'akuntabilitas', 'Public officials must accept accountability.'], ['adequate', 'memadai', 'The evidence is not adequate.'],
  ['advocate', 'menganjurkan / pembela', 'She advocates for equal access to education.'], ['allegedly', 'konon / diduga', 'The minister allegedly accepted a bribe.'],
  ['ambiguity', 'ambiguitas', 'The contract contains some ambiguity.'], ['appraisal', 'penilaian', 'Staff receive an annual appraisal.'],
  ['articulate', 'mengungkapkan dengan jelas', 'She can articulate complex ideas clearly.'], ['attribute', 'menghubungkan / sifat', 'Experts attribute the rise to inflation.'],
  ['bias', 'bias', 'The report shows a clear bias.'], ['breakthrough', 'terobosan', 'Scientists made a major breakthrough.'],
  ['coincide', 'bertepatan', 'The festival coincides with the holiday.'], ['commence', 'dimulai', 'The ceremony will commence at nine.'],
  ['compatible', 'kompatibel', 'This software is compatible with older phones.'], ['compelling', 'meyakinkan', 'She made a compelling argument.'],
  ['complement', 'melengkapi', 'The two methods complement each other.'], ['comply', 'mematuhi', 'All companies must comply with the law.'],
  ['conceive', 'menggagas', 'The idea was conceived in 2019.'], ['concise', 'ringkas', 'Keep your summary concise.'],
  ['conform', 'menyesuaikan diri', 'Students must conform to the dress code.'], ['consensus', 'konsensus', 'There is a broad consensus on the issue.'],
  ['constitute', 'merupakan', 'Women constitute half of the workforce.'], ['contemplate', 'merenungkan', 'He contemplated leaving his job.'],
  ['contradict', 'bertentangan', 'The two reports contradict each other.'], ['conventional', 'konvensional', 'Conventional methods were too slow.'],
  ['correlation', 'korelasi', 'There is a correlation between sleep and grades.'], ['deficit', 'defisit', 'The budget deficit is growing.'],
  ['deliberate', 'disengaja', 'It was a deliberate decision.'], ['deploy', 'mengerahkan / menerapkan', 'The company deployed the new system.'],
  ['deteriorate', 'memburuk', 'His health deteriorated quickly.'], ['deviate', 'menyimpang', 'Do not deviate from the plan.'],
  ['diminish', 'berkurang', 'The pain diminished after a week.'], ['discourse', 'wacana', 'Political discourse has become polarized.'],
  ['discrimination', 'diskriminasi', 'The law bans discrimination at work.'], ['dispose', 'membuang', 'Dispose of batteries safely.'],
  ['diverge', 'berbeda arah', 'Their opinions diverge on this point.'], ['domain', 'ranah', 'Privacy is a complex legal domain.'],
  ['elaborate', 'menguraikan / rumit', 'Could you elaborate on that point?'], ['eligible', 'memenuhi syarat', 'Students over 18 are eligible to apply.'],
  ['empirical', 'empiris', 'The claim lacks empirical support.'], ['endorse', 'mendukung secara resmi', 'The union endorsed the proposal.'],
  ['entail', 'melibatkan / berakibat', 'The job entails frequent travel.'], ['equitable', 'adil', 'We need an equitable distribution of resources.'],
  ['explicit', 'eksplisit', 'The instructions were explicit.'], ['exploit', 'mengeksploitasi', 'Companies should not exploit workers.'],
  ['feasibility', 'kelayakan', 'We completed a feasibility study.'], ['fluctuate', 'berfluktuasi', 'Prices fluctuate with demand.'],
  ['foster', 'membina / menumbuhkan', 'Teachers should foster curiosity.'], ['hypothesis', 'hipotesis', 'The data support the hypothesis.'],
  ['illustrate', 'mengilustrasikan', 'This graph illustrates the trend.'], ['impose', 'memberlakukan', 'The government imposed new taxes.'],
  ['incentive', 'insentif', 'Tax incentives encourage investment.'], ['incidence', 'insiden / tingkat kejadian', 'The incidence of flu rose in winter.'],
  ['infrastructure', 'infrastruktur', 'The country invested in infrastructure.'], ['integrity', 'integritas', 'She is known for her integrity.'],
  ['interpret', 'menafsirkan', 'How do you interpret these results?'], ['intervene', 'turun tangan', 'The government had to intervene.'],
  ['legitimate', 'sah / beralasan', 'That is a legitimate concern.'], ['leverage', 'memanfaatkan', 'We can leverage our experience in Asia.'],
  ['mandatory', 'wajib', 'Attendance is mandatory.'], ['marginal', 'marginal / kecil', 'There was only a marginal improvement.'],
  ['mitigate', 'mengurangi dampak', 'Trees help mitigate flooding.'], ['modify', 'memodifikasi', 'We modified the design.'],
  ['notion', 'gagasan', 'The notion of fairness varies by culture.'], ['obscure', 'samar / tidak jelas', 'The reasons remain obscure.'],
  ['offset', 'mengimbangi', 'Higher prices offset the lower sales.'], ['paradox', 'paradoks', 'It is a paradox that more choice makes us less happy.'],
  ['perceive', 'memandang / mempersepsikan', 'Customers perceive the brand as reliable.'], ['phenomenon', 'fenomena', 'Remote work is a global phenomenon.'],
  ['pragmatic', 'pragmatis', 'We need a pragmatic solution.'], ['precede', 'mendahului', 'A short speech preceded the dinner.'],
  ['prerequisite', 'prasyarat', 'Basic maths is a prerequisite for this course.'], ['prevalent', 'lazim / meluas', 'Obesity is prevalent in cities.'],
  ['prospect', 'prospek', 'The job prospects are good.'], ['provision', 'ketentuan / penyediaan', 'The law includes a provision for refunds.'],
  ['radical', 'radikal', 'The plan requires radical change.'], ['rationale', 'dasar pemikiran', 'Explain the rationale behind your choice.'],
  ['refine', 'menyempurnakan', 'We refined the model after testing.'], ['reinforce', 'memperkuat', 'Practice reinforces learning.'],
  ['reluctant', 'enggan', 'He was reluctant to share his opinion.'], ['retain', 'mempertahankan', 'Companies struggle to retain staff.'],
  ['rigorous', 'ketat / cermat', 'The study used rigorous methods.'], ['scenario', 'skenario', 'In the worst scenario, we lose the contract.'],
  ['scope', 'cakupan', 'That question is beyond the scope of this report.'], ['simulate', 'menyimulasikan', 'The software simulates real traffic.'],
  ['skeptical', 'skeptis', 'Many experts remain skeptical.'], ['stakeholder', 'pemangku kepentingan', 'All stakeholders were consulted.'],
  ['stimulate', 'merangsang', 'Low interest rates stimulate spending.'], ['subsequent', 'berikutnya', 'Subsequent studies confirmed the result.'],
  ['subsidy', 'subsidi', 'Farmers receive a fuel subsidy.'], ['supplement', 'melengkapi / suplemen', 'Online videos supplement the lessons.'],
  ['sustain', 'mempertahankan', 'The company cannot sustain these losses.'], ['terminate', 'mengakhiri', 'The contract was terminated early.'],
  ['transparency', 'transparansi', 'Voters demand more transparency.'], ['trigger', 'memicu', 'The news triggered a debate.'],
  ['unprecedented', 'belum pernah terjadi', 'The pandemic caused unprecedented disruption.'], ['validate', 'memvalidasi', 'We need to validate these findings.'],
  ['viable', 'layak / dapat dijalankan', 'Is this business model viable?'], ['vulnerable', 'rentan', 'Children are vulnerable to online risks.'],
  ['whereas', 'sedangkan', 'Some prefer cities, whereas others like villages.'], ['hence', 'oleh sebab itu', 'The road was closed; hence the delay.'],
  ['albeit', 'meskipun', 'It was a success, albeit a small one.'], ['thereby', 'dengan demikian', 'They cut costs, thereby increasing profit.'],
  ['by and large', 'secara umum', 'By and large, the project went well.'], ['in light of', 'mengingat', 'In light of the data, we changed the plan.'],
  ['with regard to', 'berkenaan dengan', 'With regard to your request, we agree.'], ['shed light on', 'menjelaskan / menyingkap', 'The study sheds light on the causes.'],
  ['draw on', 'memanfaatkan', 'The author draws on her own experience.'], ['account for', 'menjelaskan / merupakan', 'Exports account for half of the income.'],
  ['give rise to', 'menimbulkan', 'The decision gave rise to protests.'], ['in the long run', 'dalam jangka panjang', 'In the long run, the investment pays off.'],
];

export const c2Extra: LexiconEntry[] = [
  ['aberration', 'penyimpangan', 'The poor result was an aberration.'], ['acquiesce', 'menyetujui dengan enggan', 'The board acquiesced to the demands.'],
  ['adamant', 'bersikeras', 'She was adamant that she was right.'], ['admonish', 'menegur', 'The judge admonished the lawyer.'],
  ['ameliorate', 'memperbaiki', 'New policies aim to ameliorate poverty.'], ['anomaly', 'anomali', 'The data show a strange anomaly.'],
  ['antithesis', 'antitesis', 'His style is the antithesis of mine.'], ['apprehensive', 'cemas', 'She felt apprehensive about the move.'],
  ['arduous', 'berat / sulit', 'It was an arduous journey.'], ['assiduous', 'tekun', 'He is an assiduous researcher.'],
  ['astute', 'cerdik', 'She made an astute observation.'], ['audacious', 'berani', 'It was an audacious plan.'],
  ['benevolent', 'murah hati', 'A benevolent donor funded the school.'], ['candid', 'terus terang', 'Thank you for your candid feedback.'],
  ['capricious', 'plin-plan', 'The weather here is capricious.'], ['circumvent', 'mengakali', 'They tried to circumvent the rules.'],
  ['cogent', 'kuat / meyakinkan', 'She presented a cogent argument.'], ['complacent', 'berpuas diri', 'Do not become complacent after success.'],
  ['conducive', 'kondusif', 'A quiet room is conducive to study.'], ['conjecture', 'dugaan', 'That is pure conjecture.'],
  ['connotation', 'konotasi', 'The word has a negative connotation.'], ['corroborate', 'menguatkan', 'Witnesses corroborated her story.'],
  ['culminate', 'memuncak', 'The talks culminated in an agreement.'], ['cursory', 'sepintas', 'He gave the report a cursory glance.'],
  ['debilitating', 'melemahkan', 'She suffers from a debilitating illness.'], ['delineate', 'menggambarkan batas', 'The report delineates each role.'],
  ['deleterious', 'merusak', 'Stress has deleterious effects on health.'], ['didactic', 'bersifat menggurui', 'The film is too didactic.'],
  ['disparity', 'kesenjangan', 'There is a huge disparity in income.'], ['disseminate', 'menyebarluaskan', 'The results were widely disseminated.'],
  ['eclectic', 'eklektik', 'She has an eclectic taste in music.'], ['efficacy', 'kemanjuran', 'The efficacy of the vaccine is high.'],
  ['egregious', 'mencolok (buruk)', 'It was an egregious error.'], ['elucidate', 'menjelaskan', 'Could you elucidate your theory?'],
  ['empathetic', 'empatik', 'A good nurse is empathetic.'], ['ephemeral', 'fana / sesaat', 'Social media fame is ephemeral.'],
  ['equivocal', 'mendua / tidak tegas', 'His answer was equivocal.'], ['erroneous', 'keliru', 'The article contains erroneous claims.'],
  ['esoteric', 'esoteris', 'The lecture was too esoteric for most students.'], ['exacerbation', 'perburukan', 'The drought led to an exacerbation of poverty.'],
  ['exemplary', 'teladan', 'Her work is exemplary.'], ['exonerate', 'membebaskan dari tuduhan', 'The evidence exonerated him.'],
  ['expedite', 'mempercepat', 'We need to expedite the process.'], ['extrapolate', 'mengekstrapolasi', 'We cannot extrapolate from one case.'],
  ['fallacy', 'kekeliruan logika', 'That argument rests on a fallacy.'], ['formidable', 'tangguh', 'She is a formidable opponent.'],
  ['galvanize', 'membangkitkan', 'The speech galvanized the crowd.'], ['gratuitous', 'tidak perlu / berlebihan', 'The film has gratuitous violence.'],
  ['hegemony', 'hegemoni', 'The empire maintained its hegemony for centuries.'], ['heterogeneous', 'heterogen', 'The class is highly heterogeneous.'],
  ['idiosyncratic', 'khas / unik', 'He has an idiosyncratic style.'], ['impetus', 'dorongan', 'The crisis gave impetus to reform.'],
  ['implicit', 'tersirat', 'There was an implicit agreement.'], ['incessant', 'tiada henti', 'The incessant noise kept me awake.'],
  ['incongruous', 'tidak serasi', 'The modern building looks incongruous here.'], ['indispensable', 'sangat diperlukan', 'Water is indispensable to life.'],
  ['ineffable', 'tak terlukiskan', 'The view was of ineffable beauty.'], ['innate', 'bawaan', 'Some talents seem innate.'],
  ['insidious', 'licik / diam-diam merusak', 'Misinformation has an insidious effect.'], ['intractable', 'sulit diatasi', 'It is an intractable problem.'],
  ['juxtapose', 'menyandingkan', 'The exhibition juxtaposes old and new art.'], ['lucid', 'jernih', 'She gave a lucid explanation.'],
  ['magnanimous', 'berjiwa besar', 'He was magnanimous in victory.'], ['mitigation', 'mitigasi', 'Flood mitigation is a priority.'],
  ['mundane', 'biasa / duniawi', 'He hates mundane tasks.'], ['nebulous', 'kabur / samar', 'The plan is still nebulous.'],
  ['nonchalant', 'acuh tak acuh', 'She seemed nonchalant about the result.'], ['obfuscate', 'mengaburkan', 'Jargon can obfuscate meaning.'],
  ['obsolete', 'usang', 'This technology is now obsolete.'], ['onerous', 'memberatkan', 'The rules are onerous for small firms.'],
  ['paramount', 'terpenting', 'Safety is paramount.'], ['pejorative', 'merendahkan', 'The term is often used in a pejorative sense.'],
  ['perfunctory', 'asal-asalan', 'He gave a perfunctory apology.'], ['pervasive', 'merasuk / meluas', 'Advertising is pervasive in modern life.'],
  ['pragmatism', 'pragmatisme', 'Her pragmatism helped the team.'], ['precarious', 'genting', 'The economy is in a precarious state.'],
  ['preclude', 'mencegah / menutup kemungkinan', 'The injury precluded him from playing.'], ['proliferation', 'penyebaran pesat', 'The proliferation of apps is remarkable.'],
  ['propensity', 'kecenderungan', 'He has a propensity for exaggeration.'], ['quintessential', 'paling khas', 'It is the quintessential Javanese dish.'],
  ['recalcitrant', 'membangkang', 'The recalcitrant student refused to work.'], ['reciprocal', 'timbal balik', 'The two countries signed a reciprocal agreement.'],
  ['relinquish', 'melepaskan', 'He refused to relinquish control.'], ['reprehensible', 'tercela', 'His behavior was reprehensible.'],
  ['rhetoric', 'retorika', 'The speech was full of empty rhetoric.'], ['salient', 'menonjol', 'Summarize the salient points.'],
  ['spurious', 'palsu / tidak sahih', 'The study found a spurious correlation.'], ['stringent', 'ketat', 'The lab follows stringent rules.'],
  ['succinct', 'singkat dan jelas', 'Please write a succinct summary.'], ['superfluous', 'berlebihan', 'Remove superfluous words.'],
  ['tacit', 'diam-diam disetujui', 'There was tacit approval from the board.'], ['tenuous', 'lemah / tipis', 'The link between the two is tenuous.'],
  ['tentative', 'sementara / ragu', 'We made a tentative plan.'], ['ubiquitous', 'ada di mana-mana', 'Smartphones are ubiquitous.'],
  ['unequivocal', 'tegas / tanpa ragu', 'Her answer was unequivocal.'], ['unwarranted', 'tidak beralasan', 'The criticism was unwarranted.'],
  ['vehement', 'keras / berapi-api', 'He was vehement in his opposition.'], ['vindicate', 'membuktikan benar', 'The results vindicated her approach.'],
  ['volatile', 'mudah bergejolak', 'The market is highly volatile.'], ['wane', 'memudar', 'Interest in the topic began to wane.'],
  ['zealous', 'bersemangat berlebihan', 'He is a zealous supporter of the team.'], ['epitome', 'lambang / contoh sempurna', 'She is the epitome of elegance.'],
  ['in lieu of', 'sebagai pengganti', 'He received shares in lieu of salary.'], ['by the same token', 'demikian pula', 'By the same token, we must cut costs.'],
  ['a fortiori', 'terlebih lagi', 'If adults find it hard, a fortiori children will.'], ['par excellence', 'yang paling unggul', 'She is the storyteller par excellence.'],
  ['moot point', 'hal yang tak relevan lagi', 'Whether we should have gone is now a moot point.'], ['pay lip service to', 'hanya di mulut saja', 'Many firms pay lip service to diversity.'],
  ['tip the balance', 'menentukan hasil', 'Price tipped the balance in our favor.'], ['beg the question', 'memunculkan pertanyaan', 'This begs the question of who will pay.'],
];
