import type { SentenceEntry } from './types';

// Translated sentences per CEFR level (reading/listening items for review,
// placement and mock exams).
export const englishSentences: Record<string, SentenceEntry[]> = {
  a1: [
    ['My name is Sari and I am from Bandung.', 'Nama saya Sari dan saya dari Bandung.'], ['I live with my parents and my sister.', 'Saya tinggal bersama orang tua dan saudara perempuan saya.'],
    ['I get up at six every morning.', 'Saya bangun jam enam setiap pagi.'], ['I have rice and eggs for breakfast.', 'Saya sarapan nasi dan telur.'],
    ['My school is near my house.', 'Sekolah saya dekat rumah saya.'], ['I go to work by bus.', 'Saya pergi bekerja naik bus.'],
    ['The shop opens at nine o’clock.', 'Toko itu buka jam sembilan.'], ['This bag is very heavy.', 'Tas ini sangat berat.'],
    ['Where is the bathroom, please?', 'Di mana kamar mandinya?'], ['How much is this shirt?', 'Berapa harga kemeja ini?'],
    ['I do not like cold weather.', 'Saya tidak suka cuaca dingin.'], ['It is hot and sunny today.', 'Hari ini panas dan cerah.'],
    ['My brother plays football on Sundays.', 'Kakak/adik laki-laki saya bermain sepak bola setiap Minggu.'], ['She can speak English and Indonesian.', 'Dia bisa berbahasa Inggris dan Indonesia.'],
    ['We watch TV after dinner.', 'Kami menonton TV setelah makan malam.'], ['The cat is sleeping on the bed.', 'Kucing sedang tidur di atas tempat tidur.'],
    ['I am hungry. Let us eat now.', 'Saya lapar. Ayo makan sekarang.'], ['Can you help me, please?', 'Bisakah kamu membantu saya?'],
    ['There is a park next to the school.', 'Ada taman di sebelah sekolah.'], ['There are three chairs in my room.', 'Ada tiga kursi di kamar saya.'],
    ['My father is a teacher.', 'Ayah saya seorang guru.'], ['Her mother works in a hospital.', 'Ibunya bekerja di rumah sakit.'],
    ['I drink water every day.', 'Saya minum air setiap hari.'], ['The train is late today.', 'Keretanya terlambat hari ini.'],
    ['What time is it now?', 'Jam berapa sekarang?'], ['It is half past seven.', 'Sekarang jam setengah delapan.'],
    ['I am reading a book now.', 'Saya sedang membaca buku sekarang.'], ['They are playing in the garden.', 'Mereka sedang bermain di kebun.'],
    ['Yesterday I visited my grandmother.', 'Kemarin saya mengunjungi nenek saya.'], ['We went to the beach last Sunday.', 'Kami pergi ke pantai hari Minggu lalu.'],
    ['I am going to study tonight.', 'Saya akan belajar malam ini.'], ['My birthday is in May.', 'Ulang tahun saya di bulan Mei.'],
    ['This is my friend, Dimas.', 'Ini teman saya, Dimas.'], ['Nice to meet you!', 'Senang bertemu denganmu!'],
    ['See you tomorrow.', 'Sampai jumpa besok.'], ['Please close the window.', 'Tolong tutup jendelanya.'],
    ['Do you have a pen?', 'Apakah kamu punya pulpen?'], ['I have two cats and a dog.', 'Saya punya dua kucing dan seekor anjing.'],
    ['The coffee is too hot.', 'Kopinya terlalu panas.'], ['I like apples and bananas.', 'Saya suka apel dan pisang.'],
    ['My phone is on the table.', 'Ponsel saya ada di atas meja.'], ['The market is very busy today.', 'Pasar sangat ramai hari ini.'],
    ['He is tall and friendly.', 'Dia tinggi dan ramah.'], ['I am tired after work.', 'Saya lelah setelah bekerja.'],
    ['We have English class on Monday.', 'Kami ada kelas bahasa Inggris hari Senin.'], ['Turn left at the bank.', 'Belok kiri di bank.'],
    ['I want a cup of tea, please.', 'Saya mau secangkir teh.'], ['The bus stop is over there.', 'Halte bus ada di sana.'],
    ['My sister is ten years old.', 'Adik perempuan saya berumur sepuluh tahun.'], ['I usually walk to school.', 'Saya biasanya berjalan kaki ke sekolah.'],
    ['I never eat breakfast late.', 'Saya tidak pernah sarapan terlambat.'], ['The weather is bad today.', 'Cuaca buruk hari ini.'],
    ['Can I sit here?', 'Boleh saya duduk di sini?'], ['I do not understand. Can you repeat?', 'Saya tidak mengerti. Bisa diulang?'],
    ['We eat dinner at seven.', 'Kami makan malam jam tujuh.'], ['The library is quiet.', 'Perpustakaannya tenang.'],
    ['I am sick, so I stay at home.', 'Saya sakit, jadi saya tinggal di rumah.'], ['Wash your hands before lunch.', 'Cuci tanganmu sebelum makan siang.'],
    ['My favorite color is blue.', 'Warna favorit saya biru.'], ['Thank you very much!', 'Terima kasih banyak!'],
  ],
  a2: [
    ['I usually go shopping on Saturday morning.', 'Saya biasanya berbelanja hari Sabtu pagi.'], ['Last weekend we visited a small village near the mountains.', 'Akhir pekan lalu kami mengunjungi desa kecil dekat pegunungan.'],
    ['The hotel was cheap, but the room was clean.', 'Hotelnya murah, tetapi kamarnya bersih.'], ['I have never been to Japan.', 'Saya belum pernah ke Jepang.'],
    ['Have you finished your homework yet?', 'Apakah kamu sudah menyelesaikan PR-mu?'], ['I am going to learn to drive next year.', 'Saya akan belajar menyetir tahun depan.'],
    ['The train was delayed because of the rain.', 'Keretanya terlambat karena hujan.'], ['Could you tell me the way to the station?', 'Bisakah Anda memberi tahu jalan ke stasiun?'],
    ['Go straight and turn right at the traffic lights.', 'Jalan lurus dan belok kanan di lampu lalu lintas.'], ['This jacket is more expensive than that one.', 'Jaket ini lebih mahal dari yang itu.'],
    ['It is the best restaurant in town.', 'Itu restoran terbaik di kota.'], ['I would like to book a table for two.', 'Saya ingin memesan meja untuk dua orang.'],
    ['Can I pay by card?', 'Bisakah saya membayar dengan kartu?'], ['I bought these shoes online last week.', 'Saya membeli sepatu ini secara daring minggu lalu.'],
    ['She was cooking when I arrived.', 'Dia sedang memasak ketika saya tiba.'], ['We should leave early to avoid traffic.', 'Kita sebaiknya berangkat lebih awal untuk menghindari macet.'],
    ['You must wear a helmet on a motorbike.', 'Kamu harus memakai helm saat naik motor.'], ['I have a headache, so I am going to rest.', 'Saya sakit kepala, jadi saya akan beristirahat.'],
    ['The doctor told me to drink more water.', 'Dokter menyuruh saya minum lebih banyak air.'], ['My cousin is getting married in June.', 'Sepupu saya akan menikah di bulan Juni.'],
    ['We celebrated my grandmother’s birthday at home.', 'Kami merayakan ulang tahun nenek di rumah.'], ['I have lived in this city for three years.', 'Saya sudah tinggal di kota ini selama tiga tahun.'],
    ['The museum is closed on Mondays.', 'Museumnya tutup setiap Senin.'], ['Do not forget to bring your passport.', 'Jangan lupa membawa paspormu.'],
    ['My flight leaves at ten in the morning.', 'Penerbangan saya berangkat jam sepuluh pagi.'], ['I lost my keys yesterday, but I found them later.', 'Saya kehilangan kunci kemarin, tetapi saya menemukannya nanti.'],
    ['He is good at playing the guitar.', 'Dia pandai bermain gitar.'], ['I am interested in photography.', 'Saya tertarik pada fotografi.'],
    ['What do you usually do in your free time?', 'Apa yang biasanya kamu lakukan di waktu luang?'], ['I enjoy walking in the park after work.', 'Saya senang berjalan di taman setelah bekerja.'],
    ['It was raining, so we stayed inside.', 'Sedang hujan, jadi kami tetap di dalam.'], ['The weather will be cloudy tomorrow.', 'Cuaca besok akan berawan.'],
    ['I need to buy a present for my friend.', 'Saya perlu membeli hadiah untuk teman saya.'], ['Is there a pharmacy near here?', 'Apakah ada apotek di dekat sini?'],
    ['My office is on the fifth floor.', 'Kantor saya di lantai lima.'], ['I have a meeting with my boss at two.', 'Saya ada rapat dengan atasan jam dua.'],
    ['She works as a nurse in a big hospital.', 'Dia bekerja sebagai perawat di rumah sakit besar.'], ['I made a mistake in the test.', 'Saya membuat kesalahan dalam ujian.'],
    ['Could you speak more slowly, please?', 'Bisakah Anda berbicara lebih pelan?'], ['I agree with you, but it is too expensive.', 'Saya setuju denganmu, tetapi terlalu mahal.'],
    ['How long does it take to get there?', 'Berapa lama waktu yang dibutuhkan untuk sampai ke sana?'], ['It takes about thirty minutes by car.', 'Sekitar tiga puluh menit dengan mobil.'],
    ['The concert was amazing and very loud.', 'Konsernya luar biasa dan sangat keras.'], ['Our team won the match yesterday.', 'Tim kami memenangkan pertandingan kemarin.'],
    ['I exercise three times a week.', 'Saya berolahraga tiga kali seminggu.'], ['Fruit and vegetables are healthy.', 'Buah dan sayur itu sehat.'],
    ['The streets are crowded during the holiday.', 'Jalanan ramai selama liburan.'], ['I was surprised by the good news.', 'Saya terkejut dengan kabar baik itu.'],
    ['Please send me the address by message.', 'Tolong kirimkan alamatnya lewat pesan.'], ['I forgot my password again.', 'Saya lupa kata sandi saya lagi.'],
    ['We rented a car for the trip.', 'Kami menyewa mobil untuk perjalanan itu.'], ['The island is famous for its beaches.', 'Pulau itu terkenal dengan pantainya.'],
    ['I was nervous before the interview.', 'Saya gugup sebelum wawancara.'], ['My neighbor helped me carry the boxes.', 'Tetangga saya membantu membawa kotak-kotak itu.'],
    ['The soup is too spicy for me.', 'Supnya terlalu pedas untuk saya.'], ['What size are these trousers?', 'Ukuran berapa celana ini?'],
    ['I prefer tea to coffee.', 'Saya lebih suka teh daripada kopi.'], ['We are planning a trip to Lombok.', 'Kami sedang merencanakan perjalanan ke Lombok.'],
    ['The library opens at eight and closes at five.', 'Perpustakaan buka jam delapan dan tutup jam lima.'], ['I hope you feel better soon.', 'Semoga kamu cepat merasa lebih baik.'],
  ],
  b1: [
    ['In my opinion, public transport should be cheaper.', 'Menurut saya, transportasi umum seharusnya lebih murah.'], ['If it rains tomorrow, we will cancel the picnic.', 'Jika besok hujan, kami akan membatalkan piknik.'],
    ['I have been learning English for two years.', 'Saya sudah belajar bahasa Inggris selama dua tahun.'], ['The meeting was postponed because the manager was ill.', 'Rapat ditunda karena manajernya sakit.'],
    ['Although the hotel was old, the service was excellent.', 'Meskipun hotelnya tua, layanannya sangat baik.'], ['She suggested that we take a taxi.', 'Dia menyarankan agar kami naik taksi.'],
    ['I would rather stay at home than go out tonight.', 'Saya lebih suka di rumah daripada keluar malam ini.'], ['The new app helps users manage their time.', 'Aplikasi baru itu membantu pengguna mengatur waktu mereka.'],
    ['Many young people move to cities to find jobs.', 'Banyak anak muda pindah ke kota untuk mencari pekerjaan.'], ['We need to reduce the amount of plastic we use.', 'Kita perlu mengurangi jumlah plastik yang kita gunakan.'],
    ['The book was so interesting that I finished it in a day.', 'Bukunya begitu menarik sehingga saya menyelesaikannya dalam sehari.'], ['I am used to getting up early.', 'Saya sudah terbiasa bangun pagi.'],
    ['He told me that he would call later.', 'Dia bilang dia akan menelepon nanti.'], ['The results were better than we expected.', 'Hasilnya lebih baik dari yang kami harapkan.'],
    ['Could you explain why the order was late?', 'Bisakah Anda menjelaskan mengapa pesanannya terlambat?'], ['I apologize for the inconvenience.', 'Saya mohon maaf atas ketidaknyamanannya.'],
    ['The museum, which opened last year, is very popular.', 'Museum itu, yang dibuka tahun lalu, sangat populer.'], ['People who exercise regularly usually sleep better.', 'Orang yang rutin berolahraga biasanya tidur lebih nyenyak.'],
    ['It is important to check information before sharing it.', 'Penting untuk memeriksa informasi sebelum membagikannya.'], ['I am thinking about changing my job.', 'Saya sedang memikirkan untuk berganti pekerjaan.'],
    ['The price includes breakfast and airport transfer.', 'Harganya termasuk sarapan dan antar-jemput bandara.'], ['You should have told me earlier.', 'Seharusnya kamu memberi tahu saya lebih awal.'],
    ['I was walking home when it started to rain.', 'Saya sedang berjalan pulang ketika mulai hujan.'], ['The company has decided to hire more staff.', 'Perusahaan telah memutuskan untuk merekrut lebih banyak staf.'],
    ['Online shopping is convenient, but it can be risky.', 'Belanja daring praktis, tetapi bisa berisiko.'], ['She has lived abroad since 2019.', 'Dia tinggal di luar negeri sejak 2019.'],
    ['I prefer working in a team rather than alone.', 'Saya lebih suka bekerja dalam tim daripada sendirian.'], ['The festival attracts thousands of visitors every year.', 'Festival itu menarik ribuan pengunjung setiap tahun.'],
    ['If I had more time, I would learn another language.', 'Jika saya punya lebih banyak waktu, saya akan belajar bahasa lain.'], ['The teacher encouraged us to ask questions.', 'Guru mendorong kami untuk bertanya.'],
    ['It took me a long time to get used to the food.', 'Butuh waktu lama bagi saya untuk terbiasa dengan makanannya.'], ['Smartphones have changed the way we communicate.', 'Ponsel pintar telah mengubah cara kita berkomunikasi.'],
    ['I would like to complain about the noise.', 'Saya ingin mengeluhkan kebisingan itu.'], ['The bridge was built in the nineteenth century.', 'Jembatan itu dibangun pada abad kesembilan belas.'],
    ['Visitors are not allowed to take photos inside.', 'Pengunjung tidak diizinkan mengambil foto di dalam.'], ['He managed to finish the project on time.', 'Dia berhasil menyelesaikan proyek tepat waktu.'],
    ['I am looking forward to hearing from you.', 'Saya menantikan kabar darimu.'], ['The more you practise, the more confident you become.', 'Semakin banyak berlatih, semakin percaya diri kamu.'],
    ['Instead of driving, I cycle to work.', 'Alih-alih menyetir, saya bersepeda ke kantor.'], ['There is a good chance that prices will rise.', 'Kemungkinan besar harga akan naik.'],
    ['We discussed the advantages and disadvantages of the plan.', 'Kami membahas kelebihan dan kekurangan rencana itu.'], ['The flight was cancelled due to bad weather.', 'Penerbangan dibatalkan karena cuaca buruk.'],
    ['I realized that I had left my wallet at home.', 'Saya sadar bahwa saya meninggalkan dompet di rumah.'], ['Most of my friends prefer streaming to watching TV.', 'Sebagian besar teman saya lebih suka streaming daripada menonton TV.'],
    ['Volunteers helped clean the beach after the storm.', 'Para relawan membantu membersihkan pantai setelah badai.'], ['I cannot decide which course to choose.', 'Saya tidak bisa memutuskan kursus mana yang akan dipilih.'],
    ['The report shows that pollution has increased.', 'Laporan menunjukkan bahwa polusi meningkat.'], ['She is responsible for training new employees.', 'Dia bertanggung jawab melatih karyawan baru.'],
    ['I wish I had studied harder at school.', 'Saya berharap dulu belajar lebih giat di sekolah.'], ['Traditional markets are still popular in many towns.', 'Pasar tradisional masih populer di banyak kota.'],
    ['You will get a discount if you book early.', 'Kamu akan mendapat diskon jika memesan lebih awal.'], ['The film was based on a true story.', 'Film itu berdasarkan kisah nyata.'],
    ['I prefer to read the news on paper.', 'Saya lebih suka membaca berita di kertas.'], ['He has been working here since he graduated.', 'Dia sudah bekerja di sini sejak lulus.'],
    ['It is worth visiting the old town.', 'Kota tua itu layak dikunjungi.'], ['We ran out of time, so we skipped the last question.', 'Waktu kami habis, jadi kami melewatkan soal terakhir.'],
    ['Good sleep is essential for concentration.', 'Tidur yang baik penting untuk konsentrasi.'], ['I did not expect the exam to be so easy.', 'Saya tidak menyangka ujiannya semudah itu.'],
    ['The government plans to build more schools.', 'Pemerintah berencana membangun lebih banyak sekolah.'], ['Let me know if you need any help.', 'Beri tahu saya jika kamu butuh bantuan.'],
  ],
  b2: [
    ['Despite the heavy traffic, we arrived on time.', 'Meskipun lalu lintas padat, kami tiba tepat waktu.'], ['The company is likely to expand into new markets.', 'Perusahaan kemungkinan besar akan berekspansi ke pasar baru.'],
    ['Had I known about the delay, I would have taken a later train.', 'Seandainya saya tahu tentang keterlambatan itu, saya akan naik kereta berikutnya.'], ['Remote work has become the norm in many industries.', 'Kerja jarak jauh telah menjadi hal biasa di banyak industri.'],
    ['The research highlights the importance of early education.', 'Penelitian itu menyoroti pentingnya pendidikan usia dini.'], ['We need to take long-term consequences into account.', 'Kita perlu memperhitungkan konsekuensi jangka panjang.'],
    ['Not only did she win the competition, but she also broke the record.', 'Dia tidak hanya memenangkan lomba, tetapi juga memecahkan rekor.'], ['The policy was introduced to reduce air pollution.', 'Kebijakan itu diperkenalkan untuk mengurangi polusi udara.'],
    ['It is widely believed that exercise improves mental health.', 'Secara luas diyakini bahwa olahraga meningkatkan kesehatan mental.'], ['The new system is more efficient, whereas the old one was slow.', 'Sistem baru lebih efisien, sedangkan yang lama lambat.'],
    ['He is used to dealing with difficult customers.', 'Dia terbiasa menangani pelanggan yang sulit.'], ['Rising housing costs have forced many families to move.', 'Naiknya biaya perumahan memaksa banyak keluarga pindah.'],
    ['The article raises important questions about privacy.', 'Artikel itu memunculkan pertanyaan penting tentang privasi.'], ['I would appreciate it if you could reply by Friday.', 'Saya akan sangat berterima kasih jika Anda bisa membalas paling lambat Jumat.'],
    ['The team came up with an innovative solution.', 'Tim itu mencetuskan solusi yang inovatif.'], ['There has been a significant increase in online sales.', 'Terjadi peningkatan signifikan dalam penjualan daring.'],
    ['The project was completed ahead of schedule.', 'Proyek itu selesai lebih cepat dari jadwal.'], ['She argued that the plan was not financially viable.', 'Dia berpendapat bahwa rencana itu tidak layak secara finansial.'],
    ['Tourism brings benefits, but it also puts pressure on local resources.', 'Pariwisata membawa manfaat, tetapi juga menekan sumber daya lokal.'], ['The data suggest a clear link between diet and health.', 'Data menunjukkan hubungan jelas antara pola makan dan kesehatan.'],
    ['I am not in favor of banning cars from the city centre.', 'Saya tidak setuju melarang mobil di pusat kota.'], ['Students are expected to submit their work on time.', 'Mahasiswa diharapkan mengumpulkan tugas tepat waktu.'],
    ['The manager pointed out several mistakes in the report.', 'Manajer menunjukkan beberapa kesalahan dalam laporan.'], ['Social media can spread misinformation very quickly.', 'Media sosial dapat menyebarkan disinformasi dengan sangat cepat.'],
    ['If the government had acted sooner, the crisis could have been avoided.', 'Jika pemerintah bertindak lebih cepat, krisis itu bisa dihindari.'], ['The new law will come into effect next month.', 'Undang-undang baru akan berlaku bulan depan.'],
    ['On the other hand, electric cars are still expensive.', 'Di sisi lain, mobil listrik masih mahal.'], ['Several factors contributed to the company’s success.', 'Beberapa faktor berkontribusi pada kesuksesan perusahaan itu.'],
    ['It is essential that everyone follows the safety rules.', 'Sangat penting bahwa semua orang mengikuti aturan keselamatan.'], ['The survey was conducted among five hundred students.', 'Survei itu dilakukan terhadap lima ratus mahasiswa.'],
    ['She has a flexible approach to solving problems.', 'Dia punya pendekatan fleksibel dalam menyelesaikan masalah.'], ['The festival has been postponed until further notice.', 'Festival ditunda sampai pemberitahuan lebih lanjut.'],
    ['Many experts believe that automation will change the job market.', 'Banyak pakar percaya bahwa otomatisasi akan mengubah pasar kerja.'], ['We should focus on quality rather than quantity.', 'Kita sebaiknya fokus pada kualitas daripada kuantitas.'],
    ['The museum is well worth a visit, especially for history lovers.', 'Museum itu sangat layak dikunjungi, terutama bagi pencinta sejarah.'], ['He apologized for not having replied sooner.', 'Dia meminta maaf karena tidak membalas lebih cepat.'],
    ['Access to clean water remains a challenge in some regions.', 'Akses air bersih masih menjadi tantangan di beberapa wilayah.'], ['The more we rely on technology, the more vulnerable we become.', 'Semakin kita bergantung pada teknologi, semakin rentan kita.'],
    ['Her presentation was clear, concise and persuasive.', 'Presentasinya jelas, ringkas, dan meyakinkan.'], ['We were asked to evaluate the effectiveness of the program.', 'Kami diminta menilai efektivitas program itu.'],
    ['Public opinion on the issue is deeply divided.', 'Opini publik tentang isu itu sangat terbelah.'], ['Unless we reduce emissions, temperatures will keep rising.', 'Kecuali kita mengurangi emisi, suhu akan terus naik.'],
    ['The company offers a wide range of services.', 'Perusahaan itu menawarkan berbagai layanan.'], ['I have been meaning to call you for weeks.', 'Sudah berminggu-minggu saya ingin meneleponmu.'],
    ['Critics claim that the reform benefits only the rich.', 'Para kritikus mengklaim reformasi itu hanya menguntungkan orang kaya.'], ['The findings are consistent with previous studies.', 'Temuan itu konsisten dengan penelitian sebelumnya.'],
    ['Working part-time allowed her to gain valuable experience.', 'Bekerja paruh waktu memungkinkannya mendapat pengalaman berharga.'], ['It remains to be seen whether the plan will work.', 'Masih harus dilihat apakah rencana itu akan berhasil.'],
    ['Customers expect fast and reliable delivery.', 'Pelanggan mengharapkan pengiriman yang cepat dan andal.'], ['The city has invested heavily in public transport.', 'Kota itu banyak berinvestasi di transportasi umum.'],
    ['She managed to strike a balance between work and family.', 'Dia berhasil menyeimbangkan pekerjaan dan keluarga.'], ['The lecture focused on the causes of the economic crisis.', 'Kuliah itu berfokus pada penyebab krisis ekonomi.'],
    ['Many workers are concerned about job security.', 'Banyak pekerja khawatir tentang keamanan pekerjaan.'], ['It is often argued that competition drives innovation.', 'Sering dikemukakan bahwa persaingan mendorong inovasi.'],
    ['The hotel was fully booked, so we had to look elsewhere.', 'Hotelnya penuh, jadi kami harus mencari tempat lain.'], ['To some extent, I agree with the author’s view.', 'Sampai batas tertentu, saya setuju dengan pandangan penulis.'],
    ['Local farmers have struggled to compete with imports.', 'Petani lokal kesulitan bersaing dengan produk impor.'], ['The government should provide more support for small businesses.', 'Pemerintah seharusnya memberi lebih banyak dukungan bagi usaha kecil.'],
    ['Overall, the benefits outweigh the drawbacks.', 'Secara keseluruhan, manfaatnya lebih besar daripada kekurangannya.'], ['We should have booked the tickets in advance.', 'Seharusnya kita memesan tiket lebih awal.'],
  ],
  c1: [
    ['The findings shed light on the causes of youth unemployment.', 'Temuan itu menyingkap penyebab pengangguran kaum muda.'], ['Arguably, the policy has done more harm than good.', 'Bisa dibilang, kebijakan itu lebih banyak merugikan daripada menguntungkan.'],
    ['Only after the report was published did the public react.', 'Baru setelah laporan diterbitkan publik bereaksi.'], ['The initiative aims to foster collaboration between universities and industry.', 'Inisiatif itu bertujuan menumbuhkan kolaborasi antara universitas dan industri.'],
    ['There is a growing consensus that the current system is unsustainable.', 'Semakin banyak kesepakatan bahwa sistem saat ini tidak berkelanjutan.'], ['The author makes a compelling case for stricter regulation.', 'Penulis memberikan argumen meyakinkan untuk regulasi yang lebih ketat.'],
    ['In light of recent events, the conference has been cancelled.', 'Mengingat peristiwa terkini, konferensi dibatalkan.'], ['The two studies appear to contradict each other.', 'Kedua penelitian itu tampaknya saling bertentangan.'],
    ['Measures were taken to mitigate the impact of the floods.', 'Langkah-langkah diambil untuk mengurangi dampak banjir.'], ['Were the government to raise taxes, consumption would fall.', 'Seandainya pemerintah menaikkan pajak, konsumsi akan turun.'],
    ['The proposal was met with considerable skepticism.', 'Usulan itu disambut dengan skeptisisme yang cukup besar.'], ['His argument rests on a number of questionable assumptions.', 'Argumennya bertumpu pada sejumlah asumsi yang patut dipertanyakan.'],
    ['The company has been criticized for its lack of transparency.', 'Perusahaan itu dikritik karena kurangnya transparansi.'], ['It is essential to distinguish between correlation and causation.', 'Penting untuk membedakan korelasi dan kausalitas.'],
    ['The reforms were implemented with remarkable speed.', 'Reformasi itu diterapkan dengan kecepatan luar biasa.'], ['She articulated her concerns with great clarity.', 'Dia mengungkapkan kekhawatirannya dengan sangat jelas.'],
    ['The benefits, albeit modest, are nonetheless significant.', 'Manfaatnya, meskipun kecil, tetap signifikan.'], ['Stakeholders were consulted at every stage of the project.', 'Para pemangku kepentingan diajak berkonsultasi di setiap tahap proyek.'],
    ['The data should be interpreted with caution.', 'Data itu harus ditafsirkan dengan hati-hati.'], ['Rarely has a single invention had such a profound impact.', 'Jarang ada satu penemuan yang berdampak sedalam itu.'],
    ['The book offers valuable insight into rural life.', 'Buku itu memberikan wawasan berharga tentang kehidupan pedesaan.'], ['Critics argue that the scheme is neither fair nor efficient.', 'Para kritikus berpendapat skema itu tidak adil maupun efisien.'],
    ['The committee is expected to reach a decision by the end of the month.', 'Komite diharapkan mengambil keputusan paling lambat akhir bulan.'], ['Economic growth has not translated into higher wages.', 'Pertumbuhan ekonomi belum berujung pada upah yang lebih tinggi.'],
    ['The study draws on interviews with over two hundred teachers.', 'Penelitian itu memanfaatkan wawancara dengan lebih dari dua ratus guru.'], ['Such measures are unlikely to address the root causes of poverty.', 'Langkah semacam itu kecil kemungkinan menyentuh akar kemiskinan.'],
    ['The museum has undergone extensive renovation.', 'Museum itu telah menjalani renovasi besar-besaran.'], ['She was reluctant to commit to a long-term contract.', 'Dia enggan terikat kontrak jangka panjang.'],
    ['The notion that success depends solely on talent is misleading.', 'Gagasan bahwa kesuksesan semata-mata bergantung pada bakat itu menyesatkan.'], ['The new regulations impose strict limits on emissions.', 'Peraturan baru memberlakukan batas emisi yang ketat.'],
    ['Public trust in institutions has steadily declined.', 'Kepercayaan publik terhadap lembaga terus menurun.'], ['The results were consistent across all age groups.', 'Hasilnya konsisten di semua kelompok usia.'],
    ['The speaker anticipated several objections to her argument.', 'Pembicara mengantisipasi beberapa keberatan terhadap argumennya.'], ['Access to education is a prerequisite for social mobility.', 'Akses pendidikan adalah prasyarat bagi mobilitas sosial.'],
    ['The article provides a comprehensive overview of the debate.', 'Artikel itu memberikan tinjauan menyeluruh tentang perdebatan tersebut.'], ['Had the warning been heeded, the disaster might have been prevented.', 'Seandainya peringatan diindahkan, bencana itu mungkin bisa dicegah.'],
    ['The project was abandoned owing to a lack of funding.', 'Proyek itu ditinggalkan karena kekurangan dana.'], ['Opinions on the matter remain sharply divided.', 'Pendapat tentang hal itu tetap terbelah tajam.'],
    ['The firm’s reputation was undermined by a series of scandals.', 'Reputasi perusahaan itu dilemahkan oleh serangkaian skandal.'], ['Innovation often emerges from unexpected collaborations.', 'Inovasi sering muncul dari kolaborasi yang tak terduga.'],
    ['The survey reveals a marked shift in consumer behavior.', 'Survei itu mengungkap pergeseran nyata dalam perilaku konsumen.'], ['We must weigh the short-term costs against the long-term gains.', 'Kita harus menimbang biaya jangka pendek dengan keuntungan jangka panjang.'],
    ['The novel explores themes of identity and belonging.', 'Novel itu menjelajahi tema identitas dan rasa memiliki.'], ['It could be argued that the media shapes rather than reflects opinion.', 'Dapat dikatakan bahwa media membentuk alih-alih mencerminkan opini.'],
    ['The government has pledged to increase spending on health.', 'Pemerintah berjanji meningkatkan belanja kesehatan.'], ['These figures should not be taken at face value.', 'Angka-angka ini tidak boleh diterima begitu saja.'],
    ['The initiative has had a marginal effect on unemployment.', 'Inisiatif itu berdampak kecil terhadap pengangguran.'], ['The conclusions are based on rigorous analysis.', 'Kesimpulannya didasarkan pada analisis yang cermat.'],
    ['Local communities must be involved in decision-making.', 'Komunitas lokal harus dilibatkan dalam pengambilan keputusan.'], ['The phenomenon is by no means limited to large cities.', 'Fenomena itu sama sekali tidak terbatas pada kota besar.'],
    ['She has a remarkable ability to simplify complex ideas.', 'Dia punya kemampuan luar biasa menyederhanakan gagasan rumit.'], ['The report calls for greater accountability in public spending.', 'Laporan itu menyerukan akuntabilitas yang lebih besar dalam belanja publik.'],
    ['Few would dispute the need for reform.', 'Hanya sedikit yang membantah perlunya reformasi.'], ['The benefits of the scheme are yet to materialize.', 'Manfaat skema itu belum terwujud.'],
    ['The debate has been dominated by a handful of voices.', 'Perdebatan itu didominasi oleh segelintir suara.'], ['Such an approach entails considerable risk.', 'Pendekatan semacam itu mengandung risiko yang cukup besar.'],
    ['In the long run, investing in education pays off.', 'Dalam jangka panjang, investasi dalam pendidikan membuahkan hasil.'], ['The author’s tone is subtly ironic.', 'Nada penulis itu ironis secara halus.'],
    ['The policy disproportionately affects low-income households.', 'Kebijakan itu berdampak tidak proporsional pada rumah tangga berpenghasilan rendah.'], ['Ultimately, the success of the plan depends on public support.', 'Pada akhirnya, keberhasilan rencana itu bergantung pada dukungan publik.'],
  ],
  c2: [
    ['The argument, though superficially persuasive, collapses under scrutiny.', 'Argumen itu, meski tampak meyakinkan, runtuh ketika diperiksa dengan cermat.'], ['Seldom has a policy been so universally derided.', 'Jarang sekali sebuah kebijakan dicemooh secara begitu luas.'],
    ['The novel’s ambiguity is precisely what makes it compelling.', 'Ambiguitas novel itu justru yang membuatnya memikat.'], ['His meticulous attention to detail borders on obsession.', 'Perhatiannya yang teliti terhadap detail nyaris seperti obsesi.'],
    ['The reforms, ostensibly aimed at efficiency, served mainly to centralize power.', 'Reformasi itu, yang katanya untuk efisiensi, terutama berfungsi memusatkan kekuasaan.'], ['To reconcile these competing interests is no mean feat.', 'Mendamaikan kepentingan-kepentingan yang bersaing ini bukan perkara mudah.'],
    ['The evidence, such as it is, hardly substantiates the claim.', 'Bukti yang ada, sejauh itu, hampir tidak menguatkan klaim tersebut.'], ['Her prose is at once lucid and deeply evocative.', 'Prosanya sekaligus jernih dan sangat menggugah.'],
    ['The crisis exposed the precarious nature of the global supply chain.', 'Krisis itu menyingkap rapuhnya rantai pasok global.'], ['Notwithstanding its flaws, the study marks a significant advance.', 'Terlepas dari kelemahannya, penelitian itu menandai kemajuan penting.'],
    ['The term has acquired a pejorative connotation over time.', 'Istilah itu seiring waktu memperoleh konotasi merendahkan.'], ['Were it not for her intervention, the talks would have collapsed.', 'Kalau bukan karena campur tangannya, perundingan itu akan gagal.'],
    ['The distinction may seem pedantic, but it is crucial.', 'Perbedaan itu mungkin tampak remeh, tetapi sangat penting.'], ['Such rhetoric does little to dispel public anxiety.', 'Retorika semacam itu hampir tidak meredakan kecemasan publik.'],
    ['The findings cast doubt on long-held assumptions.', 'Temuan itu meragukan asumsi yang lama dipegang.'], ['The minister’s remarks exacerbated an already tense situation.', 'Pernyataan menteri itu memperburuk situasi yang sudah tegang.'],
    ['His explanation, while plausible, remains unproven.', 'Penjelasannya, meski masuk akal, tetap belum terbukti.'], ['The paradigm shift was neither sudden nor inevitable.', 'Pergeseran paradigma itu tidak tiba-tiba maupun tak terelakkan.'],
    ['What the report omits is as telling as what it includes.', 'Apa yang dihilangkan laporan itu sama bermaknanya dengan apa yang dicantumkan.'], ['The discrepancy between the two accounts is striking.', 'Kesenjangan antara kedua keterangan itu mencolok.'],
    ['Invariably, the most vulnerable bear the brunt of austerity.', 'Selalu saja, kelompok paling rentan yang menanggung beban penghematan.'], ['The exhibition juxtaposes colonial and contemporary art.', 'Pameran itu menyandingkan seni kolonial dan kontemporer.'],
    ['Her rebuttal was as succinct as it was devastating.', 'Bantahannya sama ringkasnya dengan telaknya.'], ['The committee’s tacit approval emboldened the developers.', 'Persetujuan diam-diam komite membuat para pengembang semakin berani.'],
    ['The link between the two events is tenuous at best.', 'Kaitan antara kedua peristiwa itu paling-paling sangat lemah.'], ['The author deftly weaves personal memoir with social history.', 'Penulis dengan cekatan menjalin memoar pribadi dengan sejarah sosial.'],
    ['It would be disingenuous to deny the scheme’s shortcomings.', 'Tidak jujur jika menyangkal kekurangan skema itu.'], ['The ubiquity of screens has reshaped childhood.', 'Hadirnya layar di mana-mana telah mengubah masa kanak-kanak.'],
    ['The treaty was hailed as a triumph of pragmatic diplomacy.', 'Perjanjian itu dipuji sebagai kemenangan diplomasi pragmatis.'], ['The theory, elegant as it is, fails to account for the anomalies.', 'Teori itu, seanggun apa pun, gagal menjelaskan anomali-anomalinya.'],
    ['Conversely, a decline in demand could trigger a recession.', 'Sebaliknya, penurunan permintaan bisa memicu resesi.'], ['The rationale behind the decision was never made explicit.', 'Dasar pemikiran di balik keputusan itu tidak pernah dijelaskan secara eksplisit.'],
    ['Intrinsically, the problem is one of trust rather than technology.', 'Pada hakikatnya, masalahnya adalah soal kepercayaan, bukan teknologi.'], ['She dismissed the criticism as unwarranted and ill-informed.', 'Dia menepis kritik itu sebagai tidak beralasan dan kurang informasi.'],
    ['The sheer scale of the project was daunting.', 'Skala proyek itu sungguh menciutkan nyali.'], ['The decline of the industry was a slow, insidious process.', 'Kemunduran industri itu adalah proses lambat yang diam-diam merusak.'],
    ['Any attempt to quantify happiness is inherently reductive.', 'Setiap upaya mengukur kebahagiaan pada dasarnya menyederhanakan secara berlebihan.'], ['The orchestra delivered an impeccable performance.', 'Orkestra itu tampil tanpa cela.'],
    ['Their resilience in the face of adversity was remarkable.', 'Ketangguhan mereka menghadapi kesulitan sungguh luar biasa.'], ['The legislation was rushed through with scant debate.', 'Undang-undang itu disahkan terburu-buru dengan debat yang minim.'],
    ['The essay articulates a nuanced critique of consumerism.', 'Esai itu menyampaikan kritik bernuansa terhadap konsumerisme.'], ['The phenomenon defies easy explanation.', 'Fenomena itu sulit dijelaskan dengan mudah.'],
    ['He was adamant that the figures had been manipulated.', 'Dia bersikeras bahwa angka-angka itu telah dimanipulasi.'], ['The proliferation of fake news poses a formidable challenge.', 'Merebaknya berita palsu menimbulkan tantangan yang berat.'],
    ['Little did they know that the venture would transform the industry.', 'Mereka sama sekali tidak tahu usaha itu akan mengubah industri.'], ['The film eschews sentimentality in favor of stark realism.', 'Film itu menghindari sentimentalitas demi realisme yang lugas.'],
    ['The data lend credence to the hypothesis.', 'Data itu memberi kredibilitas pada hipotesis tersebut.'], ['The negotiations reached an impasse over funding.', 'Perundingan menemui jalan buntu soal pendanaan.'],
    ['An ephemeral trend rarely leaves a lasting legacy.', 'Tren sesaat jarang meninggalkan warisan yang abadi.'], ['The critique is incisive, if somewhat uncharitable.', 'Kritik itu tajam, meskipun agak kurang berbaik sangka.'],
    ['The court’s ruling set an important precedent.', 'Putusan pengadilan itu menetapkan preseden penting.'], ['The redundancy in the text obscures its central argument.', 'Pengulangan dalam teks itu mengaburkan argumen utamanya.'],
    ['He is a staunch advocate of academic freedom.', 'Dia pembela teguh kebebasan akademik.'], ['The narrative oscillates between hope and despair.', 'Narasinya berayun antara harapan dan keputusasaan.'],
    ['These concerns are by no means unfounded.', 'Kekhawatiran ini sama sekali bukan tanpa dasar.'], ['The ramifications of the decision are still unfolding.', 'Dampak lanjutan keputusan itu masih terus berkembang.'],
    ['She has an uncanny ability to anticipate market trends.', 'Dia punya kemampuan luar biasa mengantisipasi tren pasar.'], ['The policy is predicated on a flawed understanding of human behavior.', 'Kebijakan itu didasarkan pada pemahaman keliru tentang perilaku manusia.'],
    ['To dismiss the proposal outright would be short-sighted.', 'Menolak usulan itu mentah-mentah adalah pandangan yang picik.'], ['The poem’s imagery is hauntingly beautiful.', 'Citraan puisi itu indah sekaligus menghantui.'],
  ],
};
